
HButton=HControl.extend({componentName:"button",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}
this._29=[this.rect.width,this.rect.height];},setLabelHeightDiff:function(_6f){this._4w=_6f;return'';},setLabelWidthDiff:function(_6h){this._4x=_6h;return'';},onIdle:function(){if(this.drawn){var _h=this.rect.width;var _q=this.rect.height;if((_h!=this._29[0])||(_q!=this._29[1])){this._29[0]=_h;this._29[1]=_q;if(this.markupElemIds.label){var _4o=parseInt(_q+this._4w,10);prop_set(this.markupElemIds.label,'line-height',_4o+'px');if(is.ie6){var _79=parseInt(_h+this._4x,10);prop_set(this.markupElemIds.label,'height',_4o+'px');prop_set(this.markupElemIds.label,'width',_79+'px');}}}}},draw:function(){if(!this.drawn){this.drawRect();this._4w=0;this._4x=0;this.drawMarkup();}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}}}});HClickButton=HButton.extend({constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HClickButton]';this.setMouseDown(true);this.setMouseUp(true);this._19=false;this._1B=false;if(!this.isinherited){this.draw();}},focus:function(){if(!this._19&&!this._1B){this._1B=true;this._19=false;}
this.base();},blur:function(){if(!this._19){this._1B=false;}
this.base();},mouseDown:function(x,y,_U){if(this._1B){this._19=true;}
this.base(x,y,_U);},mouseUp:function(x,y,_U){if(this._1B&&this._19){this._19=false;this.click(x,y,_U);}
this.base(x,y,_U);},click:function(x,y,_U){this.setValue(this.value+1);if(this.action){this.action();}}});HToggleButton=HClickButton.extend({constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HToggleButton]';if(!this.isinherited){this.draw();}},click:function(x,y,_U){this.setValue(!this.value);},setValue:function(_7){if(null===_7||undefined===_7){_7=false;}
this.base(_7);},_70:function(){if(this.markupElemIds.control){var _9=elem_get(this.markupElemIds.control);this.toggleCSSClass(_9,HToggleButton.cssOn,this.value);this.toggleCSSClass(_9,HToggleButton.cssOff,!this.value);}},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}
if(this.markupElemIds.control){this._70();}}}},{cssOn:"on",cssOff:"off"});HStringView=HControl.extend({componentName:"stringview",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HStringView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(!this._0Y){this._0Y=this.bindDomElement("stringview"+this.elemId);}
if(this._0Y){elem_set(this._0Y,this.value);}}},stringElementId:function(){return this._0Y;},optimizeWidth:function(){if(this._0Y){var _6V=elem_get(this._0Y).cloneNode(true);var _2z=elem_add(_6V);prop_set(_2z,"visibility","hidden",true);elem_append(0,_2z);var _h=this.stringWidth(this.value,null,_2z);if(!isNaN(_h)){var _5r=prop_get_extra_width(this._0Y);this.resizeTo(_h+_5r,this.rect.height);}
elem_del(_2z);}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_6,_2){this._3C="textcontrol";if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HTextControl]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},die:function(){if(this.drawn){var _05=this._3C+this.elemId;Event.stopObserving(_05,'mousedown',this._2x);Event.stopObserving(_05,'mousemove',this._2x);Event.stopObserving(_05,'focus',this._3M);Event.stopObserving(_05,'blur',this._46);}
this.base();},setEnabled:function(_7){this.base(_7);if(this._0b){elem_get(this._0b).disabled=(!this.enabled);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._0b=this.bindDomElement(this._3C+this.elemId);if(this._0b){elem_get(this._0b).setAttribute("autocomplete","off");this.setEnabled(this.enabled);}
this._6I();this.drawn=true;}
this.refresh();},_6I:function(){var _05=this._3C+this.elemId;this._2x=function(_5N){HControl.stopPropagation(_5N);};Event.observe(_05,'mousedown',this._2x,false);Event.observe(_05,'mousemove',this._2x,false);var _t=this;this._3M=function(event){HEventManager.changeActiveControl(_t);};Event.observe(_05,'focus',this._3M,false);this._46=function(event){_t._72();HEventManager.changeActiveControl(null);};Event.observe(_05,'blur',this._46,false);},refresh:function(){this.base();if(this._0b){if(elem_get(this._0b).value!=this.value){elem_get(this._0b).value=this.value;}}},onIdle:function(){if(this.active){this._72();}},_72:function(){if(this.drawn){if(elem_get(this._0b).value!=this.value){this.setValue(elem_get(this._0b).value);}}},lostActiveStatus:function(_O){if(this._0b){elem_get(this._0b).blur();}}});HTextArea=HTextControl.extend({componentName:"textarea",constructor:function(_1,_6,_2){this.base(_1,_6,_2);}});HSlider=HControl.extend({packageName:"sliders",componentName:"slider",constructor:function(_1,_6,_2){if(!_2){_2={};}
_2.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _B=Base.extend({minValue:0,maxValue:1});_B=_B.extend(_2);_2=new _B();if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HSlider]';this.refreshOnValueChange=false;this._4v='sliderknob';this._0g=false;if(!this.isinherited){this.draw();}},setValue:function(_4){if(_4<this.minValue){_4=this.minValue;}
if(_4>this.maxValue){_4=this.maxValue;}
this.base(_4);if(this._35){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._63();}
this.refresh();},startDrag:function(_5,_a){var _0=elem_get(this.elemId);var _4I=helmi.Element.getPageLocation(_0,true);this._6v=_4I[0];this._6w=_4I[1];this.doDrag(_5,_a);},endDrag:function(_5,_a){this.doDrag(_5,_a);},doDrag:function(_5,_a){_5-=this._6v;_a-=this._6w;_7s=this._0g?_a:_5;_4=this._6A(_7s);this.setValue(_4);},keyDown:function(_G){if((_G==Event.KEY_LEFT&&!this._0g)||(_G==Event.KEY_UP&&this._0g)){this._1J=true;this._2o(-0.05);}
else if((_G==Event.KEY_RIGHT&&!this._0g)||(_G==Event.KEY_DOWN&&this._0g)){this._1J=true;this._2o(0.05);}
else if(_G==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_G==Event.KEY_END){this.setValue(this.maxValue);}
else if(_G==Event.KEY_PAGEUP){this._1J=true;this._2o(-0.25);}
else if(_G==Event.KEY_PAGEDOWN){this._1J=true;this._2o(0.25);}},keyUp:function(_G){this._1J=false;},mouseWheel:function(_Y){var _1o;if(_Y>0){_1o=-0.05;}
else{_1o=0.05;}
_4=(this.maxValue-this.minValue)*_1o;this.setValue(this.value+_4);},_2o:function(_1o,_1j){if(!_1j){_1j=300;}
else if(_1j==300){_1j=50;}
if(this._1J&&this.active){_4=(this.maxValue-this.minValue)*_1o;this.setValue(this.value+_4);var _t=this;if(this._36){window.clearTimeout(this._36);this._36=null;}
this._36=window.setTimeout(function(){_t._2o(_1o,_1j);},_1j);}},_63:function(){this._35=this.bindDomElement(this._4v+this.elemId);this.drawKnobPos();},_3G:function(){var _9=elem_get(this._35);if(this._0g){_4R=this.rect.height-parseInt(_9.offsetHeight,10);}else{_4R=this.rect.width-parseInt(_9.offsetWidth,10);}
_34=_4R*((this.value-this.minValue)/(this.maxValue-this.minValue));_3o=parseInt(_34,10)+'px';return _3o;},_6A:function(_4C){_0F=this._0g?(_4C):(_4C);if(_0F<0){_0F=0;}
if(this._0g){if(_0F>this.rect.height){_0F=this.rect.height;}
return this.minValue+((_0F/this.rect.height)*(this.maxValue-this.minValue));}else{if(_0F>this.rect.width){_0F=this.rect.width;}
return this.minValue+((_0F/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_7A=this._0g?'top':'left';_3m=this._3G();prop_set(this._35,_7A,_3m);}});HVSlider=HSlider.extend({packageName:"sliders",componentName:"vslider",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HVSlider]';this._4v='vsliderknob';this._0g=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
if(!_2){_2={};}
var _B=Base.extend({value:0,minValue:0,maxValue:100});_B=_B.extend(_2);_2=new _B();this.value=_2.value;this.minValue=_2.minValue;this.maxValue=_2.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._3k='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_01){this.progressFrameHeight=_01;},setProgressFrameNum:function(_2q){this.progressFrames=_2q;},setValue:function(_4){this.base(_4);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _01=this.currProgressFrame*this.progressFrameHeight;prop_set(this.progressbarElemId,'background-position','0px -'+_01+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._31();}},_31:function(){this.progressbarElemId=this.bindDomElement(this._3k+this.elemId);this.drawProgress();},_3G:function(){var _34=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _3o=parseInt(Math.round(_34),10)+'px';return _3o;},drawProgress:function(){if(this.progressbarElemId){var _3m=this._3G();prop_set(this.progressbarElemId,'width',_3m);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
if(!_2){_2={};}
var _B=Base.extend({value:0,interval:20});_B=_B.extend(_2);_2=new _B();this.type='[HProgressIndicator]';this._3k='progressmark';this.interval=_2.interval;this.value=_2.value;this._1b=null;if(!this.isinherited){this.draw();}},setValue:function(_4){if(this._3j){if(_4==true&&!this._1b){var temp=this;this._1b=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._1b);this._1b=null;}}},die:function(){this.base();if(this._1b){clearInterval(this._1b);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._31();}},_31:function(){this._3j=this.bindDomElement(this._3k+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._3j){prop_set(this._3j,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({componentName:"imageview",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"blank.gif";}
this.type='[HImageView]';if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(!this._0s){this._0s=this.bindDomElement(HImageView._5e+this.elemId);}
if(this._0s){elem_get(this._0s).src=this.value;}}},scaleToFit:function(){if(this._0s){prop_set(this._0s,'width',this.rect.width+'px');prop_set(this._0s,'height',this.rect.height+'px');}},scaleToOriginal:function(){if(this._0s){prop_set(this._0s,'width','auto');prop_set(this._0s,'height','auto');}}},{_5e:"imageview"});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_6,_2){_2=new(Base.extend({vertical:false}).extend(_2));if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HSplitView]';this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a,_K){if(!_K){return;}
_5-=this.pageX();_a-=this.pageY();var _N=this.dividers.indexOfObject(_K);this._0G=new HPoint(_5,_a);this._2r=new HPoint(_5,_a);this._C=this._0G.subtract(_K.rect.leftTop);this._0c=this.splitviews[_N];this._P=this.splitviews[_N+1];this._K=_K;if(this.vertical==false){this._2i=this._0c.rect.top;this._2j=this._P.rect.bottom-this.dividerWidth;}else{this._2i=this._0c.rect.left;this._2j=this._P.rect.right-this.dividerWidth;}},doDrag:function(_5,_a,_K){if(!_K){return;}
_5-=this.pageX();_a-=this.pageY();if(this.vertical==false){var _l=_a-this._C.y;if(_l<this._2i||_l>this._2j){return;}
this._0c.rect.setHeight(_l);this._0c.rect.updateSecondaryValues();this._0c.setStyle('height',this._0c.rect.height+'px',true);this._K.rect.setTop(_l);this._K.rect.updateSecondaryValues();this._K.setStyle('top',this._K.rect.top+'px',true);this._P.rect.setTop(_l+this.dividerWidth);this._P.rect.updateSecondaryValues();this._P.setStyle('top',this._P.rect.top+'px',true);this._P.setStyle('height',this._P.rect.height+'px',true);}else{var _l=_5-this._C.x;if(_l<this._2i||_l>this._2j){return;}
this._0c.rect.setRight(_l);this._0c.rect.updateSecondaryValues();this._0c.setStyle('width',this._0c.rect.width+'px',true);this._K.rect.setLeft(_l);this._K.rect.updateSecondaryValues();this._K.setStyle('left',this._K.rect.left+'px',true);this._P.rect.setLeft(_l+this.dividerWidth);this._P.rect.updateSecondaryValues();this._P.setStyle('left',this._P.rect.left+'px',true);this._P.setStyle('width',this._P.rect.width+'px',true);}},endDrag:function(_5,_a,_K){this.doDrag(_5,_a);delete this._0G;delete this._2r;delete this._C;delete this._0c;delete this._P;delete this._K;delete this._2i;delete this._2j;},addSplitViewItem:function(_0E,_N){if(_N!==undefined){this.splitviews.splice(_N,0,_0E);}else{this.splitviews.push(_0E);}},removeSplitViewItem:function(_0E){if(typeof _0E=="object"){var _N=this.splitviews.indexOfObject(_0E);if(_N!=-1){this.splitviews.splice(_N,1);_0E.die();this.dividers.splice(_N,1);this.dividers[_N].die();}}},setVertical:function(_7){this.vertical=_7;this.options.vertical=_7;},adjustViews:function(){var _0p=this.splitviews.length;var _2p;var _1i;var _2v;var _1l;if(this.vertical==false){_2p=this.rect.height-this.dividerWidth*(_0p-1);_1i=0;for(var i=0;i<_0p;i++){_1i+=this.splitviews[i].rect.height;}
_2v=_2p/_1i;_1l=0;for(var i=0;i<_0p;i++){var _02=this.splitviews[i];var _1g=_02.rect.height*_2v;if(i==_0p-1){_1g=Math.floor(_1g);}else{_1g=Math.ceil(_1g);}
_02.rect.offsetTo(0,_1l);_02.rect.setSize(this.rect.width,_1g);_02.draw();_1l+=_1g+this.dividerWidth;}}else{_2p=this.rect.width-this.dividerWidth*(_0p-1);_1i=0;for(var i=0;i<_0p;i++){_1i+=this.splitviews[i].rect.width;}
_2v=_2p/_1i;_1l=0;for(var i=0;i<_0p;i++){var _02=this.splitviews[i];var _1h=_02.rect.width*_2v;if(i==_0p-1){_1h=Math.floor(_1h);}else{_1h=Math.ceil(_1h);}
_02.rect.offsetTo(_1l,0);_02.rect.setSize(_1h,this.rect.height);_02.draw();_1l+=_1h+this.dividerWidth;}}
this.draw();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){this.base();if(this.drawn){var _0p=this.splitviews.length;var _S;for(var i=0;i<(_0p-1);i++){_S=new HRect(this.splitviews[i].rect);if(!this.vertical){_S.offsetTo(_S.left,_S.bottom);_S.setHeight(this.dividerWidth);}else{_S.offsetTo(_S.right,_S.top);_S.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_S,this);}else{var _02=this.dividers[i];_02.rect.offsetTo(_S.left,_S.top);_02.rect.setSize(_S.width,_S.height);_02.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_6,_2){if(!_2){_2={};}
_2.events={mouseDown:true,keyDown:true,mouseWheel:true};var _B=Base.extend({minValue:0,value:0,interval:500});_B=_B.extend(_2);_2=new _B();if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.interval=_2.interval;this.type='[HStepper]';this._7y="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_4){_4--;_4=(_4<this.minValue)?this.maxValue:_4;this.setValue(_4);},stepDown:function(_4){_4++;_4=(_4>this.maxValue)?this.minValue:_4;this.setValue(_4);},mouseDown:function(_5,_a,_0R){this.setMouseUp(true);var temp=this;if(_a<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_5,_a,_0R){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_G){this.setKeyUp(true);var temp=this;if(_G==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_G==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_G){clearInterval(this.counter);},mouseWheel:function(_Y){if(_Y>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HRadiobutton=HToggleButton.extend({componentName:"radiobutton",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HRadiobutton]';if(!this.isinherited){this.draw();}},setValueMatrix:function(_5p){this.valueMatrix=_5p;this.valueMatrixIndex=this.valueMatrix.addValue(this.valueObj,this.value);},click:function(x,y,_U){this.base(x,y,_U);if(undefined!==this.valueMatrix&&this.valueMatrix instanceof HValueMatrix){this.valueMatrix.setValue(this.valueMatrixIndex);}}});HRadioButton=HRadiobutton;HPasswordControl=HTextControl.extend({componentName:"passwordcontrol",constructor:function(_1,_6,_2){this.base(_1,_6,_2);}});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a){this.parent.startDrag(_5,_a,this);},doDrag:function(_5,_a){this.parent.doDrag(_5,_a,this);},endDrag:function(_5,_a){this.parent.endDrag(_5,_a,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HCheckbox=HToggleButton.extend({componentName:"checkbox",constructor:function(_1,_6,_2){if(this.isinherited){this.base(_1,_6,_2);}
else{this.isinherited=true;this.base(_1,_6,_2);this.isinherited=false;}
this.type='[HCheckbox]';if(!this.isinherited){this.draw();}}});