
HButton=HControl.extend({componentName:"button",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}
this._29=[this.rect.width,this.rect.height];},setLabelHeightDiff:function(_6f){this._4s=_6f;return'';},setLabelWidthDiff:function(_6h){this._4t=_6h;return'';},onIdle:function(){if(this.drawn){var _h=this.rect.width;var _r=this.rect.height;if((_h!=this._29[0])||(_r!=this._29[1])){this._29[0]=_h;this._29[1]=_r;if(this.markupElemIds.label){var _4i=parseInt(_r+this._4s,10);prop_set(this.markupElemIds.label,'line-height',_4i+'px');if(is.ie6){var _72=parseInt(_h+this._4t,10);prop_set(this.markupElemIds.label,'height',_4i+'px');prop_set(this.markupElemIds.label,'width',_72+'px');}}}}},draw:function(){if(!this.drawn){this.drawRect();this._4s=0;this._4t=0;this.drawMarkup();}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}}}});HClickButton=HButton.extend({constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HClickButton]';this.setMouseDown(true);this.setMouseUp(true);this._1d=false;this._1D=false;if(!this.isinherited){this.draw();}},focus:function(){if(!this._1d&&!this._1D){this._1D=true;this._1d=false;}
this.base();},blur:function(){if(!this._1d){this._1D=false;}
this.base();},mouseDown:function(x,y,_T){if(this._1D){this._1d=true;}
this.base(x,y,_T);},mouseUp:function(x,y,_T){if(this._1D&&this._1d){this._1d=false;this.click(x,y,_T);}
this.base(x,y,_T);},click:function(x,y,_T){this.setValue(this.value+1);if(this.action){this.action();}}});HToggleButton=HClickButton.extend({constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HToggleButton]';if(!this.isinherited){this.draw();}},click:function(x,y,_T){this.setValue(!this.value);},setValue:function(_7){if(null===_7||undefined===_7){_7=false;}
this.base(_7);},_6T:function(){if(this.markupElemIds.control){var _9=elem_get(this.markupElemIds.control);this.toggleCSSClass(_9,HToggleButton.cssOn,this.value);this.toggleCSSClass(_9,HToggleButton.cssOff,!this.value);}},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}
if(this.markupElemIds.control){this._6T();}}}},{cssOn:"on",cssOff:"off"});HStringView=HControl.extend({componentName:"stringview",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HStringView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(!this._11){this._11=this.bindDomElement("stringview"+this.elemId);}
if(this._11){elem_set(this._11,this.value);}}},stringElementId:function(){return this._11;},optimizeWidth:function(){if(this._11){var _6P=elem_get(this._11).cloneNode(true);var _2y=elem_add(_6P);prop_set(_2y,"visibility","hidden",true);elem_append(0,_2y);var _h=this.stringWidth(this.value,null,_2y);if(!isNaN(_h)){var _5t=prop_get_extra_width(this._11);this.resizeTo(_h+_5t,this.rect.height);}
elem_del(_2y);}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_2,_6,_3){this._3v="textcontrol";if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HTextControl]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},die:function(){if(this.drawn){var _04=this._3v+this.elemId;Event.stopObserving(_04,'mousedown',this._2v);Event.stopObserving(_04,'mousemove',this._2v);Event.stopObserving(_04,'focus',this._3F);Event.stopObserving(_04,'blur',this._3Z);}
this.base();},setEnabled:function(_7){this.base(_7);if(this._0a){elem_get(this._0a).disabled=(!this.enabled);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._0a=this.bindDomElement(this._3v+this.elemId);if(this._0a){elem_get(this._0a).setAttribute("autocomplete","off");this.setEnabled(this.enabled);}
this._6C();this.drawn=true;}
this.refresh();},_6C:function(){var _04=this._3v+this.elemId;this._2v=function(_5P){HControl.stopPropagation(_5P);};Event.observe(_04,'mousedown',this._2v,false);Event.observe(_04,'mousemove',this._2v,false);var _t=this;this._3F=function(event){HEventManager.changeActiveControl(_t);};Event.observe(_04,'focus',this._3F,false);this._3Z=function(event){_t._6V();HEventManager.changeActiveControl(null);};Event.observe(_04,'blur',this._3Z,false);},refresh:function(){this.base();if(this._0a){if(elem_get(this._0a).value!=this.value){elem_get(this._0a).value=this.value;}}},onIdle:function(){if(this.active){this._6V();}},_6V:function(){if(this.drawn){if(elem_get(this._0a).value!=this.value){this.setValue(elem_get(this._0a).value);}}},lostActiveStatus:function(_N){if(this._0a){elem_get(this._0a).blur();}}});HTextArea=HTextControl.extend({componentName:"textarea",constructor:function(_2,_6,_3){this.base(_2,_6,_3);}});HSlider=HControl.extend({packageName:"sliders",componentName:"slider",constructor:function(_2,_6,_3){if(!_3){_3={};}
_3.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _B=Base.extend({minValue:0,maxValue:1});_B=_B.extend(_3);_3=new _B();if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HSlider]';this.refreshOnValueChange=false;this._4r='sliderknob';this._0f=false;if(!this.isinherited){this.draw();}},setValue:function(_4){if(_4<this.minValue){_4=this.minValue;}
if(_4>this.maxValue){_4=this.maxValue;}
this.base(_4);if(this._32){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._64();}
this.refresh();},startDrag:function(_5,_a){var _0=elem_get(this.elemId);var _4K=helmi.Element.getPageLocation(_0,true);this._6p=_4K[0];this._6q=_4K[1];this.doDrag(_5,_a);},endDrag:function(_5,_a){this.doDrag(_5,_a);},doDrag:function(_5,_a){_5-=this._6p;_a-=this._6q;_7q=this._0f?_a:_5;_4=this._6u(_7q);this.setValue(_4);},keyDown:function(_G){if((_G==Event.KEY_LEFT&&!this._0f)||(_G==Event.KEY_UP&&this._0f)){this._1L=true;this._2m(-0.05);}
else if((_G==Event.KEY_RIGHT&&!this._0f)||(_G==Event.KEY_DOWN&&this._0f)){this._1L=true;this._2m(0.05);}
else if(_G==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_G==Event.KEY_END){this.setValue(this.maxValue);}
else if(_G==Event.KEY_PAGEUP){this._1L=true;this._2m(-0.25);}
else if(_G==Event.KEY_PAGEDOWN){this._1L=true;this._2m(0.25);}},keyUp:function(_G){this._1L=false;},mouseWheel:function(_Y){var _1r;if(_Y>0){_1r=-0.05;}
else{_1r=0.05;}
_4=(this.maxValue-this.minValue)*_1r;this.setValue(this.value+_4);},_2m:function(_1r,_1n){if(!_1n){_1n=300;}
else if(_1n==300){_1n=50;}
if(this._1L&&this.active){_4=(this.maxValue-this.minValue)*_1r;this.setValue(this.value+_4);var _t=this;if(this._33){window.clearTimeout(this._33);this._33=null;}
this._33=window.setTimeout(function(){_t._2m(_1r,_1n);},_1n);}},_64:function(){this._32=this.bindDomElement(this._4r+this.elemId);this.drawKnobPos();},_3z:function(){var _9=elem_get(this._32);if(this._0f){_4T=this.rect.height-parseInt(_9.offsetHeight,10);}else{_4T=this.rect.width-parseInt(_9.offsetWidth,10);}
_31=_4T*((this.value-this.minValue)/(this.maxValue-this.minValue));_3l=parseInt(_31,10)+'px';return _3l;},_6u:function(_4y){_0F=this._0f?(_4y):(_4y);if(_0F<0){_0F=0;}
if(this._0f){if(_0F>this.rect.height){_0F=this.rect.height;}
return this.minValue+((_0F/this.rect.height)*(this.maxValue-this.minValue));}else{if(_0F>this.rect.width){_0F=this.rect.width;}
return this.minValue+((_0F/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_7E=this._0f?'top':'left';_3j=this._3z();prop_set(this._32,_7E,_3j);}});HVSlider=HSlider.extend({packageName:"sliders",componentName:"vslider",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HVSlider]';this._4r='vsliderknob';this._0f=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
if(!_3){_3={};}
var _B=Base.extend({value:0,minValue:0,maxValue:100});_B=_B.extend(_3);_3=new _B();this.value=_3.value;this.minValue=_3.minValue;this.maxValue=_3.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._3h='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_02){this.progressFrameHeight=_02;},setProgressFrameNum:function(_2o){this.progressFrames=_2o;},setValue:function(_4){this.base(_4);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _02=this.currProgressFrame*this.progressFrameHeight;prop_set(this.progressbarElemId,'background-position','0px -'+_02+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._2Y();}},_2Y:function(){this.progressbarElemId=this.bindDomElement(this._3h+this.elemId);this.drawProgress();},_3z:function(){var _31=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _3l=parseInt(Math.round(_31),10)+'px';return _3l;},drawProgress:function(){if(this.progressbarElemId){var _3j=this._3z();prop_set(this.progressbarElemId,'width',_3j);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
if(!_3){_3={};}
var _B=Base.extend({value:0,interval:20});_B=_B.extend(_3);_3=new _B();this.type='[HProgressIndicator]';this._3h='progressmark';this.interval=_3.interval;this.value=_3.value;this._1e=null;if(!this.isinherited){this.draw();}},setValue:function(_4){if(this._3g){if(_4==true&&!this._1e){var temp=this;this._1e=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._1e);this._1e=null;}}},die:function(){this.base();if(this._1e){clearInterval(this._1e);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._2Y();}},_2Y:function(){this._3g=this.bindDomElement(this._3h+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._3g){prop_set(this._3g,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({componentName:"imageview",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"blank.gif";}
this.type='[HImageView]';if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(!this._0s){this._0s=this.bindDomElement(HImageView._5e+this.elemId);}
if(this._0s){elem_get(this._0s).src=this.value;}}},scaleToFit:function(){if(this._0s){prop_set(this._0s,'width',this.rect.width+'px');prop_set(this._0s,'height',this.rect.height+'px');}},scaleToOriginal:function(){if(this._0s){prop_set(this._0s,'width','auto');prop_set(this._0s,'height','auto');}}},{_5e:"imageview"});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_2,_6,_3){_3=new(Base.extend({vertical:false}).extend(_3));if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HSplitView]';this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a,_K){if(!_K){return;}
_5-=this.pageX();_a-=this.pageY();var _M=this.dividers.indexOfObject(_K);this._0H=new HPoint(_5,_a);this._2p=new HPoint(_5,_a);this._C=this._0H.subtract(_K.rect.leftTop);this._0b=this.splitviews[_M];this._O=this.splitviews[_M+1];this._K=_K;if(this.vertical==false){this._2g=this._0b.rect.top;this._2h=this._O.rect.bottom-this.dividerWidth;}else{this._2g=this._0b.rect.left;this._2h=this._O.rect.right-this.dividerWidth;}},doDrag:function(_5,_a,_K){if(!_K){return;}
_5-=this.pageX();_a-=this.pageY();if(this.vertical==false){var _l=_a-this._C.y;if(_l<this._2g||_l>this._2h){return;}
this._0b.rect.setHeight(_l);this._0b.rect.updateSecondaryValues();this._0b.setStyle('height',this._0b.rect.height+'px',true);this._K.rect.setTop(_l);this._K.rect.updateSecondaryValues();this._K.setStyle('top',this._K.rect.top+'px',true);this._O.rect.setTop(_l+this.dividerWidth);this._O.rect.updateSecondaryValues();this._O.setStyle('top',this._O.rect.top+'px',true);this._O.setStyle('height',this._O.rect.height+'px',true);}else{var _l=_5-this._C.x;if(_l<this._2g||_l>this._2h){return;}
this._0b.rect.setRight(_l);this._0b.rect.updateSecondaryValues();this._0b.setStyle('width',this._0b.rect.width+'px',true);this._K.rect.setLeft(_l);this._K.rect.updateSecondaryValues();this._K.setStyle('left',this._K.rect.left+'px',true);this._O.rect.setLeft(_l+this.dividerWidth);this._O.rect.updateSecondaryValues();this._O.setStyle('left',this._O.rect.left+'px',true);this._O.setStyle('width',this._O.rect.width+'px',true);}},endDrag:function(_5,_a,_K){this.doDrag(_5,_a);delete this._0H;delete this._2p;delete this._C;delete this._0b;delete this._O;delete this._K;delete this._2g;delete this._2h;},addSplitViewItem:function(_0D,_M){if(_M!==undefined){this.splitviews.splice(_M,0,_0D);}else{this.splitviews.push(_0D);}},removeSplitViewItem:function(_0D){if(typeof _0D=="object"){var _M=this.splitviews.indexOfObject(_0D);if(_M!=-1){this.splitviews.splice(_M,1);_0D.die();this.dividers.splice(_M,1);this.dividers[_M].die();}}},setVertical:function(_7){this.vertical=_7;this.options.vertical=_7;},adjustViews:function(){var _0p=this.splitviews.length;var _2n;var _1m;var _2t;var _1p;if(this.vertical==false){_2n=this.rect.height-this.dividerWidth*(_0p-1);_1m=0;for(var i=0;i<_0p;i++){_1m+=this.splitviews[i].rect.height;}
_2t=_2n/_1m;_1p=0;for(var i=0;i<_0p;i++){var _03=this.splitviews[i];var _1k=_03.rect.height*_2t;if(i==_0p-1){_1k=Math.floor(_1k);}else{_1k=Math.ceil(_1k);}
_03.rect.offsetTo(0,_1p);_03.rect.setSize(this.rect.width,_1k);_03.draw();_1p+=_1k+this.dividerWidth;}}else{_2n=this.rect.width-this.dividerWidth*(_0p-1);_1m=0;for(var i=0;i<_0p;i++){_1m+=this.splitviews[i].rect.width;}
_2t=_2n/_1m;_1p=0;for(var i=0;i<_0p;i++){var _03=this.splitviews[i];var _1l=_03.rect.width*_2t;if(i==_0p-1){_1l=Math.floor(_1l);}else{_1l=Math.ceil(_1l);}
_03.rect.offsetTo(_1p,0);_03.rect.setSize(_1l,this.rect.height);_03.draw();_1p+=_1l+this.dividerWidth;}}
this.draw();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){this.base();if(this.drawn){var _0p=this.splitviews.length;var _R;for(var i=0;i<(_0p-1);i++){_R=new HRect(this.splitviews[i].rect);if(!this.vertical){_R.offsetTo(_R.left,_R.bottom);_R.setHeight(this.dividerWidth);}else{_R.offsetTo(_R.right,_R.top);_R.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_R,this);}else{var _03=this.dividers[i];_03.rect.offsetTo(_R.left,_R.top);_03.rect.setSize(_R.width,_R.height);_03.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_2,_6,_3){if(!_3){_3={};}
_3.events={mouseDown:true,keyDown:true,mouseWheel:true};var _B=Base.extend({minValue:0,value:0,interval:500});_B=_B.extend(_3);_3=new _B();if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.interval=_3.interval;this.type='[HStepper]';this._7C="stepperlabel";this.border=((_2.bottom-_2.top)/2+_2.top);if(!this.isinherited){this.draw();}},stepUp:function(_4){_4--;_4=(_4<this.minValue)?this.maxValue:_4;this.setValue(_4);},stepDown:function(_4){_4++;_4=(_4>this.maxValue)?this.minValue:_4;this.setValue(_4);},mouseDown:function(_5,_a,_0U){this.setMouseUp(true);var temp=this;if(_a<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_5,_a,_0U){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_G){this.setKeyUp(true);var temp=this;if(_G==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_G==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_G){clearInterval(this.counter);},mouseWheel:function(_Y){if(_Y>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HRadiobutton=HToggleButton.extend({componentName:"radiobutton",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HRadiobutton]';if(!this.isinherited){this.draw();}},setValueMatrix:function(_5r){this.valueMatrix=_5r;this.valueMatrixIndex=this.valueMatrix.addValue(this.valueObj,this.value);},click:function(x,y,_T){this.base(x,y,_T);if(undefined!==this.valueMatrix&&this.valueMatrix instanceof HValueMatrix){this.valueMatrix.setValue(this.valueMatrixIndex);}}});HRadioButton=HRadiobutton;HPasswordControl=HTextControl.extend({componentName:"passwordcontrol",constructor:function(_2,_6,_3){this.base(_2,_6,_3);}});HDivider=HControl.extend({componentName:"divider",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a){this.parent.startDrag(_5,_a,this);},doDrag:function(_5,_a){this.parent.doDrag(_5,_a,this);},endDrag:function(_5,_a){this.parent.endDrag(_5,_a,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HCheckbox=HToggleButton.extend({componentName:"checkbox",constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HCheckbox]';if(!this.isinherited){this.draw();}}});