
HButton=HControl.extend({componentName:"button",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}
this._drawnSize=[this.rect.width,this.rect.height];},setLabelHeightDiff:function(_newHeightDiff){this._labelHeightDiff=_newHeightDiff;return'';},setLabelWidthDiff:function(_newWidthDiff){this._labelWidthDiff=_newWidthDiff;return'';},onIdle:function(){if(this.drawn){var Hf=this.rect.width;var HM=this.rect.height;if((Hf!=this._drawnSize[0])||(HM!=this._drawnSize[1])){this._drawnSize[0]=Hf;this._drawnSize[1]=HM;if(this.markupElemIds.label){var _heightDiff=parseInt(HM+this._labelHeightDiff,10);prop_set(this.markupElemIds.label,'line-height',_heightDiff+'px');if(is.ie6){var _widthDiff=parseInt(Hf+this._labelWidthDiff,10);prop_set(this.markupElemIds.label,'height',_heightDiff+'px');prop_set(this.markupElemIds.label,'width',_widthDiff+'px');}}}}},draw:function(){if(!this.drawn){this.drawRect();this._labelHeightDiff=0;this._labelWidthDiff=0;this.drawMarkup();}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}}}});HClickButton=HButton.extend({constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HClickButton]';this.setMouseDown(true);this.setMouseUp(true);this.H1B=false;this.H0X=false;if(!this.isinherited){this.draw();}},focus:function(){if(!this.H1B&&!this.H0X){this.H0X=true;this.H1B=false;}
this.base();},blur:function(){if(!this.H1B){this.H0X=false;}
this.base();},mouseDown:function(x,y,HW){if(this.H0X){this.H1B=true;}
this.base(x,y,HW);},mouseUp:function(x,y,HW){if(this.H0X&&this.H1B){this.H1B=false;this.click(x,y,HW);}
this.base(x,y,HW);},click:function(x,y,HW){this.setValue(this.value+1);if(this.action){this.action();}}});HToggleButton=HClickButton.extend({constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HToggleButton]';if(!this.isinherited){this.draw();}},click:function(x,y,HW){this.setValue(!this.value);},setValue:function(Hh){if(null===Hh||undefined===Hh){Hh=false;}
this.base(Hh);},_updateToggleState:function(){if(this.markupElemIds.control){var Hc=elem_get(this.markupElemIds.control);this.toggleCSSClass(Hc,HToggleButton.cssOn,this.value);this.toggleCSSClass(Hc,HToggleButton.cssOff,!this.value);}},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}
if(this.markupElemIds.control){this._updateToggleState();}}}},{cssOn:"on",cssOff:"off"});HImageButton=HControl.extend({componentName:"imagebutton",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.styleButtonDefaults=new(Base.extend({image:this.getThemeGfxPath()+"blank.gif",alternateImage:""}).extend(H1));this.H0z=this.getThemeGfxPath()+this.styleButtonDefaults.image;this.H4t=this.getThemeGfxPath()+this.styleButtonDefaults.alternateImage;this.type='[HImageButton]';this.preserveTheme=true;this.setMouseUp(true);if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},_updateImageState:function(){if(!this.value){elem_get(this.H07).src=this.H0z;}else{if(this.H4t){elem_get(this.H07).src=this.H4t;}}},refresh:function(){if(this.drawn){this.base();if(!this.H07){this.H07=this.bindDomElement(HImageButton.H2v+this.elemId);}
if(this.H07){this._updateImageState();}}},mouseUp:function(H8,H9,H03){this.setValue(!this.value);}},{H2v:"imagebutton"});