
Date.prototype.getWeek=function(){var Hr=this.getFullYear();var H63=new Date(Hr,0,1);var H0I=H63.getDay();var H64=((Date.UTC(Hr,this.getMonth(),this.getDate())-
Date.UTC(Hr,0,1))/(1000*60*60*24));if(H0I==0){H0I=6;}else{H0I--;}
var H65=H64-(7-H0I);var H4o=Math.floor(H65/7)+1;if(0<=H0I&&H0I<=3){H4o+=1;}
H3m=H4o;if(H3m==53){if(H0I==3||((H0I==2||H0I==3)&&((Hr%4==0&&Hr%100!=0)||Hr%400==0))){}else{H3m=1;}}
return H3m;}
Date.prototype.getMonthLength=function(){var Hz=this.getMonth();var Hr=this.getFullYear();var H62=[31,28,31,30,31,30,31,31,30,31,30,31];if(Hz==1&&((Hr%4==0&&Hr%100!=0)||Hr%400==0)){return 29;}else{return H62[Hz];}}
HDateValue=HValue.extend({constructor:function(H6,H3){this.validate(H3);this._dateFormat="";this._timezone=2;this.base(H6,H3);this.type='[HDateValue]';},validate:function(H3){},set:function(H3){this.base(H3);},getYear:function(){var HV=this._utcToLocal();return HV.getFullYear();},getMonth:function(){var HV=this._utcToLocal();return HV.getMonth()+1;},getWeek:function(){var HV=this._utcToLocal();return HV.getWeek();},getMDay:function(){var HV=this._utcToLocal();return HV.getDate();},getHour:function(){var HV=this._utcToLocal();return HV.getHours();},_utcToLocal:function(){var _localTime=this.value.getTime();var _localOffset=this.value.getTimezoneOffset()*60000;var _utc=_localTime+_localOffset;var HV=new Date(_utc+(this._timezone*3600000));return HV;},getMinute:function(){var HV=this._utcToLocal();return HV.getUTCMinutes();},getSecond:function(){var HV=this._utcToLocal();return HV.getUTCSeconds();},getMilliSecond:function(){var HV=this._utcToLocal();return HV.getUTCMilliseconds();},getTimeZone:function(){return this._timezone;},setYear:function(_yearNum,_monthNum,_mdayNum){if(_monthNum){_monthNum-=1;}
this.value.setFullYear(_yearNum,_monthNum,_mdayNum);this.base(this.value);},setMonth:function(_monthNum,_mdayNum){this.value.setMonth(_monthNum-1,_mdayNum);this.base(this.value);},setMDay:function(_mdayNum){this.value.setDate(_mdayNum);this.base(this.value);},setHour:function(_hourNum,_minuteNum,_secondNum,_msNum){this.value.setHours(_hourNum,_minuteNum,_secondNum,_msNum);this.base(this.value);},setMinute:function(_minuteNum,_secondNum,_msNum){this.value.setMinutes(_minuteNum,_secondNum,_msNum);this.base(this.value);},setSecond:function(_secondNum,_msNum){this.value.setSeconds(_secondNum,_msNum);this.base(this.value);},setTimeZone:function(_theTimeZoneValue){this._timezone=_theTimeZoneValue;},setDateFormat:function(_reprString){this._dateFormat=_reprString;},toDateString:function(){var _monthNames=["January","February","March","April","May","June","July","August","September","October","November","December"];var _abbpreviatedMonthNames=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];var _dateString=this._dateFormat;var _stringArray=[""];var Hb=0;var ch="";var Hu=this.getMDay().toString();var Hz=this.getMonth().toString();var Hr=this.getYear().toString();var _year2Digits=(Hr.length==1?"0"+Hr:(Hr.charAt(Hr.length-2)+Hr.charAt(Hr.length-1)));var _24hour=this.getHour().toString();var _hour=this.getHour();var _12hour=(_hour>12)?_hour-12:_hour;_12hour=(_12hour==0)?12:_12hour;var _minute=this.getMinute().toString();var _second=this.getSecond().toString();var _timezone=this.getTimeZone();var _timezoneS=_timezone.toString();var _milliseconds=this.getHour()*60*60*1000+
this.getMinute()*60*1000+
this.getSecond()*1000+
this.getMilliSecond();var _designator=(0<_milliseconds&&_milliseconds<=12*60*60*1000)?"AM":"PM";var regexpArray=[[/dd/g,(Hu.length==1?"0":"")+Hu],[/d/g,Hu],[/MMMM/g,"'"+_monthNames[parseInt(Hz)-1]+"'"],[/MMM/g,"'"+_abbpreviatedMonthNames[parseInt(Hz)-1]+"'"],[/MM/g,(Hz.length==1?"0":"")+Hz],[/M/g,Hz],[/yyyy/g,Hr],[/yy/g,_year2Digits],[/y/g,parseInt(_year2Digits)],[/HH/g,(_24hour.length==1?"0":"")+_24hour],[/H/g,_24hour],[/hh/g,(_12hour.length==1?"0":"")+_12hour],[/h/g,_12hour],[/mm/g,(_minute.length==1?"0":"")+_minute],[/m/g,_minute],[/ss/g,(_second.length==1?"0":"")+_second],[/s/g,_second],[/zz/g,((_timezone>0)?"+":"")+(_timezoneS.length==1?"0":"")+_timezone],[/z/g,((_timezone>0)?"+":"")+_timezone],[/tt/g,"'"+_designator+"'"],[/t/g,"'"+_designator.charAt(0)+"'"]];for(var i=0;i<_dateString.length;i++){ch=_dateString.charAt(i);if(ch=="'"){if(i>0){Hb++;_stringArray[Hb]="";}
_stringArray[Hb]+=ch;i++;ch=_dateString.charAt(i);while(ch!="'"&&i<_dateString.length){_stringArray[Hb]+=ch;i++;ch=_dateString.charAt(i);}
if(i<_dateString.length){_stringArray[Hb]+=ch;Hb++;_stringArray[Hb]="";}}else{_stringArray[Hb]+=ch;}}
for(var i=0;i<_stringArray.length;i++){if(_stringArray[i].charAt(0)!="'"){for(var j=0;j<regexpArray.length;j++){_stringArray[i]=_stringArray[i].replace(regexpArray[j][0],regexpArray[j][1]);if(_stringArray[i].indexOf("'")>=0){var k=_stringArray[i].indexOf("'");var k2=_stringArray[i].indexOf("'",k+1);var _split=_stringArray[i];var _split1=_split.substring(0,k);var _split2=_split.substring(k,k2+1);var _split3=_split.substring(k2+1,_split.length);_stringArray.splice(i,1,_split1,_split2,_split3);i++;break;}}}}
return _stringArray.join("").replace(/'/g,"");},toXML:function(HT){var H0t=this.id;var _timezone=this.getTimeZone();_timezone=((_timezone>0)?"+":"")+_timezone;return'<date id="'+H0t+'" order="'+HT+'" epochvalue="'+this.value.getTime()+'" timezone="'+_timezone+'"><year>'+this.getYear()+'</year><month>'+this.getMonth()+'</month><mday>'+this.getMDay()+'</mday><hour>'+this.getHour()+'</hour><minute>'+this.getMinute()+'</minute><second>'+this.getSecond()+'</second></date>';}});HCalendarButton=HControl.extend({packageName:"calendar",componentName:"calendarbutton",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HCalendarButton]';this.H1a="calendarbuttonlabel";this.setMouseDown(true);this.setKeyDown(true);if(!this.isinherited){this.draw();}},keyDown:function(Hx){this.parent.keyDown(Hx);},H1L:function(){if(this.value==0){this.toggleCSSClass(elem_get(this.HG),"shaded",false);this.toggleCSSClass(elem_get(this.HG),HCalendarButton.cssOn,false);this.toggleCSSClass(elem_get(this.HG),HCalendarButton.cssOff,true);}else if(this.value==1){this.toggleCSSClass(elem_get(this.HG),"shaded",false);this.toggleCSSClass(elem_get(this.HG),HCalendarButton.cssOn,true);this.toggleCSSClass(elem_get(this.HG),HCalendarButton.cssOff,false);}else if(this.value==2){this.toggleCSSClass(elem_get(this.HG),"shaded",true);this.toggleCSSClass(elem_get(this.HG),HCalendarButton.cssOn,false);this.toggleCSSClass(elem_get(this.HG),HCalendarButton.cssOff,false);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){if(!this.HG){this.HG=elem_bind(this.H1a+this.elemId);}
if(this.HG){elem_set(this.HG,this.label);this.H1L();}
this.drawRect();}},setShaded:function(){this.value=0;},setSelected:function(){},setNormal:function(){},mouseDown:function(H8,H9,H03){this.parent.selectDay(this.index);}},{cssOn:"on",cssOff:"off"});HCalendarControl=HControl.extend({packageName:"calendar",componentName:"calendarcontrol",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HCalendarControl]';this.preserveTheme=true;var H4q=new Date().getFullYear();var H4r=[];for(var i=H4q-2;i<H4q+6;i++){H4r.push(i);}
this.Hl={hSpace:26,vSpace:20,selectToday:true,switchMonths:true,dayList:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],startDay:0,monthList:["January","February","March","April","May","June","July","August","September","October","November","December"],yearList:H4r,barHeight:25};this.H0D=false;if(!this.isinherited){this.draw();}},keyDown:function(Hx){if(Hx==Event.KEY_LEFT){this.previousDay();}
else if(Hx==Event.KEY_RIGHT){this.nextDay();}
else if(Hx==Event.KEY_UP){this.previousWeek();}
else if(Hx==Event.KEY_DOWN){this.nextWeek();}
else if(Hx==Event.KEY_PAGEUP){this.previousMonth();}
else if(Hx==Event.KEY_PAGEDOWN){this.nextMonth();}},previousDay:function(){var Hu=this.day-1;if(Hu<1){this.previousMonth();Hu=new Date(this.year,this.month,1).getMonthLength();}
this.setDate(this.year,this.month,Hu);},nextDay:function(){var Hu=this.day+1;if(Hu>new Date(this.year,this.month,1).getMonthLength()){this.nextMonth();Hu=1;}
this.setDate(this.year,this.month,Hu);},previousWeek:function(){var Hu=this.day-7;if(Hu<1){this.previousMonth();Hu=new Date(this.year,this.month,1).getMonthLength()+
(this.day-7);}
this.setDate(this.year,this.month,Hu);},nextWeek:function(){var Hu=this.day+7;var H4p=new Date(this.year,this.month,1).getMonthLength();if(Hu>H4p){this.nextMonth();Hu=Hu-H4p;}
this.setDate(this.year,this.month,Hu);},previousMonth:function(){var Hz=this.month-1;var Hr=this.year;if(Hz<0){Hr--;Hz=this.Hl.monthList.length-1;}
this.setDate(Hr,Hz,this.day);},nextMonth:function(){var Hz=this.month+1;var Hr=this.year;if(Hz>this.Hl.monthList.length-1){Hr++;Hz=0;}
this.setDate(Hr,Hz,this.day);},draw:function(){if(!this.H0D){this.rect.width=this.Hl.hSpace*8;this.rect.right=this.rect.left+this.rect.width;this.rect.height=this.Hl.barHeight+
this.Hl.vSpace*7;this.rect.bottom=this.rect.top+this.rect.height;}
this.base();if(!this.H0D){this.drawMarkup();var Hy,HH,HU,HY;this.H3n();this.monthControl=new HComboBox(new HRect(4,3,86,23),this,{enabled:this.enabled});for(var i=0;i<this.Hl.monthList.length;i++){this.monthControl.addItem(this.Hl.monthList[i]);}
this.monthControl.selectedIndexChanged=this.H66;this.yearControl=new HComboBox(new HRect(89,3,146,23),this,{enabled:this.enabled});for(var i=0;i<this.Hl.yearList.length;i++){this.yearControl.addItem(this.Hl.yearList[i]);}
this.yearControl.selectedIndexChanged=this.H67;this.closeButton=new HButton(new HRect(150,7,164,21),this,{label:'',enabled:this.enabled});this.closeButton.setMouseUp(true);this.closeButton.mouseUp=this.H68;var i,j,H7;var k=0;i=0;for(j=0;j<7-this.Hl.startDay;j++){Hy=this.Hl.hSpace*(j+1);HH=this.Hl.barHeight+
this.Hl.vSpace*(i);HU=Hy+this.Hl.hSpace;HY=HH+this.Hl.vSpace;H7=new HCalendarHeaderButton(new HRect(Hy,HH,HU,HY),this,{label:this.Hl.dayList[j+this.Hl.startDay],enabled:this.enabled});}
if(this.Hl.startDay==1){Hy=this.Hl.hSpace*(j+1);HH=this.Hl.barHeight+
this.Hl.vSpace*(i);HU=Hy+this.Hl.hSpace;HY=HH+this.Hl.vSpace;H7=new HCalendarHeaderButton(new HRect(Hy,HH,HU,HY),this,{label:this.Hl.dayList[0],enabled:this.enabled});}
Hy=0;HH=this.Hl.barHeight+
this.Hl.vSpace*(i);HU=Hy+this.Hl.hSpace;HY=HH+this.Hl.vSpace;H7=new HCalendarHeaderButton(new HRect(Hy,HH,HU,HY),this,{label:'',enabled:this.enabled});this.spot2=[];for(i=0;i<6;i++){Hy=0;HH=this.Hl.barHeight+
this.Hl.vSpace*(i+1);HU=Hy+this.Hl.hSpace;HY=HH+this.Hl.vSpace;H7=new HCalendarHeaderButton(new HRect(Hy,HH,HU,HY),this,{label:this.spotstr2[i],enabled:this.enabled});this.spot2[i]=H7;}
this.spot=[];for(i=0;i<6;i++){for(j=0;j<7;j++){Hy=this.Hl.hSpace*(j+1);HH=this.Hl.barHeight+
this.Hl.vSpace*(i+1);HU=Hy+this.Hl.hSpace;HY=HH+this.Hl.vSpace;H7=new HCalendarButton(new HRect(Hy,HH,HU,HY),this,{label:this.spotstr[k].day,enabled:this.enabled});H7.index=k;H7.setValue(this.spotstr[k].shade);this.spot[k]=H7;k++;}}
this.H3k();this.H3l();this.H0D=true;}},H68:function(H8,H9){this.parent.hide();this.base(H8,H9);},H66:function(){if(this.parent.updating2){return;}
this.parent.setDate(this.parent.year,this.selectedIndex(),this.parent.day);},H67:function(){if(this.parent.updating){return;}
this.parent.setDate(this.selectedItem().label,this.parent.month,this.parent.day);},H3l:function(){this.updating=true;for(var i=0;i<this.Hl.yearList.length;i++){if(this.Hl.yearList[i]==this.year){this.yearControl.selectItemAtIndex(i);break;}}
this.updating=false;},H3k:function(){this.updating2=true;this.monthControl.selectItemAtIndex(this.month);this.updating2=false;},H69:function(){for(var i=0;i<6;i++){this.spot2[i].setLabel(this.spotstr2[i]);}},H6a:function(){for(var i=0;i<42;i++){this.spot[i].setLabel(this.spotstr[i].day);this.spot[i].setValue(this.spotstr[i].shade);}},H2t:function(day,which){if(which==0){return{shade:2,day:day};}
if(which==1){return{shade:0,day:day};}
if(which==2){return{shade:1,day:day};}},setDate:function(Hr,Hz,Hu,H6b){if(Hr==this.year&&Hz==this.month&&Hu==this.day){return;}
if(!H6b){this.setValue(new Date(Hr,Hz,Hu));}
this.H3n(Hr,Hz,Hu);this.H6a();this.H69();this.H3k();this.H3l();},setValue:function(H2u){this.base(H2u);if(this.valueObj instanceof HDateValue&&!this.H4s){this.setDate(H2u.getFullYear(),H2u.getMonth(),H2u.getDate(),true);}},selectDay:function(i){if(i==this.todayspot){return;}
if(i<this.firstspot&&this.Hl.switchMonths){this.setDate(this.year,this.month-1,this.spotday[i]);}else if(i>=this.lastspot&&this.Hl.switchMonths){this.setDate(this.year,this.month+1,this.spotday[i]);}else{if(this.todayspot!=null){this.spotstr[this.todayspot]=this.H2t(this.spotday[this.todayspot],1);this.spot[this.todayspot].setValue(this.spotstr[this.todayspot].shade);}
this.todayspot=i;this.H3n(this.year,this.month,this.spotday[i]);this.spot[i].setValue(this.spotstr[i].shade);this.H3k();this.H3l();this.H4s=true;this.setValue(new Date(this.year,this.month,this.spotday[i]));this.H4s=false;}},H3n:function(Hr,Hz,Hu){var d=new Date();if(!Hz&&Hz!=0){Hz=d.getMonth();}
if(!Hu){Hu=d.getDate();}
if(!Hr){Hr=d.getFullYear();}
if(Hr<100){Hr+=1900;}
if(Hz<0){Hz=11;Hr-=1;}else if(Hz>11){Hz=0;Hr+=1;}
var l=new Date(Hr,Hz,1).getMonthLength();if(Hu>l||Hu<0){Hu=l;}
this.year=Hr;this.month=Hz;this.day=Hu;var date=new Date(this.year,this.month,this.day);date.setDate(1);var HZ=date.getDay()-this.Hl.startDay;if(HZ==-(this.Hl.startDay)||HZ==0){HZ+=7;}
this.spotstr2=new Array();var thisMonth_length=new Date(this.year,this.month,1).getMonthLength();var lastMonth=(this.month==0)?11:this.month-1;var lastMonth_length=new Date(this.year,lastMonth,1).getMonthLength();var calstart=lastMonth_length-HZ+1;var which,c;Hu=0;this.spotday=new Array();this.spotstr=new Array();for(var i=0;i<HZ;i++){if(i==0){var year1=(this.month==0)?this.year-1:this.year;this.spotstr2[0]=new Date(year1,lastMonth,calstart+i).getWeek();}
this.spotday[i]=calstart+i;this.spotstr[i]=this.H2t(this.spotday[i],0);}
this.firstspot=HZ;for(var i=HZ;i<thisMonth_length+HZ;i++){if(i==7){this.spotstr2[1]=new Date(this.year,this.month,i-HZ+1).getWeek();}else if(i==14){this.spotstr2[2]=new Date(this.year,this.month,i-HZ+1).getWeek();}else if(i==21){this.spotstr2[3]=new Date(this.year,this.month,i-HZ+1).getWeek();}else if(i==28){this.spotstr2[4]=new Date(this.year,this.month,i-HZ+1).getWeek();}
if(i==35){if(c<15){var year1=(this.month==11)?this.year+1:this.year;var month1=(this.month==11)?0:this.month+1;this.spotstr2[5]=new Date(year1,month1,i-HZ+1).getWeek();}else{this.spotstr2[5]=new Date(this.year,this.month,i-HZ+1).getWeek();}}
this.spotday[i]=i-HZ+1;if(this.spotday[i]==this.day&&this.Hl.selectToday){which=2;this.todayspot=i;}else{which=1;}
this.spotstr[i]=this.H2t(this.spotday[i],which);}
c=1;this.lastspot=thisMonth_length+HZ;for(var i=thisMonth_length+HZ;i<42;i++){if(i==35){if(c<15){var year1=(this.month==11)?this.year+1:this.year;var month1=(this.month==11)?0:this.month+1;this.spotstr2[5]=new Date(year1,month1,c).getWeek();}else{this.spotstr2[5]=new Date(this.year,this.month,c).getWeek();}}
this.spotday[i]=c++;this.spotstr[i]=this.H2t(this.spotday[i],0);}}});HCalendarHeaderButton=HControl.extend({packageName:"calendar",componentName:"calendarheaderbutton",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HCalendarHeaderButton]';this.H1a="calendarheaderbuttonlabel";this.setKeyDown(true);if(!this.isinherited){this.draw();}},keyDown:function(Hx){this.parent.keyDown(Hx);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){if(!this.HG){this.HG=elem_bind(this.H1a+this.elemId);}
if(this.HG){elem_set(this.HG,this.label);}
this.drawRect();}}});