
var HClass=function(){if(arguments.length){var _3l=arguments[0];if(this==window){HClass.prototype.extend.call(_3l,arguments.callee.prototype);}else{this.extend(_3l);}}};HClass.prototype={extend:function(_0N,_4){var _1o=HClass.prototype.extend;if(arguments.length==2){var _2s=this[_0N];if((_2s instanceof Function)&&(_4 instanceof Function)&&_2s.valueOf()!=_4.valueOf()&&/\bbase\b/.test(_4)){var _2P=_4;_4=function(){var _02=this.base;this.base=_2s;var _60=_2P.apply(this,arguments);this.base=_02;return _60;};_4.valueOf=function(){return _2P;};_4.toString=function(){return String(_2P);};}
return this[_0N]=_4;}else if(_0N){var _0p={toSource:null};var _4l=["toString","valueOf"];if(HClass._30){_4l.push("constructor");}
for(var i=0;(_e=_4l[i]);i++){if(_0N[_e]!=_0p[_e]){_1o.call(this,_e,_0N[_e]);}}
for(var _e in _0N){if(!_0p[_e]){_1o.call(this,_e,_0N[_e]);}}}
return this;},base:function(){}};HClass.extend=function(_0m,_38){var _1o=HClass.prototype.extend;if(!_0m){_0m={};}
HClass._30=true;var _0p=new this;_1o.call(_0p,_0m);var _1Q=_0p.constructor;_0p.constructor=this;delete HClass._30;var _0I=function(){if(!HClass._30){_1Q.apply(this,arguments);}
this.constructor=_0I;};_0I.prototype=_0p;_0I.extend=this.extend;_0I.implement=this.implement;_0I.toString=function(){return String(_1Q);}
_1o.call(_0I,_38);var _2T=_1Q?_0I:_0p;if(_2T.init instanceof Function){_2T.init();}
return _2T;};HClass.implement=function(_1s){if(_1s instanceof Function){_1s=_1s.prototype;}
this.prototype.extend(_1s);}
var Base=HClass;ie_htc_path=null;function ie_early_fixes(){var b=navigator.appName;var ua=navigator.userAgent.toLowerCase();var _5Q=ua.indexOf("opera")>-1;if(!_5Q&&b=="Microsoft Internet Explorer"){var _62=document.scripts[document.scripts.length-1];var _4x=_62.src;ie_htc_path=_4x.substring(0,_4x.lastIndexOf("/")+1);}}
ie_early_fixes();is_safari=navigator.userAgent.toLowerCase().indexOf("safari")>-1;is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Event=HClass.extend({constructor:null,element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(is_ie||is_safari){return(e.button==1);}else{return(e.button==0);}},observers:false,_5L:function(_9,_e,_0a,_04){if(!Event.observers){Event.observers=[];}
if(_9.addEventListener){this.observers.push([_9,_e,_0a,_04]);_9.addEventListener(_e,_0a,_04);}else if(_9.attachEvent){this.observers.push([_9,_e,_0a,_04]);_9.attachEvent("on"+_e,_0a);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_9,_e,_0a,_04){if(typeof _9=="string"){_9=document.getElementById(_9);}
_04=_04||false;Event._5L(_9,_e,_0a,_04);},stopObserving:function(_9,_e,_0a,_04){if(typeof _9=="string"){_9=document.getElementById(_9);}
_04=_04||false;if(_9.removeEventListener){_9.removeEventListener(_e,_0a,_04);}else if(detachEvent){try{element.detachEvent("on"+name,_0a);}catch(e){}}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_9&&eo[1]==_e&&eo[2]==_0a&&eo[3]==_04){Event.observers[i]=null;Event.observers.splice(i,1);}else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34});if(is_ie){Event.observe(window,"unload",Event.unloadCache,false);}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length;var _3r=[];for(i=0;i<l;i++){_3r.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _3r.join("&");}
Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_n,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _z=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_z=_z.extend(_2);this.options=new _z();this.request(_n);},request:function(_n){this.url=_n;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _j=this;this.transport.onreadystatechange=function(){_j.onStateChange()};this.setRequestHeaders();var _50=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_50);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1A=this.transport.readyState;if(_1A>1){this.respondToReadyState(_1A);}},respondToReadyState:function(_1A){if(_1A==4){try{(this.options["on"+(this.success()?"Success":"Failure")]||(function(){}))(this.transport);}catch(e){console.log(e);}}
if(_1A==4){this.transport.onreadystatechange=function(){};}},success:function(){return!this.transport.status||(this.transport.status>=200&&this.transport.status<300);}});frameskips=1;var _05=document;var _11=0;var quot='"';var apos="'";is_ie=(_05.all&&navigator.userAgent.indexOf("Opera")==-1);is_ie6=(is_ie&&navigator.userAgent.indexOf("MSIE 6")!=-1);is_ie7=(is_ie&&navigator.userAgent.indexOf("MSIE 7")!=-1);is_safari=(navigator.userAgent.indexOf("KHTML")!=-1);var _2B=[];var _3N=false;onloader=function(_39){if(_3N){eval(_39);}else{_2B.push(_39);}};var _5P=null;var _4c=function(_1Y){if(_1Y){_3N=true;while(_2B.length!=0){var _5v=_2B.shift();eval(_5v);}}else{_5P=setTimeout('_4b()',10);}};var _4b=function(){var _1Y=false;if(is_ie){var _3W="javascript:void(0)";if(location.protocol=="https:"){_3W="src=//0";}
_05.write("<scr"+"ipt id=_4U defer src="+_3W+"><\/scr"+"ipt>");var _5u=_05.getElementById("_4U");_5u.onreadystatechange=function(){if(this.readyState=="complete"){_4c(true);}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(_05.readyState))){_1Y=true;}
else if(document.body){_1Y=true;}
_4c(_1Y);};_4b();var _2a;var _w=[];var _1f=[];var _1I=[];var _2n=[];var _2o={};var _2p=false;var _0U=[];var prop_do_csstext=false;elem_bind=function(_3G){var _9=_05.getElementById(_3G);if(!_9){return false;}
var _6=_2r(_9);_1I[_6]=[];_1f[_6]=[];return _6;};elem_add=function(_9){var _6=_2r(_9);_1I[_6]=[];_1f[_6]=[];return _6;};elem_get=function(_6){return _w[_6];};elem_set=function(_6,_1X){_w[_6].innerHTML=_1X;};elem_del=function(_6){var _3e=_w[_6];if(_3e){var _4f=_3e.parentNode;if(_4f){_4f.removeChild(_3e);}}
_w[_6]=null;_1I[_6]=[];_1f[_6]=[];_0U.push(_6);};elem_replace=function(_6,_9){var _3Q=_0U.indexOf(_6);if(_3Q>-1){_0U.splice(_3Q,1);}
_w[_6]=_9;};elem_append=function(_2V,_6){_w[_2V].appendChild(_w[_6]);};elem_mk=function(_2V,_3g){if(_3g===undefined){_3g='div';}
var _9=_05.createElement(_3g);_w[_2V].appendChild(_9);var _6=_2r(_9);_1I[_6]=[];_1f[_6]=[];return _6;};elem_count=function(){var _3I=0;for(var i=0;i<_w.length;i++){if(_w[i]){_3I++;}}
return _3I;};_2r=function(_9){var _6;if(_0U.length>0){var _5j=_0U[0];_0U.splice(0,1);_w[_5j]=_9;_6=_5j;}
else{_w.push(_9);_6=_w.length-1;}
return _6;};styl_get=function(_6,_e){return prop_get(_6,_e);};var _1z="prop_get = function(_6,_e,_2y){var _y = _1f[_6];if((_y[_e]===undefined)||(_2y!==undefined)){";_1z+="if((_e == 'opacity') && (_2y != -1)) {var _2b = prop_get_opacity(_6);} else {";if(!is_ie){_1z+="var _2b = _05.defaultView.getComputedStyle(_w[_6],null).getPropertyValue(_e);";}else{_1z+="var _53 = _e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4});var _2b = _w[_6].currentStyle[_53];";}
_1z+="}_y[_e]=_2b;}return _y[_e];};";onloader(_1z);styl_set=function(_6,_e,_4){try{prop_set(_6,_e,_4);return true;}
catch(e){return false;}};prop_set=function(_6,_e,_4,_2y){var _y=_1f[_6];var _5H=_y[_e]!=_4;if(_5H){_y[_e]=_4;if(_2y){if(_e=='opacity'){prop_set_opacity(_6,_4);}
else{try{is_ie?(_w[_6].style.setAttribute(_e.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_y[_e])):(_w[_6].style.setProperty(_e,_y[_e],''));}
catch(e){_w[_6].cssText+=';'+_e+': '+_y[_e]+';';}}}else{var _52=_2n;var _3u=_1I[_6];_3u.push(_e);if(!_2o[_6]){_52.push(_6);_2o[_6]=true;}}}};var _0o="var _5X=function(_6){var _3u=_1I[_6];var _y=_1f[_6];var _9=_w[_6];if(!_9){return}var _2A=_9.style;var _6F=_3u.length;";if(prop_do_csstext){_0o+="var _3B=[];";}
_0o+="for(var _3w=0;_3w<_6F;_3w++){var _e=_3u.shift();";if(prop_do_csstext){_0o+="_3B.push(_e+':'+_y[_e]);}_2A.cssText += ';'+_3B.join(';')+';';";}else{_0o+="if(_e == 'opacity') { _2b = prop_set_opacity(_6, _y[_e]); } else {";if(is_ie){_0o+="_2A.setAttribute(_e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_y[_e]);}";}
else{_0o+="_2A.setProperty(_e,_y[_e],'');}";}
_0o+="};";}
_0o+="}";eval(_0o);var _4g='prop_loop_start(_11)';var _5Y=1;var _2Y=1;var prop_loop_start=function(_11){clearTimeout(_2a);if(_2p){_11*=2;_2a=setTimeout(_4g,_11);return;}else{_11=parseInt(frameskips*(_2Y/_5Y),10);if(_11<40){_11=40;}
_2p=true;_2a=setTimeout(_4g,_11);}
_2Y-=now();var _5D=_2n.length;for(var i=0;i<_5D;i++){var _6=_2n.shift();_2o[_6]=false;_5X(_6);}
_5Y++;_2Y+=now();_2p=false;return;};var prop_loop_stop=function(){clearTimeout(_2a);};var now=function(){return new Date().getTime();};var prop_get_opacity=function(_6){var _01;var _4M=prop_get(_6,'opacity',-1);if(_01=_4M||(_4M==0)){return parseFloat(_01);}
if(_01=(_w[_6].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_01[1]){return parseFloat(_01[1])/100;}}
return 1.0;};var prop_set_opacity=function(_6,_4){if(_4==1&&is_ie){_w[_6].style.setAttribute('filter',prop_get(_6,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_4<0.00001)_4=0;if(is_ie){_w[_6].style.setAttribute('filter',prop_get(_6,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_4*100+')');}
else{_w[_6].style.setProperty('opacity',_4,'');}}};var prop_get_extra_width=function(_6){var _h=prop_get_int_value(_6,'padding-left')+
prop_get_int_value(_6,'padding-right')+
prop_get_int_value(_6,'border-left-width')+
prop_get_int_value(_6,'border-right-width');return _h;};var prop_get_extra_height=function(_6){var _p=prop_get_int_value(_6,'padding-top')+
prop_get_int_value(_6,'padding-bottom')+
prop_get_int_value(_6,'border-top-width')+
prop_get_int_value(_6,'border-bottom-width');return _p;};var prop_get_int_value=function(_6,_4k){var _2I=parseInt(prop_get(_6,_4k,true),10);if(isNaN(_2I)){_2I=0;}
return _2I;};onloader('elem_add(document.body);');onloader('prop_loop_start();');HEventManager=HClass.extend({events:[false,false,0,0,[],[],[],false,false,false],HStatusButton:0,HStatusButton2:1,HStatusCoordX:2,HStatusCoordY:3,HStatusKeys:4,HStatusDirection:5,HStatusSpeed:6,HStatusAltKey:7,HStatusCtrlKey:8,HStatusShiftKey:9,constructor:null,start:function(){var _0k;if(is_ie){_0k=document;}
else{_0k=window;}
Event.observe(_0k,'mousemove',this.mouseMove);Event.observe(_0k,'mouseup',this.mouseUp);Event.observe(_0k,'mousedown',this.mouseDown);Event.observe(_0k,'keyup',this.keyUp);Event.observe(_0k,'keydown',this.keyDown);Event.observe(_0k,'keypress',this.keyPress);Event.observe(_0k,'contextmenu',this.contextMenu);if(window.addEventListener){window.addEventListener('DOMMouseScroll',this.mouseWheel,false);}
window.onmousewheel=document.onmousewheel=this.mouseWheel;this.focusItems=[];this.mouseMoveItems=[];this.eventItems=[];this.focusOptions=[];this.dragItems=[];this.hoverItems=[];this.hoverInterval=100;this.hoverTimer=new Date().getTime();this.topmostDroppable=null;this._2z=[];this._3K=true;this.activeControl=null;this._6D=null;},enablePositionCache:function(){this._3K=true;},disablePositionCache:function(){this._3K=false;},invalidatePositionCache:function(_c){if(_c){this._2z[_c]=null;}
else{this._2z=[];}},register:function(_s,_3P){var _c=_s.elemId;var _9=elem_get(_c);if(is_ie){_9.setAttribute('owner',_s);}
else{_9.owner=_s;}
this.eventItems[_c]=true;this.focusItems[_c]=false;this.focusOptions[_c]=_3P;Event.observe(_9,'mouseover',_s._5F);},unregister:function(_s){if(_s==this.activeControl){this.changeActiveControl(null);}
var _c=_s.elemId;var _9=elem_get(_c);this.eventItems[_c]=false;this.focusItems[_c]=false;this._2z[_c]=null;try{Event.stopObserving(_9,'mouseover',_s._5F);}catch(e){window.status=e;}},focus:function(_s){var _c=_s.elemId;var _9=elem_get(_c);if(this.focusItems[_c]==false&&_s.isDragged==false){Event.stopObserving(_9,'mouseover',_s._5F);Event.observe(_9,'mouseout',_s._5E);this.focusItems[_c]=true;_s.focus();}},blur:function(_s){var _c=_s.elemId;var _9=elem_get(_c);if(this.focusItems[_c]==true&&_s.isDragged==false){Event.stopObserving(_9,'mouseout',_s._5E);Event.observe(_9,'mouseover',_s._5F);this.focusItems[_c]=false;_s.blur();}},mouseMove:function(e){var _3=HEventManager;var _8=Event.pointerX(e);var _a=Event.pointerY(e);var _3C=false;_3.events[_3.HStatusCoordX]=_8;_3.events[_3.HStatusCoordY]=_a;for(var i=0;i<_3.dragItems.length;i++){var _c=_3.dragItems[i];_3.focusOptions[_c].owner.doDrag(_8,_a);_3.invalidatePositionCache(_c);_3C=true;}
if(new Date().getTime()>_3.hoverTimer+_3.hoverInterval){_3._6Q();for(var i=0;i<_3.mouseMoveItems.length;i++){var _c=_3.mouseMoveItems[i];var _0n=_3.focusOptions[_c].owner;_0n.mouseMove(_8,_a);}
for(var i=0;i<_3.dragItems.length;i++){var _3k=_3.topmostDroppable;_3.topmostDroppable=null;var _c=_3.dragItems[i];var _0n=_3.focusOptions[_c].owner;for(var j=0;j<_3.hoverItems.length;j++){var _1W=_3.hoverItems[j];if(_1W!=_c&&_3.focusOptions[_1W].owner){var _2j=_3.focusOptions[_1W].owner;if(!_3.topmostDroppable||_2j.zIndex()>_3.topmostDroppable.zIndex()||_2j.parent==_3.topmostDroppable){if(_2j.events.droppable){_3.topmostDroppable=_2j;}}}}
if(_3k!=_3.topmostDroppable){if(_3k){_3k.onHoverEnd(_0n);}
if(_3.topmostDroppable){_3.topmostDroppable.onHoverStart(_0n);}}}
_3.hoverTimer=new Date().getTime();}
if(_3C){Event.stop(e);}},_6Q:function(){var _3=HEventManager;_3.hoverItems=[];var x=_3.events[_3.HStatusCoordX];var y=_3.events[_3.HStatusCoordY];for(var _t=0;_t<_3.eventItems.length;_t++){if(!_3.eventItems[_t]||!_3.focusOptions[_t].owner){continue;}
var _3A=_3.focusOptions[_t].owner;var _9=elem_get(_t);var _0F;if(!_3._3K||!_3._2z[_t]){_3._2z[_t]={_5C:[_3A.pageX(),_3A.pageY()],_6M:helmi.Element.getVisibleSize(_9)};}
_0F=_3._2z[_t];if(x>=_0F._5C[0]&&x<=_0F._5C[0]+_0F._6M[0]&&y>=_0F._5C[1]&&y<=_0F._5C[1]+_0F._6M[1]){_3.hoverItems.push(_t);}}},mouseDown:function(e,_0H){var _3=HEventManager;_3._6H(e);var _3F=false;if(_0H===undefined){_0H=Event.isLeftClick(e);}
if(_0H){_3.events[_3.HStatusButton]=true;}else{_3.events[_3.HStatusButton2]=true;}
var _8=_3.events[_3.HStatusCoordX];var _a=_3.events[_3.HStatusCoordY];var _K=null;var _2e=[];var _2R=[];for(var i=0;i<_3.focusItems.length;i++){if(_3.focusItems[i]==true){if(_3.focusOptions[i].owner.enabled){_K=_3.focusOptions[i].owner;}
if((_3.focusOptions[i].draggable==true)&&(_3.dragItems.indexOf(i)==-1)){_2e.push(i);}
else if(_3.focusOptions[i].mouseDown==true){_2R.push(i);}}}
_3.changeActiveControl(_K);for(var i=0;i<_2e.length;i++){_3.dragItems.push(_2e[i]);_3.focusOptions[_2e[i]].owner.startDrag(_8,_a);_3F=true;}
for(var i=0;i<_2R.length;i++){_3.focusOptions[_2R[i]].owner.mouseDown(_8,_a,_0H);}
if(_3F){document.body.focus();_3._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if(_3.hoverItems.length>0){Event.stop(e);}
return true;},changeActiveControl:function(_K){var _3=HEventManager;var _0d=_3.activeControl;if(_K!=_0d){if(_0d){_0d.active=false;_0d._6G(_K);}
_3.activeControl=null;if(_K){_K.active=true;_3.activeControl=_K;_K._6y(_0d);}}},mouseUp:function(e){var _3=HEventManager;_3._6H(e);var _3E=false;_3.events[_3.HStatusButton]=false;_3.events[_3.HStatusButton2]=false;var _8=_3.events[_3.HStatusCoordX];var _a=_3.events[_3.HStatusCoordY];for(var i=0;i<_3.dragItems.length;i++){var _c=_3.dragItems[i];var _0n=_3.focusOptions[_c].owner;_0n.endDrag(_8,_a);_3E=true;_3._6Q();if(_3.hoverItems.indexOf(_c)<0){_3.blur(_0n);}
if(_3.topmostDroppable){_3.topmostDroppable.onHoverEnd(_0n);_3.topmostDroppable.onDrop(_0n);_3.topmostDroppable=null;}}
_3.dragItems=[];if(_3E){document.onselectstart=_3._storedOnSelectStart;}
for(var _t=0;_t<_3.focusItems.length;_t++){if(_3.focusItems[_t]==true){if(_3.focusOptions[_t].mouseUp==true){_3.focusOptions[_t].owner.mouseUp(_8,_a,true);}}}
return true;},keyDown:function(e){var _3=HEventManager;_3._6H(e);var _0z=e.keyCode;if(_3.activeControl&&_3.focusOptions[_3.activeControl.elemId].keyDown==true){Event.stop(e);if(_3._6D!=_0z){_3.activeControl.keyDown(_0z);}}
var _1B=_3.events[_3.HStatusKeys];if(_1B.indexOf(_0z)==-1){_1B.push(_0z);}
_3._6D=_0z;},keyUp:function(e){var _3=HEventManager;_3._6H(e);var _0z=e.keyCode;_3._6D=null;if(_3.activeControl&&_3.focusOptions[_3.activeControl.elemId].keyUp==true){_3.activeControl.keyUp(_0z);}
var _1B=_3.events[_3.HStatusKeys];var _40=_1B.indexOf(_0z);if(_40!=-1){_1B.splice(_40,1);}},keyPress:function(e){var _3=HEventManager;if(_3.activeControl&&_3.focusOptions[_3.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _3=HEventManager;var _T=0;if(!e){e=window.event;}
if(e.wheelDelta){_T=e.wheelDelta/120;if(window.opera)_T=-_T;}else if(e.detail){_T=-e.detail/3;}
for(var _t=0;_t<_3.focusItems.length;_t++){if(_3.focusItems[_t]==true){if(_3.focusOptions[_t].mouseWheel==true){Event.stop(e);_3.focusOptions[_t].owner.mouseWheel(_T);}}}},contextMenu:function(e){var _3=HEventManager;_3.mouseDown(e,false);Event.stop(e);},_6H:function(e){var _3=HEventManager;_3.events[_3.HStatusAltKey]=e.altKey;_3.events[_3.HStatusCtrlKey]=e.ctrlKey;_3.events[_3.HStatusShiftKey]=e.shiftKey;}});onloader('HEventManager.start();');ie_namespace={};function $(_0){if(typeof _0=='string')_0=document.getElementById(_0);return _0;}
helmi={};Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;}
helmi.UserAgent=function(){var b=navigator.appName;var v=navigator.appVersion;var ua=navigator.userAgent.toLowerCase();this.safari=ua.indexOf("safari")>-1;this.opera=ua.indexOf("opera")>-1;this.ns=!this.opera&&!this.safari&&(b=="Netscape");this.ie=!this.opera&&(b=="Microsoft Internet Explorer");this.gecko=!this.safari&&ua.indexOf("gecko")>-1;if(this.ns){this.ns4=(this.v==4);this.v=parseInt(ua.substr(ua.indexOf("netscape")+9,1),10);this.ns6=(this.v==6);this.ns7=(this.v==7);}else if(this.ie){this.ie4=(v.indexOf("MSIE 4")>0);this.ie5=(v.indexOf("MSIE 5")>0);this.ie55=(v.indexOf("MSIE 5.5")>0);this.ie6=(v.indexOf("MSIE 6")>0);this.ie7=(v.indexOf("MSIE 7")>0);}else if(this.opera){this.v=parseInt(ua.substr(ua.indexOf("opera")+6,1),10);this.opera6=(this.v==6);this.opera7=(this.v==7);this.opera8=(this.v==8);this.opera9=(this.v==9);}
this.win=ua.indexOf("win")>-1;this.mac=ua.indexOf("mac")>-1;}
is=new helmi.UserAgent();helmi.Element=Base.extend({constructor:null,getPageLocation:function(_0,_1d){var _Q=0,_R=0;var _f;var _1y=_0;if(is.opera){if(is.opera9){do{_f=_0.offsetParent;_Q+=_0.offsetLeft;_R+=_0.offsetTop;_0=_f;}while(_0);}else{if(_0.tagName.toLowerCase()=="body"){return[0,0];}
var _02;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"&&_02&&(_02.style.position=="absolute"||_02.style.position=="relative"||_02.style.position=="fixed")){}else{_Q+=_0.offsetLeft;_R+=_0.offsetTop;}
if(_f&&_f.tagName.toLowerCase()=="body"&&(_0.style.position=="absolute"||_0.style.position=="relative"||_0.style.position=="fixed"||_0.tagName.toLowerCase()=="input"||_0.tagName.toLowerCase()=="button"||_0.tagName.toLowerCase()=="select"||_0.tagName.toLowerCase()=="textarea")){}else if(_f){_Q+=_f.clientLeft;_R+=_f.clientTop;}
_02=_0;_0=_f;}while(_0);}}else if(is.safari){if(_0.tagName.toLowerCase()=="body"){return[0,0];}
var _02;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"&&_02&&(_02.style.position=="absolute"||_02.style.position=="fixed")){}else{_Q+=_0.offsetLeft;_R+=_0.offsetTop;}
_02=_0;_0=_f;}while(_0);}else if(is.ns){if(_1d){var _0s=[];var x=_0.offsetLeft;var y=_0.offsetTop;var _3L=null;do{_f=_0.offsetParent;if(_0==_1y&&_0.style.position!="absolute"){if(_f&&(_f.style.overflow=="scroll"||_f.style.overflow=="auto")){_3L=_f;}}
if(_0.style.overflow=="scroll"||_0.style.overflow=="auto"){_0s.push([_0,_0.style.overflow,_0.scrollLeft,_0.scrollTop]);_0.style.overflow="inherit";}
_0=_f;}while(_0);}
_0=_1y;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"){}else{if(_0==_1y&&_0.style.position!="absolute"){_Q+=x;_R+=y;}else{_Q+=_0.offsetLeft;_R+=_0.offsetTop;}}
if(_f&&_f.tagName.toLowerCase()=="body"&&(_0.style.position=="absolute"||_0.style.position=="fixed")){}else if(_f){_Q+=(_f.offsetWidth-_f.clientWidth)/2;_R+=(_f.offsetHeight-_f.clientHeight)/2;if(_f==_3L){_Q+=(_f.offsetWidth-_f.clientWidth)/2;_R+=(_f.offsetHeight-_f.clientHeight)/2;}}
_0=_f;}while(_0);if(_1d){var l=_0s.length;for(var i=0;i<l;i++){_0s[i][0].style.overflow=_0s[i][1];_0s[i][0].scrollLeft=_0s[i][2];_0s[i][0].scrollTop=_0s[i][3];}}}else if(is.ie){if(_0.tagName.toLowerCase()=="body"){return[0,0];}
do{_f=_0.offsetParent;_Q+=_0.offsetLeft;_R+=_0.offsetTop;if(_f&&_f.tagName.toLowerCase()=="html"&&_0.style.position=="relative"){_Q-=2;_R-=2;}
if(_f&&_f.tagName.toLowerCase()=="html"&&_0.style.position=="absolute"){}else if(_f){_Q+=_f.clientLeft;_R+=_f.clientTop;}
_0=_f;}while(_0);}
if(_1d){_0=_1y;do{if(!_0.tagName||_0.tagName.toLowerCase()=="body"){break;}
if(_0.style.position=="fixed"){_Q+=window.pageXOffset||document.documentElement.scrollLeft;_R+=window.pageYOffset||document.documentElement.scrollTop;}
_f=_0.parentNode;if(_0!=_1y){if(is.opera&&_0.tagName.toLowerCase()=="tr"){}else{_Q-=_0.scrollLeft;_R-=_0.scrollTop;}}
_0=_f;}while(_0);}
return[_Q,_R];},getSize:function(_0){return[_0.offsetWidth,_0.offsetHeight];},getVisibleSize:function(_0){var w=_0.offsetWidth;var h=_0.offsetHeight;var _q=_0.parentNode;while(_q&&_q.nodeName.toLowerCase()!='body'){var _V;if(!is.ie){_V=document.defaultView.getComputedStyle(_q,null).getPropertyValue('overflow');}else{_V=_q.currentStyle.getAttribute('overflow');}
_V=_V!='visible';if(w>_q.clientWidth&&_V){w=_q.clientWidth-_0.offsetLeft;}
if(h>_q.clientHeight&&_V){h=_q.clientHeight-_0.offsetTop;}
_0=_0.parentNode;_q=_0.parentNode;}
return[w,h];},getVisiblePageLocation:function(_0,_1d){var _0K=this.getPageLocation(_0,_1d);var x=_0K[0];var y=_0K[1];var _q=_0.parentNode;while(_q&&_q.nodeName.toLowerCase()!='body'){var _V;if(!is.ie){_V=document.defaultView.getComputedStyle(_q,null).getPropertyValue('overflow');}else{_V=_q.currentStyle.getAttribute('overflow');}
_V=_V!='visible';_0K=this.getPageLocation(_q,_1d);if(x<_0K[0]&&_V){x=_0K[0];}
if(y<_0K[1]&&_V){y=_0K[1];}
_0=_0.parentNode;_q=_0.parentNode;}
return[x,y];},hasClassName:function(_0,_0X){_0=$(_0);if(!_0)return;var _3S=false;var _0Y=_0.className.split(' ');for(var i=0;i<_0Y.length;i++){if(_0Y[i]==_0X){_3S=true;}}
return _3S;},addClassName:function(_0,_0X){_0=$(_0);if(!_0)return;helmi.Element.removeClassName(_0,_0X);_0.className+=' '+_0X;},removeClassName:function(_0,_0X){_0=$(_0);if(!_0)return;var _2S='';var _0Y=_0.className.split(' ');for(var i=0;i<_0Y.length;i++){if(_0Y[i]!=_0X){if(i>0)_2S+=' ';_2S+=_0Y[i];}}
_0.className=_2S;}});Object.extend(Array.prototype,{indexOfObject:function(_1M){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_1M){return i;}}
return-1;},containsObject:function(_1M){return this.indexOfObject(_1M)!=-1;},removeObject:function(_1M){while((i=this.indexOfObject(object))>=0){this.splice(i,1);}},first:function(){return this[0];},last:function(){return this[this.length-1];}});if(!is.ns7){Object.extend(Array.prototype,{indexOf:Array.prototype.indexOfObject});}
helmi.Window=Base.extend({constructor:null,getInnerWidth:function(){return(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;},getInnerHeight:function(){return(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;}});helmi.Event=Base.extend({constructor:null,getPageX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},getPageY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},getKeyCode:function(e){return e.keyCode;},getCharCode:function(e){if(is.ns){return e.charCode;}else{return e.keyCode;}}});HPath=HClass.extend({constructor:null,getRelativePath:function(_m,_D){var _m=this.getRelativeFilePath(_m,_D);return _m.slice(0,_m.lastIndexOf("/")+1);},getRelativeFilePath:function(_m,_D){_m=_m||"";if(_D.charAt(0)=="/"){return _D;}
var _m=_m.substring(0,_m.lastIndexOf("/")+1);var _3H=_D.indexOf("../");var _37=_m.length;var _3M;while(_3H==0){if((_3M=_m.lastIndexOf("/",_37))!=-1){_37=_m.lastIndexOf("/",_3M-1);_m=_m.substring(0,_37+1);}else{break;}
_D=_D.substring(3);_3H=_D.indexOf("../");}
return _m+_D;}});ie_namespace.iestyleSheetLoaded=function(){if(document.readyState=="complete"&&window.event.srcElement.readyState=="complete"){_0S();}}
stylesheet_refresh=function(_1D){_1D.cssText+="";}
_0S=function(_0){var _0=_0||document.documentElement;while(_0){if(_0.nodeType==1){HStyle._2H(_0);}
var _1x=_0.firstChild;if(!_1x){_1x=_0.nextSibling;}
while(!_1x&&_0.parentNode){_0=_0.parentNode;_1x=_0.nextSibling;}
_0=_1x;}}
ie_namespace.ieinlineStyleChanged=function(){var _0=window.event.srcElement;if(window.event.propertyName=="style.opacity"){HOpacityFix._2D(_0);}
else if(window.event.propertyName=="src"&&_0.tagName=="IMG"||(_0.tagName=="INPUT"&&_0.type=="image")){HOpacityFix._2C(_0);}}
HStyle=HClass.extend({constructor:null,init:function(){this._6t=/^(auto|0cm)$/;},_2H:function(_0){var _08=_0.currentStyle;if((_08.position=="absolute"||_08.position=="fixed")&&_08.left!="auto"&&_08.right!="auto"&&_08.width=="auto"){HRighBottoFix._1b(_0);}
if((_08.position=="absolute"||_08.position=="fixed")&&_08.top!="auto"&&_08.bottom!="auto"&&_08.height=="auto"){HRighBottoFix._4n(_0);}
if(_0.currentStyle.opacity){HOpacityFix._2D(_0);}
if(_0.currentStyle.backgroundImage){HOpacityFix._3O(_0);}
if(_0.tagName=="IMG"||(_0.tagName=="INPUT"&&_0.type=="image")){HOpacityFix._2C(_0);}}});HNumber=HClass.extend({constructor:null,init:function(){this._4T=/^\d+(px)?$/i;this._4S=/^\d+%$/;},getPixelValue:function(_0,_4){if(this._4T.test(_4)){return parseInt(_4);}
var _0h=_0.style.left;var _61=_0.runtimeStyle.left;_0.runtimeStyle.left=_0.currentStyle.left;HRighBottoFix.resizing=true;_0.style.left=_4||0;_4=_0.style.pixelLeft;_0.style.left=_0h;HRighBottoFix.resizing=false;_0.runtimeStyle.left=_61;return _4;}});HOpacityFix=HClass.extend({constructor:null,init:function(){this._4h=new RegExp(".png$","i");},_2D:function(_0){var _01=(parseFloat(_0.currentStyle.opacity)*100)||1;var _O=_0.filters["DXImageTransform.Microsoft.Alpha"];if(_O){_O.Opacity=_01;_O.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.Alpha(opacity="+_01+")";}},_3O:function(_0){var _n=_0.currentStyle.backgroundImage.match(/url\(\s*['"]?([^'")]+)['"]?\s*\)/);if(!_n){return;}else{_n=_n[1];}
var _O=_0.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(this._4h.test(_n)){if(_O){_O.sizingMethod="scale";_O.src=_n;_O.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_n+"',sizingMethod='scale')";}
_0.runtimeStyle.zoom="1";_0.runtimeStyle.backgroundImage="none";}else if(_O){_O.Enabled=false;}},_2C:function(_0){if(this._4h.test(_0.src)){var _0u=new Image(_0.width,_0.height);_0u.onload=function(){_0.width=_0u.width;_0.height=_0u.height;_0u=null;}
this._3o(_0,_0u);}},_3o:function(_0,_0u){var _O=_0.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_O){_O.src=_0.src;_O.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_0.src+"',sizingMethod='scale')";}
var _4G=_0.src;_0.src=HPath.getRelativeFilePath(_4G,"blank.gif");_0u.src=_4G;}});HRighBottoFix=HClass.extend({constructor:null,init:function(){eval("this._5l="+String(this._1q).replace(/padding/g,"margin"));eval("this._5m="+String(this._1q).replace(/Width/g,"Height").replace(/Left/g,"Top").replace(/Right/g,"Bottom"));eval("this._6A="+String(this._5m).replace(/padding/g,"margin"));eval("this._6z="+String(this._3R).replace(/Width/g,"Height"));eval("this._5B="+String(this._1u).replace(/Width/g,"Height").replace(/width/g,"height").replace(/Right/g,"Bottom"));eval("this._6B="+String(this._13).replace(/Width/g,"Height"));eval("this._4n="+String(this._1b).replace(/Width/g,"Height").replace(/width/g,"height").replace(/left/g,"top").replace(/right/g,"bottom"));this.resizing=false;},_3T:function(_0){return _0.currentStyle.hasLayout;},_1q:function(_0){return this._13(_0,_0.currentStyle.paddingLeft)+
this._13(_0,_0.currentStyle.paddingRight);},_3R:function(_0){return _0.offsetWidth-_0.clientWidth;},_1u:function(_0){var _00=_0.offsetParent;while(_00&&!this._3T(_00)){_00=_00.offsetParent;}
if(!_00._6L){_00._6L=[];}
if(!_0._addedResizewidthFix){_00._6L.push(_0);var _q=_00;while(_q.offsetParent){_q=_q.offsetParent;if(_q._6L){_q._6L.push(_0);}
if(_q.style.position=="absolute"||_q.style.position=="fixed"){break;}}
_0._addedResizewidthFix=true;}
if(!_00._resizewidth){_00.attachEvent("onpropertychange",function(){if(window.event.propertyName=="style.width"){for(var i=0;i<_00._6L.length;i++){HRighBottoFix._1b(_00._6L[i]);}}});_00._resizewidth=true;}
return(_00||document.documentElement).clientWidth;},_13:function(_0,_4){if(HNumber._4S.test(_4)){return parseInt(parseFloat(_4)/100*this._1u(_0));}
return HNumber.getPixelValue(_0,_4);},_1b:function(_0){var _F=parseInt(_0.currentStyle.left);var _h=this._1u(_0)-this._13(_0,_0.currentStyle.right)-_F-this._5l(_0);var _h=this._1u(_0)-parseInt(_0.currentStyle.right)-_F;if(parseInt(_0.runtimeStyle.width)==_h){return;}
_0.runtimeStyle.width="";if(_0.offsetWidth<_h){if(_h<0){_h=0;}
_h-=this._3R(_0)+this._1q(_0);_0.runtimeStyle.width=_h;}}});ie_complete=document.readyState=="complete";ie_initialized=false;ie_documentLoaded=function(){if(document.readyState=="complete"){_0S();}}
ie_fixes=function(){if(is.ie6&&!ie_initialized){if(ie_complete){var _68=document.createStyleSheet();_68.cssText='style,link{behavior:url('+ie_htc_path+'ie_css_style.htc)}\n*{behavior:url('+ie_htc_path+'ie_css_element.htc)}';ie_documentLoaded();}else{document.write('<style type="text/css">style,link{behavior:url('+ie_htc_path+'ie_css_style.htc)}\n*{behavior:url('+ie_htc_path+'ie_css_element.htc)}</style>');document.onreadystatechange=ie_documentLoaded;}
ie_initialized=true;}}
ie_fixes();HTransportURL=false;HTransportPoll=true;HTransporter=Base.extend({constructor:null,start:function(_6k){this.url_base=_6k;this.ses_id=0;this.err_msg='';this.isBusy=false;this.syncNum=0;this.syncDelay=0;this.pollMode=HTransportPoll;this.req_timeout=setTimeout('HTransporter.sync();',this.syncDelay);},setPollMode:function(_5){this.pollMode=_5;},failure:function(resp){alert('HTTP ERROR! STOP.');clearTimeout(this.req_timeout);this.isBusy=true;},respond:function(resp){var _4t=resp.responseText;eval(_4t);HTransporter.isBusy=false;},sync:function(){var valid_delay=((this.syncDelay&&this.syncDelay>0)||this.syncDelay==0);if(valid_delay&&this.url_base){if(!this.isBusy){this.isBusy=true;var _4z=HValueManager.toXML();if(""!=_4z||this.pollMode){this.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){HTransporter.respond(resp);},onFailure:function(resp){HTransporter.failure(resp);},method:'post',postBody:'ses_id='+HTransporter.ses_id+_4z};this.req=new Ajax.Request(this.url_base,req_args);HVM.isGetting=false;}
else{this.isBusy=false;}}
this.req_timeout=setTimeout('HTransporter.sync();',this.syncDelay);}},stop:function(){clearTimeout(this.req_timeout);}});onloader("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:[],tosync:[],isSending:false,isGetting:false,add:function(_6,_j){this.values[_6]=_j;},set:function(_6,_4){this.values[_6].set(_4);},del:function(_6){var _4I=this.values[_6];var _6l=_4I.views;for(var _C=0;_C<_6l.length;_C++){var _6e=_6l[_C];_6e.valueObj=new HDummyValue(0,_4I.value);}
this.values[_6]=null;},changed:function(_1E){if(this.isGetting==false){if(this.tosync.indexOf(_1E.id)==-1){this.tosync.push(_1E.id);}}},toXML:function(){var _4i='&HSyncData=';if(!this.isSending){this.isSending=true;var _4B=this.tosync.length;if(_4B==0){this.isSending=false;return'';}
var _4D=[];for(var _14=0;_14<_4B;_14++){var _3a=this.tosync.shift();var _69=this.values[_3a];_4D.push(_69.toXML(_14));}
var _6a=_4D.join('');_4i+='<hsyncvalues version="2240" length="'+_4B+'">'+_6a+'</hsyncvalues>';this.isSending=false;}
return _4i;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_6,_4){this.id=_6;this.type='[HValue]';this.value=_4;this.views=[];HValueManager.add(_6,this);},set:function(_4){if(_4!=this.value){this.value=_4;HValueManager.changed(this);this.refresh();}},get:function(){return this.value;},bind:function(_I){if(_I===undefined){throw("HValueBindError: _I is undefined!");}
this.views.push(_I);_I.setValueObj(this);},unbind:function(_I){for(var _C=0;_C<this.views.length;_C++){var _6g=this.views[_C];if(_6g===_I){this.views.splice(_C);return;}}},release:function(_I){return this.unbind(_I);},refresh:function(){for(var _C=0;_C<this.views.length;_C++){var _I=this.views[_C];if(_I.value!=this.value){if(!_I._valueIsBeingSet){_I._valueIsBeingSet=true;_I.setValue(this.value);_I._valueIsBeingSet=false;}}}},toXML:function(_14){var _3a=this.id;var _4C=this.type.slice(1,-1).toLowerCase();var _3b=this.value;var _4A=typeof _3b;var _X=_3b.toString();_X=_X.replace(/&/g,'&amp;');_X=_X.replace(/</g,'&lt;');_X=_X.replace(/>/g,'&gt;');_X=_X.replace(/%/g,'%25');_X=_X.replace(/&/g,'%26');return'<'+_4C+' id="'+_3a+'" order="'+_14+'" jstype="'+_4A+'" length="'+_3b.toString().length+'">'+_X+'</'+_4C+'>';}});JSLoader=Base.extend({constructor:function(_1O){this._16=[];this._1O=_1O;this._32=null;this._1m=[];},_5O:function(_4s){var _16=jsLoader._1m.shift();console.log('resp: ',_4s);console.log('loadedJS: ',_16);console.log('jsLoader.loadedJS: ',jsLoader._16);console.log('jsLoader.currJS: ',jsLoader._1m);jsLoader._16.push(_16);eval(_4s.responseText);},load:function(_1Z){if((jsLoader._1m.indexOf(_1Z)!=-1)&&(jsLoader._16.indexOf(_1Z)!=-1)){return;}
this._1m.push(_1Z);req_args={onSuccess:function(resp){jsLoader._5O(resp);},onFailure:function(resp){console.log("failed to load js: "+jsLoader._1m);},method:'get',asynchronous:false};this._32=new Ajax.Request(this._1O+_1Z,req_args);}});onloader("jsLoader = new JSLoader('/gz/?js=');");HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _b=arguments;if(_b.length===0){this._1i();}
else if(_b.length==2){this._3z(_b[0],_b[1]);}
else if(_b.length==1){this._1j(_b[0]);}
else{throw"Invalid number of arguments.";}},_1i:function(){this.x=null;this.y=null;},_3z:function(x,y){this.x=x;this.y=y;},_1j:function(_d){this.x=_d.x;this.y=_d.y;},set:function(){var _b=arguments;if(_b.length===0){this._1i();}
else if(_b.length==2){this._3z(_b[0],_b[1]);}
else if(_b.length==1){this._1j(_b[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_d){_b=arguments;if((_b.length==1)&&(_b[0].type==this.type)){_d=_b[0];return new HPoint((this.x+_d.x),(this.y+_d.y));}
else if(_b.length==2){return new HPoint((this.x+_b[0]),(this.y+_b[1]));}else{return new HPoint(0,0);}},subtract:function(){_b=arguments;if((_b.length==1)&&(_b[0].type==this.type)){_d=_b[0];return new HPoint(this.x-_d.x,this.y-_d.y);}
else if(_b.length==2){return new HPoint(this.x-_b[0],this.y-_b[1]);}else{return new HPoint(0,0);}},equals:function(_d){return(this.x==_d.x&&this.y==_d.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _b=arguments;if(_b.length===0){this._1i();}else if(_b.length==4){this._3y(_b[0],_b[1],_b[2],_b[3]);}
else if(_b.length==2){this._1j(_b[0],_b[1]);}
else if(_b.length==1){this._3x(_b[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1i:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_3y:function(_F,_0i,_0M,_0W){this.top=_0i;this.left=_F;this.bottom=_0W;this.right=_0M;},_1j:function(_44,_4v){this.top=_44.y;this.left=_44.x;this.bottom=_4v.y;this.right=_4v.x;},_3x:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _b=arguments;if(_b.length===0){this._1i();}else if(_b.length==4){this._3y(_b[0],_b[1],_b[2],_b[3]);}
else if(_b.length==2){this._1j(_b[0],_b[1]);}
else if(_b.length==1){this._3x(_b[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_F){this.left=_F;this.updateSecondaryValues();},setRight:function(_0M){this.right=_0M;this.updateSecondaryValues();},setTop:function(_0i){this.top=_0i;this.updateSecondaryValues();},setBottom:function(_0W){this.bottom=_0W;this.updateSecondaryValues();},setLeftTop:function(_d){this.left=_d.x;this.top=_d.y;this.updateSecondaryValues();},setLeftBottom:function(_d){this.left=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setRightTop:function(_d){this.right=_d.x;this.top=_d.y;this.updateSecondaryValues();},setRightBottom:function(_d){this.right=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setWidth:function(_h){this.right=this.left+_h;this.updateSecondaryValues();},setHeight:function(_p){this.bottom=this.top+_p;this.updateSecondaryValues();},setSize:function(){var _b=arguments;if(_b.length===2){_h=_b[0];_p=_b[1];}
else if(_b.length===1){_h=_b.x;_p=_b.y;}
this.right=this.left+_h;this.bottom=this.top+_p;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_j){if(_j instanceof HPoint){return this._58(_j);}
else if(_j instanceof HRect){return this._59(_j);}
else{throw"Wrong argument type.";}},_58:function(_d){return(_d.x>=this.left&&_d.x<=this.right&&_d.y>=this.top&&_d.y<=this.bottom);},_59:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _b=arguments;if(_b.length===1){this._5x(_b[0]);}else if(_b.length==2){this._3Y(_b[0],_b[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5x:function(_d){this._3Y(_d.x,_d.y);},_3Y:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _b=arguments;if(_b.length===1){this._5M(_b[0]);}else if(_b.length==2){this._49(_b[0],_b[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5M:function(_d){this._49(_d.x,_d.y);},_49:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _b=arguments;if(_b.length===1){this._5N(_b[0]);}else if(_b.length==2){this._4a(_b[0],_b[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5N:function(_d){this._4a(_d.x,_d.y);},_4a:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_j){},unbind:function(_j){}});HDefaultApplicationInterval=20;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _14=0;_14<this.apps.length;_14++){if(this.apps[_14]){if(!this.busyApps[_14]){if((this.ticks%this.appPriorities[_14])==0){this.appTimers[_14]=setTimeout('if (HSystem.apps['+_14+']) {HSystem.apps['+_14+']._4y();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._6O=setTimeout('HSystem.ticker();',10);},addApp:function(_0V,_0g){if(this.freeAppIds.length>200){var _14=this.freeAppIds.shift();this.apps[_14]=_0V;}else{this.apps.push(_0V);var _14=this.apps.length-1;}
_0V.parent=this;_0V.parents=[this];_0V.appId=_14;this.startApp(_14,_0g);return _14;},startApp:function(_14,_0g){if(_0g===undefined){_0g=this.defaultInterval;}
this.appPriorities[_14]=_0g;this.busyApps[_14]=false;},stopApp:function(_14){this.busyApps[_14]=true;},reniceApp:function(_14,_0g){this.appPriorities[_14]=_0g;},killApp:function(_14,_5k){if(!_5k){var _65=new Date().getTime();while(this.busyApps[_14]==true){if(new Date().getTime()>_65+this.maxAppRunTime){break;}}}
this.busyApps[_14]=true;this.apps[_14].destroyAllViews();delete this.apps[_14];this.apps[_14]=null;this.freeAppIds.push(_14);}});onloader('HSystem.ticker();');HApplication=HClass.extend({constructor:function(_0g){this.type='[HApplication]';this.views=[];this.recycleableViewIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_0g);},buildParents:function(_B){_B.parent=this;_B.parents=[];for(var _0J=0;_0J<this.parents.length;_0J++){_B.parents.push(this.parents[_0J]);}
_B.parents.push(this);},addView:function(_B){this.buildParents(_B);this.viewsZOrder.push(_B);if(this.recycleableViewIds.length>100){var _v=this.recycleableViewIds.shift();this.views[_v]=_B;}else{this.views.push(_B);var _v=this.views.length-1;}
return _v;},removeView:function(_v){if(this.views[_v]){this.views[_v].remove();}},destroyView:function(_v){if(this.views[_v]){this.views[_v].die();}},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}},_5U:function(){for(var _C=0;_C<this.views.length;_C++){if(this.views[_C]){this.views[_C].onIdle();}}},_4y:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._5U();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2k={};this._1R={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_S){this.themePath=_S;},_5g:function(_n){console.log("ERROR: Template Not Found: '"+_n+"' ");},_5f:function(_n){console.log("ERROR: Template Failure: '"+_n+"' ");},_5e:function(_n){console.log("ERROR: Template Exception: '"+_n+"' ");},fetch:function(_n,_0C){var _4u;if(!_0C){var _0C='text/html; charset=UTF-8';}
var _32=new Ajax.Request(_n,{method:'GET',onSuccess:function(_6s){_4u=_6s.responseText;},on404:function(){HThemeManager._5g(_n);},onFailure:function(){HThemeManager._5f(_n);},onException:function(){HThemeManager._5e(_n);},asynchronous:false,contentType:_0C});_32.onStateChange();return _4u;},getThemeGfxPath:function(){var _l=this._1S[0];var _o=this._1S[1];var _8=this._1S[2];var _G=this._1S[3];var _0A=this._0A(_l,_o,_8,_G);return this._U(_0A,'gfx/');},getCssFilePath:function(_0t){return"url('"+this._U(this.getThemeGfxPath(),_0t);+"')";},loadCSS:function(_n){var _0C='text/css';var _0D=this.fetch(_n,_0C);if(!_0D||_0D==""){return;}
_0D=this._3s(_0D);var _0h,_1D,_1V;if(is_ie){_0h=_05.createStyleSheet();_0h.cssText=_0D;}
else{_0h=_05.createElement("style");_0h.type=_0C;_0h.media="all";_1V=_05.getElementsByTagName('head')[0];_1V.appendChild(_0h);if(navigator.userAgent.indexOf('KHTML')!=-1){var _5d=_05.createTextNode(_0D);_0h.appendChild(_5d);}
else{_0h.innerHTML=_0D;}}},_4W:function(_2g){if(_2g[_2g.length-1]!='/'){_2g+='/';}
return _2g;},_U:function(_66,_67){return this._4W(_66)+_67;},_0A:function(_l,_o,_8,_G){var _S=_8;if(_8===null){_S=this.themePath;}
if(HThemeMode==0){if(_G){_S=this._U(_S,_G);}
if(_8===null){_S=this._U(_S,_o);_S=this._U(_S,'themes');}
_S=this._U(_S,_l);}
else if(HThemeMode==1){_S=this._U(_S,_l);}
return _S;},_1T:function(_l,_o,_8,_G){this._1S=[_l,_o,_8,_G];var _5b=this._0A(_l,_o,_8,_G);var _5c=this._U('css',_o+'.css');var _1T=this._U(_5b,_5c);return _1T;},_2O:function(_l,_o,_8,_G){var _5r=this._0A(_l,_o,_8,_G);var _5s=this._U('html',_o+'.html');var _5t=this._U(_5r,_5s);return _5t;},loadMarkup:function(_l,_o,_8,_G){if(!this._2k[_l]){this._2k[_l]={};}
var _y=this._2k[_l][_o];if(null===_y||undefined===_y){var _2O=this._2O(_l,_o,_8,_G);_y=this.fetch(_2O);if(null===_y||undefined===_y){_y="";}
this._2k[_l][_o]=_y;}
return _y;},getMarkup:function(_l,_o,_8,_G){if(!this._1R[_l]){var _55=this._1T(_l,'common',_8,null);this._1R[_l]={};this.loadCSS(_55);}
if(!this._1R[_l][_o]){var _56=this._1T(_l,_o,_8,_G);this._1R[_l][_o]=true;this.loadCSS(_56);}
return this.loadMarkup(_l,_o,_8,_G);},_1P:function(_l,_o,_8,_G){var _0A=this._0A(_l,_o,_8,_G);var _n=this._U(_0A,'gfx/');return _n;},_57:function(_l,_o,_8,_G,_0t){return this._U(this._1P(_l,_o,_8,_G),_0t);},getThemeGfxFile:function(_0t){return this.getThemeGfxPath()+_0t;},setTheme:function(_4H){this.currentTheme=_4H;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_0T:new RegExp(/#\{([^\}]*)\}/),_3s:function(_1l){while(this._0T.test(_1l)){_1l=_1l.replace(this._0T,eval(RegExp.$1));}
return _1l;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _1v=this.markup;var _ID=this.elemId.toString();var _WIDTH=this.rect.width;var _HEIGHT=this.rect.height;while(HMarkupView._0T.test(_1v)){_1v=_1v.replace(HMarkupView._0T,eval(RegExp.$1));}
this.markup=_1v;},toggleCSSClass:function(_09,_1k,_4w){if(_09){var _3U=helmi.Element.hasClassName(_09,_1k);if(_4w){if(!_3U){helmi.Element.addClassName(_09,_1k);}}
else{if(_3U){helmi.Element.removeClassName(_09,_1k);}}}}},{_0T:new RegExp(/#\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,constructor:function(_1,_7){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;this.resizeElements=[];this._4p=false;this._35=[];this.hasResizeElements=false;this.optimizeWidthOnRefresh=true;this.parent=_7;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.recycleableViewIds=[];this.viewsZOrder=[];this._5a();prop_set(this.elemId,'display','none',true);if(this.isAbsolute){prop_set(this.elemId,'position','absolute',true);}else{prop_set(this.elemId,'position','relative',true);}
prop_set(this.elemId,'overflow','hidden',true);this.setRect(_1);this.isHidden=false;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this._3t=_1.left;this._3v=_1.top;this._12=[];if(!this.isinherited){this.draw();}},setFlexRight:function(_5,_W){if(_5===undefined){_5=true;}
this.flexRight=_5;if(_W===undefined){_W=0;}
this.flexRightOffset=_W;},setFlexLeft:function(_5,_W){if(_5===undefined){_5=true;}
this.flexLeft=_5;if(_W!==undefined){this.rect.setLeft(_W);}},setFlexTop:function(_5,_W){if(_5===undefined){_5=true;}
this.flexTop=_5;if(_W!==undefined){this.rect.setTop(_W);}},setFlexBottom:function(_5,_W){if(_5===undefined){_5=true;}
this.flexBottom=_5;if(_W===undefined){_W=0;}
this.flexBottomOffset=_W;},setAbsolute:function(_5){if(_5===undefined){_5=true;}
this.isAbsolute=_5;},setRelative:function(_5){if(_5===undefined){_5=true}
this.isAbsolute=(!_5);},getThemeGfxPath:function(){if(this.preserveTheme){_l=this.theme;}else{_l=HThemeManager.currentTheme;}
return HThemeManager._1P(_l,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0t){if(this.preserveTheme){_l=this.theme;}else{_l=HThemeManager.currentTheme;}
return HThemeManager._57(_l,this.componentName,this.themePath,this.packageName,_0t);},addResizeableElement:function(_34){var _4o=_34[0];if(this._35.indexOf(_4o)==-1){this._35.push(_4o);this.resizeElements.push(_34);}
this.addResizeableElementCalled=true;return'';},initResizeElements:function(){for(var _0L=0;_0L<this.resizeElements.length;_0L++){var _c=this.bindDomElement(this._35[_0L]);this.resizeElements[_0L][0]=_c;}
this._4p=true;if(this.resizeElements.length!=0){this.hasResizeElements=true;}},doResizeElements:function(){for(var _0L=0;_0L<this.resizeElements.length;_0L++){var _2c=this.resizeElements[_0L];var _4=Math.max(this.rect.width+_2c[1],0);prop_set(_2c[0],'width',_4+'px');_4=Math.max(this.rect.height+_2c[2],0);prop_set(_2c[0],'height',_4+'px');}},_5a:function(){if(!this.elemId){var _2U;if(this.parent.elemId===undefined){_2U=0;}
else{_2U=this.parent.elemId;}
this.elemId=elem_mk(_2U);this.setStyle('visibility','hidden',true);helmi.Element.addClassName(elem_get(this.elemId),HThemeManager.currentTheme);}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
if(!this._4p&&this.addResizeableElementCalled){this.initResizeElements();}
if(this.hasResizeElements){this.doResizeElements();}
this.drawn=true;var _c=this.elemId;var _1=this.rect;if(this.flexLeft){prop_set(_c,'left',_1.left+'px',true);}else{prop_set(_c,'left','auto',true);}
if(this.flexTop){prop_set(_c,'top',_1.top+'px',true);}else{prop_set(_c,'top','auto',true);}
if(this.flexRight){prop_set(_c,'right',this.flexRightOffset+'px',true);}else{prop_set(_c,'right','auto',true);}
if(this.flexBottom){prop_set(_c,'bottom',this.flexBottomOffset+'px',true);}else{prop_set(_c,'bottom','auto',true);}
if(this.flexLeft&&this.flexRight){prop_set(_c,'width','auto',true);}else{prop_set(_c,'width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){prop_set(_c,'height','auto',true);}else{prop_set(_c,'height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){prop_set(_c,'visibility','inherit',true);}
prop_set(_c,'display','block',true);this._4N();if(this._3t!=_1.left||this._3v!=_1.top){this.invalidatePositionCache();this._3t=_1.left;this._3v=_1.top;}
if(is.ie6&&!this.ie_resizefixadded){_0S(elem_get(this.elemId));this.ie_resizefixadded=true;}},_4N:function(){prop_set(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this),true);},_2l:function(){var _3j=this.parent.viewsZOrder;for(var i=0;i<_3j.length;i++){if(_3j[i].elemId){prop_set(_3j[i].elemId,'z-index',i,true);}}},draw:function(){this.drawRect();},_45:function(){var _l;if(this.preserveTheme){_l=this.theme;}
else{_l=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_l,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){prop_set(this.elemId,'display','none',true);this._45();this.bindMarkupVariables();elem_set(this.elemId,this.markup);this.markupElemIds={};var _4j=['bg','label','state','control','value','subview'];for(var i=0;i<_4j.length;i++){var _0e=_4j[i];var _3J=_0e+this.elemId;var _5q=' id="'+_3J+'"';if(this.markup.indexOf(_5q)!=-1){this.markupElemIds[_0e]=this.bindDomElement(_3J);}}
prop_set(this.elemId,'display','block',true);if(is.ie6&&!this.ie_htmlresizefixadded){_0S(elem_get(this.elemId));this.ie_htmlresizefixadded=true;}},setHTML:function(_1X){elem_set(this.elemId,_1X);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_e,_4,_2w){if(!this.elemId){return;}
prop_set(this.elemId,_e,_4,_2w);},style:function(_e){if(!this.elemId){return;}
return prop_get(this.elemId,_e);},setStyleForPart:function(_0e,_e,_4,_2w){if(!this.markupElemIds[_0e]){return;}
prop_set(this.markupElemIds[_0e],_e,_4,_2w);},styleForPart:function(_0e,_e){if(!this.markupElemIds[_0e]){return;}
prop_get(this.markupElemIds[_0e],_e);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){this.parent.viewsZOrder.splice(this.parent.viewsZOrder.indexOf(this),1);var _4e=this.parent.views.indexOf(this);this.parent.views[_4e]=null;this.parent.recycleableViewIds.push(_4e);this._2l();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}
this.remove();for(var i=0;i<this._12.length;i++){elem_del(this._12[i]);}
this._12=[];elem_del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var _C=0;_C<this.views.length;_C++){if(this.views[_C]){this.views[_C].onIdle();}}},buildParents:function(_B){_B.parent=this;_B.parents=[];for(var _0J=0;_0J<this.parents.length;_0J++){_B.parents.push(this.parents[_0J]);}
_B.parents.push(this);},addView:function(_B){this.buildParents(_B);this.viewsZOrder.push(_B);if(this.recycleableViewIds.length>100){var _v=this.recycleableViewIds.shift();this.views[_v]=_B;}else{this.views.push(_B);var _v=this.views.length-1;}
return _v;},removeView:function(_v){if(this.views[_v]){this.views[_v].remove();}},destroyView:function(_v){if(this.views[_v]){this.views[_v].die();}},bounds:function(){var _0B=new HRect(this.rect);_0B.right-=_0B.left;_0B.left=0;_0B.bottom-=_0B.top;_0B.top=0;return _0B;},resizeBy:function(_2F,_1G){var _1=this.rect;_1.right+=_2F;_1.bottom+=_1G;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_h,_p){var _1=this.rect;_1.right=_1.left+_h;_1.bottom=_1.top+_p;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_2F,_1G){this.rect.offsetBy(_2F,_1G);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _J=this.zIndex();this.parent.viewsZOrder.splice(_J,1);this.parent.viewsZOrder.push(this);this._2l();},sendToBack:function(){if(!this.parent){return;}
var _J=this.zIndex();this.parent.viewsZOrder.splice(_J,1);this.parent.viewsZOrder.splice(0,0,this);this._2l();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this);},stringWidth:function(_2h,_20,_c){if(_20!==undefined&&_20!=null){_2h=_2h.substring(0,_20);}
if(_c===undefined||_c==null){_c=this.elemId;}
var _0q=elem_mk(_c);prop_set(_0q,"visibility","hidden",true);prop_set(_0q,"position","absolute",true);prop_set(_0q,"white-space","nowrap",true);elem_set(_0q,_2h);var _h;var _p;if(is_ie||is.opera){_h=elem_get(_0q).offsetWidth;if(arguments[3]){_p=elem_get(_0q).offsetHeight;}}else{_h=prop_get(_0q,"width");if(arguments[3]){_p=prop_get(_0q,"height");}}
elem_del(_0q);if(arguments[3]){return new HPoint(parseInt(_h,10),parseInt(_p,10));}else{return parseInt(_h,10);}},pageX:function(){var _8=0;var _9=this;while(_9){if(_9.elemId&&_9.rect){_8+=elem_get(_9.elemId).offsetLeft;_8-=elem_get(_9.elemId).scrollLeft;}
_9=_9.parent;}
return _8;},pageY:function(){var _a=0;var _9=this;while(_9){if(_9.elemId&&_9.rect){_a+=elem_get(_9.elemId).offsetTop;_a-=elem_get(_9.elemId).scrollTop;}
_9=_9.parent;}
return _a;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].invalidatePositionCache();}}},bindDomElement:function(_Z){var _2v=elem_bind(_Z);if(_2v){this._12.push(_2v);}
return _2v;},unbindDomElement:function(_09){var _3X=this._12.indexOf(_09);if(_3X>-1){elem_del(_09);this._12.splice(_3X,1);}},animateTo:function(_j,_0r,_0G){if(_j instanceof HPoint){var _1=new HRect(_j,_j);_1.setSize(this.rect.width,this.rect.height);this._2t(_1,_0r);}
else if(_j instanceof HRect){this._2t(_j,_0r);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._1N){window.clearInterval(this._1N);this._1N=null;var _F=parseInt(this.style('left'),10);var _0i=parseInt(this.style('top'),10);var _h=parseInt(this.style('width'),10);var _p=parseInt(this.style('height'),10);this.rect.set(_F,_0i,_F+_h,_0i+_p);if(this._3q){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_2t:function(_1,_0r,_0G){if(null===_0r||undefined===_0r){_0r=500;}
if(null===_0G||undefined===_0G||_0G<1){_0G=50;}
if(!this._1N){this._3q=false;this.onAnimationStart();var _64=new Date().getTime();var _r=this;this._1N=window.setInterval(function(){_r._6v({startTime:_64,duration:_0r,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_r.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_r.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_r.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_r.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0G));}},_6v:function(_j){var _4J=new Date().getTime();if(_4J<_j.startTime+_j.duration){var _51=_4J-_j.startTime;for(var i=0;i<_j.props.length;i++){var _2E=_j.props[i].from;var _4L=_j.props[i].to;if(_2E!=_4L){var _5W=_j.transition(_51,_2E,(_4L-_2E),_j.duration);this.setStyle(_j.props[i].prop,_5W+_j.props[i].unit);}}}else{for(var i=0;i<_j.props.length;i++){this.setStyle(_j.props[i].prop,_j.props[i].to+_j.props[i].unit);}
this._3q=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7);}
else{this.isinherited=true;this.base(_1,_7);this.isinherited=false;}
if(!_2){_2={};}
var options=new(HComponentDefaults.extend(_2));this.options=options;var _u=options.label;this.setLabel(_u);var _1n=options.events;this.setEvents(_1n);this.type='[HControl]';this.refreshOnValueChange=true;if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _5y=(_2.minValue||_2.maxValue);if(_5y){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(null!==options.visible&&undefined!==options.visible){if(options.visible){this.show();}
else{this.hide();}}
if(!this.isinherited){this.draw();}},setAction:function(_3m){this.action=_3m;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
HEventManager.unregister(this);this.base();},setLabel:function(_u){this.label=_u;this.refresh();},setEnabled:function(_5){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].setEnabled(_5);}}
if(this.enabled==_5){return;}
this.enabled=_5;if(_5){HEventManager.register(this,this.events);}
else{HEventManager.unregister(this);}
this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_DISABLED,!this.enabled);},setValue:function(_4){if(_4==undefined){return;}
if(!this.valueObj){return;}
if(_4!==this.value){this.value=_4;this.valueObj.set(this.value);if(this.refreshOnValueChange){this.refresh();}}},setValueObj:function(_2q){this.valueObj=_2q;this.setValue(_2q.value);},setValueRange:function(_4,_26,_23){this.minValue=_26;this.maxValue=_23;_4=(_4<_26)?_26:_4;_4=(_4>_23)?_23:_4;this.setValue(_4);this.refresh();},setEvents:function(_1n){if(!this.events){var _5i=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false});this.events=new _5i;}
if(_1n){this.events.extend(_1n);}
this.events.owner=this;HEventManager.focusOptions[this.elemId]=this.events;var _46=this.events.mouseMove;var _2Q=HEventManager.mouseMoveItems.indexOf(this.elemId);if(_46&&(_2Q==-1)){HEventManager.mouseMoveItems.push(this.elemId);}else if((!_46)&&(_2Q!=-1)){HEventManager.split(_2Q);}
this.isDragged=false;},setMouseMove:function(_5){this.events.mouseMove=_5;this.setEvents();},setMouseDown:function(_5){this.events.mouseDown=_5;this.setEvents();},setMouseUp:function(_5){this.events.mouseUp=_5;this.setEvents();},setMouseWheel:function(_5){this.events.mouseWheel=_5;this.setEvents();},setDraggable:function(_5){this.events.draggable=_5;this.setEvents();},setDroppable:function(_5){this.events.droppable=_5;this.setEvents();},setKeyDown:function(_5){this.events.keyDown=_5;this.setEvents();},setKeyUp:function(_5){this.events.keyUp=_5;this.setEvents();},focus:function(){},blur:function(){},gainedActiveStatus:function(_0d){},_6y:function(_0d){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_0d);},lostActiveStatus:function(_K){},_6G:function(_K){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_K);},mouseMove:function(_8,_a){},mouseDown:function(_8,_a,_P){},mouseUp:function(_8,_a,_P){},mouseWheel:function(_T){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_E){},keyUp:function(_E){},_5F:function(e){if(!Event.element){return;}
var _r=Event.element(e);while(_r&&_r.owner===undefined){_r=_r.parentNode;}
if(!_r){return;}
var _3=_r.owner;HEventManager.focus(_3);Event.stop(e);},_5E:function(e){if(!Event.element){return;}
var _r=Event.element(e);while(_r&&_r.owner===undefined){_r=_r.parentNode;}
if(!_r){return;}
var _3=_r.owner;HEventManager.blur(_3);Event.stop(e);},invalidatePositionCache:function(){this.base();HEventManager.invalidatePositionCache(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_6,_4){this.id=_6;this.value=_4;this.type='[HDummyValue]';},set:function(_4){this.value=_4;},get:function(){return this.value;},bind:function(_1E){},unbind:function(_1E){}});HComponentDefaults=HClass.extend({label:"Untitled",events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});