
var HClass=function(){if(arguments.length){var _3D=arguments[0];if(this==window){HClass.prototype.extend.call(_3D,arguments.callee.prototype);}else{this.extend(_3D);}}};HClass.prototype={extend:function(_10,_4){var _1C=HClass.prototype.extend;if(arguments.length==2){var _2J=this[_10];if((_2J instanceof Function)&&(_4 instanceof Function)&&_2J.valueOf()!=_4.valueOf()&&/\bbase\b/.test(_4)){var _39=_4;_4=function(){var _07=this.base;this.base=_2J;var _6z=_39.apply(this,arguments);this.base=_07;return _6z;};_4.valueOf=function(){return _39;};_4.toString=function(){return String(_39);};}
return this[_10]=_4;}else if(_10){var _0w={toSource:null};var _4S=["toString","valueOf"];if(HClass._3k){_4S.push("constructor");}
for(var i=0;(_1h=_4S[i]);i++){if(_10[_1h]!=_0w[_1h]){_1C.call(this,_1h,_10[_1h]);}}
for(var _1h in _10){if(!_0w[_1h]){_1C.call(this,_1h,_10[_1h]);}}}
return this;},base:function(){}};HClass.extend=function(_0t,_3s){var _1C=HClass.prototype.extend;if(!_0t){_0t={};}
HClass._3k=true;var _0w=new this;_1C.call(_0w,_0t);var _24=_0w.constructor;_0w.constructor=this;delete HClass._3k;var _0V=function(){if(!HClass._3k){_24.apply(this,arguments);}
this.constructor=_0V;};_0V.prototype=_0w;_0V.extend=this.extend;_0V.implement=this.implement;_0V.toString=function(){return String(_24);}
_1C.call(_0V,_3s);var _3d=_24?_0V:_0w;if(_3d.init instanceof Function){_3d.init();}
return _3d;};HClass.implement=function(_1G){if(_1G instanceof Function){_1G=_1G.prototype;}
this.prototype.extend(_1G);}
var Base=HClass;ie_htc_path=null;function ie_early_fixes(){var b=navigator.appName;var ua=navigator.userAgent.toLowerCase();var _6o=ua.indexOf("opera")>-1;if(!_6o&&b=="Microsoft Internet Explorer"){var _6B=document.scripts[document.scripts.length-1];var _54=_6B.src;ie_htc_path=_54.substring(0,_54.lastIndexOf("/")+1);}}
ie_early_fixes();is_safari=navigator.userAgent.toLowerCase().indexOf("safari")>-1;is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Event=HClass.extend({constructor:null,element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(is_ie||is_safari){return(e.button==1);}else{return(e.button==0);}},observers:false,_6j:function(_9,_1h,_0e,_09){if(!Event.observers){Event.observers=[];}
if(_9.addEventListener){this.observers.push([_9,_1h,_0e,_09]);_9.addEventListener(_1h,_0e,_09);}else if(_9.attachEvent){this.observers.push([_9,_1h,_0e,_09]);_9.attachEvent("on"+_1h,_0e);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_9,_1h,_0e,_09){if(typeof _9=="string"){_9=document.getElementById(_9);}
_09=_09||false;Event._6j(_9,_1h,_0e,_09);},stopObserving:function(_9,_1h,_0e,_09){if(typeof _9=="string"){_9=document.getElementById(_9);}
_09=_09||false;if(_9.removeEventListener){_9.removeEventListener(_1h,_0e,_09);}else if(detachEvent){try{element.detachEvent("on"+name,_0e);}catch(e){}}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_9&&eo[1]==_1h&&eo[2]==_0e&&eo[3]==_09){Event.observers[i]=null;Event.observers.splice(i,1);}else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34});if(is_ie){Event.observe(window,"unload",Event.unloadCache,false);}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length;var _3J=[];for(i=0;i<l;i++){_3J.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _3J.join("&");}
Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_o,_3){this.transport=Ajax.getTransport();if(!_3){_3={};}
var _B=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_B=_B.extend(_3);this.options=new _B();this.request(_o);},request:function(_o){this.url=_o;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _k=this;this.transport.onreadystatechange=function(){_k.onStateChange()};this.setRequestHeaders();var _5x=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_5x);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1P=this.transport.readyState;if(_1P>1){this.respondToReadyState(_1P);}},respondToReadyState:function(_1P){if(_1P==4){try{(this.options["on"+(this.success()?"Success":"Failure")]||(function(){}))(this.transport);}catch(e){console.log(e);}}
if(_1P==4){this.transport.onreadystatechange=function(){};}},success:function(){return!this.transport.status||(this.transport.status>=200&&this.transport.status<300);}});frameskips=1;var _q=document;var _1f=0;var quot='"';var apos="'";is_ie=(_q.all&&navigator.userAgent.indexOf("Opera")==-1);is_ie6=(is_ie&&navigator.userAgent.indexOf("MSIE 6")!=-1);is_ie7=(is_ie&&navigator.userAgent.indexOf("MSIE 7")!=-1);is_safari=(navigator.userAgent.indexOf("KHTML")!=-1);var _2T=[];var _49=false;onloader=function(_3t){if(_49){eval(_3t);}else{_2T.push(_3t);}};var _6n=null;var _4I=function(_2d){if(_2d){_49=true;while(_2T.length!=0){var _63=_2T.shift();eval(_63);}}else{_6n=setTimeout('_4H()',10);}};var _4H=function(){var _2d=false;if(is_ie){var _4l="javascript:void(0)";if(location.protocol=="https:"){_4l="src=//0";}
_q.write("<scr"+"ipt id=_5q defer src="+_4l+"><\/scr"+"ipt>");var _62=_q.getElementById("_5q");_62.onreadystatechange=function(){if(this.readyState=="complete"){_4I(true);}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(_q.readyState))){_2d=true;}
else if(document.body){_2d=true;}
_4I(_2d);};_4H();var _2q;var _a=[];var _1s=[];var _1X=[];var _2D=[];var _2E={};var _2F=false;var _18=[];var prop_do_csstext=false;elem_bind=function(_42){var _9=_q.getElementById(_42);if(!_9){return false;}
var _8=_2H(_9);_1X[_8]=[];_1s[_8]=[];return _8;};elem_add=function(_9){var _8=_2H(_9);_1X[_8]=[];_1s[_8]=[];return _8;};elem_get=function(_8){return _a[_8];};elem_set=function(_8,_2c){_a[_8].innerHTML=_2c;};elem_del=function(_8){var _3w=_a[_8];if(_3w){var _4M=_3w.parentNode;if(_4M){_4M.removeChild(_3w);}}
_a[_8]=null;_1X[_8]=[];_1s[_8]=[];_18.push(_8);};elem_replace=function(_8,_9){var _4c=_18.indexOf(_8);if(_4c>-1){_18.splice(_4c,1);}
_a[_8]=_9;};elem_append=function(_3f,_8){_a[_3f].appendChild(_a[_8]);};elem_mk=function(_3f,_3y){if(_3y===undefined){_3y='div';}
var _9=_q.createElement(_3y);_a[_3f].appendChild(_9);var _8=_2H(_9);_1X[_8]=[];_1s[_8]=[];return _8;};elem_count=function(){var _44=0;for(var i=0;i<_a.length;i++){if(_a[i]){_44++;}}
return _44;};_2H=function(_9){var _8;if(_18.length>0){var _5R=_18[0];_18.splice(0,1);_a[_5R]=_9;_8=_5R;}
else{_a.push(_9);_8=_a.length-1;}
return _8;};styl_get=function(_8,_1h){return prop_get(_8,_1h);};var _1O="prop_get = function(_8,_1h,_2Q){var _A = _1s[_8];if((_A[_1h]===undefined)||(_2Q!==undefined)){";_1O+="if((_1h == 'opacity') && (_2Q != -1)) {var _2r = prop_get_opacity(_8);} else {";if(!is_ie){_1O+="var _2r = _q.defaultView.getComputedStyle(_a[_8],null).getPropertyValue(_1h);";}else{_1O+="var _5A = _1h.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4});var _2r = _a[_8].currentStyle[_5A];";}
_1O+="}_A[_1h]=_2r;}return _A[_1h];};";onloader(_1O);styl_set=function(_8,_1h,_4){try{prop_set(_8,_1h,_4);return true;}
catch(e){return false;}};prop_set=function(_8,_1h,_4,_2Q){var _A=_1s[_8];var _6g=_A[_1h]!=_4;if(_6g){_A[_1h]=_4;if(_2Q){if(_1h=='opacity'){prop_set_opacity(_8,_4);}
else{try{is_ie?(_a[_8].style.setAttribute(_1h.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_A[_1h])):(_a[_8].style.setProperty(_1h,_A[_1h],''));}
catch(e){_a[_8].cssText+=';'+_1h+': '+_A[_1h]+';';}}}else{var _5z=_2D;var _3O=_1X[_8];_3O.push(_1h);if(!_2E[_8]){_5z.push(_8);_2E[_8]=true;}}}};var _0v="var _6w=function(_8){var _3O=_1X[_8];var _A=_1s[_8];var _9=_a[_8];if(!_9){return}var _2S=_9.style;var _7m=_3O.length;";if(prop_do_csstext){_0v+="var _3X=[];";}
_0v+="for(var _3R=0;_3R<_7m;_3R++){var _1h=_3O.shift();";if(prop_do_csstext){_0v+="_3X.push(_1h+':'+_A[_1h]);}_2S.cssText += ';'+_3X.join(';')+';';";}else{_0v+="if(_1h == 'opacity') { _2r = prop_set_opacity(_8, _A[_1h]); } else {";if(is_ie){_0v+="_2S.setAttribute(_1h.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_A[_1h]);}";}
else{_0v+="_2S.setProperty(_1h,_A[_1h],'');}";}
_0v+="};";}
_0v+="}";eval(_0v);var _4N='prop_loop_start(_1f)';var _6x=1;var _3i=1;var prop_loop_start=function(_1f){clearTimeout(_2q);if(_2F){_1f*=2;_2q=setTimeout(_4N,_1f);return;}else{_1f=parseInt(frameskips*(_3i/_6x),10);if(_1f<40){_1f=40;}
_2F=true;_2q=setTimeout(_4N,_1f);}
_3i-=now();var _6b=_2D.length;for(var i=0;i<_6b;i++){var _8=_2D.shift();_2E[_8]=false;_6w(_8);}
_6x++;_3i+=now();_2F=false;return;};var prop_loop_stop=function(){clearTimeout(_2q);};var now=function(){return new Date().getTime();};var prop_get_opacity=function(_8){var _06;var _5h=prop_get(_8,'opacity',-1);if(_06=_5h||(_5h==0)){return parseFloat(_06);}
if(_06=(_a[_8].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_06[1]){return parseFloat(_06[1])/100;}}
return 1.0;};var prop_set_opacity=function(_8,_4){if(_4==1&&is_ie){_a[_8].style.setAttribute('filter',prop_get(_8,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_4<0.00001)_4=0;if(is_ie){_a[_8].style.setAttribute('filter',prop_get(_8,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_4*100+')');}
else{_a[_8].style.setProperty('opacity',_4,'');}}};var prop_get_extra_width=function(_8){var _h=prop_get_int_value(_8,'padding-left')+
prop_get_int_value(_8,'padding-right')+
prop_get_int_value(_8,'border-left-width')+
prop_get_int_value(_8,'border-right-width');return _h;};var prop_get_extra_height=function(_8){var _r=prop_get_int_value(_8,'padding-top')+
prop_get_int_value(_8,'padding-bottom')+
prop_get_int_value(_8,'border-top-width')+
prop_get_int_value(_8,'border-bottom-width');return _r;};var prop_get_int_value=function(_8,_4R){var _30=parseInt(prop_get(_8,_4R,true),10);if(isNaN(_30)){_30=0;}
return _30;};onloader('elem_add(document.body);');onloader('prop_loop_start();');HEventManager=HClass.extend({events:[false,false,0,0,[],[],[],false,false,false],HStatusButton:0,HStatusButton2:1,HStatusCoordX:2,HStatusCoordY:3,HStatusKeys:4,HStatusDirection:5,HStatusSpeed:6,HStatusAltKey:7,HStatusCtrlKey:8,HStatusShiftKey:9,constructor:null,start:function(){var _0r;if(is_ie){_0r=document;}
else{_0r=window;}
Event.observe(_0r,'mousemove',this.mouseMove);Event.observe(_0r,'mouseup',this.mouseUp);Event.observe(_0r,'mousedown',this.mouseDown);Event.observe(_0r,'keyup',this.keyUp);Event.observe(_0r,'keydown',this.keyDown);Event.observe(_0r,'keypress',this.keyPress);Event.observe(_0r,'contextmenu',this.contextMenu);if(window.addEventListener){window.addEventListener('DOMMouseScroll',this.mouseWheel,false);}
window.onmousewheel=document.onmousewheel=this.mouseWheel;this.focusItems=[];this.mouseMoveItems=[];this.eventItems=[];this.focusOptions=[];this.dragItems=[];this.hoverItems=[];this.hoverInterval=100;this.hoverTimer=new Date().getTime();this.topmostDroppable=null;this._2R=[];this._46=true;this.activeControl=null;this._7k=null;},enablePositionCache:function(){this._46=true;},disablePositionCache:function(){this._46=false;},invalidatePositionCache:function(_c){if(_c){this._2R[_c]=null;}
else{this._2R=[];}},register:function(_u,_4b){var _c=_u.elemId;var _9=elem_get(_c);if(is_ie){_9.setAttribute('owner',_u);}
else{_9.owner=_u;}
this.eventItems[_c]=true;this.focusItems[_c]=false;this.focusOptions[_c]=_4b;Event.observe(_9,'mouseover',_u._6d);},unregister:function(_u){if(_u==this.activeControl){this.changeActiveControl(null);}
var _c=_u.elemId;var _9=elem_get(_c);this.eventItems[_c]=false;this.focusItems[_c]=false;this._2R[_c]=null;try{Event.stopObserving(_9,'mouseover',_u._6d);}catch(e){window.status=e;}},focus:function(_u){var _c=_u.elemId;var _9=elem_get(_c);if(this.focusItems[_c]==false&&_u.isDragged==false){Event.stopObserving(_9,'mouseover',_u._6d);Event.observe(_9,'mouseout',_u._6c);this.focusItems[_c]=true;_u.focus();}},blur:function(_u){var _c=_u.elemId;var _9=elem_get(_c);if(this.focusItems[_c]==true&&_u.isDragged==false){Event.stopObserving(_9,'mouseout',_u._6c);Event.observe(_9,'mouseover',_u._6d);this.focusItems[_c]=false;_u.blur();}},mouseMove:function(e){var _1=HEventManager;var _5=Event.pointerX(e);var _a=Event.pointerY(e);var _3Y=false;_1.events[_1.HStatusCoordX]=_5;_1.events[_1.HStatusCoordY]=_a;for(var i=0;i<_1.dragItems.length;i++){var _c=_1.dragItems[i];_1.focusOptions[_c].owner.doDrag(_5,_a);_1.invalidatePositionCache(_c);_3Y=true;}
if(new Date().getTime()>_1.hoverTimer+_1.hoverInterval){_1._7D();for(var i=0;i<_1.mouseMoveItems.length;i++){var _c=_1.mouseMoveItems[i];var _0u=_1.focusOptions[_c].owner;_0u.mouseMove(_5,_a);}
for(var i=0;i<_1.dragItems.length;i++){var _3C=_1.topmostDroppable;_1.topmostDroppable=null;var _c=_1.dragItems[i];var _0u=_1.focusOptions[_c].owner;for(var j=0;j<_1.hoverItems.length;j++){var _2b=_1.hoverItems[j];if(_2b!=_c&&_1.focusOptions[_2b].owner){var _2z=_1.focusOptions[_2b].owner;if(!_1.topmostDroppable||_2z.zIndex()>_1.topmostDroppable.zIndex()||_2z.parent==_1.topmostDroppable){if(_2z.events.droppable){_1.topmostDroppable=_2z;}}}}
if(_3C!=_1.topmostDroppable){if(_3C){_3C.onHoverEnd(_0u);}
if(_1.topmostDroppable){_1.topmostDroppable.onHoverStart(_0u);}}}
_1.hoverTimer=new Date().getTime();}
if(_3Y){Event.stop(e);}},_7D:function(){var _1=HEventManager;_1.hoverItems=[];var x=_1.events[_1.HStatusCoordX];var y=_1.events[_1.HStatusCoordY];for(var _v=0;_v<_1.eventItems.length;_v++){if(!_1.eventItems[_v]||!_1.focusOptions[_v].owner){continue;}
var _3W=_1.focusOptions[_v].owner;var _9=elem_get(_v);var _0S;if(!_1._46||!_1._2R[_v]){_1._2R[_v]={_6a:[_3W.pageX(),_3W.pageY()],_7x:helmi.Element.getVisibleSize(_9)};}
_0S=_1._2R[_v];if(x>=_0S._6a[0]&&x<=_0S._6a[0]+_0S._7x[0]&&y>=_0S._6a[1]&&y<=_0S._6a[1]+_0S._7x[1]){_1.hoverItems.push(_v);}}},mouseDown:function(e,_0U){var _1=HEventManager;_1._7o(e);var _41=false;if(_0U===undefined){_0U=Event.isLeftClick(e);}
if(_0U){_1.events[_1.HStatusButton]=true;}else{_1.events[_1.HStatusButton2]=true;}
var _5=_1.events[_1.HStatusCoordX];var _a=_1.events[_1.HStatusCoordY];var _N=null;var _2u=[];var _3b=[];for(var i=0;i<_1.focusItems.length;i++){if(_1.focusItems[i]==true){if(_1.focusOptions[i].owner.enabled){_N=_1.focusOptions[i].owner;}
if((_1.focusOptions[i].draggable==true)&&(_1.dragItems.indexOf(i)==-1)){_2u.push(i);}
else if(_1.focusOptions[i].mouseDown==true){_3b.push(i);}}}
_1.changeActiveControl(_N);for(var i=0;i<_2u.length;i++){_1.dragItems.push(_2u[i]);_1.focusOptions[_2u[i]].owner.startDrag(_5,_a);_41=true;}
for(var i=0;i<_3b.length;i++){_1.focusOptions[_3b[i]].owner.mouseDown(_5,_a,_0U);}
if(_41){document.body.focus();_1._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if(_1.hoverItems.length>0){Event.stop(e);}
return true;},changeActiveControl:function(_N){var _1=HEventManager;var _0h=_1.activeControl;if(_N!=_0h){if(_0h){_0h.active=false;_0h._7n(_N);}
_1.activeControl=null;if(_N){_N.active=true;_1.activeControl=_N;_N._7f(_0h);}}},mouseUp:function(e){var _1=HEventManager;_1._7o(e);var _40=false;_1.events[_1.HStatusButton]=false;_1.events[_1.HStatusButton2]=false;var _5=_1.events[_1.HStatusCoordX];var _a=_1.events[_1.HStatusCoordY];for(var i=0;i<_1.dragItems.length;i++){var _c=_1.dragItems[i];var _0u=_1.focusOptions[_c].owner;_0u.endDrag(_5,_a);_40=true;_1._7D();if(_1.hoverItems.indexOf(_c)<0){_1.blur(_0u);}
if(_1.topmostDroppable){_1.topmostDroppable.onHoverEnd(_0u);_1.topmostDroppable.onDrop(_0u);_1.topmostDroppable=null;}}
_1.dragItems=[];if(_40){document.onselectstart=_1._storedOnSelectStart;}
for(var _v=0;_v<_1.focusItems.length;_v++){if(_1.focusItems[_v]==true){if(_1.focusOptions[_v].mouseUp==true){_1.focusOptions[_v].owner.mouseUp(_5,_a,true);}}}
return true;},keyDown:function(e){var _1=HEventManager;_1._7o(e);var _0L=e.keyCode;if(_1.activeControl&&_1.focusOptions[_1.activeControl.elemId].keyDown==true){Event.stop(e);if(_1._7k!=_0L){_1.activeControl.keyDown(_0L);}}
var _1Q=_1.events[_1.HStatusKeys];if(_1Q.indexOf(_0L)==-1){_1Q.push(_0L);}
_1._7k=_0L;},keyUp:function(e){var _1=HEventManager;_1._7o(e);var _0L=e.keyCode;_1._7k=null;if(_1.activeControl&&_1.focusOptions[_1.activeControl.elemId].keyUp==true){_1.activeControl.keyUp(_0L);}
var _1Q=_1.events[_1.HStatusKeys];var _4q=_1Q.indexOf(_0L);if(_4q!=-1){_1Q.splice(_4q,1);}},keyPress:function(e){var _1=HEventManager;if(_1.activeControl&&_1.focusOptions[_1.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _1=HEventManager;var _Y=0;if(!e){e=window.event;}
if(e.wheelDelta){_Y=e.wheelDelta/120;if(window.opera)_Y=-_Y;}else if(e.detail){_Y=-e.detail/3;}
for(var _v=0;_v<_1.focusItems.length;_v++){if(_1.focusItems[_v]==true){if(_1.focusOptions[_v].mouseWheel==true){Event.stop(e);_1.focusOptions[_v].owner.mouseWheel(_Y);}}}},contextMenu:function(e){var _1=HEventManager;_1.mouseDown(e,false);Event.stop(e);},_7o:function(e){var _1=HEventManager;_1.events[_1.HStatusAltKey]=e.altKey;_1.events[_1.HStatusCtrlKey]=e.ctrlKey;_1.events[_1.HStatusShiftKey]=e.shiftKey;}});onloader('HEventManager.start();');ie_namespace={};function $(_0){if(typeof _0=='string')_0=document.getElementById(_0);return _0;}
helmi={};Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;}
helmi.UserAgent=function(){var b=navigator.appName;var v=navigator.appVersion;var ua=navigator.userAgent.toLowerCase();this.safari=ua.indexOf("safari")>-1;this.opera=ua.indexOf("opera")>-1;this.ns=!this.opera&&!this.safari&&(b=="Netscape");this.ie=!this.opera&&(b=="Microsoft Internet Explorer");this.gecko=!this.safari&&ua.indexOf("gecko")>-1;if(this.ns){this.ns4=(this.v==4);this.v=parseInt(ua.substr(ua.indexOf("netscape")+9,1),10);this.ns6=(this.v==6);this.ns7=(this.v==7);}else if(this.ie){this.ie4=(v.indexOf("MSIE 4")>0);this.ie5=(v.indexOf("MSIE 5")>0);this.ie55=(v.indexOf("MSIE 5.5")>0);this.ie6=(v.indexOf("MSIE 6")>0);this.ie7=(v.indexOf("MSIE 7")>0);}else if(this.opera){this.v=parseInt(ua.substr(ua.indexOf("opera")+6,1),10);this.opera6=(this.v==6);this.opera7=(this.v==7);this.opera8=(this.v==8);this.opera9=(this.v==9);}
this.win=ua.indexOf("win")>-1;this.mac=ua.indexOf("mac")>-1;}
is=new helmi.UserAgent();helmi.Element=Base.extend({constructor:null,getPageLocation:function(_0,_1q){var _U=0,_V=0;var _f;var _1N=_0;if(is.opera){if(is.opera9){do{_f=_0.offsetParent;_U+=_0.offsetLeft;_V+=_0.offsetTop;_0=_f;}while(_0);}else{if(_0.tagName.toLowerCase()=="body"){return[0,0];}
var _07;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"&&_07&&(_07.style.position=="absolute"||_07.style.position=="relative"||_07.style.position=="fixed")){}else{_U+=_0.offsetLeft;_V+=_0.offsetTop;}
if(_f&&_f.tagName.toLowerCase()=="body"&&(_0.style.position=="absolute"||_0.style.position=="relative"||_0.style.position=="fixed"||_0.tagName.toLowerCase()=="input"||_0.tagName.toLowerCase()=="button"||_0.tagName.toLowerCase()=="select"||_0.tagName.toLowerCase()=="textarea")){}else if(_f){_U+=_f.clientLeft;_V+=_f.clientTop;}
_07=_0;_0=_f;}while(_0);}}else if(is.safari){if(_0.tagName.toLowerCase()=="body"){return[0,0];}
var _07;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"&&_07&&(_07.style.position=="absolute"||_07.style.position=="fixed")){}else{_U+=_0.offsetLeft;_V+=_0.offsetTop;}
_07=_0;_0=_f;}while(_0);}else if(is.ns){if(_1q){var _0A=[];var x=_0.offsetLeft;var y=_0.offsetTop;var _47=null;do{_f=_0.offsetParent;if(_0==_1N&&_0.style.position!="absolute"){if(_f&&(_f.style.overflow=="scroll"||_f.style.overflow=="auto")){_47=_f;}}
if(_0.style.overflow=="scroll"||_0.style.overflow=="auto"){_0A.push([_0,_0.style.overflow,_0.scrollLeft,_0.scrollTop]);_0.style.overflow="inherit";}
_0=_f;}while(_0);}
_0=_1N;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"){}else{if(_0==_1N&&_0.style.position!="absolute"){_U+=x;_V+=y;}else{_U+=_0.offsetLeft;_V+=_0.offsetTop;}}
if(_f&&_f.tagName.toLowerCase()=="body"&&(_0.style.position=="absolute"||_0.style.position=="fixed")){}else if(_f){_U+=(_f.offsetWidth-_f.clientWidth)/2;_V+=(_f.offsetHeight-_f.clientHeight)/2;if(_f==_47){_U+=(_f.offsetWidth-_f.clientWidth)/2;_V+=(_f.offsetHeight-_f.clientHeight)/2;}}
_0=_f;}while(_0);if(_1q){var l=_0A.length;for(var i=0;i<l;i++){_0A[i][0].style.overflow=_0A[i][1];_0A[i][0].scrollLeft=_0A[i][2];_0A[i][0].scrollTop=_0A[i][3];}}}else if(is.ie){if(_0.tagName.toLowerCase()=="body"){return[0,0];}
do{_f=_0.offsetParent;_U+=_0.offsetLeft;_V+=_0.offsetTop;if(_f&&_f.tagName.toLowerCase()=="html"&&_0.style.position=="relative"){_U-=2;_V-=2;}
if(_f&&_f.tagName.toLowerCase()=="html"&&_0.style.position=="absolute"){}else if(_f){_U+=_f.clientLeft;_V+=_f.clientTop;}
_0=_f;}while(_0);}
if(_1q){_0=_1N;do{if(!_0.tagName||_0.tagName.toLowerCase()=="body"){break;}
if(_0.style.position=="fixed"){_U+=window.pageXOffset||document.documentElement.scrollLeft;_V+=window.pageYOffset||document.documentElement.scrollTop;}
_f=_0.parentNode;if(_0!=_1N){if(is.opera&&_0.tagName.toLowerCase()=="tr"){}else{_U-=_0.scrollLeft;_V-=_0.scrollTop;}}
_0=_f;}while(_0);}
return[_U,_V];},getSize:function(_0){return[_0.offsetWidth,_0.offsetHeight];},getVisibleSize:function(_0){var w=_0.offsetWidth;var h=_0.offsetHeight;var _s=_0.parentNode;while(_s&&_s.nodeName.toLowerCase()!='body'){var _01;if(!is.ie){_01=document.defaultView.getComputedStyle(_s,null).getPropertyValue('overflow');}else{_01=_s.currentStyle.getAttribute('overflow');}
_01=_01!='visible';if(w>_s.clientWidth&&_01){w=_s.clientWidth-_0.offsetLeft;}
if(h>_s.clientHeight&&_01){h=_s.clientHeight-_0.offsetTop;}
_0=_0.parentNode;_s=_0.parentNode;}
return[w,h];},getVisiblePageLocation:function(_0,_1q){var _0X=this.getPageLocation(_0,_1q);var x=_0X[0];var y=_0X[1];var _s=_0.parentNode;while(_s&&_s.nodeName.toLowerCase()!='body'){var _01;if(!is.ie){_01=document.defaultView.getComputedStyle(_s,null).getPropertyValue('overflow');}else{_01=_s.currentStyle.getAttribute('overflow');}
_01=_01!='visible';_0X=this.getPageLocation(_s,_1q);if(x<_0X[0]&&_01){x=_0X[0];}
if(y<_0X[1]&&_01){y=_0X[1];}
_0=_0.parentNode;_s=_0.parentNode;}
return[x,y];},hasClassName:function(_0,_1b){_0=$(_0);if(!_0)return;var _4e=false;var _1c=_0.className.split(' ');for(var i=0;i<_1c.length;i++){if(_1c[i]==_1b){_4e=true;}}
return _4e;},addClassName:function(_0,_1b){_0=$(_0);if(!_0)return;helmi.Element.removeClassName(_0,_1b);_0.className+=' '+_1b;},removeClassName:function(_0,_1b){_0=$(_0);if(!_0)return;var _3c='';var _1c=_0.className.split(' ');for(var i=0;i<_1c.length;i++){if(_1c[i]!=_1b){if(i>0)_3c+=' ';_3c+=_1c[i];}}
_0.className=_3c;}});Object.extend(Array.prototype,{indexOfObject:function(_20){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_20){return i;}}
return-1;},containsObject:function(_20){return this.indexOfObject(_20)!=-1;},removeObject:function(_20){while((i=this.indexOfObject(object))>=0){this.splice(i,1);}},first:function(){return this[0];},last:function(){return this[this.length-1];}});if(!is.ns7){Object.extend(Array.prototype,{indexOf:Array.prototype.indexOfObject});}
helmi.Window=Base.extend({constructor:null,getInnerWidth:function(){return(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;},getInnerHeight:function(){return(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;}});helmi.Event=Base.extend({constructor:null,getPageX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},getPageY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},getKeyCode:function(e){return e.keyCode;},getCharCode:function(e){if(is.ns){return e.charCode;}else{return e.keyCode;}}});HPath=HClass.extend({constructor:null,getRelativePath:function(_n,_F){var _n=this.getRelativeFilePath(_n,_F);return _n.slice(0,_n.lastIndexOf("/")+1);},getRelativeFilePath:function(_n,_F){_n=_n||"";if(_F.charAt(0)=="/"){return _F;}
var _n=_n.substring(0,_n.lastIndexOf("/")+1);var _43=_F.indexOf("../");var _3r=_n.length;var _48;while(_43==0){if((_48=_n.lastIndexOf("/",_3r))!=-1){_3r=_n.lastIndexOf("/",_48-1);_n=_n.substring(0,_3r+1);}else{break;}
_F=_F.substring(3);_43=_F.indexOf("../");}
return _n+_F;}});ie_namespace.iestyleSheetLoaded=function(){if(document.readyState=="complete"&&window.event.srcElement.readyState=="complete"){_15();}}
stylesheet_refresh=function(_1S){_1S.cssText+="";}
_15=function(_0){var _0=_0||document.documentElement;while(_0){if(_0.nodeType==1){HStyle._2Z(_0);}
var _1M=_0.firstChild;if(!_1M){_1M=_0.nextSibling;}
while(!_1M&&_0.parentNode){_0=_0.parentNode;_1M=_0.nextSibling;}
_0=_1M;}}
ie_namespace.ieinlineStyleChanged=function(){var _0=window.event.srcElement;if(window.event.propertyName=="style.opacity"){HOpacityFix._2V(_0);}
else if(window.event.propertyName=="src"&&_0.tagName=="IMG"||(_0.tagName=="INPUT"&&_0.type=="image")){HOpacityFix._2U(_0);}}
HStyle=HClass.extend({constructor:null,init:function(){this._75=/^(auto|0cm)$/;},_2Z:function(_0){var _0c=_0.currentStyle;if((_0c.position=="absolute"||_0c.position=="fixed")&&_0c.left!="auto"&&_0c.right!="auto"&&_0c.width=="auto"){HRighBottoFix._1o(_0);}
if((_0c.position=="absolute"||_0c.position=="fixed")&&_0c.top!="auto"&&_0c.bottom!="auto"&&_0c.height=="auto"){HRighBottoFix._4U(_0);}
if(_0.currentStyle.opacity){HOpacityFix._2V(_0);}
if(_0.currentStyle.backgroundImage){HOpacityFix._4a(_0);}
if(_0.tagName=="IMG"||(_0.tagName=="INPUT"&&_0.type=="image")){HOpacityFix._2U(_0);}}});HNumber=HClass.extend({constructor:null,init:function(){this._5p=/^\d+(px)?$/i;this._5o=/^\d+%$/;},getPixelValue:function(_0,_4){if(this._5p.test(_4)){return parseInt(_4);}
var _0l=_0.style.left;var _6A=_0.runtimeStyle.left;_0.runtimeStyle.left=_0.currentStyle.left;HRighBottoFix.resizing=true;_0.style.left=_4||0;_4=_0.style.pixelLeft;_0.style.left=_0l;HRighBottoFix.resizing=false;_0.runtimeStyle.left=_6A;return _4;}});HOpacityFix=HClass.extend({constructor:null,init:function(){this._4O=new RegExp(".png$","i");},_2V:function(_0){var _06=(parseFloat(_0.currentStyle.opacity)*100)||1;var _S=_0.filters["DXImageTransform.Microsoft.Alpha"];if(_S){_S.Opacity=_06;_S.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.Alpha(opacity="+_06+")";}},_4a:function(_0){var _o=_0.currentStyle.backgroundImage.match(/url\(\s*['"]?([^'")]+)['"]?\s*\)/);if(!_o){return;}else{_o=_o[1];}
var _S=_0.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(this._4O.test(_o)){if(_S){_S.sizingMethod="scale";_S.src=_o;_S.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_o+"',sizingMethod='scale')";}
_0.runtimeStyle.zoom="1";_0.runtimeStyle.backgroundImage="none";}else if(_S){_S.Enabled=false;}},_2U:function(_0){if(this._4O.test(_0.src)){var _0C=new Image(_0.width,_0.height);_0C.onload=function(){_0.width=_0C.width;_0.height=_0C.height;_0C=null;}
this._3G(_0,_0C);}},_3G:function(_0,_0C){var _S=_0.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_S){_S.src=_0.src;_S.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_0.src+"',sizingMethod='scale')";}
var _5a=_0.src;_0.src=HPath.getRelativeFilePath(_5a,"blank.gif");_0C.src=_5a;}});HRighBottoFix=HClass.extend({constructor:null,init:function(){eval("this._5T="+String(this._1E).replace(/padding/g,"margin"));eval("this._5U="+String(this._1E).replace(/Width/g,"Height").replace(/Left/g,"Top").replace(/Right/g,"Bottom"));eval("this._7h="+String(this._5U).replace(/padding/g,"margin"));eval("this._7g="+String(this._4d).replace(/Width/g,"Height"));eval("this._69="+String(this._1I).replace(/Width/g,"Height").replace(/width/g,"height").replace(/Right/g,"Bottom"));eval("this._7i="+String(this._1i).replace(/Width/g,"Height"));eval("this._4U="+String(this._1o).replace(/Width/g,"Height").replace(/width/g,"height").replace(/left/g,"top").replace(/right/g,"bottom"));this.resizing=false;},_4f:function(_0){return _0.currentStyle.hasLayout;},_1E:function(_0){return this._1i(_0,_0.currentStyle.paddingLeft)+
this._1i(_0,_0.currentStyle.paddingRight);},_4d:function(_0){return _0.offsetWidth-_0.clientWidth;},_1I:function(_0){var _05=_0.offsetParent;while(_05&&!this._4f(_05)){_05=_05.offsetParent;}
if(!_05._7s){_05._7s=[];}
if(!_0._addedResizewidthFix){_05._7s.push(_0);var _s=_05;while(_s.offsetParent){_s=_s.offsetParent;if(_s._7s){_s._7s.push(_0);}
if(_s.style.position=="absolute"||_s.style.position=="fixed"){break;}}
_0._addedResizewidthFix=true;}
if(!_05._resizewidth){_05.attachEvent("onpropertychange",function(){if(window.event.propertyName=="style.width"){for(var i=0;i<_05._7s.length;i++){HRighBottoFix._1o(_05._7s[i]);}}});_05._resizewidth=true;}
return(_05||document.documentElement).clientWidth;},_1i:function(_0,_4){if(HNumber._5o.test(_4)){return parseInt(parseFloat(_4)/100*this._1I(_0));}
return HNumber.getPixelValue(_0,_4);},_1o:function(_0){var _I=parseInt(_0.currentStyle.left);var _h=this._1I(_0)-this._1i(_0,_0.currentStyle.right)-_I-this._5T(_0);var _h=this._1I(_0)-parseInt(_0.currentStyle.right)-_I;if(parseInt(_0.runtimeStyle.width)==_h){return;}
_0.runtimeStyle.width="";if(_0.offsetWidth<_h){if(_h<0){_h=0;}
_h-=this._4d(_0)+this._1E(_0);_0.runtimeStyle.width=_h;}}});ie_complete=document.readyState=="complete";ie_initialized=false;ie_documentLoaded=function(){if(document.readyState=="complete"){_15();}}
ie_fixes=function(){if(is.ie6&&!ie_initialized){if(ie_complete){var _6I=document.createStyleSheet();_6I.cssText='style,link{behavior:url('+ie_htc_path+'ie_css_style.htc)}\n*{behavior:url('+ie_htc_path+'ie_css_element.htc)}';ie_documentLoaded();}else{document.write('<style type="text/css">style,link{behavior:url('+ie_htc_path+'ie_css_style.htc)}\n*{behavior:url('+ie_htc_path+'ie_css_element.htc)}</style>');document.onreadystatechange=ie_documentLoaded;}
ie_initialized=true;}}
ie_fixes();SHA={_4k:0,hexCase:function(){return SHA._4k;},setHexCase:function(_5B){SHA._4k=_5B;},_3K:"=",base64Pad:function(){return SHA._3K;},setBase64Pad:function(_6r){SHA._3K=_6r;},_3Q:8,chrsz:function(){return SHA._3Q;},setChrsz:function(_5w){SHA._3Q=_5w;},hexSHA1:function(_0G){var _1=SHA;return _1._79(_1._7e(_1._7y(_0G),_0G.length*_1._3Q));},b64SHA1:function(_0G){var _1=SHA;return _1._78(_1._7e(_1._7y(_0G),_0G.length*_1._3Q));},strSHA1:function(_0G){var _1=SHA;return _1._7a(_1._7e(_1._7y(_0G),_0G.length*_1._3Q));},hexHmacSHA1:function(_0E,_0y){var _1=SHA;return _1._79(_1._7d(_0E,_0y));},b64HmacSHA1:function(_0E,_0y){var _1=SHA;return _1._78(_1._7d(_0E,_0y));},strHmacSHA1:function(_0E,_0y){var _1=SHA;return _1._7a(_1._7d(_0E,_0y));},str2Base64:function(_H){var _1=SHA;return _1._78(_1._7y(_H));},test:function(){return SHA.hexSHA1("abc")=="a9993e364706816aba3e25717850c26c9cd0d89d";},_7e:function(_5,_36){var _1=SHA;_5[_36>>5]|=0x80<<(24-_36%32);_5[((_36+64>>9)<<4)+15]=_36;var _17=new Array(80),_0N=1732584193,_Q=-271733879,_X=-1732584194,_q=271733878,_1h=-1009589776,_i,_4C,_4D,_4E,_4F,_4G,_Z,_0n;for(_i=0;_i<_5.length;_i+=16){_4C=_0N;_4D=_Q;_4E=_X;_4F=_q;_4G=_1h;for(_Z=0;_Z<80;_Z++){if(_Z<16){_17[_Z]=_5[_i+_Z];}
else{_17[_Z]=_1._7t(_17[_Z-3]^_17[_Z-8]^_17[_Z-14]^_17[_Z-16],1);}
_0n=_1._7u(_1._7u(_1._7t(_0N,5),_1._7v(_Z,_Q,_X,_q)),_1._7u(_1._7u(_1h,_17[_Z]),_1._7w(_Z)));_1h=_q;_q=_X;_X=_1._7t(_Q,30);_Q=_0N;_0N=_0n;}
_0N=_1._7u(_0N,_4C);_Q=_1._7u(_Q,_4D);_X=_1._7u(_X,_4E);_q=_1._7u(_q,_4F);_1h=_1._7u(_1h,_4G);}
return[_0N,_Q,_X,_q,_1h];},_7v:function(_0n,_Q,_X,_q){if(_0n<20){return(_Q&_X)|((~_Q)&_q);}
if(_0n<40){return _Q^_X^_q;}
if(_0n<60){return(_Q&_X)|(_Q&_q)|(_X&_q);}
return _Q^_X^_q;},_7w:function(_0n){return(_0n<20)?1518500249:(_0n<40)?1859775393:(_0n<60)?-1894007588:-899497514;},_7d:function(_0E,_0y){var _1=SHA,_1w=_1._7y(_0E),_4o=new Array(16),_4J=new Array(16),_i,_4h;if(_1w.length>16){_1w=_1._7e(_1w,_0E.length*_1._3Q);}
for(_i=0;_i<16;_i++){_4o[_i]=_1w[_i]^0x36363636;_4J[_i]=_1w[_i]^0x5C5C5C5C;}
_4h=_1._7e(_4o.concat(_1._7y(_0y)),512+_0y.length*_1._3Q);return _1._7e(_4J.concat(_4h),512+160);},_7u:function(_5,_a){var _4w=(_5&0xFFFF)+(_a&0xFFFF),_6e=(_5>>16)+(_a>>16)+(_4w>>16);return(_6e<<16)|(_4w&0xFFFF);},_7t:function(_2o,_3S){return(_2o<<_3S)|(_2o>>>(32-_3S));},_7y:function(_H){var _1=SHA,_1v=[],_38=(1<<_1._3Q)-1,_6H=_H.length*_1._3Q,_i;for(_i=0;_i<_6H;_i+=_1._3Q){_1v[_i>>5]|=(_H.charCodeAt(_i/_1._3Q)&_38)<<(32-_1._3Q-_i%32);}
return _1v;},_7a:function(_1v){var _1=SHA,_H="",_38=(1<<_1._3Q)-1,_i,_2M=_1v.length*32,_5n=32-_1._3Q;for(_i=0;_i<_2M;_i+=_1._3Q){_H+=String.fromCharCode((_1v[_i>>5]>>>(_5n-_i%32))&_38);}
return _H;},_79:function(_0q){var _1=SHA,_4j=_1._4k?"0123456789ABCDEF":"0123456789abcdef",_H="",_i,_2L=_0q.length*4;for(_i=0;_i<_2L;_i++){_H+=_4j.charAt((_0q[_i>>2]>>((3-_i%4)*8+4))&0xF)+
_4j.charAt((_0q[_i>>2]>>((3-_i%4)*8))&0xF);}
return _H;},_78:function(_0q){var _1=SHA,_6M="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",_H="",_i,_2L=_0q.length*4,_5g,_Z,_2M=_0q.length*32;for(var _i=0;_i<_2L;_i+=3){_5g=(((_0q[_i>>2]>>8*(3-_i%4))&0xFF)<<16)|(((_0q[_i+1>>2]>>8*(3-(_i+1)%4))&0xFF)<<8)|((_0q[_i+2>>2]>>8*(3-(_i+2)%4))&0xFF);for(_Z=0;_Z<4;_Z++){if(_i*8+_Z*6>_2M){_H+=_1._3K;}
else{_H+=_6M.charAt((_5g>>6*(3-_Z))&0x3F);}}}
return _H;}};HTransportURL=false;HTransportPoll=true;HTransporter=Base.extend({constructor:null,start:function(_6W){this.url_base=_6W;this.ses_id=0;this.err_msg='';this.isBusy=false;this.syncNum=0;this.syncDelay=0;this.pollMode=HTransportPoll;this.req_timeout=setTimeout('HTransporter.sync();',this.syncDelay);},setPollMode:function(_7){this.pollMode=_7;},failure:function(resp){alert('HTTP ERROR! STOP.');clearTimeout(this.req_timeout);this.isBusy=true;},respond:function(resp){var _50=resp.responseText;eval(_50);HTransporter.isBusy=false;},sync:function(){var valid_delay=((this.syncDelay&&this.syncDelay>0)||this.syncDelay==0);if(valid_delay&&this.url_base){if(!this.isBusy){this.isBusy=true;var _56=HValueManager.toXML();if(""!=_56||this.pollMode){this.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){HTransporter.respond(resp);},onFailure:function(resp){HTransporter.failure(resp);},method:'post',postBody:'ses_id='+HTransporter.ses_id+_56};this.req=new Ajax.Request(this.url_base,req_args);HVM.isGetting=false;}
else{this.isBusy=false;}}
this.req_timeout=setTimeout('HTransporter.sync();',this.syncDelay);}},stop:function(){clearTimeout(this.req_timeout);}});onloader("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:[],tosync:[],isSending:false,isGetting:false,add:function(_8,_k){this.values[_8]=_k;},set:function(_8,_4){this.values[_8].set(_4);},del:function(_8){var _5c=this.values[_8];var _6X=_5c.views;for(var _E=0;_E<_6X.length;_E++){var _6Q=_6X[_E];_6Q.valueObj=new HDummyValue(0,_5c.value);}
this.values[_8]=null;},changed:function(_1T){if(this.isGetting==false){if(this.tosync.indexOf(_1T.id)==-1){this.tosync.push(_1T.id);}}},toXML:function(){var _4P='&HSyncData=';if(!this.isSending){this.isSending=true;var _6J=this.tosync.length;if(_6J==0){this.isSending=false;return'';}
var _57=[];for(var _i=0;_i<_6J;_i++){var _2x=this.tosync.shift();var _6K=this.values[_2x];_57.push(_6K.toXML(_i));}
var _6L=_57.join('');_4P+='<hsyncvalues version="8118">'+_6L+'</hsyncvalues>';this.isSending=false;}
return _4P;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_8,_4){this.id=_8;this.type='[HValue]';this.value=_4;this.views=[];HValueManager.add(_8,this);},set:function(_4){if(_4!=this.value){this.value=_4;HValueManager.changed(this);this.refresh();}},get:function(){return this.value;},bind:function(_L){if(_L===undefined){throw("HValueBindError: _L is undefined!");}
this.views.push(_L);_L.setValueObj(this);},unbind:function(_L){for(var _E=0;_E<this.views.length;_E++){var _6S=this.views[_E];if(_6S===_L){this.views.splice(_E);return;}}},release:function(_L){return this.unbind(_L);},refresh:function(){for(var _E=0;_E<this.views.length;_E++){var _L=this.views[_E];if(_L.value!=this.value){if(!_L._valueIsBeingSet){_L._valueIsBeingSet=true;_L.setValue(this.value);_L._valueIsBeingSet=false;}}}},toXML:function(_i){var _2x=this.id.toString();var _0m=this.value;var _0J=(typeof _0m)[0];var _0I;if(_0J=='s'){_0I=_0m.toString();_0I=SHA.str2Base64(_0I);}
else if(_0J=='n'){if(Math.ceil(_0m)===Math.floor(_0m)===_0m){_0J='i'
_0I=parseInt(_0m,10).toString();}
else{_0J='f'
_0I=parseFloat(_0m).toString();}}
else if(_0J=='b'){if(_0m){_0I='1';}
else{_0I='0';}}
else{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_2x);console.log('  syncjstype:',_0J);console.log('  typeof:',(typeof _0m));console.log('  syncvalue:',_0m);}
return'';}
return'<'+_0J+' id="'+_2x+'">'+_0I+'</'+_0J+'>';}});JSLoader=Base.extend({constructor:function(_22){this._1J=[];this._22=_22;this._3m=null;},_6m:function(_4Z){eval(_4Z.responseText);},load:function(_2e){if(jsLoader._1J.indexOf(_2e)!=-1){return;}
req_args={onSuccess:function(resp){jsLoader._6m(resp);},onFailure:function(resp){console.log("failed to load js: "+jsLoader._28);},method:'get',asynchronous:false};this._3m=new Ajax.Request(this._22+_2e,req_args);this._1J.push(_2e);}});onloader("jsLoader = new JSLoader('/gz/?js=');");HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _Q=arguments;if(_Q.length===0){this._1x();}
else if(_Q.length==2){this._3V(_Q[0],_Q[1]);}
else if(_Q.length==1){this._1y(_Q[0]);}
else{throw"Invalid number of arguments.";}},_1x:function(){this.x=null;this.y=null;},_3V:function(x,y){this.x=x;this.y=y;},_1y:function(_d){this.x=_d.x;this.y=_d.y;},set:function(){var _Q=arguments;if(_Q.length===0){this._1x();}
else if(_Q.length==2){this._3V(_Q[0],_Q[1]);}
else if(_Q.length==1){this._1y(_Q[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_2){if(this.x<_2.left){this.x=_2.left;}
if(this.y<_2.top){this.y=_2.top;}
if(this.x>_2.right){this.x=_2.right;}
if(this.y>_2.bottom){this.y=_2.bottom;}},add:function(_d){_Q=arguments;if((_Q.length==1)&&(_Q[0].type==this.type)){_d=_Q[0];return new HPoint((this.x+_d.x),(this.y+_d.y));}
else if(_Q.length==2){return new HPoint((this.x+_Q[0]),(this.y+_Q[1]));}else{return new HPoint(0,0);}},subtract:function(){_Q=arguments;if((_Q.length==1)&&(_Q[0].type==this.type)){_d=_Q[0];return new HPoint(this.x-_d.x,this.y-_d.y);}
else if(_Q.length==2){return new HPoint(this.x-_Q[0],this.y-_Q[1]);}else{return new HPoint(0,0);}},equals:function(_d){return(this.x==_d.x&&this.y==_d.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _Q=arguments;if(_Q.length===0){this._1x();}else if(_Q.length==4){this._3U(_Q[0],_Q[1],_Q[2],_Q[3]);}
else if(_Q.length==2){this._1y(_Q[0],_Q[1]);}
else if(_Q.length==1){this._3T(_Q[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1x:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_3U:function(_I,_0o,_0Z,_1a){this.top=_0o;this.left=_I;this.bottom=_1a;this.right=_0Z;},_1y:function(_4u,_52){this.top=_4u.y;this.left=_4u.x;this.bottom=_52.y;this.right=_52.x;},_3T:function(_2){this.top=_2.top;this.left=_2.left;this.bottom=_2.bottom;this.right=_2.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _Q=arguments;if(_Q.length===0){this._1x();}else if(_Q.length==4){this._3U(_Q[0],_Q[1],_Q[2],_Q[3]);}
else if(_Q.length==2){this._1y(_Q[0],_Q[1]);}
else if(_Q.length==1){this._3T(_Q[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_I){this.left=_I;this.updateSecondaryValues();},setRight:function(_0Z){this.right=_0Z;this.updateSecondaryValues();},setTop:function(_0o){this.top=_0o;this.updateSecondaryValues();},setBottom:function(_1a){this.bottom=_1a;this.updateSecondaryValues();},setLeftTop:function(_d){this.left=_d.x;this.top=_d.y;this.updateSecondaryValues();},setLeftBottom:function(_d){this.left=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setRightTop:function(_d){this.right=_d.x;this.top=_d.y;this.updateSecondaryValues();},setRightBottom:function(_d){this.right=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setWidth:function(_h){this.right=this.left+_h;this.updateSecondaryValues();},setHeight:function(_r){this.bottom=this.top+_r;this.updateSecondaryValues();},setSize:function(){var _Q=arguments;if(_Q.length===2){_h=_Q[0];_r=_Q[1];}
else if(_Q.length===1){_h=_Q.x;_r=_Q.y;}
this.right=this.left+_h;this.bottom=this.top+_r;this.updateSecondaryValues();},intersects:function(_2){return(((_2.left>=this.left&&_2.left<=this.right)||(_2.right>=this.left&&_2.right<=this.right))&&((_2.top>=this.top&&_2.top<=this.bottom)||(_2.bottom>=this.top&&_2.bottom<=this.bottom)));},contains:function(_k){if(_k instanceof HPoint){return this._5G(_k);}
else if(_k instanceof HRect){return this._5H(_k);}
else{throw"Wrong argument type.";}},_5G:function(_d){return(_d.x>=this.left&&_d.x<=this.right&&_d.y>=this.top&&_d.y<=this.bottom);},_5H:function(_2){return(_2.left>=this.left&&_2.right<=this.right&&_2.top>=this.top&&_2.bottom<=this.bottom);},insetBy:function(){var _Q=arguments;if(_Q.length===1){this._65(_Q[0]);}else if(_Q.length==2){this._4n(_Q[0],_Q[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_65:function(_d){this._4n(_d.x,_d.y);},_4n:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _Q=arguments;if(_Q.length===1){this._6k(_Q[0]);}else if(_Q.length==2){this._4A(_Q[0],_Q[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_6k:function(_d){this._4A(_d.x,_d.y);},_4A:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _Q=arguments;if(_Q.length===1){this._6l(_Q[0]);}else if(_Q.length==2){this._4B(_Q[0],_Q[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_6l:function(_d){this._4B(_d.x,_d.y);},_4B:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_2){return(this.left==_2.left&&this.top==_2.top&&this.right==_2.right&&this.bottom==_2.bottom);},intersection:function(_2){return new HRect(Math.max(this.left,_2.left),Math.max(this.top,_2.top),Math.min(this.right,_2.right),Math.min(this.bottom,_2.bottom));},union:function(_2){return new HRect(Math.min(this.left,_2.left),Math.min(this.top,_2.top),Math.max(this.right,_2.right),Math.max(this.bottom,_2.bottom));},bind:function(_k){},unbind:function(_k){}});HDefaultApplicationInterval=20;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _Z=0;_Z<this.apps.length;_Z++){if(this.apps[_Z]){if(!this.busyApps[_Z]){if((this.ticks%this.appPriorities[_Z])==0){this.appTimers[_Z]=setTimeout('if (HSystem.apps['+_Z+']) {HSystem.apps['+_Z+']._55();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._7B=setTimeout('HSystem.ticker();',10);},addApp:function(_19,_0k){if(this.freeAppIds.length>200){var _Z=this.freeAppIds.shift();this.apps[_Z]=_19;}else{this.apps.push(_19);var _Z=this.apps.length-1;}
_19.parent=this;_19.parents=[this];_19.appId=_Z;this.startApp(_Z,_0k);return _Z;},startApp:function(_Z,_0k){if(_0k===undefined){_0k=this.defaultInterval;}
this.appPriorities[_Z]=_0k;this.busyApps[_Z]=false;},stopApp:function(_Z){this.busyApps[_Z]=true;},reniceApp:function(_Z,_0k){this.appPriorities[_Z]=_0k;},killApp:function(_Z,_5S){if(!_5S){var _6E=new Date().getTime();while(this.busyApps[_Z]==true){if(new Date().getTime()>_6E+this.maxAppRunTime){break;}}}
this.busyApps[_Z]=true;this.apps[_Z].destroyAllViews();delete this.apps[_Z];this.apps[_Z]=null;this.freeAppIds.push(_Z);}});onloader('HSystem.ticker();');HApplication=HClass.extend({constructor:function(_0k){this.type='[HApplication]';this.views=[];this.recycleableViewIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_0k);},buildParents:function(_D){_D.parent=this;_D.parents=[];for(var _0W=0;_0W<this.parents.length;_0W++){_D.parents.push(this.parents[_0W]);}
_D.parents.push(this);},addView:function(_D){this.buildParents(_D);this.viewsZOrder.push(_D);if(this.recycleableViewIds.length>100){var _x=this.recycleableViewIds.shift();this.views[_x]=_D;}else{this.views.push(_D);var _x=this.views.length-1;}
return _x;},removeView:function(_x){if(this.views[_x]){this.views[_x].remove();}},destroyView:function(_x){if(this.views[_x]){this.views[_x].die();}},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}},_6t:function(){for(var _E=0;_E<this.views.length;_E++){if(this.views[_E]){this.views[_E].onIdle();}}},_55:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._6t();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2A={};this._25={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_W){this.themePath=_W;},_5O:function(_o){console.log("ERROR: Template Not Found: '"+_o+"' ");},_5N:function(_o){console.log("ERROR: Template Failure: '"+_o+"' ");},_5M:function(_o){console.log("ERROR: Template Exception: '"+_o+"' ");},fetch:function(_o,_0P){var _51;if(!_0P){var _0P='text/html; charset=UTF-8';}
var _3m=new Ajax.Request(_o,{method:'GET',onSuccess:function(_74){_51=_74.responseText;},on404:function(){HThemeManager._5O(_o);},onFailure:function(){HThemeManager._5N(_o);},onException:function(){HThemeManager._5M(_o);},asynchronous:false,contentType:_0P});_3m.onStateChange();return _51;},getThemeGfxPath:function(){var _m=this._26[0];var _p=this._26[1];var _z=this._26[2];var _J=this._26[3];var _0M=this._0M(_m,_p,_z,_J);return this._00(_0M,'gfx/');},getCssFilePath:function(_0B){return"url('"+this._00(this.getThemeGfxPath(),_0B);+"')";},loadCSS:function(_o){var _0P='text/css';var _0Q=this.fetch(_o,_0P);if(!_0Q||_0Q==""){return;}
_0Q=this._3M(_0Q);var _0l,_1S,_2a;if(is_ie){_0l=_q.createStyleSheet();_0l.cssText=_0Q;}
else{_0l=_q.createElement("style");_0l.type=_0P;_0l.media="all";_2a=_q.getElementsByTagName('head')[0];_2a.appendChild(_0l);if(navigator.userAgent.indexOf('KHTML')!=-1){var _5L=_q.createTextNode(_0Q);_0l.appendChild(_5L);}
else{_0l.innerHTML=_0Q;}}},_5s:function(_H){if(_H[_H.length-1]!='/'){_H+='/';}
return _H;},_00:function(_6F,_6G){return this._5s(_6F)+_6G;},_0M:function(_m,_p,_z,_J){var _W=_z;if(_z===null){_W=this.themePath;}
if(HThemeMode==0){if(_J){_W=this._00(_W,_J);}
if(_z===null){_W=this._00(_W,_p);_W=this._00(_W,'themes');}
_W=this._00(_W,_m);}
else if(HThemeMode==1){_W=this._00(_W,_m);}
return _W;},_27:function(_m,_p,_z,_J){this._26=[_m,_p,_z,_J];var _5J=this._0M(_m,_p,_z,_J);var _5K=this._00('css',_p+'.css');var _27=this._00(_5J,_5K);return _27;},_37:function(_m,_p,_z,_J){var _5Z=this._0M(_m,_p,_z,_J);var _60=this._00('html',_p+'.html');var _61=this._00(_5Z,_60);return _61;},loadMarkup:function(_m,_p,_z,_J){if(!this._2A[_m]){this._2A[_m]={};}
var _A=this._2A[_m][_p];if(null===_A||undefined===_A){var _37=this._37(_m,_p,_z,_J);_A=this.fetch(_37);if(null===_A||undefined===_A){_A="";}
this._2A[_m][_p]=_A;}
return _A;},getMarkup:function(_m,_p,_z,_J){if(!this._25[_m]){var _5D=this._27(_m,'common',_z,null);this._25[_m]={};this.loadCSS(_5D);}
if(!this._25[_m][_p]){var _5E=this._27(_m,_p,_z,_J);this._25[_m][_p]=true;this.loadCSS(_5E);}
return this.loadMarkup(_m,_p,_z,_J);},_23:function(_m,_p,_z,_J){var _0M=this._0M(_m,_p,_z,_J);var _o=this._00(_0M,'gfx/');return _o;},_5F:function(_m,_p,_z,_J,_0B){return this._00(this._23(_m,_p,_z,_J),_0B);},getThemeGfxFile:function(_0B){return this.getThemeGfxPath()+_0B;},setTheme:function(_5b){this.currentTheme=_5b;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_16:new RegExp(/#\{([^\}]*)\}/),_3M:function(_1A){while(this._16.test(_1A)){_1A=_1A.replace(this._16,eval(RegExp.$1));}
return _1A;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _1K=this.markup;var _ID=this.elemId.toString();var _WIDTH=this.rect.width;var _HEIGHT=this.rect.height;while(HMarkupView._16.test(_1K)){_1K=_1K.replace(HMarkupView._16,eval(RegExp.$1));}
this.markup=_1K;},toggleCSSClass:function(_0d,_1z,_53){if(_0d){var _4g=helmi.Element.hasClassName(_0d,_1z);if(_53){if(!_4g){helmi.Element.addClassName(_0d,_1z);}}
else{if(_4g){helmi.Element.removeClassName(_0d,_1z);}}}}},{_16:new RegExp(/#\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,constructor:function(_2,_6){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;this.resizeElements=[];this._4W=false;this._3p=[];this.hasResizeElements=false;this.optimizeWidthOnRefresh=true;this.parent=_6;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.recycleableViewIds=[];this.viewsZOrder=[];this._5I();prop_set(this.elemId,'display','none',true);if(this.isAbsolute){prop_set(this.elemId,'position','absolute',true);}else{prop_set(this.elemId,'position','relative',true);}
prop_set(this.elemId,'overflow','hidden',true);this.setRect(_2);this.isHidden=false;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this._3N=_2.left;this._3P=_2.top;this._1g=[];if(!this.isinherited){this.draw();}},setFlexRight:function(_7,_02){if(_7===undefined){_7=true;}
this.flexRight=_7;if(_02===undefined){_02=0;}
this.flexRightOffset=_02;},setFlexLeft:function(_7,_02){if(_7===undefined){_7=true;}
this.flexLeft=_7;if(_02!==undefined){this.rect.setLeft(_02);}},setFlexTop:function(_7,_02){if(_7===undefined){_7=true;}
this.flexTop=_7;if(_02!==undefined){this.rect.setTop(_02);}},setFlexBottom:function(_7,_02){if(_7===undefined){_7=true;}
this.flexBottom=_7;if(_02===undefined){_02=0;}
this.flexBottomOffset=_02;},setAbsolute:function(_7){if(_7===undefined){_7=true;}
this.isAbsolute=_7;},setRelative:function(_7){if(_7===undefined){_7=true}
this.isAbsolute=(!_7);},getThemeGfxPath:function(){if(this.preserveTheme){_m=this.theme;}else{_m=HThemeManager.currentTheme;}
return HThemeManager._23(_m,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0B){if(this.preserveTheme){_m=this.theme;}else{_m=HThemeManager.currentTheme;}
return HThemeManager._5F(_m,this.componentName,this.themePath,this.packageName,_0B);},addResizeableElement:function(_3o){var _4V=_3o[0];if(this._3p.indexOf(_4V)==-1){this._3p.push(_4V);this.resizeElements.push(_3o);}
this.addResizeableElementCalled=true;return'';},initResizeElements:function(){for(var _0Y=0;_0Y<this.resizeElements.length;_0Y++){var _c=this.bindDomElement(this._3p[_0Y]);this.resizeElements[_0Y][0]=_c;}
this._4W=true;if(this.resizeElements.length!=0){this.hasResizeElements=true;}},doResizeElements:function(){for(var _0Y=0;_0Y<this.resizeElements.length;_0Y++){var _2s=this.resizeElements[_0Y];var _4=Math.max(this.rect.width+_2s[1],0);prop_set(_2s[0],'width',_4+'px');_4=Math.max(this.rect.height+_2s[2],0);prop_set(_2s[0],'height',_4+'px');}},_5I:function(){if(!this.elemId){var _3e;if(this.parent.elemId===undefined){_3e=0;}
else{_3e=this.parent.elemId;}
this.elemId=elem_mk(_3e);this.setStyle('visibility','hidden',true);helmi.Element.addClassName(elem_get(this.elemId),HThemeManager.currentTheme);}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
if(!this._4W&&this.addResizeableElementCalled){this.initResizeElements();}
if(this.hasResizeElements){this.doResizeElements();}
this.drawn=true;var _c=this.elemId;var _2=this.rect;if(this.flexLeft){prop_set(_c,'left',_2.left+'px',true);}else{prop_set(_c,'left','auto',true);}
if(this.flexTop){prop_set(_c,'top',_2.top+'px',true);}else{prop_set(_c,'top','auto',true);}
if(this.flexRight){prop_set(_c,'right',this.flexRightOffset+'px',true);}else{prop_set(_c,'right','auto',true);}
if(this.flexBottom){prop_set(_c,'bottom',this.flexBottomOffset+'px',true);}else{prop_set(_c,'bottom','auto',true);}
if(this.flexLeft&&this.flexRight){prop_set(_c,'width','auto',true);}else{prop_set(_c,'width',_2.width+'px',true);}
if(this.flexTop&&this.flexBottom){prop_set(_c,'height','auto',true);}else{prop_set(_c,'height',_2.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){prop_set(_c,'visibility','inherit',true);}
prop_set(_c,'display','block',true);this._5i();if(this._3N!=_2.left||this._3P!=_2.top){this.invalidatePositionCache();this._3N=_2.left;this._3P=_2.top;}
if(is.ie6&&!this.ie_resizefixadded){_15(elem_get(this.elemId));this.ie_resizefixadded=true;}},_5i:function(){prop_set(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this),true);},_2B:function(){var _3B=this.parent.viewsZOrder;for(var i=0;i<_3B.length;i++){if(_3B[i].elemId){prop_set(_3B[i].elemId,'z-index',i,true);}}},draw:function(){this.drawRect();},_4v:function(){var _m;if(this.preserveTheme){_m=this.theme;}
else{_m=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_m,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){prop_set(this.elemId,'display','none',true);this._4v();this.bindMarkupVariables();elem_set(this.elemId,this.markup);this.markupElemIds={};var _4Q=['bg','label','state','control','value','subview'];for(var i=0;i<_4Q.length;i++){var _0i=_4Q[i];var _45=_0i+this.elemId;var _5Y=' id="'+_45+'"';if(this.markup.indexOf(_5Y)!=-1){this.markupElemIds[_0i]=this.bindDomElement(_45);}}
prop_set(this.elemId,'display','block',true);if(is.ie6&&!this.ie_htmlresizefixadded){_15(elem_get(this.elemId));this.ie_htmlresizefixadded=true;}},setHTML:function(_2c){elem_set(this.elemId,_2c);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_2){if(this.rect){this.rect.unbind(this);}
this.rect=_2;this.rect.bind(this);this.refresh();},setStyle:function(_1h,_4,_2O){if(!this.elemId){return;}
prop_set(this.elemId,_1h,_4,_2O);},style:function(_1h){if(!this.elemId){return;}
return prop_get(this.elemId,_1h);},setStyleForPart:function(_0i,_1h,_4,_2O){if(!this.markupElemIds[_0i]){return;}
prop_set(this.markupElemIds[_0i],_1h,_4,_2O);},styleForPart:function(_0i,_1h){if(!this.markupElemIds[_0i]){return;}
prop_get(this.markupElemIds[_0i],_1h);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){this.parent.viewsZOrder.splice(this.parent.viewsZOrder.indexOf(this),1);var _4L=this.parent.views.indexOf(this);this.parent.views[_4L]=null;this.parent.recycleableViewIds.push(_4L);this._2B();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}
this.remove();for(var i=0;i<this._1g.length;i++){elem_del(this._1g[i]);}
this._1g=[];elem_del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var _E=0;_E<this.views.length;_E++){if(this.views[_E]){this.views[_E].onIdle();}}},buildParents:function(_D){_D.parent=this;_D.parents=[];for(var _0W=0;_0W<this.parents.length;_0W++){_D.parents.push(this.parents[_0W]);}
_D.parents.push(this);},addView:function(_D){this.buildParents(_D);this.viewsZOrder.push(_D);if(this.recycleableViewIds.length>100){var _x=this.recycleableViewIds.shift();this.views[_x]=_D;}else{this.views.push(_D);var _x=this.views.length-1;}
return _x;},removeView:function(_x){if(this.views[_x]){this.views[_x].remove();}},destroyView:function(_x){if(this.views[_x]){this.views[_x].die();}},bounds:function(){var _0O=new HRect(this.rect);_0O.right-=_0O.left;_0O.left=0;_0O.bottom-=_0O.top;_0O.top=0;return _0O;},resizeBy:function(_2X,_1V){var _2=this.rect;_2.right+=_2X;_2.bottom+=_1V;_2.updateSecondaryValues();this.drawRect();},resizeTo:function(_h,_r){var _2=this.rect;_2.right=_2.left+_h;_2.bottom=_2.top+_r;_2.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_2X,_1V){this.rect.offsetBy(_2X,_1V);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _M=this.zIndex();this.parent.viewsZOrder.splice(_M,1);this.parent.viewsZOrder.push(this);this._2B();},sendToBack:function(){if(!this.parent){return;}
var _M=this.zIndex();this.parent.viewsZOrder.splice(_M,1);this.parent.viewsZOrder.splice(0,0,this);this._2B();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this);},stringWidth:function(_2w,_2f,_c){if(_2f!==undefined&&_2f!=null){_2w=_2w.substring(0,_2f);}
if(_c===undefined||_c==null){_c=this.elemId;}
var _0x=elem_mk(_c);prop_set(_0x,"visibility","hidden",true);prop_set(_0x,"position","absolute",true);prop_set(_0x,"white-space","nowrap",true);elem_set(_0x,_2w);var _h;var _r;if(is_ie||is.opera){_h=elem_get(_0x).offsetWidth;if(arguments[3]){_r=elem_get(_0x).offsetHeight;}}else{_h=prop_get(_0x,"width");if(arguments[3]){_r=prop_get(_0x,"height");}}
elem_del(_0x);if(arguments[3]){return new HPoint(parseInt(_h,10),parseInt(_r,10));}else{return parseInt(_h,10);}},pageX:function(){var _5=0;var _9=this;while(_9){if(_9.elemId&&_9.rect){_5+=elem_get(_9.elemId).offsetLeft;_5-=elem_get(_9.elemId).scrollLeft;}
_9=_9.parent;}
return _5;},pageY:function(){var _a=0;var _9=this;while(_9){if(_9.elemId&&_9.rect){_a+=elem_get(_9.elemId).offsetTop;_a-=elem_get(_9.elemId).scrollTop;}
_9=_9.parent;}
return _a;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].invalidatePositionCache();}}},bindDomElement:function(_04){var _2N=elem_bind(_04);if(_2N){this._1g.push(_2N);}
return _2N;},unbindDomElement:function(_0d){var _4m=this._1g.indexOf(_0d);if(_4m>-1){elem_del(_0d);this._1g.splice(_4m,1);}},animateTo:function(_k,_0z,_0T){if(_k instanceof HPoint){var _2=new HRect(_k,_k);_2.setSize(this.rect.width,this.rect.height);this._2K(_2,_0z);}
else if(_k instanceof HRect){this._2K(_k,_0z);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._21){window.clearInterval(this._21);this._21=null;var _I=parseInt(this.style('left'),10);var _0o=parseInt(this.style('top'),10);var _h=parseInt(this.style('width'),10);var _r=parseInt(this.style('height'),10);this.rect.set(_I,_0o,_I+_h,_0o+_r);if(this._3I){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_2K:function(_2,_0z,_0T){if(null===_0z||undefined===_0z){_0z=500;}
if(null===_0T||undefined===_0T||_0T<1){_0T=50;}
if(!this._21){this._3I=false;this.onAnimationStart();var _6D=new Date().getTime();var _t=this;this._21=window.setInterval(function(){_t._77({startTime:_6D,duration:_0z,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_t.rect.left,to:_2.left,unit:'px'},{prop:'top',from:_t.rect.top,to:_2.top,unit:'px'},{prop:'width',from:_t.rect.width,to:_2.width,unit:'px'},{prop:'height',from:_t.rect.height,to:_2.height,unit:'px'}]});},Math.round(1000/_0T));}},_77:function(_k){var _5d=new Date().getTime();if(_5d<_k.startTime+_k.duration){var _5y=_5d-_k.startTime;for(var i=0;i<_k.props.length;i++){var _2W=_k.props[i].from;var _5f=_k.props[i].to;if(_2W!=_5f){var _6v=_k.transition(_5y,_2W,(_5f-_2W),_k.duration);this.setStyle(_k.props[i].prop,_6v+_k.props[i].unit);}}}else{for(var i=0;i<_k.props.length;i++){this.setStyle(_k.props[i].prop,_k.props[i].to+_k.props[i].unit);}
this._3I=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({constructor:function(_2,_6,_3){if(this.isinherited){this.base(_2,_6);}
else{this.isinherited=true;this.base(_2,_6);this.isinherited=false;}
if(!_3){_3={};}
var options=new(HComponentDefaults.extend(_3));this.options=options;var _w=options.label;this.setLabel(_w);var _1B=options.events;this.setEvents(_1B);this.type='[HControl]';this.refreshOnValueChange=true;if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _66=(_3.minValue||_3.maxValue);if(_66){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(null!==options.visible&&undefined!==options.visible){if(options.visible){this.show();}
else{this.hide();}}
if(!this.isinherited){this.draw();}},setAction:function(_3E){this.action=_3E;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
HEventManager.unregister(this);this.base();},setLabel:function(_w){this.label=_w;this.refresh();},setEnabled:function(_7){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].setEnabled(_7);}}
if(this.enabled==_7){return;}
this.enabled=_7;if(_7){HEventManager.register(this,this.events);}
else{HEventManager.unregister(this);}
this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_DISABLED,!this.enabled);},setValue:function(_4){if(_4==undefined){return;}
if(!this.valueObj){return;}
if(_4!==this.value){this.value=_4;this.valueObj.set(this.value);if(this.refreshOnValueChange){this.refresh();}}},setValueObj:function(_2G){this.valueObj=_2G;this.setValue(_2G.value);},setValueRange:function(_4,_2l,_2i){this.minValue=_2l;this.maxValue=_2i;_4=(_4<_2l)?_2l:_4;_4=(_4>_2i)?_2i:_4;this.setValue(_4);this.refresh();},setEvents:function(_1B){if(!this.events){var _5Q=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false});this.events=new _5Q;}
if(_1B){this.events.extend(_1B);}
this.events.owner=this;HEventManager.focusOptions[this.elemId]=this.events;var _4x=this.events.mouseMove;var _3a=HEventManager.mouseMoveItems.indexOf(this.elemId);if(_4x&&(_3a==-1)){HEventManager.mouseMoveItems.push(this.elemId);}else if((!_4x)&&(_3a!=-1)){HEventManager.split(_3a);}
this.isDragged=false;},setMouseMove:function(_7){this.events.mouseMove=_7;this.setEvents();},setMouseDown:function(_7){this.events.mouseDown=_7;this.setEvents();},setMouseUp:function(_7){this.events.mouseUp=_7;this.setEvents();},setMouseWheel:function(_7){this.events.mouseWheel=_7;this.setEvents();},setDraggable:function(_7){this.events.draggable=_7;this.setEvents();},setDroppable:function(_7){this.events.droppable=_7;this.setEvents();},setKeyDown:function(_7){this.events.keyDown=_7;this.setEvents();},setKeyUp:function(_7){this.events.keyUp=_7;this.setEvents();},focus:function(){},blur:function(){},gainedActiveStatus:function(_0h){},_7f:function(_0h){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_0h);},lostActiveStatus:function(_N){},_7n:function(_N){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_N);},mouseMove:function(_5,_a){},mouseDown:function(_5,_a,_T){},mouseUp:function(_5,_a,_T){},mouseWheel:function(_Y){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_G){},keyUp:function(_G){},_6d:function(e){if(!Event.element){return;}
var _t=Event.element(e);while(_t&&_t.owner===undefined){_t=_t.parentNode;}
if(!_t){return;}
var _1=_t.owner;HEventManager.focus(_1);Event.stop(e);},_6c:function(e){if(!Event.element){return;}
var _t=Event.element(e);while(_t&&_t.owner===undefined){_t=_t.parentNode;}
if(!_t){return;}
var _1=_t.owner;HEventManager.blur(_1);Event.stop(e);},invalidatePositionCache:function(){this.base();HEventManager.invalidatePositionCache(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_8,_4){this.id=_8;this.value=_4;this.type='[HDummyValue]';},set:function(_4){this.value=_4;},get:function(){return this.value;},bind:function(_1T){},unbind:function(_1T){}});HComponentDefaults=HClass.extend({label:"Untitled",events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});