
HIMLE RIA Framework
Copyright(C)2008 HIMLE GROUP http:Copyright(C)2006-2007 Helmi Technologies Inc.This program is free software;you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation;either version 2 of the License,or(at your option)any later version.This program is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY;without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the GNU General Public License for more details.You should have received a copy of the GNU General Public License along with this program;if not,write to the Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,MA 02111-1307 USA
var HClass=function(){if(arguments.length){var _2G=arguments[0];if(this==window){HClass.prototype.extend.call(_2G,arguments.callee.prototype);}else{this.extend(_2G);}}};HClass.prototype={extend:function(_0y,_6){var _0Y=HClass.prototype.extend;if(arguments.length==2){var _1V=this[_0y];if((_1V instanceof Function)&&(_6 instanceof Function)&&_1V.valueOf()!=_6.valueOf()&&/\bbase\b/.test(_6)){var _2e=_6;_6=function(){var _T=this.base;this.base=_1V;var _56=_2e.apply(this,arguments);this.base=_T;return _56;};_6.valueOf=function(){return _2e;};_6.toString=function(){return String(_2e);};}
return this[_0y]=_6;}else if(_0y){var _0d={toSource:null};var _3C=["toString","valueOf"];if(HClass._2m){_3C.push("constructor");}
for(var i=0;(_e=_3C[i]);i++){if(_0y[_e]!=_0d[_e]){_0Y.call(this,_e,_0y[_e]);}}
for(var _e in _0y){if(!_0d[_e]){_0Y.call(this,_e,_0y[_e]);}}}
return this;},base:function(){}};HClass.extend=function(_0a,_2u){var _0Y=HClass.prototype.extend;if(!_0a){_0a={};}
HClass._2m=true;var _0d=new this;_0Y.call(_0d,_0a);var _1q=_0d.constructor;_0d.constructor=this;delete HClass._2m;var _0u=function(){if(!HClass._2m){_1q.apply(this,arguments);}
this.constructor=_0u;};_0u.prototype=_0d;_0u.extend=this.extend;_0u.implement=this.implement;_0u.toString=function(){return String(_1q);}
_0Y.call(_0u,_2u);var _2i=_1q?_0u:_0d;if(_2i.init instanceof Function){_2i.init();}
return _2i;};HClass.implement=function(_12){if(_12 instanceof Function){_12=_12.prototype;}
this.prototype.extend(_12);}
var Base=HClass;ie_htc_path=null;function ie_early_fixes(){var b=navigator.appName;var ua=navigator.userAgent.toLowerCase();var _4V=ua.indexOf("opera")>-1;if(!_4V&&b=="Microsoft Internet Explorer"){var _58=document.scripts[document.scripts.length-1];var _3M=_58.src;ie_htc_path=_3M.substring(0,_3M.lastIndexOf("/")+1);}}
ie_early_fixes();is_safari=navigator.userAgent.toLowerCase().indexOf("safari")>-1;is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Event=HClass.extend({constructor:null,element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(is_ie||is_safari){return(e.button==1);}else{return(e.button==0);}},observers:false,_4R:function(_4,_e,_01,_V){if(!Event.observers){Event.observers=[];}
if(_4.addEventListener){this.observers.push([_4,_e,_01,_V]);_4.addEventListener(_e,_01,_V);}else if(_4.attachEvent){this.observers.push([_4,_e,_01,_V]);_4.attachEvent("on"+_e,_01);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_4,_e,_01,_V){if(typeof _4=="string"){_4=document.getElementById(_4);}
_V=_V||false;Event._4R(_4,_e,_01,_V);},stopObserving:function(_4,_e,_01,_V){if(typeof _4=="string"){_4=document.getElementById(_4);}
_V=_V||false;if(_4.removeEventListener){_4.removeEventListener(_e,_01,_V);}else if(detachEvent){try{element.detachEvent("on"+name,_01);}catch(e){}}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_4&&eo[1]==_e&&eo[2]==_01&&eo[3]==_V){Event.observers[i]=null;Event.observers.splice(i,1);}else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34});if(is_ie){Event.observe(window,"unload",Event.unloadCache,false);}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length;var _2L=[];for(i=0;i<l;i++){_2L.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _2L.join("&");}
Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_m,_3){this.transport=Ajax.getTransport();if(!_3){_3={};}
var _08=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_08=_08.extend(_3);this.options=new _08();this.request(_m);},request:function(_m){this.url=_m;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _j=this;this.transport.onreadystatechange=function(){_j.onStateChange()};this.setRequestHeaders();var _48=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_48);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1c=this.transport.readyState;if(_1c>1){this.respondToReadyState(_1c);}},respondToReadyState:function(_1c){if(_1c==4){try{(this.options["on"+(this.success()?"Success":"Failure")]||(function(){}))(this.transport);}catch(e){console.log(e);}}
if(_1c==4){this.transport.onreadystatechange=function(){};}},success:function(){return!this.transport.status||(this.transport.status>=200&&this.transport.status<300);}});frameskips=1;var _W=document;var _0K=0;var quot='"';var apos="'";is_ie=(_W.all&&navigator.userAgent.indexOf("Opera")==-1);is_ie6=(is_ie&&navigator.userAgent.indexOf("MSIE 6")!=-1);is_ie7=(is_ie&&navigator.userAgent.indexOf("MSIE 7")!=-1);is_safari=(navigator.userAgent.indexOf("KHTML")!=-1);var _22=[];var _37=false;onloader=function(_2v){if(_37){eval(_2v);}else{_22.push(_2v);}};var _4U=null;var _3t=function(_1y){if(_1y){_37=true;while(_22.length!=0){var _4A=_22.shift();eval(_4A);}}else{_4U=setTimeout('_3s()',10);}};var _3s=function(){var _1y=false;if(is_ie){var _3g="javascript:void(0)";if(location.protocol=="https:"){_3g="src=//0";}
_W.write("<scr"+"ipt id=_45 defer src="+_3g+"><\/scr"+"ipt>");var _4z=_W.getElementById("_45");_4z.onreadystatechange=function(){if(this.readyState=="complete"){_3t(true);}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(_W.readyState))){_1y=true;}
else if(document.body){_1y=true;}
_3t(_1y);};_3s();var _1E;var _u=[];var _0R=[];var _1m=[];var _1Q=[];var _1R={};var _1S=false;var _0F=[];var prop_do_csstext=false;elem_bind=function(_30){var _4=_W.getElementById(_30);if(!_4){return false;}
var _5=_1U(_4);_1m[_5]=[];_0R[_5]=[];return _5;};elem_add=function(_4){var _5=_1U(_4);_1m[_5]=[];_0R[_5]=[];return _5;};elem_get=function(_5){return _u[_5];};elem_set=function(_5,_1x){_u[_5].innerHTML=_1x;};elem_del=function(_5){var _2A=_u[_5];if(_2A){var _3v=_2A.parentNode;if(_3v){_3v.removeChild(_2A);}}
_u[_5]=null;_1m[_5]=[];_0R[_5]=[];_0F.push(_5);};elem_replace=function(_5,_4){var _3a=_0F.indexOf(_5);if(_3a>-1){_0F.splice(_3a,1);}
_u[_5]=_4;};elem_append=function(_2k,_5){_u[_2k].appendChild(_u[_5]);};elem_mk=function(_2k,_2C){if(_2C===undefined){_2C='div';}
var _4=_W.createElement(_2C);_u[_2k].appendChild(_4);var _5=_1U(_4);_1m[_5]=[];_0R[_5]=[];return _5;};elem_count=function(){var _32=0;for(var i=0;i<_u.length;i++){if(_u[i]){_32++;}}
return _32;};_1U=function(_4){var _5;if(_0F.length>0){var _4q=_0F[0];_0F.splice(0,1);_u[_4q]=_4;_5=_4q;}
else{_u.push(_4);_5=_u.length-1;}
return _5;};styl_get=function(_5,_e){return prop_get(_5,_e);};var _19="prop_get = function(_5,_e,_1Z){var _x = _0R[_5];if((_x[_e]===undefined)||(_1Z!==undefined)){";_19+="if((_e == 'opacity') && (_1Z != -1)) {var _1F = prop_get_opacity(_5);} else {";if(!is_ie){_19+="var _1F = _W.defaultView.getComputedStyle(_u[_5],null).getPropertyValue(_e);";}else{_19+="var _4b = _e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4});var _1F = _u[_5].currentStyle[_4b];";}
_19+="}_x[_e]=_1F;}return _x[_e];};";onloader(_19);styl_set=function(_5,_e,_6){try{prop_set(_5,_e,_6);return true;}
catch(e){return false;}};prop_set=function(_5,_e,_6,_1Z){var _x=_0R[_5];var _4N=_x[_e]!=_6;if(_4N){_x[_e]=_6;if(_1Z){if(_e=='opacity'){prop_set_opacity(_5,_6);}
else{try{is_ie?(_u[_5].style.setAttribute(_e.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_x[_e])):(_u[_5].style.setProperty(_e,_x[_e],''));}
catch(e){_u[_5].cssText+=';'+_e+': '+_x[_e]+';';}}}else{var _4a=_1Q;var _2O=_1m[_5];_2O.push(_e);if(!_1R[_5]){_4a.push(_5);_1R[_5]=true;}}}};var _0c="var _50=function(_5){var _2O=_1m[_5];var _x=_0R[_5];var _4=_u[_5];if(!_4){return}var _21=_4.style;var _5I=_2O.length;";if(prop_do_csstext){_0c+="var _2V=[];";}
_0c+="for(var _2Q=0;_2Q<_5I;_2Q++){var _e=_2O.shift();";if(prop_do_csstext){_0c+="_2V.push(_e+':'+_x[_e]);}_21.cssText += ';'+_2V.join(';')+';';";}else{_0c+="if(_e == 'opacity') { _1F = prop_set_opacity(_5, _x[_e]); } else {";if(is_ie){_0c+="_21.setAttribute(_e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_x[_e]);}";}
else{_0c+="_21.setProperty(_e,_x[_e],'');}";}
_0c+="};";}
_0c+="}";eval(_0c);var _3w='prop_loop_start(_0K)';var _51=1;var _2l=1;var prop_loop_start=function(_0K){clearTimeout(_1E);if(_1S){_0K*=2;_1E=setTimeout(_3w,_0K);return;}else{_0K=parseInt(frameskips*(_2l/_51),10);if(_0K<40){_0K=40;}
_1S=true;_1E=setTimeout(_3w,_0K);}
_2l-=now();var _4J=_1Q.length;for(var i=0;i<_4J;i++){var _5=_1Q.shift();_1R[_5]=false;_50(_5);}
_51++;_2l+=now();_1S=false;return;};var prop_loop_stop=function(){clearTimeout(_1E);};var now=function(){return new Date().getTime();};var prop_get_opacity=function(_5){var _S;var _40=prop_get(_5,'opacity',-1);if(_S=_40||(_40==0)){return parseFloat(_S);}
if(_S=(_u[_5].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_S[1]){return parseFloat(_S[1])/100;}}
return 1.0;};var prop_set_opacity=function(_5,_6){if(_6==1&&is_ie){_u[_5].style.setAttribute('filter',prop_get(_5,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_6<0.00001)_6=0;if(is_ie){_u[_5].style.setAttribute('filter',prop_get(_5,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_6*100+')');}
else{_u[_5].style.setProperty('opacity',_6,'');}}};var prop_get_extra_width=function(_5){var _h=prop_get_int_value(_5,'padding-left')+
prop_get_int_value(_5,'padding-right')+
prop_get_int_value(_5,'border-left-width')+
prop_get_int_value(_5,'border-right-width');return _h;};var prop_get_extra_height=function(_5){var _o=prop_get_int_value(_5,'padding-top')+
prop_get_int_value(_5,'padding-bottom')+
prop_get_int_value(_5,'border-top-width')+
prop_get_int_value(_5,'border-bottom-width');return _o;};var prop_get_int_value=function(_5,_3B){var _29=parseInt(prop_get(_5,_3B,true),10);if(isNaN(_29)){_29=0;}
return _29;};onloader('elem_add(document.body);');onloader('prop_loop_start();');HEventManager=HClass.extend({events:[false,false,0,0,[],[],[],false,false,false],HStatusButton:0,HStatusButton2:1,HStatusCoordX:2,HStatusCoordY:3,HStatusKeys:4,HStatusDirection:5,HStatusSpeed:6,HStatusAltKey:7,HStatusCtrlKey:8,HStatusShiftKey:9,constructor:null,start:function(){var _09;if(is_ie){_09=document;}
else{_09=window;}
Event.observe(_09,'mousemove',this.mouseMove);Event.observe(_09,'mouseup',this.mouseUp);Event.observe(_09,'mousedown',this.mouseDown);Event.observe(_09,'keyup',this.keyUp);Event.observe(_09,'keydown',this.keyDown);Event.observe(_09,'keypress',this.keyPress);Event.observe(_09,'contextmenu',this.contextMenu);if(window.addEventListener){window.addEventListener('DOMMouseScroll',this.mouseWheel,false);}
window.onmousewheel=document.onmousewheel=this.mouseWheel;this.focusItems=[];this.mouseMoveItems=[];this.eventItems=[];this.focusOptions=[];this.dragItems=[];this.hoverItems=[];this.hoverInterval=100;this.hoverTimer=new Date().getTime();this.topmostDroppable=null;this._20=[];this._34=true;this.activeControl=null;this._5H=null;},enablePositionCache:function(){this._34=true;},disablePositionCache:function(){this._34=false;},invalidatePositionCache:function(_9){if(_9){this._20[_9]=null;}
else{this._20=[];}},register:function(_q,_39){var _9=_q.elemId;var _4=elem_get(_9);if(is_ie){_4.setAttribute('owner',_q);}
else{_4.owner=_q;}
this.eventItems[_9]=true;this.focusItems[_9]=false;this.focusOptions[_9]=_39;Event.observe(_4,'mouseover',_q._4L);},unregister:function(_q){if(_q==this.activeControl){this.changeActiveControl(null);}
var _9=_q.elemId;var _4=elem_get(_9);this.eventItems[_9]=false;this.focusItems[_9]=false;this._20[_9]=null;try{Event.stopObserving(_4,'mouseover',_q._4L);}catch(e){window.status=e;}},focus:function(_q){var _9=_q.elemId;var _4=elem_get(_9);if(this.focusItems[_9]==false&&_q.isDragged==false){Event.stopObserving(_4,'mouseover',_q._4L);Event.observe(_4,'mouseout',_q._4K);this.focusItems[_9]=true;_q.focus();}},blur:function(_q){var _9=_q.elemId;var _4=elem_get(_9);if(this.focusItems[_9]==true&&_q.isDragged==false){Event.stopObserving(_4,'mouseout',_q._4K);Event.observe(_4,'mouseover',_q._4L);this.focusItems[_9]=false;_q.blur();}},mouseMove:function(e){var _2=HEventManager;var _b=Event.pointerX(e);var _c=Event.pointerY(e);var _2W=false;_2.events[_2.HStatusCoordX]=_b;_2.events[_2.HStatusCoordY]=_c;for(var i=0;i<_2.dragItems.length;i++){var _9=_2.dragItems[i];_2.focusOptions[_9].owner.doDrag(_b,_c);_2.invalidatePositionCache(_9);_2W=true;}
if(new Date().getTime()>_2.hoverTimer+_2.hoverInterval){_2._5Q();for(var i=0;i<_2.mouseMoveItems.length;i++){var _9=_2.mouseMoveItems[i];var _0b=_2.focusOptions[_9].owner;_0b.mouseMove(_b,_c);}
for(var i=0;i<_2.dragItems.length;i++){var _2F=_2.topmostDroppable;_2.topmostDroppable=null;var _9=_2.dragItems[i];var _0b=_2.focusOptions[_9].owner;for(var j=0;j<_2.hoverItems.length;j++){var _1w=_2.hoverItems[j];if(_1w!=_9&&_2.focusOptions[_1w].owner){var _1M=_2.focusOptions[_1w].owner;if(!_2.topmostDroppable||_1M.zIndex()>_2.topmostDroppable.zIndex()||_1M.parent==_2.topmostDroppable){if(_1M.events.droppable){_2.topmostDroppable=_1M;}}}}
if(_2F!=_2.topmostDroppable){if(_2F){_2F.onHoverEnd(_0b);}
if(_2.topmostDroppable){_2.topmostDroppable.onHoverStart(_0b);}}}
_2.hoverTimer=new Date().getTime();}
if(_2W){Event.stop(e);}},_5Q:function(){var _2=HEventManager;_2.hoverItems=[];var x=_2.events[_2.HStatusCoordX];var y=_2.events[_2.HStatusCoordY];for(var _r=0;_r<_2.eventItems.length;_r++){if(!_2.eventItems[_r]||!_2.focusOptions[_r].owner){continue;}
var _2U=_2.focusOptions[_r].owner;var _4=elem_get(_r);var _0s;if(!_2._34||!_2._20[_r]){_2._20[_r]={_4I:[_2U.pageX(),_2U.pageY()],_5N:helmi.Element.getVisibleSize(_4)};}
_0s=_2._20[_r];if(x>=_0s._4I[0]&&x<=_0s._4I[0]+_0s._5N[0]&&y>=_0s._4I[1]&&y<=_0s._4I[1]+_0s._5N[1]){_2.hoverItems.push(_r);}}},mouseDown:function(e,_13){var _2=HEventManager;_2._5K(e);var _2Z=false;if(_13===undefined){_13=Event.isLeftClick(e);}
if(_13){_2.events[_2.HStatusButton]=true;}else{_2.events[_2.HStatusButton2]=true;}
var _b=_2.events[_2.HStatusCoordX];var _c=_2.events[_2.HStatusCoordY];var _G=null;var _1H=[];var _2g=[];for(var i=0;i<_2.focusItems.length;i++){if(_2.focusItems[i]==true){if(_2.focusOptions[i].owner.enabled){_G=_2.focusOptions[i].owner;}
if((_2.focusOptions[i].draggable==true)&&(_2.dragItems.indexOf(i)==-1)){_1H.push(i);}
else if(_2.focusOptions[i].mouseDown==true){_2g.push(i);}}}
_2.changeActiveControl(_G);for(var i=0;i<_1H.length;i++){_2.dragItems.push(_1H[i]);_2.focusOptions[_1H[i]].owner.startDrag(_b,_c);_2Z=true;}
for(var i=0;i<_2g.length;i++){_2.focusOptions[_2g[i]].owner.mouseDown(_b,_c,_13);}
if(_2Z){document.body.focus();_2._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if(_2.hoverItems.length>0){Event.stop(e);}
return true;},changeActiveControl:function(_G){var _2=HEventManager;var _03=_2.activeControl;if(_G!=_03){if(_03){_03.active=false;_03._5J(_G);}
_2.activeControl=null;if(_G){_G.active=true;_2.activeControl=_G;_G._5C(_03);}}},mouseUp:function(e){var _2=HEventManager;_2._5K(e);var _2Y=false;_2.events[_2.HStatusButton]=false;_2.events[_2.HStatusButton2]=false;var _b=_2.events[_2.HStatusCoordX];var _c=_2.events[_2.HStatusCoordY];for(var i=0;i<_2.dragItems.length;i++){var _9=_2.dragItems[i];var _0b=_2.focusOptions[_9].owner;_0b.endDrag(_b,_c);_2Y=true;_2._5Q();if(_2.hoverItems.indexOf(_9)<0){_2.blur(_0b);}
if(_2.topmostDroppable){_2.topmostDroppable.onHoverEnd(_0b);_2.topmostDroppable.onDrop(_0b);_2.topmostDroppable=null;}}
_2.dragItems=[];if(_2Y){document.onselectstart=_2._storedOnSelectStart;}
for(var _r=0;_r<_2.focusItems.length;_r++){if(_2.focusItems[_r]==true){if(_2.focusOptions[_r].mouseUp==true){_2.focusOptions[_r].owner.mouseUp(_b,_c,true);}}}
return true;},keyDown:function(e){var _2=HEventManager;_2._5K(e);var _0l=e.keyCode;if(_2.activeControl&&_2.focusOptions[_2.activeControl.elemId].keyDown==true){Event.stop(e);if(_2._5H!=_0l){_2.activeControl.keyDown(_0l);}}
var _1d=_2.events[_2.HStatusKeys];if(_1d.indexOf(_0l)==-1){_1d.push(_0l);}
_2._5H=_0l;},keyUp:function(e){var _2=HEventManager;_2._5K(e);var _0l=e.keyCode;_2._5H=null;if(_2.activeControl&&_2.focusOptions[_2.activeControl.elemId].keyUp==true){_2.activeControl.keyUp(_0l);}
var _1d=_2.events[_2.HStatusKeys];var _3k=_1d.indexOf(_0l);if(_3k!=-1){_1d.splice(_3k,1);}},keyPress:function(e){var _2=HEventManager;if(_2.activeControl&&_2.focusOptions[_2.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _2=HEventManager;var _0f=0;if(!e){e=window.event;}
if(e.wheelDelta){_0f=e.wheelDelta/120;if(window.opera)_0f=-_0f;}else if(e.detail){_0f=-e.detail/3;}
for(var _r=0;_r<_2.focusItems.length;_r++){if(_2.focusItems[_r]==true){if(_2.focusOptions[_r].mouseWheel==true){Event.stop(e);_2.focusOptions[_r].owner.mouseWheel(_0f);}}}},contextMenu:function(e){var _2=HEventManager;_2.mouseDown(e,false);Event.stop(e);},_5K:function(e){var _2=HEventManager;_2.events[_2.HStatusAltKey]=e.altKey;_2.events[_2.HStatusCtrlKey]=e.ctrlKey;_2.events[_2.HStatusShiftKey]=e.shiftKey;}});onloader('HEventManager.start();');ie_namespace={};function $(_0){if(typeof _0=='string')_0=document.getElementById(_0);return _0;}
helmi={};Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;}
helmi.UserAgent=function(){var b=navigator.appName;var v=navigator.appVersion;var ua=navigator.userAgent.toLowerCase();this.safari=ua.indexOf("safari")>-1;this.opera=ua.indexOf("opera")>-1;this.ns=!this.opera&&!this.safari&&(b=="Netscape");this.ie=!this.opera&&(b=="Microsoft Internet Explorer");this.gecko=!this.safari&&ua.indexOf("gecko")>-1;if(this.ns){this.ns4=(this.v==4);this.v=parseInt(ua.substr(ua.indexOf("netscape")+9,1),10);this.ns6=(this.v==6);this.ns7=(this.v==7);}else if(this.ie){this.ie4=(v.indexOf("MSIE 4")>0);this.ie5=(v.indexOf("MSIE 5")>0);this.ie55=(v.indexOf("MSIE 5.5")>0);this.ie6=(v.indexOf("MSIE 6")>0);this.ie7=(v.indexOf("MSIE 7")>0);}else if(this.opera){this.v=parseInt(ua.substr(ua.indexOf("opera")+6,1),10);this.opera6=(this.v==6);this.opera7=(this.v==7);this.opera8=(this.v==8);this.opera9=(this.v==9);}
this.win=ua.indexOf("win")>-1;this.mac=ua.indexOf("mac")>-1;}
is=new helmi.UserAgent();helmi.Element=Base.extend({constructor:null,getPageLocation:function(_0,_0Q){var _J=0,_K=0;var _f;var _18=_0;if(is.opera){if(is.opera9){do{_f=_0.offsetParent;_J+=_0.offsetLeft;_K+=_0.offsetTop;_0=_f;}while(_0);}else{if(_0.tagName.toLowerCase()=="body"){return[0,0];}
var _T;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"&&_T&&(_T.style.position=="absolute"||_T.style.position=="relative"||_T.style.position=="fixed")){}else{_J+=_0.offsetLeft;_K+=_0.offsetTop;}
if(_f&&_f.tagName.toLowerCase()=="body"&&(_0.style.position=="absolute"||_0.style.position=="relative"||_0.style.position=="fixed"||_0.tagName.toLowerCase()=="input"||_0.tagName.toLowerCase()=="button"||_0.tagName.toLowerCase()=="select"||_0.tagName.toLowerCase()=="textarea")){}else if(_f){_J+=_f.clientLeft;_K+=_f.clientTop;}
_T=_0;_0=_f;}while(_0);}}else if(is.safari){if(_0.tagName.toLowerCase()=="body"){return[0,0];}
var _T;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"&&_T&&(_T.style.position=="absolute"||_T.style.position=="fixed")){}else{_J+=_0.offsetLeft;_K+=_0.offsetTop;}
_T=_0;_0=_f;}while(_0);}else if(is.ns){if(_0Q){var _0h=[];var x=_0.offsetLeft;var y=_0.offsetTop;var _35=null;do{_f=_0.offsetParent;if(_0==_18&&_0.style.position!="absolute"){if(_f&&(_f.style.overflow=="scroll"||_f.style.overflow=="auto")){_35=_f;}}
if(_0.style.overflow=="scroll"||_0.style.overflow=="auto"){_0h.push([_0,_0.style.overflow,_0.scrollLeft,_0.scrollTop]);_0.style.overflow="inherit";}
_0=_f;}while(_0);}
_0=_18;do{_f=_0.offsetParent;if(_0.tagName.toLowerCase()=="body"){}else{if(_0==_18&&_0.style.position!="absolute"){_J+=x;_K+=y;}else{_J+=_0.offsetLeft;_K+=_0.offsetTop;}}
if(_f&&_f.tagName.toLowerCase()=="body"&&(_0.style.position=="absolute"||_0.style.position=="fixed")){}else if(_f){_J+=(_f.offsetWidth-_f.clientWidth)/2;_K+=(_f.offsetHeight-_f.clientHeight)/2;if(_f==_35){_J+=(_f.offsetWidth-_f.clientWidth)/2;_K+=(_f.offsetHeight-_f.clientHeight)/2;}}
_0=_f;}while(_0);if(_0Q){var l=_0h.length;for(var i=0;i<l;i++){_0h[i][0].style.overflow=_0h[i][1];_0h[i][0].scrollLeft=_0h[i][2];_0h[i][0].scrollTop=_0h[i][3];}}}else if(is.ie){if(_0.tagName.toLowerCase()=="body"){return[0,0];}
do{_f=_0.offsetParent;_J+=_0.offsetLeft;_K+=_0.offsetTop;if(_f&&_f.tagName.toLowerCase()=="html"&&_0.style.position=="relative"){_J-=2;_K-=2;}
if(_f&&_f.tagName.toLowerCase()=="html"&&_0.style.position=="absolute"){}else if(_f){_J+=_f.clientLeft;_K+=_f.clientTop;}
_0=_f;}while(_0);}
if(_0Q){_0=_18;do{if(!_0.tagName||_0.tagName.toLowerCase()=="body"){break;}
if(_0.style.position=="fixed"){_J+=window.pageXOffset||document.documentElement.scrollLeft;_K+=window.pageYOffset||document.documentElement.scrollTop;}
_f=_0.parentNode;if(_0!=_18){if(is.opera&&_0.tagName.toLowerCase()=="tr"){}else{_J-=_0.scrollLeft;_K-=_0.scrollTop;}}
_0=_f;}while(_0);}
return[_J,_K];},getSize:function(_0){return[_0.offsetWidth,_0.offsetHeight];},getVisibleSize:function(_0){var w=_0.offsetWidth;var h=_0.offsetHeight;var _p=_0.parentNode;while(_p&&_p.nodeName.toLowerCase()!='body'){var _N;if(!is.ie){_N=document.defaultView.getComputedStyle(_p,null).getPropertyValue('overflow');}else{_N=_p.currentStyle.getAttribute('overflow');}
_N=_N!='visible';if(w>_p.clientWidth&&_N){w=_p.clientWidth-_0.offsetLeft;}
if(h>_p.clientHeight&&_N){h=_p.clientHeight-_0.offsetTop;}
_0=_0.parentNode;_p=_0.parentNode;}
return[w,h];},getVisiblePageLocation:function(_0,_0Q){var _0w=this.getPageLocation(_0,_0Q);var x=_0w[0];var y=_0w[1];var _p=_0.parentNode;while(_p&&_p.nodeName.toLowerCase()!='body'){var _N;if(!is.ie){_N=document.defaultView.getComputedStyle(_p,null).getPropertyValue('overflow');}else{_N=_p.currentStyle.getAttribute('overflow');}
_N=_N!='visible';_0w=this.getPageLocation(_p,_0Q);if(x<_0w[0]&&_N){x=_0w[0];}
if(y<_0w[1]&&_N){y=_0w[1];}
_0=_0.parentNode;_p=_0.parentNode;}
return[x,y];},hasClassName:function(_0,_0H){_0=$(_0);if(!_0)return;var _3c=false;var _0I=_0.className.split(' ');for(var i=0;i<_0I.length;i++){if(_0I[i]==_0H){_3c=true;}}
return _3c;},addClassName:function(_0,_0H){_0=$(_0);if(!_0)return;helmi.Element.removeClassName(_0,_0H);_0.className+=' '+_0H;},removeClassName:function(_0,_0H){_0=$(_0);if(!_0)return;var _2h='';var _0I=_0.className.split(' ');for(var i=0;i<_0I.length;i++){if(_0I[i]!=_0H){if(i>0)_2h+=' ';_2h+=_0I[i];}}
_0.className=_2h;}});Object.extend(Array.prototype,{indexOfObject:function(_1n){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_1n){return i;}}
return-1;},containsObject:function(_1n){return this.indexOfObject(_1n)!=-1;},removeObject:function(_1n){while((i=this.indexOfObject(object))>=0){this.splice(i,1);}},first:function(){return this[0];},last:function(){return this[this.length-1];}});if(!is.ns7){Object.extend(Array.prototype,{indexOf:Array.prototype.indexOfObject});}
helmi.Window=Base.extend({constructor:null,getInnerWidth:function(){return(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;},getInnerHeight:function(){return(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;}});helmi.Event=Base.extend({constructor:null,getPageX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},getPageY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},getKeyCode:function(e){return e.keyCode;},getCharCode:function(e){if(is.ns){return e.charCode;}else{return e.keyCode;}}});HPath=HClass.extend({constructor:null,getRelativePath:function(_l,_A){var _l=this.getRelativeFilePath(_l,_A);return _l.slice(0,_l.lastIndexOf("/")+1);},getRelativeFilePath:function(_l,_A){_l=_l||"";if(_A.charAt(0)=="/"){return _A;}
var _l=_l.substring(0,_l.lastIndexOf("/")+1);var _31=_A.indexOf("../");var _2t=_l.length;var _36;while(_31==0){if((_36=_l.lastIndexOf("/",_2t))!=-1){_2t=_l.lastIndexOf("/",_36-1);_l=_l.substring(0,_2t+1);}else{break;}
_A=_A.substring(3);_31=_A.indexOf("../");}
return _l+_A;}});ie_namespace.iestyleSheetLoaded=function(){if(document.readyState=="complete"&&window.event.srcElement.readyState=="complete"){_0D();}}
stylesheet_refresh=function(_1h){_1h.cssText+="";}
_0D=function(_0){var _0=_0||document.documentElement;while(_0){if(_0.nodeType==1){HStyle._28(_0);}
var _17=_0.firstChild;if(!_17){_17=_0.nextSibling;}
while(!_17&&_0.parentNode){_0=_0.parentNode;_17=_0.nextSibling;}
_0=_17;}}
ie_namespace.ieinlineStyleChanged=function(){var _0=window.event.srcElement;if(window.event.propertyName=="style.opacity"){HOpacityFix._24(_0);}
else if(window.event.propertyName=="src"&&_0.tagName=="IMG"||(_0.tagName=="INPUT"&&_0.type=="image")){HOpacityFix._23(_0);}}
HStyle=HClass.extend({constructor:null,init:function(){this._5y=/^(auto|0cm)$/;},_28:function(_0){var _Z=_0.currentStyle;if((_Z.position=="absolute"||_Z.position=="fixed")&&_Z.left!="auto"&&_Z.right!="auto"&&_Z.width=="auto"){HRighBottoFix._0P(_0);}
if((_Z.position=="absolute"||_Z.position=="fixed")&&_Z.top!="auto"&&_Z.bottom!="auto"&&_Z.height=="auto"){HRighBottoFix._3D(_0);}
if(_0.currentStyle.opacity){HOpacityFix._24(_0);}
if(_0.currentStyle.backgroundImage){HOpacityFix._38(_0);}
if(_0.tagName=="IMG"||(_0.tagName=="INPUT"&&_0.type=="image")){HOpacityFix._23(_0);}}});HNumber=HClass.extend({constructor:null,init:function(){this._44=/^\d+(px)?$/i;this._43=/^\d+%$/;},getPixelValue:function(_0,_6){if(this._44.test(_6)){return parseInt(_6);}
var _07=_0.style.left;var _57=_0.runtimeStyle.left;_0.runtimeStyle.left=_0.currentStyle.left;HRighBottoFix.resizing=true;_0.style.left=_6||0;_6=_0.style.pixelLeft;_0.style.left=_07;HRighBottoFix.resizing=false;_0.runtimeStyle.left=_57;return _6;}});HOpacityFix=HClass.extend({constructor:null,init:function(){this._3x=new RegExp(".png$","i");},_24:function(_0){var _S=(parseFloat(_0.currentStyle.opacity)*100)||1;var _I=_0.filters["DXImageTransform.Microsoft.Alpha"];if(_I){_I.Opacity=_S;_I.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.Alpha(opacity="+_S+")";}},_38:function(_0){var _m=_0.currentStyle.backgroundImage.match(/url\(\s*['"]?([^'")]+)['"]?\s*\)/);if(!_m){return;}else{_m=_m[1];}
var _I=_0.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(this._3x.test(_m)){if(_I){_I.sizingMethod="scale";_I.src=_m;_I.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_m+"',sizingMethod='scale')";}
_0.runtimeStyle.zoom="1";_0.runtimeStyle.backgroundImage="none";}else if(_I){_I.Enabled=false;}},_23:function(_0){if(this._3x.test(_0.src)){var _0j=new Image(_0.width,_0.height);_0j.onload=function(){_0.width=_0j.width;_0.height=_0j.height;_0j=null;}
this._2J(_0,_0j);}},_2J:function(_0,_0j){var _I=_0.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_I){_I.src=_0.src;_I.Enabled=true;}else{_0.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_0.src+"',sizingMethod='scale')";}
var _3V=_0.src;_0.src=HPath.getRelativeFilePath(_3V,"blank.gif");_0j.src=_3V;}});HRighBottoFix=HClass.extend({constructor:null,init:function(){eval("this._4s="+String(this._10).replace(/padding/g,"margin"));eval("this._4t="+String(this._10).replace(/Width/g,"Height").replace(/Left/g,"Top").replace(/Right/g,"Bottom"));eval("this._5E="+String(this._4t).replace(/padding/g,"margin"));eval("this._5D="+String(this._3b).replace(/Width/g,"Height"));eval("this._4H="+String(this._15).replace(/Width/g,"Height").replace(/width/g,"height").replace(/Right/g,"Bottom"));eval("this._5F="+String(this._0M).replace(/Width/g,"Height"));eval("this._3D="+String(this._0P).replace(/Width/g,"Height").replace(/width/g,"height").replace(/left/g,"top").replace(/right/g,"bottom"));this.resizing=false;},_3d:function(_0){return _0.currentStyle.hasLayout;},_10:function(_0){return this._0M(_0,_0.currentStyle.paddingLeft)+
this._0M(_0,_0.currentStyle.paddingRight);},_3b:function(_0){return _0.offsetWidth-_0.clientWidth;},_15:function(_0){var _R=_0.offsetParent;while(_R&&!this._3d(_R)){_R=_R.offsetParent;}
if(!_R._5M){_R._5M=[];}
if(!_0._addedResizewidthFix){_R._5M.push(_0);var _p=_R;while(_p.offsetParent){_p=_p.offsetParent;if(_p._5M){_p._5M.push(_0);}
if(_p.style.position=="absolute"||_p.style.position=="fixed"){break;}}
_0._addedResizewidthFix=true;}
if(!_R._resizewidth){_R.attachEvent("onpropertychange",function(){if(window.event.propertyName=="style.width"){for(var i=0;i<_R._5M.length;i++){HRighBottoFix._0P(_R._5M[i]);}}});_R._resizewidth=true;}
return(_R||document.documentElement).clientWidth;},_0M:function(_0,_6){if(HNumber._43.test(_6)){return parseInt(parseFloat(_6)/100*this._15(_0));}
return HNumber.getPixelValue(_0,_6);},_0P:function(_0){var _F=parseInt(_0.currentStyle.left);var _h=this._15(_0)-this._0M(_0,_0.currentStyle.right)-_F-this._4s(_0);var _h=this._15(_0)-parseInt(_0.currentStyle.right)-_F;if(parseInt(_0.runtimeStyle.width)==_h){return;}
_0.runtimeStyle.width="";if(_0.offsetWidth<_h){if(_h<0){_h=0;}
_h-=this._3b(_0)+this._10(_0);_0.runtimeStyle.width=_h;}}});ie_complete=document.readyState=="complete";ie_initialized=false;ie_documentLoaded=function(){if(document.readyState=="complete"){_0D();}}
ie_fixes=function(){if(is.ie6&&!ie_initialized){if(ie_complete){var _5e=document.createStyleSheet();_5e.cssText='style,link{behavior:url('+ie_htc_path+'ie_css_style.htc)}\n*{behavior:url('+ie_htc_path+'ie_css_element.htc)}';ie_documentLoaded();}else{document.write('<style type="text/css">style,link{behavior:url('+ie_htc_path+'ie_css_style.htc)}\n*{behavior:url('+ie_htc_path+'ie_css_element.htc)}</style>');document.onreadystatechange=ie_documentLoaded;}
ie_initialized=true;}}
ie_fixes();HTransportURL=false;HTransportPoll=true;HTransporter=Base.extend({constructor:null,start:function(_5p){this.url_base=_5p;this.ses_id=0;this.err_msg='';this.isBusy=false;this.syncNum=0;this.syncDelay=0;this.pollMode=HTransportPoll;this.req_timeout=setTimeout('HTransporter.sync();',this.syncDelay);},setPollMode:function(_7){this.pollMode=_7;},failure:function(resp){alert('HTTP ERROR! STOP.');clearTimeout(this.req_timeout);this.isBusy=true;},respond:function(resp){var _3I=resp.responseText;eval(_3I);HTransporter.isBusy=false;},sync:function(){var valid_delay=((this.syncDelay&&this.syncDelay>0)||this.syncDelay==0);if(valid_delay&&this.url_base){if(!this.isBusy){this.isBusy=true;var _3O=HValueManager.toXML();if(""!=_3O||this.pollMode){this.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){HTransporter.respond(resp);},onFailure:function(resp){HTransporter.failure(resp);},method:'post',postBody:'ses_id='+HTransporter.ses_id+_3O};this.req=new Ajax.Request(this.url_base,req_args);HVM.isGetting=false;}
else{this.isBusy=false;}}
this.req_timeout=setTimeout('HTransporter.sync();',this.syncDelay);}},stop:function(){clearTimeout(this.req_timeout);}});onloader("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:[],tosync:[],isSending:false,isGetting:false,add:function(_5,_j){this.values[_5]=_j;},set:function(_5,_6){this.values[_5].set(_6);},del:function(_5){var _3X=this.values[_5];var _5q=_3X.views;for(var _z=0;_z<_5q.length;_z++){var _5k=_5q[_z];_5k.valueObj=new HDummyValue(0,_3X.value);}
this.values[_5]=null;},changed:function(_1i){if(this.isGetting==false){if(this.tosync.indexOf(_1i.id)==-1){this.tosync.push(_1i.id);}}},toXML:function(){var _3y='&HSyncData=';if(!this.isSending){this.isSending=true;var _3Q=this.tosync.length;if(_3Q==0){this.isSending=false;return'';}
var _3S=[];for(var _0N=0;_0N<_3Q;_0N++){var _2w=this.tosync.shift();var _5f=this.values[_2w];_3S.push(_5f.toXML(_0N));}
var _5g=_3S.join('');_3y+='<hsyncvalues version="2240" length="'+_3Q+'">'+_5g+'</hsyncvalues>';this.isSending=false;}
return _3y;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_5,_6){this.id=_5;this.type='[HValue]';this.value=_6;this.views=[];HValueManager.add(_5,this);},set:function(_6){if(_6!=this.value){this.value=_6;HValueManager.changed(this);this.refresh();}},get:function(){return this.value;},bind:function(_E){if(_E===undefined){throw("HValueBindError: _E is undefined!");}
this.views.push(_E);_E.setValueObj(this);},unbind:function(_E){for(var _z=0;_z<this.views.length;_z++){var _5m=this.views[_z];if(_5m===_E){this.views.splice(_z);return;}}},release:function(_E){return this.unbind(_E);},refresh:function(){for(var _z=0;_z<this.views.length;_z++){var _E=this.views[_z];if(_E.value!=this.value){if(!_E._valueIsBeingSet){_E._valueIsBeingSet=true;_E.setValue(this.value);_E._valueIsBeingSet=false;}}}},toXML:function(_0N){var _2w=this.id;var _3R=this.type.slice(1,-1).toLowerCase();var _2x=this.value;var _3P=typeof _2x;var _P=_2x.toString();_P=_P.replace(/&/g,'&amp;');_P=_P.replace(/</g,'&lt;');_P=_P.replace(/>/g,'&gt;');_P=_P.replace(/%/g,'%25');_P=_P.replace(/&/g,'%26');return'<'+_3R+' id="'+_2w+'" order="'+_0N+'" jstype="'+_3P+'" length="'+_2x.toString().length+'">'+_P+'</'+_3R+'>';}});HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _8=arguments;if(_8.length===0){this._0T();}
else if(_8.length==2){this._2T(_8[0],_8[1]);}
else if(_8.length==1){this._0U(_8[0]);}
else{throw"Invalid number of arguments.";}},_0T:function(){this.x=null;this.y=null;},_2T:function(x,y){this.x=x;this.y=y;},_0U:function(_d){this.x=_d.x;this.y=_d.y;},set:function(){var _8=arguments;if(_8.length===0){this._0T();}
else if(_8.length==2){this._2T(_8[0],_8[1]);}
else if(_8.length==1){this._0U(_8[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_d){_8=arguments;if((_8.length==1)&&(_8[0].type==this.type)){_d=_8[0];return new HPoint((this.x+_d.x),(this.y+_d.y));}
else if(_8.length==2){return new HPoint((this.x+_8[0]),(this.y+_8[1]));}else{return new HPoint(0,0);}},subtract:function(){_8=arguments;if((_8.length==1)&&(_8[0].type==this.type)){_d=_8[0];return new HPoint(this.x-_d.x,this.y-_d.y);}
else if(_8.length==2){return new HPoint(this.x-_8[0],this.y-_8[1]);}else{return new HPoint(0,0);}},equals:function(_d){return(this.x==_d.x&&this.y==_d.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _8=arguments;if(_8.length===0){this._0T();}else if(_8.length==4){this._2S(_8[0],_8[1],_8[2],_8[3]);}
else if(_8.length==2){this._0U(_8[0],_8[1]);}
else if(_8.length==1){this._2R(_8[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_0T:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_2S:function(_F,_0m,_1e,_0S){this.top=_0m;this.left=_F;this.bottom=_0S;this.right=_1e;},_0U:function(_3n,_3K){this.top=_3n.y;this.left=_3n.x;this.bottom=_3K.y;this.right=_3K.x;},_2R:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _8=arguments;if(_8.length===0){this._0T();}else if(_8.length==4){this._2S(_8[0],_8[1],_8[2],_8[3]);}
else if(_8.length==2){this._0U(_8[0],_8[1]);}
else if(_8.length==1){this._2R(_8[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_F){this.left=_F;this.updateSecondaryValues();},setRight:function(_1e){this.right=_1e;this.updateSecondaryValues();},setTop:function(_0m){this.top=_0m;this.updateSecondaryValues();},setBottom:function(_0S){this.bottom=_0S;this.updateSecondaryValues();},setLeftTop:function(_d){this.left=_d.x;this.top=_d.y;this.updateSecondaryValues();},setLeftBottom:function(_d){this.left=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setRightTop:function(_d){this.right=_d.x;this.top=_d.y;this.updateSecondaryValues();},setRightBottom:function(_d){this.right=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setWidth:function(_h){this.right=this.left+_h;this.updateSecondaryValues();},setHeight:function(_o){this.bottom=this.top+_o;this.updateSecondaryValues();},setSize:function(){var _8=arguments;if(_8.length===2){_h=_8[0];_o=_8[1];}
else if(_8.length===1){_h=_8.x;_o=_8.y;}
this.right=this.left+_h;this.bottom=this.top+_o;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_j){if(_j instanceof HPoint){return this._4f(_j);}
else if(_j instanceof HRect){return this._4g(_j);}
else{throw"Wrong argument type.";}},_4f:function(_d){return(_d.x>=this.left&&_d.x<=this.right&&_d.y>=this.top&&_d.y<=this.bottom);},_4g:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _8=arguments;if(_8.length===1){this._4C(_8[0]);}else if(_8.length==2){this._3i(_8[0],_8[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_4C:function(_d){this._3i(_d.x,_d.y);},_3i:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _8=arguments;if(_8.length===1){this._4S(_8[0]);}else if(_8.length==2){this._3q(_8[0],_8[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_4S:function(_d){this._3q(_d.x,_d.y);},_3q:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _8=arguments;if(_8.length===1){this._4T(_8[0]);}else if(_8.length==2){this._3r(_8[0],_8[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_4T:function(_d){this._3r(_d.x,_d.y);},_3r:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_j){},unbind:function(_j){}});HDefaultApplicationInterval=20;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _0N=0;_0N<this.apps.length;_0N++){if(this.apps[_0N]){if(!this.busyApps[_0N]){if((this.ticks%this.appPriorities[_0N])==0){this.appTimers[_0N]=setTimeout('if (HSystem.apps['+_0N+']) {HSystem.apps['+_0N+']._3N();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._5P=setTimeout('HSystem.ticker();',10);},addApp:function(_0G,_06){if(this.freeAppIds.length>200){var _0N=this.freeAppIds.shift();this.apps[_0N]=_0G;}else{this.apps.push(_0G);var _0N=this.apps.length-1;}
_0G.parent=this;_0G.parents=[this];_0G.appId=_0N;this.startApp(_0N,_06);return _0N;},startApp:function(_0N,_06){if(_06===undefined){_06=this.defaultInterval;}
this.appPriorities[_0N]=_06;this.busyApps[_0N]=false;},stopApp:function(_0N){this.busyApps[_0N]=true;},reniceApp:function(_0N,_06){this.appPriorities[_0N]=_06;},killApp:function(_0N,_4r){if(!_4r){var _5b=new Date().getTime();while(this.busyApps[_0N]==true){if(new Date().getTime()>_5b+this.maxAppRunTime){break;}}}
this.busyApps[_0N]=true;this.apps[_0N].destroyAllViews();delete this.apps[_0N];this.apps[_0N]=null;this.freeAppIds.push(_0N);}});onloader('HSystem.ticker();');HApplication=HClass.extend({constructor:function(_06){this.type='[HApplication]';this.views=[];this.recycleableViewIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_06);},buildParents:function(_c){_c.parent=this;_c.parents=[];for(var _0v=0;_0v<this.parents.length;_0v++){_c.parents.push(this.parents[_0v]);}
_c.parents.push(this);},addView:function(_c){this.buildParents(_c);this.viewsZOrder.push(_c);if(this.recycleableViewIds.length>100){var _t=this.recycleableViewIds.shift();this.views[_t]=_c;}else{this.views.push(_c);var _t=this.views.length-1;}
return _t;},removeView:function(_t){if(this.views[_t]){this.views[_t].remove();}},destroyView:function(_t){if(this.views[_t]){this.views[_t].die();}},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}},_4X:function(){for(var _z=0;_z<this.views.length;_z++){if(this.views[_z]){this.views[_z].onIdle();}}},_3N:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._4X();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._1N={};this._1r={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_L){this.themePath=_L;},_4n:function(_m){console.log("ERROR: Template Not Found: '"+_m+"' ");},_4m:function(_m){console.log("ERROR: Template Failure: '"+_m+"' ");},_4l:function(_m){console.log("ERROR: Template Exception: '"+_m+"' ");},fetch:function(_m,_0p){var _3J;if(!_0p){var _0p='text/html; charset=UTF-8';}
var _55=new Ajax.Request(_m,{method:'GET',onSuccess:function(_5x){_3J=_5x.responseText;},on404:function(){HThemeManager._4n(_m);},onFailure:function(){HThemeManager._4m(_m);},onException:function(){HThemeManager._4l(_m);},asynchronous:false,contentType:_0p});_55.onStateChange();return _3J;},getThemeGfxPath:function(){var _k=this._1s[0];var _n=this._1s[1];var _w=this._1s[2];var _B=this._1s[3];var _0n=this._0n(_k,_n,_w,_B);return this._M(_0n,'gfx/');},getCssFilePath:function(_0i){return"url('"+this._M(this.getThemeGfxPath(),_0i);+"')";},loadCSS:function(_m){var _0p='text/css';var _0q=this.fetch(_m,_0p);if(!_0q||_0q==""){return;}
_0q=this._2M(_0q);var _07,_1h,_1v;if(is_ie){_07=_W.createStyleSheet();_07.cssText=_0q;}
else{_07=_W.createElement("style");_07.type=_0p;_07.media="all";_1v=_W.getElementsByTagName('head')[0];_1v.appendChild(_07);if(navigator.userAgent.indexOf('KHTML')!=-1){var _4k=_W.createTextNode(_0q);_07.appendChild(_4k);}
else{_07.innerHTML=_0q;}}},_46:function(_1J){if(_1J[_1J.length-1]!='/'){_1J+='/';}
return _1J;},_M:function(_5c,_5d){return this._46(_5c)+_5d;},_0n:function(_k,_n,_w,_B){var _L=_w;if(_w===null){_L=this.themePath;}
if(HThemeMode==0){if(_B){_L=this._M(_L,_B);}
if(_w===null){_L=this._M(_L,_n);_L=this._M(_L,'themes');}
_L=this._M(_L,_k);}
else if(HThemeMode==1){_L=this._M(_L,_k);}
return _L;},_1t:function(_k,_n,_w,_B){this._1s=[_k,_n,_w,_B];var _4i=this._0n(_k,_n,_w,_B);var _4j=this._M('css',_n+'.css');var _1t=this._M(_4i,_4j);return _1t;},_2d:function(_k,_n,_w,_B){var _4w=this._0n(_k,_n,_w,_B);var _4x=this._M('html',_n+'.html');var _4y=this._M(_4w,_4x);return _4y;},loadMarkup:function(_k,_n,_w,_B){if(!this._1N[_k]){this._1N[_k]={};}
var _x=this._1N[_k][_n];if(null===_x||undefined===_x){var _2d=this._2d(_k,_n,_w,_B);_x=this.fetch(_2d);if(null===_x||undefined===_x){_x="";}
this._1N[_k][_n]=_x;}
return _x;},getMarkup:function(_k,_n,_w,_B){if(!this._1r[_k]){var _4c=this._1t(_k,'common',_w,null);this._1r[_k]={};this.loadCSS(_4c);}
if(!this._1r[_k][_n]){var _4d=this._1t(_k,_n,_w,_B);this._1r[_k][_n]=true;this.loadCSS(_4d);}
return this.loadMarkup(_k,_n,_w,_B);},_1p:function(_k,_n,_w,_B){var _0n=this._0n(_k,_n,_w,_B);var _m=this._M(_0n,'gfx/');return _m;},_4e:function(_k,_n,_w,_B,_0i){return this._M(this._1p(_k,_n,_w,_B),_0i);},getThemeGfxFile:function(_0i){return this.getThemeGfxPath()+_0i;},setTheme:function(_3W){this.currentTheme=_3W;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_0E:new RegExp(/#\{([^\}]*)\}/),_2M:function(_0W){while(this._0E.test(_0W)){_0W=_0W.replace(this._0E,eval(RegExp.$1));}
return _0W;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _16=this.markup;var _ID=this.elemId.toString();var _WIDTH=this.rect.width;var _HEIGHT=this.rect.height;while(HMarkupView._0E.test(_16)){_16=_16.replace(HMarkupView._0E,eval(RegExp.$1));}
this.markup=_16;},toggleCSSClass:function(_00,_0V,_3L){if(_00){var _3e=helmi.Element.hasClassName(_00,_0V);if(_3L){if(!_3e){helmi.Element.addClassName(_00,_0V);}}
else{if(_3e){helmi.Element.removeClassName(_00,_0V);}}}}},{_0E:new RegExp(/#\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,constructor:function(_1,_a){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;this.resizeElements=[];this._3F=false;this._2r=[];this.hasResizeElements=false;this.optimizeWidthOnRefresh=true;this.parent=_a;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.recycleableViewIds=[];this.viewsZOrder=[];this._4h();prop_set(this.elemId,'display','none',true);if(this.isAbsolute){prop_set(this.elemId,'position','absolute',true);}else{prop_set(this.elemId,'position','relative',true);}
prop_set(this.elemId,'overflow','hidden',true);this.setRect(_1);this.isHidden=false;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this._2N=_1.left;this._2P=_1.top;this._0L=[];if(!this.isinherited){this.draw();}},setFlexRight:function(_7,_O){if(_7===undefined){_7=true;}
this.flexRight=_7;if(_O===undefined){_O=0;}
this.flexRightOffset=_O;},setFlexLeft:function(_7,_O){if(_7===undefined){_7=true;}
this.flexLeft=_7;if(_O!==undefined){this.rect.setLeft(_O);}},setFlexTop:function(_7,_O){if(_7===undefined){_7=true;}
this.flexTop=_7;if(_O!==undefined){this.rect.setTop(_O);}},setFlexBottom:function(_7,_O){if(_7===undefined){_7=true;}
this.flexBottom=_7;if(_O===undefined){_O=0;}
this.flexBottomOffset=_O;},setAbsolute:function(_7){if(_7===undefined){_7=true;}
this.isAbsolute=_7;},setRelative:function(_7){if(_7===undefined){_7=true}
this.isAbsolute=(!_7);},getThemeGfxPath:function(){if(this.preserveTheme){_k=this.theme;}else{_k=HThemeManager.currentTheme;}
return HThemeManager._1p(_k,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0i){if(this.preserveTheme){_k=this.theme;}else{_k=HThemeManager.currentTheme;}
return HThemeManager._4e(_k,this.componentName,this.themePath,this.packageName,_0i);},addResizeableElement:function(_2q){var _3E=_2q[0];if(this._2r.indexOf(_3E)==-1){this._2r.push(_3E);this.resizeElements.push(_2q);}
this.addResizeableElementCalled=true;return'';},initResizeElements:function(){for(var _0x=0;_0x<this.resizeElements.length;_0x++){var _9=this.bindDomElement(this._2r[_0x]);this.resizeElements[_0x][0]=_9;}
this._3F=true;if(this.resizeElements.length!=0){this.hasResizeElements=true;}},doResizeElements:function(){for(var _0x=0;_0x<this.resizeElements.length;_0x++){var _1G=this.resizeElements[_0x];var _6=Math.max(this.rect.width+_1G[1],0);prop_set(_1G[0],'width',_6+'px');_6=Math.max(this.rect.height+_1G[2],0);prop_set(_1G[0],'height',_6+'px');}},_4h:function(){if(!this.elemId){var _2j;if(this.parent.elemId===undefined){_2j=0;}
else{_2j=this.parent.elemId;}
this.elemId=elem_mk(_2j);this.setStyle('visibility','hidden',true);helmi.Element.addClassName(elem_get(this.elemId),HThemeManager.currentTheme);}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
if(!this._3F&&this.addResizeableElementCalled){this.initResizeElements();}
if(this.hasResizeElements){this.doResizeElements();}
this.drawn=true;var _9=this.elemId;var _1=this.rect;if(this.flexLeft){prop_set(_9,'left',_1.left+'px',true);}else{prop_set(_9,'left','auto',true);}
if(this.flexTop){prop_set(_9,'top',_1.top+'px',true);}else{prop_set(_9,'top','auto',true);}
if(this.flexRight){prop_set(_9,'right',this.flexRightOffset+'px',true);}else{prop_set(_9,'right','auto',true);}
if(this.flexBottom){prop_set(_9,'bottom',this.flexBottomOffset+'px',true);}else{prop_set(_9,'bottom','auto',true);}
if(this.flexLeft&&this.flexRight){prop_set(_9,'width','auto',true);}else{prop_set(_9,'width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){prop_set(_9,'height','auto',true);}else{prop_set(_9,'height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){prop_set(_9,'visibility','inherit',true);}
prop_set(_9,'display','block',true);this._41();if(this._2N!=_1.left||this._2P!=_1.top){this.invalidatePositionCache();this._2N=_1.left;this._2P=_1.top;}
if(is.ie6&&!this.ie_resizefixadded){_0D(elem_get(this.elemId));this.ie_resizefixadded=true;}},_41:function(){prop_set(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this),true);},_1O:function(){var _2E=this.parent.viewsZOrder;for(var i=0;i<_2E.length;i++){if(_2E[i].elemId){prop_set(_2E[i].elemId,'z-index',i,true);}}},draw:function(){this.drawRect();},_3o:function(){var _k;if(this.preserveTheme){_k=this.theme;}
else{_k=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_k,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){prop_set(this.elemId,'display','none',true);this._3o();this.bindMarkupVariables();elem_set(this.elemId,this.markup);this.markupElemIds={};var _3z=['bg','label','state','control','value','subview'];for(var i=0;i<_3z.length;i++){var _04=_3z[i];var _33=_04+this.elemId;var _4v=' id="'+_33+'"';if(this.markup.indexOf(_4v)!=-1){this.markupElemIds[_04]=this.bindDomElement(_33);}}
prop_set(this.elemId,'display','block',true);if(is.ie6&&!this.ie_htmlresizefixadded){_0D(elem_get(this.elemId));this.ie_htmlresizefixadded=true;}},setHTML:function(_1x){elem_set(this.elemId,_1x);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_e,_6,_1Y){if(!this.elemId){return;}
prop_set(this.elemId,_e,_6,_1Y);},style:function(_e){if(!this.elemId){return;}
return prop_get(this.elemId,_e);},setStyleForPart:function(_04,_e,_6,_1Y){if(!this.markupElemIds[_04]){return;}
prop_set(this.markupElemIds[_04],_e,_6,_1Y);},styleForPart:function(_04,_e){if(!this.markupElemIds[_04]){return;}
prop_get(this.markupElemIds[_04],_e);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){this.parent.viewsZOrder.splice(this.parent.viewsZOrder.indexOf(this),1);var _3u=this.parent.views.indexOf(this);this.parent.views[_3u]=null;this.parent.recycleableViewIds.push(_3u);this._1O();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}
this.remove();for(var i=0;i<this._0L.length;i++){elem_del(this._0L[i]);}
this._0L=[];elem_del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var _z=0;_z<this.views.length;_z++){if(this.views[_z]){this.views[_z].onIdle();}}},buildParents:function(_c){_c.parent=this;_c.parents=[];for(var _0v=0;_0v<this.parents.length;_0v++){_c.parents.push(this.parents[_0v]);}
_c.parents.push(this);},addView:function(_c){this.buildParents(_c);this.viewsZOrder.push(_c);if(this.recycleableViewIds.length>100){var _t=this.recycleableViewIds.shift();this.views[_t]=_c;}else{this.views.push(_c);var _t=this.views.length-1;}
return _t;},removeView:function(_t){if(this.views[_t]){this.views[_t].remove();}},destroyView:function(_t){if(this.views[_t]){this.views[_t].die();}},bounds:function(){var _0o=new HRect(this.rect);_0o.right-=_0o.left;_0o.left=0;_0o.bottom-=_0o.top;_0o.top=0;return _0o;},resizeBy:function(_26,_1k){var _1=this.rect;_1.right+=_26;_1.bottom+=_1k;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_h,_o){var _1=this.rect;_1.right=_1.left+_h;_1.bottom=_1.top+_o;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_26,_1k){this.rect.offsetBy(_26,_1k);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _27=this.zIndex();this.parent.viewsZOrder.splice(_27,1);this.parent.viewsZOrder.push(this);this._1O();},sendToBack:function(){if(!this.parent){return;}
var _27=this.zIndex();this.parent.viewsZOrder.splice(_27,1);this.parent.viewsZOrder.splice(0,0,this);this._1O();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this);},stringWidth:function(_1K,_1z,_9){if(_1z!==undefined&&_1z!=null){_1K=_1K.substring(0,_1z);}
if(_9===undefined||_9==null){_9=this.elemId;}
var _0e=elem_mk(_9);prop_set(_0e,"visibility","hidden",true);prop_set(_0e,"position","absolute",true);prop_set(_0e,"white-space","nowrap",true);elem_set(_0e,_1K);var _h;var _o;if(is_ie||is.opera){_h=elem_get(_0e).offsetWidth;if(arguments[3]){_o=elem_get(_0e).offsetHeight;}}else{_h=prop_get(_0e,"width");if(arguments[3]){_o=prop_get(_0e,"height");}}
elem_del(_0e);if(arguments[3]){return new HPoint(parseInt(_h,10),parseInt(_o,10));}else{return parseInt(_h,10);}},pageX:function(){var _b=0;var _4=this;while(_4){if(_4.elemId&&_4.rect){_b+=elem_get(_4.elemId).offsetLeft;_b-=elem_get(_4.elemId).scrollLeft;}
_4=_4.parent;}
return _b;},pageY:function(){var _c=0;var _4=this;while(_4){if(_4.elemId&&_4.rect){_c+=elem_get(_4.elemId).offsetTop;_c-=elem_get(_4.elemId).scrollTop;}
_4=_4.parent;}
return _c;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].invalidatePositionCache();}}},bindDomElement:function(_Q){var _1X=elem_bind(_Q);if(_1X){this._0L.push(_1X);}
return _1X;},unbindDomElement:function(_00){var _3h=this._0L.indexOf(_00);if(_3h>-1){elem_del(_00);this._0L.splice(_3h,1);}},animateTo:function(_j,_0g,_0t){if(_j instanceof HPoint){var _1=new HRect(_j,_j);_1.setSize(this.rect.width,this.rect.height);this._1W(_1,_0g);}
else if(_j instanceof HRect){this._1W(_j,_0g);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._1o){window.clearInterval(this._1o);this._1o=null;var _F=parseInt(this.style('left'),10);var _0m=parseInt(this.style('top'),10);var _h=parseInt(this.style('width'),10);var _o=parseInt(this.style('height'),10);this.rect.set(_F,_0m,_F+_h,_0m+_o);if(this._2K){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_1W:function(_1,_0g,_0t){if(null===_0g||undefined===_0g){_0g=500;}
if(null===_0t||undefined===_0t||_0t<1){_0t=50;}
if(!this._1o){this._2K=false;this.onAnimationStart();var _5a=new Date().getTime();var _v=this;this._1o=window.setInterval(function(){_v._5z({startTime:_5a,duration:_0g,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_v.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_v.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_v.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_v.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0t));}},_5z:function(_j){var _3Y=new Date().getTime();if(_3Y<_j.startTime+_j.duration){var _49=_3Y-_j.startTime;for(var i=0;i<_j.props.length;i++){var _25=_j.props[i].from;var _3Z=_j.props[i].to;if(_25!=_3Z){var _4Z=_j.transition(_49,_25,(_3Z-_25),_j.duration);this.setStyle(_j.props[i].prop,_4Z+_j.props[i].unit);}}}else{for(var i=0;i<_j.props.length;i++){this.setStyle(_j.props[i].prop,_j.props[i].to+_j.props[i].unit);}
this._2K=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a);}
else{this.isinherited=true;this.base(_1,_a);this.isinherited=false;}
if(!_3){_3={};}
var options=new(HComponentDefaults.extend(_3));this.options=options;var _s=options.label;this.setLabel(_s);var _0X=options.events;this.setEvents(_0X);this.type='[HControl]';this.refreshOnValueChange=true;if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _4E=(_3.minValue||_3.maxValue);if(_4E){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(null!==options.visible&&undefined!==options.visible){if(options.visible){this.show();}
else{this.hide();}}
if(!this.isinherited){this.draw();}},setAction:function(_2H){this.action=_2H;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
HEventManager.unregister(this);this.base();},setLabel:function(_s){this.label=_s;this.refresh();},setEnabled:function(_7){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].setEnabled(_7);}}
if(this.enabled==_7){return;}
this.enabled=_7;if(_7){HEventManager.register(this,this.events);}
else{HEventManager.unregister(this);}
this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_DISABLED,!this.enabled);},setValue:function(_6){if(_6==undefined){return;}
if(!this.valueObj){return;}
if(_6!==this.value){this.value=_6;this.valueObj.set(this.value);if(this.refreshOnValueChange){this.refresh();}}},setValueObj:function(_1T){this.valueObj=_1T;this.setValue(_1T.value);},setValueRange:function(_6,_1D,_1A){this.minValue=_1D;this.maxValue=_1A;_6=(_6<_1D)?_1D:_6;_6=(_6>_1A)?_1A:_6;this.setValue(_6);this.refresh();},setEvents:function(_0X){if(!this.events){var _4p=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false});this.events=new _4p;}
if(_0X){this.events.extend(_0X);}
this.events.owner=this;HEventManager.focusOptions[this.elemId]=this.events;var _3p=this.events.mouseMove;var _2f=HEventManager.mouseMoveItems.indexOf(this.elemId);if(_3p&&(_2f==-1)){HEventManager.mouseMoveItems.push(this.elemId);}else if((!_3p)&&(_2f!=-1)){HEventManager.split(_2f);}
this.isDragged=false;},setMouseMove:function(_7){this.events.mouseMove=_7;this.setEvents();},setMouseDown:function(_7){this.events.mouseDown=_7;this.setEvents();},setMouseUp:function(_7){this.events.mouseUp=_7;this.setEvents();},setMouseWheel:function(_7){this.events.mouseWheel=_7;this.setEvents();},setDraggable:function(_7){this.events.draggable=_7;this.setEvents();},setDroppable:function(_7){this.events.droppable=_7;this.setEvents();},setKeyDown:function(_7){this.events.keyDown=_7;this.setEvents();},setKeyUp:function(_7){this.events.keyUp=_7;this.setEvents();},focus:function(){},blur:function(){},gainedActiveStatus:function(_03){},_5C:function(_03){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_03);},lostActiveStatus:function(_G){},_5J:function(_G){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_G);},mouseMove:function(_b,_c){},mouseDown:function(_b,_c,_Y){},mouseUp:function(_b,_c,_Y){},mouseWheel:function(_0f){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_2a){},keyUp:function(_2a){},_4L:function(e){if(!Event.element){return;}
var _v=Event.element(e);while(_v&&_v.owner===undefined){_v=_v.parentNode;}
if(!_v){return;}
var _2=_v.owner;HEventManager.focus(_2);Event.stop(e);},_4K:function(e){if(!Event.element){return;}
var _v=Event.element(e);while(_v&&_v.owner===undefined){_v=_v.parentNode;}
if(!_v){return;}
var _2=_v.owner;HEventManager.blur(_2);Event.stop(e);},invalidatePositionCache:function(){this.base();HEventManager.invalidatePositionCache(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_5,_6){this.id=_5;this.value=_6;this.type='[HDummyValue]';},set:function(_6){this.value=_6;},get:function(){return this.value;},bind:function(_1i){},unbind:function(_1i){}});HComponentDefaults=HClass.extend({label:"Untitled",events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HButton=HControl.extend({componentName:"button",constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}
this._1u=[this.rect.width,this.rect.height];},setLabelHeightDiff:function(_4M){this._3l=_4M;return'';},setLabelWidthDiff:function(_4O){this._3m=_4O;return'';},onIdle:function(){if(this.drawn){var _h=this.rect.width;var _o=this.rect.height;if((_h!=this._1u[0])||(_o!=this._1u[1])){this._1u[0]=_h;this._1u[1]=_o;if(this.markupElemIds.label){var _3f=parseInt(_o+this._3l,10);prop_set(this.markupElemIds.label,'line-height',_3f+'px');if(is.ie6){var _5w=parseInt(_h+this._3m,10);prop_set(this.markupElemIds.label,'height',_3f+'px');prop_set(this.markupElemIds.label,'width',_5w+'px');}}}}},draw:function(){if(!this.drawn){this.drawRect();this._3l=0;this._3m=0;this.drawMarkup();}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}}}});HClickButton=HButton.extend({constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HClickButton]';this.setMouseDown(true);this.setMouseUp(true);this._0J=false;this._0Z=false;if(!this.isinherited){this.draw();}},focus:function(){if(!this._0J&&!this._0Z){this._0Z=true;this._0J=false;}
this.base();},blur:function(){if(!this._0J){this._0Z=false;}
this.base();},mouseDown:function(x,y,_Y){if(this._0Z){this._0J=true;}
this.base(x,y,_Y);},mouseUp:function(x,y,_Y){if(this._0Z&&this._0J){this._0J=false;this.click(x,y,_Y);}
this.base(x,y,_Y);},click:function(x,y,_Y){this.setValue(this.value+1);if(this.action){this.action();}}});HToggleButton=HClickButton.extend({constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HToggleButton]';if(!this.isinherited){this.draw();}},click:function(x,y,_Y){this.setValue(!this.value);},setValue:function(_7){if(null===_7||undefined===_7){_7=false;}
this.base(_7);},_5n:function(){if(this.markupElemIds.control){var _4=elem_get(this.markupElemIds.control);this.toggleCSSClass(_4,HToggleButton.cssOn,this.value);this.toggleCSSClass(_4,HToggleButton.cssOff,!this.value);}},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}
if(this.markupElemIds.control){this._5n();}}}},{cssOn:"on",cssOff:"off"});HStringView=HControl.extend({componentName:"stringview",constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HStringView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(!this._0z){this._0z=this.bindDomElement("stringview"+this.elemId);}
if(this._0z){elem_set(this._0z,this.value);}}},stringElementId:function(){return this._0z;},optimizeWidth:function(){if(this._0z){var _5j=elem_get(this._0z).cloneNode(true);var _1L=elem_add(_5j);prop_set(_1L,"visibility","hidden",true);elem_append(0,_1L);var _h=this.stringWidth(this.value,null,_1L);if(!isNaN(_h)){var _47=prop_get_extra_width(this._0z);this.resizeTo(_h+_47,this.rect.height);}
elem_del(_1L);}}});HWindowLabel=HButton.extend({packageName:"window",componentName:"windowlabel",constructor:function(_1,_a,_3){if(!_3){_3={};}
if(!_3.events){_3.events={};}
if(!_3.events.draggable){_3.events.draggable=true;}
if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HWindowLabel]';if(!this.isinherited){this.draw();}},gainedActiveStatus:function(_03){HEventManager.changeActiveControl(this.parent.parent);},startDrag:function(_b,_c){this.parent.parent.startDrag(_b,_c);},doDrag:function(_b,_c){this.parent.parent.doDrag(_b,_c);},endDrag:function(_b,_c){this.parent.parent.endDrag(_b,_c);}});HWindowBar=HButton.extend({packageName:"window",componentName:"windowbar",constructor:function(_1,_a,_3){if(!_3){_3={};}
if(!_3.events){_3.events={};}
if(!_3.events.draggable){_3.events.draggable=true;}
if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HWindowBar]';if(!this.isinherited){this.draw();}},setLabel:function(_s){this.label=_s;if(this.parent.windowLabel){this.parent.windowLabel.setLabel(_s);}},startDrag:function(_b,_c){this.parent.startDrag(_b,_c);},doDrag:function(_b,_c){this.parent.doDrag(_b,_c);},endDrag:function(_b,_c){this.parent.endDrag(_b,_c);}});HWindowView=HView.extend({packageName:"window",componentName:"windowview",constructor:function(_1,_a){if(this.isinherited){this.base(_1,_a);}
else{this.isinherited=true;this.base(_1,_a);this.isinherited=false;}
this.type='[HWindowView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawMarkup();var _0C=this.bindDomElement(HWindowView._1j+this.elemId);if(!_0C){throw("HWindowView: The HTML template must have an element with "+"the ID '"+HWindowView._1j+" + this.elemId'.");}
elem_append(this.parent.elemId,_0C);elem_append(0,this.elemId);elem_del(this.elemId);elem_replace(this.elemId,elem_get(_0C));}
this.drawRect();}},{_1j:"windowview"});HWindowControl=HControl.extend({packageName:"window",componentName:"windowcontrol",constructor:function(_1,_a,_3){if(!_3){_3={};}
var _08=Base.extend({minSize:[64,32],maxSize:[4096,3072],barHeight:21,resizeW:4,resizeE:4,resizeN:4,resizeS:4,resizeNW:[4,4],resizeNE:[4,4],resizeSW:[4,4],resizeSE:[16,16],menuBar:null});_3=new(_08.extend(_3))();if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HWindowControl]';this.preserveTheme=true;this._2p();this.setDraggable(true);this.drawRect();this.drawMarkup();this.buildWinParts();this.setLabel(this.label);if(_3.menuBar){this.setMenuBar(_3.menuBar);}
if(!this.isinherited){this.draw();}},buildWinParts:function(){this.calcWindowPartRects();this.windowBar=new HWindowBar(this._g.windowBarRect,this,{label:this.label});this.windowBar.draw();this.windowLabel=new HWindowLabel(this._g.windowLabelRect,this.windowBar,{label:this.label});this.windowLabel.draw();this.windowView=new HWindowView(this._g.windowViewRect,this);this.windowView.draw();},_2p:function(){this._g={dragWindow:false,resizeW:false,resizeE:false,resizeN:false,resizeS:false,resizeNW:false,resizeNE:false,resizeSW:false,resizeSE:false,dragWindowRect:new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN),resizeNRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.options.resizeN),resizeSRect:new HRect(this.options.resizeW,this.rect.height-this.options.resizeS,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,this.options.resizeN,this.options.resizeW,this.rect.height-this.options.resizeS),resizeERect:new HRect(this.rect.width-this.options.resizeE,this.options.resizeN,this.rect.width,this.rect.height-this.options.resizeS),resizeNWRect:new HRect(0,0,this.options.resizeNW[0],this.options.resizeNW[1]),resizeNERect:new HRect(this.rect.width-this.options.resizeNE[0],0,this.rect.width,this.options.resizeNE[1]),resizeSWRect:new HRect(0,this.rect.height-this.options.resizeSW[1],this.options.resizeSW[0],this.rect.height),resizeSERect:new HRect(this.rect.width-this.options.resizeSE[0],this.rect.height-this.options.resizeSE[1],this.rect.width,this.rect.height)};},checkWindowSizeConstrains:function(){var _3H=this._g.resizeW||this._g.resizeSW||this._g.resizeNW;var _3G=this._g.resizeN||this._g.resizeNE||this._g.resizeNW;if(this.rect.width<this.options.minSize[0]){if(_3H){this.rect.left=this.rect.right-this.options.minSize[0];}
this.rect.setWidth(this.options.minSize[0]);}else if(this.rect.width>this.options.maxSize[0]){if(_3H){this.rect.left=this.rect.right-this.options.maxSize[0];}
this.rect.setWidth(this.options.maxSize[0]);}
if(this.rect.height<this.options.minSize[1]){if(_3G){this.rect.top=this.rect.bottom-this.options.minSize[1];}
this.rect.setHeight(this.options.minSize[1]);}else if(this.rect.height>this.options.maxSize[1]){if(_3G){this.rect.top=this.rect.bottom-this.options.maxSize[1];}
this.rect.setHeight(this.options.maxSize[1]);}
var _2c=0-this.options.resizeW;if(this.rect.left<_2c){this.rect.left=_2c;this.rect.right=this.rect.width+_2c;}
var _2B=0-this.options.resizeN;if(this.rect.top<_2B){this.rect.top=_2B;this.rect.bottom=this.rect.height+_2B;}},startDrag:function(_b,_c){this._1f=new HPoint(_b,_c);this._3A=new HPoint(_b,_c);this._1g=new HRect(this.rect);this._2p();var _05=this._1f.subtract(this._1g.leftTop);if(this._g.resizeNWRect.contains(_05)){this._D=_05;this._g.resizeNW=true;}else if(this._g.resizeNERect.contains(_05)){this._D=this._1f.subtract(this._1g.rightTop);this._g.resizeNE=true;}else if(this._g.resizeSWRect.contains(_05)){this._D=this._1f.subtract(this._1g.leftBottom);this._g.resizeSW=true;}else if(this._g.resizeSERect.contains(_05)){this._D=this._1f.subtract(this._1g.rightBottom);this._g.resizeSE=true;}else if(this._g.resizeNRect.contains(_05)){this._D=_c-this.rect.top;this._g.resizeN=true;}else if(this._g.resizeSRect.contains(_05)){this._D=_c-this.rect.bottom;this._g.resizeS=true;}else if(this._g.resizeWRect.contains(_05)){this._D=_b-this.rect.left;this._g.resizeW=true;}else if(this._g.resizeERect.contains(_05)){this._D=_b-this.rect.right;this._g.resizeE=true;}else if(this._g.dragWindowRect.contains(_05)){this._D=this._1f.subtract(this._1g.leftTop);this._g.dragWindow=true;}
this.bringToFront();this.doDrag(_b,_c);},doDrag:function(_b,_c){var _C;var _0r=new HPoint(_b,_c);if(!this._3A.equals(_0r)){if(this._g.resizeNW==true){_C=_0r.subtract(this._D);this.rect.setLeftTop(_C);}else if(this._g.resizeNE==true){_C=_0r.subtract(this._D);this.rect.setRightTop(_C);}else if(this._g.resizeSW==true){_C=_0r.subtract(this._D);this.rect.setLeftBottom(_C);}else if(this._g.resizeSE==true){_C=_0r.subtract(this._D);this.rect.setRightBottom(_C);}else if(this._g.resizeN==true){_C=_c-this._D;this.rect.top=_C;this.rect.updateSecondaryValues();}else if(this._g.resizeS==true){_C=_c-this._D;this.rect.bottom=_C;this.rect.updateSecondaryValues();}else if(this._g.resizeW==true){_C=_b-this._D;this.rect.left=_C;this.rect.updateSecondaryValues();}else if(this._g.resizeE==true){_C=_b-this._D;this.rect.right=_C;this.rect.updateSecondaryValues();}else if(this._g.dragWindow==true){_C=_0r.subtract(this._D);this.rect.offsetTo(_C);}
this.checkWindowSizeConstrains();this.setStyle('left',this.rect.left+'px',true);this.setStyle('top',this.rect.top+'px',true);this.setStyle('width',this.rect.width+'px',true);this.setStyle('height',this.rect.height+'px',true);if(this._g.dragWindow==false){this.calcWindowPartRects();}
this._3A=_0r;}},endDrag:function(_b,_c){this.doDrag(_b,_c);},calcWindowPartRects:function(){var _1P=new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN);var _42=new HRect(0,0,_1P.width,_1P.height);var _1l=new HRect(this.options.resizeW,this.options.resizeN+this.options.barHeight,this.rect.width-this.options.resizeE,this.rect.height-this.options.resizeS);if(this.menuBar){var _1C=this.options.menuBarHeight;if(_1C+this.options.resizeN+this.options.barHeight>this.rect.height-this.options.resizeS){_1C=this.rect.height-this.options.barHeight-
this.options.resizeS-this.options.resizeN;}
_1l.setTop(_1l.top+_1C);this.menuBar.resizeTo(_1l.width,_1C);}
if(!this._g.windowBarRect){this._g.windowBarRect=_1P;this._g.windowLabelRect=_42;this._g.windowViewRect=_1l;}else{this.windowBar.setRect(_1P);this.windowLabel.setRect(_42);this.windowView.setRect(_1l);}},draw:function(){this.drawRect();},setLabel:function(_s){if(this.drawn&&this.windowLabel){this.windowLabel.setLabel(_s);}
this.base(_s);},refresh:function(){if(this.windowBar){this.windowBar.refresh();}
this.drawRect();},setMenuBar:function(_1B){if(_1B==this.menuBar){return;}
if(this.menuBar){this.menuBar.die();}
this.menuBar=_1B;if(_1B){this.options.menuBarHeight=this.menuBar.rect.height;this.menuBar.remove();this.addView(this.menuBar);elem_append(this.elemId,this.menuBar.elemId);this.menuBar.moveTo(this.windowView.rect.left,this.windowBar.rect.bottom);}
this.calcWindowPartRects();}});HWindow=HWindowControl;HTabLabel=HButton.extend({packageName:"tab",componentName:"tablabel",constructor:function(_F,_o,_a,_3){if(!_3){var _3={};}
if(!_3.label){throw("HTabLabelConstructionError: No label specified!");}
if(null===_3.tabId||undefined===_3.tabId){throw("HTabLabelConstructionError: No id specified!");}
if(!_3.tabControl){throw("HTabLabelConstructionError: No control specified!");}
if(!_3.highlight){_3.highlight=false;}
if(!_3.events){_3.events={mouseDown:true};}
var _1=new HRect(_F,0,_F+5,_o);if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HTabLabel]';this._5l="tabhighlight";this.tabControl=_3.tabControl;this.tabId=_3.tabId;this.setHighlight(_3.highlight);if(!this.isinherited){this.draw();}},setHighlight:function(_7){this.highlight=_7;if(_7){this.tabControl.selectTab(this.tabId);}
this.refresh();},mouseDown:function(_b,_c,_5A){if(this.tabControl&&!this.highlight){this.setHighlight(true);}},setValue:function(_6){this.base(_6);if(this.value&&this.tabControl){this.tabControl.selectTab(this.tabId);}},refresh:function(){if(this.drawn){if(this.markupElemIds['label']){var _2b=this.stringWidth(this.label,null,this.markupElemIds['label']);this.rect.setWidth(_2b+16);}
this.base();if(!this._11){this._11=this.bindDomElement(this._5l+this.elemId);}
if(this._11){var _3j=(prop_get(this._11,'visibility')=='hidden');if(_3j&&this.highlight){prop_set(this._11,'visibility','',true);}
else if(!_3j&&!this.highlight){prop_set(this._11,'visibility','hidden',true);}}}}});HTabBar=HView.extend({packageName:"tab",componentName:"tabbar",constructor:function(_1,_a){if(this.isinherited){this.base(_1,_a);}
else{this.isinherited=true;this.base(_1,_a);this.isinherited=false;}
this.type='[HTabBar]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.drawRect();}});HTabView=HView.extend({packageName:"tab",componentName:"tabview",constructor:function(_1,_a,_3){if(!_3){_3={};}
if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HTabView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawMarkup();var _0C=this.bindDomElement(HTabView._1j+this.elemId);if(!_0C){throw("HTabView: The HTML template must have an element with "+"the ID '"+HTabView._1j+" + this.elemId'.");}
elem_append(this.parent.elemId,_0C);elem_append(0,this.elemId);elem_del(this.elemId);elem_replace(this.elemId,elem_get(_0C));}
this.drawRect();}},{_1j:"tabview"});HTabControl=HControl.extend({packageName:"tab",componentName:"tabcontrol",constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.tabDefaults=new(Base.extend({label:'Untitled',labelHeight:21,labelWidth:192}).extend(_3));this.type='[HTabControl]';this.preserveTheme=true;this.tabs={};this._H=[];this._4P=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){var _1=this.rect;var _4G=new HRect(0,0,_1.width,this.tabDefaults.labelHeight);this.labelViews=new HTabBar(_4G,this);this.labelViews.draw();this._02=0;var _5s=0;var _5v=this.tabDefaults.labelHeight;var _5t=_1.width;var _5u=(_1.height-this.tabDefaults.labelHeight);var _2D=new HRect(_5s,_5v,_5t,_5u);this.tabDefaults.rect=new HRect(0,0,_2D.width,_2D.height);this.tabViews=new HView(_2D,this);this.tabViews.draw();this.activeTab=-1;this.drawn=true;}
this.drawRect();},addTab:function(_0k,_2s,_s,_2b){if(this._4P){this.draw();}
if(!_0k){var _5i=this.tabDefaults.rect;_0k=new HTabView(_5i,this.tabViews);_0k.draw();}
if(!_s){var _s=this.tabDefaults.label;}
_0k.hide();if(this._H.length==0){_2s=true;}
var _0B=_0k.viewId;this.tabs[_0B]=_0k;this._H.push(_0B);var _5h={label:_s,tabId:_0B,tabControl:this,highlight:false};var _2y=new HTabLabel(this._02,this.tabDefaults.labelHeight,this.labelViews,_5h);this._02+=(_2y.rect.width-1);var _3T=_2y.viewId;_2y.draw();if(_3T!=_0B){throw("HTabControlAddTabError: tabId Mismatch ("+_3T+" vs. "+
_0B+")");}
if(_2s){this.selectTab(_0B);}
this.refresh();return _0B;},_54:function(){if(this._H.length==0){this._02=0;}
var _14=0;for(var i=0;i<this._H.length;i++){var _s=this.labelViews.views[this._H[i]];this._02=_14+_s.rect.width;var _3U=new HRect(_14,_s.rect.top,this._02,_s.rect.bottom);this.labelViews.views[this._H[i]].setRect(_3U);this._02--;_14=this._02;}},removeTab:function(_U){if(this.tabs[_U]instanceof HTabView){if(this.activeTab==_U){if(!this.selectPreviousTab()){if(!this.selectNextTab()){this.activeTab=-1;}}}
this.tabViews.destroyView(_U);this.labelViews.destroyView(_U);this.tabs[_U]=null;var _0A=this._H.indexOf(_U);this._H.splice(_0A,1);this._54();}},removeSelectedTab:function(){this.removeTab(this.activeTab);},selectNextTab:function(){var _0A=this._H.indexOf(this.activeTab);if(_0A<this._H.length-1){return this.selectTab(this._H[_0A+1]);}
return false;},selectPreviousTab:function(){var _0A=this._H.indexOf(this.activeTab);if(_0A>0){return this.selectTab(this._H[_0A-1]);}
return false;},selectTab:function(_U){if(this.activeTab!=_U){var _0A=this._H.indexOf(_U);if(_0A>-1){if(this.activeTab!=-1){this.tabViews.views[this.activeTab].setStyle('display','none');this.tabViews.views[this.activeTab].hide();this.labelViews.views[this.activeTab].setHighlight(false);}
this.activeTab=_U;this.tabViews.views[this.activeTab].setStyle('display','block');this.tabViews.views[this.activeTab].show();this.labelViews.views[this.activeTab].setHighlight(true);return true;}}
return false;},numberOfTabs:function(){return this._H.length;}});HTab=HTabControl;HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_a,_3){if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
if(!_3){_3={};}
var _08=Base.extend({value:0,minValue:0,maxValue:100});_08=_08.extend(_3);_3=new _08();this.value=_3.value;this.minValue=_3.minValue;this.maxValue=_3.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._4Y='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_O){this.progressFrameHeight=_O;},setProgressFrameNum:function(_4Q){this.progressFrames=_4Q;},setValue:function(_6){this.base(_6);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _O=this.currProgressFrame*this.progressFrameHeight;prop_set(this.progressbarElemId,'background-position','0px -'+_O+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._4B();}},_4B:function(){this.progressbarElemId=this.bindDomElement(this._4Y+this.elemId);this.drawProgress();},_5r:function(){var _4D=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _53=parseInt(Math.round(_4D),10)+'px';return _53;},drawProgress:function(){if(this.progressbarElemId){var _52=this._5r();prop_set(this.progressbarElemId,'width',_52);}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_a,_3){this._2z="textcontrol";if(this.isinherited){this.base(_1,_a,_3);}
else{this.isinherited=true;this.base(_1,_a,_3);this.isinherited=false;}
this.type='[HTextControl]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},die:function(){if(this.drawn){var _Q=this._2z+this.elemId;Event.stopObserving(_Q,'mousedown',this._1I);Event.stopObserving(_Q,'mousemove',this._1I);Event.stopObserving(_Q,'focus',this._2I);Event.stopObserving(_Q,'blur',this._2X);}
this.base();},setEnabled:function(_7){this.base(_7);if(this._X){elem_get(this._X).disabled=(!this.enabled);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._X=this.bindDomElement(this._2z+this.elemId);if(this._X){elem_get(this._X).setAttribute("autocomplete","off");this.setEnabled(this.enabled);}
this._59();this.drawn=true;}
this.refresh();},_59:function(){var _Q=this._2z+this.elemId;this._1I=function(_4o){HControl.stopPropagation(_4o);};Event.observe(_Q,'mousedown',this._1I,false);Event.observe(_Q,'mousemove',this._1I,false);var _v=this;this._2I=function(event){HEventManager.changeActiveControl(_v);};Event.observe(_Q,'focus',this._2I,false);this._2X=function(event){_v._5o();HEventManager.changeActiveControl(null);};Event.observe(_Q,'blur',this._2X,false);},refresh:function(){this.base();if(this._X){if(elem_get(this._X).value!=this.value){elem_get(this._X).value=this.value;}}},onIdle:function(){if(this.active){this._5o();}},_5o:function(){if(this.drawn){if(elem_get(this._X).value!=this.value){this.setValue(elem_get(this._X).value);}}},lostActiveStatus:function(_G){if(this._X){elem_get(this._X).blur();}}});HTextArea=HTextControl.extend({componentName:"textarea",constructor:function(_1,_a,_3){this.base(_1,_a,_3);}});HLeechView=HView.extend({constructor:function(_4,_a){if(typeof _4=='number'){this.elemId=_4;_4=elem_get(this.elemId);}
else if(typeof _4=='string'){this.elemId=elem_bind(_4);_4=elem_get(this.elemId);}
else if(typeof _4=='object'){this.elemId=elem_add(_4);}
var _1a=(_4.clientLeft||_4.offsetLeft);var _1b=(_4.clientTop||_4.offsetTop);var _2o=_1a+(_4.clientWidth||_4.offsetWidth);var _2n=_1b+(_4.clientHeight||_4.offsetHeight);var _1=new HRect(_1a,_1b,_2o,_2n);this.base(_1,_a);this.type='[HLeechView]';}});HLeechComponentExtension={constructor:function(_4,_a,_3){if(typeof _4=='number'){this.elemId=_4;_4=elem_get(this.elemId);}
else if(typeof _4=='string'){this.elemId=elem_bind(_4);_4=elem_get(this.elemId);}
else if(typeof _4=='object'){this.elemId=elem_add(_4);}
var _1a=(_4.clientLeft||_4.offsetLeft);var _1b=(_4.clientTop||_4.offsetTop);var _2o=_1a+(_4.clientWidth||_4.offsetWidth);var _2n=_1b+(_4.clientHeight||_4.offsetHeight);var _1=new HRect(_1a,_1b,_2o,_2n);this.base(_1,_a,_3);this.type=this.type.replace('[H','[HLeech');}}
HLeechControl=HControl.extend(HLeechComponentExtension);