
HEventManager=HClass.extend({events:[false,false,0,0,[],[],[],false,false,false],HStatusButton:0,HStatusButton2:1,HStatusCoordX:2,HStatusCoordY:3,HStatusKeys:4,HStatusDirection:5,HStatusSpeed:6,HStatusAltKey:7,HStatusCtrlKey:8,HStatusShiftKey:9,constructor:null,start:function(){var H0K;if(is_ie){H0K=document;}
else{H0K=window;}
Event.observe(H0K,'mousemove',this.mouseMove);Event.observe(H0K,'mouseup',this.mouseUp);Event.observe(H0K,'mousedown',this.mouseDown);Event.observe(H0K,'keyup',this.keyUp);Event.observe(H0K,'keydown',this.keyDown);Event.observe(H0K,'keypress',this.keyPress);Event.observe(H0K,'contextmenu',this.contextMenu);if(window.addEventListener){window.addEventListener('DOMMouseScroll',this.mouseWheel,false);}
window.onmousewheel=document.onmousewheel=this.mouseWheel;this.focusItems=[];this.eventItems=[];this.focusOptions=[];this.dragItems=[];this.hoverItems=[];this.hoverInterval=100;this.hoverTimer=new Date().getTime();this.topmostDroppable=null;this.H1G=[];this.H3z=true;this.activeControl=null;this.H3B=null;},enablePositionCache:function(){this.H3z=true;},disablePositionCache:function(){this.H3z=false;},invalidatePositionCache:function(Hk){if(Hk){this.H1G[Hk]=null;}
else{this.H1G=[];}},register:function(HI,H4Q){var Hk=HI.elemId;var Hc=elem_get(Hk);if(is_ie){Hc.setAttribute('owner',HI);}
else{Hc.owner=HI;}
this.eventItems[Hk]=true;this.focusItems[Hk]=false;this.focusOptions[Hk]=H4Q;Event.observe(Hc,'mouseover',HI.H24);},unregister:function(HI){if(HI==this.activeControl){this.changeActiveControl(null);}
var Hk=HI.elemId;var Hc=elem_get(Hk);this.eventItems[Hk]=false;this.focusItems[Hk]=false;this.H1G[Hk]=null;try{Event.stopObserving(Hc,'mouseover',HI.H24);}catch(e){window.status=e;}},focus:function(HI){var Hk=HI.elemId;var Hc=elem_get(Hk);if(this.focusItems[Hk]==false&&HI.isDragged==false){Event.stopObserving(Hc,'mouseover',HI.H24);Event.observe(Hc,'mouseout',HI.H3A);this.focusItems[Hk]=true;HI.focus();}},blur:function(HI){var Hk=HI.elemId;var Hc=elem_get(Hk);if(this.focusItems[Hk]==true&&HI.isDragged==false){Event.stopObserving(Hc,'mouseout',HI.H3A);Event.observe(Hc,'mouseover',HI.H24);this.focusItems[Hk]=false;HI.blur();}},mouseMove:function(e){var H5=HEventManager;var H8=Event.pointerX(e);var H9=Event.pointerY(e);var H4R=false;H5.events[H5.HStatusCoordX]=H8;H5.events[H5.HStatusCoordY]=H9;for(var i=0;i<H5.dragItems.length;i++){var Hk=H5.dragItems[i];H5.focusOptions[Hk].owner.doDrag(H8,H9);H5.invalidatePositionCache(Hk);H4R=true;}
if(new Date().getTime()>H5.hoverTimer+H5.hoverInterval){H5.H4V();for(var i=0;i<H5.dragItems.length;i++){var H3y=H5.topmostDroppable;H5.topmostDroppable=null;var Hk=H5.dragItems[i];var H0v=H5.focusOptions[Hk].owner;for(var j=0;j<H5.hoverItems.length;j++){var H2C=H5.hoverItems[j];if(H2C!=Hk&&H5.focusOptions[H2C].owner){var H2D=H5.focusOptions[H2C].owner;if(!H5.topmostDroppable||H2D.zIndex()>H5.topmostDroppable.zIndex()||H2D.parent==H5.topmostDroppable){if(H2D.events.droppable){H5.topmostDroppable=H2D;}}}}
if(H3y!=H5.topmostDroppable){if(H3y){H3y.onHoverEnd(H0v);}
if(H5.topmostDroppable){H5.topmostDroppable.onHoverStart(H0v);}}}
H5.hoverTimer=new Date().getTime();}
if(H4R){Event.stop(e);}},H4V:function(){var H5=HEventManager;H5.hoverItems=[];var x=H5.events[H5.HStatusCoordX];var y=H5.events[H5.HStatusCoordY];for(var HN=0;HN<H5.eventItems.length;HN++){if(!H5.eventItems[HN]||!H5.focusOptions[HN].owner){continue;}
var H4W=H5.focusOptions[HN].owner;var Hc=elem_get(HN);var H1n;if(!H5.H3z||!H5.H1G[HN]){H5.H1G[HN]={H1N:[H4W.pageX(),H4W.pageY()],H4S:helmi.Element.getVisibleSize(Hc)};}
H1n=H5.H1G[HN];if(x>=H1n.H1N[0]&&x<=H1n.H1N[0]+H1n.H4S[0]&&y>=H1n.H1N[1]&&y<=H1n.H1N[1]+H1n.H4S[1]){H5.hoverItems.push(HN);}}},mouseDown:function(e,H03){var H5=HEventManager;H5.H2B(e);var H4T=false;if(H03===undefined){H03=Event.isLeftClick(e);}
if(H03){H5.events[H5.HStatusButton]=true;}else{H5.events[H5.HStatusButton2]=true;}
var H8=H5.events[H5.HStatusCoordX];var H9=H5.events[H5.HStatusCoordY];var HE=null;var H2E=[];var H3C=[];for(var i=0;i<H5.focusItems.length;i++){if(H5.focusItems[i]==true){if(H5.focusOptions[i].owner.enabled){HE=H5.focusOptions[i].owner;}
if((H5.focusOptions[i].draggable==true)&&(H5.dragItems.indexOf(i)==-1)){H2E.push(i);}
else if(H5.focusOptions[i].mouseDown==true){H3C.push(i);}}}
H5.changeActiveControl(HE);for(var i=0;i<H2E.length;i++){H5.dragItems.push(H2E[i]);H5.focusOptions[H2E[i]].owner.startDrag(H8,H9);H4T=true;}
for(var i=0;i<H3C.length;i++){H5.focusOptions[H3C[i]].owner.mouseDown(H8,H9,H03);}
if(H4T){document.body.focus();H5.H6u=document.onselectstart;document.onselectstart=function(){return false;};}
if(H5.hoverItems.length>0){Event.stop(e);}
return true;},changeActiveControl:function(HE){var H5=HEventManager;var H0A=H5.activeControl;if(HE!=H0A){if(H0A){H0A.active=false;H0A._lostActiveStatus(HE);}
H5.activeControl=null;if(HE){HE.active=true;H5.activeControl=HE;HE._gainedActiveStatus(H0A);}}},mouseUp:function(e){var H5=HEventManager;H5.H2B(e);var H4U=false;H5.events[H5.HStatusButton]=false;H5.events[H5.HStatusButton2]=false;var H8=H5.events[H5.HStatusCoordX];var H9=H5.events[H5.HStatusCoordY];for(var i=0;i<H5.dragItems.length;i++){var Hk=H5.dragItems[i];var H0v=H5.focusOptions[Hk].owner;H0v.endDrag(H8,H9);H4U=true;H5.H4V();if(H5.hoverItems.indexOf(Hk)<0){H5.blur(H0v);}
if(H5.topmostDroppable){H5.topmostDroppable.onHoverEnd(H0v);H5.topmostDroppable.onDrop(H0v);H5.topmostDroppable=null;}}
H5.dragItems=[];if(H4U){document.onselectstart=H5.H6u;}
for(var HN=0;HN<H5.focusItems.length;HN++){if(H5.focusItems[HN]==true){if(H5.focusOptions[HN].mouseUp==true){H5.focusOptions[HN].owner.mouseUp(H8,H9,true);}}}
return true;},keyDown:function(e){var H5=HEventManager;H5.H2B(e);var _theKeyCode=e.keyCode;if(H5.activeControl&&H5.focusOptions[H5.activeControl.elemId].keyDown==true){Event.stop(e);if(H5.H3B!=_theKeyCode){H5.activeControl.keyDown(_theKeyCode);}}
var _realTimeArr=H5.events[H5.HStatusKeys];if(_realTimeArr.indexOf(_theKeyCode)==-1){_realTimeArr.push(_theKeyCode);}
H5.H3B=_theKeyCode;},keyUp:function(e){var H5=HEventManager;H5.H2B(e);var _theKeyCode=e.keyCode;H5.H3B=null;if(H5.activeControl&&H5.focusOptions[H5.activeControl.elemId].keyUp==true){H5.activeControl.keyUp(_theKeyCode);}
var _realTimeArr=H5.events[H5.HStatusKeys];var _keyCodeIndex=_realTimeArr.indexOf(_theKeyCode);if(_keyCodeIndex!=-1){_realTimeArr.splice(_keyCodeIndex,1);}},keyPress:function(e){var H5=HEventManager;if(H5.activeControl&&H5.focusOptions[H5.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var H5=HEventManager;var H0a=0;if(!e){e=window.event;}
if(e.wheelDelta){H0a=e.wheelDelta/120;if(window.opera)H0a=-H0a;}else if(e.detail){H0a=-e.detail/3;}
for(var HN=0;HN<H5.focusItems.length;HN++){if(H5.focusItems[HN]==true){if(H5.focusOptions[HN].mouseWheel==true){Event.stop(e);H5.focusOptions[HN].owner.mouseWheel(H0a);}}}},contextMenu:function(e){var H5=HEventManager;H5.mouseDown(e,false);Event.stop(e);},H2B:function(e){var H5=HEventManager;H5.events[H5.HStatusAltKey]=e.altKey;H5.events[H5.HStatusCtrlKey]=e.ctrlKey;H5.events[H5.HStatusShiftKey]=e.shiftKey;}});onloader('HEventManager.start();');HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var Ha=arguments;if(Ha.length===0){this.H1C();}
else if(Ha.length==2){this.H4v(Ha[0],Ha[1]);}
else if(Ha.length==1){this.H1D(Ha[0]);}
else{throw"Invalid number of arguments.";}},H1C:function(){this.x=null;this.y=null;},H4v:function(x,y){this.x=x;this.y=y;},H1D:function(Hi){this.x=Hi.x;this.y=Hi.y;},set:function(){var Ha=arguments;if(Ha.length===0){this.H1C();}
else if(Ha.length==2){this.H4v(Ha[0],Ha[1]);}
else if(Ha.length==1){this.H1D(Ha[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(H0){if(this.x<H0.left){this.x=H0.left;}
if(this.y<H0.top){this.y=H0.top;}
if(this.x>H0.right){this.x=H0.right;}
if(this.y>H0.bottom){this.y=H0.bottom;}},add:function(Hi){Ha=arguments;if((Ha.length==1)&&(Ha[0].type==this.type)){Hi=Ha[0];return new HPoint((this.x+Hi.x),(this.y+Hi.y));}
else if(Ha.length==2){return new HPoint((this.x+Ha[0]),(this.y+Ha[1]));}else{return new HPoint(0,0);}},subtract:function(){Ha=arguments;if((Ha.length==1)&&(Ha[0].type==this.type)){Hi=Ha[0];return new HPoint(this.x-Hi.x,this.y-Hi.y);}
else if(Ha.length==2){return new HPoint(this.x-Ha[0],this.y-Ha[1]);}else{return new HPoint(0,0);}},equals:function(Hi){return(this.x==Hi.x&&this.y==Hi.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var Ha=arguments;if(Ha.length===0){this.H1C();}else if(Ha.length==4){this.H3o(Ha[0],Ha[1],Ha[2],Ha[3]);}
else if(Ha.length==2){this.H1D(Ha[0],Ha[1]);}
else if(Ha.length==1){this.H2w(Ha[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},H1C:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},H3o:function(Hy,HH,HU,HY){this.top=HH;this.left=Hy;this.bottom=HY;this.right=HU;},H1D:function(H4w,H4x){this.top=H4w.y;this.left=H4w.x;this.bottom=H4x.y;this.right=H4x.x;},H2w:function(H0){this.top=H0.top;this.left=H0.left;this.bottom=H0.bottom;this.right=H0.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var Ha=arguments;if(Ha.length===0){this.H1C();}else if(Ha.length==4){this.H3o(Ha[0],Ha[1],Ha[2],Ha[3]);}
else if(Ha.length==2){this.H1D(Ha[0],Ha[1]);}
else if(Ha.length==1){this.H2w(Ha[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(Hy){this.left=Hy;this.updateSecondaryValues();},setRight:function(HU){this.right=HU;this.updateSecondaryValues();},setTop:function(HH){this.top=HH;this.updateSecondaryValues();},setBottom:function(HY){this.bottom=HY;this.updateSecondaryValues();},setLeftTop:function(Hi){this.left=Hi.x;this.top=Hi.y;this.updateSecondaryValues();},setLeftBottom:function(Hi){this.left=Hi.x;this.bottom=Hi.y;this.updateSecondaryValues();},setRightTop:function(Hi){this.right=Hi.x;this.top=Hi.y;this.updateSecondaryValues();},setRightBottom:function(Hi){this.right=Hi.x;this.bottom=Hi.y;this.updateSecondaryValues();},setWidth:function(Hf){this.right=this.left+Hf;this.updateSecondaryValues();},setHeight:function(HM){this.bottom=this.top+HM;this.updateSecondaryValues();},setSize:function(){var Ha=arguments;if(Ha.length===2){Hf=Ha[0];HM=Ha[1];}
else if(Ha.length===1){Hf=Ha.x;HM=Ha.y;}
this.right=this.left+Hf;this.bottom=this.top+HM;this.updateSecondaryValues();},intersects:function(H0){return(((H0.left>=this.left&&H0.left<=this.right)||(H0.right>=this.left&&H0.right<=this.right))&&((H0.top>=this.top&&H0.top<=this.bottom)||(H0.bottom>=this.top&&H0.bottom<=this.bottom)));},contains:function(Hg){if(Hg instanceof HPoint){return this.H6f(Hg);}
else if(Hg instanceof HRect){return this.H6g(Hg);}
else{throw"Wrong argument type.";}},H6f:function(Hi){return(Hi.x>=this.left&&Hi.x<=this.right&&Hi.y>=this.top&&Hi.y<=this.bottom);},H6g:function(H0){return(H0.left>=this.left&&H0.right<=this.right&&H0.top>=this.top&&H0.bottom<=this.bottom);},insetBy:function(){var Ha=arguments;if(Ha.length===1){this.H6h(Ha[0]);}else if(Ha.length==2){this.H4y(Ha[0],Ha[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},H6h:function(Hi){this.H4y(Hi.x,Hi.y);},H4y:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var Ha=arguments;if(Ha.length===1){this.H6i(Ha[0]);}else if(Ha.length==2){this.H4z(Ha[0],Ha[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},H6i:function(Hi){this.H4z(Hi.x,Hi.y);},H4z:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var Ha=arguments;if(Ha.length===1){this.H6j(Ha[0]);}else if(Ha.length==2){this.H4A(Ha[0],Ha[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},H6j:function(Hi){this.H4A(Hi.x,Hi.y);},H4A:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(H0){return(this.left==H0.left&&this.top==H0.top&&this.right==H0.right&&this.bottom==H0.bottom);},intersection:function(H0){return new HRect(Math.max(this.left,H0.left),Math.max(this.top,H0.top),Math.min(this.right,H0.right),Math.min(this.bottom,H0.bottom));},union:function(H0){return new HRect(Math.min(this.left,H0.left),Math.min(this.top,H0.top),Math.max(this.right,H0.right),Math.max(this.bottom,H0.bottom));},bind:function(Hg){},unbind:function(Hg){}});HDefaultApplicationInterval=100;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var Hv=0;Hv<this.apps.length;Hv++){if(this.apps[Hv]){if(!this.busyApps[Hv]){if((this.ticks%this.appPriorities[Hv])==0){this.appTimers[Hv]=setTimeout('if (HSystem.apps['+Hv+']) {HSystem.apps['+Hv+'].H4N();}',0);}}}}},ticker:function(){this.ticks++;this.scheduler();this.H6M=setTimeout('HSystem.ticker();',0);},addApp:function(H1F,H0e){if(this.freeAppIds.length>200){var Hv=this.freeAppIds.shift();this.apps[Hv]=H1F;}else{this.apps.push(H1F);var Hv=this.apps.length-1;}
H1F.parent=this;H1F.parents=[this];H1F.appId=Hv;this.startApp(Hv,H0e);return Hv;},startApp:function(Hv,H0e){if(H0e===undefined){H0e=this.defaultInterval;}
this.appPriorities[Hv]=H0e;this.busyApps[Hv]=false;},stopApp:function(Hv){this.busyApps[Hv]=true;},reniceApp:function(Hv,H0e){this.appPriorities[Hv]=H0e;},killApp:function(Hv,H6q){if(!H6q){var _startedWaiting=new Date().getTime();while(this.busyApps[Hv]==true){if(new Date().getTime()>_startedWaiting+this.maxAppRunTime){break;}}}
this.busyApps[Hv]=true;this.apps[Hv].destroyAllViews();delete this.apps[Hv];this.apps[Hv]=null;this.freeAppIds.push(Hv);}});onloader('HSystem.ticker();');HApplication=HClass.extend({constructor:function(H0e){this.type='[HApplication]';this.views=[];this.recycleableViewIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,H0e);},buildParents:function(HS){HS.parent=this;HS.parents=[];for(var H1i=0;H1i<this.parents.length;H1i++){HS.parents.push(this.parents[H1i]);}
HS.parents.push(this);},addView:function(HS){this.buildParents(HS);this.viewsZOrder.push(HS);if(this.recycleableViewIds.length>100){var HL=this.recycleableViewIds.shift();this.views[HL]=HS;}else{this.views.push(HS);var HL=this.views.length-1;}
return HL;},removeView:function(HL){if(this.views[HL]){this.views[HL].remove();}},destroyView:function(HL){if(this.views[HL]){this.views[HL].die();}},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}},H6c:function(){for(var Hs=0;Hs<this.views.length;Hs++){if(this.views[Hs]){this.views[Hs].onIdle();}}},H4N:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this.H6c();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='helmiTheme';HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._tmplCache={};this._cssCache={};this.currentTheme='helmiTheme';},setThemePath:function(_path){this.themePath=_path;},_errTemplateNotFound:function(HC){alert("ERROR: Template Not Found: '"+HC+"' ");},_errTemplateFailure:function(HC){alert("ERROR: Template Failure: '"+HC+"' ");},_errTemplateException:function(HC){alert("ERROR: Template Exception: '"+HC+"' ");},fetch:function(HC,_contentType){var H4P;if(!_contentType){var _contentType='text/html; charset=UTF-8';}
var H6r=new Ajax.Request(HC,{method:'GET',onSuccess:function(H6s){H4P=H6s.responseText;},on404:function(){HThemeManager._errTemplateNotFound(HC);},onFailure:function(){HThemeManager._errTemplateFailure(HC);},onException:function(){HThemeManager._errTemplateException(HC);},asynchronous:false,contentType:_contentType});H6r.onStateChange();return H4P;},getThemeGfxPath:function(){var Hp=this._cssEvalParams[0];var HF=this._cssEvalParams[1];var HR=this._cssEvalParams[2];var _pkgName=this._cssEvalParams[3];var _urlPrefix=this._urlPrefix(Hp,HF,HR,_pkgName);return this._joinPath(_urlPrefix,'gfx/');},getCssFilePath:function(_fileName){return"url('"+this._joinPath(this.getThemeGfxPath(),_fileName);+"')";},loadCSS:function(HC){var _contentType='text/css';var H1m=this.fetch(HC,_contentType);if(!H1m||H1m==""){return;}
H1m=this._bindCSSVariables(H1m);var H0C,H23,H2A;if(is_ie){H0C=H0s.createStyleSheet();H0C.cssText=H1m;}
else{H0C=H0s.createElement("style");H0C.type=_contentType;H0C.media="all";H2A=H0s.getElementsByTagName('head')[0];H2A.appendChild(H0C);if(navigator.userAgent.indexOf('KHTML')!=-1){var H6t=H0s.createTextNode(H1m);H0C.appendChild(H6t);}
else{H0C.innerHTML=H1m;}}},_addSlash:function(_str){if(_str[_str.length-1]!='/'){_str+='/';}
return _str;},_joinPath:function(_str1,_str2){return this._addSlash(_str1)+_str2;},_urlPrefix:function(Hp,HF,HR,_pkgName){var _path=HR;if(HR===null){_path=this.themePath;}
if(HThemeMode==0){if(_pkgName){_path=this._joinPath(_path,_pkgName);}
if(HR===null){_path=this._joinPath(_path,HF);_path=this._joinPath(_path,'themes');}
_path=this._joinPath(_path,Hp);}
else if(HThemeMode==1){_path=this._joinPath(_path,Hp);}
return _path;},_cssUrl:function(Hp,HF,HR,_pkgName){this._cssEvalParams=[Hp,HF,HR,_pkgName];var _cssPrefix=this._urlPrefix(Hp,HF,HR,_pkgName);var _cssSuffix=this._joinPath('css',HF+'.css');var _cssUrl=this._joinPath(_cssPrefix,_cssSuffix);return _cssUrl;},_markupUrl:function(Hp,HF,HR,_pkgName){var _htmlPrefix=this._urlPrefix(Hp,HF,HR,_pkgName);var _htmlSuffix=this._joinPath('html',HF+'.html');var _htmlUrl=this._joinPath(_htmlPrefix,_htmlSuffix);return _htmlUrl;},loadMarkup:function(Hp,HF,HR,_pkgName){if(!this._tmplCache[Hp]){this._tmplCache[Hp]={};}
var HP=this._tmplCache[Hp][HF];if(null===HP||undefined===HP){var _markupUrl=this._markupUrl(Hp,HF,HR,_pkgName);HP=this.fetch(_markupUrl);if(null===HP||undefined===HP){HP="";}
this._tmplCache[Hp][HF]=HP;}
return HP;},getMarkup:function(Hp,HF,HR,_pkgName){if(!this._cssCache[Hp]){var _commonCssUrl=this._cssUrl(Hp,'common',HR,null);this._cssCache[Hp]={};this.loadCSS(_commonCssUrl);}
if(!this._cssCache[Hp][HF]){var _componentCssUrl=this._cssUrl(Hp,HF,HR,_pkgName);this._cssCache[Hp][HF]=true;this.loadCSS(_componentCssUrl);}
return this.loadMarkup(Hp,HF,HR,_pkgName);},_componentGfxPath:function(Hp,HF,HR,_pkgName){var _urlPrefix=this._urlPrefix(Hp,HF,HR,_pkgName);var HC=this._joinPath(_urlPrefix,'gfx/');return HC;},_componentGfxFile:function(Hp,HF,HR,_pkgName,_fileName){return this._joinPath(this._componentGfxPath(Hp,HF,HR,_pkgName),_fileName);},getThemeGfxFile:function(_fileName){return this.getThemeGfxPath()+_fileName;},setTheme:function(H4O){this.currentTheme=H4O;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},H1j:new RegExp(/#\{([^\}]*)\}/),_bindCSSVariables:function(_cssTmpl){while(this.H1j.test(_cssTmpl)){_cssTmpl=_cssTmpl.replace(this.H1j,eval(RegExp.$1));}
return _cssTmpl;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var H20=this.markup;var _ID=this.elemId.toString();var _WIDTH=this.rect.width;var _HEIGHT=this.rect.height;while(HMarkupView.H1j.test(H20)){H20=H20.replace(HMarkupView.H1j,eval(RegExp.$1));}
this.markup=H20;},toggleCSSClass:function(H0B,H21,H4B){if(H0B){var H4C=helmi.Element.hasClassName(H0B,H21);if(H4B){if(!H4C){helmi.Element.addClassName(H0B,H21);}}
else{if(H4C){helmi.Element.removeClassName(H0B,H21);}}}}},{H1j:new RegExp(/#\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,constructor:function(H0,H4){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;this.resizeElements=[];this.H4I=false;this.H3u=[];this.hasResizeElements=false;this.optimizeWidthOnRefresh=true;this.parent=H4;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.recycleableViewIds=[];this.viewsZOrder=[];this.H6k();prop_set(this.elemId,'display','none',true);prop_set(this.elemId,'position','absolute',true);prop_set(this.elemId,'overflow','hidden',true);this.setRect(H0);this.isHidden=false;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this.H4F=H0.left;this.H4G=H0.top;this.H1E=[];if(!this.isinherited){this.draw();}},getThemeGfxPath:function(){if(this.preserveTheme){Hp=this.theme;}else{Hp=HThemeManager.currentTheme;}
return HThemeManager._componentGfxPath(Hp,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_fileName){if(this.preserveTheme){Hp=this.theme;}else{Hp=HThemeManager.currentTheme;}
return HThemeManager._componentGfxFile(Hp,this.componentName,this.themePath,this.packageName,_fileName);},addResizeableElement:function(H3t){var H4H=H3t[0];if(this.H3u.indexOf(H4H)==-1){this.H3u.push(H4H);this.resizeElements.push(H3t);}
this.addResizeableElementCalled=true;return'';},initResizeElements:function(){for(var H10=0;H10<this.resizeElements.length;H10++){var Hk=this.bindDomElement(this.H3u[H10]);this.resizeElements[H10][0]=Hk;}
this.H4I=true;if(this.resizeElements.length!=0){this.hasResizeElements=true;}},doResizeElements:function(){for(var H10=0;H10<this.resizeElements.length;H10++){var H2y=this.resizeElements[H10];var H3=Math.max(this.rect.width+H2y[1],0);prop_set(H2y[0],'width',H3+'px');H3=Math.max(this.rect.height+H2y[2],0);prop_set(H2y[0],'height',H3+'px');}},H6k:function(){if(!this.elemId){var H3p;if(this.parent.elemId===undefined){H3p=0;}
else{H3p=this.parent.elemId;}
this.elemId=elem_mk(H3p);this.setStyle('visibility','hidden',true);helmi.Element.addClassName(elem_get(this.elemId),HThemeManager.currentTheme);}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
if(!this.H4I&&this.addResizeableElementCalled){this.initResizeElements();}
if(this.hasResizeElements){this.doResizeElements();}
this.drawn=true;var Hk=this.elemId;var H0=this.rect;prop_set(Hk,'left',H0.left+'px',true);prop_set(Hk,'top',H0.top+'px',true);prop_set(Hk,'width',H0.width+'px',true);prop_set(Hk,'height',H0.height+'px',true);if(undefined===this.isHidden||this.isHidden==false){prop_set(Hk,'visibility','inherit',true);}
prop_set(Hk,'display','block',true);this.H4E();if(this.H4F!=H0.left||this.H4G!=H0.top){this.invalidatePositionCache();this.H4F=H0.left;this.H4G=H0.top;}
if(is.ie6&&!this.ie_resizefixadded){_traverseTree(elem_get(this.elemId));this.ie_resizefixadded=true;}},H4E:function(){prop_set(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this),true);},H2x:function(){var H3r=this.parent.viewsZOrder;for(var i=0;i<H3r.length;i++){if(H3r[i].elemId){prop_set(H3r[i].elemId,'z-index',i,true);}}},draw:function(){this.drawRect();},H4D:function(){var Hp;if(this.preserveTheme){Hp=this.theme;}
else{Hp=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(Hp,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){prop_set(this.elemId,'display','none',true);this.H4D();this.bindMarkupVariables();elem_set(this.elemId,this.markup);this.markupElemIds={};var _predefinedPartNames=['bg','label','state','control','value','subview'];for(var i=0;i<_predefinedPartNames.length;i++){var _partName=_predefinedPartNames[i];var _elemName=_partName+this.elemId;var _htmlIdMatch=' id="'+_elemName+'"';if(this.markup.indexOf(_htmlIdMatch)!=-1){this.markupElemIds[_partName]=this.bindDomElement(_elemName);}}
prop_set(this.elemId,'display','block',true);if(is.ie6&&!this.ie_htmlresizefixadded){_traverseTree(elem_get(this.elemId));this.ie_htmlresizefixadded=true;}},setHTML:function(H13){elem_set(this.elemId,H13);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(H0){if(this.rect){this.rect.unbind(this);}
this.rect=H0;this.rect.bind(this);this.refresh();},setStyle:function(Hd,H3,H3s){if(!this.elemId){return;}
prop_set(this.elemId,Hd,H3,H3s);},style:function(Hd){if(!this.elemId){return;}
return prop_get(this.elemId,Hd);},setStyleForPart:function(_partName,Hd,H3,H3s){if(!this.markupElemIds[_partName]){return;}
prop_set(this.markupElemIds[_partName],Hd,H3,H3s);},styleForPart:function(_partName,Hd){if(!this.markupElemIds[_partName]){return;}
prop_get(this.markupElemIds[_partName],Hd);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){this.parent.viewsZOrder.splice(this.parent.viewsZOrder.indexOf(this),1);var H4K=this.parent.views.indexOf(this);this.parent.views[H4K]=null;this.parent.recycleableViewIds.push(H4K);this.H2x();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].die();}}
this.remove();for(var i=0;i<this.H1E.length;i++){elem_del(this.H1E[i]);}
this.H1E=[];elem_del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var Hs=0;Hs<this.views.length;Hs++){if(this.views[Hs]){this.views[Hs].onIdle();}}},buildParents:function(HS){HS.parent=this;HS.parents=[];for(var H1i=0;H1i<this.parents.length;H1i++){HS.parents.push(this.parents[H1i]);}
HS.parents.push(this);},addView:function(HS){this.buildParents(HS);this.viewsZOrder.push(HS);if(this.recycleableViewIds.length>100){var HL=this.recycleableViewIds.shift();this.views[HL]=HS;}else{this.views.push(HS);var HL=this.views.length-1;}
return HL;},removeView:function(HL){if(this.views[HL]){this.views[HL].remove();}},destroyView:function(HL){if(this.views[HL]){this.views[HL].die();}},bounds:function(){var H1k=new HRect(this.rect);H1k.right-=H1k.left;H1k.left=0;H1k.bottom-=H1k.top;H1k.top=0;return H1k;},resizeBy:function(H3q,H22){var H0=this.rect;H0.right+=H3q;H0.bottom+=H22;H0.updateSecondaryValues();this.drawRect();},resizeTo:function(Hf,HM){var H0=this.rect;H0.right=H0.left+Hf;H0.bottom=H0.top+HM;H0.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(H3q,H22){this.rect.offsetBy(H3q,H22);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var Hb=this.zIndex();this.parent.viewsZOrder.splice(Hb,1);this.parent.viewsZOrder.push(this);this.H2x();},sendToBack:function(){if(!this.parent){return;}
var Hb=this.zIndex();this.parent.viewsZOrder.splice(Hb,1);this.parent.viewsZOrder.splice(0,0,this);this.H2x();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this);},stringWidth:function(H0T,HX,Hk){if(HX!==undefined&&HX!=null){H0T=H0T.substring(0,HX);}
if(Hk===undefined||Hk==null){Hk=this.elemId;}
var H0J=elem_mk(Hk);prop_set(H0J,"visibility","hidden",true);prop_set(H0J,"position","absolute",true);prop_set(H0J,"white-space","nowrap",true);elem_set(H0J,H0T);var Hf;var HM;if(is_ie||is.opera){Hf=elem_get(H0J).offsetWidth;if(arguments[3]){HM=elem_get(H0J).offsetHeight;}}else{Hf=prop_get(H0J,"width");if(arguments[3]){HM=prop_get(H0J,"height");}}
elem_del(H0J);if(arguments[3]){return new HPoint(parseInt(Hf,10),parseInt(HM,10));}else{return parseInt(Hf,10);}},pageX:function(){var H8=0;var Hc=this;while(Hc){if(Hc.elemId&&Hc.rect){H8+=elem_get(Hc.elemId).offsetLeft;H8-=elem_get(Hc.elemId).scrollLeft;}
Hc=Hc.parent;}
return H8;},pageY:function(){var H9=0;var Hc=this;while(Hc){if(Hc.elemId&&Hc.rect){H9+=elem_get(Hc.elemId).offsetTop;H9-=elem_get(Hc.elemId).scrollTop;}
Hc=Hc.parent;}
return H9;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].invalidatePositionCache();}}},bindDomElement:function(H0i){var H3v=elem_bind(H0i);if(H3v){this.H1E.push(H3v);}
return H3v;},unbindDomElement:function(H0B){var H4J=this.H1E.indexOf(H0B);if(H4J>-1){elem_del(H0B);this.H1E.splice(H4J,1);}},animateTo:function(Hg,H11,H1l){if(Hg instanceof HPoint){var H0=new HRect(Hg,Hg);H0.setSize(this.rect.width,this.rect.height);this.H3w(H0,H11);}
else if(Hg instanceof HRect){this.H3w(Hg,H11);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this.H2z){window.clearInterval(this.H2z);this.H2z=null;var Hy=parseInt(this.style('left'),10);var HH=parseInt(this.style('top'),10);var Hf=parseInt(this.style('width'),10);var HM=parseInt(this.style('height'),10);this.rect.set(Hy,HH,Hy+Hf,HH+HM);if(this.H4L){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},H3w:function(H0,H11,H1l){if(null===H11||undefined===H11){H11=500;}
if(null===H1l||undefined===H1l||H1l<1){H1l=50;}
if(!this.H2z){this.H4L=false;this.onAnimationStart();var H6m=new Date().getTime();var Hw=this;this.H2z=window.setInterval(function(){Hw.H6n({startTime:H6m,duration:H11,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:Hw.rect.left,to:H0.left,unit:'px'},{prop:'top',from:Hw.rect.top,to:H0.top,unit:'px'},{prop:'width',from:Hw.rect.width,to:H0.width,unit:'px'},{prop:'height',from:Hw.rect.height,to:H0.height,unit:'px'}]});},Math.round(1000/H1l));}},H6n:function(Hg){var HV=new Date().getTime();if(HV<Hg.startTime+Hg.duration){var H6o=HV-Hg.startTime;for(var i=0;i<Hg.props.length;i++){var H3x=Hg.props[i].from;var H4M=Hg.props[i].to;if(H3x!=H4M){var H6p=Hg.transition(H6o,H3x,(H4M-H3x),Hg.duration);this.setStyle(Hg.props[i].prop,H6p+Hg.props[i].unit);}}}else{for(var i=0;i<Hg.props.length;i++){this.setStyle(Hg.props[i].prop,Hg.props[i].to+Hg.props[i].unit);}
this.H4L=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4);}
else{this.isinherited=true;this.base(H0,H4);this.isinherited=false;}
if(!H1){H1={};}
var options=new(HComponentDefaults.extend(H1));this.options=options;var HB=options.label;this.setLabel(HB);var H1U=options.events;this.setEvents(H1U);this.type='[HControl]';this.refreshOnValueChange=true;if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var H6e=(H1.minValue||H1.maxValue);if(H6e){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(null!==options.visible&&undefined!==options.visible){if(options.visible){this.show();}
else{this.hide();}}
if(!this.isinherited){this.draw();}},setAction:function(H4u){this.action=H4u;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
HEventManager.unregister(this);this.base();},setLabel:function(HB){this.label=HB;this.refresh();},setEnabled:function(Hh){for(var i=0;i<this.views.length;i++){if(this.views[i]){this.views[i].setEnabled(Hh);}}
if(this.enabled==Hh){return;}
this.enabled=Hh;if(Hh){HEventManager.register(this,this.events);}
else{HEventManager.unregister(this);}
this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_DISABLED,!this.enabled);},setValue:function(H3){if(H3==undefined){return}
if(!this.valueObj){return}
if(H3!==this.value){this.value=H3;this.valueObj.set(this.value);if(this.refreshOnValueChange){this.refresh();}}},setValueObj:function(H1K){this.valueObj=H1K;this.setValue(H1K.value);},setValueRange:function(H3,H2n,H2o){this.minValue=H2n;this.maxValue=H2o;H3=(H3<H2n)?H2n:H3;H3=(H3>H2o)?H2o:H3;this.setValue(H3);this.refresh();},setEvents:function(H1U){if(!this.events){var H6d=HClass.extend({mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false});this.events=new H6d;}
if(H1U){this.events.extend(H1U);}
this.events.owner=this;HEventManager.focusOptions[this.elemId]=this.events;this.isDragged=false;},setMouseDown:function(Hh){this.events.mouseDown=Hh;this.setEvents();},setMouseUp:function(Hh){this.events.mouseUp=Hh;this.setEvents();},setMouseWheel:function(Hh){this.events.mouseWheel=Hh;this.setEvents();},setDraggable:function(Hh){this.events.draggable=Hh;this.setEvents();},setDroppable:function(Hh){this.events.droppable=Hh;this.setEvents();},setKeyDown:function(Hh){this.events.keyDown=Hh;this.setEvents();},setKeyUp:function(Hh){this.events.keyUp=Hh;this.setEvents();},focus:function(){},blur:function(){},gainedActiveStatus:function(H0A){},_gainedActiveStatus:function(H0A){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(H0A);},lostActiveStatus:function(HE){},_lostActiveStatus:function(HE){if(this.enabled){this.toggleCSSClass(elem_get(this.elemId),HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(HE);},mouseDown:function(H8,H9,HW){},mouseUp:function(H8,H9,HW){},mouseWheel:function(H0a){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(Hx){},keyUp:function(Hx){},H24:function(e){if(!Event.element){return;}
var Hw=Event.element(e);while(Hw&&Hw.owner===undefined){Hw=Hw.parentNode;}
if(!Hw){return;}
var H5=Hw.owner;HEventManager.focus(H5);Event.stop(e);},H3A:function(e){if(!Event.element){return;}
var Hw=Event.element(e);while(Hw&&Hw.owner===undefined){Hw=Hw.parentNode;}
if(!Hw){return;}
var H5=Hw.owner;HEventManager.blur(H5);Event.stop(e);},invalidatePositionCache:function(){this.base();HEventManager.invalidatePositionCache(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(H6,H3){this.id=H6;this.value=H3;this.type='[HDummyValue]';},set:function(H3){this.value=H3;},get:function(){return this.value;},bind:function(H2b){},unbind:function(H2b){}});HComponentDefaults=HClass.extend({label:"Untitled",events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HRectValue=HRect.extend({constructor:function(){this.type='[HRectValue]';var H6,H3;var Ha=arguments;if(Ha.length===0){throw"Invalid number of arguments. HRectValue works as HRect, but needs an id as the first argument.";}else if(Ha.length==1){H6=Ha[0];this.H1C();}else if(Ha.length==5){H6=Ha[0];this.H3o(Ha[1],Ha[2],Ha[3],Ha[4]);}
else if(Ha.length==3){H6=Ha[0];this.H1D(Ha[1],Ha[2]);}
else if(Ha.length==2){H6=Ha[0];if((Ha[1]instanceof HRect)||(args[1]instanceof HRectValue)){this.H2w(Ha[1]);}else if(Ha[1]instanceof Array){this.H5d(Ha[1]);}else{throw"Invalid argument. Expected Array or Rect.";}}
else{throw"Invalid number of arguments.";}
H3=[this.left,this.top,this.right,this.bottom];this.id=H6;this.value=H3;this.views=[];this.updateSecondaryValues();HValueManager.add(H6,this);},updateSecondaryValues:function(){this.base();if(this.H5e()){this.value[0]=this.left;this.value[1]=this.top;this.value[2]=this.right;this.value[3]=this.bottom;this.refresh();}},H5d:function(H2L){this.left=H2L[0];this.top=H2L[1];this.right=H2L[2];this.bottom=H2L[3];},H5e:function(){if((this.left!=this.value[0])||(this.top!=this.value[1])||(this.right!=this.value[2])||(this.bottom!=this.value[3])){HValueManager.changed(this);this.refresh();return true;}
return false;},set:function(){var Ha=arguments;if(Ha.length==1){if((Ha[0]instanceof HRect)||(Ha[0]instanceof HRectValue)){this.H2w(Ha[0]);}else if(Ha[0]instanceof Array){this.H5d(Ha[0]);}}else{this.base.apply(this,Ha);}
this.H5e();},get:function(){return this.value;},bind:function(Ho){if(this.views.indexOf(Ho.elemId)==-1){this.views.push(Ho);if(Ho.rect!==this){Ho.setRect(this);}}},unbind:function(Ho){for(var Hs=0;Hs<this.views.length;Hs++){var H3P=this.views[Hs];if(H3P===Ho){this.views.splice(Hs);return;}}},refresh:function(){for(var Hs=0;Hs<this.views.length;Hs++){var Ho=this.views[Hs];Ho.drawRect();}},toXML:function(HT){return'<rect id="'+this.id+'" order="'+HT+'"><left>'+this.left+'</left><top>'+this.top+'</top><right>'+this.right+'</right><bottom>'+this.bottom+'</bottom></rect>';}});