
HMenuItem=HControl.extend({packageName:"menus",componentName:"menuitem",constructor:function(H0,H4,H1){if(!H1){H1={};}
if(typeof H1!="object"){throw('MenuItemConstructorError: H1 must be an object');}
var _hasValueObj=true;if(!H1.valueObj){_hasValueObj=false;}
if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HMenuItem]';this.H5x="menuitemleftimage";this.H5y="menuitemrightimage";this.preserveTheme=true;this.marked=false;this.setMouseDown(true);this.setMouseUp(true);this.refreshOnValueChange=true;if(H4.type=="[HMenu]"||H4.type=="[HMenuBar]"||H4.type=="[HPopupMenu]"){if(!H1){H1={};}
H4.addItem(this,H1.index);}
if(!this.isinherited){this.draw();}},H5z:function(){if(this.value){this.toggleCSSClass(elem_get(this.H1u),this.cssOn,true);this.toggleCSSClass(elem_get(this.H1u),this.cssOff,false);}else{this.toggleCSSClass(elem_get(this.H1u),this.cssOn,false);this.toggleCSSClass(elem_get(this.H1u),this.cssOff,true);}},H5A:function(){if(this.leaf){this.toggleCSSClass(elem_get(this.H1v),this.cssRightOn,true);this.toggleCSSClass(elem_get(this.H1v),this.cssRightOff,false);}else{this.toggleCSSClass(elem_get(this.H1v),this.cssRightOn,false);this.toggleCSSClass(elem_get(this.H1v),this.cssRightOff,true);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){if(this.markupElemIds.label){elem_set(this.markupElemIds.label,this.label);}
if(!this.H1u){this.H1u=this.bindDomElement(this.H5x+this.elemId);}
if(this.H1u&&!this.leaf){this.H5z();}
if(!this.H1v){this.H1v=this.bindDomElement(this.H5y+this.elemId);}
if(this.H1v&&this.menu&&this.menu.type=="[HMenu]"){this.H5A();}}},H43:function(H5B){this.leaf=H5B;},stringWidth:function(H0T,HX){return this.base(H0T,HX)+
prop_get_extra_width(this.markupElemIds.label);},setMarked:function(H3){this.marked=H3;this.setValue(H3);},lostActiveStatus:function(HE){if(this.menu.hideMenu){this.menu.hideMenu();}},cssOn:"leftimageOn",cssOff:"leftimage",cssRightOn:"rightimageOn",cssRightOff:"rightimage"}).extend(HValueMatrixComponentExtension).extend({mouseDown:function(H8,H9,H03){if(this.menu.radioMode){this.base(H8,H9,H03);}},mouseUp:function(H8,H9,H03){if(this.action){this.action();}
if(this.menu.radioMode){this.base(H8,H9,H03);}
if(this.menu.mouseUpOnMenuItem){this.menu.mouseUpOnMenuItem(this);}}});HMenu=HControl.extend({packageName:"menus",componentName:"menu",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HMenu]';this.preserveTheme=true;this.menuItems=[];this.H0q={itemHeight:21,menuOffset:-5};this.totalHeight=0;if(!this.isinherited){this.draw();}},draw:function(){this.base();this.H5C();this.drawRect();},hide:function(){var i,H7,l=this.menuItems.length;for(i=0;i<l;i++){H7=this.menuItems[i];if(H7!=this&&H7.leaf){H7.leaf.hide();}}
this.base();},H31:function(){var i,H7,l=this.menu.menuItems.length;var Hb;for(i=0;i<l;i++){H7=this.menu.menuItems[i];if(H7!=this&&H7.leaf){H7.leaf.hide();}else if(H7==this){Hb=i;}}
if(this.leaf){this.leaf.rect.left=this.menu.rect.left+this.menu.rect.width+
this.menu.H0q.menuOffset;this.leaf.rect.top=this.menu.rect.top+
(Hb*this.menu.H0q.itemHeight);this.leaf.setStyle("left",this.leaf.rect.left+"px");this.leaf.setStyle("top",this.leaf.rect.top+"px");this.leaf.bringToFront();this.leaf.show();}},addItem:function(H7,Hb){if(H7.type=="[HMenu]"){var H06=H7;H06.hide();H7=new HMenuItem(new HRect(0,0,0,0),this,H7.options);H06.superitem=H7;H7.H43(H06);}else{H7.menu=this;if(Hb!==undefined){this.menuItems.splice(Hb,0,H7);}else{this.menuItems.push(H7);}}
H7.focus=this.H31;if(this.valueMatrix){this.H44(H7);}
this.draw();},hideMenu:function(){var H06=this;while(H06.superitem){if(H06.superitem.menu.type=="[HMenuBar]"){H06.superitem.menu.H1w=false;break;}
H06=H06.superitem.menu;}
H06.hide();},removeItem:function(Hg){if(typeof Hg=="number"){var H7=this.menuItems[Hg];if(H7){return(this.removeItem(H7))?H7:null;}else{return null;}}else if(Hg.type=="[HMenuItem]"){var Hb=this.menuItems.indexOf(Hg);if(Hb>=0){var H7=this.menuItems[Hb];H7.focus=undefined;H7.menu=undefined;this.menuItems.splice(Hb,1);this.draw();return true;}else{return false;}}else if(Hg.type=="[HMenu]"){if(Hg.superitem){return Hg.superitem.menu.removeItem(Hg.superitem);}else{return false;}}},H5C:function(){this.totalHeight=0;var i,H7,l=this.menuItems.length;for(i=0;i<l;i++){var H7=this.menuItems[i];H7.rect.set(0,this.totalHeight,100,this.totalHeight+this.H0q.itemHeight);this.totalHeight=this.totalHeight+this.H0q.itemHeight;H7.draw();}
var H2h=0;for(i=0;i<l;i++){var H7=this.menuItems[i];var Hf=H7.stringWidth(H7.label)
if(Hf>H2h){H2h=Hf;}}
for(i=0;i<l;i++){var H7=this.menuItems[i];H7.rect.setWidth(H2h);H7.drawRect();}
this.rect.set(this.rect.left,this.rect.top,this.rect.left+H2h,this.rect.top+this.totalHeight);},setRadioMode:function(H45,H1b){this.radioMode=H45;if(H45){this.valueMatrix=new HValueMatrix();H1b=(H1b||new HValue('menuDummy'+this.elemId,-1));H1b.bind(this.valueMatrix);H1b.bind(this);var i,H7,l=this.menuItems.length;for(i=0;i<l;i++){var H7=this.menuItems[i];this.H44(H7);}}},H44:function(H7){if(H7.type=="[HMenuItem]"&&!H7.leaf){H7.setValueMatrix(this.valueMatrix);}},indexOfItem:function(H7){return this.menuItems.indexOf(H7);},mouseUpOnMenuItem:function(H7){this.hideMenu();}});HMenuBar=HControl.extend({packageName:"menus",componentName:"menubar",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HMenuBar]';this.preserveTheme=true;this.menuItems=[];this.H0q={itemWidth:100,itemHeight:21};this.setMouseDown(true);this.totalWidth=0;this.H1w=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.arrangeMenuItems();this.drawRect();},hide:function(){var i,H7,l=this.menuItems.length;for(i=0;i<l;i++){H7=this.menuItems[i];if(H7!=this&&H7.leaf){H7.leaf.hide();}}
this.base();},H31:function(){if(this.menu.H1w==false){return;}
var i,H7,l=this.menu.menuItems.length;var Hb;for(i=0;i<l;i++){H7=this.menu.menuItems[i];if(H7!=this&&H7.leaf){H7.leaf.hide();}else if(H7==this){Hb=i;}}
if(this.leaf){var Hf=0;for(i=0;i<Hb;i++){Hf+=this.menu.menuItems[i].rect.width;}
this.leaf.rect.left=this.menu.pageX()+Hf;this.leaf.rect.top=this.menu.pageY()+
this.menu.H0q.itemHeight;this.leaf.setStyle("left",this.leaf.rect.left+"px");this.leaf.setStyle("top",this.leaf.rect.top+"px");this.leaf.bringToFront();this.leaf.show();}},H5E:function(){if(this.leaf){if(this.menu.H1w==false){var Hf=0;for(i=0;i<this.menu.menuItems.length;i++){if(this.menu.menuItems[i]==this){break;}
Hf+=this.menu.menuItems[i].rect.width;}
this.leaf.rect.left=this.menu.pageX()+Hf;this.leaf.rect.top=this.menu.pageY()+
this.menu.H0q.itemHeight;this.leaf.setStyle("left",this.leaf.rect.left+"px");this.leaf.setStyle("top",this.leaf.rect.top+"px");this.leaf.bringToFront();this.leaf.show();}else{this.leaf.hide();}}
if(this.menu.H1w==false){this.menu.H1w=true;}else{this.menu.H1w=false;}},addItem:function(H7,Hb){if(H7.type=="[HMenu]"){var H06=H7;H06.hide();H7=new HMenuItem(new HRect(0,0,100,48),this,H7.options);H06.superitem=H7;H7.H43(H06);}else{H7.menu=this;if(Hb!==undefined){this.menuItems.splice(Hb,0,H7);}else{this.menuItems.push(H7);}}
H7.focus=this.H31;H7.setMouseDown(true);H7.mouseDown=this.H5E;this.draw();},removeItem:function(Hg){if(typeof Hg=="number"){var H7=this.menuItems[Hg];if(H7){return(this.removeItem(H7))?H7:null;}else{return null;}}else if(Hg.type=="[HMenuItem]"){var Hb=this.menuItems.indexOf(Hg);if(Hb>=0){var H7=this.menuItems[Hb];H7.die();H7.focus=undefined;H7.menu=undefined;this.menuItems.splice(Hb,1);this.draw();return true;}else{return false;}}else if(Hg.type=="[HMenu]"){if(Hg.superitem){return Hg.superitem.menu.removeItem(Hg.superitem);}else{return false;}}},arrangeMenuItems:function(){this.totalWidth=0;var i,l=this.menuItems.length;for(i=0;i<l;i++){var _menuItem=this.menuItems[i];var _menuItemRectLeft=this.totalWidth;var _menuItemRectRight=this.totalWidth+this.H0q.itemWidth;var _menuItemRectBottom=this.H0q.itemHeight;_menuItem.setRect(new HRect(_menuItemRectLeft,0,_menuItemRectRight,_menuItemRectBottom));this.totalWidth=this.totalWidth+this.H0q.itemWidth;_menuItem.draw();}
var _stringWidth=0,_itemWidth=0;for(i=0;i<l;i++){var _menuItem=this.menuItems[i];_stringWidth=_menuItem.stringWidth(_menuItem.label);_menuItem.rect.setLeft(_itemWidth);_itemWidth+=_stringWidth;_menuItem.rect.setWidth(_stringWidth);_menuItem.drawRect();}
var HU=this.rect.left+_itemWidth;this.rect.setRight(HU);var HY=this.rect.top+this.H0q.itemHeight;this.rect.setBottom(HY);this.drawRect();}});HPopupButton=HButton.extend({packageName:"menus",componentName:"popupbutton",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HPopupButton]';if(H1.popupMenu){this.popupmenu=H1.popupMenu;this.popupmenu.popupbutton=this;this.popupmenu.hide();this.popupmenu.setOwner(this);}
this.setMouseDown(true);if(!this.isinherited){this.draw();}},mouseDown:function(x,y,HW){if(this.popupmenu.isHidden){this.popupmenu.rect.left=this.pageX();this.popupmenu.rect.top=this.pageY()+this.rect.height;this.popupmenu.setStyle("left",this.popupmenu.rect.left+"px");this.popupmenu.setStyle("top",this.popupmenu.rect.top+"px");this.popupmenu.bringToFront();this.popupmenu.show();}else{this.popupmenu.hide();}},lostActiveStatus:function(HE){if(!HE||this.popupmenu.indexOfItem(HE)==-1){this.popupmenu.hide();}},selectedIndexChanged:function(){}});HPopUpButton=HPopupButton;HPopupMenu=HMenu.extend({packageName:"menus",componentName:"popupmenu",constructor:function(H0,H4,H1){if(!H1){H1={};}
if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HPopupMenu]';this.preserveTheme=true;this.selectedIndex=-1;this.selectedItem=null;this.owner=null;if(!this.isinherited){this.draw();}
if(H1.choices instanceof Array){for(var i=0;i<H1.choices.length;i++){var H7=H1.choices[i];if(null===H7.enabled||undefined===H7.enabled){H7.enabled=true;}
var _newMenuItem=new HMenuItem(new HRect(0,0,0,18),this,{label:H7.label,value:H7.value,enabled:H7.enabled});}}},H5D:function(H32){var H2i;if(!H32){H2i="";}
else{H2i=H32.label;}
if(this.popupbutton.type=="[HPopupButton]"){this.popupbutton.setLabel(H2i);}else if(this.popupbutton.type=="[HTextControl]"){this.popupbutton.setValue(H2i);}
if(!this.radioMode){this.setValue(H32.value);}},setOwner:function(H0v){this.owner=H0v;},selectItem:function(H7){this.selectedItem=H7;var Hb=this.menuItems.indexOf(H7);this.selectItemAtIndex(Hb);},selectItemAtIndex:function(Hb){if(Hb!=this.selectedIndex){this.selectedIndex=Hb;this.H5D(this.menuItems[Hb]);this.selectedIndexChanged();}},selectedIndexChanged:function(){if(this.owner&&this.owner.selectedIndexChanged){this.owner.selectedIndexChanged();}},mouseUpOnMenuItem:function(H7){this.selectItem(H7);this.hide();},setValue:function(H3){this.base(H3);if(this.owner){this.owner.setValue(H3);}}});HPopUpMenu=HPopupMenu;HComboBox=HControl.extend({packageName:"menus",componentName:"combobox",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HComboBox]';this.preserveTheme=true;this.H0D=false;this.setMouseDown(true);this.popupMenu=new HPopupMenu(new HRect(this.rect.left,this.rect.top+this.rect.height,220,200),this.app);this.popupMenu.setOwner(this);if(!this.isinherited){this.draw();}},die:function(){if(this.popupMenu){this.popupMenu.die();}
this.base();},draw:function(){if(!this.drawn){this.drawRect();if(!this.H0D){this.textControl=new HTextControl(this.H46(),this,{value:"",enabled:this.enabled});this.comboBoxButton=new HComboBoxButton(this.H47(),this,{label:"",enabled:this.enabled,popupMenu:this.popupMenu,textControl:this.textControl});this.H0D=true;}
this.drawn=true;}else{this.drawRect();}},H46:function(){var HU=this.rect.width-this.rect.height;return new HRect(0,0,HU,this.rect.height);},H47:function(){var Hy=this.rect.width-this.rect.height;return new HRect(Hy,0,this.rect.width,this.rect.height);},drawRect:function(){this.base();if(this.H0D){this.textControl.setRect(this.H46());this.comboBoxButton.setRect(this.H47());}},addItem:function(HB,Hb){new HMenuItem(new HRect(0,0,100,18),this.popupMenu,{label:HB,index:Hb});},removeItem:function(Hb){this.popupMenu.removeItem(Hb);},selectItem:function(H7){this.popupMenu.selectItem(H7);},selectItemAtIndex:function(Hb){this.popupMenu.selectItemAtIndex(Hb);},selectedIndex:function(){return this.popupMenu.selectedIndex;},selectedItem:function(){return this.popupMenu.selectedItem;},selectedIndexChanged:function(){}});HComboBoxButton=HButton.extend({packageName:"menus",componentName:"comboboxbutton",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HComboBoxButton]';this.H1a="comboboxbuttonlabel";if(H1.popupMenu){this.popupmenu=H1.popupMenu;this.popupmenu.popupbutton=H1.textControl;this.popupmenu.textcontrol=this;this.popupmenu.hide();}
this.setMouseDown(true);if(!this.isinherited){this.draw();}},mouseDown:function(x,y,HW){if(this.popupmenu.isHidden){this.popupmenu.rect.left=this.parent.pageX();this.popupmenu.rect.top=this.parent.pageY()+
this.parent.rect.height;this.popupmenu.rect.right=this.popupmenu.rect.left+
this.popupmenu.rect.width;this.popupmenu.rect.bottom=this.popupmenu.rect.top+
this.popupmenu.rect.height;this.popupmenu.setStyle("left",this.popupmenu.rect.left+"px");this.popupmenu.setStyle("top",this.popupmenu.rect.top+"px");this.popupmenu.bringToFront();this.popupmenu.show();}else{this.popupmenu.hide();}},lostActiveStatus:function(HE){if(!HE||this.popupmenu.indexOfItem(HE)==-1){this.popupmenu.hide();}}});