
HLocalTableValue=HValue.extend({constructor:function(H6,H3){this.initTable(H6,H3);this.value=H3.value;},initTable:function(H6,H3){},set:function(H3){},updateBuffer:function(_startingRow,_endingRow){},setCell:function(_table,H3,_row,Hq){if(!this.value[_row]){return;}
this.value[_row][Hq]=H3;},getCell:function(_table,_row,Hq){if(!this.value[_row]){return"";}
return this.value[_row][Hq];},numberOfRows:function(){return 100;},toXML:function(){}});HTableValue=HValue.extend({constructor:function(H6,H3){this.initTable(H6,H3);},initTable:function(H6,H3){if(typeof H3!="object"){throw"HTableValue error: value not an object";}
if(typeof H3.value!="object"){throw"HTableValue error: object.value not an array";}
if(typeof H3.length!="number"){throw"HTableValue error: object.length not a number";}
if(typeof H3.startrow!="number"){throw"HTableValue error: object.startrow not a number";}
if(typeof H3.endrow!="number"){throw"HTableValue error: object.endrow not a number";}
if(typeof H3.columns!="object"){throw"HTableValue error: object.columns not an array";}
this.value=H3.value;this.length=H3.length;this.columns=H3.columns;this.startrow=H3.startrow;this.endrow=H3.endrow;this.startrow1=0;this.endrow1=0;this.id=H6;this.type='[HTableValue]';this.views=[];this.startdatarow=this.startrow;this.enddatarow=this.endrow;this.datalength=this.endrow-(this.startrow-1);this.gettingData=false;this.gettingData1=false;this.gettingDataInterrupted=false;this.gettingDataInterrupted1=false;this.index1=0;this.index2=0;this.valueRequested=undefined;HValueManager.add(H6,this);},set:function(H3){if(this.valueRequested==1){this.value1=H3;this.gettingData1=false;}else if(this.valueRequested==0){this.value=H3;this.gettingData=false;}
if(this.gettingDataInterrupted){this.tableControl.reloadData();this.gettingDataInterrupted=false;}
if(this.gettingDataInterrupted1){this.tableControl.reloadData();this.gettingDataInterrupted1=false;}
if(this.reloading==true){this.tableControl.reloadData();this.reloading=false;}},updateBuffer:function(_startingRow,_endingRow){var HX=this.datalength;var _whichValue=undefined;if(this.startdatarow-1<=_startingRow&&_endingRow<=this.enddatarow-1){var _rowTopLimit;var _rowBottomLimit;if(this.startrow-1<=_startingRow&&_endingRow<=this.endrow-1){_rowTopLimit=this.startrow-1+parseInt(HX/4,10);_rowBottomLimit=this.endrow-1-parseInt(HX/4,10);_whichValue=0;}else if((this.startrow1&&this.endrow1)&&this.startrow1-1<=_startingRow&&_endingRow<=this.endrow1-1){_rowTopLimit=this.startrow1-1+parseInt(HX/4,10);_rowBottomLimit=this.endrow1-1-parseInt(HX/4,10);_whichValue=1;}
if(_endingRow>_rowBottomLimit){if(_whichValue==0&&this.startrow1<this.startrow){var _newRowStart=this.endrow+1;var _newRowEnd=this.endrow+HX;if(_newRowEnd>this.length){_newRowEnd=this.length;}
this.startrow1=_newRowStart;this.endrow1=_newRowEnd;this.startrow2=this.startrow1;this.endrow2=this.endrow1;window.status="going down 0 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.startdatarow=this.startrow;this.enddatarow=this.endrow1;this.valueRequested=1;this.gettingData1=true;HValueManager.changed(this);}
if(_whichValue==1&&this.startrow<this.startrow1){var _newRowStart=this.endrow1+1;var _newRowEnd=this.endrow1+HX;if(_newRowEnd>this.length){_newRowEnd=this.length;}
this.startrow=_newRowStart;this.endrow=_newRowEnd;this.startrow2=this.startrow;this.endrow2=this.endrow;window.status="going down 1 "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" ";this.startdatarow=this.startrow1;this.enddatarow=this.endrow;this.valueRequested=0;this.gettingData=true;HValueManager.changed(this);}}
if(_startingRow<_rowTopLimit){if(this.startrow-1==0&&_whichValue==0){}else{if(_whichValue==0&&this.startrow<this.startrow1){var _newRowStart=this.startrow-HX;var _newRowEnd=this.startrow-1;if(_newRowStart<1){_newRowStart=1;}
this.startrow1=_newRowStart;this.endrow1=_newRowEnd;this.startrow2=this.startrow1;this.endrow2=this.endrow1;this.startdatarow=this.startrow1;window.status="going up 0 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.enddatarow=this.endrow;this.valueRequested=1;this.gettingData1=true;HValueManager.changed(this);}
if(_whichValue==1&&this.startrow1<this.startrow){var _newRowStart=this.startrow1-HX;var _newRowEnd=this.startrow1-1;if(_newRowStart<1){_newRowStart=1;}
this.startrow=_newRowStart;this.endrow=_newRowEnd;this.startrow2=this.startrow;this.endrow2=this.endrow;this.startdatarow=this.startrow;this.enddatarow=this.endrow1;window.status="going up 1 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.valueRequested=0;this.gettingData=true;HValueManager.changed(this);}}}}else{var _viewLength=_endingRow-_startingRow;var _newRowStart=_startingRow-parseInt(HX/2,10)+parseInt(_viewLength/2,10);if(_newRowStart<1){_newRowStart=1;}
var _newRowEnd=_newRowStart+HX-1;if(_newRowEnd>this.length){_newRowEnd=this.length;}
this.startrow=_newRowStart;this.endrow=_newRowEnd;this.startrow1=undefined;this.endrow1=undefined;this.startrow2=this.startrow;this.endrow2=this.endrow;this.startdatarow=_newRowStart;this.enddatarow=_newRowEnd;this.valueRequested=0;this.gettingData=true;this.reloading=true;HValueManager.changed(this);}},setCell:function(_table,H3,_row,Hq){this.value[_row][Hq]=H3;},getCell:function(_table,_row,Hq){if(this.startrow-1<=_row&&_row<=this.endrow-1){if(this.gettingData){this.gettingDataInterrupted=true;}else{if(this.value[_row-(this.startrow-1)]){return this.value[_row-(this.startrow-1)][Hq];}}}else if(this.startrow1-1<=_row&&_row<=this.endrow1-1){if(this.gettingData1){this.gettingDataInterrupted1=true;}else{if(this.value1&&this.value1[_row-(this.startrow1-1)]){return this.value1[_row-(this.startrow1-1)][Hq];}}}
return"-";},numberOfRows:function(){return this.length;},toXML:function(HT){var H0t=this.id;var H3X="";for(var Hq=0;Hq<this.columns.length;Hq++){H3X+='<getrows column="'+this.columns[Hq]+'" startrow="'+this.startrow2+'" endrow="'+this.endrow2+'" />';}
return'<tablevalue length="'+this.columns.length+'" id="'+H0t+'" order="'+HT+'">'+H3X+'</tablevalue>';}});HTableColumn=HControl.extend({packageName:"table",componentName:"tablecolumn",constructor:function(H0,H4,H1){H1=new(Base.extend({dataView:"",headerView:""}).extend(H1));if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HTableColumn]';this.width=H0.width;this.dataView=this.options.dataView;this.headerView=this.options.headerView;this.index=this.options.index;this.preserveTheme=true;if(!this.isinherited){this.draw();}}});HTableHeaderView=HControl.extend({packageName:"table",componentName:"tableheaderview",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HTableHeaderView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){this.base();}});HTableHeaderColumn=HControl.extend({packageName:"table",componentName:"tableheadercolumn",constructor:function(H0,H4,H1){this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;this.type='[HTableHeaderColumn]';this.H1a="tableheadercolumnlabel";this.H5u="tableheaderselected";this.H5v="tableheaderorder";this.preserveTheme=true;this.setMouseUp(true);this.setDraggable(true);this.options=this.parent.parent.tableViewDefaults;this.H2T();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(!this.HG){this.HG=elem_bind(this.H1a+this.elemId);this.H2U=elem_bind(this.H5u+this.elemId);this.H1t=elem_bind(this.H5v+this.elemId);}
if(this.HG){elem_set(this.HG,this.label);}},H5w:function(){H05.direction=!H05.direction;this.toggleCSSClass(elem_get(this.H1t),'order-dn',!H05.direction);this.toggleCSSClass(elem_get(this.H1t),'order-up',H05.direction);for(var H2g=0;H2g<this.parent.parent.tableHeaderColumns.length;H2g++){var H2V=this.parent.parent.tableHeaderColumns[H2g].H2U;if(H2V&&(H2V!=this.H6K)){prop_set(H2V,'visibility','hidden');}
var H2W=this.parent.parent.tableHeaderColumns[H2g].H1t;if(H2W&&(H2W!=this.H1t)){prop_set(H2W,'visibility','hidden');}}
if(this.H2U){prop_set(this.H2U,'visibility','inherit');}
if(this.H1t){prop_set(this.H1t,'visibility','inherit');}
var Hb=this.parent.parent.tableHeaderColumns.indexOf(this);H05.column=Hb;this.parent.parent.data.value.sort(H05);this.parent.parent.reloadData();},startDrag:function(H8,H9){this.base(H8,H9);this.H2T();H8-=this.parent.pageX();H9-=this.parent.pageY();this.H19=this.parent.parent.tableHeaderColumns.indexOf(this);this.H30=false;this.H0S=new HPoint(H8,H9);this.H1R=new HPoint(H8,H9);this.H1O=new HRect(this.rect);this.H2T();var H2X=this.H0S.subtract(this.H1O.leftTop);if(this.H0j.resizeWRect.contains(H2X)){this.HK=H8-this.rect.left;this.H0j.resizeW=true;}else if(this.H0j.resizeERect.contains(H2X)){this.HK=H8-this.rect.right;this.H0j.resizeE=true;}else if(this.H0j.dragColumnRect.contains(H2X)){this.HK=this.H0S.subtract(this.H1O.leftTop);this.H0j.dragColumn=true;}
this.bringToFront();this.H42=true;this.doDrag(H8,H9);this.H42=false;},doDrag:function(H8,H9){if(this.H42==false){H8-=this.parent.pageX();H9-=this.parent.pageY();}
var H0E=this.parent.parent;var Ht;var H0p=new HPoint(H8,H9);var Hb=this.parent.parent.tableHeaderColumns.indexOf(this);var Hq=this.parent.parent.tableColumns[Hb];if(!this.H1R.equals(H0p)){if(this.H0j.resizeW==true){if(Hb==0){return;}
Ht=H8-this.HK;this.rect.left=Ht;this.rect.updateSecondaryValues();this.drawRect();Hq.rect.left=Ht+this.parent.parent.scrollLeft();Hq.rect.updateSecondaryValues();Hq.drawRect();this.parent.parent._columnOrigins[Hb]=Ht+this.parent.parent.scrollLeft();H0E._tableColumns[Hb].width=this.rect.width;var H1P=this.parent.parent.tableColumns[(Hb-1)];if(H1P){H1P.rect.right=Ht+this.parent.parent.scrollLeft();H1P.rect.updateSecondaryValues();H1P.drawRect();this.parent.parent._tableColumns[Hb-1].width=H1P.rect.width;H2Y=this.parent.parent.tableHeaderColumns[Hb-1];H2Y.rect.right=Ht;H2Y.rect.updateSecondaryValues();H2Y.drawRect();}}else if(this.H0j.resizeE==true){var l=this.parent.parent.tableColumns.length;if(Hb==l-1){return;}
Ht=H8-this.HK;this.rect.right=Ht;this.rect.updateSecondaryValues();this.drawRect();Hq.rect.right=Ht+this.parent.parent.scrollLeft();Hq.rect.updateSecondaryValues();Hq.drawRect();this.parent.parent._columnOrigins[Hb+1]=Ht+this.parent.parent.scrollLeft();this.parent.parent._tableColumns[Hb].width=this.rect.width;var H1Q=this.parent.parent.tableColumns[(Hb+1)];if(H1Q){H1Q.rect.left=Ht+this.parent.parent.scrollLeft();H1Q.rect.updateSecondaryValues();H1Q.drawRect();this.parent.parent._tableColumns[Hb+1].width=H1Q.rect.width;H2Z=this.parent.parent.tableHeaderColumns[Hb+1];H2Z.rect.left=Ht;H2Z.rect.updateSecondaryValues();H2Z.drawRect();}}else if(this.H0j.dragColumn==true){Ht=H0p.subtract(this.HK);this.setStyle('opacity',0.4);this.setStyle('left',Ht.x+"px");Hq.setStyle('opacity',0.4);Hq.setStyle('left',Ht.x+this.parent.parent.scrollLeft()+"px");}
this.H30=true;if(this.H0j.dragColumn==false){}
this.H1R=H0p;}},endDrag:function(H8,H9){this.base(H8,H9);this.doDrag(H8,H9);H8-=this.parent.pageX();H9-=this.parent.pageY();var H0E=this.parent.parent;this.setStyle('opacity',1.0);H0E.tableColumns[this.H19].setStyle('opacity',1.0);var Hh=false;var i,l=H0E.tableHeaderColumns.length;for(i=0;i<l;i++){if(H0E.tableHeaderColumns[i].rect.left<=H8&&H8<=H0E.tableHeaderColumns[i].rect.right&&H0E.tableHeaderColumns[i]!=this){if(this.H0j.dragColumn==true){H0E.moveColumn(this.H19,i);Hh=true;}}}
if(Hh==false&&this.H0j.dragColumn==true){this.setStyle('left',this.H1O.left+"px");H0E.tableColumns[this.H19].setStyle('left',this.H1O.left+"px");this.H5w();}},drawRect:function(){this.H30=false;this.base();},H2T:function(){this.H0j={dragColumn:false,resizeW:false,resizeE:false,dragColumnRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,0,this.options.resizeW,this.rect.height),resizeERect:new HRect(this.rect.width-this.options.resizeE,0,this.rect.width,this.rect.height)};}});H05=function(a,b){if(a[H05.column]<b[H05.column]){return(H05.direction)?-1:1;}
if(a[H05.column]>b[H05.column]){return(H05.direction)?1:-1;}
return 0;}
H05.direction=true;H05.column=0;_HTableColumn=function(Hb,Hf,H0T,H0R,H2f){this.index=Hb;this.width=Hf;this.string=H0T;this.dataView=H0R;this.headerView=H2f;this.headerCreated=false;this.created=false;}
HTableControl=HControl.extend({packageName:"table",componentName:"itablecontrol",constructor:function(H0,H4,H1){H1=new(Base.extend({rowHeight:21,headerViewHeight:21,bufferLength:3,resizeW:5,resizeE:5}).extend(H1));if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.tableViewDefaults=H1;this.type='[HTableControl]';this.preserveTheme=true;this.tableColumns=[];this._columnOrigins=[];this.tableHeaderColumns=[];this._tableColumns=[];this.H15=[];this._tableRows=[];this.numberOfRows=0;this.H16=0;this._dataRowBufferEndIndex=0;this.H17=0;this.H1M=0;this.H0b=0;this.headerView=new HTableHeaderView(new HRect(0,0,this.rect.width,this.options.headerViewHeight),this);this.tableView=new HView(new HRect(0,this.options.headerViewHeight,this.rect.width,this.rect.height),this);this.tableView.setStyle("overflow","auto");this.columnsView=new HView(new HRect(0,0,this.rect.width,this.rect.height-this.options.headerViewHeight),this.tableView);var _cornerRect=new HRect(this.rect.width-18,0,this.rect.width,this.options.headerViewHeight);this.cornerView=new HTableCornerView(_cornerRect,this);this._scrollRect=new HRect(this.tableView.rect);this._scrollRect.offsetTo(0,0);if(!this.isinherited){this.draw();}},onIdle:function(){this.H5r();this.base();},H2e:function(){if(this.numberOfRows==0||this._tableColumns.length==0){return;}
var _startingRow=this._rowAtPoint(new HPoint(0,this._scrollRect.top));var _endingRow=this._rowAtPoint(new HPoint(0,this._scrollRect.bottom));var _startingColumn,_endingColumn;var _xPos=this._scrollRect.left;var i=0;while(i<this._tableColumns.length&&_xPos>this._columnOrigins[i]){i++;}
_startingColumn=i-1;if(_startingColumn==-1){_startingColumn=0;}
var _xPos=this._scrollRect.right;while(i<this._tableColumns.length&&_xPos>this._columnOrigins[i]){i++;}
_endingColumn=i-1;if(_endingColumn==-1){_endingColumn=this._tableColumns.length-1;}
var H3Y=false;var _partUpRowsUpdated=false;var H3Z=false;for(var i=_startingColumn;i<=_endingColumn;i++){if(this._tableColumns[i].created==false){var _columnRect=new HRect(this._columnOrigins[i],0,this._columnOrigins[i]+this._tableColumns[i].width,this.columnsView.rect.height);this.tableColumns[i]=new HTableColumn(_columnRect,this.columnsView,{label:this._tableColumns[i].string,dataView:this._tableColumns[i].dataView,headerView:this._tableColumns[i].headerView});this._tableColumns[i].created=true;}
if(this._tableColumns[i].headerCreated==false){var _headerColumnRect=new HRect(this._columnOrigins[i]-this._scrollRect.left,0,this._columnOrigins[i]-this._scrollRect.left+this._tableColumns[i].width,this.options.headerViewHeight);this.tableHeaderColumns[i]=new HTableHeaderColumn(_headerColumnRect,this.headerView,{label:this._tableColumns[i].string});this.tableHeaderColumns[i].draw();this._tableColumns[i].headerCreated=true;}
var _tableColumn=this.tableColumns[i];var _tableHeaderColumn=this.tableHeaderColumns[i];if(this.H15[i]==false){this._initializeRows(i,_startingRow,_endingRow);this.H15[i]=true;}}
for(var i=0;i<this._tableColumns.length;i++){if(this._tableColumns[i].created==true){var _tableColumn=this.tableColumns[i];var _tableHeaderColumn=this.tableHeaderColumns[i];_tableHeaderColumn.rect.offsetTo(this._columnOrigins[i]-this._scrollRect.left,0);_tableHeaderColumn.drawRect();_tableColumn.rect.set(this._columnOrigins[i],0,this._columnOrigins[i]+_tableColumn.width,this.columnsView.rect.height);_tableColumn.drawRect();if(!this.H41&&this.H16<=_startingRow&&_startingRow<this.H16+this.tableViewDefaults.bufferLength*this.H0b){var _dataBuffer=new HDataBuffer(_startingRow,_endingRow,this.H16,this._dataRowBufferEndIndex,this.H0b);var H5s=_dataBuffer.lowerLimit();var H5t=_dataBuffer.upperLimit();if(_startingRow>H5t){H3Y=true;var H0u=this.H17;var _yPos=_dataBuffer.getNewBottomRow()*this.options.rowHeight;var _newRowStart=_dataBuffer.getNewBottomRow();var _newRowEnd=_dataBuffer.getNewBottomRowEnd();this.H2S(H0u,_newRowStart,_newRowEnd,i,_yPos,_tableColumn);}else if(_startingRow<=H5s){_partUpRowsUpdated=true;var H0u=this.H1M;var _yPos=_dataBuffer.getNewTopRow()*this.options.rowHeight;var _newRowStart=_dataBuffer.getNewTopRow();var _newRowEnd=_dataBuffer.getNewTopRowEnd();this.H2S(H0u,_newRowStart,_newRowEnd,i,_yPos,_tableColumn);}}else{H3Z=true;var _dataBuffer=new HDataBuffer(_startingRow,_endingRow,0,0,this.H0b);var _startingBufferRow=_dataBuffer.startingRow();var _endingBufferRow=_dataBuffer.endingRow();var H0u=0;var _yPos=_startingBufferRow*this.options.rowHeight;this.H2S(H0u,_startingBufferRow,_startingBufferRow+this.H0b*3,i,_yPos,_tableColumn);}}}
if(H3Y==true){var _dataBuffer=new HDataBuffer(_startingRow,_endingRow,0,0,this.H0b);var _indexes=_dataBuffer.getNewDownBufferIndexes(this.H17);this.H17=_indexes[0];this.H1M=_indexes[1];this.H16+=this.H0b;}
if(_partUpRowsUpdated==true){var _dataBuffer=new HDataBuffer(_startingRow,_endingRow,0,0,this.H0b);var _indexes=_dataBuffer.getNewUpBufferIndexes(this.H17);this.H17=_indexes[0];this.H1M=_indexes[1];this.H16-=this.H0b;}
if(H3Z==true){var _dataBuffer=new HDataBuffer(_startingRow,_endingRow,0,0,this.H0b);this.H17=0;this.H1M=_dataBuffer.endBufferStartRow();this.H16=_startingRow-this.H0b;}
this.data.updateBuffer(_startingRow,_endingRow);},H2S:function(H0u,_startRealRow,_endRealRow,H0d,H3W,H7){var H3;for(var _rowIndex=_startRealRow;_rowIndex<_endRealRow;_rowIndex++){H3=this.data.getCell(this,_rowIndex,this._tableColumns[H0d].index);H3=(H3)?H3:"1";this._tableRows[H0d][H0u].setValue(H3);this._tableRows[H0d][H0u].rect.offsetTo(0,H3W);this._tableRows[H0d][H0u].drawRect();H3W+=this.options.rowHeight;H0u++;}},_initializeRows:function(H0d,_startingRow,_endingRow){var _tableColumn=this.tableColumns[H0d];if(!this.H0b){this.H0b=_endingRow-_startingRow;}
var _dataBuffer=new HDataBuffer(_startingRow,_endingRow,0,0,this.H0b);var _startingBufferRow=_dataBuffer.startingRow();var _endingBufferRow=_dataBuffer.endingRow();this.H16=_startingBufferRow;this._dataRowBufferEndIndex=_endingBufferRow;var _yPos=_startingBufferRow*this.options.rowHeight;this.H1M=_dataBuffer.endBufferStartRow();this._tableRows[H0d]=new Array();var H0R=_tableColumn.dataView
if(typeof H0R=="string"){H0R=ITextControl}
var H40,H1A,H3;for(var _rowIndex=_startingBufferRow;_rowIndex<_endingBufferRow;_rowIndex++){H3=this.data.getCell(this,_rowIndex,this._tableColumns[H0d].index);H3=(H3)?H3:"1";H1A=new HRect(0,_yPos,_tableColumn.rect.width,_yPos+this.options.rowHeight);H40=new H0R(H1A,_tableColumn,{value:H3});this._tableRows[H0d].push(H40);_yPos+=this.options.rowHeight;}},_calculateDimensions:function(){var _tableWidth=0,_tableHeight;if(this._tableColumns.length>0){var Hf;this._columnOrigins[0]=0;width=this._tableColumns[0].width;_tableWidth+=width;for(var i=1;i<this._tableColumns.length;i++){this._columnOrigins[i]=this._columnOrigins[i-1]+width;width=this._tableColumns[i].width;_tableWidth+=width;}}
_tableHeight=this.numberOfRows*this.options.rowHeight;this.columnsView.rect.setSize(_tableWidth,_tableHeight);this.columnsView.drawRect();if(this.headerView){this.headerView.rect.setWidth(_tableWidth);this.headerView.drawRect();}},_rowAtPoint:function(Hi){return parseInt(Hi.y/this.options.rowHeight,10);},rowAtPoint:function(Hi){var H9=Hi.y;if(H9==0){return 0;}
H9-=this.options.headerViewHeight;return parseInt(H9/this.options.rowHeight);},addColumn:function(Hb,Hf,Hd,H0R,H2f){var Hq=new _HTableColumn(Hb,Hf,Hd,H0R,H2f);this._tableColumns.push(Hq);this.H15.push(false);},setData:function(H01){this.data=H01;this.data.tableControl=this;this.numberOfRows=this.data.numberOfRows();this._calculateDimensions();},reloadData:function(H01){this.H18=true;this.H41=true;this.H2e();this.H41=false;this.H18=false;},removeColumn:function(Hq){this.H18=true;var Hb=this.tableColumns.indexOf(Hq);this._tableColumns.splice(Hb,1);this.tableHeaderColumns[Hb].die();this.tableHeaderColumns.splice(Hb,1);this.tableColumns[Hb].die();this.tableColumns.splice(Hb,1);this._tableRows.splice(Hb,1);this.H15.splice(Hb,1);this._calculateDimensions();this.H2e();this.H18=false;},moveColumn:function(H0d,H1s){this.H18=true;var H0c=H0d;var H0Q=H1s;if(H0c<H0Q){var H2R=H0Q;H0Q=H0c;H0c=H2R;}
var Hq=this._tableColumns[H0c];this._tableColumns.splice(H0c,1);this._tableColumns.splice(H0Q,0,Hq);Hq=this.tableColumns[H0c];this.tableColumns.splice(H0c,1);this.tableColumns.splice(H0Q,0,Hq);Hq=this.tableHeaderColumns[H0c]
this.tableHeaderColumns.splice(H0c,1);this.tableHeaderColumns.splice(H0Q,0,Hq);Hq=this.H15[H0c]
this.H15.splice(H0c,1);this.H15.splice(H0Q,0,Hq);Hq=this._tableRows[H0c]
this._tableRows.splice(H0c,1);this._tableRows.splice(H0Q,0,Hq);this._calculateDimensions();this.H2e();this.H18=false;},scrollLeft:function(){return this._scrollRect.left;},scrollTop:function(){return this._scrollRect.top;},H5r:function(){var _tableElem=elem_get(this.tableView.elemId);if(!_tableElem){throw("Error: HTableControl element not found");}
var _prevScrollRect=new HRect(this._scrollRect);this._scrollRect.offsetTo(parseInt(_tableElem.scrollLeft,10),parseInt(_tableElem.scrollTop,10));if(!_prevScrollRect.equals(this._scrollRect)){this.H18=true;this.H2e();this.H18=false;}}});