
HTextEdit=Base.extend({constructor:null,execCommand:function(H2M,H0P,H3,_doc){_doc=_doc||document;var H0g=H2M.toLowerCase();if((H0g=="hilitecolor"||H0g=="inserthtml")&&is.ie){return;}
if((H0g=="backcolor"||H0g=="forecolor"||H0g=="hilitecolor")&&H0P==true){}else if(H0g=="copy"&&!is.ns&&!is.opera){_doc.execCommand(H2M,H0P,H3);}else if(H0g=="createlink"&&H0P==true){}else if(H0g=="fontsize"){if(is.safari){switch(parseInt(H3)){case 1:H3="x-small";break;case 2:H3="small";break;case 3:H3="medium";break;case 4:H3="large";break;case 5:H3="x-large";break;case 6:H3="xx-large";break;case 7:H3="48px";break;}}
_doc.execCommand(H2M,H0P,H3);}else if(H0g=="formatblock"&&H0P==true){}else if(H0g=="inserthtml"&&H0P==true){}else if(H0g=="insertimage"&&H0P==true){}else if(is.safari&&H0g=="createlink"){if(this._execCreateLink){this._execCreateLink(H3);}}else{_doc.execCommand(H2M,H0P,H3);}},enableSelectionListeners:function(){var obj=this;if(!this.H2N){if(is.ie){document.attachEvent("onkeydown",function(e){obj.H0O(e);});document.attachEvent("onkeyup",function(e){obj.H0O(e);});document.attachEvent("onmouseup",function(e){obj.H0O(e);});}else{document.addEventListener("keydown",function(e){obj.H0O(e);},false);document.addEventListener("keyup",function(e){obj.H0O(e);},false);document.addEventListener("mouseup",function(e){obj.H0O(e);},false);}
this.H2N=true;}},saveSelection:function(){if(is.ie){this.HA.range=this.Hj.range;}else{this.HA.anchorNode=this.Hj.anchorNode;this.HA.anchorOffset=this.Hj.anchorOffset;this.HA.focusNode=this.Hj.focusNode;this.HA.focusOffset=this.Hj.focusOffset;this.HA.isCollapsed=this.Hj.isCollapsed;if(is.safari){this.HA.baseNode=this.Hj.baseNode;this.HA.baseOffset=this.Hj.baseOffset;this.HA.extentNode=this.Hj.extentNode;this.HA.extentOffset=this.Hj.extentOffset;}else{this.HA.range=this.Hj.range;}}},loadSelection:function(_window){var _window=_window||window;if(is.ie){this.HA.range.select();}else{var Hj=_window.getSelection();if(is.ns||is.opera){if(Hj.rangeCount>0){Hj.removeAllRanges();}
if(is.opera){var H2=this.HA.anchorNode;do{if(H2.nodeType==1&&H2.getAttribute("contentEditable")=="true"){H2.setAttribute("contentEditable","false");H2.setAttribute("contentEditable","true")}
H2=H2.parentNode;}while(H2);}
var H5m=document.createRange();H5m.setStart(this.HA.anchorNode,this.HA.anchorOffset);Hj.addRange(H5m);if(this.HA.isCollapsed==false){Hj.extend(this.HA.focusNode,this.HA.focusOffset);}}else if(is.safari){Hj.empty();Hj.setBaseAndExtent(this.HA.baseNode,this.HA.baseOffset,this.HA.extentNode,this.HA.extentOffset);}}},populateSelection:function(e,_window){var _window=_window||window;if(is.ie){var Hj=_window.document.selection;if(Hj.type.toLowerCase()!="control"){var H6J=Hj.createRange();this.Hj.range=H6J;}}else{var Hj=_window.getSelection();this.Hj.anchorNode=Hj.anchorNode;this.Hj.anchorOffset=Hj.anchorOffset;this.Hj.focusNode=Hj.focusNode;this.Hj.focusOffset=Hj.focusOffset;this.Hj.isCollapsed=Hj.isCollapsed;if(is.safari){this.Hj.baseNode=Hj.baseNode;this.Hj.baseOffset=Hj.baseOffset;this.Hj.extentNode=Hj.extentNode;this.Hj.extentOffset=Hj.extentOffset;}else{this.Hj.range=Hj.getRangeAt(0);}}
if(!this.Hb){this.Hb=0;}
if(e){if(e.type=="keydown"||e.type=="keyup"){this.saveSelection();}}},H0O:function(e){if(is.ie){this.populateSelection(e);}else{var Hj=window.getSelection();if(Hj.rangeCount>0){this.populateSelection(e);}else if(is.safari){this.populateSelection(e);}}},Hj:{anchorNode:null,anchorOffset:-1,focusNode:null,focusOffset:-1,isCollapsed:undefined},HA:{anchorNode:null,anchorOffset:-1,focusNode:null,focusOffset:-1,isCollapsed:undefined},H2N:false});HStyleButton=HImageButton.extend({packageName:"richtext",componentName:"stylebutton",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HStyleButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},mouseUp:function(){if(this.styleButtonDefaults.richtextview){HTextEdit.execCommand(this.styleButtonDefaults.command,false,null,this.styleButtonDefaults.richtextview.iframe().contentWindow.document);}
this.base();}},{H2v:"imageview"});HRichTextView=HControl.extend({packageName:"richtext",componentName:"richtextview",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HRichTextView]';this.preserveTheme=true;this.H2j=false;this.H48=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.base();},onIdle:function(){if(this.drawn){var H0w=elem_get(this.markupElemIds.control);if(!this.H2j&&H0w.contentWindow&&H0w.contentWindow.document){H0w.contentWindow.document.designMode="on";this.H2j=true;}
if(this.H2j&&H0w.contentWindow.document.body){if(!this.H48){H0w.contentWindow.document.body.innerHTML=this.value;this.H48=true;}
var H13=H0w.contentWindow.document.body.innerHTML;if(this.value!=H13){this.H49=true;this.setValue(H13);this.H49=false;}}}},setValue:function(H3){if(!this.H49){if(this.H2j){var H0w=elem_get(this.markupElemIds.control);if(H0w.contentWindow.document.body){H0w.contentWindow.document.body.innerHTML=H3;}}}
this.base(H3);},iframe:function(){return elem_get(this.markupElemIds.control);}});HRichTextControl=HControl.extend({packageName:"richtext",componentName:"richtextcontrol",constructor:function(H0,H4,H1){if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HRichTextControl]';this.preserveTheme=true;this.H0D=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.base();this.drawRect();this.drawMarkup();if(!this.H0D){this.barView=new HRichTextBar(new HRect(0,0,this.rect.width,20),this,{value:this.value});this.barView.draw();this.richTextView=new HRichTextView(new HRect(0,20,this.rect.width,this.rect.height),this,{value:(this.value||"editable text")});this.richTextView.draw();}
this.drawn=true;}
this.drawRect();}});HRichTextArea=HRichTextControl;HRichTextEditor=HRichTextControl;