
HTreeNode=HControl.extend({packageName:"tree",componentName:"treenode",constructor:function(H4,H1T,H1){var H0=new HRect();if(!H1){H1={};}
if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.setContent(H1T);this.type='[HTreeNode]';this.preserveTheme=true;this.expanded=true;this.selected=false;this.toggleControl=new HTreeNodeToggleControl(this);this.tree=null;this.childNodes=[];this.parent.addChildNode(this);if(!this.isinherited){this.draw();}},setContent:function(H1T){this.content=H1T;if(this.content){this.content.ownerNode=this;this.content.setEvents({mouseDown:false,mouseUp:false,draggable:true,droppable:true});var Hw=this;this.content.startDrag=function(H8,H9){this.actuallyDragging=false;this.canBeDropped=false;if(this.ownerNode.tree.allowNodeDragging){this.base(H8,H9);this.originX=H8;this.originY=H9;}};this.content.doDrag=function(H8,H9){if(this.ownerNode.tree.allowNodeDragging){if(this.actuallyDragging){prop_set(this.dragElemId,'left',(H8-this.originX)+'px');prop_set(this.dragElemId,'top',(H9-this.originY)+'px');}
else{if(H8>this.originX+4||H8<this.originX-4||H9>this.originY+4||H9<this.originY-4){this.actuallyDragging=true;this.canBeDropped=true;this.createDragClone(H8,H9);}}}};this.content.endDrag=function(H8,H9){if(this.ownerNode.tree.allowNodeDragging){this.base(H8,H9);}
if(this.actuallyDragging){this.deleteDragClone();this.actuallyDragging=false;}
else if(this.H0X){this.mouseUp(H8,H9);}};this.content.focus=function(){this.base();this.H0X=true;};this.content.blur=function(){this.base();this.H0X=false;};this.content.createDragClone=function(H8,H9){var H2=elem_get(this.ownerNode.elemId);var H1d=helmi.Element.getPageLocation(H2,true);this.dragElemId=elem_mk(this.appId);prop_set(this.dragElemId,'visibility','hidden',true);var H2l=H2.cloneNode(true);H2l.removeAttribute("id");H2l.innerHTML=H2l.innerHTML.replace(/\s+id="[^"]*"/g,"");this.dragContentElemId=elem_add(H2l);prop_set(this.dragElemId,'opacity',0.50);prop_set(this.dragElemId,'position','absolute',true);prop_set(this.dragElemId,'left',H1d[0]+'px',true);prop_set(this.dragElemId,'top',H1d[1]+'px',true);elem_append(this.dragElemId,this.dragContentElemId);prop_set(this.dragElemId,'z-index',this.app.viewsZOrder.length);prop_set(this.dragElemId,'visibility','visible',true);this.originX=this.originX-H1d[0];this.originY=this.originY-H1d[1];};this.content.deleteDragClone=function(){if(this.dragContentElemId){elem_del(this.dragContentElemId);this.dragContentElemId=null;}
if(this.dragElemId){elem_del(this.dragElemId);this.dragElemId=null;}};this.content.mouseUp=function(H8,H9){this.ownerNode.mouseUp(H8,H9);};this.content.onDrop=function(H00){if(!this.isValidDroppable(H00)||!H00.canBeDropped){return;}
H00.canBeDropped=false;this.ownerNode.setHover(false);H00.ownerNode.moveUnder(this.ownerNode);};this.content.onHoverStart=function(H00){if(!this.isValidDroppable(H00)){return;}
this.ownerNode.setHover(true);};this.content.onHoverEnd=function(H00){if(!this.isValidDroppable(H00)){return;}
this.ownerNode.setHover(false);};this.content.isValidDroppable=function(H00){if(!this.ownerNode.tree.allowNodeDragging||this==H00||!this.ownerNode||!H00.ownerNode||this.ownerNode==H00.ownerNode.parent||this.ownerNode.isDescendantOf(H00.ownerNode)){return false;}
return true;}}},setHover:function(Hh){this.toggleCSSClass(HTreeNode.H38+this.elemId,HTreeNode.cssHover,Hh);},isDescendantOf:function(H0V){if(this.parent==H0V){return true;}
else if(!this.parent.isDescendantOf){return false;}
else{return this.parent.isDescendantOf(H0V);}},hasChildren:function(){return(this.childNodes.length>0);},addChildNode:function(He){if(this.tree&&this.tree!=He.tree){He.setTree(this.tree);}
this.childNodes.push(He);if(this.drawn){He.addDomNode();this.H1e();}
this.tree.childNodeAdded(this,He);},addDomNode:function(){if(!this.drawn){var H2=elem_get(this.elemId);elem_get(this.appId).appendChild(H2);this.draw();this.postDrawBindings();var H5I=elem_get(this.parent.childContainerId);H2=elem_get(this.elemId);H5I.appendChild(H2);this.tree.invalidatePositionCache();}},setTree:function(H36){this.tree=H36;for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].setTree(H36);}},removeChildNode:function(He){He.deselect();He.removeDomNode();He.tree=null;this.childNodes.splice(this.childNodes.indexOf(He),1);this.H1e();this.tree.childNodeRemoved(this,He);},removeFromParent:function(){this.parent.removeChildNode(this);},removeAllChildren:function(){for(var i=this.childNodes.length-1;i>=0;i--){this.childNodes[i].removeAllChildren();this.childNodes[i].removeFromParent();}},removeDomNode:function(){if(this.drawn){var Hc=elem_get(this.elemId);Hc.parentNode.removeChild(Hc);this.tree.invalidatePositionCache();}},collapse:function(){if(!this.expanded){return;}
this.expanded=false;this.H35();},expand:function(){if(this.expanded){return;}
this.expanded=true;this.H35();},H35:function(){if(this.drawn){if(this.expanded){prop_set(this.childContainerId,'display','block');}
else{prop_set(this.childContainerId,'display','none');}
this.H1e();this.tree.invalidatePositionCache();}},collapseAllChildren:function(){for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].collapseAllChildren();this.childNodes[i].collapse();}},expandAllChildren:function(){for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].expandAllChildren();this.childNodes[i].expand();}},toggle:function(){if(this.expanded){this.collapse();}
else{this.expand();}},H1e:function(){var H4b=this.hasChildren();this.toggleCSSClass(HTreeNode.H37+this.elemId,HTreeNode.cssExpanded,this.expanded&&H4b);this.toggleCSSClass(HTreeNode.H37+this.elemId,HTreeNode.cssCollapsed,!this.expanded&&H4b);},select:function(H1x,HQ){this.tree.selectNode(this,H1x,HQ);},deselect:function(){this.tree.deselectNode(this);},refreshSelectionStatus:function(){if(this.drawn){this.toggleCSSClass(HTreeNode.H38+this.elemId,HTreeNode.cssSelected,this.selected);}},selectAllChildren:function(HQ){if(this.tree.treeType==HTreeControl.H_MULTIPLE_SELECTION_TREE){for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].selectAllChildren(HQ);this.childNodes[i].select(true,HQ);}}},deselectAllChildren:function(){for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].deselectAllChildren();this.childNodes[i].deselect();}},draw:function(){if(!this.drawn){this.drawMarkup();this.drawn=true;}},drawChildren:function(){var H1S="";for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].draw();H1S+=this.childNodes[i].markup;}
return H1S;},moveUnder:function(H0W){this.deselect();this.parent.removeChildNode(this);if(this.parent.H1e){this.parent.H1e();}
this.remove();H0W.addView(this);H0W.addChildNode(this);if(H0W.drawn){elem_append(H0W.childContainerId,this.elemId);}
if(H0W.H1e){H0W.H1e();}},postDrawBindings:function(){elem_replace(this.elemId,$(HTreeNode.H0F+this.elemId));this.childContainerId=this.bindDomElement(HTreeNode.H5J+this.elemId);this.togglerId=this.bindDomElement(HTreeNode.H37+this.elemId);this.contentId=this.bindDomElement(HTreeNode.H38+this.elemId);if(this.content){this.content.remove();this.addView(this.content);if(this.content.drawn){this.content.refresh();}
else{this.content.draw();}
prop_set(this.content.elemId,'position','relative',true);elem_append(this.contentId,this.content.elemId);if(!this.tree.staticNodeWidth){this.content.optimizeWidth();}}
this.toggleControl.draw();prop_set(this.toggleControl.elemId,'position','relative',true);elem_append(this.togglerId,this.toggleControl.elemId);this.H35();this.refreshSelectionStatus();this.setEnabled(false);for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].postDrawBindings();}},importJSON:function(H01,H0r,H0){if(!this.tree){return;}
this.tree.importJSON(H01,H0r,H0,this);},mouseUp:function(H8,H9){var H4c=HEventManager.events[HEventManager.HStatusCtrlKey];var H1x=(this.tree.treeType==HTreeControl.H_MULTIPLE_SELECTION_TREE)&&H4c;if(H1x){if(this.selected){this.deselect();}
else{this.select(true);}}
else{if(this.selected&&H4c){this.tree.deselectAllNodes();}
else{this.select(false);}}}},{cssSelected:"selected",cssExpanded:"expanded",cssCollapsed:"collapsed",cssHover:"hovering",H37:"treenodetoggler",H38:"treenodecontent",H5J:"treenodechildren",H0F:"treenode"});HTreeNodeToggleControl=HControl.extend({constructor:function(H4){var H0=new HRect();var H1={events:{mouseDown:true,mouseUp:false,draggable:false,droppable:false}};this.base(H0,H4,H1);},mouseDown:function(H8,H9){if(this.parent.hasChildren()){this.parent.toggle();}}});HTreeControl=HControl.extend({packageName:"tree",componentName:"treecontrol",constructor:function(H0,H4,H1){if(!H1){H1={};}
H1.events={mouseDown:false,mouseUp:false,draggable:false};var HJ=Base.extend({staticNodeWidth:false,allowNodeDragging:false,treeType:HTreeControl.H_SINGLE_SELECTION_TREE});this.options=new(HJ.extend(H1))();if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HTreeControl]';this.preserveTheme=true;this.childNodes=[];this.setTreeType(this.options.treeType);this.selectedNodes=[];this.setStaticNodeWidth(this.options.staticNodeWidth);this.allowNodeDragging=this.options.allowNodeDragging;if(!this.isinherited){this.draw();}},expandAll:function(){for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].expandAllChildren();this.childNodes[i].expand();}},collapseAll:function(){for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].collapseAllChildren();this.childNodes[i].collapse();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.childContainerId=this.bindDomElement(HTreeControl.H0F+this.elemId);for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].postDrawBindings();}
var Hw=this;Event.observe(elem_get(this.childContainerId),'scroll',function(e){if(Hw.H34){window.clearTimeout(Hw.H34);Hw.H34=null;}
Hw.H34=window.setTimeout(function(){Hw.invalidatePositionCache();},300);},false);this.drawn=true;}},drawChildren:function(){var H1S="";for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].draw();H1S+=this.childNodes[i].markup;}
return H1S;},setTreeType:function(H0U){if(this.treeType==HTreeControl.H_MULTIPLE_SELECTION_TREE&&H0U==HTreeControl.H_SINGLE_SELECTION_TREE&&this.selectedNodes.length>0){var H5F=this.selectedNodes[this.selectedNodes.length-1];this.deselectAllNodes();this.selectNode(H5F);}
this.treeType=H0U;},selectNode:function(He,H1x,HQ){var H0k=false;if(this.treeType==HTreeControl.H_SINGLE_SELECTION_TREE||!H1x){H0k=this.deselectAllNodesExcept(He,true);}
if(!this.isSelectedNode(He)){He.selected=true;He.setValue("mouseUp");this.selectedNodes.push(He);He.refreshSelectionStatus();H0k=true;}
if(!HQ&&H0k){this.selectionChanged();}},deselectNode:function(He,HQ){if(this.isSelectedNode(He)){He.selected=false;He.setValue("");this.selectedNodes.splice(this.selectedNodes.indexOf(He),1);He.refreshSelectionStatus();if(!HQ){this.selectionChanged();}}},selectAllNodes:function(){if(this.treeType==HTreeControl.H_MULTIPLE_SELECTION_TREE){var H0k=this.childNodes.length>0&&(this.selectedNodes.length!=this.childNodes.length);for(var i=0;i<this.childNodes.length;i++){this.childNodes[i].selectAllChildren(true);this.childNodes[i].select(true,true);}
if(H0k){this.selectionChanged();}}},deselectAllNodes:function(HQ){var H0k=(this.selectedNodes.length>0);var H5G=!HQ&&H0k;while(this.selectedNodes.length>0){this.deselectNode(this.selectedNodes[0],true);}
if(H5G){this.selectionChanged();}
return H0k;},deselectAllNodesExcept:function(He,HQ){var H0k=false;if(!this.isSelectedNode(He)){H0k=this.deselectAllNodes(HQ);}
else{this.selectedNodes.splice(this.selectedNodes.indexOf(He),1);H0k=this.deselectAllNodes(HQ);this.selectedNodes.splice(0,0,He);}
return H0k;},selectedNode:function(){if(this.selectedNodes.length>0){return this.selectedNodes[0];}
return null;},isSelectedNode:function(He){return(this.selectedNodes.indexOf(He)>-1);},removeAllNodes:function(){for(var i=this.childNodes.length-1;i>=0;i--){this.childNodes[i].removeAllChildren();this.childNodes[i].removeFromParent();}},importJSON:function(H01,H0r,H0,H02){if(typeof(H0r)=="undefined"||H0r==null){H0r=HStringView;}
if(typeof(H0)=="undefined"||H0==null){H0=new HRect();}
if(typeof(H02)=="undefined"||H02==null){H02=this;}
this.H4a(H01,H0r,H02,H0);},H4a:function(H01,H0r,HD,H0){var l=H01.length;for(var i=0;i<l;i++){var H7=new H0r(H0,this.app);for(var H1c in H01[i]){if(H1c!="children"){var H2k=H1c.substring(0,1).toUpperCase()+
H1c.substring(1,H1c.length);H2k="set"+H2k;if(eval("H7."+H2k)){eval("H7."+H2k+"(H01[i][H1c])");}
else{H7[H1c]=H01[i][H1c];}}}
var H5H=new HTreeNode(HD,H7);this.H4a(H01[i].children,H0r,H5H,H0);}},setStaticNodeWidth:function(Hh){this.staticNodeWidth=Hh;},hasChildren:function(){return(this.childNodes.length>0);},addChildNode:function(He){He.setTree(this);this.childNodes.push(He);if(this.drawn){He.addDomNode();}
this.childNodeAdded(this,He);},removeChildNode:function(He){He.deselect();He.removeDomNode();He.tree=null;this.childNodes.splice(this.childNodes.indexOf(He),1);this.childNodeRemoved(this,He);},selectionChanged:function(){},childNodeAdded:function(H02,H33){},childNodeRemoved:function(H02,H33){}},{H_SINGLE_SELECTION_TREE:0,H_MULTIPLE_SELECTION_TREE:1,H0F:"treecontrol"});