
HTransportURL=false;HTransportPoll=true;HTransporter=Base.extend({constructor:null,start:function(H6I){this.url_base=H6I;this.ses_id=0;this.err_msg='';this.isBusy=false;this.syncNum=0;this.syncDelay=0;this.pollMode=HTransportPoll;this.H3S=setTimeout('HTransporter.sync();',this.syncDelay);},setPollMode:function(Hh){this.pollMode=Hh;},failure:function(resp){alert('HTTP ERROR! STOP.');clearTimeout(this.H3S);this.isBusy=true;},respond:function(resp){var t=HTransporter;try{t.err_msg='';HVM.isGetting=true;eval(resp.responseText);HVM.isGetting=false;}catch(e){t.err_msg='&err_msg='+e;}
t.isBusy=false;},sync:function(){var valid_delay=((this.syncDelay&&this.syncDelay>0)||this.syncDelay==0);if(valid_delay&&this.url_base){if(!this.isBusy){this.isBusy=true;var H5l=HValueManager.toXML();if(""!=H5l||this.pollMode){this.syncNum++;req_args={onSuccess:function(resp){HTransporter.respond(resp);},onFailure:function(resp){HTransporter.failure(resp);},method:'post',postBody:'ses_id='+HTransporter.ses_id+HTransporter.err_msg+H5l};this.req=new Ajax.Request(this.url_base,req_args);}
else{this.isBusy=false;}}
this.H3S=setTimeout('HTransporter.sync();',this.syncDelay);}},stop:function(){clearTimeout(this.H3S);}});onloader("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:[],tosync:[],isSending:false,isGetting:false,add:function(H6,Hg){this.values[H6]=Hg;},set:function(H6,H3){this.values[H6].set(H3);},del:function(H6){var H5f=this.values[H6];var H5g=H5f.views;for(var Hs=0;Hs<H5g.length;Hs++){var H6F=H5g[Hs];H6F.valueObj=new HDummyValue(0,H5f.value);}
this.values[H6]=null;},changed:function(H2b){if(this.isGetting==false){if(this.tosync.indexOf(H2b.id)==-1){this.tosync.push(H2b.id);}}},toXML:function(){var H5h='&HSyncData=';if(!this.isSending){this.isSending=true;var H3Q=this.tosync.length;if(H3Q==0){this.isSending=false;return'';}
var H5k=[];for(var HT=0;HT<H3Q;HT++){var H0t=this.tosync.shift();var H6H=this.values[H0t];H5k.push(H6H.toXML(HT));}
var H6G=H5k.join('');H5h+='<hsyncvalues version="2240" length="'+H3Q+'">'+H6G+'</hsyncvalues>';this.isSending=false;}
return H5h;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(H6,H3){this.id=H6;this.type='[HValue]';this.value=H3;this.views=[];HValueManager.add(H6,this);},set:function(H3){if(H3!=this.value){this.value=H3;HValueManager.changed(this);this.refresh();}},get:function(){return this.value;},bind:function(Ho){if(Ho===undefined){throw("HValueBindError: Ho is undefined!");}
if(this.views.indexOf(Ho.elemId)==-1){this.views.push(Ho);Ho.setValueObj(this);}},unbind:function(Ho){for(var Hs=0;Hs<this.views.length;Hs++){var H3P=this.views[Hs];if(H3P===Ho){this.views.splice(Hs);return;}}},refresh:function(){for(var Hs=0;Hs<this.views.length;Hs++){var Ho=this.views[Hs];if(Ho.value!=this.value){if(!Ho.H2a){Ho.H2a=true;Ho.setValue(this.value);Ho.H2a=false;}}}},toXML:function(HT){var H0t=this.id;var H5i=this.type.slice(1,-1).toLowerCase();var H3R=this.value;var H5j=typeof H3R;var H0f=H3R.toString();H0f=H0f.replace(/&/g,'&amp;');H0f=H0f.replace(/</g,'&lt;');H0f=H0f.replace(/>/g,'&gt;');H0f=H0f.replace(/%/g,'%25');H0f=H0f.replace(/&/g,'%26');return'<'+H5i+' id="'+H0t+'" order="'+HT+'" jstype="'+H5j+'" length="'+H3R.toString().length+'">'+H0f+'</'+H5i+'>';}});HControlValue=HValue.extend({constructor:function(H6,H3){this.validate(H3);this.label=(H3.label!==undefined)?H3.label:"Untitled";if(H3.value===undefined){H3.value=0;}
this.enabled=(H3.enabled!==undefined)?H3.enabled:true;this.active=(H3.active!==undefined)?H3.active:false;this.base(H6,H3.value);this.type='[HControlValue]';},validate:function(H3){if(typeof H3!="object"){throw('ControlValueError: ControlValue must be an object');}},set:function(H3){if(typeof H3=="boolean"){var H2R=H3;H3={};H3.value=H2R;}
this.validate(H3);this.label=(H3.label!==undefined)?H3.label:this.label;if(H3.value===undefined){H3.value=this.value;}
this.enabled=(H3.enabled!==undefined)?H3.enabled:this.enabled;this.active=(H3.active!==undefined)?H3.active:this.active;this.base(H3.value);},setLabel:function(HB){this.set({label:HB});},setValue:function(H3){this.set({value:H3});},setEnabled:function(H2N){this.set({enabled:H2N});},setActive:function(_active){this.set({active:_active});},bind:function(Ho){this.base(Ho);if(this.views.indexOf(Ho.elemId)==-1){this.views.push(Ho);Ho.setLabel(this.label);Ho.setEnabled(this.enabled);}},refresh:function(){this.base();for(var Hs=0;Hs<this.views.length;Hs++){var Ho=this.views[Hs];if(Ho.value!=this.value){if(!Ho.H2a){Ho.H2a=true;Ho.setLabel(this.label);Ho.setEnabled(this.enabled);Ho.H2a=false;}}}},toXML:function(HT){var H0t=this.id;return'<controlvalue id="'+H0t+'" order="'+HT+'"><label>'+this.label+'</label><value>'+this.value+'</value><enabled>'+this.enabled+'</enabled><active>'+this.active+'</active></controlvalue>';}});HValueMatrixComponentExtension={setValueMatrix:function(H2P){this.valueMatrix=H2P;this.valueMatrixIndex=this.valueMatrix.addValue(this.valueObj,this.value);},mouseDown:function(H8,H9,H03){if(this.valueMatrix instanceof HValueMatrix){this.valueMatrix.setValue(this.valueMatrixIndex);}else{this.setValue(!this.value);}},mouseUp:function(H8,H9,H03){if(this.valueMatrix instanceof HValueMatrix){this.valueMatrix.setValue(this.valueMatrixIndex);}else{this.setValue(!this.value);}}};HValueMatrix=HClass.extend({constructor:function(){this.values=[];this.value=-1;},setValueObj:function(H1K){this.valueObj=H1K;this.setValue(this.valueObj.value);},setValue:function(Hb){if(Hb!=this.value){if(this.value!=-1){this.values[this.value].set(false);}
if(Hb!=-1){this.valueObj.set(Hb);this.value=Hb;this.values[this.value].set(true);}}},addValue:function(H5o,H5p){this.values.push(H5o);var H1s=this.values.length-1;if(H5p){this.setValue(H1s);}
return H1s;}});