
HWindowLabel=HButton.extend({packageName:"window",componentName:"windowlabel",constructor:function(H0,H4,H1){if(!H1){H1={};}
if(!H1.events){H1.events={};}
if(!H1.events.draggable){H1.events.draggable=true;}
if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HWindowLabel]';if(!this.isinherited){this.draw();}},gainedActiveStatus:function(H0A){HEventManager.changeActiveControl(this.parent.parent);},startDrag:function(H8,H9){this.parent.parent.startDrag(H8,H9);},doDrag:function(H8,H9){this.parent.parent.doDrag(H8,H9);},endDrag:function(H8,H9){this.parent.parent.endDrag(H8,H9);}});HWindowBar=HButton.extend({packageName:"window",componentName:"windowbar",constructor:function(H0,H4,H1){if(!H1){H1={};}
if(!H1.events){H1.events={};}
if(!H1.events.draggable){H1.events.draggable=true;}
if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HWindowBar]';if(!this.isinherited){this.draw();}},setLabel:function(HB){this.label=HB;if(this.parent.windowLabel){this.parent.windowLabel.setLabel(HB);}},startDrag:function(H8,H9){this.parent.startDrag(H8,H9);},doDrag:function(H8,H9){this.parent.doDrag(H8,H9);},endDrag:function(H8,H9){this.parent.endDrag(H8,H9);}});HWindowView=HView.extend({packageName:"window",componentName:"windowview",constructor:function(H0,H4){if(this.isinherited){this.base(H0,H4);}
else{this.isinherited=true;this.base(H0,H4);this.isinherited=false;}
this.type='[HWindowView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawMarkup();var H1h=this.bindDomElement(HWindowView.H0F+this.elemId);if(!H1h){throw("HWindowView: The HTML template must have an element with "+"the ID '"+HWindowView.H0F+" + this.elemId'.");}
elem_append(this.parent.elemId,H1h);elem_append(0,this.elemId);elem_del(this.elemId);elem_replace(this.elemId,elem_get(H1h));}
this.drawRect();}},{H0F:"windowview"});HWindowControl=HControl.extend({packageName:"window",componentName:"windowcontrol",constructor:function(H0,H4,H1){if(!H1){H1={};}
var HJ=Base.extend({minSize:[64,32],maxSize:[4096,3072],barHeight:21,resizeW:4,resizeE:4,resizeN:4,resizeS:4,resizeNW:[4,4],resizeNE:[4,4],resizeSW:[4,4],resizeSE:[16,16],menuBar:null});H1=new(HJ.extend(H1))();if(this.isinherited){this.base(H0,H4,H1);}
else{this.isinherited=true;this.base(H0,H4,H1);this.isinherited=false;}
this.type='[HWindowControl]';this.preserveTheme=true;this.H3h();this.setDraggable(true);this.drawRect();this.drawMarkup();this.H2p();this.windowBar=new HWindowBar(this.Hn.windowBarRect,this,{label:this.label});this.windowBar.draw();this.windowLabel=new HWindowLabel(this.Hn.windowLabelRect,this.windowBar,{label:this.label});this.windowLabel.draw();this.windowView=new HWindowView(this.Hn.windowViewRect,this);this.windowView.draw();this.setLabel(this.label);if(H1.menuBar){this.setMenuBar(H1.menuBar);}
if(!this.isinherited){this.draw();}},H3h:function(){this.Hn={dragWindow:false,resizeW:false,resizeE:false,resizeN:false,resizeS:false,resizeNW:false,resizeNE:false,resizeSW:false,resizeSE:false,dragWindowRect:new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN),resizeNRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.options.resizeN),resizeSRect:new HRect(this.options.resizeW,this.rect.height-this.options.resizeS,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,this.options.resizeN,this.options.resizeW,this.rect.height-this.options.resizeS),resizeERect:new HRect(this.rect.width-this.options.resizeE,this.options.resizeN,this.rect.width,this.rect.height-this.options.resizeS),resizeNWRect:new HRect(0,0,this.options.resizeNW[0],this.options.resizeNW[1]),resizeNERect:new HRect(this.rect.width-this.options.resizeNE[0],0,this.rect.width,this.options.resizeNE[1]),resizeSWRect:new HRect(0,this.rect.height-this.options.resizeSW[1],this.options.resizeSW[0],this.rect.height),resizeSERect:new HRect(this.rect.width-this.options.resizeSE[0],this.rect.height-this.options.resizeSE[1],this.rect.width,this.rect.height)};},H4k:function(){var H4l=this.Hn.resizeW||this.Hn.resizeSW||this.Hn.resizeNW;var H4m=this.Hn.resizeN||this.Hn.resizeNE||this.Hn.resizeNW;if(this.rect.width<this.options.minSize[0]){if(H4l){this.rect.left=this.rect.right-this.options.minSize[0];}
this.rect.setWidth(this.options.minSize[0]);}else if(this.rect.width>this.options.maxSize[0]){if(H4l){this.rect.left=this.rect.right-this.options.maxSize[0];}
this.rect.setWidth(this.options.maxSize[0]);}
if(this.rect.height<this.options.minSize[1]){if(H4m){this.rect.top=this.rect.bottom-this.options.minSize[1];}
this.rect.setHeight(this.options.minSize[1]);}else if(this.rect.height>this.options.maxSize[1]){if(H4m){this.rect.top=this.rect.bottom-this.options.maxSize[1];}
this.rect.setHeight(this.options.maxSize[1]);}
var H3i=0-this.options.resizeW;if(this.rect.left<H3i){this.rect.left=H3i;this.rect.right=this.rect.width+H3i;}
var H3j=0-this.options.resizeN;if(this.rect.top<H3j){this.rect.top=H3j;this.rect.bottom=this.rect.height+H3j;}},startDrag:function(H8,H9){this.H0S=new HPoint(H8,H9);this.H1R=new HPoint(H8,H9);this.H1Y=new HRect(this.rect);this.H3h();var H0y=this.H0S.subtract(this.H1Y.leftTop);if(this.Hn.resizeNWRect.contains(H0y)){this.HK=H0y;this.Hn.resizeNW=true;}else if(this.Hn.resizeNERect.contains(H0y)){this.HK=this.H0S.subtract(this.H1Y.rightTop);this.Hn.resizeNE=true;}else if(this.Hn.resizeSWRect.contains(H0y)){this.HK=this.H0S.subtract(this.H1Y.leftBottom);this.Hn.resizeSW=true;}else if(this.Hn.resizeSERect.contains(H0y)){this.HK=this.H0S.subtract(this.H1Y.rightBottom);this.Hn.resizeSE=true;}else if(this.Hn.resizeNRect.contains(H0y)){this.HK=H9-this.rect.top;this.Hn.resizeN=true;}else if(this.Hn.resizeSRect.contains(H0y)){this.HK=H9-this.rect.bottom;this.Hn.resizeS=true;}else if(this.Hn.resizeWRect.contains(H0y)){this.HK=H8-this.rect.left;this.Hn.resizeW=true;}else if(this.Hn.resizeERect.contains(H0y)){this.HK=H8-this.rect.right;this.Hn.resizeE=true;}else if(this.Hn.dragWindowRect.contains(H0y)){this.HK=this.H0S.subtract(this.H1Y.leftTop);this.Hn.dragWindow=true;}
this.bringToFront();this.doDrag(H8,H9);},doDrag:function(H8,H9){var Ht;var H0p=new HPoint(H8,H9);if(!this.H1R.equals(H0p)){if(this.Hn.resizeNW==true){Ht=H0p.subtract(this.HK);this.rect.setLeftTop(Ht);}else if(this.Hn.resizeNE==true){Ht=H0p.subtract(this.HK);this.rect.setRightTop(Ht);}else if(this.Hn.resizeSW==true){Ht=H0p.subtract(this.HK);this.rect.setLeftBottom(Ht);}else if(this.Hn.resizeSE==true){Ht=H0p.subtract(this.HK);this.rect.setRightBottom(Ht);}else if(this.Hn.resizeN==true){Ht=H9-this.HK;this.rect.top=Ht;this.rect.updateSecondaryValues();}else if(this.Hn.resizeS==true){Ht=H9-this.HK;this.rect.bottom=Ht;this.rect.updateSecondaryValues();}else if(this.Hn.resizeW==true){Ht=H8-this.HK;this.rect.left=Ht;this.rect.updateSecondaryValues();}else if(this.Hn.resizeE==true){Ht=H8-this.HK;this.rect.right=Ht;this.rect.updateSecondaryValues();}else if(this.Hn.dragWindow==true){Ht=H0p.subtract(this.HK);this.rect.offsetTo(Ht);}
this.H4k();this.setStyle('left',this.rect.left+'px',true);this.setStyle('top',this.rect.top+'px',true);this.setStyle('width',this.rect.width+'px',true);this.setStyle('height',this.rect.height+'px',true);if(this.Hn.dragWindow==false){this.H2p();}
this.H1R=H0p;}},endDrag:function(H8,H9){this.doDrag(H8,H9);},H2p:function(){var H2q=new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN);var H4n=new HRect(0,0,H2q.width,H2q.height);var H1Z=new HRect(this.options.resizeW,this.options.resizeN+this.options.barHeight,this.rect.width-this.options.resizeE,this.rect.height-this.options.resizeS);if(this.menuBar){var H2s=this.options.menuBarHeight;if(H2s+this.options.resizeN+this.options.barHeight>this.rect.height-this.options.resizeS){H2s=this.rect.height-this.options.barHeight-
this.options.resizeS-this.options.resizeN;}
H1Z.setTop(H1Z.top+H2s);this.menuBar.resizeTo(H1Z.width,H2s);}
if(!this.Hn.windowBarRect){this.Hn.windowBarRect=H2q;this.Hn.windowLabelRect=H4n;this.Hn.windowViewRect=H1Z;}else{this.windowBar.setRect(H2q);this.windowLabel.setRect(H4n);this.windowView.setRect(H1Z);}},draw:function(){this.drawRect();},setLabel:function(HB){if(this.drawn){this.windowLabel.setLabel(HB);}
this.base(HB);},refresh:function(){if(this.windowBar){this.windowBar.refresh();}
this.drawRect();},setMenuBar:function(H2r){if(H2r==this.menuBar){return;}
if(this.menuBar){this.menuBar.die();}
this.menuBar=H2r;if(H2r){this.options.menuBarHeight=this.menuBar.rect.height;this.menuBar.remove();this.addView(this.menuBar);elem_append(this.elemId,this.menuBar.elemId);this.menuBar.moveTo(this.windowView.rect.left,this.windowBar.rect.bottom);}
this.H2p();}});HWindow=HWindowControl;