
HWindowBar=HButton.extend({packageName:"window",componentName:"windowbar",constructor:function(_2,_6,_3){if(!_3){_3={};}
if(!_3.events){_3.events={};}
if(!_3.events.draggable){_3.events.draggable=true;}
if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HWindowBar]';if(!this.isinherited){this.draw();}},setLabel:function(_w){this.label=_w;if(this.parent.windowLabel){this.parent.windowLabel.setLabel(_w);}},startDrag:function(_5,_a){this.parent.startDrag(_5,_a);},doDrag:function(_5,_a){this.parent.doDrag(_5,_a);},endDrag:function(_5,_a){this.parent.endDrag(_5,_a);}});HWindowLabel=HButton.extend({packageName:"window",componentName:"windowlabel",constructor:function(_2,_6,_3){if(!_3){_3={};}
if(!_3.events){_3.events={};}
if(!_3.events.draggable){_3.events.draggable=true;}
if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HWindowLabel]';if(!this.isinherited){this.draw();}},gainedActiveStatus:function(_0h){HEventManager.changeActiveControl(this.parent.parent);},startDrag:function(_5,_a){this.parent.parent.startDrag(_5,_a);},doDrag:function(_5,_a){this.parent.parent.doDrag(_5,_a);},endDrag:function(_5,_a){this.parent.parent.endDrag(_5,_a);}});HWindowView=HView.extend({packageName:"window",componentName:"windowview",constructor:function(_2,_6){if(this.isinherited){this.base(_2,_6);}
else{this.isinherited=true;this.base(_2,_6);this.isinherited=false;}
this.type='[HWindowView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawMarkup();var _14=this.bindDomElement(HWindowView._1U+this.elemId);if(!_14){throw("HWindowView: The HTML template must have an element with "+"the ID '"+HWindowView._1U+" + this.elemId'.");}
elem_append(this.parent.elemId,_14);elem_append(0,this.elemId);elem_del(this.elemId);elem_replace(this.elemId,elem_get(_14));}
this.drawRect();}},{_1U:"windowview"});HWindowControl=HControl.extend({packageName:"window",componentName:"windowcontrol",constructor:function(_2,_6,_3){if(!_3){_3={};}
var _B=Base.extend({minSize:[64,32],maxSize:[4096,3072],barHeight:21,resizeW:4,resizeE:4,resizeN:4,resizeS:4,resizeNW:[4,4],resizeNE:[4,4],resizeSW:[4,4],resizeSE:[16,16],menuBar:null});_3=new(_B.extend(_3))();if(this.isinherited){this.base(_2,_6,_3);}
else{this.isinherited=true;this.base(_2,_6,_3);this.isinherited=false;}
this.type='[HWindowControl]';this.preserveTheme=true;this._3n();this.setDraggable(true);this.drawRect();this.drawMarkup();this.buildWinParts();this.setLabel(this.label);if(_3.menuBar){this.setMenuBar(_3.menuBar);}
if(!this.isinherited){this.draw();}},buildWinParts:function(){this.calcWindowPartRects();this.windowBar=new HWindowBar(this._g.windowBarRect,this,{label:this.label});this.windowBar.draw();this.windowLabel=new HWindowLabel(this._g.windowLabelRect,this.windowBar,{label:this.label});this.windowLabel.draw();this.windowView=new HWindowView(this._g.windowViewRect,this);this.windowView.draw();},_3n:function(){this._g={dragWindow:false,resizeW:false,resizeE:false,resizeN:false,resizeS:false,resizeNW:false,resizeNE:false,resizeSW:false,resizeSE:false,dragWindowRect:new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN),resizeNRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.options.resizeN),resizeSRect:new HRect(this.options.resizeW,this.rect.height-this.options.resizeS,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,this.options.resizeN,this.options.resizeW,this.rect.height-this.options.resizeS),resizeERect:new HRect(this.rect.width-this.options.resizeE,this.options.resizeN,this.rect.width,this.rect.height-this.options.resizeS),resizeNWRect:new HRect(0,0,this.options.resizeNW[0],this.options.resizeNW[1]),resizeNERect:new HRect(this.rect.width-this.options.resizeNE[0],0,this.rect.width,this.options.resizeNE[1]),resizeSWRect:new HRect(0,this.rect.height-this.options.resizeSW[1],this.options.resizeSW[0],this.rect.height),resizeSERect:new HRect(this.rect.width-this.options.resizeSE[0],this.rect.height-this.options.resizeSE[1],this.rect.width,this.rect.height)};},checkWindowSizeConstrains:function(){var _4Y=this._g.resizeW||this._g.resizeSW||this._g.resizeNW;var _4X=this._g.resizeN||this._g.resizeNE||this._g.resizeNW;if(this.rect.width<this.options.minSize[0]){if(_4Y){this.rect.left=this.rect.right-this.options.minSize[0];}
this.rect.setWidth(this.options.minSize[0]);}else if(this.rect.width>this.options.maxSize[0]){if(_4Y){this.rect.left=this.rect.right-this.options.maxSize[0];}
this.rect.setWidth(this.options.maxSize[0]);}
if(this.rect.height<this.options.minSize[1]){if(_4X){this.rect.top=this.rect.bottom-this.options.minSize[1];}
this.rect.setHeight(this.options.minSize[1]);}else if(this.rect.height>this.options.maxSize[1]){if(_4X){this.rect.top=this.rect.bottom-this.options.maxSize[1];}
this.rect.setHeight(this.options.maxSize[1]);}
var _35=0-this.options.resizeW;if(this.rect.left<_35){this.rect.left=_35;this.rect.right=this.rect.width+_35;}
var _3x=0-this.options.resizeN;if(this.rect.top<_3x){this.rect.top=_3x;this.rect.bottom=this.rect.height+_3x;}},startDrag:function(_5,_a){this._0H=new HPoint(_5,_a);this._2p=new HPoint(_5,_a);this._1R=new HRect(this.rect);this._3n();var _0j=this._0H.subtract(this._1R.leftTop);if(this._g.resizeNWRect.contains(_0j)){this._C=_0j;this._g.resizeNW=true;}else if(this._g.resizeNERect.contains(_0j)){this._C=this._0H.subtract(this._1R.rightTop);this._g.resizeNE=true;}else if(this._g.resizeSWRect.contains(_0j)){this._C=this._0H.subtract(this._1R.leftBottom);this._g.resizeSW=true;}else if(this._g.resizeSERect.contains(_0j)){this._C=this._0H.subtract(this._1R.rightBottom);this._g.resizeSE=true;}else if(this._g.resizeNRect.contains(_0j)){this._C=_a-this.rect.top;this._g.resizeN=true;}else if(this._g.resizeSRect.contains(_0j)){this._C=_a-this.rect.bottom;this._g.resizeS=true;}else if(this._g.resizeWRect.contains(_0j)){this._C=_5-this.rect.left;this._g.resizeW=true;}else if(this._g.resizeERect.contains(_0j)){this._C=_5-this.rect.right;this._g.resizeE=true;}else if(this._g.dragWindowRect.contains(_0j)){this._C=this._0H.subtract(this._1R.leftTop);this._g.dragWindow=true;}
this.bringToFront();this.doDrag(_5,_a);},doDrag:function(_5,_a){var _l;var _0R=new HPoint(_5,_a);if(!this._2p.equals(_0R)){if(this._g.resizeNW==true){_l=_0R.subtract(this._C);this.rect.setLeftTop(_l);}else if(this._g.resizeNE==true){_l=_0R.subtract(this._C);this.rect.setRightTop(_l);}else if(this._g.resizeSW==true){_l=_0R.subtract(this._C);this.rect.setLeftBottom(_l);}else if(this._g.resizeSE==true){_l=_0R.subtract(this._C);this.rect.setRightBottom(_l);}else if(this._g.resizeN==true){_l=_a-this._C;this.rect.top=_l;this.rect.updateSecondaryValues();}else if(this._g.resizeS==true){_l=_a-this._C;this.rect.bottom=_l;this.rect.updateSecondaryValues();}else if(this._g.resizeW==true){_l=_5-this._C;this.rect.left=_l;this.rect.updateSecondaryValues();}else if(this._g.resizeE==true){_l=_5-this._C;this.rect.right=_l;this.rect.updateSecondaryValues();}else if(this._g.dragWindow==true){_l=_0R.subtract(this._C);this.rect.offsetTo(_l);}
this.checkWindowSizeConstrains();this.setStyle('left',this.rect.left+'px',true);this.setStyle('top',this.rect.top+'px',true);this.setStyle('width',this.rect.width+'px',true);this.setStyle('height',this.rect.height+'px',true);if(this._g.dragWindow==false){this.calcWindowPartRects();}
this._2p=_0R;}},endDrag:function(_5,_a){this.doDrag(_5,_a);},calcWindowPartRects:function(){var _2C=new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN);var _5l=new HRect(0,0,_2C.width,_2C.height);var _1W=new HRect(this.options.resizeW,this.options.resizeN+this.options.barHeight,this.rect.width-this.options.resizeE,this.rect.height-this.options.resizeS);if(this.menuBar){var _2k=this.options.menuBarHeight;if(_2k+this.options.resizeN+this.options.barHeight>this.rect.height-this.options.resizeS){_2k=this.rect.height-this.options.barHeight-
this.options.resizeS-this.options.resizeN;}
_1W.setTop(_1W.top+_2k);this.menuBar.resizeTo(_1W.width,_2k);}
if(!this._g.windowBarRect){this._g.windowBarRect=_2C;this._g.windowLabelRect=_5l;this._g.windowViewRect=_1W;}else{this.windowBar.setRect(_2C);this.windowLabel.setRect(_5l);this.windowView.setRect(_1W);}},draw:function(){this.drawRect();},setLabel:function(_w){if(this.drawn&&this.windowLabel){this.windowLabel.setLabel(_w);}
this.base(_w);},refresh:function(){if(this.windowBar){this.windowBar.refresh();}
this.drawRect();},setMenuBar:function(_2j){if(_2j==this.menuBar){return;}
if(this.menuBar){this.menuBar.die();}
this.menuBar=_2j;if(_2j){this.options.menuBarHeight=this.menuBar.rect.height;this.menuBar.remove();this.addView(this.menuBar);elem_append(this.elemId,this.menuBar.elemId);this.menuBar.moveTo(this.windowView.rect.left,this.windowBar.rect.bottom);}
this.calcWindowPartRects();},stopAnimation:function(){this.base();this.calcWindowPartRects();this.refresh();}});HWindow=HWindowControl;