
HButton=HControl.extend({componentName:'button'});HCheckbox=HButton.extend({componentName:'checkbox',constructor:function(_1,_m,_2){this.base(_1,_m,_2);this.setClickable(true);},click:function(){this.setValue(!this.value);},refreshValue:function(){if(this.markupElemIds.control){if(this.value){this.toggleCSSClass(this.markupElemIds.control,'checked',true);this.toggleCSSClass(this.markupElemIds.control,'unchecked',false);}
else{this.toggleCSSClass(this.markupElemIds.control,'checked',false);this.toggleCSSClass(this.markupElemIds.control,'unchecked',true);}}}});HCheckBox=HCheckbox;HRadioButton=(HCheckbox.extend(HValueMatrixComponentExtension)).extend({componentName:'radiobutton'});HRadiobutton=HRadioButton;HStringView=HControl.extend({componentName:"stringview",componentBehaviour:['view','control','text'],refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'title',this.label);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_g,_2){this.base(_1,_g,_2);this.setTextEnter(true);},setEnabled:function(_8){this.base(_8);if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).value=this.value;}}},textEnter:function(){if(this['markupElemIds']===undefined){return;}
var _8q=ELEM.get(this.markupElemIds.value).value;if(_8q!=this.value){this.setValue(_8q);}}});HUploader=HControl.extend({componentName:'uploader',uploadState:false,uploadKey:false,uploadStateLabels:{'0':"Select file...",'1':"Uploading...",'2':"Processing data...",'3':"Upload Complete",'4':"Preparing upload",'-1':"Error: Invalid request",'-2':"Error: Invalid upload key",'-3':"Error: Invalid data format",'-4':"Error: File too big",'-6':"Error: Post-processing failed"},markupElemNames:['form','file','iframe','upload_progress','progress_label','progress_indicator','button','button_label','value','ack_button'],setUploadState:function(_W,_6d){if(_W!==this.uploadState){this.uploadState=_W;var _4f=_W.toString();if(this.uploadStateLabels[_4f]!==undefined){ELEM.get(this.markupElemIds.value).value=this.valueObj.id;var _T=this.uploadStateLabels[_4f];if(_W==0){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','hidden');ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');ELEM.setHTML(this.markupElemIds.button_label,_T);ELEM.setStyle(this.markupElemIds.button,'visibility','inherit');ELEM.setStyle(this.markupElemIds.form,'visibility','inherit');ELEM.setAttr(this.markupElemIds.form,'action','/U/'+_6d,true);ELEM.get(this.markupElemIds.file).value='';this.uploadKey=_6d;}
else if(_W==1||_W==2||_W==3||_W==4){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','inherit');if(_W==1||_W==2||_W==4){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','inherit');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');}
else{ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');}
ELEM.setHTML(this.markupElemIds.progress_label,_T);ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');if(_W==1){ELEM.get(this.markupElemIds.form).submit();}}
else if(_W<0){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');ELEM.setHTML(this.markupElemIds.progress_label,'<span style="color:red;">'+_T+'</span>');ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');}}}},refreshValue:function(){if(typeof this.value!='string'){return;}
if(this.value.indexOf(':::')<1){return;}
var _4e=this.value.split(':::');if(_4e.length!=2){return;}
var _W=parseInt(_4e[0],10),_6d=_4e[1];this.setUploadState(_W,_6d);},upload:function(){this.setValue('1:::'+this.uploadKey);},getNewUploadKey:function(){this.setValue('4:::'+this.uploadKey);},click:function(){if((this.uploadState==3)||(this.uploadState<0)){this.getNewUploadKey();}}});HTextArea=HTextControl.extend({componentName:"textarea"});HSlider=HControl.extend({componentName:"slider",constructor:function(_1,_g,_2){if(!_2){_2={};}
_2.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _w=Base.extend({minValue:0,maxValue:1});_w=_w.extend(_2);_2=new _w();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.refreshOnValueChange=false;this._5g='sliderknob';this._0z=false;if(!this.isinherited){this.draw();}},setValue:function(_8q){if(_8q<this.minValue){_8q=this.minValue;}
if(_8q>this.maxValue){_8q=this.maxValue;}
this.base(_8q);if(this._3M){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._7a();}
this.refresh();},startDrag:function(_5,_a){var _6=ELEM.get(this.elemId);var _5D=helmi.Element.getPageLocation(_6,true);this._7l=_5D[0];this._7m=_5D[1];this.doDrag(_5,_a);},endDrag:function(_5,_a){this.doDrag(_5,_a);},doDrag:function(_5,_a){_5-=this._7l;_a-=this._7m;_95=this._0z?_a:_5;_8q=this._7r(_95);this.setValue(_8q);},keyDown:function(_I){if((_I==Event.KEY_LEFT&&!this._0z)||(_I==Event.KEY_UP&&this._0z)){this._2j=true;this._30(-0.05);}
else if((_I==Event.KEY_RIGHT&&!this._0z)||(_I==Event.KEY_DOWN&&this._0z)){this._2j=true;this._30(0.05);}
else if(_I==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_I==Event.KEY_END){this.setValue(this.maxValue);}
else if(_I==Event.KEY_PAGEUP){this._2j=true;this._30(-0.25);}
else if(_I==Event.KEY_PAGEDOWN){this._2j=true;this._30(0.25);}},keyUp:function(_I){this._2j=false;},mouseWheel:function(_Z){var _1O;if(_Z>0){_1O=-0.05;}
else{_1O=0.05;}
_8q=(this.maxValue-this.minValue)*_1O;this.setValue(this.value+_8q);},_30:function(_1O,_1J){if(!_1J){_1J=300;}
else if(_1J==300){_1J=50;}
if(this._2j&&this.active){_8q=(this.maxValue-this.minValue)*_1O;this.setValue(this.value+_8q);var _o=this;if(this._3N){window.clearTimeout(this._3N);this._3N=null;}
this._3N=window.setTimeout(function(){_o._30(_1O,_1J);},_1J);}},_7a:function(){this._3M=this.bindDomElement(this._5g+this.elemId);this.drawKnobPos();},_4p:function(){var _7=ELEM.get(this._3M);if(this._0z){_5I=this.rect.height-parseInt(_7.offsetHeight,10);}else{_5I=this.rect.width-parseInt(_7.offsetWidth,10);}
_3L=_5I*((this.value-this.minValue)/(this.maxValue-this.minValue));_49=parseInt(_3L,10)+'px';return _49;},_7r:function(_5u){_10=this._0z?(_5u):(_5u);if(_10<0){_10=0;}
if(this._0z){if(_10>this.rect.height){_10=this.rect.height;}
return this.minValue+((_10/this.rect.height)*(this.maxValue-this.minValue));}else{if(_10>this.rect.width){_10=this.rect.width;}
return this.minValue+((_10/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_9s=this._0z?'top':'left';_47=this._4p();ELEM.setStyle(this._3M,_9s,_47);}});HVSlider=HSlider.extend({componentName:"vslider",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HVSlider]';this._5g='vsliderknob';this._0z=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!_2){_2={};}
var _w=Base.extend({value:0,minValue:0,maxValue:100});_w=_w.extend(_2);_2=new _w();this.value=_2.value;this.minValue=_2.minValue;this.maxValue=_2.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._46='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_09){this.progressFrameHeight=_09;},setProgressFrameNum:function(_34){this.progressFrames=_34;},setValue:function(_8q){this.base(_8q);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _09=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_09+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3K();}},_3K:function(){this.progressbarElemId=this.bindDomElement(this._46+this.elemId);this.drawProgress();},_4p:function(){var _3L=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _49=parseInt(Math.round(_3L),10)+'px';return _49;},drawProgress:function(){if(this.progressbarElemId){var _47=this._4p();ELEM.setStyle(this.progressbarElemId,'width',_47);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!_2){_2={};}
var _w=Base.extend({value:0,interval:20});_w=_w.extend(_2);_2=new _w();this.type='[HProgressIndicator]';this._46='progressmark';this.interval=_2.interval;this.value=_2.value;this._1v=null;if(!this.isinherited){this.draw();}},setValue:function(_8q){if(this._45){if(_8q==true&&!this._1v){var temp=this;this._1v=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._1v);this._1v=null;}}},die:function(){this.base();if(this._1v){clearInterval(this._1v);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3K();}},_3K:function(){this._45=this.bindDomElement(this._46+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._45){ELEM.setStyle(this._45,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_1,_g,_2){if(!_2){_2={};}
var _w=HClass.extend({scaleToFit:true});_2=new(_w.extend(_2))();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
if(!this.isinherited){this.draw();}},_5p:function(_36){this.elemId=ELEM.make(_36,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_5q:function(_36){this.elemId=ELEM.make(_36,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_5o:function(_36){if(this.options.scaleToFit){this._5p(_36);}
else{this._5q(_36);}},refreshValue:function(){ELEM.setAttr(this.elemId,'src',this.value);},refreshLabel:function(){ELEM.setAttr(this.elemId,'alt',this.label);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._5p(this._3F());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._5q(this._3F());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_g,_2){_2=new(Base.extend({vertical:false}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a,_L){if(!_L){return;}
_5-=this.pageX();_a-=this.pageY();var _d=this.dividers.indexOfObject(_L);this._2t=new HPoint(_5,_a);this._38=new HPoint(_5,_a);this._0t=this._2t.subtract(_L.rect.leftTop);this._0o=this.splitviews[_d];this._V=this.splitviews[_d+1];this._L=_L;if(this.vertical==false){this._2V=this._0o.rect.top;this._2W=this._V.rect.bottom-this.dividerWidth;}else{this._2V=this._0o.rect.left;this._2W=this._V.rect.right-this.dividerWidth;}},doDrag:function(_5,_a,_L){if(!_L){return;}
_5-=this.pageX();_a-=this.pageY();if(this.vertical==false){var _v=_a-this._0t.y;if(_v<this._2V||_v>this._2W){return;}
this._0o.rect.setHeight(_v);this._0o.rect.updateSecondaryValues();this._0o.setStyle('height',this._0o.rect.height+'px',true);this._L.rect.setTop(_v);this._L.rect.updateSecondaryValues();this._L.setStyle('top',this._L.rect.top+'px',true);this._V.rect.setTop(_v+this.dividerWidth);this._V.rect.updateSecondaryValues();this._V.setStyle('top',this._V.rect.top+'px',true);this._V.setStyle('height',this._V.rect.height+'px',true);}else{var _v=_5-this._0t.x;if(_v<this._2V||_v>this._2W){return;}
this._0o.rect.setRight(_v);this._0o.rect.updateSecondaryValues();this._0o.setStyle('width',this._0o.rect.width+'px',true);this._L.rect.setLeft(_v);this._L.rect.updateSecondaryValues();this._L.setStyle('left',this._L.rect.left+'px',true);this._V.rect.setLeft(_v+this.dividerWidth);this._V.rect.updateSecondaryValues();this._V.setStyle('left',this._V.rect.left+'px',true);this._V.setStyle('width',this._V.rect.width+'px',true);}},endDrag:function(_5,_a,_L){this.doDrag(_5,_a);delete this._2t;delete this._38;delete this._0t;delete this._0o;delete this._V;delete this._L;delete this._2V;delete this._2W;},addSplitViewItem:function(_0N,_d){if(_d!==undefined){this.splitviews.splice(_d,0,_0N);}else{this.splitviews.push(_0N);}},removeSplitViewItem:function(_0N){if(typeof _0N=="object"){var _d=this.splitviews.indexOfObject(_0N);if(_d!=-1){this.splitviews.splice(_d,1);_0N.die();this.dividers.splice(_d,1);this.dividers[_d].die();}}},setVertical:function(_8){this.vertical=_8;this.options.vertical=_8;},adjustViews:function(){var _0G=this.splitviews.length;var _32;var _1F;var _39;var _1K;if(this.vertical==false){_32=this.rect.height-this.dividerWidth*(_0G-1);_1F=0;for(var i=0;i<_0G;i++){_1F+=this.splitviews[i].rect.height;}
_39=_32/_1F;_1K=0;for(var i=0;i<_0G;i++){var _f=this.splitviews[i];var _1D=_f.rect.height*_39;if(i==_0G-1){_1D=Math.floor(_1D);}else{_1D=Math.ceil(_1D);}
_f.rect.offsetTo(0,_1K);_f.rect.setSize(this.rect.width,_1D);_f.draw();_1K+=_1D+this.dividerWidth;}}else{_32=this.rect.width-this.dividerWidth*(_0G-1);_1F=0;for(var i=0;i<_0G;i++){_1F+=this.splitviews[i].rect.width;}
_39=_32/_1F;_1K=0;for(var i=0;i<_0G;i++){var _f=this.splitviews[i];var _1E=_f.rect.width*_39;if(i==_0G-1){_1E=Math.floor(_1E);}else{_1E=Math.ceil(_1E);}
_f.rect.offsetTo(_1K,0);_f.rect.setSize(_1E,this.rect.height);_f.draw();_1K+=_1E+this.dividerWidth;}}
this.draw();},refresh:function(){this.base();if(this.drawn){var _0G=this.splitviews.length;var _01;for(var i=0;i<(_0G-1);i++){_01=new HRect(this.splitviews[i].rect);if(!this.vertical){_01.offsetTo(_01.left,_01.bottom);_01.setHeight(this.dividerWidth);}else{_01.offsetTo(_01.right,_01.top);_01.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_01,this);}else{var _f=this.dividers[i];_f.rect.offsetTo(_01.left,_01.top);_f.rect.setSize(_01.width,_01.height);_f.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_g,_2){if(!_2){_2={};}
_2.events={mouseDown:true,keyDown:true,mouseWheel:true};var _w=Base.extend({minValue:0,value:0,interval:500});_w=_w.extend(_2);_2=new _w();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.interval=_2.interval;this._68="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_8q){_8q--;_8q=(_8q<this.minValue)?this.maxValue:_8q;this.setValue(_8q);},stepDown:function(_8q){_8q++;_8q=(_8q>this.maxValue)?this.minValue:_8q;this.setValue(_8q);},mouseDown:function(_5,_a,_04){this.setMouseUp(true);var temp=this;if(_a<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_5,_a,_04){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_I){this.setKeyUp(true);var temp=this;if(_I==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_I==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_I){clearInterval(this.counter);},mouseWheel:function(_Z){if(_Z>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HPasswordControl=HTextControl.extend({componentName:"passwordcontrol"});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a){this.parent.startDrag(_5,_a,this);},doDrag:function(_5,_a){this.parent.doDrag(_5,_a,this);},endDrag:function(_5,_a){this.parent.endDrag(_5,_a,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HValidatorView=HControl.extend({constructor:function(_1,_m,_2){if(_2!==undefined){if(_2.valueField!==undefined){_1.offsetTo(_2.valueField.rect.right,_2.valueField.rect.top);}}
if(this.isinherited){this.base(_1,_m,_2);}
else{this.isinherited=true;this.base(_1,_m,_2);this.isinherited=false;}
if(!this.isinherited){this.draw();}},setValue:function(_8){if(null===_8||undefined===_8){_8=false;}
this.base(_8);},refresh:function(){this.base();this._8b();},_8b:function(){var _5=0,_a=0;this.setStyle('background-image',"url('"+this.getThemeGfxFile('validator.png')+"')");this.setStyle('background-repeat','no-repeat');if(this.enabled==false){_a=-21;}
if(this.value==true){_5=-21;_66='';}else{_66=this.value;}
ELEM.setAttr(this.elemId,'title',_66);this.setStyle('background-position',_5+'px '+_a+'px');}});HWindow=HDynControl.extend({componentName:'window',constructor:function(_1,_94,_2){if(_94.componentBehaviour[0]!='app'){console.log("Himle.ComponentParentError","HWindow parent must be an HApplication instance!");}
if(!_2){_2={};}
var _w=HClass.extend({minSize:[96,54],maxSize:[16000,9000],resizeW:2,resizeE:2,resizeN:2,resizeS:2,resizeNW:[2,2],resizeNE:[2,2],resizeSW:[2,2],resizeSE:[16,16],noResize:false});_2=new(_w.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
this.base(_1,_94,_2);this.windowView=this;HSystem.windowFocus(this);},gainedActiveStatus:function(){HSystem.windowFocus(this);},windowFocus:function(){this.toggleCSSClass(this.elemId,'inactive',false);this.setStyle('cursor','move');},windowBlur:function(){this.toggleCSSClass(this.elemId,'inactive',true);this.setStyle('cursor','default');}});HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _1f=this.drawn;this.base();if(!_1f){var i=0,_4h=[['overflow','auto']];for(i;i<_4h.length;i++){this.setStyle(_4h[i][0],_4h[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_1,_m,_2){this.tabInit();if(this.isinherited){this.base(_1,_m,_2);}
else{this.isinherited=true;this.base(_1,_m,_2);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_8q){this.base(_8q);if(typeof _8q=='number'){var _d=parseInt(_8q,10);if(_d<this.tabs.length){if(_d!=this.selectIdx){this.selectTab(_d);}}}},stringWidth:function(_13,_9){var _0w='<span style="'+this.fontStyle+'">'+_13+'</span>',_s=this.base(_0w,null,_9);return _s;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabLabelFillBg=false;this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_T){this.label=_T;},selectTab:function(_u){if(_u instanceof HTabView){_u=_u.tabIndex;}
if(this.selectIdx!=-1){var _60=this.tabLabels[this.selectIdx],_80=this.tabs[this.selectIdx];ELEM.removeClassName(_60,'item-fg');ELEM.addClassName(_60,'item-bg');HSystem.views[_80].hide();}
if(_u!=-1){var _0h=this.tabLabels[_u],_4i=this.tabs[_u];ELEM.removeClassName(_0h,'item-bg');ELEM.addClassName(_0h,'item-fg');HSystem.views[_4i].show();}
this.selectIdx=_u;this.setValue(_u);},addTab:function(_3b,_8C){var _u=this.tabs.length,_5Z='',_7f=this.stringWidth(_3b,0),_3P=_7f+this.tabLabelLeftEdge+this.tabLabelRightEdge,_1M=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_u=this.tabs.length,_0h=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);if(this.tabLabelNoHTMLPrefix){_5Z=_3b;}
else{_5Z=this.tabLabelHTMLPrefix1+_7f+this.tabLabelHTMLPrefix2+_3b+this.tabLabelHTMLSuffix;}
_1M.hide();ELEM.addClassName(_0h,'item-bg');ELEM.setStyle(_0h,'width',_3P+'px');ELEM.setStyle(_0h,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_0h,_5Z);this.tabLabelStrings.push(_3b);if(this.tabTriggerLink&&this.tabLabelElementTagName=='a'){ELEM.setAttr(_0h,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_u+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_0h,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_u+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_3P]);}
this.rightmostPx+=_3P;if(this.tabLabelAlign=='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
else if(this.tabLabelFillBg){ELEM.setStyle(this.markupElemIds.state,'left',this.rightmostPx+'px');}
this.tabs.push(_1M.viewId);this.tabLabels.push(_0h);_1M.tabIndex=_u;if(_8C){this.selectTab(_u);}
return _1M;},mouseDown:function(_5,_a){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_5-=this.pageX();_a-=this.pageY();if(_a<=this.tabLabelHeight){if(this.tabLabelAlign=='right'){_5=this.rect.width-_5;}
if(_5<=this.rightmostPx){var i=0,_5h;for(i;i<this.tabLabelBounds.length;i++){_5h=this.tabLabelBounds[i];if(_5<_5h[1]&&_5>=_5h[0]){this.selectTab(i);return;}}}}},removeTab:function(_u){var _7H=this.selectIdx,_4i=this.tabs[_u],_0h=this.tabViews[_u];this.tabs.splice(_u,1);this.tabLabels.splice(_u,1);this.tabLabelBounds.splice(_u,1);this.tabLabelStrings.splice(_u,1);if(_u==_7H){this.selectIdx=-1;if(_u==0&&this.tabs.length==0){this.selectTab(-1);}
else if(_u==(this.tabs.length-1)){this.selectTab(_u-1);}
else{this.selectTab(_u);}}
else if(_u<_7H){this.selectIdx--;}
ELEM.del(_0h);HSystem.views[_4i].die();},draw:function(){var _1f=this.drawn;this.base();if(!_1f){this.drawMarkup();}
this.refresh();}});HImageButton=HControl.extend({componentName:"imagebutton",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.styleButtonDefaults=new(Base.extend({image:this.getThemeGfxPath()+"blank.gif",alternateImage:""}).extend(_2));this._0X=this.getThemeGfxPath()+this.styleButtonDefaults.image;this._4w=this.getThemeGfxPath()+this.styleButtonDefaults.alternateImage;this.type='[HImageButton]';this.preserveTheme=true;this.setMouseUp(true);if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},_8a:function(){if(!this.value){ELEM.get(this._2S).src=this._0X;}else{if(this._4w){ELEM.get(this._2S).src=this._4w;}}},refresh:function(){if(this.drawn){this.base();if(!this._2S){this._2S=this.bindDomElement(HImageButton._67+this.elemId);}
if(this._2S){this._8a();}}},mouseUp:function(_5,_a,_04){this.setValue(!this.value);}},{_67:"imagebutton"});HButton=HControl.extend({componentName:'button'});HCheckbox=HButton.extend({componentName:'checkbox',constructor:function(_1,_m,_2){this.base(_1,_m,_2);this.setClickable(true);},click:function(){this.setValue(!this.value);},refreshValue:function(){if(this.markupElemIds.control){if(this.value){this.toggleCSSClass(this.markupElemIds.control,'checked',true);this.toggleCSSClass(this.markupElemIds.control,'unchecked',false);}
else{this.toggleCSSClass(this.markupElemIds.control,'checked',false);this.toggleCSSClass(this.markupElemIds.control,'unchecked',true);}}}});HCheckBox=HCheckbox;HRadioButton=(HCheckbox.extend(HValueMatrixComponentExtension)).extend({componentName:'radiobutton'});HRadiobutton=HRadioButton;HStringView=HControl.extend({componentName:"stringview",componentBehaviour:['view','control','text'],refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'title',this.label);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_g,_2){this.base(_1,_g,_2);this.setTextEnter(true);},setEnabled:function(_8){this.base(_8);if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).value=this.value;}}},textEnter:function(){if(this['markupElemIds']===undefined){return;}
var _8q=ELEM.get(this.markupElemIds.value).value;if(_8q!=this.value){this.setValue(_8q);}}});HUploader=HControl.extend({componentName:'uploader',uploadState:false,uploadKey:false,uploadStateLabels:{'0':"Select file...",'1':"Uploading...",'2':"Processing data...",'3':"Upload Complete",'4':"Preparing upload",'-1':"Error: Invalid request",'-2':"Error: Invalid upload key",'-3':"Error: Invalid data format",'-4':"Error: File too big",'-6':"Error: Post-processing failed"},markupElemNames:['form','file','iframe','upload_progress','progress_label','progress_indicator','button','button_label','value','ack_button'],setUploadState:function(_W,_6d){if(_W!==this.uploadState){this.uploadState=_W;var _4f=_W.toString();if(this.uploadStateLabels[_4f]!==undefined){ELEM.get(this.markupElemIds.value).value=this.valueObj.id;var _T=this.uploadStateLabels[_4f];if(_W==0){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','hidden');ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');ELEM.setHTML(this.markupElemIds.button_label,_T);ELEM.setStyle(this.markupElemIds.button,'visibility','inherit');ELEM.setStyle(this.markupElemIds.form,'visibility','inherit');ELEM.setAttr(this.markupElemIds.form,'action','/U/'+_6d,true);ELEM.get(this.markupElemIds.file).value='';this.uploadKey=_6d;}
else if(_W==1||_W==2||_W==3||_W==4){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','inherit');if(_W==1||_W==2||_W==4){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','inherit');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');}
else{ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');}
ELEM.setHTML(this.markupElemIds.progress_label,_T);ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');if(_W==1){ELEM.get(this.markupElemIds.form).submit();}}
else if(_W<0){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');ELEM.setHTML(this.markupElemIds.progress_label,'<span style="color:red;">'+_T+'</span>');ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');}}}},refreshValue:function(){if(typeof this.value!='string'){return;}
if(this.value.indexOf(':::')<1){return;}
var _4e=this.value.split(':::');if(_4e.length!=2){return;}
var _W=parseInt(_4e[0],10),_6d=_4e[1];this.setUploadState(_W,_6d);},upload:function(){this.setValue('1:::'+this.uploadKey);},getNewUploadKey:function(){this.setValue('4:::'+this.uploadKey);},click:function(){if((this.uploadState==3)||(this.uploadState<0)){this.getNewUploadKey();}}});HTextArea=HTextControl.extend({componentName:"textarea"});HSlider=HControl.extend({componentName:"slider",constructor:function(_1,_g,_2){if(!_2){_2={};}
_2.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _w=Base.extend({minValue:0,maxValue:1});_w=_w.extend(_2);_2=new _w();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.refreshOnValueChange=false;this._5g='sliderknob';this._0z=false;if(!this.isinherited){this.draw();}},setValue:function(_8q){if(_8q<this.minValue){_8q=this.minValue;}
if(_8q>this.maxValue){_8q=this.maxValue;}
this.base(_8q);if(this._3M){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._7a();}
this.refresh();},startDrag:function(_5,_a){var _6=ELEM.get(this.elemId);var _5D=helmi.Element.getPageLocation(_6,true);this._7l=_5D[0];this._7m=_5D[1];this.doDrag(_5,_a);},endDrag:function(_5,_a){this.doDrag(_5,_a);},doDrag:function(_5,_a){_5-=this._7l;_a-=this._7m;_95=this._0z?_a:_5;_8q=this._7r(_95);this.setValue(_8q);},keyDown:function(_I){if((_I==Event.KEY_LEFT&&!this._0z)||(_I==Event.KEY_UP&&this._0z)){this._2j=true;this._30(-0.05);}
else if((_I==Event.KEY_RIGHT&&!this._0z)||(_I==Event.KEY_DOWN&&this._0z)){this._2j=true;this._30(0.05);}
else if(_I==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_I==Event.KEY_END){this.setValue(this.maxValue);}
else if(_I==Event.KEY_PAGEUP){this._2j=true;this._30(-0.25);}
else if(_I==Event.KEY_PAGEDOWN){this._2j=true;this._30(0.25);}},keyUp:function(_I){this._2j=false;},mouseWheel:function(_Z){var _1O;if(_Z>0){_1O=-0.05;}
else{_1O=0.05;}
_8q=(this.maxValue-this.minValue)*_1O;this.setValue(this.value+_8q);},_30:function(_1O,_1J){if(!_1J){_1J=300;}
else if(_1J==300){_1J=50;}
if(this._2j&&this.active){_8q=(this.maxValue-this.minValue)*_1O;this.setValue(this.value+_8q);var _o=this;if(this._3N){window.clearTimeout(this._3N);this._3N=null;}
this._3N=window.setTimeout(function(){_o._30(_1O,_1J);},_1J);}},_7a:function(){this._3M=this.bindDomElement(this._5g+this.elemId);this.drawKnobPos();},_4p:function(){var _7=ELEM.get(this._3M);if(this._0z){_5I=this.rect.height-parseInt(_7.offsetHeight,10);}else{_5I=this.rect.width-parseInt(_7.offsetWidth,10);}
_3L=_5I*((this.value-this.minValue)/(this.maxValue-this.minValue));_49=parseInt(_3L,10)+'px';return _49;},_7r:function(_5u){_10=this._0z?(_5u):(_5u);if(_10<0){_10=0;}
if(this._0z){if(_10>this.rect.height){_10=this.rect.height;}
return this.minValue+((_10/this.rect.height)*(this.maxValue-this.minValue));}else{if(_10>this.rect.width){_10=this.rect.width;}
return this.minValue+((_10/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_9s=this._0z?'top':'left';_47=this._4p();ELEM.setStyle(this._3M,_9s,_47);}});HVSlider=HSlider.extend({componentName:"vslider",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HVSlider]';this._5g='vsliderknob';this._0z=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!_2){_2={};}
var _w=Base.extend({value:0,minValue:0,maxValue:100});_w=_w.extend(_2);_2=new _w();this.value=_2.value;this.minValue=_2.minValue;this.maxValue=_2.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._46='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_09){this.progressFrameHeight=_09;},setProgressFrameNum:function(_34){this.progressFrames=_34;},setValue:function(_8q){this.base(_8q);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _09=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_09+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3K();}},_3K:function(){this.progressbarElemId=this.bindDomElement(this._46+this.elemId);this.drawProgress();},_4p:function(){var _3L=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _49=parseInt(Math.round(_3L),10)+'px';return _49;},drawProgress:function(){if(this.progressbarElemId){var _47=this._4p();ELEM.setStyle(this.progressbarElemId,'width',_47);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!_2){_2={};}
var _w=Base.extend({value:0,interval:20});_w=_w.extend(_2);_2=new _w();this.type='[HProgressIndicator]';this._46='progressmark';this.interval=_2.interval;this.value=_2.value;this._1v=null;if(!this.isinherited){this.draw();}},setValue:function(_8q){if(this._45){if(_8q==true&&!this._1v){var temp=this;this._1v=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._1v);this._1v=null;}}},die:function(){this.base();if(this._1v){clearInterval(this._1v);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3K();}},_3K:function(){this._45=this.bindDomElement(this._46+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._45){ELEM.setStyle(this._45,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_1,_g,_2){if(!_2){_2={};}
var _w=HClass.extend({scaleToFit:true});_2=new(_w.extend(_2))();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
if(!this.isinherited){this.draw();}},_5p:function(_36){this.elemId=ELEM.make(_36,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_5q:function(_36){this.elemId=ELEM.make(_36,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_5o:function(_36){if(this.options.scaleToFit){this._5p(_36);}
else{this._5q(_36);}},refreshValue:function(){ELEM.setAttr(this.elemId,'src',this.value);},refreshLabel:function(){ELEM.setAttr(this.elemId,'alt',this.label);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._5p(this._3F());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._5q(this._3F());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_g,_2){_2=new(Base.extend({vertical:false}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a,_L){if(!_L){return;}
_5-=this.pageX();_a-=this.pageY();var _d=this.dividers.indexOfObject(_L);this._2t=new HPoint(_5,_a);this._38=new HPoint(_5,_a);this._0t=this._2t.subtract(_L.rect.leftTop);this._0o=this.splitviews[_d];this._V=this.splitviews[_d+1];this._L=_L;if(this.vertical==false){this._2V=this._0o.rect.top;this._2W=this._V.rect.bottom-this.dividerWidth;}else{this._2V=this._0o.rect.left;this._2W=this._V.rect.right-this.dividerWidth;}},doDrag:function(_5,_a,_L){if(!_L){return;}
_5-=this.pageX();_a-=this.pageY();if(this.vertical==false){var _v=_a-this._0t.y;if(_v<this._2V||_v>this._2W){return;}
this._0o.rect.setHeight(_v);this._0o.rect.updateSecondaryValues();this._0o.setStyle('height',this._0o.rect.height+'px',true);this._L.rect.setTop(_v);this._L.rect.updateSecondaryValues();this._L.setStyle('top',this._L.rect.top+'px',true);this._V.rect.setTop(_v+this.dividerWidth);this._V.rect.updateSecondaryValues();this._V.setStyle('top',this._V.rect.top+'px',true);this._V.setStyle('height',this._V.rect.height+'px',true);}else{var _v=_5-this._0t.x;if(_v<this._2V||_v>this._2W){return;}
this._0o.rect.setRight(_v);this._0o.rect.updateSecondaryValues();this._0o.setStyle('width',this._0o.rect.width+'px',true);this._L.rect.setLeft(_v);this._L.rect.updateSecondaryValues();this._L.setStyle('left',this._L.rect.left+'px',true);this._V.rect.setLeft(_v+this.dividerWidth);this._V.rect.updateSecondaryValues();this._V.setStyle('left',this._V.rect.left+'px',true);this._V.setStyle('width',this._V.rect.width+'px',true);}},endDrag:function(_5,_a,_L){this.doDrag(_5,_a);delete this._2t;delete this._38;delete this._0t;delete this._0o;delete this._V;delete this._L;delete this._2V;delete this._2W;},addSplitViewItem:function(_0N,_d){if(_d!==undefined){this.splitviews.splice(_d,0,_0N);}else{this.splitviews.push(_0N);}},removeSplitViewItem:function(_0N){if(typeof _0N=="object"){var _d=this.splitviews.indexOfObject(_0N);if(_d!=-1){this.splitviews.splice(_d,1);_0N.die();this.dividers.splice(_d,1);this.dividers[_d].die();}}},setVertical:function(_8){this.vertical=_8;this.options.vertical=_8;},adjustViews:function(){var _0G=this.splitviews.length;var _32;var _1F;var _39;var _1K;if(this.vertical==false){_32=this.rect.height-this.dividerWidth*(_0G-1);_1F=0;for(var i=0;i<_0G;i++){_1F+=this.splitviews[i].rect.height;}
_39=_32/_1F;_1K=0;for(var i=0;i<_0G;i++){var _f=this.splitviews[i];var _1D=_f.rect.height*_39;if(i==_0G-1){_1D=Math.floor(_1D);}else{_1D=Math.ceil(_1D);}
_f.rect.offsetTo(0,_1K);_f.rect.setSize(this.rect.width,_1D);_f.draw();_1K+=_1D+this.dividerWidth;}}else{_32=this.rect.width-this.dividerWidth*(_0G-1);_1F=0;for(var i=0;i<_0G;i++){_1F+=this.splitviews[i].rect.width;}
_39=_32/_1F;_1K=0;for(var i=0;i<_0G;i++){var _f=this.splitviews[i];var _1E=_f.rect.width*_39;if(i==_0G-1){_1E=Math.floor(_1E);}else{_1E=Math.ceil(_1E);}
_f.rect.offsetTo(_1K,0);_f.rect.setSize(_1E,this.rect.height);_f.draw();_1K+=_1E+this.dividerWidth;}}
this.draw();},refresh:function(){this.base();if(this.drawn){var _0G=this.splitviews.length;var _01;for(var i=0;i<(_0G-1);i++){_01=new HRect(this.splitviews[i].rect);if(!this.vertical){_01.offsetTo(_01.left,_01.bottom);_01.setHeight(this.dividerWidth);}else{_01.offsetTo(_01.right,_01.top);_01.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_01,this);}else{var _f=this.dividers[i];_f.rect.offsetTo(_01.left,_01.top);_f.rect.setSize(_01.width,_01.height);_f.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_g,_2){if(!_2){_2={};}
_2.events={mouseDown:true,keyDown:true,mouseWheel:true};var _w=Base.extend({minValue:0,value:0,interval:500});_w=_w.extend(_2);_2=new _w();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.interval=_2.interval;this._68="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_8q){_8q--;_8q=(_8q<this.minValue)?this.maxValue:_8q;this.setValue(_8q);},stepDown:function(_8q){_8q++;_8q=(_8q>this.maxValue)?this.minValue:_8q;this.setValue(_8q);},mouseDown:function(_5,_a,_04){this.setMouseUp(true);var temp=this;if(_a<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_5,_a,_04){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_I){this.setKeyUp(true);var temp=this;if(_I==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_I==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_I){clearInterval(this.counter);},mouseWheel:function(_Z){if(_Z>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HPasswordControl=HTextControl.extend({componentName:"passwordcontrol"});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a){this.parent.startDrag(_5,_a,this);},doDrag:function(_5,_a){this.parent.doDrag(_5,_a,this);},endDrag:function(_5,_a){this.parent.endDrag(_5,_a,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HValidatorView=HControl.extend({constructor:function(_1,_m,_2){if(_2!==undefined){if(_2.valueField!==undefined){_1.offsetTo(_2.valueField.rect.right,_2.valueField.rect.top);}}
if(this.isinherited){this.base(_1,_m,_2);}
else{this.isinherited=true;this.base(_1,_m,_2);this.isinherited=false;}
if(!this.isinherited){this.draw();}},setValue:function(_8){if(null===_8||undefined===_8){_8=false;}
this.base(_8);},refresh:function(){this.base();this._8b();},_8b:function(){var _5=0,_a=0;this.setStyle('background-image',"url('"+this.getThemeGfxFile('validator.png')+"')");this.setStyle('background-repeat','no-repeat');if(this.enabled==false){_a=-21;}
if(this.value==true){_5=-21;_66='';}else{_66=this.value;}
ELEM.setAttr(this.elemId,'title',_66);this.setStyle('background-position',_5+'px '+_a+'px');}});HWindow=HDynControl.extend({componentName:'window',constructor:function(_1,_94,_2){if(_94.componentBehaviour[0]!='app'){console.log("Himle.ComponentParentError","HWindow parent must be an HApplication instance!");}
if(!_2){_2={};}
var _w=HClass.extend({minSize:[96,54],maxSize:[16000,9000],resizeW:2,resizeE:2,resizeN:2,resizeS:2,resizeNW:[2,2],resizeNE:[2,2],resizeSW:[2,2],resizeSE:[16,16],noResize:false});_2=new(_w.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
this.base(_1,_94,_2);this.windowView=this;HSystem.windowFocus(this);},gainedActiveStatus:function(){HSystem.windowFocus(this);},windowFocus:function(){this.toggleCSSClass(this.elemId,'inactive',false);this.setStyle('cursor','move');},windowBlur:function(){this.toggleCSSClass(this.elemId,'inactive',true);this.setStyle('cursor','default');}});HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _1f=this.drawn;this.base();if(!_1f){var i=0,_4h=[['overflow','auto']];for(i;i<_4h.length;i++){this.setStyle(_4h[i][0],_4h[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_1,_m,_2){this.tabInit();if(this.isinherited){this.base(_1,_m,_2);}
else{this.isinherited=true;this.base(_1,_m,_2);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_8q){this.base(_8q);if(typeof _8q=='number'){var _d=parseInt(_8q,10);if(_d<this.tabs.length){if(_d!=this.selectIdx){this.selectTab(_d);}}}},stringWidth:function(_13,_9){var _0w='<span style="'+this.fontStyle+'">'+_13+'</span>',_s=this.base(_0w,null,_9);return _s;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabLabelFillBg=false;this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_T){this.label=_T;},selectTab:function(_u){if(_u instanceof HTabView){_u=_u.tabIndex;}
if(this.selectIdx!=-1){var _60=this.tabLabels[this.selectIdx],_80=this.tabs[this.selectIdx];ELEM.removeClassName(_60,'item-fg');ELEM.addClassName(_60,'item-bg');HSystem.views[_80].hide();}
if(_u!=-1){var _0h=this.tabLabels[_u],_4i=this.tabs[_u];ELEM.removeClassName(_0h,'item-bg');ELEM.addClassName(_0h,'item-fg');HSystem.views[_4i].show();}
this.selectIdx=_u;this.setValue(_u);},addTab:function(_3b,_8C){var _u=this.tabs.length,_5Z='',_7f=this.stringWidth(_3b,0),_3P=_7f+this.tabLabelLeftEdge+this.tabLabelRightEdge,_1M=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_u=this.tabs.length,_0h=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);if(this.tabLabelNoHTMLPrefix){_5Z=_3b;}
else{_5Z=this.tabLabelHTMLPrefix1+_7f+this.tabLabelHTMLPrefix2+_3b+this.tabLabelHTMLSuffix;}
_1M.hide();ELEM.addClassName(_0h,'item-bg');ELEM.setStyle(_0h,'width',_3P+'px');ELEM.setStyle(_0h,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_0h,_5Z);this.tabLabelStrings.push(_3b);if(this.tabTriggerLink&&this.tabLabelElementTagName=='a'){ELEM.setAttr(_0h,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_u+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_0h,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_u+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_3P]);}
this.rightmostPx+=_3P;if(this.tabLabelAlign=='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
else if(this.tabLabelFillBg){ELEM.setStyle(this.markupElemIds.state,'left',this.rightmostPx+'px');}
this.tabs.push(_1M.viewId);this.tabLabels.push(_0h);_1M.tabIndex=_u;if(_8C){this.selectTab(_u);}
return _1M;},mouseDown:function(_5,_a){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_5-=this.pageX();_a-=this.pageY();if(_a<=this.tabLabelHeight){if(this.tabLabelAlign=='right'){_5=this.rect.width-_5;}
if(_5<=this.rightmostPx){var i=0,_5h;for(i;i<this.tabLabelBounds.length;i++){_5h=this.tabLabelBounds[i];if(_5<_5h[1]&&_5>=_5h[0]){this.selectTab(i);return;}}}}},removeTab:function(_u){var _7H=this.selectIdx,_4i=this.tabs[_u],_0h=this.tabViews[_u];this.tabs.splice(_u,1);this.tabLabels.splice(_u,1);this.tabLabelBounds.splice(_u,1);this.tabLabelStrings.splice(_u,1);if(_u==_7H){this.selectIdx=-1;if(_u==0&&this.tabs.length==0){this.selectTab(-1);}
else if(_u==(this.tabs.length-1)){this.selectTab(_u-1);}
else{this.selectTab(_u);}}
else if(_u<_7H){this.selectIdx--;}
ELEM.del(_0h);HSystem.views[_4i].die();},draw:function(){var _1f=this.drawn;this.base();if(!_1f){this.drawMarkup();}
this.refresh();}});HImageButton=HControl.extend({componentName:"imagebutton",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.styleButtonDefaults=new(Base.extend({image:this.getThemeGfxPath()+"blank.gif",alternateImage:""}).extend(_2));this._0X=this.getThemeGfxPath()+this.styleButtonDefaults.image;this._4w=this.getThemeGfxPath()+this.styleButtonDefaults.alternateImage;this.type='[HImageButton]';this.preserveTheme=true;this.setMouseUp(true);if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},_8a:function(){if(!this.value){ELEM.get(this._2S).src=this._0X;}else{if(this._4w){ELEM.get(this._2S).src=this._4w;}}},refresh:function(){if(this.drawn){this.base();if(!this._2S){this._2S=this.bindDomElement(HImageButton._67+this.elemId);}
if(this._2S){this._8a();}}},mouseUp:function(_5,_a,_04){this.setValue(!this.value);}},{_67:"imagebutton"});HButton=HControl.extend({componentName:'button'});HCheckbox=HButton.extend({componentName:'checkbox',constructor:function(_1,_m,_2){this.base(_1,_m,_2);this.setClickable(true);},click:function(){this.setValue(!this.value);},refreshValue:function(){if(this.markupElemIds.control){if(this.value){this.toggleCSSClass(this.markupElemIds.control,'checked',true);this.toggleCSSClass(this.markupElemIds.control,'unchecked',false);}
else{this.toggleCSSClass(this.markupElemIds.control,'checked',false);this.toggleCSSClass(this.markupElemIds.control,'unchecked',true);}}}});HCheckBox=HCheckbox;HRadioButton=(HCheckbox.extend(HValueMatrixComponentExtension)).extend({componentName:'radiobutton'});HRadiobutton=HRadioButton;HStringView=HControl.extend({componentName:"stringview",componentBehaviour:['view','control','text'],refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'title',this.label);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_g,_2){this.base(_1,_g,_2);this.setTextEnter(true);},setEnabled:function(_8){this.base(_8);if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).value=this.value;}}},textEnter:function(){if(this['markupElemIds']===undefined){return;}
var _8q=ELEM.get(this.markupElemIds.value).value;if(_8q!=this.value){this.setValue(_8q);}}});HUploader=HControl.extend({componentName:'uploader',uploadState:false,uploadKey:false,uploadStateLabels:{'0':"Select file...",'1':"Uploading...",'2':"Processing data...",'3':"Upload Complete",'4':"Preparing upload",'-1':"Error: Invalid request",'-2':"Error: Invalid upload key",'-3':"Error: Invalid data format",'-4':"Error: File too big",'-6':"Error: Post-processing failed"},markupElemNames:['form','file','iframe','upload_progress','progress_label','progress_indicator','button','button_label','value','ack_button'],setUploadState:function(_W,_6d){if(_W!==this.uploadState){this.uploadState=_W;var _4f=_W.toString();if(this.uploadStateLabels[_4f]!==undefined){ELEM.get(this.markupElemIds.value).value=this.valueObj.id;var _T=this.uploadStateLabels[_4f];if(_W==0){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','hidden');ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');ELEM.setHTML(this.markupElemIds.button_label,_T);ELEM.setStyle(this.markupElemIds.button,'visibility','inherit');ELEM.setStyle(this.markupElemIds.form,'visibility','inherit');ELEM.setAttr(this.markupElemIds.form,'action','/U/'+_6d,true);ELEM.get(this.markupElemIds.file).value='';this.uploadKey=_6d;}
else if(_W==1||_W==2||_W==3||_W==4){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','inherit');if(_W==1||_W==2||_W==4){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','inherit');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');}
else{ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');}
ELEM.setHTML(this.markupElemIds.progress_label,_T);ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');if(_W==1){ELEM.get(this.markupElemIds.form).submit();}}
else if(_W<0){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');ELEM.setHTML(this.markupElemIds.progress_label,'<span style="color:red;">'+_T+'</span>');ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');}}}},refreshValue:function(){if(typeof this.value!='string'){return;}
if(this.value.indexOf(':::')<1){return;}
var _4e=this.value.split(':::');if(_4e.length!=2){return;}
var _W=parseInt(_4e[0],10),_6d=_4e[1];this.setUploadState(_W,_6d);},upload:function(){this.setValue('1:::'+this.uploadKey);},getNewUploadKey:function(){this.setValue('4:::'+this.uploadKey);},click:function(){if((this.uploadState==3)||(this.uploadState<0)){this.getNewUploadKey();}}});HTextArea=HTextControl.extend({componentName:"textarea"});HSlider=HControl.extend({componentName:"slider",constructor:function(_1,_g,_2){if(!_2){_2={};}
_2.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _w=Base.extend({minValue:0,maxValue:1});_w=_w.extend(_2);_2=new _w();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.refreshOnValueChange=false;this._5g='sliderknob';this._0z=false;if(!this.isinherited){this.draw();}},setValue:function(_8q){if(_8q<this.minValue){_8q=this.minValue;}
if(_8q>this.maxValue){_8q=this.maxValue;}
this.base(_8q);if(this._3M){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._7a();}
this.refresh();},startDrag:function(_5,_a){var _6=ELEM.get(this.elemId);var _5D=helmi.Element.getPageLocation(_6,true);this._7l=_5D[0];this._7m=_5D[1];this.doDrag(_5,_a);},endDrag:function(_5,_a){this.doDrag(_5,_a);},doDrag:function(_5,_a){_5-=this._7l;_a-=this._7m;_95=this._0z?_a:_5;_8q=this._7r(_95);this.setValue(_8q);},keyDown:function(_I){if((_I==Event.KEY_LEFT&&!this._0z)||(_I==Event.KEY_UP&&this._0z)){this._2j=true;this._30(-0.05);}
else if((_I==Event.KEY_RIGHT&&!this._0z)||(_I==Event.KEY_DOWN&&this._0z)){this._2j=true;this._30(0.05);}
else if(_I==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_I==Event.KEY_END){this.setValue(this.maxValue);}
else if(_I==Event.KEY_PAGEUP){this._2j=true;this._30(-0.25);}
else if(_I==Event.KEY_PAGEDOWN){this._2j=true;this._30(0.25);}},keyUp:function(_I){this._2j=false;},mouseWheel:function(_Z){var _1O;if(_Z>0){_1O=-0.05;}
else{_1O=0.05;}
_8q=(this.maxValue-this.minValue)*_1O;this.setValue(this.value+_8q);},_30:function(_1O,_1J){if(!_1J){_1J=300;}
else if(_1J==300){_1J=50;}
if(this._2j&&this.active){_8q=(this.maxValue-this.minValue)*_1O;this.setValue(this.value+_8q);var _o=this;if(this._3N){window.clearTimeout(this._3N);this._3N=null;}
this._3N=window.setTimeout(function(){_o._30(_1O,_1J);},_1J);}},_7a:function(){this._3M=this.bindDomElement(this._5g+this.elemId);this.drawKnobPos();},_4p:function(){var _7=ELEM.get(this._3M);if(this._0z){_5I=this.rect.height-parseInt(_7.offsetHeight,10);}else{_5I=this.rect.width-parseInt(_7.offsetWidth,10);}
_3L=_5I*((this.value-this.minValue)/(this.maxValue-this.minValue));_49=parseInt(_3L,10)+'px';return _49;},_7r:function(_5u){_10=this._0z?(_5u):(_5u);if(_10<0){_10=0;}
if(this._0z){if(_10>this.rect.height){_10=this.rect.height;}
return this.minValue+((_10/this.rect.height)*(this.maxValue-this.minValue));}else{if(_10>this.rect.width){_10=this.rect.width;}
return this.minValue+((_10/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_9s=this._0z?'top':'left';_47=this._4p();ELEM.setStyle(this._3M,_9s,_47);}});HVSlider=HSlider.extend({componentName:"vslider",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HVSlider]';this._5g='vsliderknob';this._0z=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!_2){_2={};}
var _w=Base.extend({value:0,minValue:0,maxValue:100});_w=_w.extend(_2);_2=new _w();this.value=_2.value;this.minValue=_2.minValue;this.maxValue=_2.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._46='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_09){this.progressFrameHeight=_09;},setProgressFrameNum:function(_34){this.progressFrames=_34;},setValue:function(_8q){this.base(_8q);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _09=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_09+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3K();}},_3K:function(){this.progressbarElemId=this.bindDomElement(this._46+this.elemId);this.drawProgress();},_4p:function(){var _3L=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _49=parseInt(Math.round(_3L),10)+'px';return _49;},drawProgress:function(){if(this.progressbarElemId){var _47=this._4p();ELEM.setStyle(this.progressbarElemId,'width',_47);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!_2){_2={};}
var _w=Base.extend({value:0,interval:20});_w=_w.extend(_2);_2=new _w();this.type='[HProgressIndicator]';this._46='progressmark';this.interval=_2.interval;this.value=_2.value;this._1v=null;if(!this.isinherited){this.draw();}},setValue:function(_8q){if(this._45){if(_8q==true&&!this._1v){var temp=this;this._1v=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._1v);this._1v=null;}}},die:function(){this.base();if(this._1v){clearInterval(this._1v);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3K();}},_3K:function(){this._45=this.bindDomElement(this._46+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._45){ELEM.setStyle(this._45,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_1,_g,_2){if(!_2){_2={};}
var _w=HClass.extend({scaleToFit:true});_2=new(_w.extend(_2))();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
if(!this.isinherited){this.draw();}},_5p:function(_36){this.elemId=ELEM.make(_36,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_5q:function(_36){this.elemId=ELEM.make(_36,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_5o:function(_36){if(this.options.scaleToFit){this._5p(_36);}
else{this._5q(_36);}},refreshValue:function(){ELEM.setAttr(this.elemId,'src',this.value);},refreshLabel:function(){ELEM.setAttr(this.elemId,'alt',this.label);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._5p(this._3F());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._5q(this._3F());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_g,_2){_2=new(Base.extend({vertical:false}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a,_L){if(!_L){return;}
_5-=this.pageX();_a-=this.pageY();var _d=this.dividers.indexOfObject(_L);this._2t=new HPoint(_5,_a);this._38=new HPoint(_5,_a);this._0t=this._2t.subtract(_L.rect.leftTop);this._0o=this.splitviews[_d];this._V=this.splitviews[_d+1];this._L=_L;if(this.vertical==false){this._2V=this._0o.rect.top;this._2W=this._V.rect.bottom-this.dividerWidth;}else{this._2V=this._0o.rect.left;this._2W=this._V.rect.right-this.dividerWidth;}},doDrag:function(_5,_a,_L){if(!_L){return;}
_5-=this.pageX();_a-=this.pageY();if(this.vertical==false){var _v=_a-this._0t.y;if(_v<this._2V||_v>this._2W){return;}
this._0o.rect.setHeight(_v);this._0o.rect.updateSecondaryValues();this._0o.setStyle('height',this._0o.rect.height+'px',true);this._L.rect.setTop(_v);this._L.rect.updateSecondaryValues();this._L.setStyle('top',this._L.rect.top+'px',true);this._V.rect.setTop(_v+this.dividerWidth);this._V.rect.updateSecondaryValues();this._V.setStyle('top',this._V.rect.top+'px',true);this._V.setStyle('height',this._V.rect.height+'px',true);}else{var _v=_5-this._0t.x;if(_v<this._2V||_v>this._2W){return;}
this._0o.rect.setRight(_v);this._0o.rect.updateSecondaryValues();this._0o.setStyle('width',this._0o.rect.width+'px',true);this._L.rect.setLeft(_v);this._L.rect.updateSecondaryValues();this._L.setStyle('left',this._L.rect.left+'px',true);this._V.rect.setLeft(_v+this.dividerWidth);this._V.rect.updateSecondaryValues();this._V.setStyle('left',this._V.rect.left+'px',true);this._V.setStyle('width',this._V.rect.width+'px',true);}},endDrag:function(_5,_a,_L){this.doDrag(_5,_a);delete this._2t;delete this._38;delete this._0t;delete this._0o;delete this._V;delete this._L;delete this._2V;delete this._2W;},addSplitViewItem:function(_0N,_d){if(_d!==undefined){this.splitviews.splice(_d,0,_0N);}else{this.splitviews.push(_0N);}},removeSplitViewItem:function(_0N){if(typeof _0N=="object"){var _d=this.splitviews.indexOfObject(_0N);if(_d!=-1){this.splitviews.splice(_d,1);_0N.die();this.dividers.splice(_d,1);this.dividers[_d].die();}}},setVertical:function(_8){this.vertical=_8;this.options.vertical=_8;},adjustViews:function(){var _0G=this.splitviews.length;var _32;var _1F;var _39;var _1K;if(this.vertical==false){_32=this.rect.height-this.dividerWidth*(_0G-1);_1F=0;for(var i=0;i<_0G;i++){_1F+=this.splitviews[i].rect.height;}
_39=_32/_1F;_1K=0;for(var i=0;i<_0G;i++){var _f=this.splitviews[i];var _1D=_f.rect.height*_39;if(i==_0G-1){_1D=Math.floor(_1D);}else{_1D=Math.ceil(_1D);}
_f.rect.offsetTo(0,_1K);_f.rect.setSize(this.rect.width,_1D);_f.draw();_1K+=_1D+this.dividerWidth;}}else{_32=this.rect.width-this.dividerWidth*(_0G-1);_1F=0;for(var i=0;i<_0G;i++){_1F+=this.splitviews[i].rect.width;}
_39=_32/_1F;_1K=0;for(var i=0;i<_0G;i++){var _f=this.splitviews[i];var _1E=_f.rect.width*_39;if(i==_0G-1){_1E=Math.floor(_1E);}else{_1E=Math.ceil(_1E);}
_f.rect.offsetTo(_1K,0);_f.rect.setSize(_1E,this.rect.height);_f.draw();_1K+=_1E+this.dividerWidth;}}
this.draw();},refresh:function(){this.base();if(this.drawn){var _0G=this.splitviews.length;var _01;for(var i=0;i<(_0G-1);i++){_01=new HRect(this.splitviews[i].rect);if(!this.vertical){_01.offsetTo(_01.left,_01.bottom);_01.setHeight(this.dividerWidth);}else{_01.offsetTo(_01.right,_01.top);_01.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_01,this);}else{var _f=this.dividers[i];_f.rect.offsetTo(_01.left,_01.top);_f.rect.setSize(_01.width,_01.height);_f.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_g,_2){if(!_2){_2={};}
_2.events={mouseDown:true,keyDown:true,mouseWheel:true};var _w=Base.extend({minValue:0,value:0,interval:500});_w=_w.extend(_2);_2=new _w();if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.interval=_2.interval;this._68="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_8q){_8q--;_8q=(_8q<this.minValue)?this.maxValue:_8q;this.setValue(_8q);},stepDown:function(_8q){_8q++;_8q=(_8q>this.maxValue)?this.minValue:_8q;this.setValue(_8q);},mouseDown:function(_5,_a,_04){this.setMouseUp(true);var temp=this;if(_a<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_5,_a,_04){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_I){this.setKeyUp(true);var temp=this;if(_I==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_I==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_I){clearInterval(this.counter);},mouseWheel:function(_Z){if(_Z>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HPasswordControl=HTextControl.extend({componentName:"passwordcontrol"});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_a){this.parent.startDrag(_5,_a,this);},doDrag:function(_5,_a){this.parent.doDrag(_5,_a,this);},endDrag:function(_5,_a){this.parent.endDrag(_5,_a,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HValidatorView=HControl.extend({constructor:function(_1,_m,_2){if(_2!==undefined){if(_2.valueField!==undefined){_1.offsetTo(_2.valueField.rect.right,_2.valueField.rect.top);}}
if(this.isinherited){this.base(_1,_m,_2);}
else{this.isinherited=true;this.base(_1,_m,_2);this.isinherited=false;}
if(!this.isinherited){this.draw();}},setValue:function(_8){if(null===_8||undefined===_8){_8=false;}
this.base(_8);},refresh:function(){this.base();this._8b();},_8b:function(){var _5=0,_a=0;this.setStyle('background-image',"url('"+this.getThemeGfxFile('validator.png')+"')");this.setStyle('background-repeat','no-repeat');if(this.enabled==false){_a=-21;}
if(this.value==true){_5=-21;_66='';}else{_66=this.value;}
ELEM.setAttr(this.elemId,'title',_66);this.setStyle('background-position',_5+'px '+_a+'px');}});HWindow=HDynControl.extend({componentName:'window',constructor:function(_1,_94,_2){if(_94.componentBehaviour[0]!='app'){console.log("Himle.ComponentParentError","HWindow parent must be an HApplication instance!");}
if(!_2){_2={};}
var _w=HClass.extend({minSize:[96,54],maxSize:[16000,9000],resizeW:2,resizeE:2,resizeN:2,resizeS:2,resizeNW:[2,2],resizeNE:[2,2],resizeSW:[2,2],resizeSE:[16,16],noResize:false});_2=new(_w.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
this.base(_1,_94,_2);this.windowView=this;HSystem.windowFocus(this);},gainedActiveStatus:function(){HSystem.windowFocus(this);},windowFocus:function(){this.toggleCSSClass(this.elemId,'inactive',false);this.setStyle('cursor','move');},windowBlur:function(){this.toggleCSSClass(this.elemId,'inactive',true);this.setStyle('cursor','default');}});HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _1f=this.drawn;this.base();if(!_1f){var i=0,_4h=[['overflow','auto']];for(i;i<_4h.length;i++){this.setStyle(_4h[i][0],_4h[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_1,_m,_2){this.tabInit();if(this.isinherited){this.base(_1,_m,_2);}
else{this.isinherited=true;this.base(_1,_m,_2);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_8q){this.base(_8q);if(typeof _8q=='number'){var _d=parseInt(_8q,10);if(_d<this.tabs.length){if(_d!=this.selectIdx){this.selectTab(_d);}}}},stringWidth:function(_13,_9){var _0w='<span style="'+this.fontStyle+'">'+_13+'</span>',_s=this.base(_0w,null,_9);return _s;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabLabelFillBg=false;this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_T){this.label=_T;},selectTab:function(_u){if(_u instanceof HTabView){_u=_u.tabIndex;}
if(this.selectIdx!=-1){var _60=this.tabLabels[this.selectIdx],_80=this.tabs[this.selectIdx];ELEM.removeClassName(_60,'item-fg');ELEM.addClassName(_60,'item-bg');HSystem.views[_80].hide();}
if(_u!=-1){var _0h=this.tabLabels[_u],_4i=this.tabs[_u];ELEM.removeClassName(_0h,'item-bg');ELEM.addClassName(_0h,'item-fg');HSystem.views[_4i].show();}
this.selectIdx=_u;this.setValue(_u);},addTab:function(_3b,_8C){var _u=this.tabs.length,_5Z='',_7f=this.stringWidth(_3b,0),_3P=_7f+this.tabLabelLeftEdge+this.tabLabelRightEdge,_1M=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_u=this.tabs.length,_0h=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);if(this.tabLabelNoHTMLPrefix){_5Z=_3b;}
else{_5Z=this.tabLabelHTMLPrefix1+_7f+this.tabLabelHTMLPrefix2+_3b+this.tabLabelHTMLSuffix;}
_1M.hide();ELEM.addClassName(_0h,'item-bg');ELEM.setStyle(_0h,'width',_3P+'px');ELEM.setStyle(_0h,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_0h,_5Z);this.tabLabelStrings.push(_3b);if(this.tabTriggerLink&&this.tabLabelElementTagName=='a'){ELEM.setAttr(_0h,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_u+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_0h,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_u+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_3P]);}
this.rightmostPx+=_3P;if(this.tabLabelAlign=='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
else if(this.tabLabelFillBg){ELEM.setStyle(this.markupElemIds.state,'left',this.rightmostPx+'px');}
this.tabs.push(_1M.viewId);this.tabLabels.push(_0h);_1M.tabIndex=_u;if(_8C){this.selectTab(_u);}
return _1M;},mouseDown:function(_5,_a){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_5-=this.pageX();_a-=this.pageY();if(_a<=this.tabLabelHeight){if(this.tabLabelAlign=='right'){_5=this.rect.width-_5;}
if(_5<=this.rightmostPx){var i=0,_5h;for(i;i<this.tabLabelBounds.length;i++){_5h=this.tabLabelBounds[i];if(_5<_5h[1]&&_5>=_5h[0]){this.selectTab(i);return;}}}}},removeTab:function(_u){var _7H=this.selectIdx,_4i=this.tabs[_u],_0h=this.tabViews[_u];this.tabs.splice(_u,1);this.tabLabels.splice(_u,1);this.tabLabelBounds.splice(_u,1);this.tabLabelStrings.splice(_u,1);if(_u==_7H){this.selectIdx=-1;if(_u==0&&this.tabs.length==0){this.selectTab(-1);}
else if(_u==(this.tabs.length-1)){this.selectTab(_u-1);}
else{this.selectTab(_u);}}
else if(_u<_7H){this.selectIdx--;}
ELEM.del(_0h);HSystem.views[_4i].die();},draw:function(){var _1f=this.drawn;this.base();if(!_1f){this.drawMarkup();}
this.refresh();}});HImageButton=HControl.extend({componentName:"imagebutton",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.styleButtonDefaults=new(Base.extend({image:this.getThemeGfxPath()+"blank.gif",alternateImage:""}).extend(_2));this._0X=this.getThemeGfxPath()+this.styleButtonDefaults.image;this._4w=this.getThemeGfxPath()+this.styleButtonDefaults.alternateImage;this.type='[HImageButton]';this.preserveTheme=true;this.setMouseUp(true);if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},_8a:function(){if(!this.value){ELEM.get(this._2S).src=this._0X;}else{if(this._4w){ELEM.get(this._2S).src=this._4w;}}},refresh:function(){if(this.drawn){this.base();if(!this._2S){this._2S=this.bindDomElement(HImageButton._67+this.elemId);}
if(this._2S){this._8a();}}},mouseUp:function(_5,_a,_04){this.setValue(!this.value);}},{_67:"imagebutton"});