
var HClass=function(){if(arguments.length){var _4s=arguments[0];if(this==window){HClass.prototype.extend.call(_4s,arguments.callee.prototype);}else{this.extend(_4s);}}};HClass.prototype={extend:function(_0B,_8q){var _2d=HClass.prototype.extend;if(arguments.length==2){var _3k=this[_0B];if((_3k instanceof Function)&&(_8q instanceof Function)&&_3k.valueOf()!=_8q.valueOf()&&(/\bbase\b/).test(_8q)){var _3W=_8q;_8q=function(){var _7v=this.base;this.base=_3k;var _7D=_3W.apply(this,arguments);this.base=_7v;return _7D;};_8q.valueOf=function(){return _3W;};_8q.toString=function(){return String(_3W);};}
return this[_0B]=_8q;}else if(_0B){var _0O={toSource:null};var _5J=["toString","valueOf"];if(HClass._49){_5J.push("constructor");}
for(var i=0;(_C=_5J[i]);i++){if(_0B[_C]!=_0O[_C]){_2d.call(this,_C,_0B[_C]);}}
for(var _C in _0B){if(!_0O[_C]){_2d.call(this,_C,_0B[_C]);}}}
this.nu=function(){var _4z=[],_0=this;for(var i=0;i<arguments.length;i++){_4z.push('arguments['+i+']');}
return eval('new _0('+_4z.join(',')+')');};return this;},base:function(){}};HClass.extend=function(_0L,_4h){var _2d=HClass.prototype.extend;if(!_0L){_0L={};}
HClass._49=true;var _0O=new this;_2d.call(_0O,_0L);var _1u=_0O.constructor;_0O.constructor=this;delete HClass._49;var _1h=function(){if(!HClass._49){_1u.apply(this,arguments);}
this.constructor=_1h;};_1h.prototype=_0O;_1h.extend=this.extend;_1h.implement=this.implement;_1h.toString=function(){return String(_1u);};_2d.call(_1h,_4h);var _40=_1u?_1h:_0O;if(_40.init instanceof Function){_40.init();}
return _40;};HClass.implement=function(_2g){if(_2g instanceof Function){_2g=_2g.prototype;}
this.prototype.extend(_2g);};var Base=HClass;if([]['indexOf']===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_6s){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_6s){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_4A=[];for(i=0;i<l;i++){_4A.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _4A.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_p,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _w=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_w=_w.extend(_2);this.options=new _w();this.request(_p);},request:function(_p){this.url=_p;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
try{this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _q=this;this.transport.onreadystatechange=function(){_q.onStateChange();};this.setRequestHeaders();var _6u=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_6u);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}}catch(e){console.log('error:',e);}},setRequestHeaders:function(){var headers={},o;if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _2o=this.transport.readyState;if(_2o>1){this.respondToReadyState(_2o);}},respondToReadyState:function(_2o){if(_2o==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_2o==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporterDebug=false;HTransporter=HClass.extend({constructor:null,start:function(_8d){var _0=HTransporter;_0.url_base=_8d;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_8){HTransporter.pollMode=_8;},failure:function(resp){var _6J=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_6J)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _7C=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_7C);}
catch(e){if(HTransporterDebug){console.log(e);console.log(e.description);}
_0.err_msg='&err_msg='+e+" - "+e.description;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_8f=((_0.syncDelay>0)||(_0.syncDelay==0));if(_8f&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1L=_0.prevData;}
else{_1L=HValueManager.toXML();_0.prevData=_1L;}
if(""!=_1L||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1L};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_4,_q){this.values[_4]=_q;},set:function(_4,_8q){this.values[_4].set(_8q);},s:function(_4,_8q){this.values[_4].s(_8q);},del:function(_4){var _66=this.values[_4],_8e=_66.views,_0q=0,_67=null;for(;_0q<_8e.length;_0q++){_67=_8e[_0q];_67.valueObj=new HDummyValue(0,_66.value);}
this.values[_4]=null;},changed:function(_2x){if(this.isGetting==false){if(this.tosync.indexOf(_2x.id)==-1){this.tosync.push(_2x.id);}
var _X=HTransporter;if(!_X.pollMode){clearTimeout(_X.req_timeout);_X.req_timeout=setTimeout('HTransporter.sync();',_X.syncDelay);}}},toXML:function(){var _5I='&HSyncData=';if(!this.isSending){this.isSending=true;var _7V=this.tosync.length;if(_7V==0){this.isSending=false;return'';}
var _5Y=[],_0K;for(_0K=0;_0K<_7V;_0K++){var _1m=this.tosync.shift();var _7W=this.values[_1m];_5Y.push(_7W.toXML(_0K));}
var _7X=_5Y.join('');_5I+='<hsyncvalues version="8118">'+_7X+'</hsyncvalues>';this.isSending=false;}
return _5I;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_4,_8q){this.id=_4;this.type='[HValue]';this.value=_8q;this.views=[];HValueManager.add(_4,this);},set:function(_8q){if(_8q!=this.value){this.value=_8q;HValueManager.changed(this);this.refresh();}},s:function(_8q){this.value=_8q;this.refresh();},get:function(){return this.value;},bind:function(_N){if(_N===undefined){throw("HValueBindError: _N is undefined!");}
this.views.push(_N);_N.setValueObj(this);},unbind:function(_N){for(var _0q=0;_0q<this.views.length;_0q++){var _89=this.views[_0q];if(_89===_N){this.views.splice(_0q);return;}}},release:function(_N){return this.unbind(_N);},refresh:function(){for(var _0q=0;_0q<this.views.length;_0q++){var _N=this.views[_0q];if(_N.value!=this.value){if(!_N._valueIsBeingSet){_N._valueIsBeingSet=true;_N.setValue(this.value);_N._valueIsBeingSet=false;}}}},toXML:function(_0K){var _1m=this.id.toString();var _0g=this.value;var _0P=(typeof _0g).slice(0,1);var _14;if(_0P=='s'){_14=_0g.toString();_14=SHA.str2Base64(_14);}
else if(_0P=='n'){if(Math.ceil(_0g)===Math.floor(_0g)===_0g){_0P='i';_14=parseInt(_0g,10).toString();}
else{_0P='f';_14=parseFloat(_0g).toString();}}
else if(_0P=='b'){if(_0g){_14='1';}
else{_14='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1m);console.log('  syncjstype:',_0P);console.log('  typeof:',(typeof _0g));console.log('  syncvalue:',_0g);}}
catch(e){alert('value error, syncid:'+_1m+' syncjstype:'+_0P+' typeof:'+(typeof _0g)+' syncvalue:'+_0g);}
return'';}
return'<'+_0P+' id="'+_1m+'">'+_14+'</'+_0P+'>';}});JSLoader=HClass.extend({constructor:function(_8c){var _0=this;_0._loadedJS=[];_0.uri=_8c;_0._7z=null;_0._okayed=false;},_94:function(_7B){var _0=this;if(_0._okayed){return;}
eval(_7B.responseText);_0._okayed=true;},load:function(_2i,_70){var _0=this;if((_0._loadedJS.indexOf(_2i)!=-1)&&(_70===undefined)){return;}
if(_70){document.write('<scr'+'ipt type="text/javascript" src="'+_2i+'"><'+'/scr'+'ipt>');}else{var _7A={onSuccess:function(resp){_0._94(resp);},onFailure:function(resp){window.status="failed to load js: "+_0.uri+_2i+'.js';},method:'get',asynchronous:false};var _p=this.uri+_2i+'.js';_0._7z=new Ajax.Request(_p,_7A);_0._loadedJS.push(_2i);_0._okayed=false;}}});RUN("jsLoader = new JSLoader('/H/js/');");var HClass=function(){if(arguments.length){var _4s=arguments[0];if(this==window){HClass.prototype.extend.call(_4s,arguments.callee.prototype);}else{this.extend(_4s);}}};HClass.prototype={extend:function(_0B,_8q){var _2d=HClass.prototype.extend;if(arguments.length==2){var _3k=this[_0B];if((_3k instanceof Function)&&(_8q instanceof Function)&&_3k.valueOf()!=_8q.valueOf()&&(/\bbase\b/).test(_8q)){var _3W=_8q;_8q=function(){var _7v=this.base;this.base=_3k;var _7D=_3W.apply(this,arguments);this.base=_7v;return _7D;};_8q.valueOf=function(){return _3W;};_8q.toString=function(){return String(_3W);};}
return this[_0B]=_8q;}else if(_0B){var _0O={toSource:null};var _5J=["toString","valueOf"];if(HClass._49){_5J.push("constructor");}
for(var i=0;(_C=_5J[i]);i++){if(_0B[_C]!=_0O[_C]){_2d.call(this,_C,_0B[_C]);}}
for(var _C in _0B){if(!_0O[_C]){_2d.call(this,_C,_0B[_C]);}}}
this.nu=function(){var _4z=[],_0=this;for(var i=0;i<arguments.length;i++){_4z.push('arguments['+i+']');}
return eval('new _0('+_4z.join(',')+')');};return this;},base:function(){}};HClass.extend=function(_0L,_4h){var _2d=HClass.prototype.extend;if(!_0L){_0L={};}
HClass._49=true;var _0O=new this;_2d.call(_0O,_0L);var _1u=_0O.constructor;_0O.constructor=this;delete HClass._49;var _1h=function(){if(!HClass._49){_1u.apply(this,arguments);}
this.constructor=_1h;};_1h.prototype=_0O;_1h.extend=this.extend;_1h.implement=this.implement;_1h.toString=function(){return String(_1u);};_2d.call(_1h,_4h);var _40=_1u?_1h:_0O;if(_40.init instanceof Function){_40.init();}
return _40;};HClass.implement=function(_2g){if(_2g instanceof Function){_2g=_2g.prototype;}
this.prototype.extend(_2g);};var Base=HClass;if([]['indexOf']===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_6s){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_6s){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_4A=[];for(i=0;i<l;i++){_4A.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _4A.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_p,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _w=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_w=_w.extend(_2);this.options=new _w();this.request(_p);},request:function(_p){this.url=_p;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
try{this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _q=this;this.transport.onreadystatechange=function(){_q.onStateChange();};this.setRequestHeaders();var _6u=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_6u);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}}catch(e){console.log('error:',e);}},setRequestHeaders:function(){var headers={},o;if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _2o=this.transport.readyState;if(_2o>1){this.respondToReadyState(_2o);}},respondToReadyState:function(_2o){if(_2o==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_2o==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporterDebug=false;HTransporter=HClass.extend({constructor:null,start:function(_8d){var _0=HTransporter;_0.url_base=_8d;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_8){HTransporter.pollMode=_8;},failure:function(resp){var _6J=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_6J)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _7C=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_7C);}
catch(e){if(HTransporterDebug){console.log(e);console.log(e.description);}
_0.err_msg='&err_msg='+e+" - "+e.description;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_8f=((_0.syncDelay>0)||(_0.syncDelay==0));if(_8f&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1L=_0.prevData;}
else{_1L=HValueManager.toXML();_0.prevData=_1L;}
if(""!=_1L||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1L};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_4,_q){this.values[_4]=_q;},set:function(_4,_8q){this.values[_4].set(_8q);},s:function(_4,_8q){this.values[_4].s(_8q);},del:function(_4){var _66=this.values[_4],_8e=_66.views,_0q=0,_67=null;for(;_0q<_8e.length;_0q++){_67=_8e[_0q];_67.valueObj=new HDummyValue(0,_66.value);}
this.values[_4]=null;},changed:function(_2x){if(this.isGetting==false){if(this.tosync.indexOf(_2x.id)==-1){this.tosync.push(_2x.id);}
var _X=HTransporter;if(!_X.pollMode){clearTimeout(_X.req_timeout);_X.req_timeout=setTimeout('HTransporter.sync();',_X.syncDelay);}}},toXML:function(){var _5I='&HSyncData=';if(!this.isSending){this.isSending=true;var _7V=this.tosync.length;if(_7V==0){this.isSending=false;return'';}
var _5Y=[],_0K;for(_0K=0;_0K<_7V;_0K++){var _1m=this.tosync.shift();var _7W=this.values[_1m];_5Y.push(_7W.toXML(_0K));}
var _7X=_5Y.join('');_5I+='<hsyncvalues version="8118">'+_7X+'</hsyncvalues>';this.isSending=false;}
return _5I;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_4,_8q){this.id=_4;this.type='[HValue]';this.value=_8q;this.views=[];HValueManager.add(_4,this);},set:function(_8q){if(_8q!=this.value){this.value=_8q;HValueManager.changed(this);this.refresh();}},s:function(_8q){this.value=_8q;this.refresh();},get:function(){return this.value;},bind:function(_N){if(_N===undefined){throw("HValueBindError: _N is undefined!");}
this.views.push(_N);_N.setValueObj(this);},unbind:function(_N){for(var _0q=0;_0q<this.views.length;_0q++){var _89=this.views[_0q];if(_89===_N){this.views.splice(_0q);return;}}},release:function(_N){return this.unbind(_N);},refresh:function(){for(var _0q=0;_0q<this.views.length;_0q++){var _N=this.views[_0q];if(_N.value!=this.value){if(!_N._valueIsBeingSet){_N._valueIsBeingSet=true;_N.setValue(this.value);_N._valueIsBeingSet=false;}}}},toXML:function(_0K){var _1m=this.id.toString();var _0g=this.value;var _0P=(typeof _0g).slice(0,1);var _14;if(_0P=='s'){_14=_0g.toString();_14=SHA.str2Base64(_14);}
else if(_0P=='n'){if(Math.ceil(_0g)===Math.floor(_0g)===_0g){_0P='i';_14=parseInt(_0g,10).toString();}
else{_0P='f';_14=parseFloat(_0g).toString();}}
else if(_0P=='b'){if(_0g){_14='1';}
else{_14='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1m);console.log('  syncjstype:',_0P);console.log('  typeof:',(typeof _0g));console.log('  syncvalue:',_0g);}}
catch(e){alert('value error, syncid:'+_1m+' syncjstype:'+_0P+' typeof:'+(typeof _0g)+' syncvalue:'+_0g);}
return'';}
return'<'+_0P+' id="'+_1m+'">'+_14+'</'+_0P+'>';}});JSLoader=HClass.extend({constructor:function(_8c){var _0=this;_0._loadedJS=[];_0.uri=_8c;_0._7z=null;_0._okayed=false;},_94:function(_7B){var _0=this;if(_0._okayed){return;}
eval(_7B.responseText);_0._okayed=true;},load:function(_2i,_70){var _0=this;if((_0._loadedJS.indexOf(_2i)!=-1)&&(_70===undefined)){return;}
if(_70){document.write('<scr'+'ipt type="text/javascript" src="'+_2i+'"><'+'/scr'+'ipt>');}else{var _7A={onSuccess:function(resp){_0._94(resp);},onFailure:function(resp){window.status="failed to load js: "+_0.uri+_2i+'.js';},method:'get',asynchronous:false};var _p=this.uri+_2i+'.js';_0._7z=new Ajax.Request(_p,_7A);_0._loadedJS.push(_2i);_0._okayed=false;}}});RUN("jsLoader = new JSLoader('/H/js/');");var HClass=function(){if(arguments.length){var _4s=arguments[0];if(this==window){HClass.prototype.extend.call(_4s,arguments.callee.prototype);}else{this.extend(_4s);}}};HClass.prototype={extend:function(_0B,_8q){var _2d=HClass.prototype.extend;if(arguments.length==2){var _3k=this[_0B];if((_3k instanceof Function)&&(_8q instanceof Function)&&_3k.valueOf()!=_8q.valueOf()&&(/\bbase\b/).test(_8q)){var _3W=_8q;_8q=function(){var _7v=this.base;this.base=_3k;var _7D=_3W.apply(this,arguments);this.base=_7v;return _7D;};_8q.valueOf=function(){return _3W;};_8q.toString=function(){return String(_3W);};}
return this[_0B]=_8q;}else if(_0B){var _0O={toSource:null};var _5J=["toString","valueOf"];if(HClass._49){_5J.push("constructor");}
for(var i=0;(_C=_5J[i]);i++){if(_0B[_C]!=_0O[_C]){_2d.call(this,_C,_0B[_C]);}}
for(var _C in _0B){if(!_0O[_C]){_2d.call(this,_C,_0B[_C]);}}}
this.nu=function(){var _4z=[],_0=this;for(var i=0;i<arguments.length;i++){_4z.push('arguments['+i+']');}
return eval('new _0('+_4z.join(',')+')');};return this;},base:function(){}};HClass.extend=function(_0L,_4h){var _2d=HClass.prototype.extend;if(!_0L){_0L={};}
HClass._49=true;var _0O=new this;_2d.call(_0O,_0L);var _1u=_0O.constructor;_0O.constructor=this;delete HClass._49;var _1h=function(){if(!HClass._49){_1u.apply(this,arguments);}
this.constructor=_1h;};_1h.prototype=_0O;_1h.extend=this.extend;_1h.implement=this.implement;_1h.toString=function(){return String(_1u);};_2d.call(_1h,_4h);var _40=_1u?_1h:_0O;if(_40.init instanceof Function){_40.init();}
return _40;};HClass.implement=function(_2g){if(_2g instanceof Function){_2g=_2g.prototype;}
this.prototype.extend(_2g);};var Base=HClass;if([]['indexOf']===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_6s){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_6s){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_4A=[];for(i=0;i<l;i++){_4A.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _4A.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_p,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _w=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_w=_w.extend(_2);this.options=new _w();this.request(_p);},request:function(_p){this.url=_p;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
try{this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _q=this;this.transport.onreadystatechange=function(){_q.onStateChange();};this.setRequestHeaders();var _6u=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_6u);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}}catch(e){console.log('error:',e);}},setRequestHeaders:function(){var headers={},o;if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _2o=this.transport.readyState;if(_2o>1){this.respondToReadyState(_2o);}},respondToReadyState:function(_2o){if(_2o==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_2o==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporterDebug=false;HTransporter=HClass.extend({constructor:null,start:function(_8d){var _0=HTransporter;_0.url_base=_8d;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_8){HTransporter.pollMode=_8;},failure:function(resp){var _6J=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_6J)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _7C=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_7C);}
catch(e){if(HTransporterDebug){console.log(e);console.log(e.description);}
_0.err_msg='&err_msg='+e+" - "+e.description;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_8f=((_0.syncDelay>0)||(_0.syncDelay==0));if(_8f&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1L=_0.prevData;}
else{_1L=HValueManager.toXML();_0.prevData=_1L;}
if(""!=_1L||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1L};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_4,_q){this.values[_4]=_q;},set:function(_4,_8q){this.values[_4].set(_8q);},s:function(_4,_8q){this.values[_4].s(_8q);},del:function(_4){var _66=this.values[_4],_8e=_66.views,_0q=0,_67=null;for(;_0q<_8e.length;_0q++){_67=_8e[_0q];_67.valueObj=new HDummyValue(0,_66.value);}
this.values[_4]=null;},changed:function(_2x){if(this.isGetting==false){if(this.tosync.indexOf(_2x.id)==-1){this.tosync.push(_2x.id);}
var _X=HTransporter;if(!_X.pollMode){clearTimeout(_X.req_timeout);_X.req_timeout=setTimeout('HTransporter.sync();',_X.syncDelay);}}},toXML:function(){var _5I='&HSyncData=';if(!this.isSending){this.isSending=true;var _7V=this.tosync.length;if(_7V==0){this.isSending=false;return'';}
var _5Y=[],_0K;for(_0K=0;_0K<_7V;_0K++){var _1m=this.tosync.shift();var _7W=this.values[_1m];_5Y.push(_7W.toXML(_0K));}
var _7X=_5Y.join('');_5I+='<hsyncvalues version="8118">'+_7X+'</hsyncvalues>';this.isSending=false;}
return _5I;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_4,_8q){this.id=_4;this.type='[HValue]';this.value=_8q;this.views=[];HValueManager.add(_4,this);},set:function(_8q){if(_8q!=this.value){this.value=_8q;HValueManager.changed(this);this.refresh();}},s:function(_8q){this.value=_8q;this.refresh();},get:function(){return this.value;},bind:function(_N){if(_N===undefined){throw("HValueBindError: _N is undefined!");}
this.views.push(_N);_N.setValueObj(this);},unbind:function(_N){for(var _0q=0;_0q<this.views.length;_0q++){var _89=this.views[_0q];if(_89===_N){this.views.splice(_0q);return;}}},release:function(_N){return this.unbind(_N);},refresh:function(){for(var _0q=0;_0q<this.views.length;_0q++){var _N=this.views[_0q];if(_N.value!=this.value){if(!_N._valueIsBeingSet){_N._valueIsBeingSet=true;_N.setValue(this.value);_N._valueIsBeingSet=false;}}}},toXML:function(_0K){var _1m=this.id.toString();var _0g=this.value;var _0P=(typeof _0g).slice(0,1);var _14;if(_0P=='s'){_14=_0g.toString();_14=SHA.str2Base64(_14);}
else if(_0P=='n'){if(Math.ceil(_0g)===Math.floor(_0g)===_0g){_0P='i';_14=parseInt(_0g,10).toString();}
else{_0P='f';_14=parseFloat(_0g).toString();}}
else if(_0P=='b'){if(_0g){_14='1';}
else{_14='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1m);console.log('  syncjstype:',_0P);console.log('  typeof:',(typeof _0g));console.log('  syncvalue:',_0g);}}
catch(e){alert('value error, syncid:'+_1m+' syncjstype:'+_0P+' typeof:'+(typeof _0g)+' syncvalue:'+_0g);}
return'';}
return'<'+_0P+' id="'+_1m+'">'+_14+'</'+_0P+'>';}});JSLoader=HClass.extend({constructor:function(_8c){var _0=this;_0._loadedJS=[];_0.uri=_8c;_0._7z=null;_0._okayed=false;},_94:function(_7B){var _0=this;if(_0._okayed){return;}
eval(_7B.responseText);_0._okayed=true;},load:function(_2i,_70){var _0=this;if((_0._loadedJS.indexOf(_2i)!=-1)&&(_70===undefined)){return;}
if(_70){document.write('<scr'+'ipt type="text/javascript" src="'+_2i+'"><'+'/scr'+'ipt>');}else{var _7A={onSuccess:function(resp){_0._94(resp);},onFailure:function(resp){window.status="failed to load js: "+_0.uri+_2i+'.js';},method:'get',asynchronous:false};var _p=this.uri+_2i+'.js';_0._7z=new Ajax.Request(_p,_7A);_0._loadedJS.push(_2i);_0._okayed=false;}}});RUN("jsLoader = new JSLoader('/H/js/');");