
ie_htc_path=null;function ie_early_fixes(){document.execCommand("BackgroundImageCache",false,true);var _7G=document.scripts[document.scripts.length-1],_5R=_7G.src;ie_htc_path=_5R.substring(0,_5R.lastIndexOf("/")+1);console={log:function(){}};}
ie_early_fixes();iefix={setWinSize:function(){window.innerWidth=document.documentElement.clientWidth;window.innerHeight=document.documentElement.clientHeight;},_8P:function(_6){return _6.currentStyle.hasLayout;},layoutWidth:function(_6){var _0=iefix,_m,i=0,_0e=_6.offsetParent;while(_0e&&!_0._8P(_0e)){_0e=_0e.offsetParent;}
if(!_0e._resizewidthElements){_0e._resizewidthElements=[];}
if(!_6._addedResizewidthFix){_0e._resizewidthElements.push(_6);_m=_0e;while(_m.offsetParent){_m=_m.offsetParent;if(_m._resizewidthElements){_m._resizewidthElements.push(_6);}
if(_m.style.position=="absolute"||_m.style.position=="fixed"){break;}}
_6._addedResizewidthFix=true;}
if(!_0e._resizewidth){_0e.attachEvent("onpropertychange",function(){if(window.event.propertyName=="style.width"){for(;i<_0e._resizewidthElements.length;i++){_0.resizeRight(_0e._resizewidthElements[i]);}}});_0e._resizewidth=true;}
return(_0e||document.documentElement).clientWidth;},getBorderWidth:function(_6){return _6.offsetWidth-_6.clientWidth;},getPixelValue:function(_6,_8q){var _0=iefix,_0p,_7F;if(_0._PIXEL.test(_8q)){return parseInt(_8q,10);}
_0p=_6.style.left;_7F=_6.runtimeStyle.left;_6.runtimeStyle.left=_6.currentStyle.left;_0.resizing=true;_6.style.left=_8q||0;_8q=_6.style.pixelLeft;_6.style.left=_0p;_0.resizing=false;_6.runtimeStyle.left=_7F;return _8q;},getPixelWidth:function(_6,_8q){var _0=iefix;if(_0._PERCENT.test(_8q)){return parseInt(parseFloat(_8q)/100*_0.layoutWidth(_6),10);}
return _0.getPixelValue(_6,_8q);},getPaddingWidth:function(_6){var _0=iefix;return _0.getPixelWidth(_6,_6.currentStyle.paddingLeft)+_0.getPixelWidth(_6,_6.currentStyle.paddingRight);},resizeRight:function(_6){var _0=iefix,_0l,_s;if(_6.currentStyle===null){return;}
_0l=parseInt(_6.currentStyle.left,10);_s=_0.layoutWidth(_6)-parseInt(_6.currentStyle.right,10)-_0l;if(parseInt(_6.runtimeStyle.width,10)==_s){return;}
_6.runtimeStyle.width="";if(_6.offsetWidth<_s){_s-=_0.getBorderWidth(_6)+_0.getPaddingWidth(_6);if(_s<0){_s=0;}
_6.runtimeStyle.width=_s;}},fixOpacity:function(_6){var _0f=(parseFloat(_6.currentStyle.opacity)*100)||1,_03=_6.filters["DXImageTransform.Microsoft.Alpha"];if(_03){_03.Opacity=_0f;_03.Enabled=true;}
else{_6.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.Alpha(opacity="+_0f+")";}},fixBackgroundImage:function(_6){var _0=iefix,_p,_03;_p=_6.currentStyle.backgroundImage.match(/url\(\s*['"]?([^'")]+)['"]?\s*\)/);if(!_p){return;}
else{_p=_p[1];}
_03=_6.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_0.pngCheck.test(_p)){if(_03){_03.sizingMethod="crop";_03.src=_p;_03.Enabled=true;}
else{_6.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_p+"',sizingMethod='crop')";}
_6.runtimeStyle.zoom="0";_6.runtimeStyle.backgroundImage="none";}
else if(_03){_03.Enabled=false;}},addFilter:function(_6,_0X){var _0=iefix,_03,_tempUrl;_03=_6.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_03){_03.src=_6.src;_03.Enabled=true;}
else{_6.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_6.src+"',sizingMethod='scale')";}
_85=_6.src;_6.src=_0.blankGifPath;_0X.src=_85;},fixImg:function(_6){var _0=iefix,_0X;if(_0.pngCheck.test(_6.src)){_0X=new Image(_6.width,_6.height);_0X.onload=function(){_6.width=_0X.width;_6.height=_0X.height;_0X=null;};_0.addFilter(_6,_0X);}},_92:['PARAM'],inlineStyleChanged:function(_6){var _0=iefix,_0k;_0k=_6.currentStyle;if(_0._92.indexOf(_6.tagName)!=-1){return;}
try{if((_0k.position=="absolute"||_0k.position=="fixed")&&_0k.left!="auto"&&_0k.right!="auto"&&_0k.width=="auto"){_0.resizeRight(_6);}
if((_0k.position=="absolute"||_0k.position=="fixed")&&_0k.top!="auto"&&_0k.bottom!="auto"&&_0k.height=="auto"){_0.resizeBottom(_6);}
if(_6.currentStyle.opacity){_0.fixOpacity(_6);}}catch(e){alert("iefix error! element:"+_6.tagName+" e:"+e.description);}
if(_6.style.backgroundColor=='transparent'&&(_6.style.backgroundImage=='none'||!_6.style.backgroundImage)){_6.style.backgroundImage="url("+ie_htc_path+"128.gif)";}},_9q:0,_0i:function(_6){var _0=iefix;_0._9q++;_6=_6||document.documentElement;while(_6){if(_6.nodeType==1){_0.inlineStyleChanged(_6);}
var _33=_6.firstChild;if(!_33){_33=_6.nextSibling;}
while(!_33&&_6.parentNode){_6=_6.parentNode;_33=_6.nextSibling;}
_6=_33;}},stylesheet_refresh:function(_5U){_5U.cssText+="";},init:function(){var _0=iefix;_0._AUTO=/^(auto|0cm)$/;_0._PIXEL=/^\d+(px)?$/i;_0._PERCENT=/^\d+%$/;_0.pngCheck=new RegExp(".png$","i");_0.blankGifPath=ie_htc_path+"0.gif";eval("_0.getMarginWidth="+String(_0.getPaddingWidth).replace(/padding/g,"margin"));eval("_0.getPaddingHeight="+String(_0.getPaddingWidth).replace(/Width/g,"Height").replace(/Left/g,"Top").replace(/Right/g,"Bottom"));eval("_0.getMarginHeight="+String(_0.getPaddingHeight).replace(/padding/g,"margin"));eval("_0.getBorderHeight="+String(_0.getBorderWidth).replace(/Width/g,"Height"));eval("_0.layoutHeight="+String(_0.layoutWidth).replace(/Width/g,"Height").replace(/width/g,"height").replace(/Right/g,"Bottom"));eval("_0.getPixelHeight="+String(_0.getPixelWidth).replace(/Width/g,"Height"));eval("_0.resizeBottom="+String(_0.resizeRight).replace(/Width/g,"Height").replace(/width/g,"height").replace(/left/g,"top").replace(/right/g,"bottom"));_0.resizing=false;},htcStyleEntry:function(){if(document.readyState=="complete"&&window.event.srcElement.readyState=="complete"){iefix._0i();}},_3e:['width','height','left','top','right','bottom','display','position'],htcElementEntry:function(){var _6=window.event.srcElement,_2n=window.event.propertyName;if(_2n=="style.opacity"){iefix.fixOpacity(_6);}
else if((_2n=="src"&&_6.tagName=="IMG")||(_6.tagName=="INPUT"&&_6.type=="image")){window.status='htcElementEntry: '+iefix._1A+' img';iefix.fixImg(_6);}
else if(_2n.substring(0,6)=='style.'){if(iefix._3e.indexOf(_2n.split('style.')[1])!=-1){iefix._0i();}}}};iefix.init();ie_complete=document.readyState=="complete";ie_initialized=false;ie_documentLoaded=function(){if(document.readyState=="complete"){iefix._0i();}};ie_fixes=function(){if(!ie_initialized){if(ie_complete){ie_documentLoaded();}
else{document.onreadystatechange=ie_documentLoaded;}
ie_initialized=true;}};ie_fixes();window.onresize=function(){iefix.setWinSize();iefix._0i();};