
ie_htc_path=null;function ie_early_fixes(){document.execCommand("BackgroundImageCache",false,true);var _7H=document.scripts[document.scripts.length-1],_5T=_7H.src;ie_htc_path=_5T.substring(0,_5T.lastIndexOf("/")+1);console={log:function(){}};}
ie_early_fixes();iefix={setWinSize:function(){window.innerWidth=document.documentElement.clientWidth;window.innerHeight=document.documentElement.clientHeight;},_8Q:function(_5){return _5.currentStyle.hasLayout;},layoutWidth:function(_5){var _0=iefix,_m,i=0,_0e=_5.offsetParent;while(_0e&&!_0._8Q(_0e)){_0e=_0e.offsetParent;}
if(!_0e._resizewidthElements){_0e._resizewidthElements=[];}
if(!_5._addedResizewidthFix){_0e._resizewidthElements.push(_5);_m=_0e;while(_m.offsetParent){_m=_m.offsetParent;if(_m._resizewidthElements){_m._resizewidthElements.push(_5);}
if(_m.style.position=="absolute"||_m.style.position=="fixed"){break;}}
_5._addedResizewidthFix=true;}
if(!_0e._resizewidth){_0e.attachEvent("onpropertychange",function(){if(window.event.propertyName=="style.width"){for(;i<_0e._resizewidthElements.length;i++){_0.resizeRight(_0e._resizewidthElements[i]);}}});_0e._resizewidth=true;}
return(_0e||document.documentElement).clientWidth;},getBorderWidth:function(_5){return _5.offsetWidth-_5.clientWidth;},getPixelValue:function(_5,_8q){var _0=iefix,_0p,_7G;if(_0._PIXEL.test(_8q)){return parseInt(_8q,10);}
_0p=_5.style.left;_7G=_5.runtimeStyle.left;_5.runtimeStyle.left=_5.currentStyle.left;_0.resizing=true;_5.style.left=_8q||0;_8q=_5.style.pixelLeft;_5.style.left=_0p;_0.resizing=false;_5.runtimeStyle.left=_7G;return _8q;},getPixelWidth:function(_5,_8q){var _0=iefix;if(_0._PERCENT.test(_8q)){return parseInt(parseFloat(_8q)/100*_0.layoutWidth(_5),10);}
return _0.getPixelValue(_5,_8q);},getPaddingWidth:function(_5){var _0=iefix;return _0.getPixelWidth(_5,_5.currentStyle.paddingLeft)+_0.getPixelWidth(_5,_5.currentStyle.paddingRight);},resizeRight:function(_5){var _0=iefix,_0l,_s;if(_5.currentStyle===null){return;}
_0l=parseInt(_5.currentStyle.left,10);_s=_0.layoutWidth(_5)-parseInt(_5.currentStyle.right,10)-_0l;if(parseInt(_5.runtimeStyle.width,10)==_s){return;}
_5.runtimeStyle.width="";if(_5.offsetWidth<_s){_s-=_0.getBorderWidth(_5)+_0.getPaddingWidth(_5);if(_s<0){_s=0;}
_5.runtimeStyle.width=_s;}},fixOpacity:function(_5){var _0f=(parseFloat(_5.currentStyle.opacity)*100)||1,_03=_5.filters["DXImageTransform.Microsoft.Alpha"];if(_03){_03.Opacity=_0f;_03.Enabled=true;}
else{_5.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.Alpha(opacity="+_0f+")";}},fixBackgroundImage:function(_5){var _0=iefix,_p,_03;_p=_5.currentStyle.backgroundImage.match(/url\(\s*['"]?([^'")]+)['"]?\s*\)/);if(!_p){return;}
else{_p=_p[1];}
_03=_5.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_0.pngCheck.test(_p)){if(_03){_03.sizingMethod="crop";_03.src=_p;_03.Enabled=true;}
else{_5.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_p+"',sizingMethod='crop')";}
_5.runtimeStyle.zoom="0";_5.runtimeStyle.backgroundImage="none";}
else if(_03){_03.Enabled=false;}},addFilter:function(_5,_0X){var _0=iefix,_03,_tempUrl;_03=_5.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_03){_03.src=_5.src;_03.Enabled=true;}
else{_5.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_5.src+"',sizingMethod='scale')";}
_85=_5.src;_5.src=_0.blankGifPath;_0X.src=_85;},fixImg:function(_5){var _0=iefix,_0X;if(_0.pngCheck.test(_5.src)){_0X=new Image(_5.width,_5.height);_0X.onload=function(){_5.width=_0X.width;_5.height=_0X.height;_0X=null;};_0.addFilter(_5,_0X);}},_93:['PARAM'],inlineStyleChanged:function(_5){var _0=iefix,_0k;_0k=_5.currentStyle;if(_0._93.indexOf(_5.tagName)!=-1){return;}
try{if((_0k.position=="absolute"||_0k.position=="fixed")&&_0k.left!="auto"&&_0k.right!="auto"&&_0k.width=="auto"){_0.resizeRight(_5);}
if((_0k.position=="absolute"||_0k.position=="fixed")&&_0k.top!="auto"&&_0k.bottom!="auto"&&_0k.height=="auto"){_0.resizeBottom(_5);}
if(_5.currentStyle.opacity){_0.fixOpacity(_5);}}catch(e){alert("iefix error! element:"+_5.tagName+" e:"+e.description);}
if(_5.style.backgroundColor=='transparent'&&(_5.style.backgroundImage=='none'||!_5.style.backgroundImage)){_5.style.backgroundImage="url("+ie_htc_path+"128.gif)";}},_9r:0,_0i:function(_5){var _0=iefix;_0._9r++;_5=_5||document.documentElement;while(_5){if(_5.nodeType==1){_0.inlineStyleChanged(_5);}
var _33=_5.firstChild;if(!_33){_33=_5.nextSibling;}
while(!_33&&_5.parentNode){_5=_5.parentNode;_33=_5.nextSibling;}
_5=_33;}},stylesheet_refresh:function(_5X){_5X.cssText+="";},init:function(){var _0=iefix;_0._AUTO=/^(auto|0cm)$/;_0._PIXEL=/^\d+(px)?$/i;_0._PERCENT=/^\d+%$/;_0.pngCheck=new RegExp(".png$","i");_0.blankGifPath=ie_htc_path+"0.gif";eval("_0.getMarginWidth="+String(_0.getPaddingWidth).replace(/padding/g,"margin"));eval("_0.getPaddingHeight="+String(_0.getPaddingWidth).replace(/Width/g,"Height").replace(/Left/g,"Top").replace(/Right/g,"Bottom"));eval("_0.getMarginHeight="+String(_0.getPaddingHeight).replace(/padding/g,"margin"));eval("_0.getBorderHeight="+String(_0.getBorderWidth).replace(/Width/g,"Height"));eval("_0.layoutHeight="+String(_0.layoutWidth).replace(/Width/g,"Height").replace(/width/g,"height").replace(/Right/g,"Bottom"));eval("_0.getPixelHeight="+String(_0.getPixelWidth).replace(/Width/g,"Height"));eval("_0.resizeBottom="+String(_0.resizeRight).replace(/Width/g,"Height").replace(/width/g,"height").replace(/left/g,"top").replace(/right/g,"bottom"));_0.resizing=false;},htcStyleEntry:function(){if(document.readyState=="complete"&&window.event.srcElement.readyState=="complete"){iefix._0i();}},_3e:['width','height','left','top','right','bottom','display','position'],htcElementEntry:function(){var _5=window.event.srcElement,_2n=window.event.propertyName;if(_2n=="style.opacity"){iefix.fixOpacity(_5);}
else if((_2n=="src"&&_5.tagName=="IMG")||(_5.tagName=="INPUT"&&_5.type=="image")){window.status='htcElementEntry: '+iefix._1A+' img';iefix.fixImg(_5);}
else if(_2n.substring(0,6)=='style.'){if(iefix._3e.indexOf(_2n.split('style.')[1])!=-1){iefix._0i();}}}};iefix.init();ie_complete=document.readyState=="complete";ie_initialized=false;ie_documentLoaded=function(){if(document.readyState=="complete"){iefix._0i();}};ie_fixes=function(){if(!ie_initialized){if(ie_complete){ie_documentLoaded();}
else{document.onreadystatechange=ie_documentLoaded;}
ie_initialized=true;}};ie_fixes();window.onresize=function(){iefix.setWinSize();iefix._0i();};