
HStyleButton=HImageButton.extend({packageName:"richtext",componentName:"stylebutton",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HStyleButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},mouseUp:function(){if(this.styleButtonDefaults.richtextview){HTextEdit.execCommand(this.styleButtonDefaults.command,false,null,this.styleButtonDefaults.richtextview.iframe().contentWindow.document);}
this.base();}},{_6a:"imageview"});HStyleButtonBar=HView.extend({packageName:"richtext",componentName:"stylebuttonbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.styleButtonBarDefaults=new(Base.extend({}).extend(_2));this.type='[HStyleButtonBar]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();if(this.styleButtonBarDefaults.styleBarSettings){if(this.styleButtonBarDefaults.styleBarSettings.bold){this.bButton=new HStyleButton(new HRect(0,0,20,20),this,{image:"bold.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"bold"});}
if(this.styleButtonBarDefaults.styleBarSettings.italic){this.iButton=new HStyleButton(new HRect(20,0,40,20),this,{image:"italic.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"italic"});}
if(this.styleButtonBarDefaults.styleBarSettings.underline){this.underlineButton=new HStyleButton(new HRect(40,0,60,20),this,{image:"underline.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"underline"});}
if(this.styleButtonBarDefaults.styleBarSettings.justify){this.justifyleftButton=new HStyleButton(new HRect(60,0,80,20),this,{image:"justifyleft.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifyleft"});this.justifycenterButton=new HStyleButton(new HRect(80,0,100,20),this,{image:"justifycenter.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifycenter"});this.justifyrightButton=new HStyleButton(new HRect(100,0,120,20),this,{image:"justifyright.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifyright"});this.justifyfullButton=new HStyleButton(new HRect(120,0,140,20),this,{image:"justifyfull.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifyfull"});}
if(this.styleButtonBarDefaults.styleBarSettings.insertunorderedlist){this.ulButton=new HStyleButton(new HRect(140,0,160,20),this,{image:"insertunorderedlist.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"insertunorderedlist"});}
if(this.styleButtonBarDefaults.styleBarSettings.insertorderedlist){this.olButton=new HStyleButton(new HRect(160,0,180,20),this,{image:"insertorderedlist.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"insertorderedlist"});}
if(this.styleButtonBarDefaults.styleBarSettings.indent){this.indentButton=new HStyleButton(new HRect(180,0,200,20),this,{image:"indent.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"indent"});}
if(this.styleButtonBarDefaults.styleBarSettings.outdent){this.outdentButton=new HStyleButton(new HRect(200,0,220,20),this,{image:"outdent.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"outdent"});}
this.fonts=new HComboBox(new HRect(220,0,280,20),this);for(var i=0;i<this.styleButtonBarDefaults.styleBarSettings.fontFamilies.length;i++){this.fonts.addItem(this.styleButtonBarDefaults.styleBarSettings.fontFamilies[i]);}
this.fonts.selectedIndexChanged=this._6V;this.fontsizes=new HComboBox(new HRect(280,0,360,20),this);for(var i=0;i<this.styleButtonBarDefaults.styleBarSettings.fontSizes.length;i++){this.fontsizes.addItem(this.styleButtonBarDefaults.styleBarSettings.fontSizes[i]);}
this.fontsizes.selectedIndexChanged=this._6W;}
this.drawn=true;}},_6V:function(){if(this.parent.styleButtonBarDefaults.richtextview){var _4r=this.parent.styleButtonBarDefaults.richtextview.iframe().contentWindow;var _3z=_4r.document;HTextEdit.execCommand("fontname",false,this.selectedItem().label,_3z);}},_6W:function(){if(this.parent.styleButtonBarDefaults.richtextview){var _4r=this.parent.styleButtonBarDefaults.richtextview.iframe().contentWindow;var _3z=_4r.document;HTextEdit.execCommand("fontsize",false,this.selectedItem().label,_3z);}},refresh:function(){if(this.drawn){this.base();}}});HRichTextBar=HButton.extend({packageName:"richtext",componentName:"richtextbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HRichTextBar]';if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.base();if(!this.bButton){this.bButton=new HStyleButton(new HRect(0,0,20,20),this,{label:this.label,value:true,command:"bold"});this.bButton.draw();this.iButton=new HStyleButton(new HRect(20,0,40,20),this,{label:this.label,value:true,command:"italic"});this.iButton.draw();this.underlineButton=new HStyleButton(new HRect(40,0,60,20),this,{label:this.label,value:true,command:"underline"});this.underlineButton.draw();this.justifyleftButton=new HStyleButton(new HRect(60,0,80,20),this,{label:this.label,value:true,command:"justifyleft"});this.justifyleftButton.draw();this.justifycenterButton=new HStyleButton(new HRect(80,0,100,20),this,{label:this.label,value:true,command:"justifycenter"});this.justifycenterButton.draw();this.justifyrightButton=new HStyleButton(new HRect(100,0,120,20),this,{label:this.label,value:true,command:"justifyright"});this.justifyrightButton.draw();this.justifyfullButton=new HStyleButton(new HRect(120,0,140,20),this,{label:this.label,value:true,command:"justifyfull"});this.justifyfullButton.draw();this.ulButton=new HStyleButton(new HRect(140,0,160,20),this,{label:this.label,value:true,command:"insertunorderedlist"});this.ulButton.draw();this.olButton=new HStyleButton(new HRect(160,0,180,20),this,{label:this.label,value:true,command:"insertorderedlist"});this.olButton.draw();this.indentButton=new HStyleButton(new HRect(180,0,200,20),this,{label:this.label,value:true,command:"indent"});this.indentButton.draw();this.outdentButton=new HStyleButton(new HRect(200,0,220,20),this,{label:this.label,value:true,command:"outdent"});this.outdentButton.draw();}}
this.drawRect();},refresh:function(){if(this.bButton){this.bButton.refresh();this.iButton.refresh();this.underlineButton.refresh();this.justifyleftButton.refresh();this.justifycenterButton.refresh();this.justifyrightButton.refresh();this.justifyfullButton.refresh();this.ulButton.refresh();this.olButton.refresh();this.indentButton.refresh();this.outdentButton.refresh();}}});HRichTextView=HControl.extend({packageName:"richtext",componentName:"richtextview",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HRichTextView]';this.preserveTheme=true;this._2O=false;this._5d=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.base();},onIdle:function(){if(this.drawn){var _0x=ELEM.get(this.markupElemIds.control);if(!this._2O&&_0x.contentWindow&&_0x.contentWindow.document){_0x.contentWindow.document.designMode="on";this._2O=true;}
if(this._2O&&_0x.contentWindow.document.body){if(!this._5d){_0x.contentWindow.document.body.innerHTML=this.value;this._5d=true;}
var _0w=_0x.contentWindow.document.body.innerHTML;if(this.value!=_0w){this._4U=true;this.setValue(_0w);this._4U=false;}}}},setValue:function(_8q){if(!this._4U){if(this._2O){var _0x=ELEM.get(this.markupElemIds.control);if(_0x.contentWindow.document.body){_0x.contentWindow.document.body.innerHTML=_8q;}}}
this.base(_8q);},iframe:function(){return ELEM.get(this.markupElemIds.control);}});HRichTextControl=HControl.extend({packageName:"richtext",componentName:"richtextcontrol",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HRichTextControl]';this.preserveTheme=true;this._7f=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.base();this.drawRect();this.drawMarkup();if(!this._7f){this.barView=new HRichTextBar(new HRect(0,0,this.rect.width,20),this,{value:this.value});this.barView.draw();this.richTextView=new HRichTextView(new HRect(0,20,this.rect.width,this.rect.height),this,{value:(this.value||"editable text")});this.richTextView.draw();}
this.drawn=true;}
this.drawRect();}});HRichTextArea=HRichTextControl;HRichTextEditor=HRichTextControl;HStyleButton=HImageButton.extend({packageName:"richtext",componentName:"stylebutton",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HStyleButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},mouseUp:function(){if(this.styleButtonDefaults.richtextview){HTextEdit.execCommand(this.styleButtonDefaults.command,false,null,this.styleButtonDefaults.richtextview.iframe().contentWindow.document);}
this.base();}},{_6a:"imageview"});HStyleButtonBar=HView.extend({packageName:"richtext",componentName:"stylebuttonbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.styleButtonBarDefaults=new(Base.extend({}).extend(_2));this.type='[HStyleButtonBar]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();if(this.styleButtonBarDefaults.styleBarSettings){if(this.styleButtonBarDefaults.styleBarSettings.bold){this.bButton=new HStyleButton(new HRect(0,0,20,20),this,{image:"bold.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"bold"});}
if(this.styleButtonBarDefaults.styleBarSettings.italic){this.iButton=new HStyleButton(new HRect(20,0,40,20),this,{image:"italic.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"italic"});}
if(this.styleButtonBarDefaults.styleBarSettings.underline){this.underlineButton=new HStyleButton(new HRect(40,0,60,20),this,{image:"underline.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"underline"});}
if(this.styleButtonBarDefaults.styleBarSettings.justify){this.justifyleftButton=new HStyleButton(new HRect(60,0,80,20),this,{image:"justifyleft.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifyleft"});this.justifycenterButton=new HStyleButton(new HRect(80,0,100,20),this,{image:"justifycenter.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifycenter"});this.justifyrightButton=new HStyleButton(new HRect(100,0,120,20),this,{image:"justifyright.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifyright"});this.justifyfullButton=new HStyleButton(new HRect(120,0,140,20),this,{image:"justifyfull.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"justifyfull"});}
if(this.styleButtonBarDefaults.styleBarSettings.insertunorderedlist){this.ulButton=new HStyleButton(new HRect(140,0,160,20),this,{image:"insertunorderedlist.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"insertunorderedlist"});}
if(this.styleButtonBarDefaults.styleBarSettings.insertorderedlist){this.olButton=new HStyleButton(new HRect(160,0,180,20),this,{image:"insertorderedlist.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"insertorderedlist"});}
if(this.styleButtonBarDefaults.styleBarSettings.indent){this.indentButton=new HStyleButton(new HRect(180,0,200,20),this,{image:"indent.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"indent"});}
if(this.styleButtonBarDefaults.styleBarSettings.outdent){this.outdentButton=new HStyleButton(new HRect(200,0,220,20),this,{image:"outdent.gif",richtextview:this.styleButtonBarDefaults.richtextview,command:"outdent"});}
this.fonts=new HComboBox(new HRect(220,0,280,20),this);for(var i=0;i<this.styleButtonBarDefaults.styleBarSettings.fontFamilies.length;i++){this.fonts.addItem(this.styleButtonBarDefaults.styleBarSettings.fontFamilies[i]);}
this.fonts.selectedIndexChanged=this._6V;this.fontsizes=new HComboBox(new HRect(280,0,360,20),this);for(var i=0;i<this.styleButtonBarDefaults.styleBarSettings.fontSizes.length;i++){this.fontsizes.addItem(this.styleButtonBarDefaults.styleBarSettings.fontSizes[i]);}
this.fontsizes.selectedIndexChanged=this._6W;}
this.drawn=true;}},_6V:function(){if(this.parent.styleButtonBarDefaults.richtextview){var _4r=this.parent.styleButtonBarDefaults.richtextview.iframe().contentWindow;var _3z=_4r.document;HTextEdit.execCommand("fontname",false,this.selectedItem().label,_3z);}},_6W:function(){if(this.parent.styleButtonBarDefaults.richtextview){var _4r=this.parent.styleButtonBarDefaults.richtextview.iframe().contentWindow;var _3z=_4r.document;HTextEdit.execCommand("fontsize",false,this.selectedItem().label,_3z);}},refresh:function(){if(this.drawn){this.base();}}});HRichTextBar=HButton.extend({packageName:"richtext",componentName:"richtextbar",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HRichTextBar]';if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.base();if(!this.bButton){this.bButton=new HStyleButton(new HRect(0,0,20,20),this,{label:this.label,value:true,command:"bold"});this.bButton.draw();this.iButton=new HStyleButton(new HRect(20,0,40,20),this,{label:this.label,value:true,command:"italic"});this.iButton.draw();this.underlineButton=new HStyleButton(new HRect(40,0,60,20),this,{label:this.label,value:true,command:"underline"});this.underlineButton.draw();this.justifyleftButton=new HStyleButton(new HRect(60,0,80,20),this,{label:this.label,value:true,command:"justifyleft"});this.justifyleftButton.draw();this.justifycenterButton=new HStyleButton(new HRect(80,0,100,20),this,{label:this.label,value:true,command:"justifycenter"});this.justifycenterButton.draw();this.justifyrightButton=new HStyleButton(new HRect(100,0,120,20),this,{label:this.label,value:true,command:"justifyright"});this.justifyrightButton.draw();this.justifyfullButton=new HStyleButton(new HRect(120,0,140,20),this,{label:this.label,value:true,command:"justifyfull"});this.justifyfullButton.draw();this.ulButton=new HStyleButton(new HRect(140,0,160,20),this,{label:this.label,value:true,command:"insertunorderedlist"});this.ulButton.draw();this.olButton=new HStyleButton(new HRect(160,0,180,20),this,{label:this.label,value:true,command:"insertorderedlist"});this.olButton.draw();this.indentButton=new HStyleButton(new HRect(180,0,200,20),this,{label:this.label,value:true,command:"indent"});this.indentButton.draw();this.outdentButton=new HStyleButton(new HRect(200,0,220,20),this,{label:this.label,value:true,command:"outdent"});this.outdentButton.draw();}}
this.drawRect();},refresh:function(){if(this.bButton){this.bButton.refresh();this.iButton.refresh();this.underlineButton.refresh();this.justifyleftButton.refresh();this.justifycenterButton.refresh();this.justifyrightButton.refresh();this.justifyfullButton.refresh();this.ulButton.refresh();this.olButton.refresh();this.indentButton.refresh();this.outdentButton.refresh();}}});HRichTextView=HControl.extend({packageName:"richtext",componentName:"richtextview",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HRichTextView]';this.preserveTheme=true;this._2O=false;this._5d=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.base();},onIdle:function(){if(this.drawn){var _0x=ELEM.get(this.markupElemIds.control);if(!this._2O&&_0x.contentWindow&&_0x.contentWindow.document){_0x.contentWindow.document.designMode="on";this._2O=true;}
if(this._2O&&_0x.contentWindow.document.body){if(!this._5d){_0x.contentWindow.document.body.innerHTML=this.value;this._5d=true;}
var _0w=_0x.contentWindow.document.body.innerHTML;if(this.value!=_0w){this._4U=true;this.setValue(_0w);this._4U=false;}}}},setValue:function(_8q){if(!this._4U){if(this._2O){var _0x=ELEM.get(this.markupElemIds.control);if(_0x.contentWindow.document.body){_0x.contentWindow.document.body.innerHTML=_8q;}}}
this.base(_8q);},iframe:function(){return ELEM.get(this.markupElemIds.control);}});HRichTextControl=HControl.extend({packageName:"richtext",componentName:"richtextcontrol",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HRichTextControl]';this.preserveTheme=true;this._7f=false;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.base();this.drawRect();this.drawMarkup();if(!this._7f){this.barView=new HRichTextBar(new HRect(0,0,this.rect.width,20),this,{value:this.value});this.barView.draw();this.richTextView=new HRichTextView(new HRect(0,20,this.rect.width,this.rect.height),this,{value:(this.value||"editable text")});this.richTextView.draw();}
this.drawn=true;}
this.drawRect();}});HRichTextArea=HRichTextControl;HRichTextEditor=HRichTextControl;