
HDataBuffer=HClass.extend({constructor:function(_H,_02,_U,_2a,_j){this._H=_H;this._02=_02;this._U=_U;this._2a=_2a;this._2I=3;this._j=_j;},startingRow:function(){return this._H-this._j;},endingRow:function(){return this._02+this._j;},lowerLimit:function(){return this._U+parseInt(this._j/2,10);},upperLimit:function(){return this._U+(this._2I-1)*(this._02-this._H)-parseInt(this._j/2,10);},endBufferStartRow:function(){return(this._2I-1)*this._j;},getNewBottomRow:function(){return this._U+this._2I*this._j;},getNewBottomRowEnd:function(){return this._U+(this._2I+1)*this._j;},getNewTopRow:function(){return this._U-this._j;},getNewTopRowEnd:function(){return this._U;},getNewDownBufferIndexes:function(_0n){if(_0n==0){return[this._j,0];}else if(_0n==this._j){return[2*this._j,this._j];}else if(_0n==2*this._j){return[0,2*this._j];}},getNewUpBufferIndexes:function(_0n){if(_0n==0){return[2*this._j,this._j];}else if(_0n==2*this._j){return[this._j,0];}else if(_0n==this._j){return[0,2*this._j];}}});HLocalTableValue=HValue.extend({constructor:function(_4,_8q){this.initTable(_4,_8q);this.value=_8q.value;},initTable:function(_4,_8q){},set:function(_8q){},updateBuffer:function(_0D,_2b){},setCell:function(_4k,_8q,_A,_k){if(!this.value[_A]){return;}
this.value[_A][_k]=_8q;},getCell:function(_4k,_A,_k){if(!this.value[_A]){return"";}
return this.value[_A][_k];},numberOfRows:function(){return 100;},toXML:function(){}});HTableValue=HValue.extend({constructor:function(_4,_8q){this.initTable(_4,_8q);},initTable:function(_4,_8q){if(typeof _8q!="object"){throw"HTableValue error: value not an object";}
if(typeof _8q.value!="object"){throw"HTableValue error: object.value not an array";}
if(typeof _8q.length!="number"){throw"HTableValue error: object.length not a number";}
if(typeof _8q.startrow!="number"){throw"HTableValue error: object.startrow not a number";}
if(typeof _8q.endrow!="number"){throw"HTableValue error: object.endrow not a number";}
if(typeof _8q.columns!="object"){throw"HTableValue error: object.columns not an array";}
this.value=_8q.value;this.length=_8q.length;this.columns=_8q.columns;this.startrow=_8q.startrow;this.endrow=_8q.endrow;this.startrow1=0;this.endrow1=0;this.id=_4;this.type='[HTableValue]';this.views=[];this.startdatarow=this.startrow;this.enddatarow=this.endrow;this.datalength=this.endrow-(this.startrow-1);this.gettingData=false;this.gettingData1=false;this.gettingDataInterrupted=false;this.gettingDataInterrupted1=false;this.index1=0;this.index2=0;this.valueRequested=undefined;HValueManager.add(_4,this);},set:function(_8q){if(this.valueRequested==1){this.value1=_8q;this.gettingData1=false;}else if(this.valueRequested==0){this.value=_8q;this.gettingData=false;}
if(this.gettingDataInterrupted){this.tableControl.reloadData();this.gettingDataInterrupted=false;}
if(this.gettingDataInterrupted1){this.tableControl.reloadData();this.gettingDataInterrupted1=false;}
if(this.reloading==true){this.tableControl.reloadData();this.reloading=false;}},updateBuffer:function(_0D,_2b){var _j=this.datalength;var _1o=undefined;if(this.startdatarow-1<=_0D&&_2b<=this.enddatarow-1){var _4d;var _4c;if(this.startrow-1<=_0D&&_2b<=this.endrow-1){_4d=this.startrow-1+parseInt(_j/4,10);_4c=this.endrow-1-parseInt(_j/4,10);_1o=0;}else if((this.startrow1&&this.endrow1)&&this.startrow1-1<=_0D&&_2b<=this.endrow1-1){_4d=this.startrow1-1+parseInt(_j/4,10);_4c=this.endrow1-1-parseInt(_j/4,10);_1o=1;}
if(_2b>_4c){if(_1o==0&&this.startrow1<this.startrow){var _x=this.endrow+1;var _D=this.endrow+_j;if(_D>this.length){_D=this.length;}
this.startrow1=_x;this.endrow1=_D;this.startrow2=this.startrow1;this.endrow2=this.endrow1;window.status="going down 0 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.startdatarow=this.startrow;this.enddatarow=this.endrow1;this.valueRequested=1;this.gettingData1=true;HValueManager.changed(this);}
if(_1o==1&&this.startrow<this.startrow1){var _x=this.endrow1+1;var _D=this.endrow1+_j;if(_D>this.length){_D=this.length;}
this.startrow=_x;this.endrow=_D;this.startrow2=this.startrow;this.endrow2=this.endrow;window.status="going down 1 "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" ";this.startdatarow=this.startrow1;this.enddatarow=this.endrow;this.valueRequested=0;this.gettingData=true;HValueManager.changed(this);}}
if(_0D<_4d){if(this.startrow-1==0&&_1o==0){}else{if(_1o==0&&this.startrow<this.startrow1){var _x=this.startrow-_j;var _D=this.startrow-1;if(_x<1){_x=1;}
this.startrow1=_x;this.endrow1=_D;this.startrow2=this.startrow1;this.endrow2=this.endrow1;this.startdatarow=this.startrow1;window.status="going up 0 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.enddatarow=this.endrow;this.valueRequested=1;this.gettingData1=true;HValueManager.changed(this);}
if(_1o==1&&this.startrow1<this.startrow){var _x=this.startrow1-_j;var _D=this.startrow1-1;if(_x<1){_x=1;}
this.startrow=_x;this.endrow=_D;this.startrow2=this.startrow;this.endrow2=this.endrow;this.startdatarow=this.startrow;this.enddatarow=this.endrow1;window.status="going up 1 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.valueRequested=0;this.gettingData=true;HValueManager.changed(this);}}}}else{var _8g=_2b-_0D;var _x=_0D-parseInt(_j/2,10)+parseInt(_8g/2,10);if(_x<1){_x=1;}
var _D=_x+_j-1;if(_D>this.length){_D=this.length;}
this.startrow=_x;this.endrow=_D;this.startrow1=undefined;this.endrow1=undefined;this.startrow2=this.startrow;this.endrow2=this.endrow;this.startdatarow=_x;this.enddatarow=_D;this.valueRequested=0;this.gettingData=true;this.reloading=true;HValueManager.changed(this);}},setCell:function(_4k,_8q,_A,_k){this.value[_A][_k]=_8q;},getCell:function(_4k,_A,_k){if(this.startrow-1<=_A&&_A<=this.endrow-1){if(this.gettingData){this.gettingDataInterrupted=true;}else{if(this.value[_A-(this.startrow-1)]){return this.value[_A-(this.startrow-1)][_k];}}}else if(this.startrow1-1<=_A&&_A<=this.endrow1-1){if(this.gettingData1){this.gettingDataInterrupted1=true;}else{if(this.value1&&this.value1[_A-(this.startrow1-1)]){return this.value1[_A-(this.startrow1-1)][_k];}}}
return"-";},numberOfRows:function(){return this.length;},toXML:function(_0K){var _1m=this.id;var _5P="";for(var _k=0;_k<this.columns.length;_k++){_5P+='<getrows column="'+this.columns[_k]+'" startrow="'+this.startrow2+'" endrow="'+this.endrow2+'" />';}
return'<tablevalue length="'+this.columns.length+'" id="'+_1m+'" order="'+_0K+'">'+_5P+'</tablevalue>';}});HTableHeaderColumn=HControl.extend({packageName:"table",componentName:"tableheadercolumn",constructor:function(_1,_g,_2){this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;this.type='[HTableHeaderColumn]';this._6b="tableheadercolumnlabel";this._87="tableheaderselected";this._86="tableheaderorder";this.preserveTheme=true;this.setMouseUp(true);this.setDraggable(true);this.options=this.parent.parent.tableViewDefaults;this._4b();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(!this._3P){this._3P=ELEM.bindId(this._6b+this.elemId);this._4e=ELEM.bindId(this._87+this.elemId);this._1G=ELEM.bindId(this._86+this.elemId);}
if(this._3P){ELEM.setHTML(this._3P,this.label);}},_7L:function(){_00.direction=!_00.direction;this.toggleCSSClass(ELEM.get(this._1G),'order-dn',!_00.direction);this.toggleCSSClass(ELEM.get(this._1G),'order-up',_00.direction);for(var _35=0;_35<this.parent.parent.tableHeaderColumns.length;_35++){var _41=this.parent.parent.tableHeaderColumns[_35]._4e;if(_41&&(_41!=this._9k)){ELEM.setStyle(_41,'visibility','hidden');}
var _42=this.parent.parent.tableHeaderColumns[_35]._1G;if(_42&&(_42!=this._1G)){ELEM.setStyle(_42,'visibility','hidden');}}
if(this._4e){ELEM.setStyle(this._4e,'visibility','inherit');}
if(this._1G){ELEM.setStyle(this._1G,'visibility','inherit');}
var _d=this.parent.parent.tableHeaderColumns.indexOf(this);_00.column=_d;this.parent.parent.data.value.sort(_00);this.parent.parent.reloadData();},startDrag:function(_6,_a){this.base(_6,_a);this._4b();_6-=this.parent.pageX();_a-=this.parent.pageY();this._0n=this.parent.parent.tableHeaderColumns.indexOf(this);this._3y=false;this._2t=new HPoint(_6,_a);this._38=new HPoint(_6,_a);this._2u=new HRect(this.rect);this._4b();var _43=this._2t.subtract(this._2u.leftTop);if(this._0c.resizeWRect.contains(_43)){this._0t=_6-this.rect.left;this._0c.resizeW=true;}else if(this._0c.resizeERect.contains(_43)){this._0t=_6-this.rect.right;this._0c.resizeE=true;}else if(this._0c.dragColumnRect.contains(_43)){this._0t=this._2t.subtract(this._2u.leftTop);this._0c.dragColumn=true;}
this.bringToFront();this._4T=true;this.doDrag(_6,_a);this._4T=false;},doDrag:function(_6,_a){if(this._4T==false){_6-=this.parent.pageX();_a-=this.parent.pageY();}
var _0R=this.parent.parent;var _v;var _3u=new HPoint(_6,_a);var _d=this.parent.parent.tableHeaderColumns.indexOf(this);var _k=this.parent.parent.tableColumns[_d];if(!this._38.equals(_3u)){if(this._0c.resizeW==true){if(_d==0){return;}
_v=_6-this._0t;this.rect.left=_v;this.rect.updateSecondaryValues();this.drawRect();_k.rect.left=_v+this.parent.parent.scrollLeft();_k.rect.updateSecondaryValues();_k.drawRect();this.parent.parent._O[_d]=_v+this.parent.parent.scrollLeft();_0R._r[_d].width=this.rect.width;var _2m=this.parent.parent.tableColumns[(_d-1)];if(_2m){_2m.rect.right=_v+this.parent.parent.scrollLeft();_2m.rect.updateSecondaryValues();_2m.drawRect();this.parent.parent._r[_d-1].width=_2m.rect.width;_45=this.parent.parent.tableHeaderColumns[_d-1];_45.rect.right=_v;_45.rect.updateSecondaryValues();_45.drawRect();}}else if(this._0c.resizeE==true){var l=this.parent.parent.tableColumns.length;if(_d==l-1){return;}
_v=_6-this._0t;this.rect.right=_v;this.rect.updateSecondaryValues();this.drawRect();_k.rect.right=_v+this.parent.parent.scrollLeft();_k.rect.updateSecondaryValues();_k.drawRect();this.parent.parent._O[_d+1]=_v+this.parent.parent.scrollLeft();this.parent.parent._r[_d].width=this.rect.width;var _2l=this.parent.parent.tableColumns[(_d+1)];if(_2l){_2l.rect.left=_v+this.parent.parent.scrollLeft();_2l.rect.updateSecondaryValues();_2l.drawRect();this.parent.parent._r[_d+1].width=_2l.rect.width;_3Z=this.parent.parent.tableHeaderColumns[_d+1];_3Z.rect.left=_v;_3Z.rect.updateSecondaryValues();_3Z.drawRect();}}else if(this._0c.dragColumn==true){_v=_3u.subtract(this._0t);this.setStyle('opacity',0.4);this.setStyle('left',_v.x+"px");_k.setStyle('opacity',0.4);_k.setStyle('left',_v.x+this.parent.parent.scrollLeft()+"px");}
this._3y=true;if(this._0c.dragColumn==false){}
this._38=_3u;}},endDrag:function(_6,_a){this.base(_6,_a);this.doDrag(_6,_a);_6-=this.parent.pageX();_a-=this.parent.pageY();var _0R=this.parent.parent;this.setStyle('opacity',1.0);_0R.tableColumns[this._0n].setStyle('opacity',1.0);var _8=false;var i,l=_0R.tableHeaderColumns.length;for(i=0;i<l;i++){if(_0R.tableHeaderColumns[i].rect.left<=_6&&_6<=_0R.tableHeaderColumns[i].rect.right&&_0R.tableHeaderColumns[i]!=this){if(this._0c.dragColumn==true){_0R.moveColumn(this._0n,i);_8=true;}}}
if(_8==false&&this._0c.dragColumn==true){this.setStyle('left',this._2u.left+"px");_0R.tableColumns[this._0n].setStyle('left',this._2u.left+"px");this._7L();}},drawRect:function(){this._3y=false;this.base();},_4b:function(){this._0c={dragColumn:false,resizeW:false,resizeE:false,dragColumnRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,0,this.options.resizeW,this.rect.height),resizeERect:new HRect(this.rect.width-this.options.resizeE,0,this.rect.width,this.rect.height)};}});_00=function(a,b){if(a[_00.column]<b[_00.column]){return(_00.direction)?-1:1;}
if(a[_00.column]>b[_00.column]){return(_00.direction)?1:-1;}
return 0;};_00.direction=true;_00.column=0;HTableHeaderView=HControl.extend({packageName:"table",componentName:"tableheaderview",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HTableHeaderView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){this.base();}});HTableCornerView=HView.extend({packageName:"table",componentName:"tablecornerview",constructor:function(_1,_g){if(this.isinherited){this.base(_1,_g);}
else{this.isinherited=true;this.base(_1,_g);this.isinherited=false;}
this.type='[HTableCornerView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawMarkup();}
this.drawRect();}});HTableColumn=HControl.extend({packageName:"table",componentName:"tablecolumn",constructor:function(_1,_g,_2){_2=new(Base.extend({dataView:"",headerView:""}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HTableColumn]';this.width=_1.width;this.dataView=this.options.dataView;this.headerView=this.options.headerView;this.index=this.options.index;this.preserveTheme=true;if(!this.isinherited){this.draw();}}});_6l=function(_d,_s,_13,_1x,_3J){this.index=_d;this.width=_s;this.string=_13;this.dataView=_1x;this.headerView=_3J;this.headerCreated=false;this.created=false;};HTableControl=HControl.extend({packageName:"table",componentName:"tablecontrol",calculateDimensions:function(){this._1W();},updateColumns:function(){this._2z();},constructor:function(_1,_g,_2){_2=new(Base.extend({rowHeight:21,headerViewHeight:21,bufferLength:3,resizeW:5,resizeE:5}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.tableViewDefaults=_2;this.type='[HTableControl]';this.preserveTheme=true;this.tableColumns=[];this._O=[];this.tableHeaderColumns=[];this._r=[];this._1d=[];this._0Q=[];this.numberOfRows=0;this._1c=0;this._4P=0;this._1e=0;this._25=0;this._08=0;this.headerView=new HTableHeaderView(new HRect(0,0,this.rect.width,this.options.headerViewHeight),this);this.tableView=new HView(new HRect(0,this.options.headerViewHeight,this.rect.width,this.rect.height),this);this.tableView.setStyle("overflow","auto");this.columnsView=new HView(new HRect(0,0,this.rect.width,this.rect.height-this.options.headerViewHeight),this.tableView);var _6E=new HRect(this.rect.width-18,0,this.rect.width,this.options.headerViewHeight);this.cornerView=new HTableCornerView(_6E,this);this._0a=new HRect(this.tableView.rect);this._0a.offsetTo(0,0);if(!this.isinherited){this.draw();}},onIdle:function(){this._2H();this.base();},_2z:function(){if(this.numberOfRows==0||this._r.length==0){return;}
var _H=this._5O(new HPoint(0,this._0a.top));var _02=this._5O(new HPoint(0,this._0a.bottom));var _3a,_2P;var _3i=this._0a.left;var i=0;while(i<this._r.length&&_3i>this._O[i]){i++;}
_3a=i-1;if(_3a==-1){_3a=0;}
var _3i=this._0a.right;while(i<this._r.length&&_3i>this._O[i]){i++;}
_2P=i-1;if(_2P==-1){_2P=this._r.length-1;}
var _5G=false;var _5H=false;var _4w=false;for(var i=_3a;i<=_2P;i++){if(this._r[i].created==false){var _6y=new HRect(this._O[i],0,this._O[i]+this._r[i].width,this.columnsView.rect.height);this.tableColumns[i]=new HTableColumn(_6y,this.columnsView,{label:this._r[i].string,dataView:this._r[i].dataView,headerView:this._r[i].headerView});this._r[i].created=true;}
if(this._r[i].headerCreated==false){var _75=new HRect(this._O[i]-this._0a.left,0,this._O[i]-this._0a.left+this._r[i].width,this.options.headerViewHeight);this.tableHeaderColumns[i]=new HTableHeaderColumn(_75,this.headerView,{label:this._r[i].string});this.tableHeaderColumns[i].draw();this._r[i].headerCreated=true;}
var _0E=this.tableColumns[i];var _4m=this.tableHeaderColumns[i];if(this._1d[i]==false){this._7e(i,_H,_02);this._1d[i]=true;}}
for(var i=0;i<this._r.length;i++){if(this._r[i].created==true){var _0E=this.tableColumns[i];var _4m=this.tableHeaderColumns[i];_4m.rect.offsetTo(this._O[i]-this._0a.left,0);_4m.drawRect();_0E.rect.set(this._O[i],0,this._O[i]+_0E.width,this.columnsView.rect.height);_0E.drawRect();if(!this._5L&&this._1c<=_H&&_H<this._1c+this.tableViewDefaults.bufferLength*this._08){var _F=new HDataBuffer(_H,_02,this._1c,this._4P,this._08);var _7E=_F.lowerLimit();var _7F=_F.upperLimit();if(_H>_7F){_5G=true;var _0C=this._1e;var _0S=_F.getNewBottomRow()*this.options.rowHeight;var _x=_F.getNewBottomRow();var _D=_F.getNewBottomRowEnd();this._4p(_0C,_x,_D,i,_0S,_0E);}else if(_H<=_7E){_5H=true;var _0C=this._25;var _0S=_F.getNewTopRow()*this.options.rowHeight;var _x=_F.getNewTopRow();var _D=_F.getNewTopRowEnd();this._4p(_0C,_x,_D,i,_0S,_0E);}}else{_4w=true;var _F=new HDataBuffer(_H,_02,0,0,this._08);var _U=_F.startRow();var _2a=_F.endRow();var _0C=0;var _0S=_U*this.options.rowHeight;this._4p(_0C,_U,_U+this._08*3,i,_0S,_0E);}}}
if(_5G==true){var _F=new HDataBuffer(_H,_02,0,0,this._08);var _2f=_F.getNewDownBufferIndexes(this._1e);this._1e=_2f[0];this._25=_2f[1];this._1c+=this._08;}
if(_5H==true){var _F=new HDataBuffer(_H,_02,0,0,this._08);var _2f=_F.getNewUpBufferIndexes(this._1e);this._1e=_2f[0];this._25=_2f[1];this._1c-=this._08;}
if(_4w==true){var _F=new HDataBuffer(_H,_02,0,0,this._08);this._1e=0;this._25=_F.endBufferStartRow();this._1c=_H-this._08;}
this.data.updateBuffer(_H,_02);},_4p:function(_0C,_7N,_6Q,_1t,_5m,_0N){var _8q;for(var _1j=_7N;_1j<_6Q;_1j++){_8q=this.data.getCell(this,_1j,this._r[_1t].index);_8q=(_8q)?_8q:"1";this._0Q[_1t][_0C].setValue(_8q);this._0Q[_1t][_0C].rect.offsetTo(0,_5m);this._0Q[_1t][_0C].drawRect();_5m+=this.options.rowHeight;_0C++;}},_7e:function(_1t,_H,_02){var _0E=this.tableColumns[_1t];if(!this._08){this._08=_02-_H;}
var _F=new HDataBuffer(_H,_02,0,0,this._08);var _U=_F.startRow();var _2a=_F.endRow();this._1c=_U;this._4P=_2a;var _0S=_U*this.options.rowHeight;this._25=_F.endBufferStartRow();this._0Q[_1t]=new Array();var _1x=_0E.dataView;if(typeof _1x=="string"){_1x=ITextControl;}
var _f,_6i,_8q;for(var _1j=_U;_1j<_2a;_1j++){_8q=this.data.getCell(this,_1j,this._r[_1t].index);_8q=(_8q)?_8q:"1";_6i=new HRect(0,_0S,_0E.rect.width,_0S+this.options.rowHeight);_f=new _1x(_6i,_0E,{value:_8q});this._0Q[_1t].push(_f);_0S+=this.options.rowHeight;}},_1W:function(){var _3c=0,_81;if(this._r.length>0){var _s;this._O[0]=0;width=this._r[0].width;_3c+=width;for(var i=1;i<this._r.length;i++){this._O[i]=this._O[i-1]+width;width=this._r[i].width;_3c+=width;}}
_81=this.numberOfRows*this.options.rowHeight;this.columnsView.rect.setSize(_3c,_81);this.columnsView.drawRect();if(this.headerView){this.headerView.rect.setWidth(_3c);this.headerView.drawRect();}},_5O:function(_e){return parseInt(_e.y/this.options.rowHeight,10);},rowAtPoint:function(_e){var _a=_e.y;if(_a==0){return 0;}
_a-=this.options.headerViewHeight;return parseInt(_a/this.options.rowHeight,10);},addColumn:function(_d,_s,_C,_1x,_3J){var _k=new _6l(_d,_s,_C,_1x,_3J);this._r.push(_k);this._1d.push(false);},setData:function(_0d){this.data=_0d;this.data.tableControl=this;this.numberOfRows=this.data.numberOfRows();this._1W();},reloadData:function(_0d){this._1g=true;this._5L=true;this._2z();this._5L=false;this._1g=false;},removeColumn:function(_k){this._1g=true;var _d=this.tableColumns.indexOf(_k);this._r.splice(_d,1);this.tableHeaderColumns[_d].die();this.tableHeaderColumns.splice(_d,1);this.tableColumns[_d].die();this.tableColumns.splice(_d,1);this._0Q.splice(_d,1);this._1d.splice(_d,1);this._1W();this._2z();this._1g=false;},moveColumn:function(_1t,_2k){this._1g=true;var _0y=_1t;var _0Y=_2k;if(_0y<_0Y){var _84=_0Y;_0Y=_0y;_0y=_84;}
var _k=this._r[_0y];this._r.splice(_0y,1);this._r.splice(_0Y,0,_k);_k=this.tableColumns[_0y];this.tableColumns.splice(_0y,1);this.tableColumns.splice(_0Y,0,_k);_k=this.tableHeaderColumns[_0y];this.tableHeaderColumns.splice(_0y,1);this.tableHeaderColumns.splice(_0Y,0,_k);_k=this._1d[_0y];this._1d.splice(_0y,1);this._1d.splice(_0Y,0,_k);_k=this._0Q[_0y];this._0Q.splice(_0y,1);this._0Q.splice(_0Y,0,_k);this._1W();this._2z();this._1g=false;},scrollLeft:function(){return this._0a.left;},scrollTop:function(){return this._0a.top;},_2H:function(){var _4l=ELEM.get(this.tableView.elemId);if(!_4l){throw("Error: HTableControl element not found");}
var _7u=new HRect(this._0a);this._0a.offsetTo(parseInt(_4l.scrollLeft,10),parseInt(_4l.scrollTop,10));if(!_7u.equals(this._0a)){this._1g=true;this._2z();this._1g=false;}}});HDataBuffer=HClass.extend({constructor:function(_H,_02,_U,_2a,_j){this._H=_H;this._02=_02;this._U=_U;this._2a=_2a;this._2I=3;this._j=_j;},startingRow:function(){return this._H-this._j;},endingRow:function(){return this._02+this._j;},lowerLimit:function(){return this._U+parseInt(this._j/2,10);},upperLimit:function(){return this._U+(this._2I-1)*(this._02-this._H)-parseInt(this._j/2,10);},endBufferStartRow:function(){return(this._2I-1)*this._j;},getNewBottomRow:function(){return this._U+this._2I*this._j;},getNewBottomRowEnd:function(){return this._U+(this._2I+1)*this._j;},getNewTopRow:function(){return this._U-this._j;},getNewTopRowEnd:function(){return this._U;},getNewDownBufferIndexes:function(_0n){if(_0n==0){return[this._j,0];}else if(_0n==this._j){return[2*this._j,this._j];}else if(_0n==2*this._j){return[0,2*this._j];}},getNewUpBufferIndexes:function(_0n){if(_0n==0){return[2*this._j,this._j];}else if(_0n==2*this._j){return[this._j,0];}else if(_0n==this._j){return[0,2*this._j];}}});HLocalTableValue=HValue.extend({constructor:function(_4,_8q){this.initTable(_4,_8q);this.value=_8q.value;},initTable:function(_4,_8q){},set:function(_8q){},updateBuffer:function(_0D,_2b){},setCell:function(_4k,_8q,_A,_k){if(!this.value[_A]){return;}
this.value[_A][_k]=_8q;},getCell:function(_4k,_A,_k){if(!this.value[_A]){return"";}
return this.value[_A][_k];},numberOfRows:function(){return 100;},toXML:function(){}});HTableValue=HValue.extend({constructor:function(_4,_8q){this.initTable(_4,_8q);},initTable:function(_4,_8q){if(typeof _8q!="object"){throw"HTableValue error: value not an object";}
if(typeof _8q.value!="object"){throw"HTableValue error: object.value not an array";}
if(typeof _8q.length!="number"){throw"HTableValue error: object.length not a number";}
if(typeof _8q.startrow!="number"){throw"HTableValue error: object.startrow not a number";}
if(typeof _8q.endrow!="number"){throw"HTableValue error: object.endrow not a number";}
if(typeof _8q.columns!="object"){throw"HTableValue error: object.columns not an array";}
this.value=_8q.value;this.length=_8q.length;this.columns=_8q.columns;this.startrow=_8q.startrow;this.endrow=_8q.endrow;this.startrow1=0;this.endrow1=0;this.id=_4;this.type='[HTableValue]';this.views=[];this.startdatarow=this.startrow;this.enddatarow=this.endrow;this.datalength=this.endrow-(this.startrow-1);this.gettingData=false;this.gettingData1=false;this.gettingDataInterrupted=false;this.gettingDataInterrupted1=false;this.index1=0;this.index2=0;this.valueRequested=undefined;HValueManager.add(_4,this);},set:function(_8q){if(this.valueRequested==1){this.value1=_8q;this.gettingData1=false;}else if(this.valueRequested==0){this.value=_8q;this.gettingData=false;}
if(this.gettingDataInterrupted){this.tableControl.reloadData();this.gettingDataInterrupted=false;}
if(this.gettingDataInterrupted1){this.tableControl.reloadData();this.gettingDataInterrupted1=false;}
if(this.reloading==true){this.tableControl.reloadData();this.reloading=false;}},updateBuffer:function(_0D,_2b){var _j=this.datalength;var _1o=undefined;if(this.startdatarow-1<=_0D&&_2b<=this.enddatarow-1){var _4d;var _4c;if(this.startrow-1<=_0D&&_2b<=this.endrow-1){_4d=this.startrow-1+parseInt(_j/4,10);_4c=this.endrow-1-parseInt(_j/4,10);_1o=0;}else if((this.startrow1&&this.endrow1)&&this.startrow1-1<=_0D&&_2b<=this.endrow1-1){_4d=this.startrow1-1+parseInt(_j/4,10);_4c=this.endrow1-1-parseInt(_j/4,10);_1o=1;}
if(_2b>_4c){if(_1o==0&&this.startrow1<this.startrow){var _x=this.endrow+1;var _D=this.endrow+_j;if(_D>this.length){_D=this.length;}
this.startrow1=_x;this.endrow1=_D;this.startrow2=this.startrow1;this.endrow2=this.endrow1;window.status="going down 0 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.startdatarow=this.startrow;this.enddatarow=this.endrow1;this.valueRequested=1;this.gettingData1=true;HValueManager.changed(this);}
if(_1o==1&&this.startrow<this.startrow1){var _x=this.endrow1+1;var _D=this.endrow1+_j;if(_D>this.length){_D=this.length;}
this.startrow=_x;this.endrow=_D;this.startrow2=this.startrow;this.endrow2=this.endrow;window.status="going down 1 "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" ";this.startdatarow=this.startrow1;this.enddatarow=this.endrow;this.valueRequested=0;this.gettingData=true;HValueManager.changed(this);}}
if(_0D<_4d){if(this.startrow-1==0&&_1o==0){}else{if(_1o==0&&this.startrow<this.startrow1){var _x=this.startrow-_j;var _D=this.startrow-1;if(_x<1){_x=1;}
this.startrow1=_x;this.endrow1=_D;this.startrow2=this.startrow1;this.endrow2=this.endrow1;this.startdatarow=this.startrow1;window.status="going up 0 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.enddatarow=this.endrow;this.valueRequested=1;this.gettingData1=true;HValueManager.changed(this);}
if(_1o==1&&this.startrow1<this.startrow){var _x=this.startrow1-_j;var _D=this.startrow1-1;if(_x<1){_x=1;}
this.startrow=_x;this.endrow=_D;this.startrow2=this.startrow;this.endrow2=this.endrow;this.startdatarow=this.startrow;this.enddatarow=this.endrow1;window.status="going up 1 "+"this.startrow "+this.startrow+" "+"this.endrow "+this.endrow+" "+"this.startrow1 "+this.startrow1+" "+"this.endrow1 "+this.endrow1+" ";this.valueRequested=0;this.gettingData=true;HValueManager.changed(this);}}}}else{var _8g=_2b-_0D;var _x=_0D-parseInt(_j/2,10)+parseInt(_8g/2,10);if(_x<1){_x=1;}
var _D=_x+_j-1;if(_D>this.length){_D=this.length;}
this.startrow=_x;this.endrow=_D;this.startrow1=undefined;this.endrow1=undefined;this.startrow2=this.startrow;this.endrow2=this.endrow;this.startdatarow=_x;this.enddatarow=_D;this.valueRequested=0;this.gettingData=true;this.reloading=true;HValueManager.changed(this);}},setCell:function(_4k,_8q,_A,_k){this.value[_A][_k]=_8q;},getCell:function(_4k,_A,_k){if(this.startrow-1<=_A&&_A<=this.endrow-1){if(this.gettingData){this.gettingDataInterrupted=true;}else{if(this.value[_A-(this.startrow-1)]){return this.value[_A-(this.startrow-1)][_k];}}}else if(this.startrow1-1<=_A&&_A<=this.endrow1-1){if(this.gettingData1){this.gettingDataInterrupted1=true;}else{if(this.value1&&this.value1[_A-(this.startrow1-1)]){return this.value1[_A-(this.startrow1-1)][_k];}}}
return"-";},numberOfRows:function(){return this.length;},toXML:function(_0K){var _1m=this.id;var _5P="";for(var _k=0;_k<this.columns.length;_k++){_5P+='<getrows column="'+this.columns[_k]+'" startrow="'+this.startrow2+'" endrow="'+this.endrow2+'" />';}
return'<tablevalue length="'+this.columns.length+'" id="'+_1m+'" order="'+_0K+'">'+_5P+'</tablevalue>';}});HTableHeaderColumn=HControl.extend({packageName:"table",componentName:"tableheadercolumn",constructor:function(_1,_g,_2){this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;this.type='[HTableHeaderColumn]';this._6b="tableheadercolumnlabel";this._87="tableheaderselected";this._86="tableheaderorder";this.preserveTheme=true;this.setMouseUp(true);this.setDraggable(true);this.options=this.parent.parent.tableViewDefaults;this._4b();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(!this._3P){this._3P=ELEM.bindId(this._6b+this.elemId);this._4e=ELEM.bindId(this._87+this.elemId);this._1G=ELEM.bindId(this._86+this.elemId);}
if(this._3P){ELEM.setHTML(this._3P,this.label);}},_7L:function(){_00.direction=!_00.direction;this.toggleCSSClass(ELEM.get(this._1G),'order-dn',!_00.direction);this.toggleCSSClass(ELEM.get(this._1G),'order-up',_00.direction);for(var _35=0;_35<this.parent.parent.tableHeaderColumns.length;_35++){var _41=this.parent.parent.tableHeaderColumns[_35]._4e;if(_41&&(_41!=this._9k)){ELEM.setStyle(_41,'visibility','hidden');}
var _42=this.parent.parent.tableHeaderColumns[_35]._1G;if(_42&&(_42!=this._1G)){ELEM.setStyle(_42,'visibility','hidden');}}
if(this._4e){ELEM.setStyle(this._4e,'visibility','inherit');}
if(this._1G){ELEM.setStyle(this._1G,'visibility','inherit');}
var _d=this.parent.parent.tableHeaderColumns.indexOf(this);_00.column=_d;this.parent.parent.data.value.sort(_00);this.parent.parent.reloadData();},startDrag:function(_6,_a){this.base(_6,_a);this._4b();_6-=this.parent.pageX();_a-=this.parent.pageY();this._0n=this.parent.parent.tableHeaderColumns.indexOf(this);this._3y=false;this._2t=new HPoint(_6,_a);this._38=new HPoint(_6,_a);this._2u=new HRect(this.rect);this._4b();var _43=this._2t.subtract(this._2u.leftTop);if(this._0c.resizeWRect.contains(_43)){this._0t=_6-this.rect.left;this._0c.resizeW=true;}else if(this._0c.resizeERect.contains(_43)){this._0t=_6-this.rect.right;this._0c.resizeE=true;}else if(this._0c.dragColumnRect.contains(_43)){this._0t=this._2t.subtract(this._2u.leftTop);this._0c.dragColumn=true;}
this.bringToFront();this._4T=true;this.doDrag(_6,_a);this._4T=false;},doDrag:function(_6,_a){if(this._4T==false){_6-=this.parent.pageX();_a-=this.parent.pageY();}
var _0R=this.parent.parent;var _v;var _3u=new HPoint(_6,_a);var _d=this.parent.parent.tableHeaderColumns.indexOf(this);var _k=this.parent.parent.tableColumns[_d];if(!this._38.equals(_3u)){if(this._0c.resizeW==true){if(_d==0){return;}
_v=_6-this._0t;this.rect.left=_v;this.rect.updateSecondaryValues();this.drawRect();_k.rect.left=_v+this.parent.parent.scrollLeft();_k.rect.updateSecondaryValues();_k.drawRect();this.parent.parent._O[_d]=_v+this.parent.parent.scrollLeft();_0R._r[_d].width=this.rect.width;var _2m=this.parent.parent.tableColumns[(_d-1)];if(_2m){_2m.rect.right=_v+this.parent.parent.scrollLeft();_2m.rect.updateSecondaryValues();_2m.drawRect();this.parent.parent._r[_d-1].width=_2m.rect.width;_45=this.parent.parent.tableHeaderColumns[_d-1];_45.rect.right=_v;_45.rect.updateSecondaryValues();_45.drawRect();}}else if(this._0c.resizeE==true){var l=this.parent.parent.tableColumns.length;if(_d==l-1){return;}
_v=_6-this._0t;this.rect.right=_v;this.rect.updateSecondaryValues();this.drawRect();_k.rect.right=_v+this.parent.parent.scrollLeft();_k.rect.updateSecondaryValues();_k.drawRect();this.parent.parent._O[_d+1]=_v+this.parent.parent.scrollLeft();this.parent.parent._r[_d].width=this.rect.width;var _2l=this.parent.parent.tableColumns[(_d+1)];if(_2l){_2l.rect.left=_v+this.parent.parent.scrollLeft();_2l.rect.updateSecondaryValues();_2l.drawRect();this.parent.parent._r[_d+1].width=_2l.rect.width;_3Z=this.parent.parent.tableHeaderColumns[_d+1];_3Z.rect.left=_v;_3Z.rect.updateSecondaryValues();_3Z.drawRect();}}else if(this._0c.dragColumn==true){_v=_3u.subtract(this._0t);this.setStyle('opacity',0.4);this.setStyle('left',_v.x+"px");_k.setStyle('opacity',0.4);_k.setStyle('left',_v.x+this.parent.parent.scrollLeft()+"px");}
this._3y=true;if(this._0c.dragColumn==false){}
this._38=_3u;}},endDrag:function(_6,_a){this.base(_6,_a);this.doDrag(_6,_a);_6-=this.parent.pageX();_a-=this.parent.pageY();var _0R=this.parent.parent;this.setStyle('opacity',1.0);_0R.tableColumns[this._0n].setStyle('opacity',1.0);var _8=false;var i,l=_0R.tableHeaderColumns.length;for(i=0;i<l;i++){if(_0R.tableHeaderColumns[i].rect.left<=_6&&_6<=_0R.tableHeaderColumns[i].rect.right&&_0R.tableHeaderColumns[i]!=this){if(this._0c.dragColumn==true){_0R.moveColumn(this._0n,i);_8=true;}}}
if(_8==false&&this._0c.dragColumn==true){this.setStyle('left',this._2u.left+"px");_0R.tableColumns[this._0n].setStyle('left',this._2u.left+"px");this._7L();}},drawRect:function(){this._3y=false;this.base();},_4b:function(){this._0c={dragColumn:false,resizeW:false,resizeE:false,dragColumnRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,0,this.options.resizeW,this.rect.height),resizeERect:new HRect(this.rect.width-this.options.resizeE,0,this.rect.width,this.rect.height)};}});_00=function(a,b){if(a[_00.column]<b[_00.column]){return(_00.direction)?-1:1;}
if(a[_00.column]>b[_00.column]){return(_00.direction)?1:-1;}
return 0;};_00.direction=true;_00.column=0;HTableHeaderView=HControl.extend({packageName:"table",componentName:"tableheaderview",constructor:function(_1,_g,_2){if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HTableHeaderView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){this.base();}});HTableCornerView=HView.extend({packageName:"table",componentName:"tablecornerview",constructor:function(_1,_g){if(this.isinherited){this.base(_1,_g);}
else{this.isinherited=true;this.base(_1,_g);this.isinherited=false;}
this.type='[HTableCornerView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawMarkup();}
this.drawRect();}});HTableColumn=HControl.extend({packageName:"table",componentName:"tablecolumn",constructor:function(_1,_g,_2){_2=new(Base.extend({dataView:"",headerView:""}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.type='[HTableColumn]';this.width=_1.width;this.dataView=this.options.dataView;this.headerView=this.options.headerView;this.index=this.options.index;this.preserveTheme=true;if(!this.isinherited){this.draw();}}});_6l=function(_d,_s,_13,_1x,_3J){this.index=_d;this.width=_s;this.string=_13;this.dataView=_1x;this.headerView=_3J;this.headerCreated=false;this.created=false;};HTableControl=HControl.extend({packageName:"table",componentName:"tablecontrol",calculateDimensions:function(){this._1W();},updateColumns:function(){this._2z();},constructor:function(_1,_g,_2){_2=new(Base.extend({rowHeight:21,headerViewHeight:21,bufferLength:3,resizeW:5,resizeE:5}).extend(_2));if(this.isinherited){this.base(_1,_g,_2);}
else{this.isinherited=true;this.base(_1,_g,_2);this.isinherited=false;}
this.tableViewDefaults=_2;this.type='[HTableControl]';this.preserveTheme=true;this.tableColumns=[];this._O=[];this.tableHeaderColumns=[];this._r=[];this._1d=[];this._0Q=[];this.numberOfRows=0;this._1c=0;this._4P=0;this._1e=0;this._25=0;this._08=0;this.headerView=new HTableHeaderView(new HRect(0,0,this.rect.width,this.options.headerViewHeight),this);this.tableView=new HView(new HRect(0,this.options.headerViewHeight,this.rect.width,this.rect.height),this);this.tableView.setStyle("overflow","auto");this.columnsView=new HView(new HRect(0,0,this.rect.width,this.rect.height-this.options.headerViewHeight),this.tableView);var _6E=new HRect(this.rect.width-18,0,this.rect.width,this.options.headerViewHeight);this.cornerView=new HTableCornerView(_6E,this);this._0a=new HRect(this.tableView.rect);this._0a.offsetTo(0,0);if(!this.isinherited){this.draw();}},onIdle:function(){this._2H();this.base();},_2z:function(){if(this.numberOfRows==0||this._r.length==0){return;}
var _H=this._5O(new HPoint(0,this._0a.top));var _02=this._5O(new HPoint(0,this._0a.bottom));var _3a,_2P;var _3i=this._0a.left;var i=0;while(i<this._r.length&&_3i>this._O[i]){i++;}
_3a=i-1;if(_3a==-1){_3a=0;}
var _3i=this._0a.right;while(i<this._r.length&&_3i>this._O[i]){i++;}
_2P=i-1;if(_2P==-1){_2P=this._r.length-1;}
var _5G=false;var _5H=false;var _4w=false;for(var i=_3a;i<=_2P;i++){if(this._r[i].created==false){var _6y=new HRect(this._O[i],0,this._O[i]+this._r[i].width,this.columnsView.rect.height);this.tableColumns[i]=new HTableColumn(_6y,this.columnsView,{label:this._r[i].string,dataView:this._r[i].dataView,headerView:this._r[i].headerView});this._r[i].created=true;}
if(this._r[i].headerCreated==false){var _75=new HRect(this._O[i]-this._0a.left,0,this._O[i]-this._0a.left+this._r[i].width,this.options.headerViewHeight);this.tableHeaderColumns[i]=new HTableHeaderColumn(_75,this.headerView,{label:this._r[i].string});this.tableHeaderColumns[i].draw();this._r[i].headerCreated=true;}
var _0E=this.tableColumns[i];var _4m=this.tableHeaderColumns[i];if(this._1d[i]==false){this._7e(i,_H,_02);this._1d[i]=true;}}
for(var i=0;i<this._r.length;i++){if(this._r[i].created==true){var _0E=this.tableColumns[i];var _4m=this.tableHeaderColumns[i];_4m.rect.offsetTo(this._O[i]-this._0a.left,0);_4m.drawRect();_0E.rect.set(this._O[i],0,this._O[i]+_0E.width,this.columnsView.rect.height);_0E.drawRect();if(!this._5L&&this._1c<=_H&&_H<this._1c+this.tableViewDefaults.bufferLength*this._08){var _F=new HDataBuffer(_H,_02,this._1c,this._4P,this._08);var _7E=_F.lowerLimit();var _7F=_F.upperLimit();if(_H>_7F){_5G=true;var _0C=this._1e;var _0S=_F.getNewBottomRow()*this.options.rowHeight;var _x=_F.getNewBottomRow();var _D=_F.getNewBottomRowEnd();this._4p(_0C,_x,_D,i,_0S,_0E);}else if(_H<=_7E){_5H=true;var _0C=this._25;var _0S=_F.getNewTopRow()*this.options.rowHeight;var _x=_F.getNewTopRow();var _D=_F.getNewTopRowEnd();this._4p(_0C,_x,_D,i,_0S,_0E);}}else{_4w=true;var _F=new HDataBuffer(_H,_02,0,0,this._08);var _U=_F.startRow();var _2a=_F.endRow();var _0C=0;var _0S=_U*this.options.rowHeight;this._4p(_0C,_U,_U+this._08*3,i,_0S,_0E);}}}
if(_5G==true){var _F=new HDataBuffer(_H,_02,0,0,this._08);var _2f=_F.getNewDownBufferIndexes(this._1e);this._1e=_2f[0];this._25=_2f[1];this._1c+=this._08;}
if(_5H==true){var _F=new HDataBuffer(_H,_02,0,0,this._08);var _2f=_F.getNewUpBufferIndexes(this._1e);this._1e=_2f[0];this._25=_2f[1];this._1c-=this._08;}
if(_4w==true){var _F=new HDataBuffer(_H,_02,0,0,this._08);this._1e=0;this._25=_F.endBufferStartRow();this._1c=_H-this._08;}
this.data.updateBuffer(_H,_02);},_4p:function(_0C,_7N,_6Q,_1t,_5m,_0N){var _8q;for(var _1j=_7N;_1j<_6Q;_1j++){_8q=this.data.getCell(this,_1j,this._r[_1t].index);_8q=(_8q)?_8q:"1";this._0Q[_1t][_0C].setValue(_8q);this._0Q[_1t][_0C].rect.offsetTo(0,_5m);this._0Q[_1t][_0C].drawRect();_5m+=this.options.rowHeight;_0C++;}},_7e:function(_1t,_H,_02){var _0E=this.tableColumns[_1t];if(!this._08){this._08=_02-_H;}
var _F=new HDataBuffer(_H,_02,0,0,this._08);var _U=_F.startRow();var _2a=_F.endRow();this._1c=_U;this._4P=_2a;var _0S=_U*this.options.rowHeight;this._25=_F.endBufferStartRow();this._0Q[_1t]=new Array();var _1x=_0E.dataView;if(typeof _1x=="string"){_1x=ITextControl;}
var _f,_6i,_8q;for(var _1j=_U;_1j<_2a;_1j++){_8q=this.data.getCell(this,_1j,this._r[_1t].index);_8q=(_8q)?_8q:"1";_6i=new HRect(0,_0S,_0E.rect.width,_0S+this.options.rowHeight);_f=new _1x(_6i,_0E,{value:_8q});this._0Q[_1t].push(_f);_0S+=this.options.rowHeight;}},_1W:function(){var _3c=0,_81;if(this._r.length>0){var _s;this._O[0]=0;width=this._r[0].width;_3c+=width;for(var i=1;i<this._r.length;i++){this._O[i]=this._O[i-1]+width;width=this._r[i].width;_3c+=width;}}
_81=this.numberOfRows*this.options.rowHeight;this.columnsView.rect.setSize(_3c,_81);this.columnsView.drawRect();if(this.headerView){this.headerView.rect.setWidth(_3c);this.headerView.drawRect();}},_5O:function(_e){return parseInt(_e.y/this.options.rowHeight,10);},rowAtPoint:function(_e){var _a=_e.y;if(_a==0){return 0;}
_a-=this.options.headerViewHeight;return parseInt(_a/this.options.rowHeight,10);},addColumn:function(_d,_s,_C,_1x,_3J){var _k=new _6l(_d,_s,_C,_1x,_3J);this._r.push(_k);this._1d.push(false);},setData:function(_0d){this.data=_0d;this.data.tableControl=this;this.numberOfRows=this.data.numberOfRows();this._1W();},reloadData:function(_0d){this._1g=true;this._5L=true;this._2z();this._5L=false;this._1g=false;},removeColumn:function(_k){this._1g=true;var _d=this.tableColumns.indexOf(_k);this._r.splice(_d,1);this.tableHeaderColumns[_d].die();this.tableHeaderColumns.splice(_d,1);this.tableColumns[_d].die();this.tableColumns.splice(_d,1);this._0Q.splice(_d,1);this._1d.splice(_d,1);this._1W();this._2z();this._1g=false;},moveColumn:function(_1t,_2k){this._1g=true;var _0y=_1t;var _0Y=_2k;if(_0y<_0Y){var _84=_0Y;_0Y=_0y;_0y=_84;}
var _k=this._r[_0y];this._r.splice(_0y,1);this._r.splice(_0Y,0,_k);_k=this.tableColumns[_0y];this.tableColumns.splice(_0y,1);this.tableColumns.splice(_0Y,0,_k);_k=this.tableHeaderColumns[_0y];this.tableHeaderColumns.splice(_0y,1);this.tableHeaderColumns.splice(_0Y,0,_k);_k=this._1d[_0y];this._1d.splice(_0y,1);this._1d.splice(_0Y,0,_k);_k=this._0Q[_0y];this._0Q.splice(_0y,1);this._0Q.splice(_0Y,0,_k);this._1W();this._2z();this._1g=false;},scrollLeft:function(){return this._0a.left;},scrollTop:function(){return this._0a.top;},_2H:function(){var _4l=ELEM.get(this.tableView.elemId);if(!_4l){throw("Error: HTableControl element not found");}
var _7u=new HRect(this._0a);this._0a.offsetTo(parseInt(_4l.scrollLeft,10),parseInt(_4l.scrollTop,10));if(!_7u.equals(this._0a)){this._1g=true;this._2z();this._1g=false;}}});