
var HClass=function(){if(arguments.length){var _42=arguments[0];if(this==window){HClass.prototype.extend.call(_42,arguments.callee.prototype);}else{this.extend(_42);}}};HClass.prototype={extend:function(_0u,_85){var _1U=HClass.prototype.extend;if(arguments.length==2){var _37=this[_0u];if((_37 instanceof Function)&&(_85 instanceof Function)&&_37.valueOf()!=_85.valueOf()&&(/\bbase\b/).test(_85)){var _3G=_85;_85=function(){var _7h=this.base;this.base=_37;var _7o=_3G.apply(this,arguments);this.base=_7h;return _7o;};_85.valueOf=function(){return _3G;};_85.toString=function(){return String(_3G);};}
return this[_0u]=_85;}else if(_0u){var _0D={toSource:null};var _5n=["toString","valueOf"];if(HClass._3O){_5n.push("constructor");}
for(var i=0;(_4=_5n[i]);i++){if(_0u[_4]!=_0D[_4]){_1U.call(this,_4,_0u[_4]);}}
for(var _4 in _0u){if(!_0D[_4]){_1U.call(this,_4,_0u[_4]);}}}
return this;},base:function(){}};HClass.extend=function(_0A,_3R){var _1U=HClass.prototype.extend;if(!_0A){_0A={};}
HClass._3O=true;var _0D=new this;_1U.call(_0D,_0A);var _1f=_0D.constructor;_0D.constructor=this;delete HClass._3O;var _12=function(){if(!HClass._3O){_1f.apply(this,arguments);}
this.constructor=_12;};_12.prototype=_0D;_12.extend=this.extend;_12.implement=this.implement;_12.toString=function(){return String(_1f);};_1U.call(_12,_3R);var _3J=_1f?_12:_0D;if(_3J.init instanceof Function){_3J.init();}
return _3J;};HClass.implement=function(_1Y){if(_1Y instanceof Function){_1Y=_1Y.prototype;}
this.prototype.extend(_1Y);};var Base=HClass;if([].indexOf===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_66){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_66){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_46=[];for(i=0;i<l;i++){_46.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _46.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_o,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _u=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_u=_u.extend(_2);this.options=new _u();this.request(_o);},request:function(_o){this.url=_o;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _r=this;this.transport.onreadystatechange=function(){_r.onStateChange();};this.setRequestHeaders();var _68=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_68);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _24=this.transport.readyState;if(_24>1){this.respondToReadyState(_24);}},respondToReadyState:function(_24){if(_24==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_24==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});ELEMTickerInterval=10;ELEM={_1f:function(){var _0=ELEM;_0._8l=[];_0._6p=null;_0._8m=false;_0._initDone=false;_0._8F=0;_0._setStyleCount=0;_0._setStyleDiffCount=0;_0._8u=0;_0._getStyleMissCount=0;_0._flushLoopCount=0;_0._flushLoopFlushedCount=0;_0._flushStylCount=0;_0._flushTime=0;_0._flushCounter=0;_0._4F=500;_0._timer=null;_0._1p=ELEMTickerInterval;_0._flushing=false;_0._needFlush=false;_0._5w=1;_0._R=[];_0._S={_7K:[]};_0._5B={};_0._17={};_0._0n={};_0._0H={};_0._4q=[];_0._3m={};_0._blockElems=",ADDRESS,BLOCKQUOTE,CENTER,DIR,DIV,DL,FIELDSET,FORM,H1,H2,H3,H4,H5,H6,HR,ISINDEX,MENU,NOFRAMES,NOSCRIPT,OL,P,PRE,TABLE,UL,";},_8p:function(_4l,_A){var _0=ELEM,i=0,_5O=[],_S=_0._4K(_A),_1z=_S._1z;for(;i!=_4l;i++){_5O.push(_0.make(_1z,_A));}
for(i=0;i!=_4l;i++){_0.del(_5O[i]);}},_61:function(_9){var _6,_0,_R;_0=ELEM;_R=_0._R;_R.push(_9);_6=_R.length-1;return _6;},_8x:function(_6){var _0=ELEM;_0._17[_6]=[];_0._5B[_6]={};_0._0n[_6]=[];_0._0H[_6]={};_0._3m[_6]=false;},bindId:function(_6o){var _0=ELEM,_9=document.getElementById(_6o),_b=_0._61(_9);_0._8x(_b);return _b;},bind:function(_9){var _6,_0=ELEM;_6=_0._61(_9);_0._8x(_6);return _6;},_8J:function(_6,_9){var _0=ELEM;_0._R[_6]=_9;},get:function(_6){return ELEM._R[_6];},setHTML:function(_6,_H){var _0=ELEM;_0._R[_6].innerHTML=_H;},_4K:function(_A){var _0=ELEM,_S=_0._S;if(!_S[_A]){_S._7K.push(_A);_S[_A]=[];_S[_A]._2p=1;_S[_A]._1K=0;_S[_A]._1z=_0.make(_0._1z,'div');}
return _S[_A]._1z;},del:function(_6){var _0=ELEM,_9=_0._R[_6],_A=_9.tagName,_1z;_1z=_0._4K(_A);_0.append(_6,_1z);var _4r=_0._4q.indexOf(_6),_S=_0._S[_A];if(_4r!=-1){_0._4q.splice(_4r,1);}
try{_9.innerHTML='';}catch(e){}
_0.setCSS(_6,'display:none;');_0.delAttr(_6,'id');_0.delAttr(_6,'ctrl');_0._8x(_6);_S._2p++;_S.push(_6);},append:function(_7u,_2b){var _0u,_3U,_0;_0=ELEM;_0u=_0._R[_7u];_3U=_0._R[_2b];_3U.appendChild(_0u);},setCSS:function(_6,_8j){ELEM._R[_6].style.cssText=_8j;},getCSS:function(_6){return ELEM._R[_6].style.cssText;},getVisibleSize:function(_6){var _0,_9,w,h,_v,_2R,_0=ELEM,_9=_0._R[_6],w=_9.offsetWidth,h=_9.offsetHeight,_v=_9.parentNode;while(_v&&_v.nodeName.toLowerCase()!='body'){if(!_0._2z){_2R=document.defaultView.getComputedStyle(_v,null).getPropertyValue('overflow');}
else{_2R=_v.currentStyle.getAttribute('overflow');}
_2R=_2R!='visible';if(w>_v.clientWidth&&_2R){w=_v.clientWidth-_9.offsetLeft;}
if(h>_v.clientHeight&&_2R){h=_v.clientHeight-_9.offsetTop;}
_9=_9.parentNode;_v=_9.parentNode;}
return[w,h];},getSize:function(_6){var _0,_9,w,h,_v,_2R,_0=ELEM,_9=_0._R[_6],w=_9.offsetWidth,h=_9.offsetHeight;return[w,h];},getScrollSize:function(_6){var _0,_9,w,h,_v,_2R,_0=ELEM,_9=_0._R[_6],w=_9.scrollWidth,h=_9.scrollHeight;return[w,h];},getVisiblePosition:function(_6){var x,y,_9,_0,_0=ELEM,x=0,y=0,_9=_0._R[_6];while(_9!==document){x+=_9.offsetLeft;y+=_9.offsetTop;x-=_9.scrollLeft;y-=_9.scrollTop;_9=_9.parentNode;if(!_9){break;}}
return[x,y];},getOpacity:function(_6){var _0,_0a,_3Z,_2w;_0=ELEM;_2w=_0.getStyle;if(_0a=_2w(_6,'-khtml-opacity')){return parseFloat(_0a);}
if(_0a=_2w(_6,'-moz-opacity')){return parseFloat(_0a);}
_3Z=_2w(_6,'opacity',true);if(_0a=_3Z||(_3Z==0)){return parseFloat(_0a);}
if(_0a=(_0._R[_6].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_0a[1]){return parseFloat(_0a[1])/100;}}
return 1.0;},setOpacity:function(_6,_85){var _0=ELEM;if(_85==1&&is_ie){_0._R[_6].style.setAttribute('filter',_0.getStyle(_6,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_85<0.00001){_85=0;}
if(_0._2z){_0._R[_6].style.setAttribute('filter',_0.getStyle(_6,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_85*100+')');}else{_0._R[_6].style.setProperty('opacity',_85,'');}}},getIntStyle:function(_6,_g){var _85=ELEM.getStyle(_6,_g);return parseInt(_85,10);},setBoxCoords:function(_6,_0e){ELEM.setStyle(_6,'left',_0e[0]+'px');ELEM.setStyle(_6,'top',_0e[1]+'px');ELEM.setStyle(_6,'width',_0e[2]+'px');ELEM.setStyle(_6,'height',_0e[3]+'px');},getExtraWidth:function(_6){var _0B=ELEM.getIntStyle;return _0B(_6,'padding-left')+_0B(_6,'padding-right')+_0B(_6,'border-left-width')+_0B(_6,'border-right-width');},getExtraHeight:function(_6){var _0B=ELEM.getIntStyle;return _0B(_6,'padding-top')+_0B(_6,'padding-bottom')+_0B(_6,'border-top-width')+_0B(_6,'border-bottom-width');},setFPS:function(_0z){ELEM._1p=1000/_0z;if(ELEM._1p<ELEMTickerInterval){ELEM._1p=ELEMTickerInterval;}},setSlowness:function(_5w){ELEM._5w=_5w;},setIdleDelay:function(_4F){ELEM._4F=_4F;},_8w:false,flushLoop:function(_0g){var _0=ELEM;_0._flushLoopCount++;if(_0._1n&&(_0._flushLoopCount%5==0)&&_0._8w){iefix._0d();_0._8w=false;}
clearTimeout(_0._timer);if(_0._flushing){_0g*=2;_0._timer=setTimeout('ELEM.flushLoop('+_0g+');',_0g);return;}else{if(!_0._needFlush){if(_0._1n&&_0._8w){iefix._0d();_0._8w=false;}
_0._timer=setTimeout('ELEM.flushLoop('+_0g+');',_0._4F);return;}
_0g=parseInt(_0._5w*(_0._flushTime/_0._flushCounter),ELEMTickerInterval);if(_0g<_0._1p||!_0g){_0g=_0._1p;}
_0._flushing=true;_0._timer=setTimeout('ELEM.flushLoop('+_0g+');',_0g);}
_0._flushTime-=new Date().getTime();var _3D,_1O,i,_17;_4q=_0._4q;_3D=_4q.length;_1O=_4q.splice(0,_3D);var _6B=new Date().getTime();for(i=0;i<_3D;i++){_0._flushLoopFlushed++;var _6=_1O.pop();_0._3m[_6]=false;_0._6C(_6);_0._8r(_6);}
_0._flushCounter++;_0._flushTime+=new Date().getTime();if(_0._4q.length==0&&_0._needFlush){_0._needFlush=false;}
_0._flushing=false;},_8r:function(_6){var _0=ELEM,_0n=_0._0n[_6],_0H=_0._0H[_6],_9=_0._R[_6],_g,_18,i,_4E=_0n.length,_1O=_0n.splice(0,_4E);for(i=0;i!=_4E;i++){_g=_1O.pop();_18=_0H[_g];_9.setAttribute(_g,_18);}},getAttr:function(_6,_g,_0I){var _0=ELEM,_2m=_0._0H[_6][_g],_18;if(_2m!==undefined&&!_0I){return _2m;}
var _9=_0._R[_6];if(_9.getAttribute(_g)==null){_9[_g]='';}
_18=_9.getAttribute(_g);_0._0H[_6][_g]=_18;return _18;},setAttr:function(_6,_g,_85,_0I){var _1P,_0=ELEM,_0n=_0._0n[_6],_0H=_0._0H[_6];_1P=_85!=_0.getAttr(_6,_g);if(_1P){_0H[_g]=_85;if(_0I){_0._R[_6].setAttribute(_g,_85);}
else{if(_0n.indexOf(_g)==-1){_0n.push(_g);}
if(!_0._3m[_6]){_0._4q.push(_6);_0._3m[_6]=true;_0._8g();}}}},delAttr:function(_6,_g){var _1P,_0=ELEM,_0n=_0._0n[_6],_0H=_0._0H[_6];delete _0H[_g];_0._R[_6].removeAttribute(_g);if(_0n.indexOf(_g)!=-1){_0n.splice(_0n.indexOf(_g,1));}
if(_0._3m[_6]){_0._4q.splice(_0._4q.indexOf(_6,1));_0._3m[_6]=false;_0._8g();}},hasClassName:function(_b,_1c){var _8=ELEM.get(_b);if(!_8)return;var _4x=false;var _1d=_8.className.split(' ');for(var i=0;i<_1d.length;i++){if(_1d[i]==_1c){_4x=true;}}
return _4x;},addClassName:function(_b,_1c){var _8=ELEM.get(_b);if(!_8)return;ELEM.removeClassName(_b,_1c);_8.className+=' '+_1c;},removeClassName:function(_b,_1c){var _8=ELEM.get(_b);if(!_8)return;var _3I='';var _1d=_8.className.split(' ');for(var i=0;i<_1d.length;i++){if(_1d[i]!=_1c){if(i>0)_3I+=' ';_3I+=_1d[i];}}
_8.className=_3I;},_8g:function(){var _0=ELEM;if(!_0._needFlush){_0._needFlush=true;if(!_0._flushing){clearTimeout(_0._timer);_0._timer=setTimeout('ELEM.flushLoop('+_0._1p+');',_0._1p);}}},printStats:function(){var _0=ELEM,_S=_0._S,i=0,_A,_7J,_2p,_1K;console.log('Recycler efficiency:');var _36=0;for(;i!=_S._7K.length;i++){_A=_S._7K[i];console.log(' tagName: '+_A);_7J=_S[_A].length;console.log('   length  : '+_7J);_2p=_S[_A]._2p;console.log('   countIn : '+_2p);_1K=_S[_A]._1K;_36+=_1K;console.log('   countOut: '+_1K);console.log('--------------------------------');}
console.log('================================');console.log('Flushing efficiency:');console.log('  total real time spent: '+_0._flushTime+'ms');console.log('  total times called:    '+_0._flushLoopCount);console.log('  total times flushed:   '+_0._flushCounter);console.log('  total items flushed:   '+_0._flushLoopFlushedCount);console.log('  total real style sets: '+_0._flushStylCount);console.log('================================');console.log('setStyle efficiency:');console.log('  total times called:    '+_0._setStyleCount);console.log('  total times non-cache: '+_0._setStyleDiffCount);console.log('================================');console.log('getStyle efficiency:');console.log('  total times called:    '+_0._8u);console.log('  total times non-cache: '+_0._getStyleMissCount);console.log('================================');console.log('Summary:');console.log('  recycler saved '+(_36)+' of '+_0._8F+' ('+Math.round(_36/_0._8F*100)+'%) document.createElement calls');console.log('  style buffer saved '+(_0._setStyleDiffCount-_0._flushStylCount)+' of '+_0._setStyleDiffCount+' ('+Math.round(((_0._setStyleDiffCount-_0._flushStylCount)/_0._setStyleDiffCount)*100)+'%) non-cached DOM style sets');console.log('  style cache saved '+(_0._setStyleCount-_0._setStyleDiffCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._setStyleDiffCount)/_0._setStyleCount)*100)+'%) DOM style sets');console.log('  style cache saved '+(_0._8u-_0._getStyleMissCount)+' of '+_0._8u+' ('+Math.round(((_0._8u-_0._getStyleMissCount)/_0._8u)*100)+'%) DOM style gets');console.log('  style buffer and cache saved '+(_0._setStyleCount-_0._flushStylCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._flushStylCount)/_0._setStyleCount)*100)+'%) total DOM style sets');},setStyle:function(_6,_g,_85,_0I){var _0=ELEM,_B=_0._5B[_6],_4s=_0._R,_1P,_17;_0._setStyleCount++;_1P=_85!==_B[_g];if(_1P){_0._setStyleDiffCount++;_B[_g]=_85;if(_0I){if(_g=='opacity'){_0.setOpacity(_6,_85);}
else{_0._2z?(_4s[_6].style.setAttribute(_g.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_B[_g])):(_4s[_6].style.setProperty(_g,_B[_g],''));}
if(_0._1n){if(iefix._2Y.indexOf(_g)!=-1){_0._8w=true;}}}else{_3m=_0._3m;_17=_0._17[_6];if(_17.indexOf(_g)==-1){_17.push(_g);}
if(!_3m[_6]){_0._4q.push(_6);_3m[_6]=true;_0._8g();}}}},make:function(_2b,_A){if(_2b===undefined){_2b=0;}
if(_A===undefined){_A='DIV';}else{_A=_A.toUpperCase();}
var _0=ELEM,_9,_6;_0._8F++;if(_0._S[_A]){if(_0._S[_A].length!=0){_6=_0._S[_A].pop();_0._S[_A]._1K++;_9=_0._R[_6];if(_0._blockElems.indexOf(','+_A+',')!=-1){_0.setCSS(_6,'display:block;');}else{_0.setCSS(_6,'display:inline;');}
_0.append(_6,_2b);return _6;}}
_9=document.createElement(_A);_0._R[_2b].appendChild(_9);_6=_0._61(_9);_0._8x(_6);return _6;},windowSize:function(){var _03,_1X;_03=(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;_1X=(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;return[_03,_1X];},_4I:function(){var _0=ELEM,_0Y,_3e;var _3s=["ELEM.getStyle=function(_6,_g,_0I){","var _0=ELEM,_B=_0._5B[_6],_26;_0._8u++;","if((_B[_g]===undefined)||_0I){","if(!_0I){_0._getStyleMissCount++;}","if((_g=='opacity')&&_0I){_26=_0.getOpacity(_6);}","else{","_26=document.defaultView.getComputedStyle(_0._R[_6],null).getPropertyValue(_g);","_6a=_g.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){","return $3.toUpperCase()+$4});","_26=_0._R[_6].currentStyle[_6a];","}_B[_g]=_26;","}return _B[_g];};"];if(_0._2z){_3s.splice(6,1);}else{_3s.splice(7,3);}
eval(_3s.join(''));var _3o=["ELEM._6C=function(_6){","var _0=ELEM,_17=_0._17[_6],_B=_0._5B[_6],_9=_0._R[_6],_1S,_52,_4g,_g,_1O,_26;","if(!_9){return;}","_1S=_9.style;","_52=_17.length;","_1O=_17.splice(0,_52);","for(_4g=0;_4g!=_52;_4g++){","_g=_1O.pop();_0._flushStylCount++;","if(_g=='opacity'){_26=_0.getOpacity(_6,_B[_g]);}else{","if(_0._1n){if(iefix._2Y.indexOf(_g)!=-1){_0._8w=true;}}try{_1S.setAttribute(_g.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_B[_g]);}catch(e){}}}};","_1S.setProperty(_g,_B[_g],'');}}};"];if(_0._2z){_3o.pop();}else{_3o.splice(9,1);}
eval(_3o.join(''));_0.bind(document.body);_0._1z=_0.make(0,'div');_0.setCSS(_0._1z,"display:none;visibility:hidden;");_0.setAttr(_0._1z,'id','trashcan_'+_0._1z);_0._timer=setTimeout('ELEM.flushLoop('+_0._1p+')',_0._1p);if(!_0._8l){return;}
while(_0._8l.length!=0){_0Y=_0._8l.shift();if(typeof _0Y=='string'){_3e=eval(_0Y);if(typeof _3e=='string'){_0._8l.push(_3e);}}}
_0._initDone=true;},_80:function(){_0=ELEM;_0._2z=(document.all&&navigator.userAgent.indexOf("Opera")==-1);_0._1n=(_0._2z&&navigator.userAgent.indexOf("MSIE 6")!=-1);_0._8A=(_0._2z&&navigator.userAgent.indexOf("MSIE 7")!=-1);_0._8C=(navigator.userAgent.indexOf("KHTML")!=-1);_0._is_ff=(navigator.userAgent.indexOf("Firefox")!=-1);_0._8B=(navigator.userAgent.indexOf("Opera")!=-1);_0._6r();},_6q:function(_0Y){var _0=ELEM;if(typeof _0Y=='string'){if(_0._initDone==true){eval(_0Y);}else{_0._8l.push(_0Y);}}},_6r:function(){var _8D=false;var _0=ELEM;if(_0._2z){var _4G="javascript:void(0)";if(location.protocol=="https:"){_4G="src=//0";}
document.write("<scr"+"ipt id=_5Y defer src="+_4G+"><\/scr"+"ipt>");var _6T=document.getElementById("_5Y");_6T.onreadystatechange=function(){if(this.readyState=="complete"){ELEM._8m=true;ELEM._4I();delete ELEM._8l;clearTimeout(ELEM._6p);delete ELEM._6p;}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(document.readyState))){_0._8m=true;}
else if(document.body){_0._8m=true;}
if(!_0._8m){_0._6p=setTimeout('ELEM._6r()',ELEMTickerInterval*10);}else{_0._4I();delete _0._8l;clearTimeout(_0._6p);delete _0._6p;}}};ELEM._1f();LOAD=ELEM._6q;ELEM._80();Event={element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}
else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(ELEM._2z||ELEM._8C){return(e.button==1);}
else{return(e.button==0);}},observers:false,_76:function(_9,_4,_1W,_2e){if(!Event.observers){Event.observers=[];}
if(_9.addEventListener){this.observers.push([_9,_4,_1W,_2e]);_9.addEventListener(_4,_1W,_2e);}
else if(_9.attachEvent){this.observers.push([_9,_4,_1W,_2e]);_9.attachEvent("on"+_4,_1W);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_9,_4,_1W,_2e){_2e=_2e||false;Event._76(_9,_4,_1W,_2e);},stopObserving:function(_9,_4,_1W,_2e){_2e=_2e||false;if(_9.removeEventListener){_9.removeEventListener(_4,_1W,_2e);}
else if(detachEvent){_9.detachEvent("on"+_4,_1W);}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_9&&eo[1]==_4&&eo[2]==_1W&&eo[3]==_2e){Event.observers[i]=null;Event.observers.splice(i,1);}
else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34};if(ELEM._2z){Event.observe(window,"unload",Event.unloadCache,false);}
_4n={mouseMove:false,mouseDown:false,click:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,isDragged:false,textEnter:false};EVENT={status:[false,false,0,0,[],false,false,false],button1:0,button2:1,crsrX:2,crsrY:3,keysDown:4,altKeyDown:5,ctrlKeyDown:6,shiftKeyDown:7,start:function(){var _3t,_3n,i,_0=EVENT;if(ELEM._2z){_3t=document;}
else{_3t=window;}
_3n=[['mousemove',EVENT.mouseMove],['mouseup',EVENT.mouseUp],['mousedown',EVENT.mouseDown],['click',EVENT.click],['keyup',EVENT.keyUp],['keydown',EVENT.keyDown],['keypress',EVENT.keyPress],['contextmenu',EVENT.contextMenu],['resize',EVENT.resize],['mousewheel',EVENT.mouseWheel]];for(i=0;i!=_3n.length;i++){Event.observe(_3t,_3n[i][0],_3n[i][1]);}
if(window.addEventListener){window.addEventListener('DOMMouseScroll',EVENT.mouseWheel,false);}
_0.listeners=[];_0.focused=[];_0.resizeListeners=[];_0.coordListeners=[];_0.focusOptions={};_0.dragItems=[];_0.hovered=[];_0.hoverInterval=50;_0.hoverTimer=new Date().getTime();_0.topmostDroppable=null;_0.textEnterCtrls=[];_0._3f=[];_0._coordCacheFlag=true;_0._lastCoordFlushTimeout=null;_0.activeControl=null;_0._lastKeyDown=null;},coordCacheFlush:function(_b){if(_b){EVENT._3f[_b]=null;}
else{EVENT._3f=[];}},reg:function(_e,_0L){var _b,_9,_0=EVENT,_7i;_b=_e.elemId;_9=ELEM.get(_b);if(ELEM._2z){_9.setAttribute('ctrl',_e);}
else{_9.ctrl=_e;}
_0.listeners[_b]=true;_0.focused[_b]=false;for(var _7i in _4n){if(_0L[_7i]===undefined){_0L[_7i]=_4n[_7i];}}
_0.focusOptions[_b]=_0L;var _3g=_0.coordListeners.indexOf(_b);if(_0L.mouseMove){if(_3g==-1){_0.coordListeners.push(_b);}}
else if(_3g!=-1){_0.coordListeners.splice(_3g,1);}
if(_0L.textEnter){if(_0.textEnterCtrls.indexOf(_e.viewId)==-1){_0.textEnterCtrls.push(_e.viewId);}}
if(_0L.resize){if(_0.resizeListeners.indexOf(_e.viewId)==-1){_0.resizeListeners.push(_e.viewId);}}
Event.observe(_9,'mouseover',_0._5a);},unreg:function(_e){var _0=EVENT,_b,_9;if(_e===this.activeControl){_0.changeActiveControl(null);}
_b=_e.elemId;_9=ELEM.get(_b);this.listeners[_b]=false;this.focused[_b]=false;this._3f[_b]=null;var _5I=_0.textEnterCtrls.indexOf(_e.viewId);if(_5I!=-1){_0.textEnterCtrls.splice(_5I,1);}
var _5p=_0.resizeListeners.indexOf(_e.viewId);if(_5p!=-1){_0.resizeListeners.splice(_5p,1);}
Event.stopObserving(_9,'mouseover',_0._5a);},resize:function(e){var i=0,_0=EVENT,_2t,_e;for(;i<_0.resizeListeners.length;i++){_2t=_0.resizeListeners[i];_e=HSystem.views[_2t];if(_e.onResize){_e.onResize();}}},_5a:function(e){if(!Event.element){return;}
var _l=Event.element(e);while(_l&&_l.ctrl===undefined){_l=_l.parentNode;}
if(!_l){return;}
var _0=_l.ctrl;EVENT.focus(_0);Event.stop(e);},_59:function(e){if(!Event.element){return;}
var _l=Event.element(e);while(_l&&_l.ctrl===undefined){_l=_l.parentNode;}
if(!_l){return;}
var _0=_l.ctrl;EVENT.blur(_0);Event.stop(e);},focus:function(_e){var _0=EVENT,_b,_9;_b=_e.elemId;_9=ELEM.get(_b);if(_0.focused[_b]==false&&_0.focusOptions[_b].isDragged==false){Event.stopObserving(_9,'mouseover',_0._5a);Event.observe(_9,'mouseout',_0._59);_0.focused[_b]=true;if(_e['focus']){_e.focus();}}},blur:function(_e){var _0=EVENT,_b,_9;_b=_e.elemId;_9=ELEM.get(_b);if(_0.focused[_b]==true&&_0.focusOptions[_b].isDragged==false){Event.stopObserving(_9,'mouseout',_0._59);Event.observe(_9,'mouseover',_0._5a);_0.focused[_b]=false;if(_e['blur']){_e.blur();}}},mouseMove:function(e){var _0=EVENT,x,y,_1h;x=Event.pointerX(e);y=Event.pointerY(e);_0.status[_0.crsrX]=x;_0.status[_0.crsrY]=y;_1h=_0.flushMouseMove(x,y);_0._8G(e);if(_1h){Event.stop(e);}},flushMouseMove:function(x,y){var _0=EVENT,x,y,_1h,i,j,_b,_e;clearTimeout(_0._lastCoordFlushTimeout);_1h=false;for(i=0;i!=_0.dragItems.length;i++){_b=_0.dragItems[i];_0.focusOptions[_b].ctrl.doDrag(x,y);_0.coordCacheFlush(_b);_1h=true;}
if(new Date().getTime()>_0.hoverTimer+_0.hoverInterval){for(i=0;i!=_0.coordListeners.length;i++){_b=_0.coordListeners[i];_e=_0.focusOptions[_b].ctrl;_e.mouseMove(x,y);}
_0._94();var _31;for(i=0;i!=_0.dragItems.length;i++){_31=_0.topmostDroppable;_0.topmostDroppable=null;_b=_0.dragItems[i];_e=_0.focusOptions[_b].ctrl;var _2x,_1Q;for(j=0;j!=_0.hovered.length;j++){_2x=_0.hovered[j];if(_2x!=_b&&_0.focusOptions[_2x].ctrl){_1Q=_0.focusOptions[_2x].ctrl;if(!_0.topmostDroppable||_1Q.zIndex()>_0.topmostDroppable.zIndex()||_1Q.supr===_0.topmostDroppable){if(_0.focusOptions[_1Q.elemId].droppable){_0.topmostDroppable=_1Q;}}}}
if(_31!=_0.topmostDroppable){if(_31){_31.onHoverEnd(_e);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverStart(_e);}}}
_0.hoverTimer=new Date().getTime();}
else{_0._lastCoordFlushTimeout=setTimeout('EVENT.flushMouseMove('+x+','+y+');',_0.hoverInterval);}
return _1h;},_94:function(){var _0=EVENT,x,y,i,_e,_9,_3K,_5v,_0e;_0.hovered=[];x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.listeners.length;i++){if(!_0.listeners[i]||!_0.focusOptions[i].ctrl){continue;}
_e=_0.focusOptions[i].ctrl;_9=ELEM.get(i);if(!_0._coordCacheFlag||!_0._3f[i]){_3K=ELEM.getVisiblePosition(_e.elemId);_5v=ELEM.getVisibleSize(_e.elemId);_0._3f[i]=[_3K[0],_3K[1],_5v[0],_5v[1]];}
_0e=_0._3f[i];if(x>=_0e[0]&&x<=_0e[0]+_0e[2]&&y>=_0e[1]&&y<=_0e[1]+_0e[3]){_0.hovered.push(i);}}},mouseDown:function(e,_06){var _0=EVENT,_3k,x,y,i,_E,_0S,_2K;_0._8G(e);_3k=false;if(_06===undefined){_06=Event.isLeftClick(e);}
if(_06){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_E=null;_0S=[];_2K=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_E=_0.focusOptions[i].ctrl;}
if((_0.focusOptions[i].draggable==true)&&_0.dragItems.indexOf(i)==-1){_0S.push(i);}
else if(_0.focusOptions[i].mouseDown==true){_2K.push(i);}}}
if(_E){_0.changeActiveControl(_E);}
for(i=0;i!=_0S.length;i++){_0.dragItems.push(_0S[i]);_0.focusOptions[_0S[i]].ctrl.startDrag(x,y);_3k=true;}
var _29=_2K.length;for(i=0;i!=_2K.length;i++){if(_0.focusOptions[_2K[i]].ctrl.mouseDown(x,y,_06)){_29--;}}
if(_3k){document.body.focus();_0._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if((_29==0)&&(_0.hovered.length!=0)&&(_E&&(_E.textElemId===false))){Event.stop(e);}
return true;},click:function(e,_06){var _0=EVENT,x,y,i,_E,_3d;_0._8G(e);if(_06===undefined){_06=Event.isLeftClick(e);}
if(_06){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_E=null;_3d=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_E=_0.focusOptions[i].ctrl;}
else if(_0.focusOptions[i].click==true){_3d.push(i);}}}
if(_E){_0.changeActiveControl(_E);}
var _29=_3d.length;for(i=0;i!=_3d.length;i++){if(_0.focusOptions[_3d[i]].ctrl.click(x,y,_06)){_29--;}}
if((_29==0)&&(_0.hovered.length!=0)&&(_E&&(_E.textElemId===false))){Event.stop(e);}
return true;},changeActiveControl:function(_e){var _0=EVENT,_1u;_1u=_0.activeControl;if(_e!=_1u){if(_1u){_1u.active=false;_1u._71(_e);}
_0.activeControl=null;if(_e){_e.active=true;_0.activeControl=_e;_e._6F(_1u);}}},mouseUp:function(e){var _0=EVENT,_3j,x,y,_b,_e,i;_0._8G(e);_3j=false;_06=Event.isLeftClick(e);_0.status[_0.button1]=false;_0.status[_0.button2]=false;x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.dragItems.length;i++){_b=_0.dragItems[i];_e=_0.focusOptions[_b].ctrl;_e.endDrag(x,y);_3j=true;_0._94();if(_0.hovered.indexOf(_b)==-1){_0.blur(_e);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverEnd(_e);_0.topmostDroppable.onDrop(_e);_0.topmostDroppable=null;}}
_0.dragItems=[];if(_3j){document.onselectstart=_0._storedOnSelectStart;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseUp==true){_0.focusOptions[i].ctrl.mouseUp(x,y,_06);}}}
return true;},keyDown:function(e){var _0=EVENT,_0v;_0._8G(e);_0v=e.keyCode;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);if(_0._lastKeyDown!=_0v){_0.activeControl.keyDown(_0v);}}
if(_0.status[_0.keysDown].indexOf(_0v)==-1){_0.status[_0.keysDown].push(_0v);}
_0._lastKeyDown=_0v;},keyUp:function(e){var _0=EVENT,_0v,_keycodeindex;_0._8G(e);_0v=e.keyCode;_0._lastKeyDown=null;for(var i=0;i!=_0.textEnterCtrls.length;i++){var _2t=_0.textEnterCtrls[i],_e=HSystem.views[_2t];if(_e.textEnter){_e.textEnter();}}
if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyUp==true){_0.activeControl.keyUp(_0v);}
_4N=_0.status[_0.keysDown].indexOf(_0v);if(_4N!=-1){_0.status[_0.keysDown].splice(_4N,1);}},keyPress:function(e){var _0=EVENT;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _0=EVENT,_X,i;_X=0;if(!e){e=window.event;}
if(e.wheelDelta){_X=e.wheelDelta/120;if(window.opera){_X=-_X;}}
else if(e.detail){_X=-e.detail/3;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseWheel==true){Event.stop(e);_0.focusOptions[i].ctrl.mouseWheel(_X);}}}},contextMenu:function(e){EVENT.mouseDown(e,false);Event.stop(e);},_8G:function(e){var _0=EVENT;_0.status[_0.altKeyDown]=e.altKey;_0.status[_0.ctrlKeyDown]=e.ctrlKey;_0.status[_0.shiftKeyDown]=e.shiftKey;}};LOAD('EVENT.start();');SHA={_4D:0,hexCase:function(){return SHA._4D;},setHexCase:function(_6b){SHA._4D=_6b;},_49:"=",base64Pad:function(){return SHA._49;},setBase64Pad:function(_7c){SHA._49=_7c;},_4f:8,chrsz:function(){return SHA._4f;},setChrsz:function(_67){SHA._4f=_67;},hexSHA1:function(_0R){var _0=SHA;return _0._8d(_0._8i(_0._8Z(_0R),_0R.length*_0._4f));},b64SHA1:function(_0R){var _0=SHA;return _0._8c(_0._8i(_0._8Z(_0R),_0R.length*_0._4f));},strSHA1:function(_0R){var _0=SHA;return _0._8e(_0._8i(_0._8Z(_0R),_0R.length*_0._4f));},hexHmacSHA1:function(_g,_0J){var _0=SHA;return _0._8d(_0._8h(_g,_0J));},b64HmacSHA1:function(_g,_0J){var _0=SHA;return _0._8c(_0._8h(_g,_0J));},strHmacSHA1:function(_g,_0J){var _0=SHA;return _0._8e(_0._8h(_g,_0J));},str2Base64:function(_K){var _0=SHA;return _0._8c(_0._8Z(_K));},test:function(){return SHA.hexSHA1("abc")=="a9993e364706816aba3e25717850c26c9cd0d89d";},_8i:function(_4,_3B){var _0=SHA;_4[_3B>>5]|=0x80<<(24-_3B%32);_4[((_3B+64>>9)<<4)+15]=_3B;var _03=new Array(80),_0W=1732584193,_W=-271733879,_04=-1732584194,_05=271733878,_1j=-1009589776,i,_5e,_5f,_5g,_5h,_5i,j,_V;for(i=0;i<_4.length;i+=16){_5e=_0W;_5f=_W;_5g=_04;_5h=_05;_5i=_1j;for(j=0;j<80;j++){if(j<16){_03[j]=_4[i+j];}
else{_03[j]=_0._8U(_03[j-3]^_03[j-8]^_03[j-14]^_03[j-16],1);}
_V=_0._8V(_0._8V(_0._8U(_0W,5),_0._8W(j,_W,_04,_05)),_0._8V(_0._8V(_1j,_03[j]),_0._8X(j)));_1j=_05;_05=_04;_04=_0._8U(_W,30);_W=_0W;_0W=_V;}
_0W=_0._8V(_0W,_5e);_W=_0._8V(_W,_5f);_04=_0._8V(_04,_5g);_05=_0._8V(_05,_5h);_1j=_0._8V(_1j,_5i);}
return[_0W,_W,_04,_05,_1j];},_8W:function(_V,_W,_04,_05){if(_V<20){return(_W&_04)|((~_W)&_05);}
if(_V<40){return _W^_04^_05;}
if(_V<60){return(_W&_04)|(_W&_05)|(_04&_05);}
return _W^_04^_05;},_8X:function(_V){return(_V<20)?1518500249:(_V<40)?1859775393:(_V<60)?-1894007588:-899497514;},_8h:function(_g,_0J){var _0=SHA,_1G=_0._8Z(_g),_4M=new Array(16),_5j=new Array(16),i,_4z;if(_1G.length>16){_1G=_0._8i(_1G,_g.length*_0._4f);}
for(i=0;i<16;i++){_4M[i]=_1G[i]^0x36363636;_5j[i]=_1G[i]^0x5C5C5C5C;}
_4z=_0._8i(_4M.concat(_0._8Z(_0J)),512+_0J.length*_0._4f);return _0._8i(_5j.concat(_4z),512+160);},_8V:function(_4,_c){var _53=(_4&0xFFFF)+(_c&0xFFFF),_72=(_4>>16)+(_c>>16)+(_53>>16);return(_72<<16)|(_53&0xFFFF);},_8U:function(_2P,_4h){return(_2P<<_4h)|(_2P>>>(32-_4h));},_8Z:function(_K){var _0=SHA,_1F=[],_3F=(1<<_0._4f)-1,_7A=_K.length*_0._4f,i;for(i=0;i<_7A;i+=_0._4f){_1F[i>>5]|=(_K.charCodeAt(i/_0._4f)&_3F)<<(32-_0._4f-i%32);}
return _1F;},_8e:function(_1F){var _0=SHA,_K="",_3F=(1<<_0._4f)-1,i,_3a=_1F.length*32,_5X=32-_0._4f;for(i=0;i<_3a;i+=_0._4f){_K+=String.fromCharCode((_1F[i>>5]>>>(_5X-i%32))&_3F);}
return _K;},_8d:function(_0y){var _0=SHA,_4C=_0._4D?"0123456789ABCDEF":"0123456789abcdef",_K="",i,_39=_0y.length*4;for(i=0;i<_39;i++){_K+=_4C.charAt((_0y[i>>2]>>((3-i%4)*8+4))&0xF)+
_4C.charAt((_0y[i>>2]>>((3-i%4)*8))&0xF);}
return _K;},_8c:function(_0y){var _0=SHA,_1y="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",_K="",i,_39=_0y.length*4,_5E,_5F,_85,_5P,j,_3a=_0y.length*32;for(i=0;i<_39;i+=3){_5E=(((_0y[i>>2]>>8*(3-i%4))&0xFF)<<16);_5F=(((_0y[i+1>>2]>>8*(3-(i+1)%4))&0xFF)<<8);_7H=((_0y[i+2>>2]>>8*(3-(i+2)%4))&0xFF);_5P=(_5E|_5F|_7H);for(j=0;j<4;j++){if(i*8+j*6>_3a){_K+=_0._49;}
else{_K+=_1y.charAt((_5P>>6*(3-j))&0x3F);}}}
return _K;}};HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporter=Base.extend({constructor:null,start:function(_7S){var _0=HTransporter;_0.url_base=_7S;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_0W){HTransporter.pollMode=_0W;},failure:function(resp){var _6m=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_6m)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _7n=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_7n);}
catch(e){_0.err_msg='&err_msg='+e;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_7V=((_0.syncDelay>0)||(_0.syncDelay==0));if(_7V&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1x=_0.prevData;}
else{_1x=HValueManager.toXML();_0.prevData=_1x;}
if(""!=_1x||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1x};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_6,_r){this.values[_6]=_r;},set:function(_6,_85){this.values[_6].set(_85);},s:function(_6,_85){this.values[_6].s(_85);},del:function(_6){var _5K=this.values[_6];var _7U=_5K.views;for(var _0l=0;_0l<_7U.length;_0l++){var _7N=_7U[_0l];_7N.valueObj=new HDummyValue(0,_5K.value);}
this.values[_6]=null;},changed:function(_2c){if(this.isGetting==false){if(this.tosync.indexOf(_2c.id)==-1){this.tosync.push(_2c.id);}
var _V=HTransporter;if(!_V.pollMode){clearTimeout(_V.req_timeout);_V.req_timeout=setTimeout('HTransporter.sync();',_V.syncDelay);}}},toXML:function(){var _5l='&HSyncData=';if(!this.isSending){this.isSending=true;var _7E=this.tosync.length;if(_7E==0){this.isSending=false;return'';}
var _5D=[],_1l;for(_1l=0;_1l<_7E;_1l++){var _2a=this.tosync.shift();var _7F=this.values[_2a];_5D.push(_7F.toXML(_1l));}
var _7G=_5D.join('');_5l+='<hsyncvalues version="8118">'+_7G+'</hsyncvalues>';this.isSending=false;}
return _5l;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_6,_85){this.id=_6;this.type='[HValue]';this.value=_85;this.views=[];HValueManager.add(_6,this);},set:function(_85){if(_85!=this.value){this.value=_85;HValueManager.changed(this);this.refresh();}},s:function(_85){this.value=_85;this.refresh();},get:function(){return this.value;},bind:function(_Q){if(_Q===undefined){throw("HValueBindError: _Q is undefined!");}
this.views.push(_Q);_Q.setValueObj(this);},unbind:function(_Q){for(var _0l=0;_0l<this.views.length;_0l++){var _7P=this.views[_0l];if(_7P===_Q){this.views.splice(_0l);return;}}},release:function(_Q){return this.unbind(_Q);},refresh:function(){for(var _0l=0;_0l<this.views.length;_0l++){var _Q=this.views[_0l];if(_Q.value!=this.value){if(!_Q._valueIsBeingSet){_Q._valueIsBeingSet=true;_Q.setValue(this.value);_Q._valueIsBeingSet=false;}}}},toXML:function(_1l){var _2a=this.id.toString();var _0b=this.value;var _0F=(typeof _0b).slice(0,1);var _0U;if(_0F=='s'){_0U=_0b.toString();_0U=SHA.str2Base64(_0U);}
else if(_0F=='n'){if(Math.ceil(_0b)===Math.floor(_0b)===_0b){_0F='i';_0U=parseInt(_0b,10).toString();}
else{_0F='f';_0U=parseFloat(_0b).toString();}}
else if(_0F=='b'){if(_0b){_0U='1';}
else{_0U='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_2a);console.log('  syncjstype:',_0F);console.log('  typeof:',(typeof _0b));console.log('  syncvalue:',_0b);}}
catch(e){alert('value error, syncid:'+_2a+' syncjstype:'+_0F+' typeof:'+(typeof _0b)+' syncvalue:'+_0b);}
return'';}
return'<'+_0F+' id="'+_2a+'">'+_0U+'</'+_0F+'>';}});JSLoader=Base.extend({constructor:function(_2n){this._20=[];this._2n=_2n;this._3P=null;},_79:function(_5s){eval(_5s.responseText);},load:function(_2A){if(jsLoader._20.indexOf(_2A)!=-1){return;}
req_args={onSuccess:function(resp){jsLoader._79(resp);},onFailure:function(resp){window.status="failed to load js: "+jsLoader._2u;},method:'get',asynchronous:false};this._3P=new Ajax.Request(this._2n+_2A+'.js',req_args);this._20.push(_2A);}});LOAD("jsLoader = new JSLoader('/H/js/');");HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _05=arguments;if(_05.length===0){this._1I();}
else if(_05.length==2){this._4k(_05[0],_05[1]);}
else if(_05.length==1){this._1J(_05[0]);}
else{throw"Invalid number of arguments.";}},_1I:function(){this.x=null;this.y=null;},_4k:function(x,y){this.x=x;this.y=y;},_1J:function(_f){this.x=_f.x;this.y=_f.y;},set:function(){var _05=arguments;if(_05.length===0){this._1I();}
else if(_05.length==2){this._4k(_05[0],_05[1]);}
else if(_05.length==1){this._1J(_05[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_f){_05=arguments;if((_05.length==1)&&(_05[0].type==this.type)){_f=_05[0];return new HPoint((this.x+_f.x),(this.y+_f.y));}
else if(_05.length==2){return new HPoint((this.x+_05[0]),(this.y+_05[1]));}else{return new HPoint(0,0);}},subtract:function(){_05=arguments;if((_05.length==1)&&(_05[0].type==this.type)){_f=_05[0];return new HPoint(this.x-_f.x,this.y-_f.y);}
else if(_05.length==2){return new HPoint(this.x-_05[0],this.y-_05[1]);}else{return new HPoint(0,0);}},equals:function(_f){return(this.x==_f.x&&this.y==_f.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _05=arguments;if(_05.length===0){this._1I();}else if(_05.length==4){this._4j(_05[0],_05[1],_05[2],_05[3]);}
else if(_05.length==2){this._1J(_05[0],_05[1]);}
else if(_05.length==1){this._4i(_05[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1I:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_4j:function(_00,_0w,_15,_1b){this.top=_0w;this.left=_00;this.bottom=_1b;this.right=_15;},_1J:function(_4Z,_5t){this.top=_4Z.y;this.left=_4Z.x;this.bottom=_5t.y;this.right=_5t.x;},_4i:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _05=arguments;if(_05.length===0){this._1I();}else if(_05.length==4){this._4j(_05[0],_05[1],_05[2],_05[3]);}
else if(_05.length==2){this._1J(_05[0],_05[1]);}
else if(_05.length==1){this._4i(_05[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_00){this.left=_00;this.updateSecondaryValues();},setRight:function(_15){this.right=_15;this.updateSecondaryValues();},setTop:function(_0w){this.top=_0w;this.updateSecondaryValues();},setBottom:function(_1b){this.bottom=_1b;this.updateSecondaryValues();},setLeftTop:function(_f){this.left=_f.x;this.top=_f.y;this.updateSecondaryValues();},setLeftBottom:function(_f){this.left=_f.x;this.bottom=_f.y;this.updateSecondaryValues();},setRightTop:function(_f){this.right=_f.x;this.top=_f.y;this.updateSecondaryValues();},setRightBottom:function(_f){this.right=_f.x;this.bottom=_f.y;this.updateSecondaryValues();},setWidth:function(_h){this.right=this.left+_h;this.updateSecondaryValues();},setHeight:function(_D){this.bottom=this.top+_D;this.updateSecondaryValues();},setSize:function(){var _05=arguments;if(_05.length===2){_h=_05[0];_D=_05[1];}
else if(_05.length===1){_h=_05.x;_D=_05.y;}
this.right=this.left+_h;this.bottom=this.top+_D;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_r){if(_r instanceof HPoint){return this._6g(_r);}
else if(_r instanceof HRect){return this._6h(_r);}
else{throw"Wrong argument type.";}},_6g:function(_f){return(_f.x>=this.left&&_f.x<=this.right&&_f.y>=this.top&&_f.y<=this.bottom);},_6h:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _05=arguments;if(_05.length===1){this._6W(_05[0]);}else if(_05.length==2){this._4L(_05[0],_05[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_6W:function(_f){this._4L(_f.x,_f.y);},_4L:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _05=arguments;if(_05.length===1){this._77(_05[0]);}else if(_05.length==2){this._5c(_05[0],_05[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_77:function(_f){this._5c(_f.x,_f.y);},_5c:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _05=arguments;if(_05.length===1){this._78(_05[0]);}else if(_05.length==2){this._5d(_05[0],_05[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_78:function(_f){this._5d(_f.x,_f.y);},_5d:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_r){},unbind:function(_r){}});HDefaultApplicationInterval=20;HSystemTickerInterval=10;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _n=0;_n<this.apps.length;_n++){if(this.apps[_n]){if(!this.busyApps[_n]){if((this.ticks%this.appPriorities[_n])==0){this.appTimers[_n]=setTimeout('if (HSystem.apps['+_n+']) {HSystem.apps['+_n+']._5y();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._91=setTimeout('HSystem.ticker();',HSystemTickerInterval);},addApp:function(_1a,_0t){if(this.freeAppIds.length>1024){var _n=this.freeAppIds.shift();this.apps[_n]=_1a;}else{this.apps.push(_1a);var _n=this.apps.length-1;}
_1a.parent=this;_1a.parents=[this];_1a.appId=_n;this.startApp(_n,_0t);return _n;},startApp:function(_n,_0t){if(_0t===undefined){_0t=this.defaultInterval;}
this.appPriorities[_n]=_0t;this.busyApps[_n]=false;},stopApp:function(_n){this.busyApps[_n]=true;},reniceApp:function(_n,_0t){this.appPriorities[_n]=_0t;},killApp:function(_n,_6D){if(!_6D){var _7x=new Date().getTime();while(this.busyApps[_n]==true){if(new Date().getTime()>_7x+this.maxAppRunTime){break;}}}
this.busyApps[_n]=true;this.apps[_n].destroyAllViews();delete this.apps[_n];this.apps[_n]=null;this.freeAppIds.push(_n);},views:[],_3p:[],addView:function(_p){var _2M;if(this._3p.length==0){_2M=this.views.length;this.views.push(_p);}
else{_2M=this._3p.pop();this.views[_2M]=_p;}
return _2M;},delView:function(_m){this.views[_m]=null;this._3p.push(_m);}});LOAD('HSystem.ticker();');HApplication=HClass.extend({constructor:function(_0t){this.type='[HApplication]';this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_0t);},buildParents:function(_m){var _p=HSystem.views[_m];_p.parent=this;_p.parents=[];for(var _14=0;_14<this.parents.length;_14++){_p.parents.push(this.parents[_14]);}
_p.parents.push(this);},addView:function(_p){var _m=HSystem.addView(_p);this.views.push(_m);this.buildParents(_m);this.viewsZOrder.push(_m);return _m;},removeView:function(_m){HSystem.views[_m].remove();},destroyView:function(_m){HSystem.views[_m].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){var i,_m;for(i=0;i<this.views.length;i++){_m=this.views[i];HSystem.views[_m].die();}},_7e:function(){var i,_m;for(i=0;i<this.views.length;i++){_m=this.views[i];HSystem.views[i].onIdle();}},_5y:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._7e();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HNoComponentCSS=[];HThemeHasIE6GifsInsteadOfPng=[];HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2X={};this._2q={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_02){this.themePath=_02;},_6v:function(_o){console.log("ERROR: Template Not Found: '"+_o+"' ");},_6u:function(_o){console.log("ERROR: Template Failure: '"+_o+"' ");},_6t:function(_o){console.log("ERROR: Template Exception: '"+_o+"' ");},fetch:function(_o,_0Z){var _25;if(!_0Z){var _0Z='text/html; charset=UTF-8';}
var _3P=new Ajax.Request(_o,{method:'GET',onSuccess:function(_83){_25=_83.responseText;},on404:function(){HThemeManager._6v(_o);},onFailure:function(){HThemeManager._6u(_o);},onException:function(){HThemeManager._6t(_o);},asynchronous:false,contentType:_0Z});_3P.onStateChange();return _25;},getThemeGfxPath:function(){var _j=this._1M[0],_t=this._1M[1],_z=this._1M[2],_F=this._1M[3],_0V=this._0V(_j,_t,_z,_F);return this._T(_0V,'gfx');},getCssFilePath:function(_0p){var _j=this._1M[0];if((HThemeHasIE6GifsInsteadOfPng.indexOf(_j)!=-1)&&ELEM._1n){return"url('"+this._T(this.getThemeGfxPath(),_0p.replace('.png','-ie6.gif'))+"')";}
else{return"url('"+this._T(this.getThemeGfxPath(),_0p)+"')";}},loadCSS:function(_o){var _0Z='text/css';var _10=this.fetch(_o,_0Z);if(!_10||_10==""){return;}
_10=this._4b(_10);var _0k,_5C,_4A;if(ELEM._2z){_0k=document.createStyleSheet();_0k.cssText=_10;}
else{_0k=document.createElement("style");_0k.type=_0Z;_0k.media="all";_4A=document.getElementsByTagName('head')[0];_4A.appendChild(_0k);if(navigator.userAgent.indexOf('KHTML')!=-1){var _6l=document.createTextNode(_10);_0k.appendChild(_6l);}
else{_0k.innerHTML=_10;}}},_62:function(_K){if(_K[_K.length-1]!='/'){_K+='/';}
return _K;},_T:function(_7y,_7z){return this._62(_7y)+_7z;},_0V:function(_j,_t,_z,_F){var _02=_z;if(_z===null){_02=this.themePath;}
if(HThemeMode==0){if(_F){_02=this._T(_02,_F);}
if(_z===null){_02=this._T(_02,_t);_02=this._T(_02,'themes');}
_02=this._T(_02,_j);}
else if(HThemeMode==1){_02=this._T(_02,_j);}
return _02;},_2s:function(_j,_t,_z,_F){this._1M=[_j,_t,_z,_F];var _6j=this._0V(_j,_t,_z,_F);var _6k=this._T('css',_t+'.css');var _2s=this._T(_6j,_6k);return _2s;},_3E:function(_j,_t,_z,_F){var _6Q=this._0V(_j,_t,_z,_F);var _6R=this._T('html',_t+'.html');var _6S=this._T(_6Q,_6R);return _6S;},loadMarkup:function(_j,_t,_z,_F){if(!this._2X[_j]){this._2X[_j]={};}
var _B=this._2X[_j][_t];if(null===_B||undefined===_B){var _3E=this._3E(_j,_t,_z,_F);_B=this.fetch(_3E);if(null===_B||undefined===_B){_B="";}
this._2X[_j][_t]=_B;}
return _B;},getMarkup:function(_j,_t,_z,_F){if(!this._2q[_j]){var _6d=this._2s(_j,'common',_z,null);this._2q[_j]={};this.loadCSS(_6d);}
if(HNoComponentCSS.indexOf(_j)==-1){if(!this._2q[_j][_t]){var _6e=this._2s(_j,_t,_z,_F);this._2q[_j][_t]=true;this.loadCSS(_6e);}}
return this.loadMarkup(_j,_t,_z,_F);},_1H:function(_j,_t,_z,_F){var _0V=this._0V(_j,_t,_z,_F);var _o=this._T(_0V,'gfx');return _o;},_6f:function(_j,_t,_z,_F,_0p){if((HThemeHasIE6GifsInsteadOfPng.indexOf(_j)!=-1)&&ELEM._1n){return this._T(this._1H(_j,_t,_z,_F),_0p.replace('.png','-ie6.gif'));}
return this._T(this._1H(_j,_t,_z,_F),_0p);},getThemeGfxFile:function(_0p){return this.getThemeGfxPath()+_0p;},setTheme:function(_5J){this.currentTheme=_5J;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_19:new RegExp(/#\{([^\}]*)\}/),_4b:function(_1N){while(this._19.test(_1N)){_1N=_1N.replace(this._19,eval(RegExp.$1));}
return _1N;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _0N=this.markup;while(HMarkupView._47.test(_0N)){_0N=_0N.replace(HMarkupView._47,this.evalMarkupVariable(RegExp.$1,true));}
while(HMarkupView._19.test(_0N)){_0N=_0N.replace(HMarkupView._19,this.evalMarkupVariable(RegExp.$1));}
this.markup=_0N;},evalMarkupVariable:function(_7B,_8z){try{var _ID=this.elemId.toString(),_WIDTH=this.rect.width,_HEIGHT=this.rect.height,_25=eval(_7B);if(_8z){return'';}
if(_25===undefined){return'';}
else{return _25;}}
catch(e){return'';}},toggleCSSClass:function(_0o,_1L,_5u){if(_0o){var _4y=ELEM.hasClassName(_0o,_1L);if(_5u){if(!_4y){ELEM.addClassName(_0o,_1L);}}
else{if(_4y){ELEM.removeClassName(_0o,_1L);}}}}},{_19:new RegExp(/#\{([^\}]*)\}/),_47:new RegExp(/\$\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,constructor:function(_1,_v){if(this.theme===undefined){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;}
else{this.preserveTheme=true;}
this.optimizeWidthOnRefresh=true;this.parent=_v;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.viewsZOrder=[];this._6i();this.setRect(_1);this.isHidden=true;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this._4d=_1.left;this._4e=_1.top;this._1i=[];if(!this.isinherited){this.draw();this.show();}},setFlexRight:function(_0W,_P){if(_0W===undefined){_0W=true;}
this.flexRight=_0W;if(_P===undefined){_P=0;}
this.flexRightOffset=_P;},setFlexLeft:function(_0W,_P){if(_0W===undefined){_0W=true;}
this.flexLeft=_0W;if(_P!==undefined){this.rect.setLeft(_P);}},setFlexTop:function(_0W,_P){if(_0W===undefined){_0W=true;}
this.flexTop=_0W;if(_P!==undefined){this.rect.setTop(_P);}},setFlexBottom:function(_0W,_P){if(_0W===undefined){_0W=true;}
this.flexBottom=_0W;if(_P===undefined){_P=0;}
this.flexBottomOffset=_P;},setAbsolute:function(_0W){if(_0W===undefined){_0W=true;}
this.isAbsolute=_0W;},setRelative:function(_0W){if(_0W===undefined){_0W=true;}
this.isAbsolute=(!_0W);},getThemeGfxPath:function(){if(this.preserveTheme){_j=this.theme;}else{_j=HThemeManager.currentTheme;}
return HThemeManager._1H(_j,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0p){if(this.preserveTheme){_j=this.theme;}else{_j=HThemeManager.currentTheme;}
return HThemeManager._6f(_j,this.componentName,this.themePath,this.packageName,_0p);},_54:function(_1t){this.elemId=ELEM.make(_1t,'div');},_7s:function(_63){var _2r='display:none;overflow:hidden;visibility:hidden;';if(this.isAbsolute){_2r+='position:absolute;';}else{_2r+='position:relative;';}
_2r+=_63;ELEM.setCSS(this.elemId,_2r);},_3r:function(){var _1t;if(this.parent.elemId===undefined){_1t=0;}
else if(this.parent.markupElemIds&&this.parent.markupElemIds['subview']){_1t=this.parent.markupElemIds['subview'];}
else{_1t=this.parent.elemId;}
return _1t;},_6i:function(){if(!this.elemId){this._54(this._3r());this._7s('');if(this.preserveTheme){ELEM.addClassName(this.elemId,this.theme);}
else{ELEM.addClassName(this.elemId,HThemeManager.currentTheme);}}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
this.drawn=true;var _b=this.elemId;var _1=this.rect;ELEM.setStyle(_b,'left',this.flexLeft?(_1.left+'px'):'auto',true);ELEM.setStyle(_b,'top',this.flexTop?(_1.top+'px'):'auto',true);ELEM.setStyle(_b,'right',this.flexRight?(this.flexRightOffset+'px'):'auto',true);ELEM.setStyle(_b,'bottom',this.flexBottom?(this.flexBottomOffset+'px'):'auto',true);ELEM.setStyle(_b,'width',(this.flexLeft&&this.flexRight)?'auto':(_1.width+'px'),true);ELEM.setStyle(_b,'height',(this.flexTop&&this.flexBottom)?'auto':(_1.height+'px'),true);if(this.flexLeft&&this.flexRight){ELEM.setStyle(_b,'min-width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){ELEM.setStyle(_b,'min-height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){ELEM.setStyle(_b,'visibility','inherit',true);}
ELEM.setStyle(_b,'display','block',true);this._5Q();if(this._4d!=_1.left||this._4e!=_1.top){this.invalidatePositionCache();this._4d=_1.left;this._4e=_1.top;}},_5Q:function(){ELEM.setStyle(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this.viewId));},_2Z:function(){var _5R=this.parent.viewsZOrder;for(var i=0;i<_5R.length;i++){ELEM.setStyle(HSystem.views[_5R[i]].elemId,'z-index',i);}},draw:function(){this.drawRect();},_51:function(){var _j;if(this.preserveTheme){_j=this.theme;}
else{_j=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_j,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){ELEM.setStyle(this.elemId,'display','none',true);this._51();this.bindMarkupVariables();ELEM.setHTML(this.elemId,this.markup);this.markupElemIds={};var _5m=['bg','label','state','control','value','subview'];for(var i=0;i<_5m.length;i++){var _0r=_5m[i];var _4p=_0r+this.elemId;var _6P=' id="'+_4p+'"';if(this.markup.indexOf(_6P)!=-1){this.markupElemIds[_0r]=this.bindDomElement(_4p);}}
ELEM.setStyle(this.elemId,'display','block',true);},setHTML:function(_H){ELEM.setHTML(this.elemId,_H);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_4,_85,_3c){if(!this.elemId){return;}
ELEM.setStyle(this.elemId,_4,_85,_3c);},style:function(_4){if(!this.elemId){return;}
return ELEM.getStyle(this.elemId,_4);},setStyleForPart:function(_0r,_4,_85,_3c){if(!this.markupElemIds[_0r]){return;}
ELEM.setStyle(this.markupElemIds[_0r],_4,_85,_3c);},styleForPart:function(_0r,_4){if(!this.markupElemIds[_0r]){return;}
ELEM.getStyle(this.markupElemIds[_0r],_4);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){var _7Y=this.parent.viewsZOrder.indexOf(this.viewId),_7X=this.parent.views.indexOf(this.viewId);this.parent.views.splice(_7X,1);HSystem.delView(this.viewId);this.parent.viewsZOrder.splice(_7Y,1);this._2Z();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].die();}
this.remove();for(var i=0;i<this._1i.length;i++){ELEM.del(this._1i[i]);}
this._1i=[];ELEM.del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].onIdle();}},buildParents:function(_m){var _p=HSystem.views[_m];_p.parent=this;_p.parents=[];for(var _14=0;_14<this.parents.length;_14++){_p.parents.push(this.parents[_14]);}
_p.parents.push(this);},addView:function(_p){var _m=HSystem.addView(_p);this.views.push(_m);this.buildParents(_m);this.viewsZOrder.push(_m);return _m;},removeView:function(_m){HSystem.views[_m].remove();},destroyView:function(_m){HSystem.views[_m].die();},bounds:function(){var _0X=new HRect(this.rect);_0X.right-=_0X.left;_0X.left=0;_0X.bottom-=_0X.top;_0X.top=0;return _0X;},resizeBy:function(_3u,_2f){var _1=this.rect;_1.right+=_3u;_1.bottom+=_2f;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_h,_D){var _1=this.rect;_1.right=_1.left+_h;_1.bottom=_1.top+_D;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_3u,_2f){this.rect.offsetBy(_3u,_2f);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _I=this.zIndex();this.parent.viewsZOrder.splice(_I,1);this.parent.viewsZOrder.push(this.viewId);this._2Z();},sendToBack:function(){if(!this.parent){return;}
var _I=this.zIndex();this.parent.viewsZOrder.splice(_I,1);this.parent.viewsZOrder.splice(0,0,this.viewId);this._2Z();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this.viewId);},stringWidth:function(_L,_2C,_b){if(_2C!==undefined&&_2C!=null){_L=_L.substring(0,_2C);}
if(_b===undefined||_b==null){_b=this.elemId;}
var _16=ELEM.make(_b);ELEM.setCSS(_16,"visibility:hidden;position:absolute;white-space:nowrap;");ELEM.setHTML(_16,_L);var _h=0,_D=0;if(ELEM._1n||ELEM._8A||ELEM._8B){_h=parseInt(ELEM.get(_16).offsetWidth,10);if(arguments[3]){_D=parseInt(ELEM.get(_16).offsetHeight,10);}}else{_h=parseInt(ELEM.get(_16).clientWidth,10);if(arguments[3]){_D=parseInt(ELEM.get(_16).clientHeight,10);}}
ELEM.del(_16);if(arguments[3]){return[_h,_D];}else{return _h;}},pageX:function(){var _4=0;var _9=this;while(_9){if(_9.elemId&&_9.rect){_4+=ELEM.get(_9.elemId).offsetLeft;_4-=ELEM.get(_9.elemId).scrollLeft;}
_9=_9.parent;}
return _4;},pageY:function(){var _c=0;var _9=this;while(_9){if(_9.elemId&&_9.rect){_c+=ELEM.get(_9.elemId).offsetTop;_c-=ELEM.get(_9.elemId).scrollTop;}
_9=_9.parent;}
return _c;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].invalidatePositionCache();}},bindDomElement:function(_08){var _3b=ELEM.bindId(_08);if(_3b){this._1i.push(_3b);}
return _3b;},unbindDomElement:function(_0o){var _4H=this._1i.indexOf(_0o);if(_4H>-1){ELEM.del(_0o);this._1i.splice(_4H,1);}},animateTo:function(_r,_0K,_0z){if(_r instanceof HPoint){var _1=new HRect(_r,_r);_1.setSize(this.rect.width,this.rect.height);this._38(_1,_0K);}
else if(_r instanceof HRect){this._38(_r,_0K);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._2l){window.clearInterval(this._2l);this._2l=null;var _00=parseInt(this.style('left'),10),_0w=parseInt(this.style('top'),10),_h=parseInt(this.style('width'),10),_D=parseInt(this.style('height'),10);this.rect.set(_00,_0w,_00+_h,_0w+_D);this.drawRect();if(this._45){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_38:function(_1,_0K,_0z){if(null===_0K||undefined===_0K){_0K=500;}
if(null===_0z||undefined===_0z||_0z<1){_0z=50;}
if(!this._2l){this._45=false;this.onAnimationStart();var _7w=new Date().getTime();var _l=this;this._2l=window.setInterval(function(){_l._8b({startTime:_7w,duration:_0K,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_l.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_l.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_l.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_l.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0z));}},_8b:function(_r){var _5L=new Date().getTime();if(_5L<_r.startTime+_r.duration){var _69=_5L-_r.startTime;for(var i=0;i<_r.props.length;i++){var _3q=_r.props[i].from;var _5N=_r.props[i].to;if(_3q!=_5N){var _7j=_r.transition(_69,_3q,(_5N-_3q),_r.duration);this.setStyle(_r.props[i].prop,_7j+_r.props[i].unit);}}}else{for(var i=0;i<_r.props.length;i++){this.setStyle(_r.props[i].prop,_r.props[i].to+_r.props[i].unit);}
this._45=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({refreshOnValueChange:true,refreshOnLabelChange:true,constructor:function(_1,_7,_2){if(!_2){_2={};}
var options=new(HComponentDefaults.extend(_2));this.options=options;if(this.isinherited){this.base(_1,_7);}
else{this.isinherited=true;this.base(_1,_7);this.isinherited=false;}
var _q=options.label;this.setLabel(_q);var _1T=options.events;this.setEvents(_1T);this.type='[HControl]';if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _6X=(_2.minValue||_2.maxValue);if(_6X){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(options.visible){this.show();}
else{this.hide();}
if(!this.isinherited){this.draw();}},setAction:function(_1B){this.action=_1B;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
EVENT.unreg(this);this.base();},setLabel:function(_q){this.label=_q;this.options.label=_q;this.refresh();},setEnabled:function(_0W){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].setEnabled(_0W);}
if(this.enabled===_0W){return;}
this.enabled=_0W;if(_0W){EVENT.reg(this,this.events);}
else{EVENT.unreg(this);}
this.toggleCSSClass(this.elemId,HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(this.elemId,HControl.CSS_DISABLED,!this.enabled);},setValue:function(_85){if(_85===undefined){return;}
if(!this.valueObj){return;}
if(_85!==this.value){this.value=_85;this.valueObj.set(this.value);this.refresh();}},setValueObj:function(_34){this.valueObj=_34;this.setValue(_34.value);},setValueRange:function(_85,_2J,_2G){this.minValue=_2J;this.maxValue=_2G;_85=(_85<_2J)?_2J:_85;_85=(_85>_2G)?_2G:_85;this.setValue(_85);this.refresh();},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}},refresh:function(){this.base();if(this.drawn){if(this.refreshOnValueChange){this.refreshValue();}
if(this.refreshOnLabelChange){this.refreshLabel();}}},setEvents:function(_1T){if(!this.events){var _6x=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,textEnter:false});this.events=new _6x;}
if(_1T){this.events.extend(_1T);}
this.events.ctrl=this;EVENT.focusOptions[this.elemId]=this.events;var _58=this.events.mouseMove;var _3H=EVENT.coordListeners.indexOf(this.elemId);if(_58&&(_3H==-1)){EVENT.coordListeners.push(this.elemId);}else if((!_58)&&(_3H!=-1)){EVENT.coordListeners.splice(_3H,1);}
this.isDragged=false;},setMouseMove:function(_0W){this.events.mouseMove=_0W;this.setEvents();},setMouseDown:function(_0W){this.events.mouseDown=_0W;this.setEvents();},setMouseUp:function(_0W){this.events.mouseUp=_0W;this.setEvents();},setMouseWheel:function(_0W){this.events.mouseWheel=_0W;this.setEvents();},setDraggable:function(_0W){this.events.draggable=_0W;this.setEvents();},setDroppable:function(_0W){this.events.droppable=_0W;this.setEvents();},setKeyDown:function(_0W){this.events.keyDown=_0W;this.setEvents();},setKeyUp:function(_0W){this.events.keyUp=_0W;this.setEvents();},setTextEnter:function(_0W){this.events.textEnter=_0W;this.setEvents();},textEnter:function(){},focus:function(){},blur:function(){},gainedActiveStatus:function(_2B){},_6F:function(_2B){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_2B);},lostActiveStatus:function(_E){},_71:function(_E){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_E);},mouseMove:function(_4,_c){},mouseDown:function(_4,_c,_01){},mouseUp:function(_4,_c,_01){},mouseWheel:function(_X){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_J){},keyUp:function(_J){},_5a:function(e){if(!Event.element){return;}
var _l=Event.element(e);while(_l&&_l.ctrl===undefined){_l=_l.parentNode;}
if(!_l){return;}
var _0=_l.ctrl;EVENT.focus(_0);Event.stop(e);},_59:function(e){if(!Event.element){return;}
var _l=Event.element(e);while(_l&&_l.ctrl===undefined){_l=_l.parentNode;}
if(!_l){return;}
var _0=_l.owner;EVENT.blur(_0);Event.stop(e);},invalidatePositionCache:function(){this.base();EVENT.coordCacheFlush(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_6,_85){this.id=_6;this.value=_85;this.type='[HDummyValue]';},set:function(_85){this.value=_85;},get:function(){return this.value;},bind:function(_2c){},unbind:function(_2c){}});HComponentDefaults=HClass.extend({label:"Untitled",visible:true,events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HDynControl=HControl.extend({componentName:'dyncontrol',constructor:function(_1,_7,_2){if(!_2){_2={};}
var _u=HClass.extend({minSize:[24,54],maxSize:[16000,9000],resizeW:1,resizeE:1,resizeN:1,resizeS:1,resizeNW:[1,1],resizeNE:[1,1],resizeSW:[1,1],resizeSE:[1,1],noResize:false});_2=new(_u.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.presrveTheme=true;this.setDraggable(true);this.type="[HDynControl]";this._6U();this._4J();if(!this.isinherited){this.draw();}},drawRect:function(_4V,_7O){if(this.rect.width<this.options.minSize[0]){var _3l=0-(this.options.minSize[0]-this.rect.width);this.rect.setWidth(this.options.minSize[0]);if(_4V){this.rect.offsetBy(_3l,0);}}
else if(this.rect.width>this.options.maxSize[0]){var _3l=0-(this.options.maxSize[0]-this.rect.width);this.rect.setWidth(this.options.maxSize[0]);if(_4V){this.rect.offsetBy(_3l,0);}}
if(this.rect.height<this.options.minSize[1]){var _3i=0-(this.options.minSize[1]-this.rect.height);this.rect.setHeight(this.options.minSize[1]);if(_7O){this.rect.offsetBy(0,_3i);}}
else if(this.rect.height>this.options.maxSize[1]){var _3i=0-(this.options.maxSize[1]-this.rect.height);this.rect.setHeight(this.options.maxSize[1]);if(_7O){this.rect.offsetBy(0,_3i);}}
this.base();},draw:function(){var _k=_0.drawn;this.base();this.drawRect();if(!_k){this.drawMarkup();this.buildStructure();}},buildStructure:function(){},_C:function(_4,_c){return this._7g.subtract(_4,_c);},dynResizeNW:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setLeftTop(_0.rect.leftTop.subtract(_N));_0.drawRect(1,1);_0._7g.set(_4,_c);},dynResizeNE:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setRightTop(_0.rect.rightTop.subtract(_N));_0.drawRect(0,1);_0._7g.set(_4,_c);},dynResizeSW:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setLeftBottom(_0.rect.leftBottom.subtract(_N));_0.drawRect(1,0);_0._7g.set(_4,_c);},dynResizeSE:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setRightBottom(_0.rect.rightBottom.subtract(_N));_0.drawRect(0,0);_0._7g.set(_4,_c);},dynResizeW:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setLeft(_0.rect.left-_N.x);_0.drawRect(1,0);_0._7g.set(_4,_c);},dynResizeE:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setRight(_0.rect.right-_N.x);_0.drawRect(0,0);_0._7g.set(_4,_c);},dynResizeN:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setTop(_0.rect.top-_N.y);_0.drawRect(0,1);_0._7g.set(_4,_c);},dynResizeS:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.setBottom(_0.rect.bottom-_N.y);_0.drawRect(0,0);_0._7g.set(_4,_c);},dynDrag:function(_0,_4,_c){var _N=_0._C(_4,_c);_0.rect.offsetTo(_0.rect.leftTop.subtract(_N));_0.drawRect(1,1);_0._7g.set(_4,_c);},_6U:function(){this._07=[];var i,_0=this,_8N=0,_8M=1,_8Q=2,_8P=3,_8R=4,_8K=5,_8L=6,_8O=7,_8n=8,_07=this._07;_07[_8N]=_0.dynResizeNW;_07[_8M]=_0.dynResizeNE;_07[_8Q]=_0.dynResizeSW;_07[_8P]=_0.dynResizeSE;_07[_8R]=_0.dynResizeW;_07[_8K]=_0.dynResizeE;_07[_8L]=_0.dynResizeN;_07[_8O]=_0.dynResizeS;_07[_8n]=_0.dynDrag;},_4J:function(){this._1C=-1;this._2i=[];var i,_27,_y=this.options,_1=this.rect,_7k=[[0,0,_y.resizeNW[0],_y.resizeNW[1]],[_1.width-_y.resizeNE[0],0,_1.width,_y.resizeNE[1]],[0,_1.height-_y.resizeSW[1],_y.resizeSW[0],_1.height],[_1.width-_y.resizeSE[0],_1.height-_y.resizeSE[1],_1.width,_1.height],[0,_y.resizeN,_y.resizeW,_1.height-_y.resizeS],[_1.width-_y.resizeE,_y.resizeN,_1.width,_1.height-_y.resizeS],[_y.resizeW,0,_1.width-_y.resizeE,_y.resizeN],[_y.resizeW,_1.height-_y.resizeS,_1.width-_y.resizeE,_1.height],[_y.resizeW,_y.resizeN,_1.width-_y.resizeE,_1.height-_y.resizeS]];for(i=0;i!=9;i++){_27=_7k[i];this._2i.push(new HRect(_27[0],_27[1],_27[2],_27[3]));}},_6n:function(){var i,_60=this._7v.subtract(this.rect.left,this.rect.top),_2i=this._2i;for(i=0;i!=9;i++){if(_2i[i].contains(_60)){this._1C=i;return;}}},startDrag:function(_4,_c,_2y){this._7v=new HPoint(_4,_c);this._7g=new HPoint(_4,_c);this._8Y=new HRect(this.rect);this._6n();if(this._1C==8){this.setStyle('cursor','move');}
this.bringToFront();this.doDrag(_4,_c,_2y);},doDrag:function(_4,_c,_2y){if(this._1C!=-1){this._07[this._1C](this,_4,_c);}},endDrag:function(_4,_c,_2y){this.doDrag(_4,_c,_2y);if(this._1C==8){this.setStyle('cursor','default');}
this._4J();}});