
HWindowBar=HButton.extend({packageName:"window",componentName:"windowbar",constructor:function(_1,_7,_2){if(!_2){_2={};}
if(!_2.events){_2.events={};}
if(!_2.events.draggable){_2.events.draggable=true;}
if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HWindowBar]';if(!this.isinherited){this.draw();}},setLabel:function(_q){this.label=_q;if(this.parent.windowLabel){this.parent.windowLabel.setLabel(_q);}},startDrag:function(_4,_c){this.parent.startDrag(_4,_c);},doDrag:function(_4,_c){this.parent.doDrag(_4,_c);},endDrag:function(_4,_c){this.parent.endDrag(_4,_c);}});HWindowLabel=HButton.extend({packageName:"window",componentName:"windowlabel",constructor:function(_1,_7,_2){if(!_2){_2={};}
if(!_2.events){_2.events={};}
if(!_2.events.draggable){_2.events.draggable=true;}
if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HWindowLabel]';if(!this.isinherited){this.draw();}},gainedActiveStatus:function(_2B){EVENT.changeActiveControl(this.parent.parent);},startDrag:function(_4,_c){this.parent.parent.startDrag(_4,_c);},doDrag:function(_4,_c){this.parent.parent.doDrag(_4,_c);},endDrag:function(_4,_c){this.parent.parent.endDrag(_4,_c);}});HWindowView=HView.extend({packageName:"window",flexTop:true,flexLeft:true,flexRight:true,flexBottom:true,flexTopOffset:24,flexLeftOffset:4,flexRightOffset:4,flexBottomOffset:4,constructor:function(_1,_7){if(this.isinherited){this.base(_1,_7);}
else{this.isinherited=true;this.base(_1,_7);this.isinherited=false;}
this.type='[HWindowView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){ELEM.setCSS(this.elemId,'position:absolute;border:1px solid #ccc;border-top: 0;background-color: #f7f7f7;overflow:auto;');}
this.drawRect();}},{_5M:"windowview"});HWindowControl=HControl.extend({packageName:"window",componentName:"windowcontrol",constructor:function(_1,_7,_2){if(!_2){_2={};}
var _u=Base.extend({minSize:[64,32],maxSize:[4096,3072],barHeight:21,resizeW:4,resizeE:4,resizeN:4,resizeS:4,resizeNW:[4,4],resizeNE:[4,4],resizeSW:[4,4],resizeSE:[16,16],menuBar:null});_2=new(_u.extend(_2))();if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HWindowControl]';this.preserveTheme=true;this._3Q();this.setDraggable(true);this.drawRect();this.drawMarkup();this.buildWinParts();this.setLabel(this.label);if(_2.menuBar){this.setMenuBar(_2.menuBar);}
if(!this.isinherited){this.draw();}},buildWinParts:function(){this.calcWindowPartRects();this.windowBar=new HWindowBar(this._i.windowBarRect,this,{label:this.label});this.windowBar.draw();this.windowLabel=new HWindowLabel(this._i.windowLabelRect,this.windowBar,{label:this.label});this.windowLabel.draw();this.windowView=new HWindowView(this._i.windowViewRect,this);this.windowView.draw();},_3Q:function(){this._i={dragWindow:false,resizeW:false,resizeE:false,resizeN:false,resizeS:false,resizeNW:false,resizeNE:false,resizeSW:false,resizeSE:false,dragWindowRect:new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN),resizeNRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.options.resizeN),resizeSRect:new HRect(this.options.resizeW,this.rect.height-this.options.resizeS,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,this.options.resizeN,this.options.resizeW,this.rect.height-this.options.resizeS),resizeERect:new HRect(this.rect.width-this.options.resizeE,this.options.resizeN,this.rect.width,this.rect.height-this.options.resizeS),resizeNWRect:new HRect(0,0,this.options.resizeNW[0],this.options.resizeNW[1]),resizeNERect:new HRect(this.rect.width-this.options.resizeNE[0],0,this.rect.width,this.options.resizeNE[1]),resizeSWRect:new HRect(0,this.rect.height-this.options.resizeSW[1],this.options.resizeSW[0],this.rect.height),resizeSERect:new HRect(this.rect.width-this.options.resizeSE[0],this.rect.height-this.options.resizeSE[1],this.rect.width,this.rect.height)};},checkWindowSizeConstrains:function(){var _5r=this._i.resizeW||this._i.resizeSW||this._i.resizeNW;var _5q=this._i.resizeN||this._i.resizeNE||this._i.resizeNW;if(this.rect.width<this.options.minSize[0]){if(_5r){this.rect.left=this.rect.right-this.options.minSize[0];}
this.rect.setWidth(this.options.minSize[0]);}else if(this.rect.width>this.options.maxSize[0]){if(_5r){this.rect.left=this.rect.right-this.options.maxSize[0];}
this.rect.setWidth(this.options.maxSize[0]);}
if(this.rect.height<this.options.minSize[1]){if(_5q){this.rect.top=this.rect.bottom-this.options.minSize[1];}
this.rect.setHeight(this.options.minSize[1]);}else if(this.rect.height>this.options.maxSize[1]){if(_5q){this.rect.top=this.rect.bottom-this.options.maxSize[1];}
this.rect.setHeight(this.options.maxSize[1]);}
var _3A=0-this.options.resizeW;if(this.rect.left<_3A){this.rect.left=_3A;this.rect.right=this.rect.width+_3A;}
var _3Y=0-this.options.resizeN;if(this.rect.top<_3Y){this.rect.top=_3Y;this.rect.bottom=this.rect.height+_3Y;}},startDrag:function(_4,_c){this._0T=new HPoint(_4,_c);this._2S=new HPoint(_4,_c);this._28=new HRect(this.rect);this._3Q();var _0s=this._0T.subtract(this._28.leftTop);if(this._i.resizeNWRect.contains(_0s)){this._C=_0s;this._i.resizeNW=true;}else if(this._i.resizeNERect.contains(_0s)){this._C=this._0T.subtract(this._28.rightTop);this._i.resizeNE=true;}else if(this._i.resizeSWRect.contains(_0s)){this._C=this._0T.subtract(this._28.leftBottom);this._i.resizeSW=true;}else if(this._i.resizeSERect.contains(_0s)){this._C=this._0T.subtract(this._28.rightBottom);this._i.resizeSE=true;}else if(this._i.resizeNRect.contains(_0s)){this._C=_c-this.rect.top;this._i.resizeN=true;}else if(this._i.resizeSRect.contains(_0s)){this._C=_c-this.rect.bottom;this._i.resizeS=true;}else if(this._i.resizeWRect.contains(_0s)){this._C=_4-this.rect.left;this._i.resizeW=true;}else if(this._i.resizeERect.contains(_0s)){this._C=_4-this.rect.right;this._i.resizeE=true;}else if(this._i.dragWindowRect.contains(_0s)){this._C=this._0T.subtract(this._28.leftTop);this._i.dragWindow=true;}
this.bringToFront();this.doDrag(_4,_c);},doDrag:function(_4,_c){var _s;var _11=new HPoint(_4,_c);if(!this._2S.equals(_11)){if(this._i.resizeNW==true){_s=_11.subtract(this._C);this.rect.setLeftTop(_s);}else if(this._i.resizeNE==true){_s=_11.subtract(this._C);this.rect.setRightTop(_s);}else if(this._i.resizeSW==true){_s=_11.subtract(this._C);this.rect.setLeftBottom(_s);}else if(this._i.resizeSE==true){_s=_11.subtract(this._C);this.rect.setRightBottom(_s);}else if(this._i.resizeN==true){_s=_c-this._C;this.rect.top=_s;this.rect.updateSecondaryValues();}else if(this._i.resizeS==true){_s=_c-this._C;this.rect.bottom=_s;this.rect.updateSecondaryValues();}else if(this._i.resizeW==true){_s=_4-this._C;this.rect.left=_s;this.rect.updateSecondaryValues();}else if(this._i.resizeE==true){_s=_4-this._C;this.rect.right=_s;this.rect.updateSecondaryValues();}else if(this._i.dragWindow==true){_s=_11.subtract(this._C);this.rect.offsetTo(_s);}
this.checkWindowSizeConstrains();this.setStyle('left',this.rect.left+'px',true);this.setStyle('top',this.rect.top+'px',true);this.setStyle('width',this.rect.width+'px',true);this.setStyle('height',this.rect.height+'px',true);if(this._i.dragWindow==false){this.calcWindowPartRects();}
this._2S=_11;}},endDrag:function(_4,_c){this.doDrag(_4,_c);},calcWindowPartRects:function(){var _32=new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN);var _5U=new HRect(0,0,_32.width,_32.height);var _2g=new HRect(this.options.resizeW,this.options.resizeN+this.options.barHeight,this.rect.width-this.options.resizeE,this.rect.height-this.options.resizeS);if(this.menuBar){var _2I=this.options.menuBarHeight;if(_2I+this.options.resizeN+this.options.barHeight>this.rect.height-this.options.resizeS){_2I=this.rect.height-this.options.barHeight-
this.options.resizeS-this.options.resizeN;}
_2g.setTop(_2g.top+_2I);this.menuBar.resizeTo(_2g.width,_2I);}
if(!this._i.windowBarRect){this._i.windowBarRect=_32;this._i.windowLabelRect=_5U;this._i.windowViewRect=_2g;}else{this.windowBar.setRect(_32);this.windowLabel.setRect(_5U);this.windowView.setRect(_2g);}},draw:function(){this.drawRect();},setLabel:function(_q){if(this.drawn&&this.windowLabel){this.windowLabel.setLabel(_q);}
this.base(_q);},refresh:function(){if(this.windowBar){this.windowBar.refresh();}
this.drawRect();},setMenuBar:function(_2H){if(_2H==this.menuBar){return;}
if(this.menuBar){this.menuBar.die();}
this.menuBar=_2H;if(_2H){this.options.menuBarHeight=this.menuBar.rect.height;this.menuBar.remove();this.addView(this.menuBar);ELEM.append(this.menuBar.elemId,this.elemId);this.menuBar.moveTo(this.windowView.rect.left,this.windowBar.rect.bottom);}
this.calcWindowPartRects();},stopAnimation:function(){this.base();this.calcWindowPartRects();this.refresh();}});HWindow=HWindowControl;