
HButton=HControl.extend({componentName:"button",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}
this._2v=[this.rect.width,this.rect.height];},setLabelHeightDiff:function(_73){this._4S=_73;return'';},setLabelWidthDiff:function(_74){this._4T=_74;return'';},onIdle:function(){if(this.drawn){var _h=this.rect.width;var _D=this.rect.height;if((_h!=this._2v[0])||(_D!=this._2v[1])){this._2v[0]=_h;this._2v[1]=_D;if(this.markupElemIds.label){var _4B=parseInt(_D+this._4S,10);ELEM.setStyle(this.markupElemIds.label,'line-height',_4B+'px');if(ELEM._1n){var _81=parseInt(_h+this._4T,10);ELEM.setStyle(this.markupElemIds.label,'height',_4B+'px');ELEM.setStyle(this.markupElemIds.label,'width',_81+'px');}}}}},draw:function(){if(!this.drawn){this.drawRect();this._4S=0;this._4T=0;this.drawMarkup();}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}}});HClickButton=HButton.extend({constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HClickButton]';this.setMouseDown(true);this.setMouseUp(true);this._1e=false;this._1V=false;if(!this.isinherited){this.draw();}},focus:function(){if(!this._1e&&!this._1V){this._1V=true;this._1e=false;}
this.base();},blur:function(){if(!this._1e){this._1V=false;}
this.base();},mouseDown:function(x,y,_01){if(this._1V){this._1e=true;}
this.base(x,y,_01);},mouseUp:function(x,y,_01){if(this._1V&&this._1e){this._1e=false;this.click(x,y,_01);}
this.base(x,y,_01);},click:function(x,y,_01){this.setValue(this.value+1);if(this.action){this.action();}}});HToggleButton=HClickButton.extend({constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HToggleButton]';if(!this.isinherited){this.draw();}},click:function(x,y,_01){this.setValue(!this.value);},setValue:function(_0W){if(null===_0W||undefined===_0W){_0W=false;}
this.base(_0W);},_7Q:function(){if(this.markupElemIds.control){var _9=ELEM.get(this.markupElemIds.control);this.toggleCSSClass(_9,HToggleButton.cssOn,this.value);this.toggleCSSClass(_9,HToggleButton.cssOff,!this.value);}},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}
if(this.markupElemIds.control){this._7Q();}}}},{cssOn:"on",cssOff:"off"});HStringView=HControl.extend({componentName:"stringview",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HStringView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_7,_2){this.markupElemIds={};if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HTextControl]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},die:function(){if(this.drawn){var _08='value'+this.elemId;Event.stopObserving(_08,'mousedown',this._2V);Event.stopObserving(_08,'mousemove',this._2V);Event.stopObserving(_08,'focus',this._43);Event.stopObserving(_08,'blur',this._4m);}
this.base();},setEnabled:function(_0W){this.base(_0W);if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,"autocomplete","off");this.setEnabled(this.enabled);}
this._7t();this.drawn=true;}
this.refresh();},_7t:function(){var _08='value'+this.elemId;this._2V=function(_6w){HControl.stopPropagation(_6w);};Event.observe(_08,'mousedown',this._2V,false);Event.observe(_08,'mousemove',this._2V,false);var _l=this;this._43=function(event){EVENT.changeActiveControl(_l);};Event.observe(_08,'focus',this._43,false);this._4m=function(event){_l._7R();EVENT.changeActiveControl(null);};Event.observe(_08,'blur',this._4m,false);},refresh:function(){this.base();if(this.markupElemIds.value){if(ELEM.getAttr(this.markupElemIds.value,'value',true)!=this.value){ELEM.setAttr(this.markupElemIds.value,'value',this.value,true);}}},onIdle:function(){if(this.active){this._7R();}},_7R:function(){if(this.drawn){if(ELEM.getAttr(this.markupElemIds.value,'value',true)!=this.value){this.setValue(ELEM.getAttr(this.markupElemIds.value,'value',true));}}},lostActiveStatus:function(_E){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).blur();}}});HTextArea=HTextControl.extend({componentName:"textarea",constructor:function(_1,_7,_2){this.base(_1,_7,_2);}});HSlider=HControl.extend({packageName:"sliders",componentName:"slider",constructor:function(_1,_7,_2){if(!_2){_2={};}
_2.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _u=Base.extend({minValue:0,maxValue:1});_u=_u.extend(_2);_2=new _u();if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HSlider]';this.refreshOnValueChange=false;this._4Q='sliderknob';this._0q=false;if(!this.isinherited){this.draw();}},setValue:function(_85){if(_85<this.minValue){_85=this.minValue;}
if(_85>this.maxValue){_85=this.maxValue;}
this.base(_85);if(this._3x){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._6V();}
this.refresh();},startDrag:function(_4,_c){var _8=ELEM.get(this.elemId);var _5k=helmi.Element.getPageLocation(_8,true);this._7a=_5k[0];this._7b=_5k[1];this.doDrag(_4,_c);},endDrag:function(_4,_c){this.doDrag(_4,_c);},doDrag:function(_4,_c){_4-=this._7a;_c-=this._7b;_8H=this._0q?_c:_4;_85=this._7f(_8H);this.setValue(_85);},keyDown:function(_J){if((_J==Event.KEY_LEFT&&!this._0q)||(_J==Event.KEY_UP&&this._0q)){this._22=true;this._2L(-0.05);}
else if((_J==Event.KEY_RIGHT&&!this._0q)||(_J==Event.KEY_DOWN&&this._0q)){this._22=true;this._2L(0.05);}
else if(_J==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_J==Event.KEY_END){this.setValue(this.maxValue);}
else if(_J==Event.KEY_PAGEUP){this._22=true;this._2L(-0.25);}
else if(_J==Event.KEY_PAGEDOWN){this._22=true;this._2L(0.25);}},keyUp:function(_J){this._22=false;},mouseWheel:function(_X){var _1A;if(_X>0){_1A=-0.05;}
else{_1A=0.05;}
_85=(this.maxValue-this.minValue)*_1A;this.setValue(this.value+_85);},_2L:function(_1A,_1v){if(!_1v){_1v=300;}
else if(_1v==300){_1v=50;}
if(this._22&&this.active){_85=(this.maxValue-this.minValue)*_1A;this.setValue(this.value+_85);var _l=this;if(this._3y){window.clearTimeout(this._3y);this._3y=null;}
this._3y=window.setTimeout(function(){_l._2L(_1A,_1v);},_1v);}},_6V:function(){this._3x=this.bindDomElement(this._4Q+this.elemId);this.drawKnobPos();},_0G:function(){var _9=ELEM.get(this._3x);if(this._0q){_5o=this.rect.height-parseInt(_9.offsetHeight,10);}else{_5o=this.rect.width-parseInt(_9.offsetWidth,10);}
_0C=_5o*((this.value-this.minValue)/(this.maxValue-this.minValue));_0E=parseInt(_0C,10)+'px';return _0E;},_7f:function(_5b){_0Q=this._0q?(_5b):(_5b);if(_0Q<0){_0Q=0;}
if(this._0q){if(_0Q>this.rect.height){_0Q=this.rect.height;}
return this.minValue+((_0Q/this.rect.height)*(this.maxValue-this.minValue));}else{if(_0Q>this.rect.width){_0Q=this.rect.width;}
return this.minValue+((_0Q/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_95=this._0q?'top':'left';_3N=this._0G();ELEM.setStyle(this._3x,_95,_3N);}});HVSlider=HSlider.extend({packageName:"sliders",componentName:"vslider",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HVSlider]';this._4Q='vsliderknob';this._0q=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
if(!_2){_2={};}
var _u=Base.extend({value:0,minValue:0,maxValue:100});_u=_u.extend(_2);_2=new _u();this.value=_2.value;this.minValue=_2.minValue;this.maxValue=_2.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._3M='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_P){this.progressFrameHeight=_P;},setProgressFrameNum:function(_2P){this.progressFrames=_2P;},setValue:function(_85){this.base(_85);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _P=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_P+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3w();}},_3w:function(){this.progressbarElemId=this.bindDomElement(this._3M+this.elemId);this.drawProgress();},_0G:function(){var _0C=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _0E=parseInt(Math.round(_0C),10)+'px';return _0E;},drawProgress:function(){if(this.progressbarElemId){var _3N=this._0G();ELEM.setStyle(this.progressbarElemId,'width',_3N);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
if(!_2){_2={};}
var _u=Base.extend({value:0,interval:20});_u=_u.extend(_2);_2=new _u();this.type='[HProgressIndicator]';this._3M='progressmark';this.interval=_2.interval;this.value=_2.value;this._1g=null;if(!this.isinherited){this.draw();}},setValue:function(_85){if(this._3L){if(_85==true&&!this._1g){var temp=this;this._1g=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._1g);this._1g=null;}}},die:function(){this.base();if(this._1g){clearInterval(this._1g);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._3w();}},_3w:function(){this._3L=this.bindDomElement(this._3M+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._3L){ELEM.setStyle(this._3L,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_1,_7,_2){if(!_2){_2={};}
var _u=HClass.extend({scaleToFit:true});_2=new(_u.extend(_2))();if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
this.type='[HImageView]';if(!this.isinherited){this.draw();}},_55:function(_2Q){this.elemId=ELEM.make(_2Q,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_56:function(_2Q){this.elemId=ELEM.make(_2Q,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_54:function(_2Q){if(this.options.scaleToFit){this._55(_2Q);}
else{this._56(_2Q);}},setValue:function(_85){this.base(_85);ELEM.setAttr(this.elemId,'src',_85);},setLabel:function(_q){this.base(_q);ELEM.setAttr(this.elemId,'alt',_q);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._55(this._3r());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._56(this._3r());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_7,_2){_2=new(Base.extend({vertical:false}).extend(_2));if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HSplitView]';this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_4,_c,_M){if(!_M){return;}
_4-=this.pageX();_c-=this.pageY();var _I=this.dividers.indexOfObject(_M);this._0T=new HPoint(_4,_c);this._2S=new HPoint(_4,_c);this._C=this._0T.subtract(_M.rect.leftTop);this._0j=this.splitviews[_I];this._U=this.splitviews[_I+1];this._M=_M;if(this.vertical==false){this._2D=this._0j.rect.top;this._2E=this._U.rect.bottom-this.dividerWidth;}else{this._2D=this._0j.rect.left;this._2E=this._U.rect.right-this.dividerWidth;}},doDrag:function(_4,_c,_M){if(!_M){return;}
_4-=this.pageX();_c-=this.pageY();if(this.vertical==false){var _s=_c-this._C.y;if(_s<this._2D||_s>this._2E){return;}
this._0j.rect.setHeight(_s);this._0j.rect.updateSecondaryValues();this._0j.setStyle('height',this._0j.rect.height+'px',true);this._M.rect.setTop(_s);this._M.rect.updateSecondaryValues();this._M.setStyle('top',this._M.rect.top+'px',true);this._U.rect.setTop(_s+this.dividerWidth);this._U.rect.updateSecondaryValues();this._U.setStyle('top',this._U.rect.top+'px',true);this._U.setStyle('height',this._U.rect.height+'px',true);}else{var _s=_4-this._C.x;if(_s<this._2D||_s>this._2E){return;}
this._0j.rect.setRight(_s);this._0j.rect.updateSecondaryValues();this._0j.setStyle('width',this._0j.rect.width+'px',true);this._M.rect.setLeft(_s);this._M.rect.updateSecondaryValues();this._M.setStyle('left',this._M.rect.left+'px',true);this._U.rect.setLeft(_s+this.dividerWidth);this._U.rect.updateSecondaryValues();this._U.setStyle('left',this._U.rect.left+'px',true);this._U.setStyle('width',this._U.rect.width+'px',true);}},endDrag:function(_4,_c,_M){this.doDrag(_4,_c);delete this._0T;delete this._2S;delete this._C;delete this._0j;delete this._U;delete this._M;delete this._2D;delete this._2E;},addSplitViewItem:function(_0M,_I){if(_I!==undefined){this.splitviews.splice(_I,0,_0M);}else{this.splitviews.push(_0M);}},removeSplitViewItem:function(_0M){if(typeof _0M=="object"){var _I=this.splitviews.indexOfObject(_0M);if(_I!=-1){this.splitviews.splice(_I,1);_0M.die();this.dividers.splice(_I,1);this.dividers[_I].die();}}},setVertical:function(_0W){this.vertical=_0W;this.options.vertical=_0W;},adjustViews:function(){var _0x=this.splitviews.length;var _2N;var _1s;var _2U;var _1w;if(this.vertical==false){_2N=this.rect.height-this.dividerWidth*(_0x-1);_1s=0;for(var i=0;i<_0x;i++){_1s+=this.splitviews[i].rect.height;}
_2U=_2N/_1s;_1w=0;for(var i=0;i<_0x;i++){var _p=this.splitviews[i];var _1q=_p.rect.height*_2U;if(i==_0x-1){_1q=Math.floor(_1q);}else{_1q=Math.ceil(_1q);}
_p.rect.offsetTo(0,_1w);_p.rect.setSize(this.rect.width,_1q);_p.draw();_1w+=_1q+this.dividerWidth;}}else{_2N=this.rect.width-this.dividerWidth*(_0x-1);_1s=0;for(var i=0;i<_0x;i++){_1s+=this.splitviews[i].rect.width;}
_2U=_2N/_1s;_1w=0;for(var i=0;i<_0x;i++){var _p=this.splitviews[i];var _1r=_p.rect.width*_2U;if(i==_0x-1){_1r=Math.floor(_1r);}else{_1r=Math.ceil(_1r);}
_p.rect.offsetTo(_1w,0);_p.rect.setSize(_1r,this.rect.height);_p.draw();_1w+=_1r+this.dividerWidth;}}
this.draw();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){this.base();if(this.drawn){var _0x=this.splitviews.length;var _Y;for(var i=0;i<(_0x-1);i++){_Y=new HRect(this.splitviews[i].rect);if(!this.vertical){_Y.offsetTo(_Y.left,_Y.bottom);_Y.setHeight(this.dividerWidth);}else{_Y.offsetTo(_Y.right,_Y.top);_Y.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_Y,this);}else{var _p=this.dividers[i];_p.rect.offsetTo(_Y.left,_Y.top);_p.rect.setSize(_Y.width,_Y.height);_p.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_7,_2){if(!_2){_2={};}
_2.events={mouseDown:true,keyDown:true,mouseWheel:true};var _u=Base.extend({minValue:0,value:0,interval:500});_u=_u.extend(_2);_2=new _u();if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.interval=_2.interval;this.type='[HStepper]';this._92="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_85){_85--;_85=(_85<this.minValue)?this.maxValue:_85;this.setValue(_85);},stepDown:function(_85){_85++;_85=(_85>this.maxValue)?this.minValue:_85;this.setValue(_85);},mouseDown:function(_4,_c,_06){this.setMouseUp(true);var temp=this;if(_c<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_4,_c,_06){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_J){this.setKeyUp(true);var temp=this;if(_J==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_J==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_J){clearInterval(this.counter);},mouseWheel:function(_X){if(_X>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HRadiobutton=HToggleButton.extend({componentName:"radiobutton",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HRadiobutton]';if(!this.isinherited){this.draw();}},setValueMatrix:function(_5Z){this.valueMatrix=_5Z;this.valueMatrixIndex=this.valueMatrix.addValue(this.valueObj,this.value);},click:function(x,y,_01){this.base(x,y,_01);if(undefined!==this.valueMatrix&&this.valueMatrix instanceof HValueMatrix){this.valueMatrix.setValue(this.valueMatrixIndex);}}});HRadioButton=HRadiobutton;HPasswordControl=HTextControl.extend({componentName:"passwordcontrol",constructor:function(_1,_7,_2){this.base(_1,_7,_2);}});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_4,_c){this.parent.startDrag(_4,_c,this);},doDrag:function(_4,_c){this.parent.doDrag(_4,_c,this);},endDrag:function(_4,_c){this.parent.endDrag(_4,_c,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HCheckbox=HToggleButton.extend({componentName:"checkbox",constructor:function(_1,_7,_2){if(this.isinherited){this.base(_1,_7,_2);}
else{this.isinherited=true;this.base(_1,_7,_2);this.isinherited=false;}
this.type='[HCheckbox]';if(!this.isinherited){this.draw();}}});