
HButton=HControl.extend({componentName:'button'});HCheckbox=HButton.extend({componentName:'checkbox',constructor:function(_1,_i,_6D){this.base(_1,_i,_6D);this.setClickable(true);},click:function(){this.setValue(!this.value);},refreshValue:function(){if(this.markupElemIds.control){if(this.value){this.toggleCSSClass(this.markupElemIds.control,'checked',true);this.toggleCSSClass(this.markupElemIds.control,'unchecked',false);}
else{this.toggleCSSClass(this.markupElemIds.control,'checked',false);this.toggleCSSClass(this.markupElemIds.control,'unchecked',true);}}}});HCheckBox=HCheckbox;HRadioButton=(HCheckbox.extend(HValueMatrixComponentExtension)).extend({componentName:'radiobutton'});HRadiobutton=HRadioButton;HStringView=HControl.extend({componentName:"stringview",componentBehaviour:['view','control','text'],refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'title',this.label);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_x,_6D){this.base(_1,_x,_6D);this.setTextEnter(true);},setEnabled:function(_8){this.base(_8);if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).value=this.value;}}},textEnter:function(){if(this['markupElemIds']===undefined){return;}
var _4=ELEM.get(this.markupElemIds.value).value;if(_4!=this.value){this.setValue(_4);}}});HTextArea=HTextControl.extend({componentName:"textarea"});HSlider=HControl.extend({componentName:"slider",constructor:function(_1,_x,_6D){if(!_6D){_6D={};}
_6D.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _r=Base.extend({minValue:0,maxValue:1});_r=_r.extend(_6D);_6D=new _r();if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
this.refreshOnValueChange=false;this._3Y='sliderknob';this._0e=false;if(!this.isinherited){this.draw();}},setValue:function(_4){if(_4<this.minValue){_4=this.minValue;}
if(_4>this.maxValue){_4=this.maxValue;}
this.base(_4);if(this._2S){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._5F();}
this.refresh();},startDrag:function(_7,_b){var _5=ELEM.get(this.elemId);var _4l=helmi.Element.getPageLocation(_5,true);this._5P=_4l[0];this._5Q=_4l[1];this.doDrag(_7,_b);},endDrag:function(_7,_b){this.doDrag(_7,_b);},doDrag:function(_7,_b){_7-=this._5P;_b-=this._5Q;_7f=this._0e?_b:_7;_4=this._5V(_7f);this.setValue(_4);},keyDown:function(_z){if((_z==Event.KEY_LEFT&&!this._0e)||(_z==Event.KEY_UP&&this._0e)){this._1C=true;this._2d(-0.05);}
else if((_z==Event.KEY_RIGHT&&!this._0e)||(_z==Event.KEY_DOWN&&this._0e)){this._1C=true;this._2d(0.05);}
else if(_z==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_z==Event.KEY_END){this.setValue(this.maxValue);}
else if(_z==Event.KEY_PAGEUP){this._1C=true;this._2d(-0.25);}
else if(_z==Event.KEY_PAGEDOWN){this._1C=true;this._2d(0.25);}},keyUp:function(_z){this._1C=false;},mouseWheel:function(_O){var _1d;if(_O>0){_1d=-0.05;}
else{_1d=0.05;}
_4=(this.maxValue-this.minValue)*_1d;this.setValue(this.value+_4);},_2d:function(_1d,_18){if(!_18){_18=300;}
else if(_18==300){_18=50;}
if(this._1C&&this.active){_4=(this.maxValue-this.minValue)*_1d;this.setValue(this.value+_4);var _k=this;if(this._2T){window.clearTimeout(this._2T);this._2T=null;}
this._2T=window.setTimeout(function(){_k._2d(_1d,_18);},_18);}},_5F:function(){this._2S=this.bindDomElement(this._3Y+this.elemId);this.drawKnobPos();},_3i:function(){var _6=ELEM.get(this._2S);if(this._0e){_4o=this.rect.height-parseInt(_6.offsetHeight,10);}else{_4o=this.rect.width-parseInt(_6.offsetWidth,10);}
_2R=_4o*((this.value-this.minValue)/(this.maxValue-this.minValue));_39=parseInt(_2R,10)+'px';return _39;},_5V:function(_4b){_0x=this._0e?(_4b):(_4b);if(_0x<0){_0x=0;}
if(this._0e){if(_0x>this.rect.height){_0x=this.rect.height;}
return this.minValue+((_0x/this.rect.height)*(this.maxValue-this.minValue));}else{if(_0x>this.rect.width){_0x=this.rect.width;}
return this.minValue+((_0x/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_7C=this._0e?'top':'left';_37=this._3i();ELEM.setStyle(this._2S,_7C,_37);}});HVSlider=HSlider.extend({componentName:"vslider",constructor:function(_1,_x,_6D){if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
this.type='[HVSlider]';this._3Y='vsliderknob';this._0e=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_x,_6D){if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
if(!_6D){_6D={};}
var _r=Base.extend({value:0,minValue:0,maxValue:100});_r=_r.extend(_6D);_6D=new _r();this.value=_6D.value;this.minValue=_6D.minValue;this.maxValue=_6D.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._36='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_V){this.progressFrameHeight=_V;},setProgressFrameNum:function(_2h){this.progressFrames=_2h;},setValue:function(_4){this.base(_4);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _V=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_V+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._2Q();}},_2Q:function(){this.progressbarElemId=this.bindDomElement(this._36+this.elemId);this.drawProgress();},_3i:function(){var _2R=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _39=parseInt(Math.round(_2R),10)+'px';return _39;},drawProgress:function(){if(this.progressbarElemId){var _37=this._3i();ELEM.setStyle(this.progressbarElemId,'width',_37);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_x,_6D){if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
if(!_6D){_6D={};}
var _r=Base.extend({value:0,interval:20});_r=_r.extend(_6D);_6D=new _r();this.type='[HProgressIndicator]';this._36='progressmark';this.interval=_6D.interval;this.value=_6D.value;this._0V=null;if(!this.isinherited){this.draw();}},setValue:function(_4){if(this._35){if(_4==true&&!this._0V){var temp=this;this._0V=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._0V);this._0V=null;}}},die:function(){this.base();if(this._0V){clearInterval(this._0V);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._2Q();}},_2Q:function(){this._35=this.bindDomElement(this._36+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._35){ELEM.setStyle(this._35,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_1,_x,_6D){if(!_6D){_6D={};}
var _r=HClass.extend({scaleToFit:true});_6D=new(_r.extend(_6D))();if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
if(!this.isinherited){this.draw();}},_46:function(_2i){this.elemId=ELEM.make(_2i,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_47:function(_2i){this.elemId=ELEM.make(_2i,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_45:function(_2i){if(this.options.scaleToFit){this._46(_2i);}
else{this._47(_2i);}},refreshValue:function(){ELEM.setAttr(this.elemId,'src',this.value);},refreshLabel:function(){ELEM.setAttr(this.elemId,'alt',this.label);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._46(this._2M());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._47(this._2M());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_x,_6D){_6D=new(Base.extend({vertical:false}).extend(_6D));if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_7,_b,_C){if(!_C){return;}
_7-=this.pageX();_b-=this.pageY();var _p=this.dividers.indexOfObject(_C);this._4x=new HPoint(_7,_b);this._5X=new HPoint(_7,_b);this._20=this._4x.subtract(_C.rect.leftTop);this._07=this.splitviews[_p];this._K=this.splitviews[_p+1];this._C=_C;if(this.vertical==false){this._28=this._07.rect.top;this._29=this._K.rect.bottom-this.dividerWidth;}else{this._28=this._07.rect.left;this._29=this._K.rect.right-this.dividerWidth;}},doDrag:function(_7,_b,_C){if(!_C){return;}
_7-=this.pageX();_b-=this.pageY();if(this.vertical==false){var _09=_b-this._20.y;if(_09<this._28||_09>this._29){return;}
this._07.rect.setHeight(_09);this._07.rect.updateSecondaryValues();this._07.setStyle('height',this._07.rect.height+'px',true);this._C.rect.setTop(_09);this._C.rect.updateSecondaryValues();this._C.setStyle('top',this._C.rect.top+'px',true);this._K.rect.setTop(_09+this.dividerWidth);this._K.rect.updateSecondaryValues();this._K.setStyle('top',this._K.rect.top+'px',true);this._K.setStyle('height',this._K.rect.height+'px',true);}else{var _09=_7-this._20.x;if(_09<this._28||_09>this._29){return;}
this._07.rect.setRight(_09);this._07.rect.updateSecondaryValues();this._07.setStyle('width',this._07.rect.width+'px',true);this._C.rect.setLeft(_09);this._C.rect.updateSecondaryValues();this._C.setStyle('left',this._C.rect.left+'px',true);this._K.rect.setLeft(_09+this.dividerWidth);this._K.rect.updateSecondaryValues();this._K.setStyle('left',this._K.rect.left+'px',true);this._K.setStyle('width',this._K.rect.width+'px',true);}},endDrag:function(_7,_b,_C){this.doDrag(_7,_b);delete this._4x;delete this._5X;delete this._20;delete this._07;delete this._K;delete this._C;delete this._28;delete this._29;},addSplitViewItem:function(_0v,_p){if(_p!==undefined){this.splitviews.splice(_p,0,_0v);}else{this.splitviews.push(_0v);}},removeSplitViewItem:function(_0v){if(typeof _0v=="object"){var _p=this.splitviews.indexOfObject(_0v);if(_p!=-1){this.splitviews.splice(_p,1);_0v.die();this.dividers.splice(_p,1);this.dividers[_p].die();}}},setVertical:function(_8){this.vertical=_8;this.options.vertical=_8;},adjustViews:function(){var _0i=this.splitviews.length;var _2f;var _15;var _2k;var _19;if(this.vertical==false){_2f=this.rect.height-this.dividerWidth*(_0i-1);_15=0;for(var i=0;i<_0i;i++){_15+=this.splitviews[i].rect.height;}
_2k=_2f/_15;_19=0;for(var i=0;i<_0i;i++){var _g=this.splitviews[i];var _13=_g.rect.height*_2k;if(i==_0i-1){_13=Math.floor(_13);}else{_13=Math.ceil(_13);}
_g.rect.offsetTo(0,_19);_g.rect.setSize(this.rect.width,_13);_g.draw();_19+=_13+this.dividerWidth;}}else{_2f=this.rect.width-this.dividerWidth*(_0i-1);_15=0;for(var i=0;i<_0i;i++){_15+=this.splitviews[i].rect.width;}
_2k=_2f/_15;_19=0;for(var i=0;i<_0i;i++){var _g=this.splitviews[i];var _14=_g.rect.width*_2k;if(i==_0i-1){_14=Math.floor(_14);}else{_14=Math.ceil(_14);}
_g.rect.offsetTo(_19,0);_g.rect.setSize(_14,this.rect.height);_g.draw();_19+=_14+this.dividerWidth;}}
this.draw();},refresh:function(){this.base();if(this.drawn){var _0i=this.splitviews.length;var _P;for(var i=0;i<(_0i-1);i++){_P=new HRect(this.splitviews[i].rect);if(!this.vertical){_P.offsetTo(_P.left,_P.bottom);_P.setHeight(this.dividerWidth);}else{_P.offsetTo(_P.right,_P.top);_P.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_P,this);}else{var _g=this.dividers[i];_g.rect.offsetTo(_P.left,_P.top);_g.rect.setSize(_P.width,_P.height);_g.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_x,_6D){if(!_6D){_6D={};}
_6D.events={mouseDown:true,keyDown:true,mouseWheel:true};var _r=Base.extend({minValue:0,value:0,interval:500});_r=_r.extend(_6D);_6D=new _r();if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
this.interval=_6D.interval;this._7z="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_4){_4--;_4=(_4<this.minValue)?this.maxValue:_4;this.setValue(_4);},stepDown:function(_4){_4++;_4=(_4>this.maxValue)?this.minValue:_4;this.setValue(_4);},mouseDown:function(_7,_b,_U){this.setMouseUp(true);var temp=this;if(_b<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_7,_b,_U){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_z){this.setKeyUp(true);var temp=this;if(_z==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_z==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_z){clearInterval(this.counter);},mouseWheel:function(_O){if(_O>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HPasswordControl=HTextControl.extend({componentName:"passwordcontrol"});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_x,_6D){if(this.isinherited){this.base(_1,_x,_6D);}
else{this.isinherited=true;this.base(_1,_x,_6D);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_7,_b){this.parent.startDrag(_7,_b,this);},doDrag:function(_7,_b){this.parent.doDrag(_7,_b,this);},endDrag:function(_7,_b){this.parent.endDrag(_7,_b,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HValidatorView=HControl.extend({constructor:function(_1,_i,_6D){if(_6D!==undefined){if(_6D.valueField!==undefined){_1.offsetTo(_6D.valueField.rect.right,_6D.valueField.rect.top);}}
if(this.isinherited){this.base(_1,_i,_6D);}
else{this.isinherited=true;this.base(_1,_i,_6D);this.isinherited=false;}
if(!this.isinherited){this.draw();}},setValue:function(_8){if(null===_8||undefined===_8){_8=false;}
this.base(_8);},refresh:function(){this.base();this._6r();},_6r:function(){var _7=0,_b=0;this.setStyle('background-image',"url('"+this.getThemeGfxFile('validator.png')+"')");this.setStyle('background-repeat','no-repeat');if(this.enabled==false){_b=-21;}
if(this.value==true){_7=-21;_4K='';}else{_4K=this.value;}
ELEM.setAttr(this.elemId,'title',_4K);this.setStyle('background-position',_7+'px '+_b+'px');}});HWindow=HDynControl.extend({componentName:'window',constructor:function(_1,_7e,_6D){if(_7e.componentBehaviour[0]!='app'){console.log("Himle.ComponentParentError","HWindow parent must be an HApplication instance!");}
if(!_6D){_6D={};}
var _r=HClass.extend({minSize:[96,54],maxSize:[16000,9000],resizeW:2,resizeE:2,resizeN:2,resizeS:2,resizeNW:[2,2],resizeNE:[2,2],resizeSW:[2,2],resizeSE:[16,16],noResize:false});_6D=new(_r.extend(_6D))();if(_6D.noResize){_6D.minSize=[_1.width,_1.height];_6D.maxSize=[_1.width,_1.height];_6D.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
this.base(_1,_7e,_6D);this.windowView=this;HSystem.windowFocus(this);},gainedActiveStatus:function(){HSystem.windowFocus(this);},windowFocus:function(){this.toggleCSSClass(this.elemId,'inactive',false);this.setStyle('cursor','move');},windowBlur:function(){this.toggleCSSClass(this.elemId,'inactive',true);this.setStyle('cursor','default');}});HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _0J=this.drawn;this.base();if(!_0J){var i=0,_3e=[['overflow','auto']];for(i;i<_3e.length;i++){this.setStyle(_3e[i][0],_3e[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_1,_i,_6D){this.tabInit();if(this.isinherited){this.base(_1,_i,_6D);}
else{this.isinherited=true;this.base(_1,_i,_6D);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_4){this.base(_4);if(typeof _4=='number'){var _p=parseInt(_4,10);if(_p<this.tabs.length){if(_p!=this.selectIdx){this.selectTab(_p);}}}},stringWidth:function(_1a,_9){var _0I='<span style="'+this.fontStyle+'">'+_1a+'</span>',_q=this.base(_0I,null,_9);return _q;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_J){this.label=_J;},selectTab:function(_o){if(_o instanceof HTabView){_o=_o.tabIndex;}
if(this.selectIdx!=-1){var _4E=this.tabLabels[this.selectIdx],_6l=this.tabs[this.selectIdx];ELEM.removeClassName(_4E,'item-fg');ELEM.addClassName(_4E,'item-bg');HSystem.views[_6l].hide();}
if(_o!=-1){var _00=this.tabLabels[_o],_3f=this.tabs[_o];ELEM.removeClassName(_00,'item-bg');ELEM.addClassName(_00,'item-fg');HSystem.views[_3f].show();}
this.selectIdx=_o;this.setValue(_o);},addTab:function(_2l,_6O){var _o=this.tabs.length,_4D='',_5I=this.stringWidth(_2l,0),_2U=_5I+this.tabLabelLeftEdge+this.tabLabelRightEdge,_1c=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_o=this.tabs.length,_00=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);if(this.tabLabelNoHTMLPrefix){_4D=_2l;}
else{_4D=this.tabLabelHTMLPrefix1+_5I+this.tabLabelHTMLPrefix2+_2l+this.tabLabelHTMLSuffix;}
_1c.hide();ELEM.addClassName(_00,'item-bg');ELEM.setStyle(_00,'width',_2U+'px');ELEM.setStyle(_00,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_00,_4D);this.tabLabelStrings.push(_2l);if(this.tabTriggerLink&&this.tabLabelElementTagName=='a'){ELEM.setAttr(_00,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_o+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_00,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_o+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_2U]);}
this.rightmostPx+=_2U;if(this.tabLabelAlign=='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
this.tabs.push(_1c.viewId);this.tabLabels.push(_00);_1c.tabIndex=_o;if(_6O){this.selectTab(_o);}
return _1c;},mouseDown:function(_7,_b){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_7-=this.pageX();_b-=this.pageY();if(_b<=this.tabLabelHeight){if(this.tabLabelAlign=='right'){_7=this.rect.width-_7;}
if(_7<=this.rightmostPx){var i=0,_3Z;for(i;i<this.tabLabelBounds.length;i++){_3Z=this.tabLabelBounds[i];if(_7<_3Z[1]&&_7>=_3Z[0]){this.selectTab(i);return;}}}}},removeTab:function(_o){var _66=this.selectIdx,_3f=this.tabs[_o],_00=this.tabViews[_o];this.tabs.splice(_o,1);this.tabLabels.splice(_o,1);this.tabLabelBounds.splice(_o,1);this.tabLabelStrings.splice(_o,1);if(_o==_66){this.selectIdx=-1;if(_o==0&&this.tabs.length==0){this.selectTab(-1);}
else if(_o==(this.tabs.length-1)){this.selectTab(_o-1);}
else{this.selectTab(_o);}}
else if(_o<_66){this.selectIdx--;}
ELEM.del(_00);HSystem.views[_3f].die();},draw:function(){var _0J=this.drawn;this.base();if(!_0J){this.drawMarkup();}
this.refresh();}});