
var HClass=function(){if(arguments.length){var _3h=arguments[0];if(this==window){HClass.prototype.extend.call(_3h,arguments.callee.prototype);}else{this.extend(_3h);}}};HClass.prototype={extend:function(_0g,_6A){var _1u=HClass.prototype.extend;if(arguments.length==2){var _2r=this[_0g];if((_2r instanceof Function)&&(_6A instanceof Function)&&_2r.valueOf()!=_6A.valueOf()&&(/\bbase\b/).test(_6A)){var _30=_6A;_6A=function(){var _5V=this.base;this.base=_2r;var _60=_30.apply(this,arguments);this.base=_5V;return _60;};_6A.valueOf=function(){return _30;};_6A.toString=function(){return String(_30);};}
return this[_0g]=_6A;}else if(_0g){var _0o={toSource:null};var _4l=["toString","valueOf"];if(HClass._38){_4l.push("constructor");}
for(var i=0;(_7=_4l[i]);i++){if(_0g[_7]!=_0o[_7]){_1u.call(this,_7,_0g[_7]);}}
for(var _7 in _0g){if(!_0o[_7]){_1u.call(this,_7,_0g[_7]);}}}
return this;},base:function(){}};HClass.extend=function(_0m,_3b){var _1u=HClass.prototype.extend;if(!_0m){_0m={};}
HClass._38=true;var _0o=new this;_1u.call(_0o,_0m);var _0S=_0o.constructor;_0o.constructor=this;delete HClass._38;var _0I=function(){if(!HClass._38){_0S.apply(this,arguments);}
this.constructor=_0I;};_0I.prototype=_0o;_0I.extend=this.extend;_0I.implement=this.implement;_0I.toString=function(){return String(_0S);};_1u.call(_0I,_3b);var _33=_0S?_0I:_0o;if(_33.init instanceof Function){_33.init();}
return _33;};HClass.implement=function(_1x){if(_1x instanceof Function){_1x=_1x.prototype;}
this.prototype.extend(_1x);};var Base=HClass;if([].indexOf===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_4X){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_4X){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_3l=[];for(i=0;i<l;i++){_3l.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _3l.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_l,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _r=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_r=_r.extend(_2);this.options=new _r();this.request(_l);},request:function(_l){this.url=_l;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _m=this;this.transport.onreadystatechange=function(){_m.onStateChange();};this.setRequestHeaders();var _4Z=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_4Z);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1C=this.transport.readyState;if(_1C>1){this.respondToReadyState(_1C);}},respondToReadyState:function(_1C){if(_1C==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_1C==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});ELEMTickerInterval=10;BROWSER_TYPE={ie:false,ie6:false,ie7:false,opera:false,safari:false,firefox:false,firefox2:false};ELEM={_0S:function(){var _0=ELEM;_0._5i=false;_0._6L=[];_0._5f=null;_0._6M=false;_0._initDone=false;_0._77=0;_0._setStyleCount=0;_0._setStyleDiffCount=0;_0._6V=0;_0._getStyleMissCount=0;_0._flushLoopCount=0;_0._flushLoopFlushedCount=0;_0._flushStylCount=0;_0._flushTime=0;_0._flushCounter=0;_0._3L=500;_0._timer=null;_0._10=ELEMTickerInterval;_0._flushing=false;_0._needFlush=false;_0._4s=1;_0._F=[];if(_0._5i){_0._G={_6k:[]};}else{_0._freeElemIds=[];}
_0._4w={};_0._0L={};_0._0a={};_0._0q={};_0._3B=[];_0._2H={};_0._blockElems=",ADDRESS,BLOCKQUOTE,CENTER,DIR,DIV,DL,FIELDSET,FORM,H1,H2,H3,H4,H5,H6,HR,ISINDEX,MENU,NOFRAMES,NOSCRIPT,OL,P,PRE,TABLE,UL,";},_6P:function(_3x,_u){if(!ELEM._5i){return;}
var _0=ELEM,i=0,_4K=[],_G=_0._3Q(_u),_1L=_G._1L;for(;i!=_3x;i++){_4K.push(_0.make(_1L,_u));}
for(i=0;i!=_3x;i++){_0.del(_4K[i]);}},_4T:function(_6){var _4,_0,_F;_0=ELEM;_F=_0._F;_F.push(_6);_4=_F.length-1;return _4;},_6Z:function(_4){var _0=ELEM;_0._0L[_4]=[];_0._4w[_4]={};_0._0a[_4]=[];_0._0q[_4]={};_0._2H[_4]=false;},bindId:function(_5e){var _0=ELEM,_6=document.getElementById(_5e),_9=_0._4T(_6);_0._6Z(_9);return _9;},bind:function(_6){var _4,_0=ELEM;_4=_0._4T(_6);_0._6Z(_4);return _4;},_7d:function(_4,_6){var _0=ELEM;_0._F[_4]=_6;},get:function(_4){return ELEM._F[_4];},setHTML:function(_4,_1w){var _0=ELEM;_0._F[_4].innerHTML=_1w;},_3Q:function(_u){if(!ELEM._5i){return;}
var _0=ELEM,_G=_0._G;if(!_G[_u]){_G._6k.push(_u);_G[_u]=[];_G[_u]._1T=1;_G[_u]._1l=0;_G[_u]._1L=_0.make(_0._1L,'div');}
return _G[_u]._1L;},del:function(_4){var _0=ELEM,_6=_0._F[_4];_0.setCSS(_4,'display:none;');if(_0._5i){var _u=_6.tagName,_1L=_0._3Q(_u),_G=_0._G[_u];_0.append(_4,_1L);}
var _3C=_0._3B.indexOf(_4);if(_3C!=-1){_0._3B.splice(_3C,1);}
try{_6.innerHTML='';}catch(e){}
_0.delAttr(_4,'id');_0.delAttr(_4,'ctrl');_0._6Z(_4);if(_0._5i){_G._1T++;_G.push(_4);}else{_0._freeElemIds.push(_4);var _5P=_6.parentNode;_5P.removeChild(_6);}},append:function(_65,_1J){var _0g,_3e,_0;_0=ELEM;_0g=_0._F[_65];_3e=_0._F[_1J];_3e.appendChild(_0g);},setCSS:function(_4,_6J){ELEM._F[_4].style.cssText=_6J;},getCSS:function(_4){return ELEM._F[_4].style.cssText;},getVisibleSize:function(_4){var _0,_6,w,h,_f,_2h,_0=ELEM,_6=_0._F[_4],w=_6.offsetWidth,h=_6.offsetHeight,_f=_6.parentNode;while(_f&&_f.nodeName.toLowerCase()!='body'){if(!_0._22){_2h=document.defaultView.getComputedStyle(_f,null).getPropertyValue('overflow');}
else{_2h=_f.currentStyle.getAttribute('overflow');}
_2h=_2h!='visible';if(w>_f.clientWidth&&_2h){w=_f.clientWidth-_6.offsetLeft;}
if(h>_f.clientHeight&&_2h){h=_f.clientHeight-_6.offsetTop;}
_6=_6.parentNode;_f=_6.parentNode;}
return[w,h];},getSize:function(_4){var _0,_6,w,h,_f,_2h,_0=ELEM,_6=_0._F[_4],w=_6.offsetWidth,h=_6.offsetHeight;return[w,h];},getScrollSize:function(_4){var _0,_6,w,h,_f,_2h,_0=ELEM,_6=_0._F[_4],w=_6.scrollWidth,h=_6.scrollHeight;return[w,h];},getVisiblePosition:function(_4){var x,y,_6,_0,_0=ELEM,x=0,y=0,_6=_0._F[_4];while(_6!==document){x+=_6.offsetLeft;y+=_6.offsetTop;x-=_6.scrollLeft;y-=_6.scrollTop;_6=_6.parentNode;if(!_6){break;}}
return[x,y];},getOpacity:function(_4){var _0,_X,_3f,_1Z;_0=ELEM;_1Z=_0.getStyle;if(_X=_1Z(_4,'-khtml-opacity')){return parseFloat(_X);}
if(_X=_1Z(_4,'-moz-opacity')){return parseFloat(_X);}
_3f=_1Z(_4,'opacity',true);if(_X=_3f||(_3f==0)){return parseFloat(_X);}
if(_X=(_0._F[_4].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_X[1]){return parseFloat(_X[1])/100;}}
return 1.0;},setOpacity:function(_4,_6A){var _0=ELEM;if(_6A==1&&_0._22){_0._F[_4].style.setAttribute('filter',_0.getStyle(_4,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_6A<0.00001){_6A=0;}
if(_0._22){_0._F[_4].style.setAttribute('filter',_0.getStyle(_4,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_6A*100+')');}else{_0._F[_4].style.setProperty('opacity',_6A,'');}}},getIntStyle:function(_4,_e){var _6A=ELEM.getStyle(_4,_e);return parseInt(_6A,10);},setBoxCoords:function(_4,_01){ELEM.setStyle(_4,'left',_01[0]+'px');ELEM.setStyle(_4,'top',_01[1]+'px');ELEM.setStyle(_4,'width',_01[2]+'px');ELEM.setStyle(_4,'height',_01[3]+'px');},getExtraWidth:function(_4){var _0n=ELEM.getIntStyle;return _0n(_4,'padding-left')+_0n(_4,'padding-right')+_0n(_4,'border-left-width')+_0n(_4,'border-right-width');},getExtraHeight:function(_4){var _0n=ELEM.getIntStyle;return _0n(_4,'padding-top')+_0n(_4,'padding-bottom')+_0n(_4,'border-top-width')+_0n(_4,'border-bottom-width');},setFPS:function(_0l){ELEM._10=1000/_0l;if(ELEM._10<ELEMTickerInterval){ELEM._10=ELEMTickerInterval;}},setSlowness:function(_4s){ELEM._4s=_4s;},setIdleDelay:function(_3L){ELEM._3L=_3L;},_6X:false,flushLoop:function(_03){var _0=ELEM;_0._flushLoopCount++;if(_0._1y&&(_0._flushLoopCount%5==0)&&_0._6X){iefix._00();_0._6X=false;}
clearTimeout(_0._timer);if(_0._flushing){_03*=2;_0._timer=setTimeout('ELEM.flushLoop('+_03+');',_03);return;}else{if(!_0._needFlush){if(_0._1y&&_0._6X){iefix._00();_0._6X=false;}
_0._timer=setTimeout('ELEM.flushLoop('+_03+');',_0._3L);return;}
_03=parseInt(_0._4s*(_0._flushTime/_0._flushCounter),ELEMTickerInterval);if(_03<_0._10||!_03){_03=_0._10;}
_0._flushing=true;_0._timer=setTimeout('ELEM.flushLoop('+_03+');',_03);}
_0._flushTime-=new Date().getTime();var _2X,_1p,i,_0L;_3B=_0._3B;_2X=_3B.length;_1p=_3B.splice(0,_2X);var _5n=new Date().getTime();for(i=0;i<_2X;i++){_0._flushLoopFlushed++;var _4=_1p.pop();_0._2H[_4]=false;_0._5o(_4);_0._6Q(_4);}
_0._flushCounter++;_0._flushTime+=new Date().getTime();if(_0._3B.length==0&&_0._needFlush){_0._needFlush=false;}
_0._flushing=false;},_6Q:function(_4){var _0=ELEM,_0a=_0._0a[_4],_0q=_0._0q[_4],_6=_0._F[_4],_e,_0M,i,_3K=_0a.length,_1p=_0a.splice(0,_3K);for(i=0;i!=_3K;i++){_e=_1p.pop();_0M=_0q[_e];_6.setAttribute(_e,_0M);}},getAttr:function(_4,_e,_0r){var _0=ELEM,_1S=_0._0q[_4][_e],_0M;if(_1S!==undefined&&!_0r){return _1S;}
var _6=_0._F[_4];if(_6.getAttribute(_e)==null){_6[_e]='';}
_0M=_6.getAttribute(_e);_0._0q[_4][_e]=_0M;return _0M;},setAttr:function(_4,_e,_6A,_0r){var _1q,_0=ELEM,_0a=_0._0a[_4],_0q=_0._0q[_4];_1q=_6A!=_0.getAttr(_4,_e);if(_1q){_0q[_e]=_6A;if(_0r){_0._F[_4].setAttribute(_e,_6A);}
else{if(_0a.indexOf(_e)==-1){_0a.push(_e);}
if(!_0._2H[_4]){_0._3B.push(_4);_0._2H[_4]=true;_0._6G();}}}},delAttr:function(_4,_e){var _1q,_0=ELEM,_0a=_0._0a[_4],_0q=_0._0q[_4];delete _0q[_e];_0._F[_4].removeAttribute(_e);if(_0a.indexOf(_e)!=-1){_0a.splice(_0a.indexOf(_e,1));}
if(_0._2H[_4]){_0._3B.splice(_0._3B.indexOf(_4,1));_0._2H[_4]=false;_0._6G();}},hasClassName:function(_9,_0Q){var _5=ELEM.get(_9);if(!_5)return;var _3E=false;var _0R=_5.className.split(' ');for(var i=0;i<_0R.length;i++){if(_0R[i]==_0Q){_3E=true;}}
return _3E;},addClassName:function(_9,_0Q){var _5=ELEM.get(_9);if(!_5)return;ELEM.removeClassName(_9,_0Q);_5.className+=' '+_0Q;},removeClassName:function(_9,_0Q){var _5=ELEM.get(_9);if(!_5)return;var _32='';var _0R=_5.className.split(' ');for(var i=0;i<_0R.length;i++){if(_0R[i]!=_0Q){if(i>0)_32+=' ';_32+=_0R[i];}}
_5.className=_32;},_6G:function(){var _0=ELEM;if(!_0._needFlush){_0._needFlush=true;if(!_0._flushing){clearTimeout(_0._timer);_0._timer=setTimeout('ELEM.flushLoop('+_0._10+');',_0._10);}}},printStats:function(){var _0=ELEM,i=0,_u,_6j,_1T,_1l,_2q=0;if(_0._5i){console.log('Recycler efficiency:');_G=_0._G;for(;i!=_G._6k.length;i++){_u=_G._6k[i];console.log(' tagName: '+_u);_6j=_G[_u].length;console.log('   length  : '+_6j);_1T=_G[_u]._1T;console.log('   countIn : '+_1T);_1l=_G[_u]._1l;_2q+=_1l;console.log('   countOut: '+_1l);console.log('--------------------------------');}}
console.log('================================');console.log('Flushing efficiency:');console.log('  total real time spent: '+_0._flushTime+'ms');console.log('  total times called:    '+_0._flushLoopCount);console.log('  total times flushed:   '+_0._flushCounter);console.log('  total items flushed:   '+_0._flushLoopFlushedCount);console.log('  total real style sets: '+_0._flushStylCount);console.log('================================');console.log('setStyle efficiency:');console.log('  total times called:    '+_0._setStyleCount);console.log('  total times non-cache: '+_0._setStyleDiffCount);console.log('================================');console.log('getStyle efficiency:');console.log('  total times called:    '+_0._6V);console.log('  total times non-cache: '+_0._getStyleMissCount);console.log('================================');console.log('Summary:');if(_0._5i){console.log('  recycler saved '+(_2q)+' of '+_0._77+' ('+Math.round(_2q/_0._77*100)+'%) document.createElement calls');}
console.log('  style buffer saved '+(_0._setStyleDiffCount-_0._flushStylCount)+' of '+_0._setStyleDiffCount+' ('+Math.round(((_0._setStyleDiffCount-_0._flushStylCount)/_0._setStyleDiffCount)*100)+'%) non-cached DOM style sets');console.log('  style cache saved '+(_0._setStyleCount-_0._setStyleDiffCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._setStyleDiffCount)/_0._setStyleCount)*100)+'%) DOM style sets');console.log('  style cache saved '+(_0._6V-_0._getStyleMissCount)+' of '+_0._6V+' ('+Math.round(((_0._6V-_0._getStyleMissCount)/_0._6V)*100)+'%) DOM style gets');console.log('  style buffer and cache saved '+(_0._setStyleCount-_0._flushStylCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._flushStylCount)/_0._setStyleCount)*100)+'%) total DOM style sets');},setStyle:function(_4,_e,_6A,_0r){var _0=ELEM,_v=_0._4w[_4],_3D=_0._F,_1q,_0L;_0._setStyleCount++;_1q=_6A!==_v[_e];if(_1q){_0._setStyleDiffCount++;_v[_e]=_6A;if(_0r){if(_e=='opacity'){_0.setOpacity(_4,_6A);}
else{_0._22?(_3D[_4].style.setAttribute(_e.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_v[_e])):(_3D[_4].style.setProperty(_e,_v[_e],''));}
if(_0._1y){if(iefix._2l.indexOf(_e)!=-1){_0._6X=true;}}}else{_2H=_0._2H;_0L=_0._0L[_4];if(_0L.indexOf(_e)==-1){_0L.push(_e);}
if(!_2H[_4]){_0._3B.push(_4);_2H[_4]=true;_0._6G();}}}},make:function(_1J,_u){if(_1J===undefined){_1J=0;}
if(_u===undefined){_u='DIV';}else{_u=_u.toUpperCase();}
var _0=ELEM,_6,_4;_0._77++;if(_0._5i){if(_0._G[_u]){if(_0._G[_u].length!=0){_4=_0._G[_u].pop();_0._G[_u]._1l++;_6=_0._F[_4];if(_0._blockElems.indexOf(','+_u+',')!=-1){_0.setCSS(_4,'display:block;');}else{_0.setCSS(_4,'display:inline;');}
_0.append(_4,_1J);return _4;}}}
_6=document.createElement(_u);_0._F[_1J].appendChild(_6);_4=_0._4T(_6);_0._6Z(_4);return _4;},windowSize:function(){var _0j,_5s;_0j=(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;_5s=(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;return[_0j,_5s];},_3O:function(){var _0=ELEM,_0F,_2y;var _2N=["ELEM.getStyle=function(_4,_e,_0r){","var _0=ELEM,_v=_0._4w[_4],_1E;_0._6V++;","if((_v[_e]===undefined)||_0r){","if(!_0r){_0._getStyleMissCount++;}","if((_e=='opacity')&&_0r){_1E=_0.getOpacity(_4);}","else{","_1E=document.defaultView.getComputedStyle(_0._F[_4],null).getPropertyValue(_e);","_51=_e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){","return $3.toUpperCase()+$4});","_1E=_0._F[_4].currentStyle[_51];","}_v[_e]=_1E;","}return _v[_e];};"];if(_0._22){_2N.splice(6,1);}else{_2N.splice(7,3);}
eval(_2N.join(''));var _2J=["ELEM._5o=function(_4){","var _0=ELEM,_0L=_0._0L[_4],_v=_0._4w[_4],_6=_0._F[_4],_1s,_40,_3s,_e,_1p,_1E;","if(!_6){return;}","_1s=_6.style;","_40=_0L.length;","_1p=_0L.splice(0,_40);","for(_3s=0;_3s!=_40;_3s++){","_e=_1p.pop();_0._flushStylCount++;","if(_e=='opacity'){_1E=_0.getOpacity(_4,_v[_e]);}else{","if(_0._1y){if(iefix._2l.indexOf(_e)!=-1){_0._6X=true;}}try{_1s.setAttribute(_e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_v[_e]);}catch(e){}}}};","_1s.setProperty(_e,_v[_e],'');}}};"];if(_0._22){_2J.pop();}else{_2J.splice(9,1);}
eval(_2J.join(''));_0.bind(document.body);if(_0._5i){_0._1L=_0.make(0,'div');_0.setCSS(_0._1L,"display:none;visibility:hidden;");_0.setAttr(_0._1L,'id','trashcan_'+_0._1L);}
_0._timer=setTimeout('ELEM.flushLoop('+_0._10+')',_0._10);if(!_0._6L){return;}
while(_0._6L.length!=0){_0F=_0._6L.shift();if(typeof _0F=='string'){_2y=eval(_0F);if(typeof _2y=='string'){_0._6L.push(_2y);}}}
_0._initDone=true;},_6v:function(){_0=ELEM;_0._22=(document.all&&navigator.userAgent.indexOf("Opera")==-1)?true:false;_0._1y=(_0._22&&navigator.userAgent.indexOf("MSIE 6")!=-1)?true:false;_0._72=(_0._22&&navigator.userAgent.indexOf("MSIE 7")!=-1)?true:false;_0._74=(navigator.userAgent.indexOf("KHTML")!=-1)?true:false;_0._is_ff=(navigator.userAgent.indexOf("Firefox")!=-1)?true:false;_0._71=(navigator.userAgent.indexOf("Firefox/3.")!=-1)?true:false;_0._73=(navigator.userAgent.indexOf("Opera")!=-1)?true:false;BROWSER_TYPE={opera:_0._73,safari:_0._74,firefox:_0._is_ff,ie:_0._22,ie6:_0._1y,ie7:_0._72,firefox3:_0._71};_0._5h();},_5g:function(_0F){var _0=ELEM;if(typeof _0F=='string'){if(_0._initDone==true){eval(_0F);}else{_0._6L.push(_0F);}}},_5h:function(){var _75=false;var _0=ELEM;if(_0._22){var _3M="javascript:void(0)";if(location.protocol=="https:"){_3M="src=//0";}
document.write("<scr"+"ipt id=_4Q defer src="+_3M+"><\/scr"+"ipt>");var _5A=document.getElementById("_4Q");_5A.onreadystatechange=function(){if(this.readyState=="complete"){ELEM._6M=true;ELEM._3O();delete ELEM._6L;clearTimeout(ELEM._5f);delete ELEM._5f;}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(document.readyState))){_0._6M=true;}
else if(document.body){_0._6M=true;}
if(!_0._6M){_0._5f=setTimeout('ELEM._5h()',ELEMTickerInterval*10);}else{_0._3O();delete _0._6L;clearTimeout(_0._5f);delete _0._5f;}}};ELEM._0S();LOAD=ELEM._5g;ELEM._6v();Event={element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}
else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(ELEM._22||ELEM._74){return(e.button==1);}
else{return(e.button==0);}},observers:false,_5I:function(_6,_7,_1v,_1M){if(!Event.observers){Event.observers=[];}
if(_6.addEventListener){this.observers.push([_6,_7,_1v,_1M]);_6.addEventListener(_7,_1v,_1M);}
else if(_6.attachEvent){this.observers.push([_6,_7,_1v,_1M]);_6.attachEvent("on"+_7,_1v);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_6,_7,_1v,_1M){_1M=_1M||false;Event._5I(_6,_7,_1v,_1M);},stopObserving:function(_6,_7,_1v,_1M){_1M=_1M||false;if(_6.removeEventListener){_6.removeEventListener(_7,_1v,_1M);}
else if(detachEvent){_6.detachEvent("on"+_7,_1v);}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_6&&eo[1]==_7&&eo[2]==_1v&&eo[3]==_1M){Event.observers[i]=null;Event.observers.splice(i,1);}
else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34};if(ELEM._22){Event.observe(window,"unload",Event.unloadCache,false);}
_3y={mouseMove:false,mouseDown:false,click:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,isDragged:false,textEnter:false};EVENT={status:[false,false,0,0,[],false,false,false],button1:0,button2:1,crsrX:2,crsrY:3,keysDown:4,altKeyDown:5,ctrlKeyDown:6,shiftKeyDown:7,start:function(){var _2O,_2I,i,_0=EVENT;if(ELEM._22){_2O=document;}
else{_2O=window;}
_2I=[['mousemove',EVENT.mouseMove],['mouseup',EVENT.mouseUp],['mousedown',EVENT.mouseDown],['click',EVENT.click],['keyup',EVENT.keyUp],['keydown',EVENT.keyDown],['keypress',EVENT.keyPress],['contextmenu',EVENT.contextMenu],['resize',EVENT.resize],['mousewheel',EVENT.mouseWheel]];for(i=0;i!=_2I.length;i++){Event.observe(_2O,_2I[i][0],_2I[i][1]);}
if(window.addEventListener){window.addEventListener('DOMMouseScroll',EVENT.mouseWheel,false);}
_0.listeners=[];_0.focused=[];_0.resizeListeners=[];_0.coordListeners=[];_0.focusOptions={};_0.dragItems=[];_0.hovered=[];_0.hoverInterval=50;_0.hoverTimer=new Date().getTime();_0.topmostDroppable=null;_0.textEnterCtrls=[];_0._2z=[];_0._coordCacheFlag=true;_0._lastCoordFlushTimeout=null;_0.activeControl=null;_0._lastKeyDown=null;},coordCacheFlush:function(_9){if(_9){EVENT._2z[_9]=null;}
else{EVENT._2z=[];}},reg:function(_c,_0u){var _9,_6,_0=EVENT,_5W;_9=_c.elemId;_6=ELEM.get(_9);if(ELEM._22){_6.setAttribute('ctrl',_c);}
else{_6.ctrl=_c;}
_0.listeners[_9]=true;_0.focused[_9]=false;for(var _5W in _3y){if(_0u[_5W]===undefined){_0u[_5W]=_3y[_5W];}}
_0.focusOptions[_9]=_0u;var _2A=_0.coordListeners.indexOf(_9);if(_0u.mouseMove){if(_2A==-1){_0.coordListeners.push(_9);}}
else if(_2A!=-1){_0.coordListeners.splice(_2A,1);}
if(_0u.textEnter){if(_0.textEnterCtrls.indexOf(_c.viewId)==-1){_0.textEnterCtrls.push(_c.viewId);}}
if(_0u.resize){if(_0.resizeListeners.indexOf(_c.viewId)==-1){_0.resizeListeners.push(_c.viewId);}}
Event.observe(_6,'mouseover',_0._47);},unreg:function(_c){var _0=EVENT,_9,_6;if(_c===this.activeControl){_0.changeActiveControl(null);}
_9=_c.elemId;_6=ELEM.get(_9);this.listeners[_9]=false;this.focused[_9]=false;this._2z[_9]=null;var _4D=_0.textEnterCtrls.indexOf(_c.viewId);if(_4D!=-1){_0.textEnterCtrls.splice(_4D,1);}
var _4n=_0.resizeListeners.indexOf(_c.viewId);if(_4n!=-1){_0.resizeListeners.splice(_4n,1);}
Event.stopObserving(_6,'mouseover',_0._47);},resize:function(e){var i=0,_0=EVENT,_1X,_c;for(;i<_0.resizeListeners.length;i++){_1X=_0.resizeListeners[i];_c=HSystem.views[_1X];if(_c.onResize){_c.onResize();}}},_47:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.focus(_0);Event.stop(e);},_46:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.blur(_0);Event.stop(e);},focus:function(_c){var _0=EVENT,_9,_6;_9=_c.elemId;_6=ELEM.get(_9);if(_0.focused[_9]==false&&_0.focusOptions[_9].isDragged==false){Event.stopObserving(_6,'mouseover',_0._47);Event.observe(_6,'mouseout',_0._46);_0.focused[_9]=true;if(_c['focus']){_c.focus();}}},blur:function(_c){var _0=EVENT,_9,_6;_9=_c.elemId;_6=ELEM.get(_9);if(_0.focused[_9]==true&&_0.focusOptions[_9].isDragged==false){Event.stopObserving(_6,'mouseout',_0._46);Event.observe(_6,'mouseover',_0._47);_0.focused[_9]=false;if(_c['blur']){_c.blur();}}},mouseMove:function(e){var _0=EVENT,x,y,_0U;x=Event.pointerX(e);y=Event.pointerY(e);_0.status[_0.crsrX]=x;_0.status[_0.crsrY]=y;_0U=_0.flushMouseMove(x,y);_0._78(e);if(_0U){Event.stop(e);}},flushMouseMove:function(x,y){var _0=EVENT,x,y,_0U,i,j,_9,_c;clearTimeout(_0._lastCoordFlushTimeout);_0U=false;for(i=0;i!=_0.dragItems.length;i++){_9=_0.dragItems[i];_0.focusOptions[_9].ctrl.doDrag(x,y);_0.coordCacheFlush(_9);_0U=true;}
if(new Date().getTime()>_0.hoverTimer+_0.hoverInterval){for(i=0;i!=_0.coordListeners.length;i++){_9=_0.coordListeners[i];_c=_0.focusOptions[_9].ctrl;_c.mouseMove(x,y);}
_0._7x();var _2o;for(i=0;i!=_0.dragItems.length;i++){_2o=_0.topmostDroppable;_0.topmostDroppable=null;_9=_0.dragItems[i];_c=_0.focusOptions[_9].ctrl;var _20,_1r;for(j=0;j!=_0.hovered.length;j++){_20=_0.hovered[j];if(_20!=_9&&_0.focusOptions[_20].ctrl){_1r=_0.focusOptions[_20].ctrl;if(!_0.topmostDroppable||_1r.zIndex()>_0.topmostDroppable.zIndex()||_1r.supr===_0.topmostDroppable){if(_0.focusOptions[_1r.elemId].droppable){_0.topmostDroppable=_1r;}}}}
if(_2o!=_0.topmostDroppable){if(_2o){_2o.onHoverEnd(_c);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverStart(_c);}}}
_0.hoverTimer=new Date().getTime();}
else{_0._lastCoordFlushTimeout=setTimeout('EVENT.flushMouseMove('+x+','+y+');',_0.hoverInterval);}
return _0U;},_7x:function(){var _0=EVENT,x,y,i,_c,_6,_34,_4r,_01;_0.hovered=[];x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.listeners.length;i++){if(!_0.listeners[i]||!_0.focusOptions[i].ctrl){continue;}
_c=_0.focusOptions[i].ctrl;_6=ELEM.get(i);if(!_0._coordCacheFlag||!_0._2z[i]){_34=ELEM.getVisiblePosition(_c.elemId);_4r=ELEM.getVisibleSize(_c.elemId);_0._2z[i]=[_34[0],_34[1],_4r[0],_4r[1]];}
_01=_0._2z[i];if(x>=_01[0]&&x<=_01[0]+_01[2]&&y>=_01[1]&&y<=_01[1]+_01[3]){_0.hovered.push(i);}}},mouseDown:function(e,_S){var _0=EVENT,_2F,x,y,i,_A,_0z,_2a;_0._78(e);_2F=false;if(_S===undefined){_S=Event.isLeftClick(e);}
if(_S){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_A=null;_0z=[];_2a=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_A=_0.focusOptions[i].ctrl;}
if((_0.focusOptions[i].draggable==true)&&_0.dragItems.indexOf(i)==-1){_0z.push(i);}
else if(_0.focusOptions[i].mouseDown==true){_2a.push(i);}}}
if(_A){_0.changeActiveControl(_A);}
for(i=0;i!=_0z.length;i++){_0.dragItems.push(_0z[i]);_0.focusOptions[_0z[i]].ctrl.startDrag(x,y);_2F=true;}
var _1H=_2a.length;for(i=0;i!=_2a.length;i++){if(_0.focusOptions[_2a[i]].ctrl.mouseDown(x,y,_S)){_1H--;}}
if(_2F){document.body.focus();_0._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if((_1H==0)&&(_0.hovered.length!=0)&&(_A&&(_A.textElemId===false))){Event.stop(e);}
return true;},click:function(e,_S){var _0=EVENT,x,y,i,_A,_2x;_0._78(e);if(_S===undefined){_S=Event.isLeftClick(e);}
if(_S){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_A=null;_2x=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_A=_0.focusOptions[i].ctrl;}
if(_0.focusOptions[i].click==true){_2x.push(i);}}}
if(_A){_0.changeActiveControl(_A);}
var _1H=_2x.length;for(i=0;i!=_2x.length;i++){if(_0.focusOptions[_2x[i]].ctrl.click(x,y,_S)){_1H--;}}
if((_1H==0)&&(_0.hovered.length!=0)&&(_A&&(_A.textElemId===false))){Event.stop(e);}
return true;},changeActiveControl:function(_c){var _0=EVENT,_15;_15=_0.activeControl;if(_c!=_15){if(_15){_15.active=false;_15._5G(_c);}
_0.activeControl=null;if(_c){_c.active=true;_0.activeControl=_c;_c._5r(_15);}}},mouseUp:function(e){var _0=EVENT,_2E,x,y,_9,_c,i;_0._78(e);_2E=false;_S=Event.isLeftClick(e);_0.status[_0.button1]=false;_0.status[_0.button2]=false;x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.dragItems.length;i++){_9=_0.dragItems[i];_c=_0.focusOptions[_9].ctrl;_c.endDrag(x,y);_2E=true;_0._7x();if(_0.hovered.indexOf(_9)==-1){_0.blur(_c);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverEnd(_c);_0.topmostDroppable.onDrop(_c);_0.topmostDroppable=null;}}
_0.dragItems=[];if(_2E){document.onselectstart=_0._storedOnSelectStart;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseUp==true){_0.focusOptions[i].ctrl.mouseUp(x,y,_S);}}}
return true;},keyDown:function(e){var _0=EVENT,_0h;_0._78(e);_0h=e.keyCode;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);if(_0._lastKeyDown!=_0h){_0.activeControl.keyDown(_0h);}}
if(_0.status[_0.keysDown].indexOf(_0h)==-1){_0.status[_0.keysDown].push(_0h);}
_0._lastKeyDown=_0h;},keyUp:function(e){var _0=EVENT,_0h,_keycodeindex;_0._78(e);_0h=e.keyCode;_0._lastKeyDown=null;for(var i=0;i!=_0.textEnterCtrls.length;i++){var _1X=_0.textEnterCtrls[i],_c=HSystem.views[_1X];if(_c.textEnter){_c.textEnter();}}
if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyUp==true){_0.activeControl.keyUp(_0h);}
_3T=_0.status[_0.keysDown].indexOf(_0h);if(_3T!=-1){_0.status[_0.keysDown].splice(_3T,1);}},keyPress:function(e){var _0=EVENT;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _0=EVENT,_M,i;_M=0;if(!e){e=window.event;}
if(e.wheelDelta){_M=e.wheelDelta/120;if(window.opera){_M=-_M;}}
else if(e.detail){_M=-e.detail/3;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseWheel==true){Event.stop(e);_0.focusOptions[i].ctrl.mouseWheel(_M);}}}},contextMenu:function(e){EVENT.mouseDown(e,false);Event.stop(e);},_78:function(e){var _0=EVENT;_0.status[_0.altKeyDown]=e.altKey;_0.status[_0.ctrlKeyDown]=e.ctrlKey;_0.status[_0.shiftKeyDown]=e.shiftKey;}};LOAD('EVENT.start();');SHA={_3J:0,hexCase:function(){return SHA._3J;},setHexCase:function(_52){SHA._3J=_52;},_3n:"=",base64Pad:function(){return SHA._3n;},setBase64Pad:function(_5O){SHA._3n=_5O;},_3r:8,chrsz:function(){return SHA._3r;},setChrsz:function(_4Y){SHA._3r=_4Y;},hexSHA1:function(_0y){var _0=SHA;return _0._6E(_0._6I(_0._7s(_0y),_0y.length*_0._3r));},b64SHA1:function(_0y){var _0=SHA;return _0._6D(_0._6I(_0._7s(_0y),_0y.length*_0._3r));},strSHA1:function(_0y){var _0=SHA;return _0._6F(_0._6I(_0._7s(_0y),_0y.length*_0._3r));},hexHmacSHA1:function(_e,_0s){var _0=SHA;return _0._6E(_0._6H(_e,_0s));},b64HmacSHA1:function(_e,_0s){var _0=SHA;return _0._6D(_0._6H(_e,_0s));},strHmacSHA1:function(_e,_0s){var _0=SHA;return _0._6F(_0._6H(_e,_0s));},str2Base64:function(_B){var _0=SHA;return _0._6D(_0._7s(_B));},test:function(){return SHA.hexSHA1("abc")=="a9993e364706816aba3e25717850c26c9cd0d89d";},_6I:function(_7,_2W){var _0=SHA;_7[_2W>>5]|=0x80<<(24-_2W%32);_7[((_2W+64>>9)<<4)+15]=_2W;var _0j=new Array(80),_0D=1732584193,_L=-271733879,_Q=-1732584194,_R=271733878,_0W=-1009589776,i,_4c,_4d,_4e,_4f,_4g,j,_K;for(i=0;i<_7.length;i+=16){_4c=_0D;_4d=_L;_4e=_Q;_4f=_R;_4g=_0W;for(j=0;j<80;j++){if(j<16){_0j[j]=_7[i+j];}
else{_0j[j]=_0._7n(_0j[j-3]^_0j[j-8]^_0j[j-14]^_0j[j-16],1);}
_K=_0._7o(_0._7o(_0._7n(_0D,5),_0._7p(j,_L,_Q,_R)),_0._7o(_0._7o(_0W,_0j[j]),_0._7q(j)));_0W=_R;_R=_Q;_Q=_0._7n(_L,30);_L=_0D;_0D=_K;}
_0D=_0._7o(_0D,_4c);_L=_0._7o(_L,_4d);_Q=_0._7o(_Q,_4e);_R=_0._7o(_R,_4f);_0W=_0._7o(_0W,_4g);}
return[_0D,_L,_Q,_R,_0W];},_7p:function(_K,_L,_Q,_R){if(_K<20){return(_L&_Q)|((~_L)&_R);}
if(_K<40){return _L^_Q^_R;}
if(_K<60){return(_L&_Q)|(_L&_R)|(_Q&_R);}
return _L^_Q^_R;},_7q:function(_K){return(_K<20)?1518500249:(_K<40)?1859775393:(_K<60)?-1894007588:-899497514;},_6H:function(_e,_0s){var _0=SHA,_1g=_0._7s(_e),_3S=new Array(16),_4h=new Array(16),i,_3G;if(_1g.length>16){_1g=_0._6I(_1g,_e.length*_0._3r);}
for(i=0;i<16;i++){_3S[i]=_1g[i]^0x36363636;_4h[i]=_1g[i]^0x5C5C5C5C;}
_3G=_0._6I(_3S.concat(_0._7s(_0s)),512+_0s.length*_0._3r);return _0._6I(_4h.concat(_3G),512+160);},_7o:function(_7,_b){var _41=(_7&0xFFFF)+(_b&0xFFFF),_5H=(_7>>16)+(_b>>16)+(_41>>16);return(_5H<<16)|(_41&0xFFFF);},_7n:function(_2f,_3t){return(_2f<<_3t)|(_2f>>>(32-_3t));},_7s:function(_B){var _0=SHA,_1f=[],_2Z=(1<<_0._3r)-1,_6b=_B.length*_0._3r,i;for(i=0;i<_6b;i+=_0._3r){_1f[i>>5]|=(_B.charCodeAt(i/_0._3r)&_2Z)<<(32-_0._3r-i%32);}
return _1f;},_6F:function(_1f){var _0=SHA,_B="",_2Z=(1<<_0._3r)-1,i,_2u=_1f.length*32,_4P=32-_0._3r;for(i=0;i<_2u;i+=_0._3r){_B+=String.fromCharCode((_1f[i>>5]>>>(_4P-i%32))&_2Z);}
return _B;},_6E:function(_0k){var _0=SHA,_3I=_0._3J?"0123456789ABCDEF":"0123456789abcdef",_B="",i,_2t=_0k.length*4;for(i=0;i<_2t;i++){_B+=_3I.charAt((_0k[i>>2]>>((3-i%4)*8+4))&0xF)+
_3I.charAt((_0k[i>>2]>>((3-i%4)*8))&0xF);}
return _B;},_6D:function(_0k){var _0=SHA,_1a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",_B="",i,_2t=_0k.length*4,_4z,_4A,_6A,_4L,j,_2u=_0k.length*32;for(i=0;i<_2t;i+=3){_4z=(((_0k[i>>2]>>8*(3-i%4))&0xFF)<<16);_4A=(((_0k[i+1>>2]>>8*(3-(i+1)%4))&0xFF)<<8);_6h=((_0k[i+2>>2]>>8*(3-(i+2)%4))&0xFF);_4L=(_4z|_4A|_6h);for(j=0;j<4;j++){if(i*8+j*6>_2u){_B+=_0._3n;}
else{_B+=_1a.charAt((_4L>>6*(3-j))&0x3F);}}}
return _B;}};HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporter=Base.extend({constructor:null,start:function(_6q){var _0=HTransporter;_0.url_base=_6q;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_8){HTransporter.pollMode=_8;},failure:function(resp){var _5c=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_5c)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _5Z=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_5Z);}
catch(e){_0.err_msg='&err_msg='+e+" - "+e.description;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_6s=((_0.syncDelay>0)||(_0.syncDelay==0));if(_6s&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_19=_0.prevData;}
else{_19=HValueManager.toXML();_0.prevData=_19;}
if(""!=_19||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_19};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_4,_m){this.values[_4]=_m;},set:function(_4,_6A){this.values[_4].set(_6A);},s:function(_4,_6A){this.values[_4].s(_6A);},del:function(_4){var _4F=this.values[_4],_6r=_4F.views,_09=0,_4G=null;for(;_09<_6r.length;_09++){_4G=_6r[_09];_4G.valueObj=new HDummyValue(0,_4F.value);}
this.values[_4]=null;},changed:function(_1K){if(this.isGetting==false){if(this.tosync.indexOf(_1K.id)==-1){this.tosync.push(_1K.id);}
var _K=HTransporter;if(!_K.pollMode){clearTimeout(_K.req_timeout);_K.req_timeout=setTimeout('HTransporter.sync();',_K.syncDelay);}}},toXML:function(){var _4j='&HSyncData=';if(!this.isSending){this.isSending=true;var _6e=this.tosync.length;if(_6e==0){this.isSending=false;return'';}
var _4y=[],_0Y;for(_0Y=0;_0Y<_6e;_0Y++){var _1I=this.tosync.shift();var _6f=this.values[_1I];_4y.push(_6f.toXML(_0Y));}
var _6g=_4y.join('');_4j+='<hsyncvalues version="8118">'+_6g+'</hsyncvalues>';this.isSending=false;}
return _4j;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_4,_6A){this.id=_4;this.type='[HValue]';this.value=_6A;this.views=[];HValueManager.add(_4,this);},set:function(_6A){if(_6A!=this.value){this.value=_6A;HValueManager.changed(this);this.refresh();}},s:function(_6A){this.value=_6A;this.refresh();},get:function(){return this.value;},bind:function(_E){if(_E===undefined){throw("HValueBindError: _E is undefined!");}
this.views.push(_E);_E.setValueObj(this);},unbind:function(_E){for(var _09=0;_09<this.views.length;_09++){var _6n=this.views[_09];if(_6n===_E){this.views.splice(_09);return;}}},release:function(_E){return this.unbind(_E);},refresh:function(){for(var _09=0;_09<this.views.length;_09++){var _E=this.views[_09];if(_E.value!=this.value){if(!_E._valueIsBeingSet){_E._valueIsBeingSet=true;_E.setValue(this.value);_E._valueIsBeingSet=false;}}}},toXML:function(_0Y){var _1I=this.id.toString();var _Y=this.value;var _0p=(typeof _Y).slice(0,1);var _0A;if(_0p=='s'){_0A=_Y.toString();_0A=SHA.str2Base64(_0A);}
else if(_0p=='n'){if(Math.ceil(_Y)===Math.floor(_Y)===_Y){_0p='i';_0A=parseInt(_Y,10).toString();}
else{_0p='f';_0A=parseFloat(_Y).toString();}}
else if(_0p=='b'){if(_Y){_0A='1';}
else{_0A='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1I);console.log('  syncjstype:',_0p);console.log('  typeof:',(typeof _Y));console.log('  syncvalue:',_Y);}}
catch(e){alert('value error, syncid:'+_1I+' syncjstype:'+_0p+' typeof:'+(typeof _Y)+' syncvalue:'+_Y);}
return'';}
return'<'+_0p+' id="'+_1I+'">'+_0A+'</'+_0p+'>';}});JSLoader=Base.extend({constructor:function(_6p){this._1z=[];this.uri=_6p;this._3a=null;},_5L:function(_4o){eval(_4o.responseText);},load:function(_23,_5q){if((jsLoader._1z.indexOf(_23)!=-1)&&(_5q===undefined)){return;}
if(_5q){document.write('<script type="text/javascript" src="'+_23+'"><'+'/script>');}else{req_args={onSuccess:function(resp){jsLoader._5L(resp);},onFailure:function(resp){window.status="failed to load js: "+jsLoader._2B;},method:'get',asynchronous:false};var _l=this.uri+_23+'.js';this._3a=new Ajax.Request(_l,req_args);this._1z.push(_23);}}});LOAD("jsLoader = new JSLoader('/H/js/');");HValueMatrixComponentExtension={componentBehaviour:['view','control','matrix'],constructor:function(_1,_f,_2){this.base(_1,_f,_2);this.setValueMatrix();},setValueMatrix:function(){if(!this.parent.valueMatrix){this.parent.valueMatrix=new HValueMatrix();}
this.valueMatrixIndex=this.parent.valueMatrix.addControl(this);},click:function(){if(this.parent.valueMatrix instanceof HValueMatrix){this.parent.valueMatrix.setValue(this.valueMatrixIndex);}}};HValueMatrix=HClass.extend({constructor:function(){this.ctrls=[];this.value=-1;this.valueObj=new HDummyValue();},setValueObj:function(_4N){this.valueObj=_4N;this.setValue(_4N.value);},setValue:function(_p){if(_p!=this.value){if(this.value!=-1){this.ctrls[this.value].setValue(false);}
if(_p!=-1){this.valueObj.set(_p);this.value=_p;if(_p<this.ctrls.length){this.ctrls[_p].setValue(true);}}}},addControl:function(_c){this.ctrls.push(_c);var _49=this.ctrls.length-1;if(_c.value){this.setValue(_49);}
return _49;}});HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _0D=arguments;if(_0D.length===0){this._1j();}
else if(_0D.length==2){this._3w(_0D[0],_0D[1]);}
else if(_0D.length==1){this._1k(_0D[0]);}
else{throw"Invalid number of arguments.";}},_1j:function(){this.x=null;this.y=null;},_3w:function(x,y){this.x=x;this.y=y;},_1k:function(_d){this.x=_d.x;this.y=_d.y;},set:function(){var _0D=arguments;if(_0D.length===0){this._1j();}
else if(_0D.length==2){this._3w(_0D[0],_0D[1]);}
else if(_0D.length==1){this._1k(_0D[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_d){_0D=arguments;if((_0D.length==1)&&(_0D[0].type==this.type)){_d=_0D[0];return new HPoint((this.x+_d.x),(this.y+_d.y));}
else if(_0D.length==2){return new HPoint((this.x+_0D[0]),(this.y+_0D[1]));}else{return new HPoint(0,0);}},subtract:function(){_0D=arguments;if((_0D.length==1)&&(_0D[0].type==this.type)){_d=_0D[0];return new HPoint(this.x-_d.x,this.y-_d.y);}
else if(_0D.length==2){return new HPoint(this.x-_0D[0],this.y-_0D[1]);}else{return new HPoint(0,0);}},equals:function(_d){return(this.x==_d.x&&this.y==_d.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _0D=arguments;if(_0D.length===0){this._1j();}else if(_0D.length==4){this._3v(_0D[0],_0D[1],_0D[2],_0D[3]);}
else if(_0D.length==2){this._1k(_0D[0],_0D[1]);}
else if(_0D.length==1){this._3u(_0D[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1j:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_3v:function(_05,_0B,_1F,_1h){this.top=_0B;this.left=_05;this.bottom=_1h;this.right=_1F;},_1k:function(_3Y,_4p){this.top=_3Y.y;this.left=_3Y.x;this.bottom=_4p.y;this.right=_4p.x;},_3u:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _0D=arguments;if(_0D.length===0){this._1j();}else if(_0D.length==4){this._3v(_0D[0],_0D[1],_0D[2],_0D[3]);}
else if(_0D.length==2){this._1k(_0D[0],_0D[1]);}
else if(_0D.length==1){this._3u(_0D[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_05){this.left=_05;this.updateSecondaryValues();},setRight:function(_1F){this.right=_1F;this.updateSecondaryValues();},setTop:function(_0B){this.top=_0B;this.updateSecondaryValues();},setBottom:function(_1h){this.bottom=_1h;this.updateSecondaryValues();},setLeftTop:function(_d){this.left=_d.x;this.top=_d.y;this.updateSecondaryValues();},setLeftBottom:function(_d){this.left=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setRightTop:function(_d){this.right=_d.x;this.top=_d.y;this.updateSecondaryValues();},setRightBottom:function(_d){this.right=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setWidth:function(_q){this.right=this.left+_q;this.updateSecondaryValues();},setHeight:function(_H){this.bottom=this.top+_H;this.updateSecondaryValues();},setSize:function(){var _0D=arguments;if(_0D.length===2){_q=_0D[0];_H=_0D[1];}
else if(_0D.length===1){_q=_0D.x;_H=_0D.y;}
this.right=this.left+_q;this.bottom=this.top+_H;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_m){if(_m instanceof HPoint){return this._56(_m);}
else if(_m instanceof HRect){return this._57(_m);}
else{throw"Wrong argument type.";}},_56:function(_d){return(_d.x>=this.left&&_d.x<=this.right&&_d.y>=this.top&&_d.y<=this.bottom);},_57:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _0D=arguments;if(_0D.length===1){this._5D(_0D[0]);}else if(_0D.length==2){this._3R(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5D:function(_d){this._3R(_d.x,_d.y);},_3R:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _0D=arguments;if(_0D.length===1){this._5J(_0D[0]);}else if(_0D.length==2){this._4a(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5J:function(_d){this._4a(_d.x,_d.y);},_4a:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _0D=arguments;if(_0D.length===1){this._5K(_0D[0]);}else if(_0D.length==2){this._4b(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5K:function(_d){this._4b(_d.x,_d.y);},_4b:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_m){},unbind:function(_m){}});HDefaultApplicationInterval=20;HSystemTickerInterval=10;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _j=0;_j<this.apps.length;_j++){if(this.apps[_j]){if(!this.busyApps[_j]){if((this.ticks%this.appPriorities[_j])==0){this.appTimers[_j]=setTimeout('if (HSystem.apps['+_j+']) {HSystem.apps['+_j+']._4u();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._7u=setTimeout('HSystem.ticker();',HSystemTickerInterval);},addApp:function(_0P,_0f){if(this.freeAppIds.length>1024){var _j=this.freeAppIds.shift();this.apps[_j]=_0P;}else{this.apps.push(_0P);var _j=this.apps.length-1;}
_0P.parent=this;_0P.parents=[this];_0P.appId=_j;this.startApp(_j,_0f);return _j;},startApp:function(_j,_0f){if(_0f===undefined){_0f=this.defaultInterval;}
this.appPriorities[_j]=_0f;this.busyApps[_j]=false;},stopApp:function(_j){this.busyApps[_j]=true;},reniceApp:function(_j,_0f){this.appPriorities[_j]=_0f;},killApp:function(_j,_5p){if(!_5p){var _68=new Date().getTime();while(this.busyApps[_j]==true){if(new Date().getTime()>_68+this.maxAppRunTime){break;}}}
this.busyApps[_j]=true;this.apps[_j].destroyAllViews();delete this.apps[_j];this.apps[_j]=null;this.freeAppIds.push(_j);},views:[],_2K:[],addView:function(_h){var _2c;if(this._2K.length==0){_2c=this.views.length;this.views.push(_h);}
else{_2c=this._2K.pop();this.views[_2c]=_h;}
return _2c;},delView:function(_i){this.views[_i]=null;this._2K.push(_i);},activeWindowId:0,windowFocus:function(_h){var _4S=this.activeWindowId,_2n=this.views,_i=_h.viewId;if(_4S!=0){_2n[_4S].windowBlur();}
this.activeWindowId=_i;_h.bringToFront();_h.windowFocus();}});LOAD('HSystem.ticker();');HApplication=HClass.extend({componentBehaviour:['app'],constructor:function(_0f){this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_0f);},buildParents:function(_i){var _h=HSystem.views[_i];_h.parent=this;_h.parents=[];for(var _0J=0;_0J<this.parents.length;_0J++){_h.parents.push(this.parents[_0J]);}
_h.parents.push(this);},addView:function(_h){var _i=HSystem.addView(_h);this.views.push(_i);this.buildParents(_i);this.viewsZOrder.push(_i);return _i;},removeView:function(_i){HSystem.views[_i].remove();},destroyView:function(_i){HSystem.views[_i].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){var i,_i;for(i=0;i<this.views.length;i++){_i=this.views[i];HSystem.views[_i].die();}},_5R:function(){var i,_i;for(i=0;i<this.views.length;i++){_i=this.views[i];HSystem.views[i].onIdle();}},_4u:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._5R();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HNoComponentCSS=[];HThemeHasIE6GifsInsteadOfPng=[];HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2k={};this._1U={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_P){this.themePath=_P;},_5l:function(_l){console.log("ERROR: Template Not Found: '"+_l+"' ");},_5k:function(_l){console.log("ERROR: Template Failure: '"+_l+"' ");},_5j:function(_l){console.log("ERROR: Template Exception: '"+_l+"' ");},fetch:function(_l,_0G){var _1D;if(!_0G){var _0G='text/html; charset=UTF-8';}
var _3a=new Ajax.Request(_l,{method:'GET',onSuccess:function(_6z){_1D=_6z.responseText;},on404:function(){HThemeManager._5l(_l);},onFailure:function(){HThemeManager._5k(_l);},onException:function(){HThemeManager._5j(_l);},asynchronous:false,contentType:_0G});_3a.onStateChange();return _1D;},getThemeGfxPath:function(){var _g=this._1n[0],_n=this._1n[1],_K=this._1n[2],_y=this._1n[3],_0C=this._0C(_g,_n,_K,_y);return this._I(_0C,'gfx');},getCssFilePath:function(_0c){var _g=this._1n[0];if((HThemeHasIE6GifsInsteadOfPng.indexOf(_g)!=-1)&&ELEM._1y){return"url('"+this._I(this.getThemeGfxPath(),_0c.replace('.png','-ie6.gif'))+"')";}
else{return"url('"+this._I(this.getThemeGfxPath(),_0c)+"')";}},loadCSS:function(_l){var _0G='text/css';var _0H=this.fetch(_l,_0G);if(!_0H||_0H==""){return;}
_0H=this._3o(_0H);var _07,_4x,_3H;if(ELEM._22){_07=document.createStyleSheet();_07.cssText=_0H;}
else{_07=document.createElement("style");_07.type=_0G;_07.media="all";_3H=document.getElementsByTagName('head')[0];_3H.appendChild(_07);if(navigator.userAgent.indexOf('KHTML')!=-1){var _5b=document.createTextNode(_0H);_07.appendChild(_5b);}
else{_07.innerHTML=_0H;}}},_4U:function(_B){if(_B[_B.length-1]!='/'){_B+='/';}
return _B;},_I:function(_69,_6a){return this._4U(_69)+_6a;},_0C:function(_g,_n,_K,_y){var _P=_K;if(_K===null){_P=this.themePath;}
if(HThemeMode==0){if(_y){_P=this._I(_P,_y);}
if(_K===null){_P=this._I(_P,_n);_P=this._I(_P,'themes');}
_P=this._I(_P,_g);}
else if(HThemeMode==1){_P=this._I(_P,_g);}
return _P;},_1W:function(_g,_n,_K,_y){this._1n=[_g,_n,_K,_y];var _59=this._0C(_g,_n,_K,_y);var _5a=this._I('css',_n+'.css');var _1W=this._I(_59,_5a);return _1W;},_2Y:function(_g,_n,_K,_y){var _5x=this._0C(_g,_n,_K,_y);var _5y=this._I('html',_n+'.html');var _5z=this._I(_5x,_5y);return _5z;},loadMarkup:function(_g,_n,_K,_y){if(!this._2k[_g]){this._2k[_g]={};}
var _v=this._2k[_g][_n];if(null===_v||undefined===_v){var _2Y=this._2Y(_g,_n,_K,_y);_v=this.fetch(_2Y);if(null===_v||undefined===_v){_v="";}
this._2k[_g][_n]=_v;}
return _v;},getMarkup:function(_g,_n,_K,_y){if(!this._1U[_g]){var _53=this._1W(_g,'common',_K,null);this._1U[_g]={};this.loadCSS(_53);}
if(HNoComponentCSS.indexOf(_g)==-1){if(!this._1U[_g][_n]){var _54=this._1W(_g,_n,_K,_y);this._1U[_g][_n]=true;this.loadCSS(_54);}}
return this.loadMarkup(_g,_n,_K,_y);},_1i:function(_g,_n,_K,_y){var _0C=this._0C(_g,_n,_K,_y);var _l=this._I(_0C,'gfx');return _l;},_55:function(_g,_n,_K,_y,_0c){if((HThemeHasIE6GifsInsteadOfPng.indexOf(_g)!=-1)&&ELEM._1y){return this._I(this._1i(_g,_n,_K,_y),_0c.replace('.png','-ie6.gif'));}
return this._I(this._1i(_g,_n,_K,_y),_0c);},getThemeGfxFile:function(_0c){return this.getThemeGfxPath()+_0c;},setTheme:function(_4E){this.currentTheme=_4E;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_0N:new RegExp(/#\{([^\}]*)\}/),_3o:function(_1o){while(this._0N.test(_1o)){_1o=_1o.replace(this._0N,eval(RegExp.$1));}
return _1o;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _0w=this.markup;while(HMarkupView._3m.test(_0w)){_0w=_0w.replace(HMarkupView._3m,this.evalMarkupVariable(RegExp.$1,true));}
while(HMarkupView._0N.test(_0w)){_0w=_0w.replace(HMarkupView._0N,this.evalMarkupVariable(RegExp.$1));}
this.markup=_0w;},evalMarkupVariable:function(_6c,_70){try{var _ID=this.elemId.toString(),_WIDTH=this.rect.width,_HEIGHT=this.rect.height,_1D=eval(_6c);if(_70){return'';}
if(_1D===undefined){return'';}
else{return _1D;}}
catch(e){return'';}},toggleCSSClass:function(_0b,_1m,_4q){if(_0b){var _3F=ELEM.hasClassName(_0b,_1m);if(_4q){if(!_3F){ELEM.addClassName(_0b,_1m);}}
else{if(_3F){ELEM.removeClassName(_0b,_1m);}}}}},{_0N:new RegExp(/#\{([^\}]*)\}/),_3m:new RegExp(/\$\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,componentBehaviour:['view'],constructor:function(_1,_f){if(this.theme===undefined){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;}
else{this.preserveTheme=true;}
this.optimizeWidthOnRefresh=true;this.parent=_f;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.viewsZOrder=[];this._58();this.setRect(_1);this.isHidden=true;this.drawn=false;this._3p=_1.left;this._3q=_1.top;this._0V=[];if(!this.isinherited){this.draw();this.show();}},setFlexRight:function(_8,_U){if(_8===undefined){_8=true;}
this.flexRight=_8;if(_U===undefined){_U=0;}
this.flexRightOffset=_U;},setFlexLeft:function(_8,_U){if(_8===undefined){_8=true;}
this.flexLeft=_8;if(_U!==undefined){this.rect.setLeft(_U);}},setFlexTop:function(_8,_U){if(_8===undefined){_8=true;}
this.flexTop=_8;if(_U!==undefined){this.rect.setTop(_U);}},setFlexBottom:function(_8,_U){if(_8===undefined){_8=true;}
this.flexBottom=_8;if(_U===undefined){_U=0;}
this.flexBottomOffset=_U;},setAbsolute:function(_8){if(_8===undefined){_8=true;}
this.isAbsolute=_8;},setRelative:function(_8){if(_8===undefined){_8=true;}
this.isAbsolute=(!_8);},getThemeGfxPath:function(){if(this.preserveTheme){_g=this.theme;}else{_g=HThemeManager.currentTheme;}
return HThemeManager._1i(_g,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0c){if(this.preserveTheme){_g=this.theme;}else{_g=HThemeManager.currentTheme;}
return HThemeManager._55(_g,this.componentName,this.themePath,this.packageName,_0c);},_42:function(_14){this.elemId=ELEM.make(_14,'div');},_64:function(_4V){var _1V='display:none;overflow:hidden;visibility:hidden;';if(this.isAbsolute){_1V+='position:absolute;';}else{_1V+='position:relative;';}
_1V+=_4V;ELEM.setCSS(this.elemId,_1V);},_2M:function(){var _14;if(this.parent.elemId===undefined){_14=0;}
else if(this.parent.markupElemIds&&this.parent.markupElemIds['subview']){_14=this.parent.markupElemIds['subview'];}
else{_14=this.parent.elemId;}
return _14;},_58:function(){if(!this.elemId){this._42(this._2M());this._64('');if(this.preserveTheme){ELEM.addClassName(this.elemId,this.theme);}
else{ELEM.addClassName(this.elemId,HThemeManager.currentTheme);}}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
this.drawn=true;var _9=this.elemId;var _1=this.rect;ELEM.setStyle(_9,'left',this.flexLeft?(_1.left+'px'):'auto',true);ELEM.setStyle(_9,'top',this.flexTop?(_1.top+'px'):'auto',true);ELEM.setStyle(_9,'right',this.flexRight?(this.flexRightOffset+'px'):'auto',true);ELEM.setStyle(_9,'bottom',this.flexBottom?(this.flexBottomOffset+'px'):'auto',true);ELEM.setStyle(_9,'width',(this.flexLeft&&this.flexRight)?'auto':(_1.width+'px'),true);ELEM.setStyle(_9,'height',(this.flexTop&&this.flexBottom)?'auto':(_1.height+'px'),true);if(this.flexLeft&&this.flexRight){ELEM.setStyle(_9,'min-width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){ELEM.setStyle(_9,'min-height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){ELEM.setStyle(_9,'visibility','inherit',true);}
ELEM.setStyle(_9,'display','block',true);this._4M();if(this._3p!=_1.left||this._3q!=_1.top){this.invalidatePositionCache();this._3p=_1.left;this._3q=_1.top;}},_4M:function(){ELEM.setStyle(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this.viewId));},_2m:function(){var _2n=this.parent.viewsZOrder;for(var i=0;i<_2n.length;i++){ELEM.setStyle(HSystem.views[_2n[i]].elemId,'z-index',i);}},draw:function(){this.drawRect();},_3Z:function(){var _g;if(this.preserveTheme){_g=this.theme;}
else{_g=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_g,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){ELEM.setStyle(this.elemId,'display','none',true);this._3Z();this.bindMarkupVariables();ELEM.setHTML(this.elemId,this.markup);this.markupElemIds={};var _4k=['bg','label','state','control','value','subview'],i=0;for(;i<_4k.length;i++){var _0e=_4k[i],_3A=_0e+this.elemId,_5w=' id="'+_3A+'"';if(this.markup.indexOf(_5w)!=-1){this.markupElemIds[_0e]=this.bindDomElement(_3A);}}
ELEM.setStyle(this.elemId,'display','block',true);},setHTML:function(_1w){ELEM.setHTML(this.elemId,_1w);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_7,_6A,_2w){if(!this.elemId){return;}
ELEM.setStyle(this.elemId,_7,_6A,_2w);},style:function(_7){if(!this.elemId){return;}
return ELEM.getStyle(this.elemId,_7);},setStyleForPart:function(_0e,_7,_6A,_2w){if(!this.markupElemIds[_0e]){return;}
ELEM.setStyle(this.markupElemIds[_0e],_7,_6A,_2w);},styleForPart:function(_0e,_7){if(!this.markupElemIds[_0e]){return;}
ELEM.getStyle(this.markupElemIds[_0e],_7);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){var _6u=this.parent.viewsZOrder.indexOf(this.viewId),_6t=this.parent.views.indexOf(this.viewId);this.parent.views.splice(_6t,1);HSystem.delView(this.viewId);this.parent.viewsZOrder.splice(_6u,1);this._2m();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].die();}
this.remove();for(var i=0;i<this._0V.length;i++){ELEM.del(this._0V[i]);}
this._0V=[];ELEM.del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].onIdle();}},buildParents:function(_i){var _h=HSystem.views[_i];_h.parent=this;_h.parents=[];for(var _0J=0;_0J<this.parents.length;_0J++){_h.parents.push(this.parents[_0J]);}
_h.parents.push(this);},addView:function(_h){var _i=HSystem.addView(_h);this.views.push(_i);this.buildParents(_i);this.viewsZOrder.push(_i);return _i;},removeView:function(_i){HSystem.views[_i].remove();},destroyView:function(_i){HSystem.views[_i].die();},bounds:function(){var _0E=new HRect(this.rect);_0E.right-=_0E.left;_0E.left=0;_0E.bottom-=_0E.top;_0E.top=0;return _0E;},resizeBy:function(_2P,_1N){var _1=this.rect;_1.right+=_2P;_1.bottom+=_1N;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_q,_H){var _1=this.rect;_1.right=_1.left+_q;_1.bottom=_1.top+_H;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_2P,_1N){this.rect.offsetBy(_2P,_1N);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _p=this.zIndex();this.parent.viewsZOrder.splice(_p,1);this.parent.viewsZOrder.push(this.viewId);this._2m();},sendToBack:function(){if(!this.parent){return;}
var _p=this.zIndex();this.parent.viewsZOrder.splice(_p,1);this.parent.viewsZOrder.splice(0,0,this.viewId);this._2m();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this.viewId);},stringWidth:function(_18,_25,_9){if(_25!==undefined&&_25!=null){_18=_18.substring(0,_25);}
if(_9===undefined||_9==null){_9=this.elemId;}
var _0K=ELEM.make(_9);ELEM.setCSS(_0K,"visibility:hidden;position:absolute;white-space:nowrap;");ELEM.setHTML(_0K,_18);var _q=0,_H=0;if(ELEM._1y||ELEM._72||ELEM._73){_q=parseInt(ELEM.get(_0K).offsetWidth,10);if(arguments[3]){_H=parseInt(ELEM.get(_0K).offsetHeight,10);}}else{_q=parseInt(ELEM.get(_0K).clientWidth,10);if(ELEM._71){_q+=1;}
if(arguments[3]){_H=parseInt(ELEM.get(_0K).clientHeight,10);}}
ELEM.del(_0K);if(arguments[3]){return[_q,_H];}else{return _q;}},pageX:function(){var _7=0;var _6=this;while(_6){if(_6.elemId&&_6.rect){_7+=ELEM.get(_6.elemId).offsetLeft;_7-=ELEM.get(_6.elemId).scrollLeft;}
if(_6.markupElemIds&&_6.markupElemIds.subview){_7+=ELEM.get(_6.markupElemIds.subview).offsetLeft;_7-=ELEM.get(_6.markupElemIds.subview).scrollLeft;}
_6=_6.parent;}
return _7;},pageY:function(){var _b=0;var _6=this;while(_6){if(_6.elemId&&_6.rect){_b+=ELEM.get(_6.elemId).offsetTop;_b-=ELEM.get(_6.elemId).scrollTop;}
if(_6.markupElemIds&&_6.markupElemIds.subview){_b+=ELEM.get(_6.markupElemIds.subview).offsetTop;_b-=ELEM.get(_6.markupElemIds.subview).scrollTop;}
_6=_6.parent;}
return _b;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].invalidatePositionCache();}},bindDomElement:function(_3z){var _2v=ELEM.bindId(_3z);if(_2v){this._0V.push(_2v);}
return _2v;},unbindDomElement:function(_0b){var _3N=this._0V.indexOf(_0b);if(_3N>-1){ELEM.del(_0b);this._0V.splice(_3N,1);}},animateTo:function(_m,_0t,_0l){if(_m instanceof HPoint){var _1=new HRect(_m,_m);_1.setSize(this.rect.width,this.rect.height);this._2s(_1,_0t);}
else if(_m instanceof HRect){this._2s(_m,_0t);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._1R){window.clearInterval(this._1R);this._1R=null;var _05=parseInt(this.style('left'),10),_0B=parseInt(this.style('top'),10),_q=parseInt(this.style('width'),10),_H=parseInt(this.style('height'),10);this.rect.set(_05,_0B,_05+_q,_0B+_H);this.drawRect();if(this._3k){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_2s:function(_1,_0t,_0l){if(null===_0t||undefined===_0t){_0t=500;}
if(null===_0l||undefined===_0l||_0l<1){_0l=50;}
if(!this._1R){this._3k=false;this.onAnimationStart();var _67=new Date().getTime();var _k=this;this._1R=window.setInterval(function(){_k._6C({startTime:_67,duration:_0t,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_k.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_k.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_k.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_k.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0l));}},_6C:function(_m){var _4H=new Date().getTime();if(_4H<_m.startTime+_m.duration){var _50=_4H-_m.startTime;for(var i=0;i<_m.props.length;i++){var _2L=_m.props[i].from;var _4J=_m.props[i].to;if(_2L!=_4J){var _5X=_m.transition(_50,_2L,(_4J-_2L),_m.duration);this.setStyle(_m.props[i].prop,_5X+_m.props[i].unit);}}}else{for(var i=0;i<_m.props.length;i++){this.setStyle(_m.props[i].prop,_m.props[i].to+_m.props[i].unit);}
this._3k=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({componentBehaviour:['view','control'],refreshOnValueChange:true,refreshOnLabelChange:true,constructor:function(_1,_w,_2){if(!_2){_2={};}
var options=new(HComponentDefaults.extend(_2));this.options=options;if(this.isinherited){this.base(_1,_w);}
else{this.isinherited=true;this.base(_1,_w);this.isinherited=false;}
var _T=options.label;this.setLabel(_T);var _1t=options.events;this.setEvents(_1t);if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _5E=(_2.minValue||_2.maxValue);if(_5E){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(options.visible){this.show();}
else{this.hide();}
if(!this.isinherited){this.draw();}},setAction:function(_3i){this.action=_3i;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
EVENT.unreg(this);this.base();},setLabel:function(_T){this.label=_T;this.options.label=_T;this.refresh();},setEnabled:function(_8){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].setEnabled(_8);}
if(this.enabled===_8){return;}
this.enabled=_8;if(_8){EVENT.reg(this,this.events);}
else{EVENT.unreg(this);}
this.toggleCSSClass(this.elemId,HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(this.elemId,HControl.CSS_DISABLED,!this.enabled);},setValue:function(_6A){if(_6A===undefined){return;}
if(!this.valueObj){return;}
if(_6A!==this.value){this.value=_6A;this.valueObj.set(this.value);this.refresh();}},setValueObj:function(_2p){this.valueObj=_2p;this.setValue(_2p.value);},setValueRange:function(_6A,_29,_28){this.minValue=_29;this.maxValue=_28;_6A=(_6A<_29)?_29:_6A;_6A=(_6A>_28)?_28:_6A;this.setValue(_6A);this.refresh();},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}},refresh:function(){this.base();if(this.drawn){if(this.refreshOnValueChange){this.refreshValue();}
if(this.refreshOnLabelChange){this.refreshLabel();}}},setEvents:function(_1t){if(!this.events){var _5m=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,textEnter:false,click:false});this.events=new _5m;}
if(_1t){this.events.extend(_1t);}
this.events.ctrl=this;EVENT.focusOptions[this.elemId]=this.events;var _45=this.events.mouseMove;var _31=EVENT.coordListeners.indexOf(this.elemId);if(_45&&(_31==-1)){EVENT.coordListeners.push(this.elemId);}else if((!_45)&&(_31!=-1)){EVENT.coordListeners.splice(_31,1);}
this.isDragged=false;},setMouseMove:function(_8){this.events.mouseMove=_8;this.setEvents();},setClickable:function(_8){this.events.click=_8;this.setEvents();},setMouseDown:function(_8){this.events.mouseDown=_8;this.setEvents();},setMouseUp:function(_8){this.events.mouseUp=_8;this.setEvents();},setMouseWheel:function(_8){this.events.mouseWheel=_8;this.setEvents();},setDraggable:function(_8){this.events.draggable=_8;this.setEvents();},setDroppable:function(_8){this.events.droppable=_8;this.setEvents();},setKeyDown:function(_8){this.events.keyDown=_8;this.setEvents();},setKeyUp:function(_8){this.events.keyUp=_8;this.setEvents();},setTextEnter:function(_8){this.events.textEnter=_8;this.setEvents();},textEnter:function(){},focus:function(){},blur:function(){},gainedActiveStatus:function(_2V){},_5r:function(_2V){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_2V);},lostActiveStatus:function(_A){},_5G:function(_A){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_A);},mouseMove:function(_7,_b){},mouseDown:function(_7,_b,_24){},mouseUp:function(_7,_b,_24){},mouseWheel:function(_M){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_z){},keyUp:function(_z){},_47:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.focus(_0);Event.stop(e);},_46:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.owner;EVENT.blur(_0);Event.stop(e);},invalidatePositionCache:function(){this.base();EVENT.coordCacheFlush(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_4,_6A){this.id=_4;this.value=_6A;},set:function(_6A){this.value=_6A;},get:function(){return this.value;},bind:function(_1K){},unbind:function(_1K){}});HComponentDefaults=HClass.extend({label:"Untitled",visible:true,events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HDynControl=HControl.extend({componentName:'dyncontrol',componentBehaviour:['view','control','window'],constructor:function(_1,_f,_2){if(!_2){_2={};}
var _r=HClass.extend({minSize:[24,54],maxSize:[16000,9000],resizeW:1,resizeE:1,resizeN:1,resizeS:1,resizeNW:[1,1],resizeNE:[1,1],resizeSW:[1,1],resizeSE:[1,1],noResize:false});_2=new(_r.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
if(this.isinherited){this.base(_1,_f,_2);}
else{this.isinherited=true;this.base(_1,_f,_2);this.isinherited=false;}
this.presrveTheme=true;this.setDraggable(true);this._5B();this._3P();if(!this.isinherited){this.draw();}},drawRect:function(_3X,_6m){if(this.rect.width<this.options.minSize[0]){var _2G=0-(this.options.minSize[0]-this.rect.width);this.rect.setWidth(this.options.minSize[0]);if(_3X){this.rect.offsetBy(_2G,0);}}
else if(this.rect.width>this.options.maxSize[0]){var _2G=0-(this.options.maxSize[0]-this.rect.width);this.rect.setWidth(this.options.maxSize[0]);if(_3X){this.rect.offsetBy(_2G,0);}}
if(this.rect.height<this.options.minSize[1]){var _2D=0-(this.options.minSize[1]-this.rect.height);this.rect.setHeight(this.options.minSize[1]);if(_6m){this.rect.offsetBy(0,_2D);}}
else if(this.rect.height>this.options.maxSize[1]){var _2D=0-(this.options.maxSize[1]-this.rect.height);this.rect.setHeight(this.options.maxSize[1]);if(_6m){this.rect.offsetBy(0,_2D);}}
this.base();},draw:function(){var _04=this.drawn;this.base();this.drawRect();if(!_04){this.drawMarkup();this.buildStructure();}},buildStructure:function(){},_1Y:function(_7,_b){return this._5T.subtract(_7,_b);},dynResizeNW:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setLeftTop(_0.rect.leftTop.subtract(_D));_0.drawRect(1,1);_0._5T.set(_7,_b);},dynResizeNE:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setRightTop(_0.rect.rightTop.subtract(_D));_0.drawRect(0,1);_0._5T.set(_7,_b);},dynResizeSW:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setLeftBottom(_0.rect.leftBottom.subtract(_D));_0.drawRect(1,0);_0._5T.set(_7,_b);},dynResizeSE:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setRightBottom(_0.rect.rightBottom.subtract(_D));_0.drawRect(0,0);_0._5T.set(_7,_b);},dynResizeW:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setLeft(_0.rect.left-_D.x);_0.drawRect(1,0);_0._5T.set(_7,_b);},dynResizeE:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setRight(_0.rect.right-_D.x);_0.drawRect(0,0);_0._5T.set(_7,_b);},dynResizeN:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setTop(_0.rect.top-_D.y);_0.drawRect(0,1);_0._5T.set(_7,_b);},dynResizeS:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.setBottom(_0.rect.bottom-_D.y);_0.drawRect(0,0);_0._5T.set(_7,_b);},dynDrag:function(_0,_7,_b){var _D=_0._1Y(_7,_b);_0.rect.offsetTo(_0.rect.leftTop.subtract(_D));_0.drawRect(1,1);_0._5T.set(_7,_b);},_5B:function(){this._V=[];var i,_0=this,_7i=0,_7h=1,_7l=2,_7k=3,_7m=4,_7f=5,_7g=6,_7j=7,_6N=8,_V=this._V;_V[_7i]=_0.dynResizeNW;_V[_7h]=_0.dynResizeNE;_V[_7l]=_0.dynResizeSW;_V[_7k]=_0.dynResizeSE;_V[_7m]=_0.dynResizeW;_V[_7f]=_0.dynResizeE;_V[_7g]=_0.dynResizeN;_V[_7j]=_0.dynResizeS;_V[_6N]=_0.dynDrag;},_3P:function(){this._1c=-1;this._1O=[];var i,_1G,_s=this.options,_1=this.rect,_5Y=[[0,0,_s.resizeNW[0],_s.resizeNW[1]],[_1.width-_s.resizeNE[0],0,_1.width,_s.resizeNE[1]],[0,_1.height-_s.resizeSW[1],_s.resizeSW[0],_1.height],[_1.width-_s.resizeSE[0],_1.height-_s.resizeSE[1],_1.width,_1.height],[0,_s.resizeN,_s.resizeW,_1.height-_s.resizeS],[_1.width-_s.resizeE,_s.resizeN,_1.width,_1.height-_s.resizeS],[_s.resizeW,0,_1.width-_s.resizeE,_s.resizeN],[_s.resizeW,_1.height-_s.resizeS,_1.width-_s.resizeE,_1.height],[_s.resizeW,_s.resizeN,_1.width-_s.resizeE,_1.height-_s.resizeS]];for(i=0;i!=9;i++){_1G=_5Y[i];this._1O.push(new HRect(_1G[0],_1G[1],_1G[2],_1G[3]));}},_5d:function(){var i,_4R=this._66.subtract(this.rect.left,this.rect.top),_1O=this._1O;for(i=0;i!=9;i++){if(_1O[i].contains(_4R)){this._1c=i;return;}}},startDrag:function(_7,_b,_21){this._66=new HPoint(_7,_b);this._5T=new HPoint(_7,_b);this._7r=new HRect(this.rect);this._5d();if(this._1c==8){this.setStyle('cursor','move');}
this.bringToFront();this.doDrag(_7,_b,_21);},doDrag:function(_7,_b,_21){if(this._1c!=-1){this._V[this._1c](this,_7,_b);}},endDrag:function(_7,_b,_21){this.doDrag(_7,_b,_21);if(this._1c==8){this.setStyle('cursor','default');}
this._3P();}});