
var HClass=function(){if(arguments.length){var _3l=arguments[0];if(this==window){HClass.prototype.extend.call(_3l,arguments.callee.prototype);}else{this.extend(_3l);}}};HClass.prototype={extend:function(_0g,_4){var _1w=HClass.prototype.extend;if(arguments.length==2){var _2v=this[_0g];if((_2v instanceof Function)&&(_4 instanceof Function)&&_2v.valueOf()!=_4.valueOf()&&(/\bbase\b/).test(_4)){var _34=_4;_4=function(){var _62=this.base;this.base=_2v;var _67=_34.apply(this,arguments);this.base=_62;return _67;};_4.valueOf=function(){return _34;};_4.toString=function(){return String(_34);};}
return this[_0g]=_4;}else if(_0g){var _0o={toSource:null};var _4r=["toString","valueOf"];if(HClass._3c){_4r.push("constructor");}
for(var i=0;(_0j=_4r[i]);i++){if(_0g[_0j]!=_0o[_0j]){_1w.call(this,_0j,_0g[_0j]);}}
for(var _0j in _0g){if(!_0o[_0j]){_1w.call(this,_0j,_0g[_0j]);}}}
return this;},base:function(){}};HClass.extend=function(_0m,_3f){var _1w=HClass.prototype.extend;if(!_0m){_0m={};}
HClass._3c=true;var _0o=new this;_1w.call(_0o,_0m);var _0S=_0o.constructor;_0o.constructor=this;delete HClass._3c;var _0I=function(){if(!HClass._3c){_0S.apply(this,arguments);}
this.constructor=_0I;};_0I.prototype=_0o;_0I.extend=this.extend;_0I.implement=this.implement;_0I.toString=function(){return String(_0S);};_1w.call(_0I,_3f);var _37=_0S?_0I:_0o;if(_37.init instanceof Function){_37.init();}
return _37;};HClass.implement=function(_1A){if(_1A instanceof Function){_1A=_1A.prototype;}
this.prototype.extend(_1A);};var Base=HClass;if([].indexOf===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_54){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_54){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_3p=[];for(i=0;i<l;i++){_3p.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _3p.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_n,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _t=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_t=_t.extend(_2);this.options=new _t();this.request(_n);},request:function(_n){this.url=_n;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _l=this;this.transport.onreadystatechange=function(){_l.onStateChange();};this.setRequestHeaders();var _56=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_56);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1G=this.transport.readyState;if(_1G>1){this.respondToReadyState(_1G);}},respondToReadyState:function(_1G){if(_1G==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_1G==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});ELEMTickerInterval=10;BROWSER_TYPE={ie:false,ie6:false,ie7:false,opera:false,safari:false,firefox:false,firefox2:false};ELEM={_0S:function(){var _0=ELEM;_0._6U=[];_0._5n=null;_0._6V=false;_0._initDone=false;_0._7g=0;_0._setStyleCount=0;_0._setStyleDiffCount=0;_0._74=0;_0._getStyleMissCount=0;_0._flushLoopCount=0;_0._flushLoopFlushedCount=0;_0._flushStylCount=0;_0._flushTime=0;_0._flushCounter=0;_0._3Q=500;_0._timer=null;_0._11=ELEMTickerInterval;_0._flushing=false;_0._needFlush=false;_0._4y=1;_0._G=[];_0._H={_6r:[]};_0._4C={};_0._0L={};_0._0a={};_0._0q={};_0._3F=[];_0._2L={};_0._blockElems=",ADDRESS,BLOCKQUOTE,CENTER,DIR,DIV,DL,FIELDSET,FORM,H1,H2,H3,H4,H5,H6,HR,ISINDEX,MENU,NOFRAMES,NOSCRIPT,OL,P,PRE,TABLE,UL,";},_6Y:function(_3B,_u){var _0=ELEM,i=0,_4P=[],_H=_0._3V(_u),_1c=_H._1c;for(;i!=_3B;i++){_4P.push(_0.make(_1c,_u));}
for(i=0;i!=_3B;i++){_0.del(_4P[i]);}},_50:function(_6){var _3,_0,_G;_0=ELEM;_G=_0._G;_G.push(_6);_3=_G.length-1;return _3;},_77:function(_3){var _0=ELEM;_0._0L[_3]=[];_0._4C[_3]={};_0._0a[_3]=[];_0._0q[_3]={};_0._2L[_3]=false;},bindId:function(_5m){var _0=ELEM,_6=document.getElementById(_5m),_9=_0._50(_6);_0._77(_9);return _9;},bind:function(_6){var _3,_0=ELEM;_3=_0._50(_6);_0._77(_3);return _3;},_7m:function(_3,_6){var _0=ELEM;_0._G[_3]=_6;},get:function(_3){return ELEM._G[_3];},setHTML:function(_3,_1z){var _0=ELEM;_0._G[_3].innerHTML=_1z;},_3V:function(_u){var _0=ELEM,_H=_0._H;if(!_H[_u]){_H._6r.push(_u);_H[_u]=[];_H[_u]._1W=1;_H[_u]._1n=0;_H[_u]._1c=_0.make(_0._1c,'div');}
return _H[_u]._1c;},del:function(_3){var _0=ELEM,_6=_0._G[_3],_u=_6.tagName,_1c;_1c=_0._3V(_u);_0.append(_3,_1c);var _3G=_0._3F.indexOf(_3),_H=_0._H[_u];if(_3G!=-1){_0._3F.splice(_3G,1);}
try{_6.innerHTML='';}catch(e){}
_0.setCSS(_3,'display:none;');_0.delAttr(_3,'id');_0.delAttr(_3,'ctrl');_0._77(_3);_H._1W++;_H.push(_3);},append:function(_6c,_1N){var _0g,_3i,_0;_0=ELEM;_0g=_0._G[_6c];_3i=_0._G[_1N];_3i.appendChild(_0g);},setCSS:function(_3,_6S){ELEM._G[_3].style.cssText=_6S;},getCSS:function(_3){return ELEM._G[_3].style.cssText;},getVisibleSize:function(_3){var _0,_6,w,h,_o,_2k,_0=ELEM,_6=_0._G[_3],w=_6.offsetWidth,h=_6.offsetHeight,_o=_6.parentNode;while(_o&&_o.nodeName.toLowerCase()!='body'){if(!_0._27){_2k=document.defaultView.getComputedStyle(_o,null).getPropertyValue('overflow');}
else{_2k=_o.currentStyle.getAttribute('overflow');}
_2k=_2k!='visible';if(w>_o.clientWidth&&_2k){w=_o.clientWidth-_6.offsetLeft;}
if(h>_o.clientHeight&&_2k){h=_o.clientHeight-_6.offsetTop;}
_6=_6.parentNode;_o=_6.parentNode;}
return[w,h];},getSize:function(_3){var _0,_6,w,h,_o,_2k,_0=ELEM,_6=_0._G[_3],w=_6.offsetWidth,h=_6.offsetHeight;return[w,h];},getScrollSize:function(_3){var _0,_6,w,h,_o,_2k,_0=ELEM,_6=_0._G[_3],w=_6.scrollWidth,h=_6.scrollHeight;return[w,h];},getVisiblePosition:function(_3){var x,y,_6,_0,_0=ELEM,x=0,y=0,_6=_0._G[_3];while(_6!==document){x+=_6.offsetLeft;y+=_6.offsetTop;x-=_6.scrollLeft;y-=_6.scrollTop;_6=_6.parentNode;if(!_6){break;}}
return[x,y];},getOpacity:function(_3){var _0,_Y,_3j,_24;_0=ELEM;_24=_0.getStyle;if(_Y=_24(_3,'-khtml-opacity')){return parseFloat(_Y);}
if(_Y=_24(_3,'-moz-opacity')){return parseFloat(_Y);}
_3j=_24(_3,'opacity',true);if(_Y=_3j||(_3j==0)){return parseFloat(_Y);}
if(_Y=(_0._G[_3].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_Y[1]){return parseFloat(_Y[1])/100;}}
return 1.0;},setOpacity:function(_3,_4){var _0=ELEM;if(_4==1&&_0._27){_0._G[_3].style.setAttribute('filter',_0.getStyle(_3,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_4<0.00001){_4=0;}
if(_0._27){_0._G[_3].style.setAttribute('filter',_0.getStyle(_3,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_4*100+')');}else{_0._G[_3].style.setProperty('opacity',_4,'');}}},getIntStyle:function(_3,_f){var _4=ELEM.getStyle(_3,_f);return parseInt(_4,10);},setBoxCoords:function(_3,_02){ELEM.setStyle(_3,'left',_02[0]+'px');ELEM.setStyle(_3,'top',_02[1]+'px');ELEM.setStyle(_3,'width',_02[2]+'px');ELEM.setStyle(_3,'height',_02[3]+'px');},getExtraWidth:function(_3){var _0n=ELEM.getIntStyle;return _0n(_3,'padding-left')+_0n(_3,'padding-right')+_0n(_3,'border-left-width')+_0n(_3,'border-right-width');},getExtraHeight:function(_3){var _0n=ELEM.getIntStyle;return _0n(_3,'padding-top')+_0n(_3,'padding-bottom')+_0n(_3,'border-top-width')+_0n(_3,'border-bottom-width');},setFPS:function(_0l){ELEM._11=1000/_0l;if(ELEM._11<ELEMTickerInterval){ELEM._11=ELEMTickerInterval;}},setSlowness:function(_4y){ELEM._4y=_4y;},setIdleDelay:function(_3Q){ELEM._3Q=_3Q;},_76:false,flushLoop:function(_04){var _0=ELEM;_0._flushLoopCount++;if(_0._10&&(_0._flushLoopCount%5==0)&&_0._76){iefix._01();_0._76=false;}
clearTimeout(_0._timer);if(_0._flushing){_04*=2;_0._timer=setTimeout('ELEM.flushLoop('+_04+');',_04);return;}else{if(!_0._needFlush){if(_0._10&&_0._76){iefix._01();_0._76=false;}
_0._timer=setTimeout('ELEM.flushLoop('+_04+');',_0._3Q);return;}
_04=parseInt(_0._4y*(_0._flushTime/_0._flushCounter),ELEMTickerInterval);if(_04<_0._11||!_04){_04=_0._11;}
_0._flushing=true;_0._timer=setTimeout('ELEM.flushLoop('+_04+');',_04);}
_0._flushTime-=new Date().getTime();var _31,_1r,i,_0L;_3F=_0._3F;_31=_3F.length;_1r=_3F.splice(0,_31);var _5u=new Date().getTime();for(i=0;i<_31;i++){_0._flushLoopFlushed++;var _3=_1r.pop();_0._2L[_3]=false;_0._5v(_3);_0._6Z(_3);}
_0._flushCounter++;_0._flushTime+=new Date().getTime();if(_0._3F.length==0&&_0._needFlush){_0._needFlush=false;}
_0._flushing=false;},_6Z:function(_3){var _0=ELEM,_0a=_0._0a[_3],_0q=_0._0q[_3],_6=_0._G[_3],_f,_0M,i,_3P=_0a.length,_1r=_0a.splice(0,_3P);for(i=0;i!=_3P;i++){_f=_1r.pop();_0M=_0q[_f];_6.setAttribute(_f,_0M);}},getAttr:function(_3,_f,_0r){var _0=ELEM,_1V=_0._0q[_3][_f],_0M;if(_1V!==undefined&&!_0r){return _1V;}
var _6=_0._G[_3];if(_6.getAttribute(_f)==null){_6[_f]='';}
_0M=_6.getAttribute(_f);_0._0q[_3][_f]=_0M;return _0M;},setAttr:function(_3,_f,_4,_0r){var _1s,_0=ELEM,_0a=_0._0a[_3],_0q=_0._0q[_3];_1s=_4!=_0.getAttr(_3,_f);if(_1s){_0q[_f]=_4;if(_0r){_0._G[_3].setAttribute(_f,_4);}
else{if(_0a.indexOf(_f)==-1){_0a.push(_f);}
if(!_0._2L[_3]){_0._3F.push(_3);_0._2L[_3]=true;_0._6P();}}}},delAttr:function(_3,_f){var _1s,_0=ELEM,_0a=_0._0a[_3],_0q=_0._0q[_3];delete _0q[_f];_0._G[_3].removeAttribute(_f);if(_0a.indexOf(_f)!=-1){_0a.splice(_0a.indexOf(_f,1));}
if(_0._2L[_3]){_0._3F.splice(_0._3F.indexOf(_3,1));_0._2L[_3]=false;_0._6P();}},hasClassName:function(_9,_0P){var _5=ELEM.get(_9);if(!_5)return;var _3I=false;var _0Q=_5.className.split(' ');for(var i=0;i<_0Q.length;i++){if(_0Q[i]==_0P){_3I=true;}}
return _3I;},addClassName:function(_9,_0P){var _5=ELEM.get(_9);if(!_5)return;ELEM.removeClassName(_9,_0P);_5.className+=' '+_0P;},removeClassName:function(_9,_0P){var _5=ELEM.get(_9);if(!_5)return;var _36='';var _0Q=_5.className.split(' ');for(var i=0;i<_0Q.length;i++){if(_0Q[i]!=_0P){if(i>0)_36+=' ';_36+=_0Q[i];}}
_5.className=_36;},_6P:function(){var _0=ELEM;if(!_0._needFlush){_0._needFlush=true;if(!_0._flushing){clearTimeout(_0._timer);_0._timer=setTimeout('ELEM.flushLoop('+_0._11+');',_0._11);}}},printStats:function(){var _0=ELEM,_H=_0._H,i=0,_u,_6q,_1W,_1n;console.log('Recycler efficiency:');var _2u=0;for(;i!=_H._6r.length;i++){_u=_H._6r[i];console.log(' tagName: '+_u);_6q=_H[_u].length;console.log('   length  : '+_6q);_1W=_H[_u]._1W;console.log('   countIn : '+_1W);_1n=_H[_u]._1n;_2u+=_1n;console.log('   countOut: '+_1n);console.log('--------------------------------');}
console.log('================================');console.log('Flushing efficiency:');console.log('  total real time spent: '+_0._flushTime+'ms');console.log('  total times called:    '+_0._flushLoopCount);console.log('  total times flushed:   '+_0._flushCounter);console.log('  total items flushed:   '+_0._flushLoopFlushedCount);console.log('  total real style sets: '+_0._flushStylCount);console.log('================================');console.log('setStyle efficiency:');console.log('  total times called:    '+_0._setStyleCount);console.log('  total times non-cache: '+_0._setStyleDiffCount);console.log('================================');console.log('getStyle efficiency:');console.log('  total times called:    '+_0._74);console.log('  total times non-cache: '+_0._getStyleMissCount);console.log('================================');console.log('Summary:');console.log('  recycler saved '+(_2u)+' of '+_0._7g+' ('+Math.round(_2u/_0._7g*100)+'%) document.createElement calls');console.log('  style buffer saved '+(_0._setStyleDiffCount-_0._flushStylCount)+' of '+_0._setStyleDiffCount+' ('+Math.round(((_0._setStyleDiffCount-_0._flushStylCount)/_0._setStyleDiffCount)*100)+'%) non-cached DOM style sets');console.log('  style cache saved '+(_0._setStyleCount-_0._setStyleDiffCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._setStyleDiffCount)/_0._setStyleCount)*100)+'%) DOM style sets');console.log('  style cache saved '+(_0._74-_0._getStyleMissCount)+' of '+_0._74+' ('+Math.round(((_0._74-_0._getStyleMissCount)/_0._74)*100)+'%) DOM style gets');console.log('  style buffer and cache saved '+(_0._setStyleCount-_0._flushStylCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._flushStylCount)/_0._setStyleCount)*100)+'%) total DOM style sets');},setStyle:function(_3,_f,_4,_0r){var _0=ELEM,_v=_0._4C[_3],_3H=_0._G,_1s,_0L;_0._setStyleCount++;_1s=_4!==_v[_f];if(_1s){_0._setStyleDiffCount++;_v[_f]=_4;if(_0r){if(_f=='opacity'){_0.setOpacity(_3,_4);}
else{_0._27?(_3H[_3].style.setAttribute(_f.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_v[_f])):(_3H[_3].style.setProperty(_f,_v[_f],''));}
if(_0._10){if(iefix._2o.indexOf(_f)!=-1){_0._76=true;}}}else{_2L=_0._2L;_0L=_0._0L[_3];if(_0L.indexOf(_f)==-1){_0L.push(_f);}
if(!_2L[_3]){_0._3F.push(_3);_2L[_3]=true;_0._6P();}}}},make:function(_1N,_u){if(_1N===undefined){_1N=0;}
if(_u===undefined){_u='DIV';}else{_u=_u.toUpperCase();}
var _0=ELEM,_6,_3;_0._7g++;if(_0._H[_u]){if(_0._H[_u].length!=0){_3=_0._H[_u].pop();_0._H[_u]._1n++;_6=_0._G[_3];if(_0._blockElems.indexOf(','+_u+',')!=-1){_0.setCSS(_3,'display:block;');}else{_0.setCSS(_3,'display:inline;');}
_0.append(_3,_1N);return _3;}}
_6=document.createElement(_u);_0._G[_1N].appendChild(_6);_3=_0._50(_6);_0._77(_3);return _3;},windowSize:function(){var _0j,_5y;_0j=(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;_5y=(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;return[_0j,_5y];},_3T:function(){var _0=ELEM,_0F,_2D;var _2R=["ELEM.getStyle=function(_3,_f,_0r){","var _0=ELEM,_v=_0._4C[_3],_1I;_0._74++;","if((_v[_f]===undefined)||_0r){","if(!_0r){_0._getStyleMissCount++;}","if((_f=='opacity')&&_0r){_1I=_0.getOpacity(_3);}","else{","_1I=document.defaultView.getComputedStyle(_0._G[_3],null).getPropertyValue(_f);","_58=_f.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){","return $3.toUpperCase()+$4});","_1I=_0._G[_3].currentStyle[_58];","}_v[_f]=_1I;","}return _v[_f];};"];if(_0._27){_2R.splice(6,1);}else{_2R.splice(7,3);}
eval(_2R.join(''));var _2N=["ELEM._5v=function(_3){","var _0=ELEM,_0L=_0._0L[_3],_v=_0._4C[_3],_6=_0._G[_3],_1u,_47,_3w,_f,_1r,_1I;","if(!_6){return;}","_1u=_6.style;","_47=_0L.length;","_1r=_0L.splice(0,_47);","for(_3w=0;_3w!=_47;_3w++){","_f=_1r.pop();_0._flushStylCount++;","if(_f=='opacity'){_1I=_0.getOpacity(_3,_v[_f]);}else{","if(_0._10){if(iefix._2o.indexOf(_f)!=-1){_0._76=true;}}try{_1u.setAttribute(_f.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_v[_f]);}catch(e){}}}};","_1u.setProperty(_f,_v[_f],'');}}};"];if(_0._27){_2N.pop();}else{_2N.splice(9,1);}
eval(_2N.join(''));_0.bind(document.body);_0._1c=_0.make(0,'div');_0.setCSS(_0._1c,"display:none;visibility:hidden;");_0.setAttr(_0._1c,'id','trashcan_'+_0._1c);_0._timer=setTimeout('ELEM.flushLoop('+_0._11+')',_0._11);if(!_0._6U){return;}
while(_0._6U.length!=0){_0F=_0._6U.shift();if(typeof _0F=='string'){_2D=eval(_0F);if(typeof _2D=='string'){_0._6U.push(_2D);}}}
_0._initDone=true;},_6E:function(){_0=ELEM;_0._27=(document.all&&navigator.userAgent.indexOf("Opera")==-1)?true:false;_0._10=(_0._27&&navigator.userAgent.indexOf("MSIE 6")!=-1)?true:false;_0._7a=(_0._27&&navigator.userAgent.indexOf("MSIE 7")!=-1)?true:false;_0._7c=(navigator.userAgent.indexOf("KHTML")!=-1)?true:false;_0._is_ff=(navigator.userAgent.indexOf("Firefox")!=-1)?true:false;_0._79=(navigator.userAgent.indexOf("Firefox/3.")!=-1)?true:false;_0._7b=(navigator.userAgent.indexOf("Opera")!=-1)?true:false;BROWSER_TYPE={opera:_0._7b,safari:_0._7c,firefox:_0._is_ff,ie:_0._27,ie6:_0._10,ie7:_0._7a,firefox3:_0._79};_0._5p();},_5o:function(_0F){var _0=ELEM;if(typeof _0F=='string'){if(_0._initDone==true){eval(_0F);}else{_0._6U.push(_0F);}}},_5p:function(){var _7d=false;var _0=ELEM;if(_0._27){var _3R="javascript:void(0)";if(location.protocol=="https:"){_3R="src=//0";}
document.write("<scr"+"ipt id=_4W defer src="+_3R+"><\/scr"+"ipt>");var _5G=document.getElementById("_4W");_5G.onreadystatechange=function(){if(this.readyState=="complete"){ELEM._6V=true;ELEM._3T();delete ELEM._6U;clearTimeout(ELEM._5n);delete ELEM._5n;}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(document.readyState))){_0._6V=true;}
else if(document.body){_0._6V=true;}
if(!_0._6V){_0._5n=setTimeout('ELEM._5p()',ELEMTickerInterval*10);}else{_0._3T();delete _0._6U;clearTimeout(_0._5n);delete _0._5n;}}};ELEM._0S();LOAD=ELEM._5o;ELEM._6E();Event={element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}
else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(ELEM._27||ELEM._7c){return(e.button==1);}
else{return(e.button==0);}},observers:false,_5Q:function(_6,_0j,_1y,_1P){if(!Event.observers){Event.observers=[];}
if(_6.addEventListener){this.observers.push([_6,_0j,_1y,_1P]);_6.addEventListener(_0j,_1y,_1P);}
else if(_6.attachEvent){this.observers.push([_6,_0j,_1y,_1P]);_6.attachEvent("on"+_0j,_1y);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_6,_0j,_1y,_1P){_1P=_1P||false;Event._5Q(_6,_0j,_1y,_1P);},stopObserving:function(_6,_0j,_1y,_1P){_1P=_1P||false;if(_6.removeEventListener){_6.removeEventListener(_0j,_1y,_1P);}
else if(detachEvent){_6.detachEvent("on"+_0j,_1y);}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_6&&eo[1]==_0j&&eo[2]==_1y&&eo[3]==_1P){Event.observers[i]=null;Event.observers.splice(i,1);}
else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34};if(ELEM._27){Event.observe(window,"unload",Event.unloadCache,false);}
_3C={mouseMove:false,mouseDown:false,click:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,isDragged:false,textEnter:false};EVENT={status:[false,false,0,0,[],false,false,false],button1:0,button2:1,crsrX:2,crsrY:3,keysDown:4,altKeyDown:5,ctrlKeyDown:6,shiftKeyDown:7,start:function(){var _2S,_2M,i,_0=EVENT;if(ELEM._27){_2S=document;}
else{_2S=window;}
_2M=[['mousemove',EVENT.mouseMove],['mouseup',EVENT.mouseUp],['mousedown',EVENT.mouseDown],['click',EVENT.click],['keyup',EVENT.keyUp],['keydown',EVENT.keyDown],['keypress',EVENT.keyPress],['contextmenu',EVENT.contextMenu],['resize',EVENT.resize],['mousewheel',EVENT.mouseWheel]];for(i=0;i!=_2M.length;i++){Event.observe(_2S,_2M[i][0],_2M[i][1]);}
if(window.addEventListener){window.addEventListener('DOMMouseScroll',EVENT.mouseWheel,false);}
_0.listeners=[];_0.focused=[];_0.resizeListeners=[];_0.coordListeners=[];_0.focusOptions={};_0.dragItems=[];_0.hovered=[];_0.hoverInterval=50;_0.hoverTimer=new Date().getTime();_0.topmostDroppable=null;_0.textEnterCtrls=[];_0._2E=[];_0._coordCacheFlag=true;_0._lastCoordFlushTimeout=null;_0.activeControl=null;_0._lastKeyDown=null;},coordCacheFlush:function(_9){if(_9){EVENT._2E[_9]=null;}
else{EVENT._2E=[];}},reg:function(_d,_0u){var _9,_6,_0=EVENT,_63;_9=_d.elemId;_6=ELEM.get(_9);if(ELEM._27){_6.setAttribute('ctrl',_d);}
else{_6.ctrl=_d;}
_0.listeners[_9]=true;_0.focused[_9]=false;for(var _63 in _3C){if(_0u[_63]===undefined){_0u[_63]=_3C[_63];}}
_0.focusOptions[_9]=_0u;var _2F=_0.coordListeners.indexOf(_9);if(_0u.mouseMove){if(_2F==-1){_0.coordListeners.push(_9);}}
else if(_2F!=-1){_0.coordListeners.splice(_2F,1);}
if(_0u.textEnter){if(_0.textEnterCtrls.indexOf(_d.viewId)==-1){_0.textEnterCtrls.push(_d.viewId);}}
if(_0u.resize){if(_0.resizeListeners.indexOf(_d.viewId)==-1){_0.resizeListeners.push(_d.viewId);}}
Event.observe(_6,'mouseover',_0._4e);},unreg:function(_d){var _0=EVENT,_9,_6;if(_d===this.activeControl){_0.changeActiveControl(null);}
_9=_d.elemId;_6=ELEM.get(_9);this.listeners[_9]=false;this.focused[_9]=false;this._2E[_9]=null;var _4J=_0.textEnterCtrls.indexOf(_d.viewId);if(_4J!=-1){_0.textEnterCtrls.splice(_4J,1);}
var _4t=_0.resizeListeners.indexOf(_d.viewId);if(_4t!=-1){_0.resizeListeners.splice(_4t,1);}
Event.stopObserving(_6,'mouseover',_0._4e);},resize:function(e){var i=0,_0=EVENT,_20,_d;for(;i<_0.resizeListeners.length;i++){_20=_0.resizeListeners[i];_d=HSystem.views[_20];if(_d.onResize){_d.onResize();}}},_4e:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.focus(_0);Event.stop(e);},_4d:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.blur(_0);Event.stop(e);},focus:function(_d){var _0=EVENT,_9,_6;_9=_d.elemId;_6=ELEM.get(_9);if(_0.focused[_9]==false&&_0.focusOptions[_9].isDragged==false){Event.stopObserving(_6,'mouseover',_0._4e);Event.observe(_6,'mouseout',_0._4d);_0.focused[_9]=true;if(_d['focus']){_d.focus();}}},blur:function(_d){var _0=EVENT,_9,_6;_9=_d.elemId;_6=ELEM.get(_9);if(_0.focused[_9]==true&&_0.focusOptions[_9].isDragged==false){Event.stopObserving(_6,'mouseout',_0._4d);Event.observe(_6,'mouseover',_0._4e);_0.focused[_9]=false;if(_d['blur']){_d.blur();}}},mouseMove:function(e){var _0=EVENT,x,y,_0U;x=Event.pointerX(e);y=Event.pointerY(e);_0.status[_0.crsrX]=x;_0.status[_0.crsrY]=y;_0U=_0.flushMouseMove(x,y);_0._7h(e);if(_0U){Event.stop(e);}},flushMouseMove:function(x,y){var _0=EVENT,x,y,_0U,i,j,_9,_d;clearTimeout(_0._lastCoordFlushTimeout);_0U=false;for(i=0;i!=_0.dragItems.length;i++){_9=_0.dragItems[i];_0.focusOptions[_9].ctrl.doDrag(x,y);_0.coordCacheFlush(_9);_0U=true;}
if(new Date().getTime()>_0.hoverTimer+_0.hoverInterval){for(i=0;i!=_0.coordListeners.length;i++){_9=_0.coordListeners[i];_d=_0.focusOptions[_9].ctrl;_d.mouseMove(x,y);}
_0._7G();var _2r;for(i=0;i!=_0.dragItems.length;i++){_2r=_0.topmostDroppable;_0.topmostDroppable=null;_9=_0.dragItems[i];_d=_0.focusOptions[_9].ctrl;var _25,_1t;for(j=0;j!=_0.hovered.length;j++){_25=_0.hovered[j];if(_25!=_9&&_0.focusOptions[_25].ctrl){_1t=_0.focusOptions[_25].ctrl;if(!_0.topmostDroppable||_1t.zIndex()>_0.topmostDroppable.zIndex()||_1t.supr===_0.topmostDroppable){if(_0.focusOptions[_1t.elemId].droppable){_0.topmostDroppable=_1t;}}}}
if(_2r!=_0.topmostDroppable){if(_2r){_2r.onHoverEnd(_d);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverStart(_d);}}}
_0.hoverTimer=new Date().getTime();}
else{_0._lastCoordFlushTimeout=setTimeout('EVENT.flushMouseMove('+x+','+y+');',_0.hoverInterval);}
return _0U;},_7G:function(){var _0=EVENT,x,y,i,_d,_6,_38,_4x,_02;_0.hovered=[];x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.listeners.length;i++){if(!_0.listeners[i]||!_0.focusOptions[i].ctrl){continue;}
_d=_0.focusOptions[i].ctrl;_6=ELEM.get(i);if(!_0._coordCacheFlag||!_0._2E[i]){_38=ELEM.getVisiblePosition(_d.elemId);_4x=ELEM.getVisibleSize(_d.elemId);_0._2E[i]=[_38[0],_38[1],_4x[0],_4x[1]];}
_02=_0._2E[i];if(x>=_02[0]&&x<=_02[0]+_02[2]&&y>=_02[1]&&y<=_02[1]+_02[3]){_0.hovered.push(i);}}},mouseDown:function(e,_U){var _0=EVENT,_2J,x,y,i,_B,_0z,_2d;_0._7h(e);_2J=false;if(_U===undefined){_U=Event.isLeftClick(e);}
if(_U){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_B=null;_0z=[];_2d=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_B=_0.focusOptions[i].ctrl;}
if((_0.focusOptions[i].draggable==true)&&_0.dragItems.indexOf(i)==-1){_0z.push(i);}
else if(_0.focusOptions[i].mouseDown==true){_2d.push(i);}}}
if(_B){_0.changeActiveControl(_B);}
for(i=0;i!=_0z.length;i++){_0.dragItems.push(_0z[i]);_0.focusOptions[_0z[i]].ctrl.startDrag(x,y);_2J=true;}
var _1L=_2d.length;for(i=0;i!=_2d.length;i++){if(_0.focusOptions[_2d[i]].ctrl.mouseDown(x,y,_U)){_1L--;}}
if(_2J){document.body.focus();_0._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if((_1L==0)&&(_0.hovered.length!=0)&&(_B&&(_B.textElemId===false))){Event.stop(e);}
return true;},click:function(e,_U){var _0=EVENT,x,y,i,_B,_2C;_0._7h(e);if(_U===undefined){_U=Event.isLeftClick(e);}
if(_U){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_B=null;_2C=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_B=_0.focusOptions[i].ctrl;}
else if(_0.focusOptions[i].click==true){_2C.push(i);}}}
if(_B){_0.changeActiveControl(_B);}
var _1L=_2C.length;for(i=0;i!=_2C.length;i++){if(_0.focusOptions[_2C[i]].ctrl.click(x,y,_U)){_1L--;}}
if((_1L==0)&&(_0.hovered.length!=0)&&(_B&&(_B.textElemId===false))){Event.stop(e);}
return true;},changeActiveControl:function(_d){var _0=EVENT,_16;_16=_0.activeControl;if(_d!=_16){if(_16){_16.active=false;_16._5M(_d);}
_0.activeControl=null;if(_d){_d.active=true;_0.activeControl=_d;_d._5x(_16);}}},mouseUp:function(e){var _0=EVENT,_2I,x,y,_9,_d,i;_0._7h(e);_2I=false;_U=Event.isLeftClick(e);_0.status[_0.button1]=false;_0.status[_0.button2]=false;x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.dragItems.length;i++){_9=_0.dragItems[i];_d=_0.focusOptions[_9].ctrl;_d.endDrag(x,y);_2I=true;_0._7G();if(_0.hovered.indexOf(_9)==-1){_0.blur(_d);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverEnd(_d);_0.topmostDroppable.onDrop(_d);_0.topmostDroppable=null;}}
_0.dragItems=[];if(_2I){document.onselectstart=_0._storedOnSelectStart;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseUp==true){_0.focusOptions[i].ctrl.mouseUp(x,y,_U);}}}
return true;},keyDown:function(e){var _0=EVENT,_0h;_0._7h(e);_0h=e.keyCode;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);if(_0._lastKeyDown!=_0h){_0.activeControl.keyDown(_0h);}}
if(_0.status[_0.keysDown].indexOf(_0h)==-1){_0.status[_0.keysDown].push(_0h);}
_0._lastKeyDown=_0h;},keyUp:function(e){var _0=EVENT,_0h,_keycodeindex;_0._7h(e);_0h=e.keyCode;_0._lastKeyDown=null;for(var i=0;i!=_0.textEnterCtrls.length;i++){var _20=_0.textEnterCtrls[i],_d=HSystem.views[_20];if(_d.textEnter){_d.textEnter();}}
if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyUp==true){_0.activeControl.keyUp(_0h);}
_3Y=_0.status[_0.keysDown].indexOf(_0h);if(_3Y!=-1){_0.status[_0.keysDown].splice(_3Y,1);}},keyPress:function(e){var _0=EVENT;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _0=EVENT,_N,i;_N=0;if(!e){e=window.event;}
if(e.wheelDelta){_N=e.wheelDelta/120;if(window.opera){_N=-_N;}}
else if(e.detail){_N=-e.detail/3;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseWheel==true){Event.stop(e);_0.focusOptions[i].ctrl.mouseWheel(_N);}}}},contextMenu:function(e){EVENT.mouseDown(e,false);Event.stop(e);},_7h:function(e){var _0=EVENT;_0.status[_0.altKeyDown]=e.altKey;_0.status[_0.ctrlKeyDown]=e.ctrlKey;_0.status[_0.shiftKeyDown]=e.shiftKey;}};LOAD('EVENT.start();');SHA={_3O:0,hexCase:function(){return SHA._3O;},setHexCase:function(_59){SHA._3O=_59;},_3r:"=",base64Pad:function(){return SHA._3r;},setBase64Pad:function(_5W){SHA._3r=_5W;},_3v:8,chrsz:function(){return SHA._3v;},setChrsz:function(_55){SHA._3v=_55;},hexSHA1:function(_0y){var _0=SHA;return _0._6N(_0._6R(_0._7B(_0y),_0y.length*_0._3v));},b64SHA1:function(_0y){var _0=SHA;return _0._6M(_0._6R(_0._7B(_0y),_0y.length*_0._3v));},strSHA1:function(_0y){var _0=SHA;return _0._6O(_0._6R(_0._7B(_0y),_0y.length*_0._3v));},hexHmacSHA1:function(_f,_0s){var _0=SHA;return _0._6N(_0._6Q(_f,_0s));},b64HmacSHA1:function(_f,_0s){var _0=SHA;return _0._6M(_0._6Q(_f,_0s));},strHmacSHA1:function(_f,_0s){var _0=SHA;return _0._6O(_0._6Q(_f,_0s));},str2Base64:function(_C){var _0=SHA;return _0._6M(_0._7B(_C));},test:function(){return SHA.hexSHA1("abc")=="a9993e364706816aba3e25717850c26c9cd0d89d";},_6R:function(_7,_30){var _0=SHA;_7[_30>>5]|=0x80<<(24-_30%32);_7[((_30+64>>9)<<4)+15]=_30;var _0j=new Array(80),_0D=1732584193,_M=-271733879,_S=-1732584194,_T=271733878,_0W=-1009589776,i,_4i,_4j,_4k,_4l,_4m,j,_L;for(i=0;i<_7.length;i+=16){_4i=_0D;_4j=_M;_4k=_S;_4l=_T;_4m=_0W;for(j=0;j<80;j++){if(j<16){_0j[j]=_7[i+j];}
else{_0j[j]=_0._7w(_0j[j-3]^_0j[j-8]^_0j[j-14]^_0j[j-16],1);}
_L=_0._7x(_0._7x(_0._7w(_0D,5),_0._7y(j,_M,_S,_T)),_0._7x(_0._7x(_0W,_0j[j]),_0._7z(j)));_0W=_T;_T=_S;_S=_0._7w(_M,30);_M=_0D;_0D=_L;}
_0D=_0._7x(_0D,_4i);_M=_0._7x(_M,_4j);_S=_0._7x(_S,_4k);_T=_0._7x(_T,_4l);_0W=_0._7x(_0W,_4m);}
return[_0D,_M,_S,_T,_0W];},_7y:function(_L,_M,_S,_T){if(_L<20){return(_M&_S)|((~_M)&_T);}
if(_L<40){return _M^_S^_T;}
if(_L<60){return(_M&_S)|(_M&_T)|(_S&_T);}
return _M^_S^_T;},_7z:function(_L){return(_L<20)?1518500249:(_L<40)?1859775393:(_L<60)?-1894007588:-899497514;},_6Q:function(_f,_0s){var _0=SHA,_1i=_0._7B(_f),_3X=new Array(16),_4n=new Array(16),i,_3K;if(_1i.length>16){_1i=_0._6R(_1i,_f.length*_0._3v);}
for(i=0;i<16;i++){_3X[i]=_1i[i]^0x36363636;_4n[i]=_1i[i]^0x5C5C5C5C;}
_3K=_0._6R(_3X.concat(_0._7B(_0s)),512+_0s.length*_0._3v);return _0._6R(_4n.concat(_3K),512+160);},_7x:function(_7,_c){var _48=(_7&0xFFFF)+(_c&0xFFFF),_5N=(_7>>16)+(_c>>16)+(_48>>16);return(_5N<<16)|(_48&0xFFFF);},_7w:function(_2i,_3x){return(_2i<<_3x)|(_2i>>>(32-_3x));},_7B:function(_C){var _0=SHA,_1h=[],_33=(1<<_0._3v)-1,_6i=_C.length*_0._3v,i;for(i=0;i<_6i;i+=_0._3v){_1h[i>>5]|=(_C.charCodeAt(i/_0._3v)&_33)<<(32-_0._3v-i%32);}
return _1h;},_6O:function(_1h){var _0=SHA,_C="",_33=(1<<_0._3v)-1,i,_2z=_1h.length*32,_4V=32-_0._3v;for(i=0;i<_2z;i+=_0._3v){_C+=String.fromCharCode((_1h[i>>5]>>>(_4V-i%32))&_33);}
return _C;},_6N:function(_0k){var _0=SHA,_3N=_0._3O?"0123456789ABCDEF":"0123456789abcdef",_C="",i,_2y=_0k.length*4;for(i=0;i<_2y;i++){_C+=_3N.charAt((_0k[i>>2]>>((3-i%4)*8+4))&0xF)+
_3N.charAt((_0k[i>>2]>>((3-i%4)*8))&0xF);}
return _C;},_6M:function(_0k){var _0=SHA,_1b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",_C="",i,_2y=_0k.length*4,_4F,_4G,_6I,_4Q,j,_2z=_0k.length*32;for(i=0;i<_2y;i+=3){_4F=(((_0k[i>>2]>>8*(3-i%4))&0xFF)<<16);_4G=(((_0k[i+1>>2]>>8*(3-(i+1)%4))&0xFF)<<8);_6o=((_0k[i+2>>2]>>8*(3-(i+2)%4))&0xFF);_4Q=(_4F|_4G|_6o);for(j=0;j<4;j++){if(i*8+j*6>_2z){_C+=_0._3r;}
else{_C+=_1b.charAt((_4Q>>6*(3-j))&0x3F);}}}
return _C;}};HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporter=Base.extend({constructor:null,start:function(_6z){var _0=HTransporter;_0.url_base=_6z;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_8){HTransporter.pollMode=_8;},failure:function(resp){var _5k=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_5k)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _66=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_66);}
catch(e){_0.err_msg='&err_msg='+e+" - "+e.description;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_6B=((_0.syncDelay>0)||(_0.syncDelay==0));if(_6B&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1a=_0.prevData;}
else{_1a=HValueManager.toXML();_0.prevData=_1a;}
if(""!=_1a||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1a};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_3,_l){this.values[_3]=_l;},set:function(_3,_4){this.values[_3].set(_4);},s:function(_3,_4){this.values[_3].s(_4);},del:function(_3){var _4L=this.values[_3];var _6A=_4L.views;for(var _09=0;_09<_6A.length;_09++){var _6t=_6A[_09];_6t.valueObj=new HDummyValue(0,_4L.value);}
this.values[_3]=null;},changed:function(_1O){if(this.isGetting==false){if(this.tosync.indexOf(_1O.id)==-1){this.tosync.push(_1O.id);}
var _L=HTransporter;if(!_L.pollMode){clearTimeout(_L.req_timeout);_L.req_timeout=setTimeout('HTransporter.sync();',_L.syncDelay);}}},toXML:function(){var _4p='&HSyncData=';if(!this.isSending){this.isSending=true;var _6l=this.tosync.length;if(_6l==0){this.isSending=false;return'';}
var _4E=[],_0Y;for(_0Y=0;_0Y<_6l;_0Y++){var _1M=this.tosync.shift();var _6m=this.values[_1M];_4E.push(_6m.toXML(_0Y));}
var _6n=_4E.join('');_4p+='<hsyncvalues version="8118">'+_6n+'</hsyncvalues>';this.isSending=false;}
return _4p;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_3,_4){this.id=_3;this.type='[HValue]';this.value=_4;this.views=[];HValueManager.add(_3,this);},set:function(_4){if(_4!=this.value){this.value=_4;HValueManager.changed(this);this.refresh();}},s:function(_4){this.value=_4;this.refresh();},get:function(){return this.value;},bind:function(_F){if(_F===undefined){throw("HValueBindError: _F is undefined!");}
this.views.push(_F);_F.setValueObj(this);},unbind:function(_F){for(var _09=0;_09<this.views.length;_09++){var _6v=this.views[_09];if(_6v===_F){this.views.splice(_09);return;}}},release:function(_F){return this.unbind(_F);},refresh:function(){for(var _09=0;_09<this.views.length;_09++){var _F=this.views[_09];if(_F.value!=this.value){if(!_F._valueIsBeingSet){_F._valueIsBeingSet=true;_F.setValue(this.value);_F._valueIsBeingSet=false;}}}},toXML:function(_0Y){var _1M=this.id.toString();var _Z=this.value;var _0p=(typeof _Z).slice(0,1);var _0A;if(_0p=='s'){_0A=_Z.toString();_0A=SHA.str2Base64(_0A);}
else if(_0p=='n'){if(Math.ceil(_Z)===Math.floor(_Z)===_Z){_0p='i';_0A=parseInt(_Z,10).toString();}
else{_0p='f';_0A=parseFloat(_Z).toString();}}
else if(_0p=='b'){if(_Z){_0A='1';}
else{_0A='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1M);console.log('  syncjstype:',_0p);console.log('  typeof:',(typeof _Z));console.log('  syncvalue:',_Z);}}
catch(e){alert('value error, syncid:'+_1M+' syncjstype:'+_0p+' typeof:'+(typeof _Z)+' syncvalue:'+_Z);}
return'';}
return'<'+_0p+' id="'+_1M+'">'+_0A+'</'+_0p+'>';}});JSLoader=Base.extend({constructor:function(_6y){this._1D=[];this.uri=_6y;this._3e=null;},_5T:function(_4u){eval(_4u.responseText);},load:function(_1C){if(jsLoader._1D.indexOf(_1C)!=-1){return;}
req_args={onSuccess:function(resp){jsLoader._5T(resp);},onFailure:function(resp){window.status="failed to load js: "+jsLoader._21;},method:'get',asynchronous:false};this._3e=new Ajax.Request(this.uri+_1C+'.js',req_args);this._1D.push(_1C);}});LOAD("jsLoader = new JSLoader('/H/js/');");HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _0D=arguments;if(_0D.length===0){this._1l();}
else if(_0D.length==2){this._3A(_0D[0],_0D[1]);}
else if(_0D.length==1){this._1m(_0D[0]);}
else{throw"Invalid number of arguments.";}},_1l:function(){this.x=null;this.y=null;},_3A:function(x,y){this.x=x;this.y=y;},_1m:function(_e){this.x=_e.x;this.y=_e.y;},set:function(){var _0D=arguments;if(_0D.length===0){this._1l();}
else if(_0D.length==2){this._3A(_0D[0],_0D[1]);}
else if(_0D.length==1){this._1m(_0D[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_e){_0D=arguments;if((_0D.length==1)&&(_0D[0].type==this.type)){_e=_0D[0];return new HPoint((this.x+_e.x),(this.y+_e.y));}
else if(_0D.length==2){return new HPoint((this.x+_0D[0]),(this.y+_0D[1]));}else{return new HPoint(0,0);}},subtract:function(){_0D=arguments;if((_0D.length==1)&&(_0D[0].type==this.type)){_e=_0D[0];return new HPoint(this.x-_e.x,this.y-_e.y);}
else if(_0D.length==2){return new HPoint(this.x-_0D[0],this.y-_0D[1]);}else{return new HPoint(0,0);}},equals:function(_e){return(this.x==_e.x&&this.y==_e.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _0D=arguments;if(_0D.length===0){this._1l();}else if(_0D.length==4){this._3z(_0D[0],_0D[1],_0D[2],_0D[3]);}
else if(_0D.length==2){this._1m(_0D[0],_0D[1]);}
else if(_0D.length==1){this._3y(_0D[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1l:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_3z:function(_05,_0B,_1J,_1j){this.top=_0B;this.left=_05;this.bottom=_1j;this.right=_1J;},_1m:function(_45,_4v){this.top=_45.y;this.left=_45.x;this.bottom=_4v.y;this.right=_4v.x;},_3y:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _0D=arguments;if(_0D.length===0){this._1l();}else if(_0D.length==4){this._3z(_0D[0],_0D[1],_0D[2],_0D[3]);}
else if(_0D.length==2){this._1m(_0D[0],_0D[1]);}
else if(_0D.length==1){this._3y(_0D[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_05){this.left=_05;this.updateSecondaryValues();},setRight:function(_1J){this.right=_1J;this.updateSecondaryValues();},setTop:function(_0B){this.top=_0B;this.updateSecondaryValues();},setBottom:function(_1j){this.bottom=_1j;this.updateSecondaryValues();},setLeftTop:function(_e){this.left=_e.x;this.top=_e.y;this.updateSecondaryValues();},setLeftBottom:function(_e){this.left=_e.x;this.bottom=_e.y;this.updateSecondaryValues();},setRightTop:function(_e){this.right=_e.x;this.top=_e.y;this.updateSecondaryValues();},setRightBottom:function(_e){this.right=_e.x;this.bottom=_e.y;this.updateSecondaryValues();},setWidth:function(_m){this.right=this.left+_m;this.updateSecondaryValues();},setHeight:function(_y){this.bottom=this.top+_y;this.updateSecondaryValues();},setSize:function(){var _0D=arguments;if(_0D.length===2){_m=_0D[0];_y=_0D[1];}
else if(_0D.length===1){_m=_0D.x;_y=_0D.y;}
this.right=this.left+_m;this.bottom=this.top+_y;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_l){if(_l instanceof HPoint){return this._5e(_l);}
else if(_l instanceof HRect){return this._5f(_l);}
else{throw"Wrong argument type.";}},_5e:function(_e){return(_e.x>=this.left&&_e.x<=this.right&&_e.y>=this.top&&_e.y<=this.bottom);},_5f:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _0D=arguments;if(_0D.length===1){this._5J(_0D[0]);}else if(_0D.length==2){this._3W(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5J:function(_e){this._3W(_e.x,_e.y);},_3W:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _0D=arguments;if(_0D.length===1){this._5R(_0D[0]);}else if(_0D.length==2){this._4g(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5R:function(_e){this._4g(_e.x,_e.y);},_4g:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _0D=arguments;if(_0D.length===1){this._5S(_0D[0]);}else if(_0D.length==2){this._4h(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5S:function(_e){this._4h(_e.x,_e.y);},_4h:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_l){},unbind:function(_l){}});HDefaultApplicationInterval=20;HSystemTickerInterval=10;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _j=0;_j<this.apps.length;_j++){if(this.apps[_j]){if(!this.busyApps[_j]){if((this.ticks%this.appPriorities[_j])==0){this.appTimers[_j]=setTimeout('if (HSystem.apps['+_j+']) {HSystem.apps['+_j+']._4A();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._7D=setTimeout('HSystem.ticker();',HSystemTickerInterval);},addApp:function(_0O,_0f){if(this.freeAppIds.length>1024){var _j=this.freeAppIds.shift();this.apps[_j]=_0O;}else{this.apps.push(_0O);var _j=this.apps.length-1;}
_0O.parent=this;_0O.parents=[this];_0O.appId=_j;this.startApp(_j,_0f);return _j;},startApp:function(_j,_0f){if(_0f===undefined){_0f=this.defaultInterval;}
this.appPriorities[_j]=_0f;this.busyApps[_j]=false;},stopApp:function(_j){this.busyApps[_j]=true;},reniceApp:function(_j,_0f){this.appPriorities[_j]=_0f;},killApp:function(_j,_5w){if(!_5w){var _6f=new Date().getTime();while(this.busyApps[_j]==true){if(new Date().getTime()>_6f+this.maxAppRunTime){break;}}}
this.busyApps[_j]=true;this.apps[_j].destroyAllViews();delete this.apps[_j];this.apps[_j]=null;this.freeAppIds.push(_j);},views:[],_2O:[],addView:function(_h){var _2f;if(this._2O.length==0){_2f=this.views.length;this.views.push(_h);}
else{_2f=this._2O.pop();this.views[_2f]=_h;}
return _2f;},delView:function(_i){this.views[_i]=null;this._2O.push(_i);},activeWindowId:0,windowFocus:function(_h){var _4Z=this.activeWindowId,_2q=this.views,_i=_h.viewId;if(_4Z!=0){_2q[_4Z].windowBlur();}
this.activeWindowId=_i;_h.bringToFront();_h.windowFocus();}});LOAD('HSystem.ticker();');HApplication=HClass.extend({componentBehaviour:['app'],constructor:function(_0f){this.type='[HApplication]';this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_0f);},buildParents:function(_i){var _h=HSystem.views[_i];_h.parent=this;_h.parents=[];for(var _0J=0;_0J<this.parents.length;_0J++){_h.parents.push(this.parents[_0J]);}
_h.parents.push(this);},addView:function(_h){var _i=HSystem.addView(_h);this.views.push(_i);this.buildParents(_i);this.viewsZOrder.push(_i);return _i;},removeView:function(_i){HSystem.views[_i].remove();},destroyView:function(_i){HSystem.views[_i].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){var i,_i;for(i=0;i<this.views.length;i++){_i=this.views[i];HSystem.views[_i].die();}},_5Y:function(){var i,_i;for(i=0;i<this.views.length;i++){_i=this.views[i];HSystem.views[i].onIdle();}},_4A:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._5Y();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HNoComponentCSS=[];HThemeHasIE6GifsInsteadOfPng=[];HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2n={};this._1X={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_R){this.themePath=_R;},_5s:function(_n){console.log("ERROR: Template Not Found: '"+_n+"' ");},_5r:function(_n){console.log("ERROR: Template Failure: '"+_n+"' ");},_5q:function(_n){console.log("ERROR: Template Exception: '"+_n+"' ");},fetch:function(_n,_0G){var _1H;if(!_0G){var _0G='text/html; charset=UTF-8';}
var _3e=new Ajax.Request(_n,{method:'GET',onSuccess:function(_6H){_1H=_6H.responseText;},on404:function(){HThemeManager._5s(_n);},onFailure:function(){HThemeManager._5r(_n);},onException:function(){HThemeManager._5q(_n);},asynchronous:false,contentType:_0G});_3e.onStateChange();return _1H;},getThemeGfxPath:function(){var _g=this._1p[0],_p=this._1p[1],_0y=this._1p[2],_x=this._1p[3],_0C=this._0C(_g,_p,_0y,_x);return this._I(_0C,'gfx');},getCssFilePath:function(_0c){var _g=this._1p[0];if((HThemeHasIE6GifsInsteadOfPng.indexOf(_g)!=-1)&&ELEM._10){return"url('"+this._I(this.getThemeGfxPath(),_0c.replace('.png','-ie6.gif'))+"')";}
else{return"url('"+this._I(this.getThemeGfxPath(),_0c)+"')";}},loadCSS:function(_n){var _0G='text/css';var _0H=this.fetch(_n,_0G);if(!_0H||_0H==""){return;}
_0H=this._3s(_0H);var _07,_4D,_3L;if(ELEM._27){_07=document.createStyleSheet();_07.cssText=_0H;}
else{_07=document.createElement("style");_07.type=_0G;_07.media="all";_3L=document.getElementsByTagName('head')[0];_3L.appendChild(_07);if(navigator.userAgent.indexOf('KHTML')!=-1){var _5j=document.createTextNode(_0H);_07.appendChild(_5j);}
else{_07.innerHTML=_0H;}}},_51:function(_C){if(_C[_C.length-1]!='/'){_C+='/';}
return _C;},_I:function(_6g,_6h){return this._51(_6g)+_6h;},_0C:function(_g,_p,_0y,_x){var _R=_0y;if(_0y===null){_R=this.themePath;}
if(HThemeMode==0){if(_x){_R=this._I(_R,_x);}
if(_0y===null){_R=this._I(_R,_p);_R=this._I(_R,'themes');}
_R=this._I(_R,_g);}
else if(HThemeMode==1){_R=this._I(_R,_g);}
return _R;},_1Z:function(_g,_p,_0y,_x){this._1p=[_g,_p,_0y,_x];var _5h=this._0C(_g,_p,_0y,_x);var _5i=this._I('css',_p+'.css');var _1Z=this._I(_5h,_5i);return _1Z;},_32:function(_g,_p,_0y,_x){var _5D=this._0C(_g,_p,_0y,_x);var _5E=this._I('html',_p+'.html');var _5F=this._I(_5D,_5E);return _5F;},loadMarkup:function(_g,_p,_0y,_x){if(!this._2n[_g]){this._2n[_g]={};}
var _v=this._2n[_g][_p];if(null===_v||undefined===_v){var _32=this._32(_g,_p,_0y,_x);_v=this.fetch(_32);if(null===_v||undefined===_v){_v="";}
this._2n[_g][_p]=_v;}
return _v;},getMarkup:function(_g,_p,_0y,_x){if(!this._1X[_g]){var _5b=this._1Z(_g,'common',_0y,null);this._1X[_g]={};this.loadCSS(_5b);}
if(HNoComponentCSS.indexOf(_g)==-1){if(!this._1X[_g][_p]){var _5c=this._1Z(_g,_p,_0y,_x);this._1X[_g][_p]=true;this.loadCSS(_5c);}}
return this.loadMarkup(_g,_p,_0y,_x);},_1k:function(_g,_p,_0y,_x){var _0C=this._0C(_g,_p,_0y,_x);var _n=this._I(_0C,'gfx');return _n;},_5d:function(_g,_p,_0y,_x,_0c){if((HThemeHasIE6GifsInsteadOfPng.indexOf(_g)!=-1)&&ELEM._10){return this._I(this._1k(_g,_p,_0y,_x),_0c.replace('.png','-ie6.gif'));}
return this._I(this._1k(_g,_p,_0y,_x),_0c);},getThemeGfxFile:function(_0c){return this.getThemeGfxPath()+_0c;},setTheme:function(_4K){this.currentTheme=_4K;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_0N:new RegExp(/#\{([^\}]*)\}/),_3s:function(_1q){while(this._0N.test(_1q)){_1q=_1q.replace(this._0N,eval(RegExp.$1));}
return _1q;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _0w=this.markup;while(HMarkupView._3q.test(_0w)){_0w=_0w.replace(HMarkupView._3q,this.evalMarkupVariable(RegExp.$1,true));}
while(HMarkupView._0N.test(_0w)){_0w=_0w.replace(HMarkupView._0N,this.evalMarkupVariable(RegExp.$1));}
this.markup=_0w;},evalMarkupVariable:function(_6j,_78){try{var _ID=this.elemId.toString(),_WIDTH=this.rect.width,_HEIGHT=this.rect.height,_1H=eval(_6j);if(_78){return'';}
if(_1H===undefined){return'';}
else{return _1H;}}
catch(e){return'';}},toggleCSSClass:function(_0b,_1o,_4w){if(_0b){var _3J=ELEM.hasClassName(_0b,_1o);if(_4w){if(!_3J){ELEM.addClassName(_0b,_1o);}}
else{if(_3J){ELEM.removeClassName(_0b,_1o);}}}}},{_0N:new RegExp(/#\{([^\}]*)\}/),_3q:new RegExp(/\$\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,componentBehaviour:['view'],constructor:function(_1,_o){if(this.theme===undefined){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;}
else{this.preserveTheme=true;}
this.optimizeWidthOnRefresh=true;this.parent=_o;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.viewsZOrder=[];this._5g();this.setRect(_1);this.isHidden=true;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this._3t=_1.left;this._3u=_1.top;this._0V=[];if(!this.isinherited){this.draw();this.show();}},setFlexRight:function(_8,_V){if(_8===undefined){_8=true;}
this.flexRight=_8;if(_V===undefined){_V=0;}
this.flexRightOffset=_V;},setFlexLeft:function(_8,_V){if(_8===undefined){_8=true;}
this.flexLeft=_8;if(_V!==undefined){this.rect.setLeft(_V);}},setFlexTop:function(_8,_V){if(_8===undefined){_8=true;}
this.flexTop=_8;if(_V!==undefined){this.rect.setTop(_V);}},setFlexBottom:function(_8,_V){if(_8===undefined){_8=true;}
this.flexBottom=_8;if(_V===undefined){_V=0;}
this.flexBottomOffset=_V;},setAbsolute:function(_8){if(_8===undefined){_8=true;}
this.isAbsolute=_8;},setRelative:function(_8){if(_8===undefined){_8=true;}
this.isAbsolute=(!_8);},getThemeGfxPath:function(){if(this.preserveTheme){_g=this.theme;}else{_g=HThemeManager.currentTheme;}
return HThemeManager._1k(_g,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0c){if(this.preserveTheme){_g=this.theme;}else{_g=HThemeManager.currentTheme;}
return HThemeManager._5d(_g,this.componentName,this.themePath,this.packageName,_0c);},_49:function(_15){this.elemId=ELEM.make(_15,'div');},_6b:function(_52){var _1Y='display:none;overflow:hidden;visibility:hidden;';if(this.isAbsolute){_1Y+='position:absolute;';}else{_1Y+='position:relative;';}
_1Y+=_52;ELEM.setCSS(this.elemId,_1Y);},_2Q:function(){var _15;if(this.parent.elemId===undefined){_15=0;}
else if(this.parent.markupElemIds&&this.parent.markupElemIds['subview']){_15=this.parent.markupElemIds['subview'];}
else{_15=this.parent.elemId;}
return _15;},_5g:function(){if(!this.elemId){this._49(this._2Q());this._6b('');if(this.preserveTheme){ELEM.addClassName(this.elemId,this.theme);}
else{ELEM.addClassName(this.elemId,HThemeManager.currentTheme);}}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
this.drawn=true;var _9=this.elemId;var _1=this.rect;ELEM.setStyle(_9,'left',this.flexLeft?(_1.left+'px'):'auto',true);ELEM.setStyle(_9,'top',this.flexTop?(_1.top+'px'):'auto',true);ELEM.setStyle(_9,'right',this.flexRight?(this.flexRightOffset+'px'):'auto',true);ELEM.setStyle(_9,'bottom',this.flexBottom?(this.flexBottomOffset+'px'):'auto',true);ELEM.setStyle(_9,'width',(this.flexLeft&&this.flexRight)?'auto':(_1.width+'px'),true);ELEM.setStyle(_9,'height',(this.flexTop&&this.flexBottom)?'auto':(_1.height+'px'),true);if(this.flexLeft&&this.flexRight){ELEM.setStyle(_9,'min-width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){ELEM.setStyle(_9,'min-height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){ELEM.setStyle(_9,'visibility','inherit',true);}
ELEM.setStyle(_9,'display','block',true);this._4R();if(this._3t!=_1.left||this._3u!=_1.top){this.invalidatePositionCache();this._3t=_1.left;this._3u=_1.top;}},_4R:function(){ELEM.setStyle(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this.viewId));},_2p:function(){var _2q=this.parent.viewsZOrder;for(var i=0;i<_2q.length;i++){ELEM.setStyle(HSystem.views[_2q[i]].elemId,'z-index',i);}},draw:function(){this.drawRect();},_46:function(){var _g;if(this.preserveTheme){_g=this.theme;}
else{_g=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_g,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){ELEM.setStyle(this.elemId,'display','none',true);this._46();this.bindMarkupVariables();ELEM.setHTML(this.elemId,this.markup);this.markupElemIds={};var _4q=['bg','label','state','control','value','subview'],i=0;for(;i<_4q.length;i++){var _0e=_4q[i],_3E=_0e+this.elemId,_5C=' id="'+_3E+'"';if(this.markup.indexOf(_5C)!=-1){this.markupElemIds[_0e]=this.bindDomElement(_3E);}}
ELEM.setStyle(this.elemId,'display','block',true);},setHTML:function(_1z){ELEM.setHTML(this.elemId,_1z);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_0j,_4,_2B){if(!this.elemId){return;}
ELEM.setStyle(this.elemId,_0j,_4,_2B);},style:function(_0j){if(!this.elemId){return;}
return ELEM.getStyle(this.elemId,_0j);},setStyleForPart:function(_0e,_0j,_4,_2B){if(!this.markupElemIds[_0e]){return;}
ELEM.setStyle(this.markupElemIds[_0e],_0j,_4,_2B);},styleForPart:function(_0e,_0j){if(!this.markupElemIds[_0e]){return;}
ELEM.getStyle(this.markupElemIds[_0e],_0j);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){var _6D=this.parent.viewsZOrder.indexOf(this.viewId),_6C=this.parent.views.indexOf(this.viewId);this.parent.views.splice(_6C,1);HSystem.delView(this.viewId);this.parent.viewsZOrder.splice(_6D,1);this._2p();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].die();}
this.remove();for(var i=0;i<this._0V.length;i++){ELEM.del(this._0V[i]);}
this._0V=[];ELEM.del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].onIdle();}},buildParents:function(_i){var _h=HSystem.views[_i];_h.parent=this;_h.parents=[];for(var _0J=0;_0J<this.parents.length;_0J++){_h.parents.push(this.parents[_0J]);}
_h.parents.push(this);},addView:function(_h){var _i=HSystem.addView(_h);this.views.push(_i);this.buildParents(_i);this.viewsZOrder.push(_i);return _i;},removeView:function(_i){HSystem.views[_i].remove();},destroyView:function(_i){HSystem.views[_i].die();},bounds:function(){var _0E=new HRect(this.rect);_0E.right-=_0E.left;_0E.left=0;_0E.bottom-=_0E.top;_0E.top=0;return _0E;},resizeBy:function(_2T,_1Q){var _1=this.rect;_1.right+=_2T;_1.bottom+=_1Q;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_m,_y){var _1=this.rect;_1.right=_1.left+_m;_1.bottom=_1.top+_y;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_2T,_1Q){this.rect.offsetBy(_2T,_1Q);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _z=this.zIndex();this.parent.viewsZOrder.splice(_z,1);this.parent.viewsZOrder.push(this.viewId);this._2p();},sendToBack:function(){if(!this.parent){return;}
var _z=this.zIndex();this.parent.viewsZOrder.splice(_z,1);this.parent.viewsZOrder.splice(0,0,this.viewId);this._2p();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this.viewId);},stringWidth:function(_19,_28,_9){if(_28!==undefined&&_28!=null){_19=_19.substring(0,_28);}
if(_9===undefined||_9==null){_9=this.elemId;}
var _0K=ELEM.make(_9);ELEM.setCSS(_0K,"visibility:hidden;position:absolute;white-space:nowrap;");ELEM.setHTML(_0K,_19);var _m=0,_y=0;if(ELEM._10||ELEM._7a||ELEM._7b){_m=parseInt(ELEM.get(_0K).offsetWidth,10);if(arguments[3]){_y=parseInt(ELEM.get(_0K).offsetHeight,10);}}else{_m=parseInt(ELEM.get(_0K).clientWidth,10);if(ELEM._79){_m+=1;}
if(arguments[3]){_y=parseInt(ELEM.get(_0K).clientHeight,10);}}
ELEM.del(_0K);if(arguments[3]){return[_m,_y];}else{return _m;}},pageX:function(){var _7=0;var _6=this;while(_6){if(_6.elemId&&_6.rect){_7+=ELEM.get(_6.elemId).offsetLeft;_7-=ELEM.get(_6.elemId).scrollLeft;}
if(_6.markupElemIds&&_6.markupElemIds.subview){_7+=ELEM.get(_6.markupElemIds.subview).offsetLeft;_7-=ELEM.get(_6.markupElemIds.subview).scrollLeft;}
_6=_6.parent;}
return _7;},pageY:function(){var _c=0;var _6=this;while(_6){if(_6.elemId&&_6.rect){_c+=ELEM.get(_6.elemId).offsetTop;_c-=ELEM.get(_6.elemId).scrollTop;}
if(_6.markupElemIds&&_6.markupElemIds.subview){_c+=ELEM.get(_6.markupElemIds.subview).offsetTop;_c-=ELEM.get(_6.markupElemIds.subview).scrollTop;}
_6=_6.parent;}
return _c;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].invalidatePositionCache();}},bindDomElement:function(_3D){var _2A=ELEM.bindId(_3D);if(_2A){this._0V.push(_2A);}
return _2A;},unbindDomElement:function(_0b){var _3S=this._0V.indexOf(_0b);if(_3S>-1){ELEM.del(_0b);this._0V.splice(_3S,1);}},animateTo:function(_l,_0t,_0l){if(_l instanceof HPoint){var _1=new HRect(_l,_l);_1.setSize(this.rect.width,this.rect.height);this._2w(_1,_0t);}
else if(_l instanceof HRect){this._2w(_l,_0t);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._1U){window.clearInterval(this._1U);this._1U=null;var _05=parseInt(this.style('left'),10),_0B=parseInt(this.style('top'),10),_m=parseInt(this.style('width'),10),_y=parseInt(this.style('height'),10);this.rect.set(_05,_0B,_05+_m,_0B+_y);this.drawRect();if(this._3o){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_2w:function(_1,_0t,_0l){if(null===_0t||undefined===_0t){_0t=500;}
if(null===_0l||undefined===_0l||_0l<1){_0l=50;}
if(!this._1U){this._3o=false;this.onAnimationStart();var _6e=new Date().getTime();var _k=this;this._1U=window.setInterval(function(){_k._6K({startTime:_6e,duration:_0t,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_k.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_k.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_k.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_k.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0l));}},_6K:function(_l){var _4M=new Date().getTime();if(_4M<_l.startTime+_l.duration){var _57=_4M-_l.startTime;for(var i=0;i<_l.props.length;i++){var _2P=_l.props[i].from;var _4O=_l.props[i].to;if(_2P!=_4O){var _64=_l.transition(_57,_2P,(_4O-_2P),_l.duration);this.setStyle(_l.props[i].prop,_64+_l.props[i].unit);}}}else{for(var i=0;i<_l.props.length;i++){this.setStyle(_l.props[i].prop,_l.props[i].to+_l.props[i].unit);}
this._3o=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({componentBehaviour:['view','control'],refreshOnValueChange:true,refreshOnLabelChange:true,constructor:function(_1,_b,_2){if(!_2){_2={};}
var options=new(HComponentDefaults.extend(_2));this.options=options;if(this.isinherited){this.base(_1,_b);}
else{this.isinherited=true;this.base(_1,_b);this.isinherited=false;}
var _J=options.label;this.setLabel(_J);var _1v=options.events;this.setEvents(_1v);this.type='[HControl]';if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _5K=(_2.minValue||_2.maxValue);if(_5K){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(options.visible){this.show();}
else{this.hide();}
if(!this.isinherited){this.draw();}},setAction:function(_3m){this.action=_3m;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
EVENT.unreg(this);this.base();},setLabel:function(_J){this.label=_J;this.options.label=_J;this.refresh();},setEnabled:function(_8){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].setEnabled(_8);}
if(this.enabled===_8){return;}
this.enabled=_8;if(_8){EVENT.reg(this,this.events);}
else{EVENT.unreg(this);}
this.toggleCSSClass(this.elemId,HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(this.elemId,HControl.CSS_DISABLED,!this.enabled);},setValue:function(_4){if(_4===undefined){return;}
if(!this.valueObj){return;}
if(_4!==this.value){this.value=_4;this.valueObj.set(this.value);this.refresh();}},setValueObj:function(_2s){this.valueObj=_2s;this.setValue(_2s.value);},setValueRange:function(_4,_2c,_2b){this.minValue=_2c;this.maxValue=_2b;_4=(_4<_2c)?_2c:_4;_4=(_4>_2b)?_2b:_4;this.setValue(_4);this.refresh();},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}},refresh:function(){this.base();if(this.drawn){if(this.refreshOnValueChange){this.refreshValue();}
if(this.refreshOnLabelChange){this.refreshLabel();}}},setEvents:function(_1v){if(!this.events){var _5t=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,textEnter:false});this.events=new _5t;}
if(_1v){this.events.extend(_1v);}
this.events.ctrl=this;EVENT.focusOptions[this.elemId]=this.events;var _4c=this.events.mouseMove;var _35=EVENT.coordListeners.indexOf(this.elemId);if(_4c&&(_35==-1)){EVENT.coordListeners.push(this.elemId);}else if((!_4c)&&(_35!=-1)){EVENT.coordListeners.splice(_35,1);}
this.isDragged=false;},setMouseMove:function(_8){this.events.mouseMove=_8;this.setEvents();},setMouseDown:function(_8){this.events.mouseDown=_8;this.setEvents();},setMouseUp:function(_8){this.events.mouseUp=_8;this.setEvents();},setMouseWheel:function(_8){this.events.mouseWheel=_8;this.setEvents();},setDraggable:function(_8){this.events.draggable=_8;this.setEvents();},setDroppable:function(_8){this.events.droppable=_8;this.setEvents();},setKeyDown:function(_8){this.events.keyDown=_8;this.setEvents();},setKeyUp:function(_8){this.events.keyUp=_8;this.setEvents();},setTextEnter:function(_8){this.events.textEnter=_8;this.setEvents();},textEnter:function(){},focus:function(){},blur:function(){},gainedActiveStatus:function(_2Z){},_5x:function(_2Z){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_2Z);},lostActiveStatus:function(_B){},_5M:function(_B){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_B);},mouseMove:function(_7,_c){},mouseDown:function(_7,_c,_Q){},mouseUp:function(_7,_c,_Q){},mouseWheel:function(_N){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_A){},keyUp:function(_A){},_4e:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.focus(_0);Event.stop(e);},_4d:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.owner;EVENT.blur(_0);Event.stop(e);},invalidatePositionCache:function(){this.base();EVENT.coordCacheFlush(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_3,_4){this.id=_3;this.value=_4;this.type='[HDummyValue]';},set:function(_4){this.value=_4;},get:function(){return this.value;},bind:function(_1O){},unbind:function(_1O){}});HComponentDefaults=HClass.extend({label:"Untitled",visible:true,events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HDynControl=HControl.extend({componentName:'dyncontrol',componentBehaviour:['view','control','window'],constructor:function(_1,_b,_2){if(!_2){_2={};}
var _t=HClass.extend({minSize:[24,54],maxSize:[16000,9000],resizeW:1,resizeE:1,resizeN:1,resizeS:1,resizeNW:[1,1],resizeNE:[1,1],resizeSW:[1,1],resizeSE:[1,1],noResize:false});_2=new(_t.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
if(this.isinherited){this.base(_1,_b,_2);}
else{this.isinherited=true;this.base(_1,_b,_2);this.isinherited=false;}
this.presrveTheme=true;this.setDraggable(true);this.type="[HDynControl]";this._5H();this._3U();if(!this.isinherited){this.draw();}},drawRect:function(_44,_6u){if(this.rect.width<this.options.minSize[0]){var _2K=0-(this.options.minSize[0]-this.rect.width);this.rect.setWidth(this.options.minSize[0]);if(_44){this.rect.offsetBy(_2K,0);}}
else if(this.rect.width>this.options.maxSize[0]){var _2K=0-(this.options.maxSize[0]-this.rect.width);this.rect.setWidth(this.options.maxSize[0]);if(_44){this.rect.offsetBy(_2K,0);}}
if(this.rect.height<this.options.minSize[1]){var _2H=0-(this.options.minSize[1]-this.rect.height);this.rect.setHeight(this.options.minSize[1]);if(_6u){this.rect.offsetBy(0,_2H);}}
else if(this.rect.height>this.options.maxSize[1]){var _2H=0-(this.options.maxSize[1]-this.rect.height);this.rect.setHeight(this.options.maxSize[1]);if(_6u){this.rect.offsetBy(0,_2H);}}
this.base();},draw:function(){var _1B=_0.drawn;this.base();this.drawRect();if(!_1B){this.drawMarkup();this.buildStructure();}},buildStructure:function(){},_22:function(_7,_c){return this._60.subtract(_7,_c);},dynResizeNW:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setLeftTop(_0.rect.leftTop.subtract(_E));_0.drawRect(1,1);_0._60.set(_7,_c);},dynResizeNE:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setRightTop(_0.rect.rightTop.subtract(_E));_0.drawRect(0,1);_0._60.set(_7,_c);},dynResizeSW:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setLeftBottom(_0.rect.leftBottom.subtract(_E));_0.drawRect(1,0);_0._60.set(_7,_c);},dynResizeSE:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setRightBottom(_0.rect.rightBottom.subtract(_E));_0.drawRect(0,0);_0._60.set(_7,_c);},dynResizeW:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setLeft(_0.rect.left-_E.x);_0.drawRect(1,0);_0._60.set(_7,_c);},dynResizeE:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setRight(_0.rect.right-_E.x);_0.drawRect(0,0);_0._60.set(_7,_c);},dynResizeN:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setTop(_0.rect.top-_E.y);_0.drawRect(0,1);_0._60.set(_7,_c);},dynResizeS:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.setBottom(_0.rect.bottom-_E.y);_0.drawRect(0,0);_0._60.set(_7,_c);},dynDrag:function(_0,_7,_c){var _E=_0._22(_7,_c);_0.rect.offsetTo(_0.rect.leftTop.subtract(_E));_0.drawRect(1,1);_0._60.set(_7,_c);},_5H:function(){this._W=[];var i,_0=this,_7r=0,_7q=1,_7u=2,_7t=3,_7v=4,_7o=5,_7p=6,_7s=7,_6W=8,_W=this._W;_W[_7r]=_0.dynResizeNW;_W[_7q]=_0.dynResizeNE;_W[_7u]=_0.dynResizeSW;_W[_7t]=_0.dynResizeSE;_W[_7v]=_0.dynResizeW;_W[_7o]=_0.dynResizeE;_W[_7p]=_0.dynResizeN;_W[_7s]=_0.dynResizeS;_W[_6W]=_0.dynDrag;},_3U:function(){this._1e=-1;this._1R=[];var i,_1K,_r=this.options,_1=this.rect,_65=[[0,0,_r.resizeNW[0],_r.resizeNW[1]],[_1.width-_r.resizeNE[0],0,_1.width,_r.resizeNE[1]],[0,_1.height-_r.resizeSW[1],_r.resizeSW[0],_1.height],[_1.width-_r.resizeSE[0],_1.height-_r.resizeSE[1],_1.width,_1.height],[0,_r.resizeN,_r.resizeW,_1.height-_r.resizeS],[_1.width-_r.resizeE,_r.resizeN,_1.width,_1.height-_r.resizeS],[_r.resizeW,0,_1.width-_r.resizeE,_r.resizeN],[_r.resizeW,_1.height-_r.resizeS,_1.width-_r.resizeE,_1.height],[_r.resizeW,_r.resizeN,_1.width-_r.resizeE,_1.height-_r.resizeS]];for(i=0;i!=9;i++){_1K=_65[i];this._1R.push(new HRect(_1K[0],_1K[1],_1K[2],_1K[3]));}},_5l:function(){var i,_4Y=this._6d.subtract(this.rect.left,this.rect.top),_1R=this._1R;for(i=0;i!=9;i++){if(_1R[i].contains(_4Y)){this._1e=i;return;}}},startDrag:function(_7,_c,_26){this._6d=new HPoint(_7,_c);this._60=new HPoint(_7,_c);this._7A=new HRect(this.rect);this._5l();if(this._1e==8){this.setStyle('cursor','move');}
this.bringToFront();this.doDrag(_7,_c,_26);},doDrag:function(_7,_c,_26){if(this._1e!=-1){this._W[this._1e](this,_7,_c);}},endDrag:function(_7,_c,_26){this.doDrag(_7,_c,_26);if(this._1e==8){this.setStyle('cursor','default');}
this._3U();}});