
var HClass=function(){if(arguments.length){var _3j=arguments[0];if(this==window){HClass.prototype.extend.call(_3j,arguments.callee.prototype);}else{this.extend(_3j);}}};HClass.prototype={extend:function(_0g,_4){var _1x=HClass.prototype.extend;if(arguments.length==2){var _2s=this[_0g];if((_2s instanceof Function)&&(_4 instanceof Function)&&_2s.valueOf()!=_4.valueOf()&&(/\bbase\b/).test(_4)){var _30=_4;_4=function(){var _5X=this.base;this.base=_2s;var _62=_30.apply(this,arguments);this.base=_5X;return _62;};_4.valueOf=function(){return _30;};_4.toString=function(){return String(_30);};}
return this[_0g]=_4;}else if(_0g){var _0o={toSource:null};var _4n=["toString","valueOf"];if(HClass._38){_4n.push("constructor");}
for(var i=0;(_0j=_4n[i]);i++){if(_0g[_0j]!=_0o[_0j]){_1x.call(this,_0j,_0g[_0j]);}}
for(var _0j in _0g){if(!_0o[_0j]){_1x.call(this,_0j,_0g[_0j]);}}}
return this;},base:function(){}};HClass.extend=function(_0m,_3d){var _1x=HClass.prototype.extend;if(!_0m){_0m={};}
HClass._38=true;var _0o=new this;_1x.call(_0o,_0m);var _0U=_0o.constructor;_0o.constructor=this;delete HClass._38;var _0K=function(){if(!HClass._38){_0U.apply(this,arguments);}
this.constructor=_0K;};_0K.prototype=_0o;_0K.extend=this.extend;_0K.implement=this.implement;_0K.toString=function(){return String(_0U);};_1x.call(_0K,_3d);var _33=_0U?_0K:_0o;if(_33.init instanceof Function){_33.init();}
return _33;};HClass.implement=function(_1z){if(_1z instanceof Function){_1z=_1z.prototype;}
this.prototype.extend(_1z);};var Base=HClass;if([].indexOf===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_4Z){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_4Z){return i;}}
return-1;}});}
try{if(window['console']===undefined){console={log:function(){}};}}catch(e){}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_3o=[];for(i=0;i<l;i++){_3o.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _3o.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_l,_6C){this.transport=Ajax.getTransport();if(!_6C){_6C={};}
var _r=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_r=_r.extend(_6C);this.options=new _r();this.request(_l);},request:function(_l){this.url=_l;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
try{this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _m=this;this.transport.onreadystatechange=function(){_m.onStateChange();};this.setRequestHeaders();var _51=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_51);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}}catch(e){console.log('error:',e);}},setRequestHeaders:function(){var headers={},o;if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1E=this.transport.readyState;if(_1E>1){this.respondToReadyState(_1E);}},respondToReadyState:function(_1E){if(_1E==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_1E==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});ELEMTickerInterval=10;BROWSER_TYPE={ie:false,ie6:false,ie7:false,opera:false,safari:false,firefox:false,firefox2:false};ELEM={_0U:function(){var _0=ELEM;_0._5k=false;_0._6P=[];_0._5h=null;_0._6Q=false;_0._initDone=false;_0._7b=0;_0._setStyleCount=0;_0._setStyleDiffCount=0;_0._6Z=0;_0._getStyleMissCount=0;_0._flushLoopCount=0;_0._flushLoopFlushedCount=0;_0._flushStylCount=0;_0._flushTime=0;_0._flushCounter=0;_0._3O=500;_0._timer=null;_0._12=ELEMTickerInterval;_0._flushing=false;_0._needFlush=false;_0._4u=1;_0._F=[];if(_0._5k){_0._G={_6m:[]};}else{_0._freeElemIds=[];}
_0._4y={};_0._0N={};_0._0b={};_0._0q={};_0._3E=[];_0._2H={};_0._blockElems=",ADDRESS,BLOCKQUOTE,CENTER,DIR,DIV,DL,FIELDSET,FORM,H1,H2,H3,H4,H5,H6,HR,ISINDEX,MENU,NOFRAMES,NOSCRIPT,OL,P,PRE,TABLE,UL,";},_6T:function(_3A,_v){if(!ELEM._5k){return;}
var _0=ELEM,i=0,_4M=[],_G=_0._3T(_v),_1N=_G._1N;for(;i!=_3A;i++){_4M.push(_0.make(_1N,_v));}
for(i=0;i!=_3A;i++){_0.del(_4M[i]);}},_4V:function(_6){var _2,_0,_F;_0=ELEM;_F=_0._F;_F.push(_6);_2=_F.length-1;return _2;},_73:function(_2){var _0=ELEM;_0._0N[_2]=[];_0._4y[_2]={};_0._0b[_2]=[];_0._0q[_2]={};_0._2H[_2]=false;},bindId:function(_5g){var _0=ELEM,_6=document.getElementById(_5g),_9=_0._4V(_6);_0._73(_9);return _9;},bind:function(_6){var _2,_0=ELEM;_2=_0._4V(_6);_0._73(_2);return _2;},_7h:function(_2,_6){var _0=ELEM;_0._F[_2]=_6;},get:function(_2){return ELEM._F[_2];},setHTML:function(_2,_0I){try{var _0=ELEM;if(!((typeof _0I==='string')||(typeof _0I==='number'))){return;}
_0._F[_2].innerHTML=_0I;}catch(e){}},_3T:function(_v){if(!ELEM._5k){return;}
var _0=ELEM,_G=_0._G;if(!_G[_v]){_G._6m.push(_v);_G[_v]=[];_G[_v]._1W=1;_G[_v]._1n=0;_G[_v]._1N=_0.make(_0._1N,'div');}
return _G[_v]._1N;},del:function(_2){var _0=ELEM,_6=_0._F[_2];_0.setCSS(_2,'display:none;');if(_0._5k){var _v=_6.tagName,_1N=_0._3T(_v),_G=_0._G[_v];_0.append(_2,_1N);}
var _3F=_0._3E.indexOf(_2);if(_3F!=-1){_0._3E.splice(_3F,1);}
try{_6.innerHTML='';}catch(e){}
_0.delAttr(_2,'id');_0.delAttr(_2,'ctrl');_0._73(_2);if(_0._5k){_G._1W++;_G.push(_2);}else{_0._freeElemIds.push(_2);var _5R=_6.parentNode;_5R.removeChild(_6);}},append:function(_67,_1L){var _0g,_3g,_0;_0=ELEM;_0g=_0._F[_67];_3g=_0._F[_1L];_3g.appendChild(_0g);},setCSS:function(_2,_6N){ELEM._F[_2].style.cssText=_6N;},getCSS:function(_2){return ELEM._F[_2].style.cssText;},getVisibleSize:function(_2){var _0,_6,w,h,_i,_2k,_0=ELEM,_6=_0._F[_2],w=_6.offsetWidth,h=_6.offsetHeight,_i=_6.parentNode;while(_i&&_i.nodeName.toLowerCase()!='body'){if(!_0._25){_2k=document.defaultView.getComputedStyle(_i,null).getPropertyValue('overflow');}
else{_2k=_i.currentStyle.getAttribute('overflow');}
_2k=_2k!='visible';if(w>_i.clientWidth&&_2k){w=_i.clientWidth-_6.offsetLeft;}
if(h>_i.clientHeight&&_2k){h=_i.clientHeight-_6.offsetTop;}
_6=_6.parentNode;_i=_6.parentNode;}
return[w,h];},getSize:function(_2){var _0,_6,w,h,_i,_2k,_0=ELEM,_6=_0._F[_2],w=_6.offsetWidth,h=_6.offsetHeight;return[w,h];},getScrollSize:function(_2){var _0,_6,w,h,_i,_2k,_0=ELEM,_6=_0._F[_2],w=_6.scrollWidth,h=_6.scrollHeight;return[w,h];},getVisiblePosition:function(_2){var x,y,_6,_0,_0=ELEM,x=0,y=0,_6=_0._F[_2];while(_6!==document){x+=_6.offsetLeft;y+=_6.offsetTop;x-=_6.scrollLeft;y-=_6.scrollTop;_6=_6.parentNode;if(!_6){break;}}
return[x,y];},getOpacity:function(_2){var _0,_Y,_3h,_22;_0=ELEM;_22=_0.getStyle;if(_Y=_22(_2,'-khtml-opacity')){return parseFloat(_Y);}
if(_Y=_22(_2,'-moz-opacity')){return parseFloat(_Y);}
_3h=_22(_2,'opacity',true);if(_Y=_3h||(_3h==0)){return parseFloat(_Y);}
if(_Y=(_0._F[_2].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_Y[1]){return parseFloat(_Y[1])/100;}}
return 1.0;},setOpacity:function(_2,_4){var _0=ELEM;if(_4==1&&_0._25){_0._F[_2].style.setAttribute('filter',_0.getStyle(_2,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_4<0.00001){_4=0;}
if(_0._25){_0._F[_2].style.setAttribute('filter',_0.getStyle(_2,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_4*100+')');}else{_0._F[_2].style.setProperty('opacity',_4,'');}}},getIntStyle:function(_2,_e){var _4=ELEM.getStyle(_2,_e);return parseInt(_4,10);},setBoxCoords:function(_2,_02){ELEM.setStyle(_2,'left',_02[0]+'px');ELEM.setStyle(_2,'top',_02[1]+'px');ELEM.setStyle(_2,'width',_02[2]+'px');ELEM.setStyle(_2,'height',_02[3]+'px');},getExtraWidth:function(_2){var _0n=ELEM.getIntStyle;return _0n(_2,'padding-left')+_0n(_2,'padding-right')+_0n(_2,'border-left-width')+_0n(_2,'border-right-width');},getExtraHeight:function(_2){var _0n=ELEM.getIntStyle;return _0n(_2,'padding-top')+_0n(_2,'padding-bottom')+_0n(_2,'border-top-width')+_0n(_2,'border-bottom-width');},setFPS:function(_0l){ELEM._12=1000/_0l;if(ELEM._12<ELEMTickerInterval){ELEM._12=ELEMTickerInterval;}},setSlowness:function(_4u){ELEM._4u=_4u;},setIdleDelay:function(_3O){ELEM._3O=_3O;},_71:false,flushLoop:function(_04){var _0=ELEM;_0._flushLoopCount++;if(_0._1A&&(_0._flushLoopCount%5==0)&&_0._71){iefix._01();_0._71=false;}
clearTimeout(_0._timer);if(_0._flushing){_04*=2;_0._timer=setTimeout('ELEM.flushLoop('+_04+');',_04);return;}else{if(!_0._needFlush){if(_0._1A&&_0._71){iefix._01();_0._71=false;}
_0._timer=setTimeout('ELEM.flushLoop('+_04+');',_0._3O);return;}
_04=parseInt(_0._4u*(_0._flushTime/_0._flushCounter),ELEMTickerInterval);if(_04<_0._12||!_04){_04=_0._12;}
_0._flushing=true;_0._timer=setTimeout('ELEM.flushLoop('+_04+');',_04);}
_0._flushTime-=new Date().getTime();var _2X,_1r,i,_0N;_3E=_0._3E;_2X=_3E.length;_1r=_3E.splice(0,_2X);var _5p=new Date().getTime();for(i=0;i<_2X;i++){_0._flushLoopFlushed++;var _2=_1r.pop();_0._2H[_2]=false;_0._5q(_2);_0._6U(_2);}
_0._flushCounter++;_0._flushTime+=new Date().getTime();if(_0._3E.length==0&&_0._needFlush){_0._needFlush=false;}
_0._flushing=false;},_6U:function(_2){var _0=ELEM,_0b=_0._0b[_2],_0q=_0._0q[_2],_6=_0._F[_2],_e,_0O,i,_3N=_0b.length,_1r=_0b.splice(0,_3N);for(i=0;i!=_3N;i++){_e=_1r.pop();_0O=_0q[_e];_6.setAttribute(_e,_0O);}},getAttr:function(_2,_e,_0r){var _0=ELEM,_1V=_0._0q[_2][_e],_0O;if(_1V!==undefined&&!_0r){return _1V;}
var _6=_0._F[_2];if(_6.getAttribute(_e)==null){_6[_e]='';}
_0O=_6.getAttribute(_e);_0._0q[_2][_e]=_0O;return _0O;},setAttr:function(_2,_e,_4,_0r){var _1t,_0=ELEM,_0b=_0._0b[_2],_0q=_0._0q[_2];_1t=_4!=_0.getAttr(_2,_e);if(_1t){_0q[_e]=_4;if(_0r){_0._F[_2].setAttribute(_e,_4);}
else{if(_0b.indexOf(_e)==-1){_0b.push(_e);}
if(!_0._2H[_2]){_0._3E.push(_2);_0._2H[_2]=true;_0._6K();}}}},delAttr:function(_2,_e){var _1t,_0=ELEM,_0b=_0._0b[_2],_0q=_0._0q[_2];delete _0q[_e];_0._F[_2].removeAttribute(_e);if(_0b.indexOf(_e)!=-1){_0b.splice(_0b.indexOf(_e,1));}
if(_0._2H[_2]){_0._3E.splice(_0._3E.indexOf(_2,1));_0._2H[_2]=false;_0._6K();}},hasClassName:function(_9,_0S){var _5=ELEM.get(_9);if(!_5)return;var _3H=false;var _0T=_5.className.split(' ');for(var i=0;i<_0T.length;i++){if(_0T[i]==_0S){_3H=true;}}
return _3H;},addClassName:function(_9,_0S){var _5=ELEM.get(_9);if(!_5)return;ELEM.removeClassName(_9,_0S);_5.className+=' '+_0S;},removeClassName:function(_9,_0S){var _5=ELEM.get(_9);if(!_5)return;var _32='';var _0T=_5.className.split(' ');for(var i=0;i<_0T.length;i++){if(_0T[i]!=_0S){if(i>0)_32+=' ';_32+=_0T[i];}}
_5.className=_32;},_6K:function(){var _0=ELEM;if(!_0._needFlush){_0._needFlush=true;if(!_0._flushing){clearTimeout(_0._timer);_0._timer=setTimeout('ELEM.flushLoop('+_0._12+');',_0._12);}}},printStats:function(){var _0=ELEM,i=0,_v,_6l,_1W,_1n,_2r=0;if(_0._5k){console.log('Recycler efficiency:');_G=_0._G;for(;i!=_G._6m.length;i++){_v=_G._6m[i];console.log(' tagName: '+_v);_6l=_G[_v].length;console.log('   length  : '+_6l);_1W=_G[_v]._1W;console.log('   countIn : '+_1W);_1n=_G[_v]._1n;_2r+=_1n;console.log('   countOut: '+_1n);console.log('--------------------------------');}}
console.log('================================');console.log('Flushing efficiency:');console.log('  total real time spent: '+_0._flushTime+'ms');console.log('  total times called:    '+_0._flushLoopCount);console.log('  total times flushed:   '+_0._flushCounter);console.log('  total items flushed:   '+_0._flushLoopFlushedCount);console.log('  total real style sets: '+_0._flushStylCount);console.log('================================');console.log('setStyle efficiency:');console.log('  total times called:    '+_0._setStyleCount);console.log('  total times non-cache: '+_0._setStyleDiffCount);console.log('================================');console.log('getStyle efficiency:');console.log('  total times called:    '+_0._6Z);console.log('  total times non-cache: '+_0._getStyleMissCount);console.log('================================');console.log('Summary:');if(_0._5k){console.log('  recycler saved '+(_2r)+' of '+_0._7b+' ('+Math.round(_2r/_0._7b*100)+'%) document.createElement calls');}
console.log('  style buffer saved '+(_0._setStyleDiffCount-_0._flushStylCount)+' of '+_0._setStyleDiffCount+' ('+Math.round(((_0._setStyleDiffCount-_0._flushStylCount)/_0._setStyleDiffCount)*100)+'%) non-cached DOM style sets');console.log('  style cache saved '+(_0._setStyleCount-_0._setStyleDiffCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._setStyleDiffCount)/_0._setStyleCount)*100)+'%) DOM style sets');console.log('  style cache saved '+(_0._6Z-_0._getStyleMissCount)+' of '+_0._6Z+' ('+Math.round(((_0._6Z-_0._getStyleMissCount)/_0._6Z)*100)+'%) DOM style gets');console.log('  style buffer and cache saved '+(_0._setStyleCount-_0._flushStylCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._flushStylCount)/_0._setStyleCount)*100)+'%) total DOM style sets');},setStyle:function(_2,_e,_4,_0r){var _0=ELEM,_s=_0._4y[_2],_3G=_0._F,_1t,_0N;_0._setStyleCount++;if(_s===undefined){_0._73(_2);var _s=_0._4y[_2];}
_1t=_4!==_s[_e];if(_1t){_0._setStyleDiffCount++;_s[_e]=_4;if(_0r){if(_e=='opacity'){_0.setOpacity(_2,_4);}
else{_0._25?(_3G[_2].style.setAttribute(_e.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_s[_e])):(_3G[_2].style.setProperty(_e,_s[_e],''));}
if(_0._1A){if(iefix._2o.indexOf(_e)!=-1){_0._71=true;}}}else{_2H=_0._2H;_0N=_0._0N[_2];if(_0N.indexOf(_e)==-1){_0N.push(_e);}
if(!_2H[_2]){_0._3E.push(_2);_2H[_2]=true;_0._6K();}}}},make:function(_1L,_v){if(_1L===undefined){_1L=0;}
if(_v===undefined){_v='DIV';}else{_v=_v.toUpperCase();}
var _0=ELEM,_6,_2;_0._7b++;if(_0._5k){if(_0._G[_v]){if(_0._G[_v].length!=0){_2=_0._G[_v].pop();_0._G[_v]._1n++;_6=_0._F[_2];if(_0._blockElems.indexOf(','+_v+',')!=-1){_0.setCSS(_2,'display:block;');}else{_0.setCSS(_2,'display:inline;');}
_0.append(_2,_1L);return _2;}}}
_6=document.createElement(_v);_0._F[_1L].appendChild(_6);_2=_0._4V(_6);_0._73(_2);return _2;},windowSize:function(){var _0j,_5u;_0j=(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;_5u=(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;return[_0j,_5u];},_3R:function(){var _0=ELEM,_0F,_2z;var _2N=["ELEM.getStyle=function(_2,_e,_0r){","var _0=ELEM,_s=_0._4y[_2],_1G;_0._6Z++;","if((_s[_e]===undefined)||_0r){","if(!_0r){_0._getStyleMissCount++;}","if((_e=='opacity')&&_0r){_1G=_0.getOpacity(_2);}","else{","_1G=document.defaultView.getComputedStyle(_0._F[_2],null).getPropertyValue(_e);","_53=_e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){","return $3.toUpperCase()+$4});","_1G=_0._F[_2].currentStyle[_53];","}_s[_e]=_1G;","}return _s[_e];};"];if(_0._25){_2N.splice(6,1);}else{_2N.splice(7,3);}
eval(_2N.join(''));var _2J=["ELEM._5q=function(_2){","var _0=ELEM,_0N=_0._0N[_2],_s=_0._4y[_2],_6=_0._F[_2],_1v,_43,_3v,_e,_1r,_1G;","if(!_6){return;}","_1v=_6.style;","_43=_0N.length;","_1r=_0N.splice(0,_43);","for(_3v=0;_3v!=_43;_3v++){","_e=_1r.pop();_0._flushStylCount++;","if(_e=='opacity'){_1G=_0.getOpacity(_2,_s[_e]);}else{","if(_0._1A){if(iefix._2o.indexOf(_e)!=-1){_0._71=true;}}try{_1v.setAttribute(_e.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_s[_e]);}catch(e){}}}};","_1v.setProperty(_e,_s[_e],'');}}};"];if(_0._25){_2J.pop();}else{_2J.splice(9,1);}
eval(_2J.join(''));_0.bind(document.body);if(_0._5k){_0._1N=_0.make(0,'div');_0.setCSS(_0._1N,"display:none;visibility:hidden;");_0.setAttr(_0._1N,'id','trashcan_'+_0._1N);}
_0._timer=setTimeout('ELEM.flushLoop('+_0._12+')',_0._12);if(!_0._6P){return;}
while(_0._6P.length!=0){_0F=_0._6P.shift();if(typeof _0F=='string'){_2z=eval(_0F);if(typeof _2z=='string'){_0._6P.push(_2z);}}}
_0._initDone=true;},_6x:function(){_0=ELEM;_0._25=(document.all&&navigator.userAgent.indexOf("Opera")==-1)?true:false;_0._1A=(_0._25&&navigator.userAgent.indexOf("MSIE 6")!=-1)?true:false;_0._76=(_0._25&&navigator.userAgent.indexOf("MSIE 7")!=-1)?true:false;_0._78=(navigator.userAgent.indexOf("KHTML")!=-1)?true:false;_0._is_ff=(navigator.userAgent.indexOf("Firefox")!=-1)?true:false;_0._75=(navigator.userAgent.indexOf("Firefox/3.")!=-1)?true:false;_0._77=(navigator.userAgent.indexOf("Opera")!=-1)?true:false;BROWSER_TYPE={opera:_0._77,safari:_0._78,firefox:_0._is_ff,ie:_0._25,ie6:_0._1A,ie7:_0._76,firefox3:_0._75};_0._5j();},_5i:function(_0F){var _0=ELEM;if(typeof _0F=='string'){if(_0._initDone==true){eval(_0F);}else{_0._6P.push(_0F);}}},_5j:function(){var _79=false;var _0=ELEM;if(_0._25){var _3P="javascript:void(0)";if(location.protocol=="https:"){_3P="src=//0";}
document.write("<scr"+"ipt id=_4T defer src="+_3P+"><\/scr"+"ipt>");var _5C=document.getElementById("_4T");_5C.onreadystatechange=function(){if(this.readyState=="complete"){ELEM._6Q=true;ELEM._3R();delete ELEM._6P;clearTimeout(ELEM._5h);delete ELEM._5h;}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(document.readyState))){_0._6Q=true;}
else if(document.body){_0._6Q=true;}
if(!_0._6Q){_0._5h=setTimeout('ELEM._5j()',ELEMTickerInterval*10);}else{_0._3R();delete _0._6P;clearTimeout(_0._5h);delete _0._5h;}}};ELEM._0U();LOAD=ELEM._5i;ELEM._6x();Event={element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}
else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(ELEM._25||ELEM._78){return(e.button==1);}
else{return(e.button==0);}},observers:false,_5K:function(_6,_0j,_1y,_1O){if(!Event.observers){Event.observers=[];}
if(_6.addEventListener){this.observers.push([_6,_0j,_1y,_1O]);_6.addEventListener(_0j,_1y,_1O);}
else if(_6.attachEvent){this.observers.push([_6,_0j,_1y,_1O]);_6.attachEvent("on"+_0j,_1y);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_6,_0j,_1y,_1O){_1O=_1O||false;Event._5K(_6,_0j,_1y,_1O);},stopObserving:function(_6,_0j,_1y,_1O){_1O=_1O||false;if(_6.removeEventListener){_6.removeEventListener(_0j,_1y,_1O);}
else if(detachEvent){_6.detachEvent("on"+_0j,_1y);}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_6&&eo[1]==_0j&&eo[2]==_1y&&eo[3]==_1O){Event.observers[i]=null;Event.observers.splice(i,1);}
else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34};if(ELEM._25){Event.observe(window,"unload",Event.unloadCache,false);}
_3B={mouseMove:false,mouseDown:false,click:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,isDragged:false,textEnter:false};EVENT={status:[false,false,0,0,[],false,false,false],button1:0,button2:1,crsrX:2,crsrY:3,keysDown:4,altKeyDown:5,ctrlKeyDown:6,shiftKeyDown:7,start:function(){var _2O,_2I,i,_0=EVENT;if(ELEM._25){_2O=document;}
else{_2O=window;}
_2I=[['mousemove',EVENT.mouseMove],['mouseup',EVENT.mouseUp],['mousedown',EVENT.mouseDown],['click',EVENT.click],['keyup',EVENT.keyUp],['keydown',EVENT.keyDown],['keypress',EVENT.keyPress],['contextmenu',EVENT.contextMenu],['resize',EVENT.resize],['mousewheel',EVENT.mouseWheel]];for(i=0;i!=_2I.length;i++){Event.observe(_2O,_2I[i][0],_2I[i][1]);}
if(window.addEventListener){window.addEventListener('DOMMouseScroll',EVENT.mouseWheel,false);}
_0.listeners=[];_0.focused=[];_0.resizeListeners=[];_0.coordListeners=[];_0.focusOptions={};_0.dragItems=[];_0.hovered=[];_0.hoverInterval=50;_0.hoverTimer=new Date().getTime();_0.topmostDroppable=null;_0.textEnterCtrls=[];_0._2A=[];_0._coordCacheFlag=true;_0._lastCoordFlushTimeout=null;_0.activeControl=null;_0._lastKeyDown=null;},coordCacheFlush:function(_9){if(_9){EVENT._2A[_9]=null;}
else{EVENT._2A=[];}},reg:function(_c,_0u){var _9,_6,_0=EVENT,_5Y;_9=_c.elemId;_6=ELEM.get(_9);if(ELEM._25){_6.setAttribute('ctrl',_c);}
else{_6.ctrl=_c;}
_0.listeners[_9]=true;_0.focused[_9]=false;for(var _5Y in _3B){if(_0u[_5Y]===undefined){_0u[_5Y]=_3B[_5Y];}}
_0.focusOptions[_9]=_0u;var _2B=_0.coordListeners.indexOf(_9);if(_0u.mouseMove){if(_2B==-1){_0.coordListeners.push(_9);}}
else if(_2B!=-1){_0.coordListeners.splice(_2B,1);}
if(_0u.textEnter){if(_0.textEnterCtrls.indexOf(_c.viewId)==-1){_0.textEnterCtrls.push(_c.viewId);}}
if(_0u.resize){if(_0.resizeListeners.indexOf(_c.viewId)==-1){_0.resizeListeners.push(_c.viewId);}}
Event.observe(_6,'mouseover',_0._4a);},unreg:function(_c){var _0=EVENT,_9,_6;if(_c===this.activeControl){_0.changeActiveControl(null);}
_9=_c.elemId;_6=ELEM.get(_9);this.listeners[_9]=false;this.focused[_9]=false;this._2A[_9]=null;var _4F=_0.textEnterCtrls.indexOf(_c.viewId);if(_4F!=-1){_0.textEnterCtrls.splice(_4F,1);}
var _4p=_0.resizeListeners.indexOf(_c.viewId);if(_4p!=-1){_0.resizeListeners.splice(_4p,1);}
Event.stopObserving(_6,'mouseover',_0._4a);},resize:function(e){var i=0,_0=EVENT,_20,_c;for(;i<_0.resizeListeners.length;i++){_20=_0.resizeListeners[i];_c=HSystem.views[_20];if(_c.onResize){_c.onResize();}}},_4a:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.focus(_0);Event.stop(e);},_49:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.blur(_0);Event.stop(e);},focus:function(_c){var _0=EVENT,_9,_6;_9=_c.elemId;_6=ELEM.get(_9);if(_0.focused[_9]==false&&_0.focusOptions[_9].isDragged==false){Event.stopObserving(_6,'mouseover',_0._4a);Event.observe(_6,'mouseout',_0._49);_0.focused[_9]=true;if(_c['focus']){_c.focus();}}},blur:function(_c){var _0=EVENT,_9,_6;_9=_c.elemId;_6=ELEM.get(_9);if(_0.focused[_9]==true&&_0.focusOptions[_9].isDragged==false){Event.stopObserving(_6,'mouseout',_0._49);Event.observe(_6,'mouseover',_0._4a);_0.focused[_9]=false;if(_c['blur']){_c.blur();}}},mouseMove:function(e){var _0=EVENT,x,y,_0W;x=Event.pointerX(e);y=Event.pointerY(e);_0.status[_0.crsrX]=x;_0.status[_0.crsrY]=y;_0W=_0.flushMouseMove(x,y);_0._7c(e);if(_0W){Event.stop(e);}},flushMouseMove:function(x,y){var _0=EVENT,x,y,_0W,i,j,_9,_c;clearTimeout(_0._lastCoordFlushTimeout);_0W=false;for(i=0;i!=_0.dragItems.length;i++){_9=_0.dragItems[i];_0.focusOptions[_9].ctrl.doDrag(x,y);_0.coordCacheFlush(_9);_0W=true;}
if(new Date().getTime()>_0.hoverTimer+_0.hoverInterval){for(i=0;i!=_0.coordListeners.length;i++){_9=_0.coordListeners[i];_c=_0.focusOptions[_9].ctrl;_c.mouseMove(x,y);}
_0._7B();var _2q;for(i=0;i!=_0.dragItems.length;i++){_2q=_0.topmostDroppable;_0.topmostDroppable=null;_9=_0.dragItems[i];_c=_0.focusOptions[_9].ctrl;var _23,_1u;for(j=0;j!=_0.hovered.length;j++){_23=_0.hovered[j];if(_23!=_9&&_0.focusOptions[_23].ctrl){_1u=_0.focusOptions[_23].ctrl;if(!_0.topmostDroppable||_1u.zIndex()>_0.topmostDroppable.zIndex()||_1u.supr===_0.topmostDroppable){if(_0.focusOptions[_1u.elemId].droppable){_0.topmostDroppable=_1u;}}}}
if(_2q!=_0.topmostDroppable){if(_2q){_2q.onHoverEnd(_c);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverStart(_c);}}}
_0.hoverTimer=new Date().getTime();}
else{_0._lastCoordFlushTimeout=setTimeout('EVENT.flushMouseMove('+x+','+y+');',_0.hoverInterval);}
return _0W;},_7B:function(){var _0=EVENT,x,y,i,_c,_6,_34,_4t,_02;_0.hovered=[];x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.listeners.length;i++){if(!_0.listeners[i]||!_0.focusOptions[i].ctrl){continue;}
_c=_0.focusOptions[i].ctrl;_6=ELEM.get(i);if(!_0._coordCacheFlag||!_0._2A[i]){_34=ELEM.getVisiblePosition(_c.elemId);_4t=ELEM.getVisibleSize(_c.elemId);_0._2A[i]=[_34[0],_34[1],_4t[0],_4t[1]];}
_02=_0._2A[i];if(x>=_02[0]&&x<=_02[0]+_02[2]&&y>=_02[1]&&y<=_02[1]+_02[3]){_0.hovered.push(i);}}},mouseDown:function(e,_U){var _0=EVENT,_2F,x,y,i,_A,_0z,_2d;_0._7c(e);_2F=false;if(_U===undefined){_U=Event.isLeftClick(e);}
if(_U){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_A=null;_0z=[];_2d=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_A=_0.focusOptions[i].ctrl;}
if((_0.focusOptions[i].draggable==true)&&_0.dragItems.indexOf(i)==-1){_0z.push(i);}
else if(_0.focusOptions[i].mouseDown==true){_2d.push(i);}}}
if(_A){_0.changeActiveControl(_A);}
for(i=0;i!=_0z.length;i++){_0.dragItems.push(_0z[i]);_0.focusOptions[_0z[i]].ctrl.startDrag(x,y);_2F=true;}
var _1J=_2d.length;for(i=0;i!=_2d.length;i++){if(_0.focusOptions[_2d[i]].ctrl.mouseDown(x,y,_U)){_1J--;}}
if(_2F){document.body.focus();_0._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if((_1J==0)&&(_0.hovered.length!=0)&&(_A&&(_A.textElemId===false))){Event.stop(e);}
return true;},click:function(e,_U){var _0=EVENT,x,y,i,_A,_2y;_0._7c(e);if(_U===undefined){_U=Event.isLeftClick(e);}
if(_U){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_A=null;_2y=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_A=_0.focusOptions[i].ctrl;}
if(_0.focusOptions[i].click==true){_2y.push(i);}}}
if(_A){_0.changeActiveControl(_A);}
var _1J=_2y.length;for(i=0;i!=_2y.length;i++){if(_0.focusOptions[_2y[i]].ctrl.click(x,y,_U)){_1J--;}}
if((_1J==0)&&(_0.hovered.length!=0)&&(_A&&(_A.textElemId===false))){Event.stop(e);}
return true;},changeActiveControl:function(_c){var _0=EVENT,_17;_17=_0.activeControl;if(_c!=_17){if(_17){_17.active=false;_17._5I(_c);}
_0.activeControl=null;if(_c){_c.active=true;_0.activeControl=_c;_c._5t(_17);}}},mouseUp:function(e){var _0=EVENT,_2E,x,y,_9,_c,i;_0._7c(e);_2E=false;_U=Event.isLeftClick(e);_0.status[_0.button1]=false;_0.status[_0.button2]=false;x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.dragItems.length;i++){_9=_0.dragItems[i];_c=_0.focusOptions[_9].ctrl;_c.endDrag(x,y);_2E=true;_0._7B();if(_0.hovered.indexOf(_9)==-1){_0.blur(_c);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverEnd(_c);_0.topmostDroppable.onDrop(_c);_0.topmostDroppable=null;}}
_0.dragItems=[];if(_2E){document.onselectstart=_0._storedOnSelectStart;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseUp==true){_0.focusOptions[i].ctrl.mouseUp(x,y,_U);}}}
return true;},keyDown:function(e){var _0=EVENT,_0h;_0._7c(e);_0h=e.keyCode;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);if(_0._lastKeyDown!=_0h){_0.activeControl.keyDown(_0h);}}
if(_0.status[_0.keysDown].indexOf(_0h)==-1){_0.status[_0.keysDown].push(_0h);}
_0._lastKeyDown=_0h;},keyUp:function(e){var _0=EVENT,_0h,_keycodeindex;_0._7c(e);_0h=e.keyCode;_0._lastKeyDown=null;for(var i=0;i!=_0.textEnterCtrls.length;i++){var _20=_0.textEnterCtrls[i],_c=HSystem.views[_20];if(_c.textEnter){_c.textEnter();}}
if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyUp==true){_0.activeControl.keyUp(_0h);}
_3W=_0.status[_0.keysDown].indexOf(_0h);if(_3W!=-1){_0.status[_0.keysDown].splice(_3W,1);}},keyPress:function(e){var _0=EVENT;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _0=EVENT,_O,i;_O=0;if(!e){e=window.event;}
if(e.wheelDelta){_O=e.wheelDelta/120;if(window.opera){_O=-_O;}}
else if(e.detail){_O=-e.detail/3;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseWheel==true){Event.stop(e);_0.focusOptions[i].ctrl.mouseWheel(_O);}}}},contextMenu:function(e){EVENT.mouseDown(e,false);Event.stop(e);},_7c:function(e){var _0=EVENT;_0.status[_0.altKeyDown]=e.altKey;_0.status[_0.ctrlKeyDown]=e.ctrlKey;_0.status[_0.shiftKeyDown]=e.shiftKey;}};LOAD('EVENT.start();');SHA={_3M:0,hexCase:function(){return SHA._3M;},setHexCase:function(_54){SHA._3M=_54;},_3q:"=",base64Pad:function(){return SHA._3q;},setBase64Pad:function(_5Q){SHA._3q=_5Q;},_3u:8,chrsz:function(){return SHA._3u;},setChrsz:function(_50){SHA._3u=_50;},hexSHA1:function(_0y){var _0=SHA;return _0._6I(_0._6M(_0._7w(_0y),_0y.length*_0._3u));},b64SHA1:function(_0y){var _0=SHA;return _0._6H(_0._6M(_0._7w(_0y),_0y.length*_0._3u));},strSHA1:function(_0y){var _0=SHA;return _0._6J(_0._6M(_0._7w(_0y),_0y.length*_0._3u));},hexHmacSHA1:function(_e,_0s){var _0=SHA;return _0._6I(_0._6L(_e,_0s));},b64HmacSHA1:function(_e,_0s){var _0=SHA;return _0._6H(_0._6L(_e,_0s));},strHmacSHA1:function(_e,_0s){var _0=SHA;return _0._6J(_0._6L(_e,_0s));},str2Base64:function(_B){var _0=SHA;return _0._6H(_0._7w(_B));},test:function(){return SHA.hexSHA1("abc")=="a9993e364706816aba3e25717850c26c9cd0d89d";},_6M:function(_7,_2W){var _0=SHA;_7[_2W>>5]|=0x80<<(24-_2W%32);_7[((_2W+64>>9)<<4)+15]=_2W;var _0j=new Array(80),_0D=1732584193,_N=-271733879,_S=-1732584194,_T=271733878,_0Y=-1009589776,i,_4f,_4g,_4h,_4i,_4j,j,_M;for(i=0;i<_7.length;i+=16){_4f=_0D;_4g=_N;_4h=_S;_4i=_T;_4j=_0Y;for(j=0;j<80;j++){if(j<16){_0j[j]=_7[i+j];}
else{_0j[j]=_0._7r(_0j[j-3]^_0j[j-8]^_0j[j-14]^_0j[j-16],1);}
_M=_0._7s(_0._7s(_0._7r(_0D,5),_0._7t(j,_N,_S,_T)),_0._7s(_0._7s(_0Y,_0j[j]),_0._7u(j)));_0Y=_T;_T=_S;_S=_0._7r(_N,30);_N=_0D;_0D=_M;}
_0D=_0._7s(_0D,_4f);_N=_0._7s(_N,_4g);_S=_0._7s(_S,_4h);_T=_0._7s(_T,_4i);_0Y=_0._7s(_0Y,_4j);}
return[_0D,_N,_S,_T,_0Y];},_7t:function(_M,_N,_S,_T){if(_M<20){return(_N&_S)|((~_N)&_T);}
if(_M<40){return _N^_S^_T;}
if(_M<60){return(_N&_S)|(_N&_T)|(_S&_T);}
return _N^_S^_T;},_7u:function(_M){return(_M<20)?1518500249:(_M<40)?1859775393:(_M<60)?-1894007588:-899497514;},_6L:function(_e,_0s){var _0=SHA,_1i=_0._7w(_e),_3V=new Array(16),_4k=new Array(16),i,_3J;if(_1i.length>16){_1i=_0._6M(_1i,_e.length*_0._3u);}
for(i=0;i<16;i++){_3V[i]=_1i[i]^0x36363636;_4k[i]=_1i[i]^0x5C5C5C5C;}
_3J=_0._6M(_3V.concat(_0._7w(_0s)),512+_0s.length*_0._3u);return _0._6M(_4k.concat(_3J),512+160);},_7s:function(_7,_b){var _44=(_7&0xFFFF)+(_b&0xFFFF),_5J=(_7>>16)+(_b>>16)+(_44>>16);return(_5J<<16)|(_44&0xFFFF);},_7r:function(_2i,_3w){return(_2i<<_3w)|(_2i>>>(32-_3w));},_7w:function(_B){var _0=SHA,_1h=[],_2Z=(1<<_0._3u)-1,_6d=_B.length*_0._3u,i;for(i=0;i<_6d;i+=_0._3u){_1h[i>>5]|=(_B.charCodeAt(i/_0._3u)&_2Z)<<(32-_0._3u-i%32);}
return _1h;},_6J:function(_1h){var _0=SHA,_B="",_2Z=(1<<_0._3u)-1,i,_2v=_1h.length*32,_4S=32-_0._3u;for(i=0;i<_2v;i+=_0._3u){_B+=String.fromCharCode((_1h[i>>5]>>>(_4S-i%32))&_2Z);}
return _B;},_6I:function(_0k){var _0=SHA,_3L=_0._3M?"0123456789ABCDEF":"0123456789abcdef",_B="",i,_2u=_0k.length*4;for(i=0;i<_2u;i++){_B+=_3L.charAt((_0k[i>>2]>>((3-i%4)*8+4))&0xF)+
_3L.charAt((_0k[i>>2]>>((3-i%4)*8))&0xF);}
return _B;},_6H:function(_0k){var _0=SHA,_1c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",_B="",i,_2u=_0k.length*4,_4B,_4C,_6C,_4N,j,_2v=_0k.length*32;for(i=0;i<_2u;i+=3){_4B=(((_0k[i>>2]>>8*(3-i%4))&0xFF)<<16);_4C=(((_0k[i+1>>2]>>8*(3-(i+1)%4))&0xFF)<<8);_6j=((_0k[i+2>>2]>>8*(3-(i+2)%4))&0xFF);_4N=(_4B|_4C|_6j);for(j=0;j<4;j++){if(i*8+j*6>_2v){_B+=_0._3q;}
else{_B+=_1c.charAt((_4N>>6*(3-j))&0x3F);}}}
return _B;}};HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporterDebug=false;HTransporter=Base.extend({constructor:null,start:function(_6s){var _0=HTransporter;_0.url_base=_6s;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_8){HTransporter.pollMode=_8;},failure:function(resp){var _5e=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_5e)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _61=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_61);}
catch(e){if(HTransporterDebug){console.log(e);console.log(e.description);}
_0.err_msg='&err_msg='+e+" - "+e.description;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_6u=((_0.syncDelay>0)||(_0.syncDelay==0));if(_6u&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1b=_0.prevData;}
else{_1b=HValueManager.toXML();_0.prevData=_1b;}
if(""!=_1b||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1b};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_2,_m){this.values[_2]=_m;},set:function(_2,_4){this.values[_2].set(_4);},s:function(_2,_4){this.values[_2].s(_4);},del:function(_2){var _4H=this.values[_2],_6t=_4H.views,_0a=0,_4I=null;for(;_0a<_6t.length;_0a++){_4I=_6t[_0a];_4I.valueObj=new HDummyValue(0,_4H.value);}
this.values[_2]=null;},changed:function(_1M){if(this.isGetting==false){if(this.tosync.indexOf(_1M.id)==-1){this.tosync.push(_1M.id);}
var _M=HTransporter;if(!_M.pollMode){clearTimeout(_M.req_timeout);_M.req_timeout=setTimeout('HTransporter.sync();',_M.syncDelay);}}},toXML:function(){var _4m='&HSyncData=';if(!this.isSending){this.isSending=true;var _6g=this.tosync.length;if(_6g==0){this.isSending=false;return'';}
var _4A=[],_10;for(_10=0;_10<_6g;_10++){var _1K=this.tosync.shift();var _6h=this.values[_1K];_4A.push(_6h.toXML(_10));}
var _6i=_4A.join('');_4m+='<hsyncvalues version="8118">'+_6i+'</hsyncvalues>';this.isSending=false;}
return _4m;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_2,_4){this.id=_2;this.type='[HValue]';this.value=_4;this.views=[];HValueManager.add(_2,this);},set:function(_4){if(_4!=this.value){this.value=_4;HValueManager.changed(this);this.refresh();}},s:function(_4){this.value=_4;this.refresh();},get:function(){return this.value;},bind:function(_E){if(_E===undefined){throw("HValueBindError: _E is undefined!");}
this.views.push(_E);_E.setValueObj(this);},unbind:function(_E){for(var _0a=0;_0a<this.views.length;_0a++){var _6p=this.views[_0a];if(_6p===_E){this.views.splice(_0a);return;}}},release:function(_E){return this.unbind(_E);},refresh:function(){for(var _0a=0;_0a<this.views.length;_0a++){var _E=this.views[_0a];if(_E.value!=this.value){if(!_E._valueIsBeingSet){_E._valueIsBeingSet=true;_E.setValue(this.value);_E._valueIsBeingSet=false;}}}},toXML:function(_10){var _1K=this.id.toString();var _Z=this.value;var _0p=(typeof _Z).slice(0,1);var _0A;if(_0p=='s'){_0A=_Z.toString();_0A=SHA.str2Base64(_0A);}
else if(_0p=='n'){if(Math.ceil(_Z)===Math.floor(_Z)===_Z){_0p='i';_0A=parseInt(_Z,10).toString();}
else{_0p='f';_0A=parseFloat(_Z).toString();}}
else if(_0p=='b'){if(_Z){_0A='1';}
else{_0A='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1K);console.log('  syncjstype:',_0p);console.log('  typeof:',(typeof _Z));console.log('  syncvalue:',_Z);}}
catch(e){alert('value error, syncid:'+_1K+' syncjstype:'+_0p+' typeof:'+(typeof _Z)+' syncvalue:'+_Z);}
return'';}
return'<'+_0p+' id="'+_1K+'">'+_0A+'</'+_0p+'>';}});JSLoader=Base.extend({constructor:function(_6r){this._1B=[];this.uri=_6r;this._3a=null;},_5N:function(_4q){eval(_4q.responseText);},load:function(_26,_5s){if((jsLoader._1B.indexOf(_26)!=-1)&&(_5s===undefined)){return;}
if(_5s){document.write('<script type="text/javascript" src="'+_26+'"><'+'/script>');}else{req_args={onSuccess:function(resp){jsLoader._5N(resp);},onFailure:function(resp){window.status="failed to load js: "+jsLoader._2C;},method:'get',asynchronous:false};var _l=this.uri+_26+'.js';this._3a=new Ajax.Request(_l,req_args);this._1B.push(_26);}}});LOAD("jsLoader = new JSLoader('/H/js/');");HValueMatrixComponentExtension={componentBehaviour:['view','control','matrix'],constructor:function(_1,_i,_6C){this.base(_1,_i,_6C);this.setValueMatrix();},setValueMatrix:function(){if(!this.parent.valueMatrix){this.parent.valueMatrix=new HValueMatrix();}
this.valueMatrixIndex=this.parent.valueMatrix.addControl(this);},click:function(){if(this.parent.valueMatrix instanceof HValueMatrix){this.parent.valueMatrix.setValue(this.valueMatrixIndex);}}};HValueMatrix=HClass.extend({constructor:function(){this.ctrls=[];this.value=-1;this.valueObj=new HDummyValue();},setValueObj:function(_4Q){this.valueObj=_4Q;this.setValue(_4Q.value);},setValue:function(_p){if(_p!=this.value){if(this.value!=-1){this.ctrls[this.value].setValue(false);}
if(_p!=-1){this.valueObj.set(_p);this.value=_p;if(_p<this.ctrls.length){this.ctrls[_p].setValue(true);}}}},addControl:function(_c){this.ctrls.push(_c);var _4c=this.ctrls.length-1;if(_c.value){this.setValue(_4c);}
return _4c;}});HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _0D=arguments;if(_0D.length===0){this._1l();}
else if(_0D.length==2){this._3z(_0D[0],_0D[1]);}
else if(_0D.length==1){this._1m(_0D[0]);}
else{throw"Invalid number of arguments.";}},_1l:function(){this.x=null;this.y=null;},_3z:function(x,y){this.x=x;this.y=y;},_1m:function(_d){this.x=_d.x;this.y=_d.y;},set:function(){var _0D=arguments;if(_0D.length===0){this._1l();}
else if(_0D.length==2){this._3z(_0D[0],_0D[1]);}
else if(_0D.length==1){this._1m(_0D[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_d){_0D=arguments;if((_0D.length==1)&&(_0D[0].type==this.type)){_d=_0D[0];return new HPoint((this.x+_d.x),(this.y+_d.y));}
else if(_0D.length==2){return new HPoint((this.x+_0D[0]),(this.y+_0D[1]));}else{return new HPoint(0,0);}},subtract:function(){_0D=arguments;if((_0D.length==1)&&(_0D[0].type==this.type)){_d=_0D[0];return new HPoint(this.x-_d.x,this.y-_d.y);}
else if(_0D.length==2){return new HPoint(this.x-_0D[0],this.y-_0D[1]);}else{return new HPoint(0,0);}},equals:function(_d){return(this.x==_d.x&&this.y==_d.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _0D=arguments;if(_0D.length===0){this._1l();}else if(_0D.length==4){this._3y(_0D[0],_0D[1],_0D[2],_0D[3]);}
else if(_0D.length==2){this._1m(_0D[0],_0D[1]);}
else if(_0D.length==1){this._3x(_0D[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1l:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_3y:function(_05,_0B,_1H,_1j){this.top=_0B;this.left=_05;this.bottom=_1j;this.right=_1H;},_1m:function(_41,_4r){this.top=_41.y;this.left=_41.x;this.bottom=_4r.y;this.right=_4r.x;},_3x:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _0D=arguments;if(_0D.length===0){this._1l();}else if(_0D.length==4){this._3y(_0D[0],_0D[1],_0D[2],_0D[3]);}
else if(_0D.length==2){this._1m(_0D[0],_0D[1]);}
else if(_0D.length==1){this._3x(_0D[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_05){this.left=_05;this.updateSecondaryValues();},setRight:function(_1H){this.right=_1H;this.updateSecondaryValues();},setTop:function(_0B){this.top=_0B;this.updateSecondaryValues();},setBottom:function(_1j){this.bottom=_1j;this.updateSecondaryValues();},setLeftTop:function(_d){this.left=_d.x;this.top=_d.y;this.updateSecondaryValues();},setLeftBottom:function(_d){this.left=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setRightTop:function(_d){this.right=_d.x;this.top=_d.y;this.updateSecondaryValues();},setRightBottom:function(_d){this.right=_d.x;this.bottom=_d.y;this.updateSecondaryValues();},setWidth:function(_q){this.right=this.left+_q;this.updateSecondaryValues();},setHeight:function(_H){this.bottom=this.top+_H;this.updateSecondaryValues();},setSize:function(){var _0D=arguments;if(_0D.length===2){_q=_0D[0];_H=_0D[1];}
else if(_0D.length===1){_q=_0D.x;_H=_0D.y;}
this.right=this.left+_q;this.bottom=this.top+_H;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_m){if(_m instanceof HPoint){return this._58(_m);}
else if(_m instanceof HRect){return this._59(_m);}
else{throw"Wrong argument type.";}},_58:function(_d){return(_d.x>=this.left&&_d.x<=this.right&&_d.y>=this.top&&_d.y<=this.bottom);},_59:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _0D=arguments;if(_0D.length===1){this._5F(_0D[0]);}else if(_0D.length==2){this._3U(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5F:function(_d){this._3U(_d.x,_d.y);},_3U:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _0D=arguments;if(_0D.length===1){this._5L(_0D[0]);}else if(_0D.length==2){this._4d(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5L:function(_d){this._4d(_d.x,_d.y);},_4d:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _0D=arguments;if(_0D.length===1){this._5M(_0D[0]);}else if(_0D.length==2){this._4e(_0D[0],_0D[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_5M:function(_d){this._4e(_d.x,_d.y);},_4e:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_m){},unbind:function(_m){}});HDefaultApplicationInterval=20;HSystemTickerInterval=10;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _j=0;_j<this.apps.length;_j++){if(this.apps[_j]){if(!this.busyApps[_j]){if((this.ticks%this.appPriorities[_j])==0){this.appTimers[_j]=setTimeout('if (HSystem.apps['+_j+']) {HSystem.apps['+_j+']._4w();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._7y=setTimeout('HSystem.ticker();',HSystemTickerInterval);},addApp:function(_0R,_06){if(this.freeAppIds.length>1024){var _j=this.freeAppIds.shift();this.apps[_j]=_0R;}else{this.apps.push(_0R);var _j=this.apps.length-1;}
_0R.parent=this;_0R.parents=[this];_0R.appId=_j;this.startApp(_j,_06);return _j;},startApp:function(_j,_06){if(_06===undefined){_06=this.defaultInterval;}
this.appPriorities[_j]=_06;this.busyApps[_j]=false;},stopApp:function(_j){this.busyApps[_j]=true;},reniceApp:function(_j,_06){this.appPriorities[_j]=_06;},killApp:function(_j,_5r){if(!_5r){var _6a=new Date().getTime();while(this.busyApps[_j]==true){if(new Date().getTime()>_6a+this.maxAppRunTime){break;}}}
this.busyApps[_j]=true;this.apps[_j].destroyAllViews();delete this.apps[_j];this.apps[_j]=null;this.freeAppIds.push(_j);},views:[],_2K:[],addView:function(_g){var _2f;if(this._2K.length==0){_2f=this.views.length;this.views.push(_g);}
else{_2f=this._2K.pop();this.views[_2f]=_g;}
return _2f;},delView:function(_h){this.views[_h]=null;this._2K.push(_h);},activeWindowId:0,windowFocus:function(_g){var _6E=this.activeWindowId,_1Q=this.views,_h=_g.viewId;if(_1Q[_6E]){_1Q[_6E].windowBlur();}
this.activeWindowId=_h;_g.bringToFront();_g.windowFocus();}});LOAD('HSystem.ticker();');HApplication=HClass.extend({componentBehaviour:['app'],constructor:function(_06){this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_06);},buildParents:function(_h){var _g=HSystem.views[_h];_g.parent=this;_g.parents=[];for(var _0L=0;_0L<this.parents.length;_0L++){_g.parents.push(this.parents[_0L]);}
_g.parents.push(this);},addView:function(_g){var _h=HSystem.addView(_g);this.views.push(_h);this.buildParents(_h);this.viewsZOrder.push(_h);return _h;},removeView:function(_h){HSystem.views[_h].remove();},destroyView:function(_h){HSystem.views[_h].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){var i,_h;for(i=0;i<this.views.length;i++){_h=this.views[i];HSystem.views[_h].die();}},_5T:function(){var i,_h;for(i=0;i<this.views.length;i++){_h=this.views[i];HSystem.views[i].onIdle();}},_4w:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._5T();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='/H/themes';HDefaultThemeName='default';HNoComponentCSS=[];HThemeHasIE6GifsInsteadOfPng=[];HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2n={};this._1X={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_R){this.themePath=_R;},_5n:function(_l){console.log("ERROR: Template Not Found: '"+_l+"' ");},_5m:function(_l){console.log("ERROR: Template Failure: '"+_l+"' ");},_5l:function(_l){console.log("ERROR: Template Exception: '"+_l+"' ");},fetch:function(_l,_0G){var _1F;if(!_0G){var _0G='text/html; charset=UTF-8';}
var _3a=new Ajax.Request(_l,{method:'GET',onSuccess:function(_6B){_1F=_6B.responseText;},on404:function(){HThemeManager._5n(_l);},onFailure:function(){HThemeManager._5m(_l);},onException:function(){HThemeManager._5l(_l);},asynchronous:false,contentType:_0G});_3a.onStateChange();return _1F;},getThemeGfxPath:function(){var _f=this._1p[0],_n=this._1p[1],_u=this._1p[2],_y=this._1p[3],_0C=this._0C(_f,_n,_u,_y);return this._I(_0C,'gfx');},getCssFilePath:function(_0d){var _f=this._1p[0];if((HThemeHasIE6GifsInsteadOfPng.indexOf(_f)!=-1)&&ELEM._1A){return"url('"+this._I(this.getThemeGfxPath(),_0d.replace('.png','-ie6.gif'))+"')";}
else{return"url('"+this._I(this.getThemeGfxPath(),_0d)+"')";}},loadCSS:function(_l){var _0G='text/css';var _0H=this.fetch(_l,_0G);if(!_0H||_0H==""){return;}
_0H=this._3r(_0H);var _08,_4z,_3K;if(ELEM._25){_08=document.createStyleSheet();_08.cssText=_0H;}
else{_08=document.createElement("style");_08.type=_0G;_08.media="all";_3K=document.getElementsByTagName('head')[0];_3K.appendChild(_08);if(navigator.userAgent.indexOf('KHTML')!=-1){var _5d=document.createTextNode(_0H);_08.appendChild(_5d);}
else{_08.innerHTML=_0H;}}},_4W:function(_B){if(_B[_B.length-1]!='/'){_B+='/';}
return _B;},_I:function(_6b,_6c){return this._4W(_6b)+_6c;},_0C:function(_f,_n,_u,_y){var _R=_u;if(_u===null){_R=this.themePath;}
if(HThemeMode==0){if(_y){_R=this._I(_R,_y);}
if(_u===null){_R=this._I(_R,_n);_R=this._I(_R,'themes');}
_R=this._I(_R,_f);}
else if(HThemeMode==1){_R=this._I(_R,_f);}
return _R;},_1Z:function(_f,_n,_u,_y){this._1p=[_f,_n,_u,_y];var _5b=this._0C(_f,_n,_u,_y);var _5c=this._I('css',_n+'.css');var _1Z=this._I(_5b,_5c);return _1Z;},_2Y:function(_f,_n,_u,_y){var _5z=this._0C(_f,_n,_u,_y);var _5A=this._I('html',_n+'.html');var _5B=this._I(_5z,_5A);return _5B;},loadMarkup:function(_f,_n,_u,_y){if(!this._2n[_f]){this._2n[_f]={};}
var _s=this._2n[_f][_n];if(null===_s||undefined===_s){var _2Y=this._2Y(_f,_n,_u,_y);_s=this.fetch(_2Y);if(null===_s||undefined===_s){_s="";}
this._2n[_f][_n]=_s;}
return _s;},getMarkup:function(_f,_n,_u,_y){if(!this._1X[_f]){var _55=this._1Z(_f,'common',_u,null);this._1X[_f]={};this.loadCSS(_55);}
if(HNoComponentCSS.indexOf(_f)==-1){if(!this._1X[_f][_n]){var _56=this._1Z(_f,_n,_u,_y);this._1X[_f][_n]=true;this.loadCSS(_56);}}
return this.loadMarkup(_f,_n,_u,_y);},_1k:function(_f,_n,_u,_y){var _0C=this._0C(_f,_n,_u,_y);var _l=this._I(_0C,'gfx');return _l;},_57:function(_f,_n,_u,_y,_0d){if((HThemeHasIE6GifsInsteadOfPng.indexOf(_f)!=-1)&&ELEM._1A){return this._I(this._1k(_f,_n,_u,_y),_0d.replace('.png','-ie6.gif'));}
return this._I(this._1k(_f,_n,_u,_y),_0d);},getThemeGfxFile:function(_0d){return this.getThemeGfxPath()+_0d;},setTheme:function(_4G){this.currentTheme=_4G;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_0P:new RegExp(/#\{([^\}]*)\}/),_3r:function(_1q){while(this._0P.test(_1q)){_1q=_1q.replace(this._0P,eval(RegExp.$1));}
return _1q;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _0w=this.markup;while(HMarkupView._3p.test(_0w)){_0w=_0w.replace(HMarkupView._3p,this.evalMarkupVariable(RegExp.$1,true));}
while(HMarkupView._0P.test(_0w)){_0w=_0w.replace(HMarkupView._0P,this.evalMarkupVariable(RegExp.$1));}
this.markup=_0w;},evalMarkupVariable:function(_6e,_74){try{var _ID=this.elemId.toString(),_WIDTH=this.rect.width,_HEIGHT=this.rect.height,_1F=eval(_6e);if(_74){return'';}
if(_1F===undefined){return'';}
else{return _1F;}}
catch(e){return'';}},toggleCSSClass:function(_0c,_1o,_4s){if(_0c){var _3I=ELEM.hasClassName(_0c,_1o);if(_4s){if(!_3I){ELEM.addClassName(_0c,_1o);}}
else{if(_3I){ELEM.removeClassName(_0c,_1o);}}}}},{_0P:new RegExp(/#\{([^\}]*)\}/),_3p:new RegExp(/\$\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,componentBehaviour:['view'],constructor:function(_1,_i){if(this.theme===undefined){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;}
else{this.preserveTheme=true;}
this.optimizeWidthOnRefresh=true;this.parent=_i;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.viewsZOrder=[];this._5a();this.setRect(_1);this.isHidden=true;this.drawn=false;this._3s=_1.left;this._3t=_1.top;this._0X=[];if(!this.isinherited){this.draw();this.show();}},setFlexRight:function(_8,_V){if(_8===undefined){_8=true;}
this.flexRight=_8;if(_V===undefined){_V=0;}
this.flexRightOffset=_V;},setFlexLeft:function(_8,_V){if(_8===undefined){_8=true;}
this.flexLeft=_8;if(_V!==undefined){this.rect.setLeft(_V);}},setFlexTop:function(_8,_V){if(_8===undefined){_8=true;}
this.flexTop=_8;if(_V!==undefined){this.rect.setTop(_V);}},setFlexBottom:function(_8,_V){if(_8===undefined){_8=true;}
this.flexBottom=_8;if(_V===undefined){_V=0;}
this.flexBottomOffset=_V;},setAbsolute:function(_8){if(_8===undefined){_8=true;}
this.isAbsolute=_8;},setRelative:function(_8){if(_8===undefined){_8=true;}
this.isAbsolute=(!_8);},getThemeGfxPath:function(){if(this.preserveTheme){_f=this.theme;}else{_f=HThemeManager.currentTheme;}
return HThemeManager._1k(_f,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0d){if(this.preserveTheme){_f=this.theme;}else{_f=HThemeManager.currentTheme;}
return HThemeManager._57(_f,this.componentName,this.themePath,this.packageName,_0d);},_45:function(_16){this.elemId=ELEM.make(_16,'div');},_66:function(_4X){var _1Y='display:none;overflow:hidden;visibility:hidden;';if(this.isAbsolute){_1Y+='position:absolute;';}else{_1Y+='position:relative;';}
_1Y+=_4X;ELEM.setCSS(this.elemId,_1Y);},_2M:function(){var _16;if(this.parent.elemId===undefined){_16=0;}
else if(this.parent.markupElemIds&&this.parent.markupElemIds['subview']){_16=this.parent.markupElemIds['subview'];}
else{_16=this.parent.elemId;}
return _16;},_5a:function(){if(!this.elemId){this._45(this._2M());this._66('');if(this.preserveTheme){ELEM.addClassName(this.elemId,this.theme);}
else{ELEM.addClassName(this.elemId,HThemeManager.currentTheme);}}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
this.drawn=true;var _9=this.elemId;var _1=this.rect;ELEM.setStyle(_9,'left',this.flexLeft?(_1.left+'px'):'auto',true);ELEM.setStyle(_9,'top',this.flexTop?(_1.top+'px'):'auto',true);ELEM.setStyle(_9,'right',this.flexRight?(this.flexRightOffset+'px'):'auto',true);ELEM.setStyle(_9,'bottom',this.flexBottom?(this.flexBottomOffset+'px'):'auto',true);ELEM.setStyle(_9,'width',(this.flexLeft&&this.flexRight)?'auto':(_1.width+'px'),true);ELEM.setStyle(_9,'height',(this.flexTop&&this.flexBottom)?'auto':(_1.height+'px'),true);if(this.flexLeft&&this.flexRight){ELEM.setStyle(_9,'min-width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){ELEM.setStyle(_9,'min-height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){ELEM.setStyle(_9,'visibility','inherit',true);}
ELEM.setStyle(_9,'display','block',true);this._4O();if(this._3s!=_1.left||this._3t!=_1.top){this.invalidatePositionCache();this._3s=_1.left;this._3t=_1.top;}},_4O:function(){ELEM.setStyle(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this.viewId));},_2p:function(){var _1Q=this.parent.viewsZOrder;for(var i=0;i<_1Q.length;i++){ELEM.setStyle(HSystem.views[_1Q[i]].elemId,'z-index',i);}},draw:function(){var _0J=this.drawn;this.drawRect();if(!_0J&&(this.componentName!==undefined)){this.drawMarkup();}
this.refresh();},_42:function(){var _f;if(this.preserveTheme){_f=this.theme;}
else{_f=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_f,this.componentName,this.themePath,this.packageName);},markupElemNames:['bg','label','state','control','value','subview'],drawMarkup:function(){ELEM.setStyle(this.elemId,'display','none',true);this._42();this.bindMarkupVariables();ELEM.setHTML(this.elemId,this.markup);this.markupElemIds={};for(var i=0;i<this.markupElemNames.length;i++){var _0f=this.markupElemNames[i],_3D=_0f+this.elemId,_5y=' id="'+_3D+'"';if(this.markup.indexOf(_5y)!=-1){this.markupElemIds[_0f]=this.bindDomElement(_3D);}}
ELEM.setStyle(this.elemId,'display','block');},setHTML:function(_0I){ELEM.setHTML(this.elemId,_0I);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_0j,_4,_2x){if(!this.elemId){return;}
ELEM.setStyle(this.elemId,_0j,_4,_2x);},style:function(_0j){if(!this.elemId){return;}
return ELEM.getStyle(this.elemId,_0j);},setStyleForPart:function(_0f,_0j,_4,_2x){if(!this.markupElemIds[_0f]){return;}
ELEM.setStyle(this.markupElemIds[_0f],_0j,_4,_2x);},styleForPart:function(_0f,_0j){if(!this.markupElemIds[_0f]){return;}
ELEM.getStyle(this.markupElemIds[_0f],_0j);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){var _6w=this.parent.viewsZOrder.indexOf(this.viewId),_6v=this.parent.views.indexOf(this.viewId);this.parent.views.splice(_6v,1);HSystem.delView(this.viewId);this.parent.viewsZOrder.splice(_6w,1);this._2p();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].die();}
this.remove();for(var i=0;i<this._0X.length;i++){ELEM.del(this._0X[i]);}
this._0X=[];ELEM.del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].onIdle();}},buildParents:function(_h){var _g=HSystem.views[_h];_g.parent=this;_g.parents=[];for(var _0L=0;_0L<this.parents.length;_0L++){_g.parents.push(this.parents[_0L]);}
_g.parents.push(this);},addView:function(_g){var _h=HSystem.addView(_g);this.views.push(_h);this.buildParents(_h);this.viewsZOrder.push(_h);return _h;},removeView:function(_h){HSystem.views[_h].remove();},destroyView:function(_h){HSystem.views[_h].die();},bounds:function(){var _0E=new HRect(this.rect);_0E.right-=_0E.left;_0E.left=0;_0E.bottom-=_0E.top;_0E.top=0;return _0E;},resizeBy:function(_2P,_1P){var _1=this.rect;_1.right+=_2P;_1.bottom+=_1P;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_q,_H){var _1=this.rect;_1.right=_1.left+_q;_1.bottom=_1.top+_H;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_2P,_1P){this.rect.offsetBy(_2P,_1P);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _p=this.zIndex();this.parent.viewsZOrder.splice(_p,1);this.parent.viewsZOrder.push(this.viewId);this._2p();},sendToBack:function(){if(!this.parent){return;}
var _p=this.zIndex();this.parent.viewsZOrder.splice(_p,1);this.parent.viewsZOrder.splice(0,0,this.viewId);this._2p();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this.viewId);},stringWidth:function(_1a,_28,_9){if(_28!==undefined&&_28!=null){_1a=_1a.substring(0,_28);}
if(_9===undefined||_9==null){_9=this.elemId;}
var _0M=ELEM.make(_9);ELEM.setCSS(_0M,"visibility:hidden;position:absolute;white-space:nowrap;");ELEM.setHTML(_0M,_1a);var _q=0,_H=0;if(ELEM._1A||ELEM._76||ELEM._77){_q=parseInt(ELEM.get(_0M).offsetWidth,10);if(arguments[3]){_H=parseInt(ELEM.get(_0M).offsetHeight,10);}}else{_q=parseInt(ELEM.get(_0M).clientWidth,10);if(ELEM._75){_q+=1;}
if(arguments[3]){_H=parseInt(ELEM.get(_0M).clientHeight,10);}}
ELEM.del(_0M);if(arguments[3]){return[_q,_H];}else{return _q;}},pageX:function(){var _7=0;var _6=this;while(_6){if(_6.elemId&&_6.rect){_7+=ELEM.get(_6.elemId).offsetLeft;_7-=ELEM.get(_6.elemId).scrollLeft;}
if(_6.markupElemIds&&_6.markupElemIds.subview){_7+=ELEM.get(_6.markupElemIds.subview).offsetLeft;_7-=ELEM.get(_6.markupElemIds.subview).scrollLeft;}
_6=_6.parent;}
return _7;},pageY:function(){var _b=0;var _6=this;while(_6){if(_6.elemId&&_6.rect){_b+=ELEM.get(_6.elemId).offsetTop;_b-=ELEM.get(_6.elemId).scrollTop;}
if(_6.markupElemIds&&_6.markupElemIds.subview){_b+=ELEM.get(_6.markupElemIds.subview).offsetTop;_b-=ELEM.get(_6.markupElemIds.subview).scrollTop;}
_6=_6.parent;}
return _b;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].invalidatePositionCache();}},bindDomElement:function(_3C){var _2w=ELEM.bindId(_3C);if(_2w){this._0X.push(_2w);}
return _2w;},unbindDomElement:function(_0c){var _3Q=this._0X.indexOf(_0c);if(_3Q>-1){ELEM.del(_0c);this._0X.splice(_3Q,1);}},animateTo:function(_m,_0t,_0l){if(_m instanceof HPoint){var _1=new HRect(_m,_m);_1.setSize(this.rect.width,this.rect.height);this._2t(_1,_0t);}
else if(_m instanceof HRect){this._2t(_m,_0t);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._1U){window.clearInterval(this._1U);this._1U=null;var _05=parseInt(this.style('left'),10),_0B=parseInt(this.style('top'),10),_q=parseInt(this.style('width'),10),_H=parseInt(this.style('height'),10);this.rect.set(_05,_0B,_05+_q,_0B+_H);this.drawRect();if(this._3n){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_2t:function(_1,_0t,_0l){if(null===_0t||undefined===_0t){_0t=500;}
if(null===_0l||undefined===_0l||_0l<1){_0l=50;}
if(!this._1U){this._3n=false;this.onAnimationStart();var _69=new Date().getTime();var _k=this;this._1U=window.setInterval(function(){_k._6G({startTime:_69,duration:_0t,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_k.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_k.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_k.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_k.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0l));}},_6G:function(_m){var _4J=new Date().getTime();if(_4J<_m.startTime+_m.duration){var _52=_4J-_m.startTime;for(var i=0;i<_m.props.length;i++){var _2L=_m.props[i].from;var _4L=_m.props[i].to;if(_2L!=_4L){var _5Z=_m.transition(_52,_2L,(_4L-_2L),_m.duration);this.setStyle(_m.props[i].prop,_5Z+_m.props[i].unit);}}}else{for(var i=0;i<_m.props.length;i++){this.setStyle(_m.props[i].prop,_m.props[i].to+_m.props[i].unit);}
this._3n=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({componentBehaviour:['view','control'],refreshOnValueChange:true,refreshOnLabelChange:true,constructor:function(_1,_x,_6C){if(!_6C){_6C={};}
var options=new(HComponentDefaults.extend(_6C));this.options=options;if(this.isinherited){this.base(_1,_x);}
else{this.isinherited=true;this.base(_1,_x);this.isinherited=false;}
var _J=options.label;this.setLabel(_J);var _1w=options.events;this.setEvents(_1w);if(this.options.valueObj){this.setValueObj(this.options.valueObj);}
if(!this.valueObj){this.setValueObj(new HDummyValue());}
if((this.value===undefined)&&(options.value!==undefined)){this.setValue(options.value);}
var _5G=(_6C.minValue||_6C.maxValue);if(_5G){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(options.visible){this.show();}
else{this.hide();}
if(!this.isinherited){this.draw();}},setAction:function(_3l){this.action=_3l;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
EVENT.unreg(this);this.base();},setLabel:function(_J){this.label=_J;this.options.label=_J;this.refresh();},setEnabled:function(_8){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].setEnabled(_8);}
if(this.enabled===_8){return;}
this.enabled=_8;if(_8){EVENT.reg(this,this.events);}
else{EVENT.unreg(this);}
this.toggleCSSClass(this.elemId,HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(this.elemId,HControl.CSS_DISABLED,!this.enabled);},setValue:function(_4){if(_4===undefined){return;}
if(!this.valueObj){return;}
if(_4!==this.value){this.value=_4;this.valueObj.set(this.value);this.refresh();}},setValueObj:function(_3k){this.valueObj=_3k;this.setValue(_3k.value);},setValueRange:function(_4,_2c,_2b){this.minValue=_2c;this.maxValue=_2b;_4=(_4<_2c)?_2c:_4;_4=(_4>_2b)?_2b:_4;this.setValue(_4);this.refresh();},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}},refresh:function(){this.base();if(this.drawn){if(this.refreshOnValueChange){this.refreshValue();}
if(this.refreshOnLabelChange){this.refreshLabel();}}},setEvents:function(_1w){if(!this.events){var _5o=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,textEnter:false,click:false});this.events=new _5o;}
if(_1w){this.events.extend(_1w);}
this.events.ctrl=this;EVENT.focusOptions[this.elemId]=this.events;var _48=this.events.mouseMove;var _31=EVENT.coordListeners.indexOf(this.elemId);if(_48&&(_31==-1)){EVENT.coordListeners.push(this.elemId);}else if((!_48)&&(_31!=-1)){EVENT.coordListeners.splice(_31,1);}
this.isDragged=false;},setMouseMove:function(_8){this.events.mouseMove=_8;this.setEvents();},setClickable:function(_8){this.events.click=_8;this.setEvents();},setMouseDown:function(_8){this.events.mouseDown=_8;this.setEvents();},setMouseUp:function(_8){this.events.mouseUp=_8;this.setEvents();},setMouseWheel:function(_8){this.events.mouseWheel=_8;this.setEvents();},setDraggable:function(_8){this.events.draggable=_8;this.setEvents();},setDroppable:function(_8){this.events.droppable=_8;this.setEvents();},setKeyDown:function(_8){this.events.keyDown=_8;this.setEvents();},setKeyUp:function(_8){this.events.keyUp=_8;this.setEvents();},setTextEnter:function(_8){this.events.textEnter=_8;this.setEvents();},textEnter:function(){},focus:function(){},blur:function(){},gainedActiveStatus:function(_2V){},_5t:function(_2V){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_2V);},lostActiveStatus:function(_A){},_5I:function(_A){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_A);},mouseMove:function(_7,_b){},mouseDown:function(_7,_b,_27){},mouseUp:function(_7,_b,_27){},mouseWheel:function(_O){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_z){},keyUp:function(_z){},_4a:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.ctrl;EVENT.focus(_0);Event.stop(e);},_49:function(e){if(!Event.element){return;}
var _k=Event.element(e);while(_k&&_k.ctrl===undefined){_k=_k.parentNode;}
if(!_k){return;}
var _0=_k.owner;EVENT.blur(_0);Event.stop(e);},invalidatePositionCache:function(){this.base();EVENT.coordCacheFlush(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_2,_4){this.id=_2;this.value=_4;},set:function(_4){this.value=_4;},get:function(){return this.value;},bind:function(_1M){},unbind:function(_1M){}});HComponentDefaults=HClass.extend({label:"Untitled",visible:true,events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HDynControl=HControl.extend({componentName:'dyncontrol',componentBehaviour:['view','control','window'],constructor:function(_1,_i,_6C){if(!_6C){_6C={};}
var _r=HClass.extend({minSize:[24,54],maxSize:[16000,9000],resizeW:1,resizeE:1,resizeN:1,resizeS:1,resizeNW:[1,1],resizeNE:[1,1],resizeSW:[1,1],resizeSE:[1,1],noResize:false});_6C=new(_r.extend(_6C))();if(_6C.noResize){_6C.minSize=[_1.width,_1.height];_6C.maxSize=[_1.width,_1.height];_6C.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
if(this.isinherited){this.base(_1,_i,_6C);}
else{this.isinherited=true;this.base(_1,_i,_6C);this.isinherited=false;}
this.presrveTheme=true;this.setDraggable(true);this._5D();this._3S();if(!this.isinherited){this.draw();}},drawRect:function(_40,_6o){if(this.rect.width<this.options.minSize[0]){var _2G=0-(this.options.minSize[0]-this.rect.width);this.rect.setWidth(this.options.minSize[0]);if(_40){this.rect.offsetBy(_2G,0);}}
else if(this.rect.width>this.options.maxSize[0]){var _2G=0-(this.options.maxSize[0]-this.rect.width);this.rect.setWidth(this.options.maxSize[0]);if(_40){this.rect.offsetBy(_2G,0);}}
if(this.rect.height<this.options.minSize[1]){var _2D=0-(this.options.minSize[1]-this.rect.height);this.rect.setHeight(this.options.minSize[1]);if(_6o){this.rect.offsetBy(0,_2D);}}
else if(this.rect.height>this.options.maxSize[1]){var _2D=0-(this.options.maxSize[1]-this.rect.height);this.rect.setHeight(this.options.maxSize[1]);if(_6o){this.rect.offsetBy(0,_2D);}}
this.base();},draw:function(){var _0J=this.drawn;this.base();if(!_0J){this.buildStructure();}},buildStructure:function(){},_21:function(_7,_b){return this._5V.subtract(_7,_b);},dynResizeNW:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setLeftTop(_0.rect.leftTop.subtract(_D));_0.drawRect(1,1);_0._5V.set(_7,_b);},dynResizeNE:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setRightTop(_0.rect.rightTop.subtract(_D));_0.drawRect(0,1);_0._5V.set(_7,_b);},dynResizeSW:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setLeftBottom(_0.rect.leftBottom.subtract(_D));_0.drawRect(1,0);_0._5V.set(_7,_b);},dynResizeSE:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setRightBottom(_0.rect.rightBottom.subtract(_D));_0.drawRect(0,0);_0._5V.set(_7,_b);},dynResizeW:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setLeft(_0.rect.left-_D.x);_0.drawRect(1,0);_0._5V.set(_7,_b);},dynResizeE:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setRight(_0.rect.right-_D.x);_0.drawRect(0,0);_0._5V.set(_7,_b);},dynResizeN:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setTop(_0.rect.top-_D.y);_0.drawRect(0,1);_0._5V.set(_7,_b);},dynResizeS:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.setBottom(_0.rect.bottom-_D.y);_0.drawRect(0,0);_0._5V.set(_7,_b);},dynDrag:function(_0,_7,_b){var _D=_0._21(_7,_b);_0.rect.offsetTo(_0.rect.leftTop.subtract(_D));_0.drawRect(1,1);_0._5V.set(_7,_b);},_5D:function(){this._W=[];var i,_0=this,_7m=0,_7l=1,_7p=2,_7o=3,_7q=4,_7j=5,_7k=6,_7n=7,_6R=8,_W=this._W;_W[_7m]=_0.dynResizeNW;_W[_7l]=_0.dynResizeNE;_W[_7p]=_0.dynResizeSW;_W[_7o]=_0.dynResizeSE;_W[_7q]=_0.dynResizeW;_W[_7j]=_0.dynResizeE;_W[_7k]=_0.dynResizeN;_W[_7n]=_0.dynResizeS;_W[_6R]=_0.dynDrag;},_3S:function(){this._1e=-1;this._1R=[];var i,_1I,_t=this.options,_1=this.rect,_60=[[0,0,_t.resizeNW[0],_t.resizeNW[1]],[_1.width-_t.resizeNE[0],0,_1.width,_t.resizeNE[1]],[0,_1.height-_t.resizeSW[1],_t.resizeSW[0],_1.height],[_1.width-_t.resizeSE[0],_1.height-_t.resizeSE[1],_1.width,_1.height],[0,_t.resizeN,_t.resizeW,_1.height-_t.resizeS],[_1.width-_t.resizeE,_t.resizeN,_1.width,_1.height-_t.resizeS],[_t.resizeW,0,_1.width-_t.resizeE,_t.resizeN],[_t.resizeW,_1.height-_t.resizeS,_1.width-_t.resizeE,_1.height],[_t.resizeW,_t.resizeN,_1.width-_t.resizeE,_1.height-_t.resizeS]];for(i=0;i!=9;i++){_1I=_60[i];this._1R.push(new HRect(_1I[0],_1I[1],_1I[2],_1I[3]));}},_5f:function(){var i,_4U=this._68.subtract(this.rect.left,this.rect.top),_1R=this._1R;for(i=0;i!=9;i++){if(_1R[i].contains(_4U)){this._1e=i;return;}}},startDrag:function(_7,_b,_24){this._68=new HPoint(_7,_b);this._5V=new HPoint(_7,_b);this._7v=new HRect(this.rect);this._5f();if(this._1e==8){this.setStyle('cursor','move');}
this.bringToFront();this.doDrag(_7,_b,_24);},doDrag:function(_7,_b,_24){if(this._1e!=-1){this._W[this._1e](this,_7,_b);}},endDrag:function(_7,_b,_24){this.doDrag(_7,_b,_24);if(this._1e==8){this.setStyle('cursor','default');}
this._3S();}});