
ie_htc_path=null;function ie_early_fixes(){document.execCommand("BackgroundImageCache",false,true);var _69=document.scripts[document.scripts.length-1],_4z=_69.src;ie_htc_path=_4z.substring(0,_4z.lastIndexOf("/")+1);console={log:function(){}};}
ie_early_fixes();iefix={setWinSize:function(){window.innerWidth=document.documentElement.clientWidth;window.innerHeight=document.documentElement.clientHeight;},_75:function(_5){return _5.currentStyle.hasLayout;},layoutWidth:function(_5){var _0=iefix,_o,i=0,_X=_5.offsetParent;while(_X&&!_0._75(_X)){_X=_X.offsetParent;}
if(!_X._resizewidthElements){_X._resizewidthElements=[];}
if(!_5._addedResizewidthFix){_X._resizewidthElements.push(_5);_o=_X;while(_o.offsetParent){_o=_o.offsetParent;if(_o._resizewidthElements){_o._resizewidthElements.push(_5);}
if(_o.style.position=="absolute"||_o.style.position=="fixed"){break;}}
_5._addedResizewidthFix=true;}
if(!_X._resizewidth){_X.attachEvent("onpropertychange",function(){if(window.event.propertyName=="style.width"){for(;i<_X._resizewidthElements.length;i++){_0.resizeRight(_X._resizewidthElements[i]);}}});_X._resizewidth=true;}
return(_X||document.documentElement).clientWidth;},getBorderWidth:function(_5){return _5.offsetWidth-_5.clientWidth;},getPixelValue:function(_5,_4){var _0=iefix,_07,_68;if(_0._PIXEL.test(_4)){return parseInt(_4,10);}
_07=_5.style.left;_68=_5.runtimeStyle.left;_5.runtimeStyle.left=_5.currentStyle.left;_0.resizing=true;_5.style.left=_4||0;_4=_5.style.pixelLeft;_5.style.left=_07;_0.resizing=false;_5.runtimeStyle.left=_68;return _4;},getPixelWidth:function(_5,_4){var _0=iefix;if(_0._PERCENT.test(_4)){return parseInt(parseFloat(_4)/100*_0.layoutWidth(_5),10);}
return _0.getPixelValue(_5,_4);},getPaddingWidth:function(_5){var _0=iefix;return _0.getPixelWidth(_5,_5.currentStyle.paddingLeft)+_0.getPixelWidth(_5,_5.currentStyle.paddingRight);},resizeRight:function(_5){var _0=iefix,_05,_m;if(_5.currentStyle===null){return;}
_05=parseInt(_5.currentStyle.left,10);_m=_0.layoutWidth(_5)-parseInt(_5.currentStyle.right,10)-_05;if(parseInt(_5.runtimeStyle.width,10)==_m){return;}
_5.runtimeStyle.width="";if(_5.offsetWidth<_m){_m-=_0.getBorderWidth(_5)+_0.getPaddingWidth(_5);if(_m<0){_m=0;}
_5.runtimeStyle.width=_m;}},fixOpacity:function(_5){var _Y=(parseFloat(_5.currentStyle.opacity)*100)||1,_P=_5.filters["DXImageTransform.Microsoft.Alpha"];if(_P){_P.Opacity=_Y;_P.Enabled=true;}
else{_5.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.Alpha(opacity="+_Y+")";}},fixBackgroundImage:function(_5){var _0=iefix,_n,_P;_n=_5.currentStyle.backgroundImage.match(/url\(\s*['"]?([^'")]+)['"]?\s*\)/);if(!_n){return;}
else{_n=_n[1];}
_P=_5.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_0.pngCheck.test(_n)){if(_P){_P.sizingMethod="crop";_P.src=_n;_P.Enabled=true;}
else{_5.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_n+"',sizingMethod='crop')";}
_5.runtimeStyle.zoom="0";_5.runtimeStyle.backgroundImage="none";}
else if(_P){_P.Enabled=false;}},addFilter:function(_5,_0Z){var _0=iefix,_P,_tempUrl;_P=_5.filters["DXImageTransform.Microsoft.AlphaImageLoader"];if(_P){_P.src=_5.src;_P.Enabled=true;}
else{_5.runtimeStyle.filter+="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+_5.src+"',sizingMethod='scale')";}
_6s=_5.src;_5.src=_0.blankGifPath;_0Z.src=_6s;},fixImg:function(_5){var _0=iefix,_0Z;if(_0.pngCheck.test(_5.src)){_0Z=new Image(_5.width,_5.height);_0Z.onload=function(){_5.width=_0Z.width;_5.height=_0Z.height;_0Z=null;};_0.addFilter(_5,_0Z);}},_7i:['PARAM'],inlineStyleChanged:function(_5){var _0=iefix,_03;_03=_5.currentStyle;if(_0._7i.indexOf(_5.tagName)!=-1){return;}
try{if((_03.position=="absolute"||_03.position=="fixed")&&_03.left!="auto"&&_03.right!="auto"&&_03.width=="auto"){_0.resizeRight(_5);}
if((_03.position=="absolute"||_03.position=="fixed")&&_03.top!="auto"&&_03.bottom!="auto"&&_03.height=="auto"){_0.resizeBottom(_5);}
if(_5.currentStyle.opacity){_0.fixOpacity(_5);}}catch(e){alert("iefix error! element:"+_5.tagName+" e:"+e.description);}
if(_5.style.backgroundColor=='transparent'&&(_5.style.backgroundImage=='none'||!_5.style.backgroundImage)){_5.style.backgroundImage="url("+ie_htc_path+"128.gif)";}},_7F:0,_01:function(_5){var _0=iefix;_0._7F++;_5=_5||document.documentElement;while(_5){if(_5.nodeType==1){_0.inlineStyleChanged(_5);}
var _2h=_5.firstChild;if(!_2h){_2h=_5.nextSibling;}
while(!_2h&&_5.parentNode){_5=_5.parentNode;_2h=_5.nextSibling;}
_5=_2h;}},stylesheet_refresh:function(_4D){_4D.cssText+="";},init:function(){var _0=iefix;_0._AUTO=/^(auto|0cm)$/;_0._PIXEL=/^\d+(px)?$/i;_0._PERCENT=/^\d+%$/;_0.pngCheck=new RegExp(".png$","i");_0.blankGifPath=ie_htc_path+"0.gif";eval("_0.getMarginWidth="+String(_0.getPaddingWidth).replace(/padding/g,"margin"));eval("_0.getPaddingHeight="+String(_0.getPaddingWidth).replace(/Width/g,"Height").replace(/Left/g,"Top").replace(/Right/g,"Bottom"));eval("_0.getMarginHeight="+String(_0.getPaddingHeight).replace(/padding/g,"margin"));eval("_0.getBorderHeight="+String(_0.getBorderWidth).replace(/Width/g,"Height"));eval("_0.layoutHeight="+String(_0.layoutWidth).replace(/Width/g,"Height").replace(/width/g,"height").replace(/Right/g,"Bottom"));eval("_0.getPixelHeight="+String(_0.getPixelWidth).replace(/Width/g,"Height"));eval("_0.resizeBottom="+String(_0.resizeRight).replace(/Width/g,"Height").replace(/width/g,"height").replace(/left/g,"top").replace(/right/g,"bottom"));_0.resizing=false;},htcStyleEntry:function(){if(document.readyState=="complete"&&window.event.srcElement.readyState=="complete"){iefix._01();}},_2o:['width','height','left','top','right','bottom','display','position'],htcElementEntry:function(){var _5=window.event.srcElement,_1F=window.event.propertyName;if(_1F=="style.opacity"){iefix.fixOpacity(_5);}
else if((_1F=="src"&&_5.tagName=="IMG")||(_5.tagName=="INPUT"&&_5.type=="image")){window.status='htcElementEntry: '+iefix._0X+' img';iefix.fixImg(_5);}
else if(_1F.substring(0,6)=='style.'){if(iefix._2o.indexOf(_1F.split('style.')[1])!=-1){iefix._01();}}}};iefix.init();ie_complete=document.readyState=="complete";ie_initialized=false;ie_documentLoaded=function(){if(document.readyState=="complete"){iefix._01();}};ie_fixes=function(){if(!ie_initialized){if(ie_complete){ie_documentLoaded();}
else{document.onreadystatechange=ie_documentLoaded;}
ie_initialized=true;}};ie_fixes();window.onresize=function(){iefix.setWinSize();iefix._01();};