
HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _1B=this.drawn;this.base();if(!_1B){var i=0,_3g=[['overflow','auto']];for(i;i<_3g.length;i++){this.setStyle(_3g[i][0],_3g[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_1,_o,_2){this.tabInit();if(this.isinherited){this.base(_1,_o,_2);}
else{this.isinherited=true;this.base(_1,_o,_2);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_4){this.base(_4);if(typeof _4=='number'){var _z=parseInt(_4,10);if(_z<this.tabs.length){if(_z!=this.selectIdx){this.selectTab(_z);}}}},stringWidth:function(_19,_9){var _1z='<span style="'+this.fontStyle+'">'+_19+'</span>',_m=this.base(_1z,null,_9);return _m;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_J){this.label=_J;},selectTab:function(_q){if(_q instanceof HTabView){_q=_q.tabIndex;}
if(this.selectIdx!=-1){var _4I=this.tabLabels[this.selectIdx],_6p=this.tabs[this.selectIdx];ELEM.removeClassName(_4I,'item-fg');ELEM.addClassName(_4I,'item-bg');HSystem.views[_6p].hide();}
if(_q!=-1){var _00=this.tabLabels[_q],_3h=this.tabs[_q];ELEM.removeClassName(_00,'item-bg');ELEM.addClassName(_00,'item-fg');HSystem.views[_3h].show();}
this.selectIdx=_q;this.setValue(_q);},addTab:function(_2m,_6T){var _q=this.tabs.length,_4H='',_5L=this.stringWidth(_2m,0),_2Y=_5L+this.tabLabelLeftEdge+this.tabLabelRightEdge,_1b=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_q=this.tabs.length,_00=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);if(this.tabLabelNoHTMLPrefix){_4H=_2m;}
else{_4H=this.tabLabelHTMLPrefix1+_5L+this.tabLabelHTMLPrefix2+_2m+this.tabLabelHTMLSuffix;}
_1b.hide();ELEM.addClassName(_00,'item-bg');ELEM.setStyle(_00,'width',_2Y+'px');ELEM.setStyle(_00,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_00,_4H);this.tabLabelStrings.push(_2m);if(this.tabTriggerLink&&this.tabLabelElementTagName=='a'){ELEM.setAttr(_00,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_q+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_00,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_q+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_2Y]);}
this.rightmostPx+=_2Y;if(this.tabLabelAlign=='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
this.tabs.push(_1b.viewId);this.tabLabels.push(_00);_1b.tabIndex=_q;if(_6T){this.selectTab(_q);}
return _1b;},mouseDown:function(_7,_c){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_7-=this.pageX();_c-=this.pageY();if(_7<=this.rightmostPx){if(_c<=this.tabLabelHeight){var i=0,_41;for(i;i<this.tabLabelBounds.length;i++){_41=this.tabLabelBounds[i];if(_7<_41[1]&&_7>=_41[0]){this.selectTab(i);return;}}}}},removeTab:function(_q){var _6a=this.selectIdx,_3h=this.tabs[_q],_00=this.tabViews[_q];this.tabs.splice(_q,1);this.tabLabels.splice(_q,1);this.tabLabelBounds.splice(_q,1);this.tabLabelStrings.splice(_q,1);if(_q==_6a){this.selectIdx=-1;if(_q==0&&this.tabs.length==0){this.selectTab(-1);}
else if(_q==(this.tabs.length-1)){this.selectTab(_q-1);}
else{this.selectTab(_q);}}
else if(_q<_6a){this.selectIdx--;}
ELEM.del(_00);HSystem.views[_3h].die();},draw:function(){var _1B=this.drawn;this.base();if(!_1B){this.drawMarkup();}
this.refresh();}});