
HButton=HControl.extend({componentName:"button",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HButton]';this.preserveTheme=true;if(!this.isinherited){this.draw();}
this._2a=[this.rect.width,this.rect.height];},setLabelHeightDiff:function(_6l){this._4l=_6l;return'';},setLabelWidthDiff:function(_6m){this._4m=_6m;return'';},onIdle:function(){if(this.drawn){var _p=this.rect.width;var _D=this.rect.height;if((_p!=this._2a[0])||(_D!=this._2a[1])){this._2a[0]=_p;this._2a[1]=_D;if(this.markupElemIds.label){var _45=parseInt(_D+this._4l,10);ELEM.setStyle(this.markupElemIds.label,'line-height',_45+'px');if(ELEM._15){var _7d=parseInt(_p+this._4m,10);ELEM.setStyle(this.markupElemIds.label,'height',_45+'px');ELEM.setStyle(this.markupElemIds.label,'width',_7d+'px');}}}}},draw:function(){if(!this.drawn){this.drawRect();this._4l=0;this._4m=0;this.drawMarkup();}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}}});HClickButton=HButton.extend({constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HClickButton]';this.setMouseDown(true);this.setMouseUp(true);this._0X=false;this._1D=false;if(!this.isinherited){this.draw();}},focus:function(){if(!this._0X&&!this._1D){this._1D=true;this._0X=false;}
this.base();},blur:function(){if(!this._0X){this._1D=false;}
this.base();},mouseDown:function(x,y,_T){if(this._1D){this._0X=true;}
this.base(x,y,_T);},mouseUp:function(x,y,_T){if(this._1D&&this._0X){this._0X=false;this.click(x,y,_T);}
this.base(x,y,_T);},click:function(x,y,_T){this.setValue(this.value+1);if(this.action){this.action();}}});HToggleButton=HClickButton.extend({constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HToggleButton]';if(!this.isinherited){this.draw();}},click:function(x,y,_T){this.setValue(!this.value);},setValue:function(_9){if(null===_9||undefined===_9){_9=false;}
this.base(_9);},_75:function(){if(this.markupElemIds.control){var _7=ELEM.get(this.markupElemIds.control);this.toggleCSSClass(_7,HToggleButton.cssOn,this.value);this.toggleCSSClass(_7,HToggleButton.cssOff,!this.value);}},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}
if(this.markupElemIds.control){this._75();}}}},{cssOn:"on",cssOff:"off"});HStringView=HControl.extend({componentName:"stringview",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HStringView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){if(this.drawn){this.base();if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_1,_c,_2){this.markupElemIds={};if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HTextControl]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},die:function(){if(this.drawn){var _00='value'+this.elemId;Event.stopObserving(_00,'mousedown',this._2y);Event.stopObserving(_00,'mousemove',this._2y);Event.stopObserving(_00,'focus',this._3C);Event.stopObserving(_00,'blur',this._3T);}
this.base();},setEnabled:function(_9){this.base(_9);if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,"autocomplete","off");this.setEnabled(this.enabled);}
this._6K();this.drawn=true;}
this.refresh();},_6K:function(){var _00='value'+this.elemId;this._2y=function(_5Q){HControl.stopPropagation(_5Q);};Event.observe(_00,'mousedown',this._2y,false);Event.observe(_00,'mousemove',this._2y,false);var _i=this;this._3C=function(event){EVENT.changeActiveControl(_i);};Event.observe(_00,'focus',this._3C,false);this._3T=function(event){_i._76();EVENT.changeActiveControl(null);};Event.observe(_00,'blur',this._3T,false);},refresh:function(){this.base();if(this.markupElemIds.value){if(ELEM.getAttr(this.markupElemIds.value,'value',true)!=this.value){ELEM.setAttr(this.markupElemIds.value,'value',this.value,true);}}},onIdle:function(){if(this.active){this._76();}},_76:function(){if(this.drawn){if(ELEM.getAttr(this.markupElemIds.value,'value',true)!=this.value){this.setValue(ELEM.getAttr(this.markupElemIds.value,'value',true));}}},lostActiveStatus:function(_B){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).blur();}}});HTextArea=HTextControl.extend({componentName:"textarea",constructor:function(_1,_c,_2){this.base(_1,_c,_2);}});HSlider=HControl.extend({packageName:"sliders",componentName:"slider",constructor:function(_1,_c,_2){if(!_2){_2={};}
_2.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};var _s=Base.extend({minValue:0,maxValue:1});_s=_s.extend(_2);_2=new _s();if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HSlider]';this.refreshOnValueChange=false;this._4j='sliderknob';this._0g=false;if(!this.isinherited){this.draw();}},setValue:function(_4){if(_4<this.minValue){_4=this.minValue;}
if(_4>this.maxValue){_4=this.maxValue;}
this.base(_4);if(this._38){this.drawKnobPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._6e();}
this.refresh();},startDrag:function(_5,_8){var _6=ELEM.get(this.elemId);var _4I=helmi.Element.getPageLocation(_6,true);this._6r=_4I[0];this._6s=_4I[1];this.doDrag(_5,_8);},endDrag:function(_5,_8){this.doDrag(_5,_8);},doDrag:function(_5,_8){_5-=this._6r;_8-=this._6s;_7R=this._0g?_8:_5;_4=this._6w(_7R);this.setValue(_4);},keyDown:function(_F){if((_F==Event.KEY_LEFT&&!this._0g)||(_F==Event.KEY_UP&&this._0g)){this._1J=true;this._2p(-0.05);}
else if((_F==Event.KEY_RIGHT&&!this._0g)||(_F==Event.KEY_DOWN&&this._0g)){this._1J=true;this._2p(0.05);}
else if(_F==Event.KEY_HOME){this.setValue(this.minValue);}
else if(_F==Event.KEY_END){this.setValue(this.maxValue);}
else if(_F==Event.KEY_PAGEUP){this._1J=true;this._2p(-0.25);}
else if(_F==Event.KEY_PAGEDOWN){this._1J=true;this._2p(0.25);}},keyUp:function(_F){this._1J=false;},mouseWheel:function(_Q){var _1i;if(_Q>0){_1i=-0.05;}
else{_1i=0.05;}
_4=(this.maxValue-this.minValue)*_1i;this.setValue(this.value+_4);},_2p:function(_1i,_1c){if(!_1c){_1c=300;}
else if(_1c==300){_1c=50;}
if(this._1J&&this.active){_4=(this.maxValue-this.minValue)*_1i;this.setValue(this.value+_4);var _i=this;if(this._39){window.clearTimeout(this._39);this._39=null;}
this._39=window.setTimeout(function(){_i._2p(_1i,_1c);},_1c);}},_6e:function(){this._38=this.bindDomElement(this._4j+this.elemId);this.drawKnobPos();},_3z:function(){var _7=ELEM.get(this._38);if(this._0g){_4M=this.rect.height-parseInt(_7.offsetHeight,10);}else{_4M=this.rect.width-parseInt(_7.offsetWidth,10);}
_37=_4M*((this.value-this.minValue)/(this.maxValue-this.minValue));_3p=parseInt(_37,10)+'px';return _3p;},_6w:function(_4z){_0B=this._0g?(_4z):(_4z);if(_0B<0){_0B=0;}
if(this._0g){if(_0B>this.rect.height){_0B=this.rect.height;}
return this.minValue+((_0B/this.rect.height)*(this.maxValue-this.minValue));}else{if(_0B>this.rect.width){_0B=this.rect.width;}
return this.minValue+((_0B/this.rect.width)*(this.maxValue-this.minValue));}},drawKnobPos:function(){_8d=this._0g?'top':'left';_3n=this._3z();ELEM.setStyle(this._38,_8d,_3n);}});HVSlider=HSlider.extend({packageName:"sliders",componentName:"vslider",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HVSlider]';this._4j='vsliderknob';this._0g=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
if(!_2){_2={};}
var _s=Base.extend({value:0,minValue:0,maxValue:100});_s=_s.extend(_2);_2=new _s();this.value=_2.value;this.minValue=_2.minValue;this.maxValue=_2.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._3m='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_Y){this.progressFrameHeight=_Y;},setProgressFrameNum:function(_2t){this.progressFrames=_2t;},setValue:function(_4){this.base(_4);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _Y=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_Y+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._36();}},_36:function(){this.progressbarElemId=this.bindDomElement(this._3m+this.elemId);this.drawProgress();},_3z:function(){var _37=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _3p=parseInt(Math.round(_37),10)+'px';return _3p;},drawProgress:function(){if(this.progressbarElemId){var _3n=this._3z();ELEM.setStyle(this.progressbarElemId,'width',_3n);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
if(!_2){_2={};}
var _s=Base.extend({value:0,interval:20});_s=_s.extend(_2);_2=new _s();this.type='[HProgressIndicator]';this._3m='progressmark';this.interval=_2.interval;this.value=_2.value;this._0Z=null;if(!this.isinherited){this.draw();}},setValue:function(_4){if(this._3l){if(_4==true&&!this._0Z){var temp=this;this._0Z=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._0Z);this._0Z=null;}}},die:function(){this.base();if(this._0Z){clearInterval(this._0Z);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._36();}},_36:function(){this._3l=this.bindDomElement(this._3m+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._3l){ELEM.setStyle(this._3l,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_1,_c,_2){if(!_2){_2={};}
var _s=HClass.extend({scaleToFit:true});_2=new(_s.extend(_2))();if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
this.type='[HImageView]';if(!this.isinherited){this.draw();}},_4u:function(_2u){this.elemId=ELEM.make(_2u,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_4v:function(_2u){this.elemId=ELEM.make(_2u,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_4t:function(_2u){if(this.options.scaleToFit){this._4u(_2u);}
else{this._4v(_2u);}},setValue:function(_4){this.base(_4);ELEM.setAttr(this.elemId,'src',_4);},setLabel:function(_w){this.base(_w);ELEM.setAttr(this.elemId,'alt',_w);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._4u(this._32());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._4v(this._32());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_1,_c,_2){_2=new(Base.extend({vertical:false}).extend(_2));if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HSplitView]';this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_8,_H){if(!_H){return;}
_5-=this.pageX();_8-=this.pageY();var _E=this.dividers.indexOfObject(_H);this._0E=new HPoint(_5,_8);this._2w=new HPoint(_5,_8);this._z=this._0E.subtract(_H.rect.leftTop);this._0a=this.splitviews[_E];this._N=this.splitviews[_E+1];this._H=_H;if(this.vertical==false){this._2i=this._0a.rect.top;this._2j=this._N.rect.bottom-this.dividerWidth;}else{this._2i=this._0a.rect.left;this._2j=this._N.rect.right-this.dividerWidth;}},doDrag:function(_5,_8,_H){if(!_H){return;}
_5-=this.pageX();_8-=this.pageY();if(this.vertical==false){var _n=_8-this._z.y;if(_n<this._2i||_n>this._2j){return;}
this._0a.rect.setHeight(_n);this._0a.rect.updateSecondaryValues();this._0a.setStyle('height',this._0a.rect.height+'px',true);this._H.rect.setTop(_n);this._H.rect.updateSecondaryValues();this._H.setStyle('top',this._H.rect.top+'px',true);this._N.rect.setTop(_n+this.dividerWidth);this._N.rect.updateSecondaryValues();this._N.setStyle('top',this._N.rect.top+'px',true);this._N.setStyle('height',this._N.rect.height+'px',true);}else{var _n=_5-this._z.x;if(_n<this._2i||_n>this._2j){return;}
this._0a.rect.setRight(_n);this._0a.rect.updateSecondaryValues();this._0a.setStyle('width',this._0a.rect.width+'px',true);this._H.rect.setLeft(_n);this._H.rect.updateSecondaryValues();this._H.setStyle('left',this._H.rect.left+'px',true);this._N.rect.setLeft(_n+this.dividerWidth);this._N.rect.updateSecondaryValues();this._N.setStyle('left',this._N.rect.left+'px',true);this._N.setStyle('width',this._N.rect.width+'px',true);}},endDrag:function(_5,_8,_H){this.doDrag(_5,_8);delete this._0E;delete this._2w;delete this._z;delete this._0a;delete this._N;delete this._H;delete this._2i;delete this._2j;},addSplitViewItem:function(_0z,_E){if(_E!==undefined){this.splitviews.splice(_E,0,_0z);}else{this.splitviews.push(_0z);}},removeSplitViewItem:function(_0z){if(typeof _0z=="object"){var _E=this.splitviews.indexOfObject(_0z);if(_E!=-1){this.splitviews.splice(_E,1);_0z.die();this.dividers.splice(_E,1);this.dividers[_E].die();}}},setVertical:function(_9){this.vertical=_9;this.options.vertical=_9;},adjustViews:function(){var _0m=this.splitviews.length;var _2r;var _19;var _2x;var _1d;if(this.vertical==false){_2r=this.rect.height-this.dividerWidth*(_0m-1);_19=0;for(var i=0;i<_0m;i++){_19+=this.splitviews[i].rect.height;}
_2x=_2r/_19;_1d=0;for(var i=0;i<_0m;i++){var _l=this.splitviews[i];var _17=_l.rect.height*_2x;if(i==_0m-1){_17=Math.floor(_17);}else{_17=Math.ceil(_17);}
_l.rect.offsetTo(0,_1d);_l.rect.setSize(this.rect.width,_17);_l.draw();_1d+=_17+this.dividerWidth;}}else{_2r=this.rect.width-this.dividerWidth*(_0m-1);_19=0;for(var i=0;i<_0m;i++){_19+=this.splitviews[i].rect.width;}
_2x=_2r/_19;_1d=0;for(var i=0;i<_0m;i++){var _l=this.splitviews[i];var _18=_l.rect.width*_2x;if(i==_0m-1){_18=Math.floor(_18);}else{_18=Math.ceil(_18);}
_l.rect.offsetTo(_1d,0);_l.rect.setSize(_18,this.rect.height);_l.draw();_1d+=_18+this.dividerWidth;}}
this.draw();},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();},refresh:function(){this.base();if(this.drawn){var _0m=this.splitviews.length;var _R;for(var i=0;i<(_0m-1);i++){_R=new HRect(this.splitviews[i].rect);if(!this.vertical){_R.offsetTo(_R.left,_R.bottom);_R.setHeight(this.dividerWidth);}else{_R.offsetTo(_R.right,_R.top);_R.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_R,this);}else{var _l=this.dividers[i];_l.rect.offsetTo(_R.left,_R.top);_l.rect.setSize(_R.width,_R.height);_l.draw();}}}}});HStepper=HButton.extend({componentName:"stepper",constructor:function(_1,_c,_2){if(!_2){_2={};}
_2.events={mouseDown:true,keyDown:true,mouseWheel:true};var _s=Base.extend({minValue:0,value:0,interval:500});_s=_s.extend(_2);_2=new _s();if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.interval=_2.interval;this.type='[HStepper]';this._8a="stepperlabel";this.border=((_1.bottom-_1.top)/2+_1.top);if(!this.isinherited){this.draw();}},stepUp:function(_4){_4--;_4=(_4<this.minValue)?this.maxValue:_4;this.setValue(_4);},stepDown:function(_4){_4++;_4=(_4>this.maxValue)?this.minValue:_4;this.setValue(_4);},mouseDown:function(_5,_8,_X){this.setMouseUp(true);var temp=this;if(_8<this.border){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}else{this.stepDown(this.value);this.counter=setInterval(function(){temp.stepDown(temp.value);},this.interval);}},mouseUp:function(_5,_8,_X){clearInterval(this.counter);},blur:function(){clearInterval(this.counter);},keyDown:function(_F){this.setKeyUp(true);var temp=this;if(_F==Event.KEY_UP){this.stepUp(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}
else if(_F==Event.KEY_DOWN){this.stepDown(this.value);this.counter=setInterval(function(){temp.stepUp(temp.value);},this.interval);}},keyUp:function(_F){clearInterval(this.counter);},mouseWheel:function(_Q){if(_Q>0){this.stepUp(this.value);}
else{this.stepDown(this.value);}}});HRadiobutton=HToggleButton.extend({componentName:"radiobutton",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HRadiobutton]';if(!this.isinherited){this.draw();}},setValueMatrix:function(_5k){this.valueMatrix=_5k;this.valueMatrixIndex=this.valueMatrix.addValue(this.valueObj,this.value);},click:function(x,y,_T){this.base(x,y,_T);if(undefined!==this.valueMatrix&&this.valueMatrix instanceof HValueMatrix){this.valueMatrix.setValue(this.valueMatrixIndex);}}});HRadioButton=HRadiobutton;HPasswordControl=HTextControl.extend({componentName:"passwordcontrol",constructor:function(_1,_c,_2){this.base(_1,_c,_2);}});HDivider=HControl.extend({componentName:"divider",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HDivider]';this.preserveTheme=true;this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_5,_8){this.parent.startDrag(_5,_8,this);},doDrag:function(_5,_8){this.parent.doDrag(_5,_8,this);},endDrag:function(_5,_8){this.parent.endDrag(_5,_8,this);},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this.drawn=true;}
this.refresh();}});HCheckbox=HToggleButton.extend({componentName:"checkbox",constructor:function(_1,_c,_2){if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HCheckbox]';if(!this.isinherited){this.draw();}}});