
var HClass=function(){if(arguments.length){var _3A=arguments[0];if(this==window){HClass.prototype.extend.call(_3A,arguments.callee.prototype);}else{this.extend(_3A);}}};HClass.prototype={extend:function(_0k,_4){var _1C=HClass.prototype.extend;if(arguments.length==2){var _2I=this[_0k];if((_2I instanceof Function)&&(_4 instanceof Function)&&_2I.valueOf()!=_4.valueOf()&&(/\bbase\b/).test(_4)){var _3g=_4;_4=function(){var _6y=this.base;this.base=_2I;var _6F=_3g.apply(this,arguments);this.base=_6y;return _6F;};_4.valueOf=function(){return _3g;};_4.toString=function(){return String(_3g);};}
return this[_0k]=_4;}else if(_0k){var _0s={toSource:null};var _4L=["toString","valueOf"];if(HClass._3o){_4L.push("constructor");}
for(var i=0;(_A=_4L[i]);i++){if(_0k[_A]!=_0s[_A]){_1C.call(this,_A,_0k[_A]);}}
for(var _A in _0k){if(!_0s[_A]){_1C.call(this,_A,_0k[_A]);}}}
return this;},base:function(){}};HClass.extend=function(_0q,_3s){var _1C=HClass.prototype.extend;if(!_0q){_0q={};}
HClass._3o=true;var _0s=new this;_1C.call(_0s,_0q);var _0Y=_0s.constructor;_0s.constructor=this;delete HClass._3o;var _0O=function(){if(!HClass._3o){_0Y.apply(this,arguments);}
this.constructor=_0O;};_0O.prototype=_0s;_0O.extend=this.extend;_0O.implement=this.implement;_0O.toString=function(){return String(_0Y);};_1C.call(_0O,_3s);var _3j=_0Y?_0O:_0s;if(_3j.init instanceof Function){_3j.init();}
return _3j;};HClass.implement=function(_1G){if(_1G instanceof Function){_1G=_1G.prototype;}
this.prototype.extend(_1G);};var Base=HClass;if([].indexOf===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_5r){var i=0,l=this.length;for(;i<l;i++){if(this[i]==_5r){return i;}}
return-1;}});}
is_ie=!(navigator.userAgent.toLowerCase().indexOf("opera")>-1)&&navigator.appName=="Microsoft Internet Explorer";Array.prototype.toQueryString=function(){var i,l=this.length,_3F=[];for(i=0;i<l;i++){_3F.push(encodeURIComponent(this[i].key)+"="+
encodeURIComponent(this[i].value));}
return _3F.join("&");};Ajax=HClass.extend({constructor:null,getTransport:function(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(is_ie){if(ScriptEngineMajorVersion()>=5){return new ActiveXObject("Msxml2.XMLHTTP");}else{return new ActiveXObject("Microsoft.XMLHTTP");}}else{return false;}}});Ajax.Request=HClass.extend({constructor:function(_o,_2){this.transport=Ajax.getTransport();if(!_2){_2={};}
var _s=HClass.extend({method:"post",asynchronous:true,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:""});_s=_s.extend(_2);this.options=new _s();this.request(_o);},request:function(_o){this.url=_o;if(this.options.method=="get"&&this.options.parameters.length){this.url+=(this.url.indexOf("?")>=0?"&":"?")+this.options.parameters.toQueryString();}
this.transport.open(this.options.method.toUpperCase(),this.url,this.options.asynchronous,this.options.username,this.options.password);var _m=this;this.transport.onreadystatechange=function(){_m.onStateChange();};this.setRequestHeaders();var _5t=this.options.method=="post"?(this.options.postBody||this.options.parameters.toQueryString()):null;this.transport.send(_5t);if(!this.options.asynchronous&&this.transport.overrideMimeType){this.onStateChange();}},setRequestHeaders:function(){var headers={};if(this.options.method=="post"){headers["Content-type"]=this.options.contentType+
(this.options.encoding?"; charset="+this.options.encoding:"");if(this.transport.overrideMimeType&&(navigator.userAgent.match(/Gecko\/(\d{4})/)||[0,2005])[1]<2005){headers["Connection"]="close";}}
var o;for(o in headers){this.transport.setRequestHeader(o,headers[o]);}},onStateChange:function(){var _1L=this.transport.readyState;if(_1L>1){this.respondToReadyState(_1L);}},respondToReadyState:function(_1L){if(_1L==4){(this.options["on"+(this.success()?"Success":"Failure")]||(function(){console.log('aa');}))(this.transport);}
if(_1L==4){this.transport.onreadystatechange=function(){};}},success:function(){return(this.transport.status>=200&&this.transport.status<300);}});ELEMTickerInterval=10;ELEM={_0Y:function(){var _0=ELEM;_0._7w=[];_0._5K=null;_0._7x=false;_0._initDone=false;_0._7P=0;_0._setStyleCount=0;_0._setStyleDiffCount=0;_0._7E=0;_0._getStyleMissCount=0;_0._flushLoopCount=0;_0._flushLoopFlushedCount=0;_0._flushStylCount=0;_0._flushTime=0;_0._flushCounter=0;_0._49=500;_0._timer=null;_0._16=ELEMTickerInterval;_0._flushing=false;_0._needFlush=false;_0._4U=1;_0._K=[];_0._L={_70:[]};_0._4X={};_0._0R={};_0._0d={};_0._0u={};_0._3W=[];_0._2X={};_0._blockElems=",ADDRESS,BLOCKQUOTE,CENTER,DIR,DIV,DL,FIELDSET,FORM,H1,H2,H3,H4,H5,H6,HR,ISINDEX,MENU,NOFRAMES,NOSCRIPT,OL,P,PRE,TABLE,UL,";},_7A:function(_3S,_x){var _0=ELEM,i=0,_5a=[],_L=_0._4e(_x),_1h=_L._1h;for(;i!=_3S;i++){_5a.push(_0.make(_1h,_x));}
for(i=0;i!=_3S;i++){_0.del(_5a[i]);}},_5m:function(_7){var _3,_0,_K;_0=ELEM;_K=_0._K;_K.push(_7);_3=_K.length-1;return _3;},_7H:function(_3){var _0=ELEM;_0._0R[_3]=[];_0._4X[_3]={};_0._0d[_3]=[];_0._0u[_3]={};_0._2X[_3]=false;},bindId:function(_5J){var _0=ELEM,_7=document.getElementById(_5J),_a=_0._5m(_7);_0._7H(_a);return _a;},bind:function(_7){var _3,_0=ELEM;_3=_0._5m(_7);_0._7H(_3);return _3;},_7T:function(_3,_7){var _0=ELEM;_0._K[_3]=_7;},get:function(_3){return ELEM._K[_3];},setHTML:function(_3,_1F){var _0=ELEM;_0._K[_3].innerHTML=_1F;},_4e:function(_x){var _0=ELEM,_L=_0._L;if(!_L[_x]){_L._70.push(_x);_L[_x]=[];_L[_x]._24=1;_L[_x]._1s=0;_L[_x]._1h=_0.make(_0._1h,'div');}
return _L[_x]._1h;},del:function(_3){var _0=ELEM,_7=_0._K[_3],_x=_7.tagName,_1h;_1h=_0._4e(_x);_0.append(_3,_1h);var _3X=_0._3W.indexOf(_3),_L=_0._L[_x];if(_3X!=-1){_0._3W.splice(_3X,1);}
try{_7.innerHTML='';}catch(e){}
_0.setCSS(_3,'display:none;');_0.delAttr(_3,'id');_0.delAttr(_3,'ctrl');_0._7H(_3);_L._24++;_L.push(_3);},append:function(_6L,_1T){var _0k,_3v,_0;_0=ELEM;_0k=_0._K[_6L];_3v=_0._K[_1T];_3v.appendChild(_0k);},setCSS:function(_3,_7u){ELEM._K[_3].style.cssText=_7u;},getCSS:function(_3){return ELEM._K[_3].style.cssText;},getVisibleSize:function(_3){var _0,_7,w,h,_u,_2v,_0=ELEM,_7=_0._K[_3],w=_7.offsetWidth,h=_7.offsetHeight,_u=_7.parentNode;while(_u&&_u.nodeName.toLowerCase()!='body'){if(!_0._2e){_2v=document.defaultView.getComputedStyle(_u,null).getPropertyValue('overflow');}
else{_2v=_u.currentStyle.getAttribute('overflow');}
_2v=_2v!='visible';if(w>_u.clientWidth&&_2v){w=_u.clientWidth-_7.offsetLeft;}
if(h>_u.clientHeight&&_2v){h=_u.clientHeight-_7.offsetTop;}
_7=_7.parentNode;_u=_7.parentNode;}
return[w,h];},getSize:function(_3){var _0,_7,w,h,_u,_2v,_0=ELEM,_7=_0._K[_3],w=_7.offsetWidth,h=_7.offsetHeight;return[w,h];},getScrollSize:function(_3){var _0,_7,w,h,_u,_2v,_0=ELEM,_7=_0._K[_3],w=_7.scrollWidth,h=_7.scrollHeight;return[w,h];},getVisiblePosition:function(_3){var x,y,_7,_0,_0=ELEM,x=0,y=0,_7=_0._K[_3];while(_7!==document){x+=_7.offsetLeft;y+=_7.offsetTop;x-=_7.scrollLeft;y-=_7.scrollTop;_7=_7.parentNode;if(!_7){break;}}
return[x,y];},getOpacity:function(_3){var _0,_02,_3y,_2b;_0=ELEM;_2b=_0.getStyle;if(_02=_2b(_3,'-khtml-opacity')){return parseFloat(_02);}
if(_02=_2b(_3,'-moz-opacity')){return parseFloat(_02);}
_3y=_2b(_3,'opacity',true);if(_02=_3y||(_3y==0)){return parseFloat(_02);}
if(_02=(_0._K[_3].currentStyle['filter']||'').match(/alpha\(opacity=(.*)\)/)){if(_02[1]){return parseFloat(_02[1])/100;}}
return 1.0;},setOpacity:function(_3,_4){var _0=ELEM;if(_4==1&&is_ie){_0._K[_3].style.setAttribute('filter',_0.getStyle(_3,'filter',true).replace(/alpha\([^\)]*\)/gi,''));}else{if(_4<0.00001){_4=0;}
if(_0._2e){_0._K[_3].style.setAttribute('filter',_0.getStyle(_3,'filter',true).replace(/alpha\([^\)]*\)/gi,'')+'alpha(opacity='+_4*100+')');}else{_0._K[_3].style.setProperty('opacity',_4,'');}}},getIntStyle:function(_3,_f){var _4=ELEM.getStyle(_3,_f);return parseInt(_4,10);},setBoxCoords:function(_3,_06){ELEM.setStyle(_3,'left',_06[0]+'px');ELEM.setStyle(_3,'top',_06[1]+'px');ELEM.setStyle(_3,'width',_06[2]+'px');ELEM.setStyle(_3,'height',_06[3]+'px');},getExtraWidth:function(_3){var _0r=ELEM.getIntStyle;return _0r(_3,'padding-left')+_0r(_3,'padding-right')+_0r(_3,'border-left-width')+_0r(_3,'border-right-width');},getExtraHeight:function(_3){var _0r=ELEM.getIntStyle;return _0r(_3,'padding-top')+_0r(_3,'padding-bottom')+_0r(_3,'border-top-width')+_0r(_3,'border-bottom-width');},setFPS:function(_0p){ELEM._16=1000/_0p;if(ELEM._16<ELEMTickerInterval){ELEM._16=ELEMTickerInterval;}},setSlowness:function(_4U){ELEM._4U=_4U;},setIdleDelay:function(_49){ELEM._49=_49;},_7G:false,flushLoop:function(_08){var _0=ELEM;_0._flushLoopCount++;if(_0._15&&(_0._flushLoopCount%5==0)&&_0._7G){iefix._05();_0._7G=false;}
clearTimeout(_0._timer);if(_0._flushing){_08*=2;_0._timer=setTimeout('ELEM.flushLoop('+_08+');',_08);return;}else{if(!_0._needFlush){if(_0._15&&_0._7G){iefix._05();_0._7G=false;}
_0._timer=setTimeout('ELEM.flushLoop('+_08+');',_0._49);return;}
_08=parseInt(_0._4U*(_0._flushTime/_0._flushCounter),ELEMTickerInterval);if(_08<_0._16||!_08){_08=_0._16;}
_0._flushing=true;_0._timer=setTimeout('ELEM.flushLoop('+_08+');',_08);}
_0._flushTime-=new Date().getTime();var _3d,_1w,i,_0R;_3W=_0._3W;_3d=_3W.length;_1w=_3W.splice(0,_3d);var _5V=new Date().getTime();for(i=0;i<_3d;i++){_0._flushLoopFlushed++;var _3=_1w.pop();_0._2X[_3]=false;_0._5W(_3);_0._7B(_3);}
_0._flushCounter++;_0._flushTime+=new Date().getTime();if(_0._3W.length==0&&_0._needFlush){_0._needFlush=false;}
_0._flushing=false;},_7B:function(_3){var _0=ELEM,_0d=_0._0d[_3],_0u=_0._0u[_3],_7=_0._K[_3],_f,_0S,i,_48=_0d.length,_1w=_0d.splice(0,_48);for(i=0;i!=_48;i++){_f=_1w.pop();_0S=_0u[_f];_7.setAttribute(_f,_0S);}},getAttr:function(_3,_f,_0v){var _0=ELEM,_22=_0._0u[_3][_f],_0S;if(_22!==undefined&&!_0v){return _22;}
var _7=_0._K[_3];if(_7.getAttribute(_f)==null){_7[_f]='';}
_0S=_7.getAttribute(_f);_0._0u[_3][_f]=_0S;return _0S;},setAttr:function(_3,_f,_4,_0v){var _1x,_0=ELEM,_0d=_0._0d[_3],_0u=_0._0u[_3];_1x=_4!=_0.getAttr(_3,_f);if(_1x){_0u[_f]=_4;if(_0v){_0._K[_3].setAttribute(_f,_4);}
else{if(_0d.indexOf(_f)==-1){_0d.push(_f);}
if(!_0._2X[_3]){_0._3W.push(_3);_0._2X[_3]=true;_0._7r();}}}},delAttr:function(_3,_f){var _1x,_0=ELEM,_0d=_0._0d[_3],_0u=_0._0u[_3];delete _0u[_f];_0._K[_3].removeAttribute(_f);if(_0d.indexOf(_f)!=-1){_0d.splice(_0d.indexOf(_f,1));}
if(_0._2X[_3]){_0._3W.splice(_0._3W.indexOf(_3,1));_0._2X[_3]=false;_0._7r();}},hasClassName:function(_a,_0V){var _6=ELEM.get(_a);if(!_6)return;var _41=false;var _0W=_6.className.split(' ');for(var i=0;i<_0W.length;i++){if(_0W[i]==_0V){_41=true;}}
return _41;},addClassName:function(_a,_0V){var _6=ELEM.get(_a);if(!_6)return;ELEM.removeClassName(_a,_0V);_6.className+=' '+_0V;},removeClassName:function(_a,_0V){var _6=ELEM.get(_a);if(!_6)return;var _3i='';var _0W=_6.className.split(' ');for(var i=0;i<_0W.length;i++){if(_0W[i]!=_0V){if(i>0)_3i+=' ';_3i+=_0W[i];}}
_6.className=_3i;},_7r:function(){var _0=ELEM;if(!_0._needFlush){_0._needFlush=true;if(!_0._flushing){clearTimeout(_0._timer);_0._timer=setTimeout('ELEM.flushLoop('+_0._16+');',_0._16);}}},printStats:function(){var _0=ELEM,_L=_0._L,i=0,_x,_6Z,_24,_1s;console.log('Recycler efficiency:');var _2H=0;for(;i!=_L._70.length;i++){_x=_L._70[i];console.log(' tagName: '+_x);_6Z=_L[_x].length;console.log('   length  : '+_6Z);_24=_L[_x]._24;console.log('   countIn : '+_24);_1s=_L[_x]._1s;_2H+=_1s;console.log('   countOut: '+_1s);console.log('--------------------------------');}
console.log('================================');console.log('Flushing efficiency:');console.log('  total real time spent: '+_0._flushTime+'ms');console.log('  total times called:    '+_0._flushLoopCount);console.log('  total times flushed:   '+_0._flushCounter);console.log('  total items flushed:   '+_0._flushLoopFlushedCount);console.log('  total real style sets: '+_0._flushStylCount);console.log('================================');console.log('setStyle efficiency:');console.log('  total times called:    '+_0._setStyleCount);console.log('  total times non-cache: '+_0._setStyleDiffCount);console.log('================================');console.log('getStyle efficiency:');console.log('  total times called:    '+_0._7E);console.log('  total times non-cache: '+_0._getStyleMissCount);console.log('================================');console.log('Summary:');console.log('  recycler saved '+(_2H)+' of '+_0._7P+' ('+Math.round(_2H/_0._7P*100)+'%) document.createElement calls');console.log('  style buffer saved '+(_0._setStyleDiffCount-_0._flushStylCount)+' of '+_0._setStyleDiffCount+' ('+Math.round(((_0._setStyleDiffCount-_0._flushStylCount)/_0._setStyleDiffCount)*100)+'%) non-cached DOM style sets');console.log('  style cache saved '+(_0._setStyleCount-_0._setStyleDiffCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._setStyleDiffCount)/_0._setStyleCount)*100)+'%) DOM style sets');console.log('  style cache saved '+(_0._7E-_0._getStyleMissCount)+' of '+_0._7E+' ('+Math.round(((_0._7E-_0._getStyleMissCount)/_0._7E)*100)+'%) DOM style gets');console.log('  style buffer and cache saved '+(_0._setStyleCount-_0._flushStylCount)+' of '+_0._setStyleCount+' ('+Math.round(((_0._setStyleCount-_0._flushStylCount)/_0._setStyleCount)*100)+'%) total DOM style sets');},setStyle:function(_3,_f,_4,_0v){var _0=ELEM,_y=_0._4X[_3],_3Y=_0._K,_1x,_0R;_0._setStyleCount++;_1x=_4!==_y[_f];if(_1x){_0._setStyleDiffCount++;_y[_f]=_4;if(_0v){if(_f=='opacity'){_0.setOpacity(_3,_4);}
else{_0._2e?(_3Y[_3].style.setAttribute(_f.replace(/((-)([a-z])(\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4;}),_y[_f])):(_3Y[_3].style.setProperty(_f,_y[_f],''));}
if(_0._15){if(iefix._2B.indexOf(_f)!=-1){_0._7G=true;}}}else{_2X=_0._2X;_0R=_0._0R[_3];if(_0R.indexOf(_f)==-1){_0R.push(_f);}
if(!_2X[_3]){_0._3W.push(_3);_2X[_3]=true;_0._7r();}}}},make:function(_1T,_x){if(_1T===undefined){_1T=0;}
if(_x===undefined){_x='DIV';}else{_x=_x.toUpperCase();}
var _0=ELEM,_7,_3;_0._7P++;if(_0._L[_x]){if(_0._L[_x].length!=0){_3=_0._L[_x].pop();_0._L[_x]._1s++;_7=_0._K[_3];if(_0._blockElems.indexOf(','+_x+',')!=-1){_0.setCSS(_3,'display:block;');}else{_0.setCSS(_3,'display:inline;');}
_0.append(_3,_1T);return _3;}}
_7=document.createElement(_x);_0._K[_1T].appendChild(_7);_3=_0._5m(_7);_0._7H(_3);return _3;},windowSize:function(){var _0n,_64;_0n=(window.innerWidth)?window.innerWidth:document.documentElement.clientWidth;_64=(window.innerHeight)?window.innerHeight:document.documentElement.clientHeight;return[_0n,_64];},_4c:function(){var _0=ELEM,_0K,_2P;var _33=["ELEM.getStyle=function(_3,_f,_0v){","var _0=ELEM,_y=_0._4X[_3],_1N;_0._7E++;","if((_y[_f]===undefined)||_0v){","if(!_0v){_0._getStyleMissCount++;}","if((_f=='opacity')&&_0v){_1N=_0.getOpacity(_3);}","else{","_1N=document.defaultView.getComputedStyle(_0._K[_3],null).getPropertyValue(_f);","_5v=_f.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){","return $3.toUpperCase()+$4});","_1N=_0._K[_3].currentStyle[_5v];","}_y[_f]=_1N;","}return _y[_f];};"];if(_0._2e){_33.splice(6,1);}else{_33.splice(7,3);}
eval(_33.join(''));var _2Z=["ELEM._5W=function(_3){","var _0=ELEM,_0R=_0._0R[_3],_y=_0._4X[_3],_7=_0._K[_3],_1A,_4r,_3N,_f,_1w,_1N;","if(!_7){return;}","_1A=_7.style;","_4r=_0R.length;","_1w=_0R.splice(0,_4r);","for(_3N=0;_3N!=_4r;_3N++){","_f=_1w.pop();_0._flushStylCount++;","if(_f=='opacity'){_1N=_0.getOpacity(_3,_y[_f]);}else{","if(_0._15){if(iefix._2B.indexOf(_f)!=-1){_0._7G=true;}}try{_1A.setAttribute(_f.replace(/((-)([a-z])(\\w))/g,function($0,$1,$2,$3,$4){return $3.toUpperCase()+$4}),_y[_f]);}catch(e){}}}};","_1A.setProperty(_f,_y[_f],'');}}};"];if(_0._2e){_2Z.pop();}else{_2Z.splice(9,1);}
eval(_2Z.join(''));_0.bind(document.body);_0._1h=_0.make(0,'div');_0.setCSS(_0._1h,"display:none;visibility:hidden;");_0.setAttr(_0._1h,'id','trashcan_'+_0._1h);_0._timer=setTimeout('ELEM.flushLoop('+_0._16+')',_0._16);if(!_0._7w){return;}
while(_0._7w.length!=0){_0K=_0._7w.shift();if(typeof _0K=='string'){_2P=eval(_0K);if(typeof _2P=='string'){_0._7w.push(_2P);}}}
_0._initDone=true;},_7c:function(){_0=ELEM;_0._2e=(document.all&&navigator.userAgent.indexOf("Opera")==-1);_0._15=(_0._2e&&navigator.userAgent.indexOf("MSIE 6")!=-1);_0._7K=(_0._2e&&navigator.userAgent.indexOf("MSIE 7")!=-1);_0._7M=(navigator.userAgent.indexOf("KHTML")!=-1);_0._is_ff=(navigator.userAgent.indexOf("Firefox")!=-1);_0._7L=(navigator.userAgent.indexOf("Opera")!=-1);_0._5M();},_5L:function(_0K){var _0=ELEM;if(typeof _0K=='string'){if(_0._initDone==true){eval(_0K);}else{_0._7w.push(_0K);}}},_5M:function(){var _7N=false;var _0=ELEM;if(_0._2e){var _4a="javascript:void(0)";if(location.protocol=="https:"){_4a="src=//0";}
document.write("<scr"+"ipt id=_5j defer src="+_4a+"><\/scr"+"ipt>");var _6c=document.getElementById("_5j");_6c.onreadystatechange=function(){if(this.readyState=="complete"){ELEM._7x=true;ELEM._4c();delete ELEM._7w;clearTimeout(ELEM._5K);delete ELEM._5K;}};return;}
else if((/KHTML|WebKit/i.test(navigator.userAgent))&&(/loaded|complete/.test(document.readyState))){_0._7x=true;}
else if(document.body){_0._7x=true;}
if(!_0._7x){_0._5K=setTimeout('ELEM._5M()',ELEMTickerInterval*10);}else{_0._4c();delete _0._7w;clearTimeout(_0._5K);delete _0._5K;}}};ELEM._0Y();LOAD=ELEM._5L;ELEM._7c();Event={element:function(e){return e.target||e.srcElement;},pointerX:function(e){return e.pageX||e.clientX+document.documentElement.scrollLeft;},pointerY:function(e){return e.pageY||e.clientY+document.documentElement.scrollTop;},stop:function(e){if(e.preventDefault){e.preventDefault();e.stopPropagation();}
else{e.returnValue=false;e.cancelBubble=true;}},isLeftClick:function(e){if(ELEM._2e||ELEM._7M){return(e.button==1);}
else{return(e.button==0);}},observers:false,_6n:function(_7,_A,_1E,_1V){if(!Event.observers){Event.observers=[];}
if(_7.addEventListener){this.observers.push([_7,_A,_1E,_1V]);_7.addEventListener(_A,_1E,_1V);}
else if(_7.attachEvent){this.observers.push([_7,_A,_1E,_1V]);_7.attachEvent("on"+_A,_1E);}},unloadCache:function(){if(!Event.observers){return;}
var i,l=Event.observers.length;for(i=0;i<l;i++){Event.stopObserving.apply(this,Event.observers[0]);}
Event.observers=false;},observe:function(_7,_A,_1E,_1V){_1V=_1V||false;Event._6n(_7,_A,_1E,_1V);},stopObserving:function(_7,_A,_1E,_1V){_1V=_1V||false;if(_7.removeEventListener){_7.removeEventListener(_A,_1E,_1V);}
else if(detachEvent){_7.detachEvent("on"+_A,_1E);}
var i=0;while(i<Event.observers.length){var eo=Event.observers[i];if(eo&&eo[0]==_7&&eo[1]==_A&&eo[2]==_1E&&eo[3]==_1V){Event.observers[i]=null;Event.observers.splice(i,1);}
else{i++;}}},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34};if(ELEM._2e){Event.observe(window,"unload",Event.unloadCache,false);}
_3U={mouseMove:false,mouseDown:false,click:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,isDragged:false,textEnter:false};EVENT={status:[false,false,0,0,[],false,false,false],button1:0,button2:1,crsrX:2,crsrY:3,keysDown:4,altKeyDown:5,ctrlKeyDown:6,shiftKeyDown:7,start:function(){var _34,_2Y,i,_0=EVENT;if(ELEM._2e){_34=document;}
else{_34=window;}
_2Y=[['mousemove',EVENT.mouseMove],['mouseup',EVENT.mouseUp],['mousedown',EVENT.mouseDown],['click',EVENT.click],['keyup',EVENT.keyUp],['keydown',EVENT.keyDown],['keypress',EVENT.keyPress],['contextmenu',EVENT.contextMenu],['resize',EVENT.resize],['mousewheel',EVENT.mouseWheel]];for(i=0;i!=_2Y.length;i++){Event.observe(_34,_2Y[i][0],_2Y[i][1]);}
if(window.addEventListener){window.addEventListener('DOMMouseScroll',EVENT.mouseWheel,false);}
_0.listeners=[];_0.focused=[];_0.resizeListeners=[];_0.coordListeners=[];_0.focusOptions={};_0.dragItems=[];_0.hovered=[];_0.hoverInterval=50;_0.hoverTimer=new Date().getTime();_0.topmostDroppable=null;_0.textEnterCtrls=[];_0._2Q=[];_0._coordCacheFlag=true;_0._lastCoordFlushTimeout=null;_0.activeControl=null;_0._lastKeyDown=null;},coordCacheFlush:function(_a){if(_a){EVENT._2Q[_a]=null;}
else{EVENT._2Q=[];}},reg:function(_d,_0y){var _a,_7,_0=EVENT,_6z;_a=_d.elemId;_7=ELEM.get(_a);if(ELEM._2e){_7.setAttribute('ctrl',_d);}
else{_7.ctrl=_d;}
_0.listeners[_a]=true;_0.focused[_a]=false;for(var _6z in _3U){if(_0y[_6z]===undefined){_0y[_6z]=_3U[_6z];}}
_0.focusOptions[_a]=_0y;var _2R=_0.coordListeners.indexOf(_a);if(_0y.mouseMove){if(_2R==-1){_0.coordListeners.push(_a);}}
else if(_2R!=-1){_0.coordListeners.splice(_2R,1);}
if(_0y.textEnter){if(_0.textEnterCtrls.indexOf(_d.viewId)==-1){_0.textEnterCtrls.push(_d.viewId);}}
if(_0y.resize){if(_0.resizeListeners.indexOf(_d.viewId)==-1){_0.resizeListeners.push(_d.viewId);}}
Event.observe(_7,'mouseover',_0._4y);},unreg:function(_d){var _0=EVENT,_a,_7;if(_d===this.activeControl){_0.changeActiveControl(null);}
_a=_d.elemId;_7=ELEM.get(_a);this.listeners[_a]=false;this.focused[_a]=false;this._2Q[_a]=null;var _54=_0.textEnterCtrls.indexOf(_d.viewId);if(_54!=-1){_0.textEnterCtrls.splice(_54,1);}
var _4N=_0.resizeListeners.indexOf(_d.viewId);if(_4N!=-1){_0.resizeListeners.splice(_4N,1);}
Event.stopObserving(_7,'mouseover',_0._4y);},resize:function(e){var i=0,_0=EVENT,_28,_d;for(;i<_0.resizeListeners.length;i++){_28=_0.resizeListeners[i];_d=HSystem.views[_28];if(_d.onResize){_d.onResize();}}},_4y:function(e){if(!Event.element){return;}
var _i=Event.element(e);while(_i&&_i.ctrl===undefined){_i=_i.parentNode;}
if(!_i){return;}
var _0=_i.ctrl;EVENT.focus(_0);Event.stop(e);},_4x:function(e){if(!Event.element){return;}
var _i=Event.element(e);while(_i&&_i.ctrl===undefined){_i=_i.parentNode;}
if(!_i){return;}
var _0=_i.ctrl;EVENT.blur(_0);Event.stop(e);},focus:function(_d){var _0=EVENT,_a,_7;_a=_d.elemId;_7=ELEM.get(_a);if(_0.focused[_a]==false&&_0.focusOptions[_a].isDragged==false){Event.stopObserving(_7,'mouseover',_0._4y);Event.observe(_7,'mouseout',_0._4x);_0.focused[_a]=true;if(_d['focus']){_d.focus();}}},blur:function(_d){var _0=EVENT,_a,_7;_a=_d.elemId;_7=ELEM.get(_a);if(_0.focused[_a]==true&&_0.focusOptions[_a].isDragged==false){Event.stopObserving(_7,'mouseout',_0._4x);Event.observe(_7,'mouseover',_0._4y);_0.focused[_a]=false;if(_d['blur']){_d.blur();}}},mouseMove:function(e){var _0=EVENT,x,y,_10;x=Event.pointerX(e);y=Event.pointerY(e);_0.status[_0.crsrX]=x;_0.status[_0.crsrY]=y;_10=_0.flushMouseMove(x,y);_0._7Q(e);if(_10){Event.stop(e);}},flushMouseMove:function(x,y){var _0=EVENT,x,y,_10,i,j,_a,_d;clearTimeout(_0._lastCoordFlushTimeout);_10=false;for(i=0;i!=_0.dragItems.length;i++){_a=_0.dragItems[i];_0.focusOptions[_a].ctrl.doDrag(x,y);_0.coordCacheFlush(_a);_10=true;}
if(new Date().getTime()>_0.hoverTimer+_0.hoverInterval){for(i=0;i!=_0.coordListeners.length;i++){_a=_0.coordListeners[i];_d=_0.focusOptions[_a].ctrl;_d.mouseMove(x,y);}
_0._8c();var _2D;for(i=0;i!=_0.dragItems.length;i++){_2D=_0.topmostDroppable;_0.topmostDroppable=null;_a=_0.dragItems[i];_d=_0.focusOptions[_a].ctrl;var _2c,_1y;for(j=0;j!=_0.hovered.length;j++){_2c=_0.hovered[j];if(_2c!=_a&&_0.focusOptions[_2c].ctrl){_1y=_0.focusOptions[_2c].ctrl;if(!_0.topmostDroppable||_1y.zIndex()>_0.topmostDroppable.zIndex()||_1y.supr===_0.topmostDroppable){if(_0.focusOptions[_1y.elemId].droppable){_0.topmostDroppable=_1y;}}}}
if(_2D!=_0.topmostDroppable){if(_2D){_2D.onHoverEnd(_d);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverStart(_d);}}}
_0.hoverTimer=new Date().getTime();}
else{_0._lastCoordFlushTimeout=setTimeout('EVENT.flushMouseMove('+x+','+y+');',_0.hoverInterval);}
return _10;},_8c:function(){var _0=EVENT,x,y,i,_d,_7,_3k,_4T,_06;_0.hovered=[];x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.listeners.length;i++){if(!_0.listeners[i]||!_0.focusOptions[i].ctrl){continue;}
_d=_0.focusOptions[i].ctrl;_7=ELEM.get(i);if(!_0._coordCacheFlag||!_0._2Q[i]){_3k=ELEM.getVisiblePosition(_d.elemId);_4T=ELEM.getVisibleSize(_d.elemId);_0._2Q[i]=[_3k[0],_3k[1],_4T[0],_4T[1]];}
_06=_0._2Q[i];if(x>=_06[0]&&x<=_06[0]+_06[2]&&y>=_06[1]&&y<=_06[1]+_06[3]){_0.hovered.push(i);}}},mouseDown:function(e,_X){var _0=EVENT,_2V,x,y,i,_B,_0D,_2o;_0._7Q(e);_2V=false;if(_X===undefined){_X=Event.isLeftClick(e);}
if(_X){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_B=null;_0D=[];_2o=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_B=_0.focusOptions[i].ctrl;}
if((_0.focusOptions[i].draggable==true)&&_0.dragItems.indexOf(i)==-1){_0D.push(i);}
else if(_0.focusOptions[i].mouseDown==true){_2o.push(i);}}}
if(_B){_0.changeActiveControl(_B);}
for(i=0;i!=_0D.length;i++){_0.dragItems.push(_0D[i]);_0.focusOptions[_0D[i]].ctrl.startDrag(x,y);_2V=true;}
var _1R=_2o.length;for(i=0;i!=_2o.length;i++){if(_0.focusOptions[_2o[i]].ctrl.mouseDown(x,y,_X)){_1R--;}}
if(_2V){document.body.focus();_0._storedOnSelectStart=document.onselectstart;document.onselectstart=function(){return false;};}
if((_1R==0)&&(_0.hovered.length!=0)&&(_B&&(_B.textElemId===false))){Event.stop(e);}
return true;},click:function(e,_X){var _0=EVENT,x,y,i,_B,_2O;_0._7Q(e);if(_X===undefined){_X=Event.isLeftClick(e);}
if(_X){_0.status[_0.button1]=true;}
else{_0.status[_0.button2]=true;}
x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];_B=null;_2O=[];for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].ctrl.enabled){_B=_0.focusOptions[i].ctrl;}
else if(_0.focusOptions[i].click==true){_2O.push(i);}}}
if(_B){_0.changeActiveControl(_B);}
var _1R=_2O.length;for(i=0;i!=_2O.length;i++){if(_0.focusOptions[_2O[i]].ctrl.click(x,y,_X)){_1R--;}}
if((_1R==0)&&(_0.hovered.length!=0)&&(_B&&(_B.textElemId===false))){Event.stop(e);}
return true;},changeActiveControl:function(_d){var _0=EVENT,_1b;_1b=_0.activeControl;if(_d!=_1b){if(_1b){_1b.active=false;_1b._6j(_d);}
_0.activeControl=null;if(_d){_d.active=true;_0.activeControl=_d;_d._5Y(_1b);}}},mouseUp:function(e){var _0=EVENT,_2U,x,y,_a,_d,i;_0._7Q(e);_2U=false;_X=Event.isLeftClick(e);_0.status[_0.button1]=false;_0.status[_0.button2]=false;x=_0.status[_0.crsrX];y=_0.status[_0.crsrY];for(i=0;i!=_0.dragItems.length;i++){_a=_0.dragItems[i];_d=_0.focusOptions[_a].ctrl;_d.endDrag(x,y);_2U=true;_0._8c();if(_0.hovered.indexOf(_a)==-1){_0.blur(_d);}
if(_0.topmostDroppable){_0.topmostDroppable.onHoverEnd(_d);_0.topmostDroppable.onDrop(_d);_0.topmostDroppable=null;}}
_0.dragItems=[];if(_2U){document.onselectstart=_0._storedOnSelectStart;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseUp==true){_0.focusOptions[i].ctrl.mouseUp(x,y,_X);}}}
return true;},keyDown:function(e){var _0=EVENT,_0l;_0._7Q(e);_0l=e.keyCode;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);if(_0._lastKeyDown!=_0l){_0.activeControl.keyDown(_0l);}}
if(_0.status[_0.keysDown].indexOf(_0l)==-1){_0.status[_0.keysDown].push(_0l);}
_0._lastKeyDown=_0l;},keyUp:function(e){var _0=EVENT,_0l,_keycodeindex;_0._7Q(e);_0l=e.keyCode;_0._lastKeyDown=null;for(var i=0;i!=_0.textEnterCtrls.length;i++){var _28=_0.textEnterCtrls[i],_d=HSystem.views[_28];if(_d.textEnter){_d.textEnter();}}
if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyUp==true){_0.activeControl.keyUp(_0l);}
_4h=_0.status[_0.keysDown].indexOf(_0l);if(_4h!=-1){_0.status[_0.keysDown].splice(_4h,1);}},keyPress:function(e){var _0=EVENT;if(_0.activeControl&&_0.focusOptions[_0.activeControl.elemId].keyDown==true){Event.stop(e);}},mouseWheel:function(e){var _0=EVENT,_Q,i;_Q=0;if(!e){e=window.event;}
if(e.wheelDelta){_Q=e.wheelDelta/120;if(window.opera){_Q=-_Q;}}
else if(e.detail){_Q=-e.detail/3;}
for(i=0;i!=_0.focused.length;i++){if(_0.focused[i]==true){if(_0.focusOptions[i].mouseWheel==true){Event.stop(e);_0.focusOptions[i].ctrl.mouseWheel(_Q);}}}},contextMenu:function(e){EVENT.mouseDown(e,false);Event.stop(e);},_7Q:function(e){var _0=EVENT;_0.status[_0.altKeyDown]=e.altKey;_0.status[_0.ctrlKeyDown]=e.ctrlKey;_0.status[_0.shiftKeyDown]=e.shiftKey;}};LOAD('EVENT.start();');SHA={_47:0,hexCase:function(){return SHA._47;},setHexCase:function(_5w){SHA._47=_5w;},_3H:"=",base64Pad:function(){return SHA._3H;},setBase64Pad:function(_6t){SHA._3H=_6t;},_3M:8,chrsz:function(){return SHA._3M;},setChrsz:function(_5s){SHA._3M=_5s;},hexSHA1:function(_0C){var _0=SHA;return _0._7o(_0._7t(_0._87(_0C),_0C.length*_0._3M));},b64SHA1:function(_0C){var _0=SHA;return _0._7n(_0._7t(_0._87(_0C),_0C.length*_0._3M));},strSHA1:function(_0C){var _0=SHA;return _0._7p(_0._7t(_0._87(_0C),_0C.length*_0._3M));},hexHmacSHA1:function(_f,_0w){var _0=SHA;return _0._7o(_0._7s(_f,_0w));},b64HmacSHA1:function(_f,_0w){var _0=SHA;return _0._7n(_0._7s(_f,_0w));},strHmacSHA1:function(_f,_0w){var _0=SHA;return _0._7p(_0._7s(_f,_0w));},str2Base64:function(_G){var _0=SHA;return _0._7n(_0._87(_G));},test:function(){return SHA.hexSHA1("abc")=="a9993e364706816aba3e25717850c26c9cd0d89d";},_7t:function(_5,_3c){var _0=SHA;_5[_3c>>5]|=0x80<<(24-_3c%32);_5[((_3c+64>>9)<<4)+15]=_3c;var _0n=new Array(80),_0I=1732584193,_P=-271733879,_V=-1732584194,_W=271733878,_12=-1009589776,i,_4C,_4D,_4E,_4F,_4G,j,_O;for(i=0;i<_5.length;i+=16){_4C=_0I;_4D=_P;_4E=_V;_4F=_W;_4G=_12;for(j=0;j<80;j++){if(j<16){_0n[j]=_5[i+j];}
else{_0n[j]=_0._82(_0n[j-3]^_0n[j-8]^_0n[j-14]^_0n[j-16],1);}
_O=_0._83(_0._83(_0._82(_0I,5),_0._84(j,_P,_V,_W)),_0._83(_0._83(_12,_0n[j]),_0._85(j)));_12=_W;_W=_V;_V=_0._82(_P,30);_P=_0I;_0I=_O;}
_0I=_0._83(_0I,_4C);_P=_0._83(_P,_4D);_V=_0._83(_V,_4E);_W=_0._83(_W,_4F);_12=_0._83(_12,_4G);}
return[_0I,_P,_V,_W,_12];},_84:function(_O,_P,_V,_W){if(_O<20){return(_P&_V)|((~_P)&_W);}
if(_O<40){return _P^_V^_W;}
if(_O<60){return(_P&_V)|(_P&_W)|(_V&_W);}
return _P^_V^_W;},_85:function(_O){return(_O<20)?1518500249:(_O<40)?1859775393:(_O<60)?-1894007588:-899497514;},_7s:function(_f,_0w){var _0=SHA,_1n=_0._87(_f),_4g=new Array(16),_4H=new Array(16),i,_43;if(_1n.length>16){_1n=_0._7t(_1n,_f.length*_0._3M);}
for(i=0;i<16;i++){_4g[i]=_1n[i]^0x36363636;_4H[i]=_1n[i]^0x5C5C5C5C;}
_43=_0._7t(_4g.concat(_0._87(_0w)),512+_0w.length*_0._3M);return _0._7t(_4H.concat(_43),512+160);},_83:function(_5,_8){var _4s=(_5&0xFFFF)+(_8&0xFFFF),_6k=(_5>>16)+(_8>>16)+(_4s>>16);return(_6k<<16)|(_4s&0xFFFF);},_82:function(_2t,_3O){return(_2t<<_3O)|(_2t>>>(32-_3O));},_87:function(_G){var _0=SHA,_1m=[],_3f=(1<<_0._3M)-1,_6R=_G.length*_0._3M,i;for(i=0;i<_6R;i+=_0._3M){_1m[i>>5]|=(_G.charCodeAt(i/_0._3M)&_3f)<<(32-_0._3M-i%32);}
return _1m;},_7p:function(_1m){var _0=SHA,_G="",_3f=(1<<_0._3M)-1,i,_2L=_1m.length*32,_5i=32-_0._3M;for(i=0;i<_2L;i+=_0._3M){_G+=String.fromCharCode((_1m[i>>5]>>>(_5i-i%32))&_3f);}
return _G;},_7o:function(_0o){var _0=SHA,_46=_0._47?"0123456789ABCDEF":"0123456789abcdef",_G="",i,_2K=_0o.length*4;for(i=0;i<_2K;i++){_G+=_46.charAt((_0o[i>>2]>>((3-i%4)*8+4))&0xF)+
_46.charAt((_0o[i>>2]>>((3-i%4)*8))&0xF);}
return _G;},_7n:function(_0o){var _0=SHA,_1g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",_G="",i,_2K=_0o.length*4,_50,_51,_7g,_5b,j,_2L=_0o.length*32;for(i=0;i<_2K;i+=3){_50=(((_0o[i>>2]>>8*(3-i%4))&0xFF)<<16);_51=(((_0o[i+1>>2]>>8*(3-(i+1)%4))&0xFF)<<8);_6X=((_0o[i+2>>2]>>8*(3-(i+2)%4))&0xFF);_5b=(_50|_51|_6X);for(j=0;j<4;j++){if(i*8+j*6>_2L){_G+=_0._3H;}
else{_G+=_1g.charAt((_5b>>6*(3-j))&0x3F);}}}
return _G;}};HTransportURL=false;HTransportPoll=true;HFailPageUrl='/';HTransporterMaxRetryCount=60;HTransporterMaxRetryTime=60000;HTransporterRetryDelay=1000;HTransporter=Base.extend({constructor:null,start:function(_77){var _0=HTransporter;_0.url_base=_77;_0.ses_id=0;_0.err_msg='';_0.isBusy=false;_0.syncNum=0;_0.syncDelay=100;_0.prevData='';_0.failCount=0;_0.firstFail=0;_0.pollMode=HTransportPoll;_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);},setPollMode:function(_9){HTransporter.pollMode=_9;},failure:function(resp){var _5H=HTransporterMaxRetryTime+(new Date().getTime()),_0=HTransporter;clearTimeout(_0.req_timeout);if(_0.firstFail==0){_0.isBusy=false;_0.firstFail=(new Date().getTime());_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else if((_0.failCount<HTransporterMaxRetryCount)&&(_0.firstFail<_5H)){_0.isBusy=false;_0.failCount++;window.status='Communications error, retry attempt '+_0.failCount+' of '+HTransporterMaxRetryCount+'...';}
else{window.status='Communications error, reloading page...';location.href=HFailPageUrl;_0.isBusy=true;}
_0.req_timeout=setTimeout('HTransporter.sync();',HTransporterRetryDelay);},respond:function(resp){var _6E=resp.responseText,_0=HTransporter;try{_0.err_msg='';eval(_6E);}
catch(e){_0.err_msg='&err_msg='+e;_0.failure(resp);}
_0.prevData='';if(_0.failCount!=0){window.status='';}
_0.failCount=0;_0.firstFail=0;_0.isBusy=false;if(_0.pollMode){_0.req_timeout=setTimeout('HTransporter.sync();',_0.syncDelay);}},sync:function(){var _0=HTransporter,_79=((_0.syncDelay>0)||(_0.syncDelay==0));if(_79&&_0.url_base){if(!_0.isBusy){_0.isBusy=true;if(_0.prevData!=''){_1f=_0.prevData;}
else{_1f=HValueManager.toXML();_0.prevData=_1f;}
if(""!=_1f||_0.pollMode){_0.syncNum++;HVM.isGetting=true;req_args={onSuccess:function(resp){_0.respond(resp);},onFailure:function(resp){_0.failure(resp);},method:'post',postBody:'ses_id='+_0.ses_id+_0.err_msg+_1f};try{_0.req=new Ajax.Request(_0.url_base,req_args);HVM.isGetting=false;}
catch(e){window.status='conn error:'+e;HVM.isGetting=false;_0.failure(null);}}
else{_0.isBusy=false;}}}},stop:function(){clearTimeout(_0.req_timeout);}});LOAD("HTransporter.start(HTransportURL);");HValueManager=HClass.extend({constructor:null,values:{},tosync:[],isSending:false,isGetting:false,add:function(_3,_m){this.values[_3]=_m;},set:function(_3,_4){this.values[_3].set(_4);},s:function(_3,_4){this.values[_3].s(_4);},del:function(_3){var _56=this.values[_3];var _78=_56.views;for(var _0c=0;_0c<_78.length;_0c++){var _72=_78[_0c];_72.valueObj=new HDummyValue(0,_56.value);}
this.values[_3]=null;},changed:function(_1U){if(this.isGetting==false){if(this.tosync.indexOf(_1U.id)==-1){this.tosync.push(_1U.id);}
var _O=HTransporter;if(!_O.pollMode){clearTimeout(_O.req_timeout);_O.req_timeout=setTimeout('HTransporter.sync();',_O.syncDelay);}}},toXML:function(){var _4J='&HSyncData=';if(!this.isSending){this.isSending=true;var _6U=this.tosync.length;if(_6U==0){this.isSending=false;return'';}
var _4Z=[],_13;for(_13=0;_13<_6U;_13++){var _1S=this.tosync.shift();var _6V=this.values[_1S];_4Z.push(_6V.toXML(_13));}
var _6W=_4Z.join('');_4J+='<hsyncvalues version="8118">'+_6W+'</hsyncvalues>';this.isSending=false;}
return _4J;},output:function(){return this.toXML();}});HVM=HValueManager;HValue=HClass.extend({constructor:function(_3,_4){this.id=_3;this.type='[HValue]';this.value=_4;this.views=[];HValueManager.add(_3,this);},set:function(_4){if(_4!=this.value){this.value=_4;HValueManager.changed(this);this.refresh();}},s:function(_4){this.value=_4;this.refresh();},get:function(){return this.value;},bind:function(_J){if(_J===undefined){throw("HValueBindError: _J is undefined!");}
this.views.push(_J);_J.setValueObj(this);},unbind:function(_J){for(var _0c=0;_0c<this.views.length;_0c++){var _74=this.views[_0c];if(_74===_J){this.views.splice(_0c);return;}}},release:function(_J){return this.unbind(_J);},refresh:function(){for(var _0c=0;_0c<this.views.length;_0c++){var _J=this.views[_0c];if(_J.value!=this.value){if(!_J._valueIsBeingSet){_J._valueIsBeingSet=true;_J.setValue(this.value);_J._valueIsBeingSet=false;}}}},toXML:function(_13){var _1S=this.id.toString();var _03=this.value;var _0t=(typeof _03).slice(0,1);var _0F;if(_0t=='s'){_0F=_03.toString();_0F=SHA.str2Base64(_0F);}
else if(_0t=='n'){if(Math.ceil(_03)===Math.floor(_03)===_03){_0t='i';_0F=parseInt(_03,10).toString();}
else{_0t='f';_0F=parseFloat(_03).toString();}}
else if(_0t=='b'){if(_03){_0F='1';}
else{_0F='0';}}
else{try{if(console&&console.log){console.log('syncvalue type error');console.log('  syncid:',_1S);console.log('  syncjstype:',_0t);console.log('  typeof:',(typeof _03));console.log('  syncvalue:',_03);}}
catch(e){alert('value error, syncid:'+_1S+' syncjstype:'+_0t+' typeof:'+(typeof _03)+' syncvalue:'+_03);}
return'';}
return'<'+_0t+' id="'+_1S+'">'+_0F+'</'+_0t+'>';}});JSLoader=Base.extend({constructor:function(_23){this._1I=[];this._23=_23;this._3q=null;},_6q:function(_4Q){eval(_4Q.responseText);},load:function(_2f){if(jsLoader._1I.indexOf(_2f)!=-1){return;}
req_args={onSuccess:function(resp){jsLoader._6q(resp);},onFailure:function(resp){window.status="failed to load js: "+jsLoader._29;},method:'get',asynchronous:false};this._3q=new Ajax.Request(this._23+_2f+'.js',req_args);this._1I.push(_2f);}});LOAD("jsLoader = new JSLoader('/gz/js/');");HPoint=HClass.extend({constructor:function(){this.type='[HPoint]';var _P=arguments;if(_P.length===0){this._1q();}
else if(_P.length==2){this._3R(_P[0],_P[1]);}
else if(_P.length==1){this._1r(_P[0]);}
else{throw"Invalid number of arguments.";}},_1q:function(){this.x=null;this.y=null;},_3R:function(x,y){this.x=x;this.y=y;},_1r:function(_e){this.x=_e.x;this.y=_e.y;},set:function(){var _P=arguments;if(_P.length===0){this._1q();}
else if(_P.length==2){this._3R(_P[0],_P[1]);}
else if(_P.length==1){this._1r(_P[0]);}
else{throw"Invalid number of arguments.";}},constrainTo:function(_1){if(this.x<_1.left){this.x=_1.left;}
if(this.y<_1.top){this.y=_1.top;}
if(this.x>_1.right){this.x=_1.right;}
if(this.y>_1.bottom){this.y=_1.bottom;}},add:function(_e){_P=arguments;if((_P.length==1)&&(_P[0].type==this.type)){_e=_P[0];return new HPoint((this.x+_e.x),(this.y+_e.y));}
else if(_P.length==2){return new HPoint((this.x+_P[0]),(this.y+_P[1]));}else{return new HPoint(0,0);}},subtract:function(){_P=arguments;if((_P.length==1)&&(_P[0].type==this.type)){_e=_P[0];return new HPoint(this.x-_e.x,this.y-_e.y);}
else if(_P.length==2){return new HPoint(this.x-_P[0],this.y-_P[1]);}else{return new HPoint(0,0);}},equals:function(_e){return(this.x==_e.x&&this.y==_e.y);}});HRect=HClass.extend({constructor:function(){this.type='[HRect]';var _P=arguments;if(_P.length===0){this._1q();}else if(_P.length==4){this._3Q(_P[0],_P[1],_P[2],_P[3]);}
else if(_P.length==2){this._1r(_P[0],_P[1]);}
else if(_P.length==1){this._3P(_P[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_1q:function(){this.top=0;this.left=0;this.bottom=-1;this.right=-1;},_3Q:function(_09,_0G,_1O,_1o){this.top=_0G;this.left=_09;this.bottom=_1o;this.right=_1O;},_1r:function(_4p,_4R){this.top=_4p.y;this.left=_4p.x;this.bottom=_4R.y;this.right=_4R.x;},_3P:function(_1){this.top=_1.top;this.left=_1.left;this.bottom=_1.bottom;this.right=_1.right;},updateSecondaryValues:function(){this.isValid=(this.right>=this.left&&this.bottom>=this.top);this.leftTop=new HPoint(this.left,this.top);this.leftBottom=new HPoint(this.left,this.bottom);this.rightTop=new HPoint(this.right,this.top);this.rightBottom=new HPoint(this.right,this.bottom);this.width=(this.right-this.left);this.height=(this.bottom-this.top);},set:function(){var _P=arguments;if(_P.length===0){this._1q();}else if(_P.length==4){this._3Q(_P[0],_P[1],_P[2],_P[3]);}
else if(_P.length==2){this._1r(_P[0],_P[1]);}
else if(_P.length==1){this._3P(_P[0]);}
else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},setLeft:function(_09){this.left=_09;this.updateSecondaryValues();},setRight:function(_1O){this.right=_1O;this.updateSecondaryValues();},setTop:function(_0G){this.top=_0G;this.updateSecondaryValues();},setBottom:function(_1o){this.bottom=_1o;this.updateSecondaryValues();},setLeftTop:function(_e){this.left=_e.x;this.top=_e.y;this.updateSecondaryValues();},setLeftBottom:function(_e){this.left=_e.x;this.bottom=_e.y;this.updateSecondaryValues();},setRightTop:function(_e){this.right=_e.x;this.top=_e.y;this.updateSecondaryValues();},setRightBottom:function(_e){this.right=_e.x;this.bottom=_e.y;this.updateSecondaryValues();},setWidth:function(_p){this.right=this.left+_p;this.updateSecondaryValues();},setHeight:function(_D){this.bottom=this.top+_D;this.updateSecondaryValues();},setSize:function(){var _P=arguments;if(_P.length===2){_p=_P[0];_D=_P[1];}
else if(_P.length===1){_p=_P.x;_D=_P.y;}
this.right=this.left+_p;this.bottom=this.top+_D;this.updateSecondaryValues();},intersects:function(_1){return(((_1.left>=this.left&&_1.left<=this.right)||(_1.right>=this.left&&_1.right<=this.right))&&((_1.top>=this.top&&_1.top<=this.bottom)||(_1.bottom>=this.top&&_1.bottom<=this.bottom)));},contains:function(_m){if(_m instanceof HPoint){return this._5B(_m);}
else if(_m instanceof HRect){return this._5C(_m);}
else{throw"Wrong argument type.";}},_5B:function(_e){return(_e.x>=this.left&&_e.x<=this.right&&_e.y>=this.top&&_e.y<=this.bottom);},_5C:function(_1){return(_1.left>=this.left&&_1.right<=this.right&&_1.top>=this.top&&_1.bottom<=this.bottom);},insetBy:function(){var _P=arguments;if(_P.length===1){this._6f(_P[0]);}else if(_P.length==2){this._4f(_P[0],_P[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_6f:function(_e){this._4f(_e.x,_e.y);},_4f:function(x,y){this.left+=x;this.top+=y;this.right-=x;this.bottom-=y;},offsetBy:function(){var _P=arguments;if(_P.length===1){this._6o(_P[0]);}else if(_P.length==2){this._4A(_P[0],_P[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_6o:function(_e){this._4A(_e.x,_e.y);},_4A:function(x,y){this.left+=x;this.top+=y;this.right+=x;this.bottom+=y;},offsetTo:function(){var _P=arguments;if(_P.length===1){this._6p(_P[0]);}else if(_P.length==2){this._4B(_P[0],_P[1]);}else{throw"Invalid number of arguments.";}
this.updateSecondaryValues();},_6p:function(_e){this._4B(_e.x,_e.y);},_4B:function(x,y){this.right+=x-this.left;this.left=x;this.bottom+=y-this.top;this.top=y;},equals:function(_1){return(this.left==_1.left&&this.top==_1.top&&this.right==_1.right&&this.bottom==_1.bottom);},intersection:function(_1){return new HRect(Math.max(this.left,_1.left),Math.max(this.top,_1.top),Math.min(this.right,_1.right),Math.min(this.bottom,_1.bottom));},union:function(_1){return new HRect(Math.min(this.left,_1.left),Math.min(this.top,_1.top),Math.max(this.right,_1.right),Math.max(this.bottom,_1.bottom));},bind:function(_m){},unbind:function(_m){}});HDefaultApplicationInterval=20;HSystemTickerInterval=10;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){if((this.ticks%10)==0&&this.fix_ie){}
for(var _k=0;_k<this.apps.length;_k++){if(this.apps[_k]){if(!this.busyApps[_k]){if((this.ticks%this.appPriorities[_k])==0){this.appTimers[_k]=setTimeout('if (HSystem.apps['+_k+']) {HSystem.apps['+_k+']._4W();}',10);}}}}},ticker:function(){this.ticks++;this.scheduler();this._89=setTimeout('HSystem.ticker();',HSystemTickerInterval);},addApp:function(_0U,_0j){if(this.freeAppIds.length>1024){var _k=this.freeAppIds.shift();this.apps[_k]=_0U;}else{this.apps.push(_0U);var _k=this.apps.length-1;}
_0U.parent=this;_0U.parents=[this];_0U.appId=_k;this.startApp(_k,_0j);return _k;},startApp:function(_k,_0j){if(_0j===undefined){_0j=this.defaultInterval;}
this.appPriorities[_k]=_0j;this.busyApps[_k]=false;},stopApp:function(_k){this.busyApps[_k]=true;},reniceApp:function(_k,_0j){this.appPriorities[_k]=_0j;},killApp:function(_k,_5X){if(!_5X){var _6O=new Date().getTime();while(this.busyApps[_k]==true){if(new Date().getTime()>_6O+this.maxAppRunTime){break;}}}
this.busyApps[_k]=true;this.apps[_k].destroyAllViews();delete this.apps[_k];this.apps[_k]=null;this.freeAppIds.push(_k);},views:[],_30:[],addView:function(_l){var _2q;if(this._30.length==0){_2q=this.views.length;this.views.push(_l);}
else{_2q=this._30.pop();this.views[_2q]=_l;}
return _2q;},delView:function(_j){this.views[_j]=null;this._30.push(_j);}});LOAD('HSystem.ticker();');HApplication=HClass.extend({constructor:function(_0j){this.type='[HApplication]';this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_0j);},buildParents:function(_j){var _l=HSystem.views[_j];_l.parent=this;_l.parents=[];for(var _0P=0;_0P<this.parents.length;_0P++){_l.parents.push(this.parents[_0P]);}
_l.parents.push(this);},addView:function(_l){var _j=HSystem.addView(_l);this.views.push(_j);this.buildParents(_j);this.viewsZOrder.push(_j);return _j;},removeView:function(_j){HSystem.views[_j].remove();},destroyView:function(_j){HSystem.views[_j].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){var i,_j;for(i=0;i<this.views.length;i++){_j=this.views[i];HSystem.views[_j].die();}},_6v:function(){var i,_j;for(i=0;i<this.views.length;i++){_j=this.views[i];HSystem.views[i].onIdle();}},_4W:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._6v();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});HDefaultThemePath='../../';HDefaultThemeName='default';HNoComponentCSS=[];HThemeHasIE6GifsInsteadOfPng=[];HThemeMode=1;HThemeManager=HClass.extend({constructor:null,init:function(){this.themePath=HDefaultThemePath;this._2A={};this._25={};this.currentTheme=HDefaultThemeName;},setThemePath:function(_U){this.themePath=_U;},_5P:function(_o){console.log("ERROR: Template Not Found: '"+_o+"' ");},_5O:function(_o){console.log("ERROR: Template Failure: '"+_o+"' ");},_5N:function(_o){console.log("ERROR: Template Exception: '"+_o+"' ");},fetch:function(_o,_0L){var _1M;if(!_0L){var _0L='text/html; charset=UTF-8';}
var _3q=new Ajax.Request(_o,{method:'GET',onSuccess:function(_7f){_1M=_7f.responseText;},on404:function(){HThemeManager._5P(_o);},onFailure:function(){HThemeManager._5O(_o);},onException:function(){HThemeManager._5N(_o);},asynchronous:false,contentType:_0L});_3q.onStateChange();return _1M;},getThemeGfxPath:function(){var _h=this._1u[0],_q=this._1u[1],_v=this._1u[2],_C=this._1u[3],_0H=this._0H(_h,_q,_v,_C);return this._M(_0H,'gfx');},getCssFilePath:function(_0f){var _h=this._1u[0];if((HThemeHasIE6GifsInsteadOfPng.indexOf(_h)!=-1)&&ELEM._15){return"url('"+this._M(this.getThemeGfxPath(),_0f.replace('.png','-ie6.gif'))+"')";}
else{return"url('"+this._M(this.getThemeGfxPath(),_0f)+"')";}},loadCSS:function(_o){var _0L='text/css';var _0M=this.fetch(_o,_0L);if(!_0M||_0M==""){return;}
_0M=this._3J(_0M);var _0b,_4Y,_44;if(ELEM._2e){_0b=document.createStyleSheet();_0b.cssText=_0M;}
else{_0b=document.createElement("style");_0b.type=_0L;_0b.media="all";_44=document.getElementsByTagName('head')[0];_44.appendChild(_0b);if(navigator.userAgent.indexOf('KHTML')!=-1){var _5G=document.createTextNode(_0M);_0b.appendChild(_5G);}
else{_0b.innerHTML=_0M;}}},_5n:function(_G){if(_G[_G.length-1]!='/'){_G+='/';}
return _G;},_M:function(_6P,_6Q){return this._5n(_6P)+_6Q;},_0H:function(_h,_q,_v,_C){var _U=_v;if(_v===null){_U=this.themePath;}
if(HThemeMode==0){if(_C){_U=this._M(_U,_C);}
if(_v===null){_U=this._M(_U,_q);_U=this._M(_U,'themes');}
_U=this._M(_U,_h);}
else if(HThemeMode==1){_U=this._M(_U,_h);}
return _U;},_27:function(_h,_q,_v,_C){this._1u=[_h,_q,_v,_C];var _5E=this._0H(_h,_q,_v,_C);var _5F=this._M('css',_q+'.css');var _27=this._M(_5E,_5F);return _27;},_3e:function(_h,_q,_v,_C){var _69=this._0H(_h,_q,_v,_C);var _6a=this._M('html',_q+'.html');var _6b=this._M(_69,_6a);return _6b;},loadMarkup:function(_h,_q,_v,_C){if(!this._2A[_h]){this._2A[_h]={};}
var _y=this._2A[_h][_q];if(null===_y||undefined===_y){var _3e=this._3e(_h,_q,_v,_C);_y=this.fetch(_3e);if(null===_y||undefined===_y){_y="";}
this._2A[_h][_q]=_y;}
return _y;},getMarkup:function(_h,_q,_v,_C){if(!this._25[_h]){var _5y=this._27(_h,'common',_v,null);this._25[_h]={};this.loadCSS(_5y);}
if(HNoComponentCSS.indexOf(_h)==-1){if(!this._25[_h][_q]){var _5z=this._27(_h,_q,_v,_C);this._25[_h][_q]=true;this.loadCSS(_5z);}}
return this.loadMarkup(_h,_q,_v,_C);},_1p:function(_h,_q,_v,_C){var _0H=this._0H(_h,_q,_v,_C);var _o=this._M(_0H,'gfx');return _o;},_5A:function(_h,_q,_v,_C,_0f){if((HThemeHasIE6GifsInsteadOfPng.indexOf(_h)!=-1)&&ELEM._15){return this._M(this._1p(_h,_q,_v,_C),_0f.replace('.png','-ie6.gif'));}
return this._M(this._1p(_h,_q,_v,_C),_0f);},getThemeGfxFile:function(_0f){return this.getThemeGfxPath()+_0f;},setTheme:function(_55){this.currentTheme=_55;},restoreDefaultTheme:function(){this.setTheme(HDefaultThemeName);},_0T:new RegExp(/#\{([^\}]*)\}/),_3J:function(_1v){while(this._0T.test(_1v)){_1v=_1v.replace(this._0T,eval(RegExp.$1));}
return _1v;}});HMarkupView=HClass.extend({bindMarkupVariables:function(){var _0A=this.markup;while(HMarkupView._3G.test(_0A)){_0A=_0A.replace(HMarkupView._3G,this.evalMarkupVariable(RegExp.$1,true));}
while(HMarkupView._0T.test(_0A)){_0A=_0A.replace(HMarkupView._0T,this.evalMarkupVariable(RegExp.$1));}
this.markup=_0A;},evalMarkupVariable:function(_6S,_7J){try{var _ID=this.elemId.toString(),_WIDTH=this.rect.width,_HEIGHT=this.rect.height,_1M=eval(_6S);if(_7J){return'';}
if(_1M===undefined){return'';}
else{return _1M;}}
catch(e){return'';}},toggleCSSClass:function(_0e,_1t,_4S){if(_0e){var _42=ELEM.hasClassName(_0e,_1t);if(_4S){if(!_42){ELEM.addClassName(_0e,_1t);}}
else{if(_42){ELEM.removeClassName(_0e,_1t);}}}}},{_0T:new RegExp(/#\{([^\}]*)\}/),_3G:new RegExp(/\$\{([^\}]*)\}/)});HView=HClass.extend({themePath:null,packageName:null,isAbsolute:true,flexRight:false,flexLeft:true,flexTop:true,flexBottom:false,flexRightOffset:0,flexBottomOffset:0,constructor:function(_1,_u){if(this.theme===undefined){this.theme=HThemeManager.currentTheme;this.preserveTheme=false;}
else{this.preserveTheme=true;}
this.optimizeWidthOnRefresh=true;this.parent=_u;this.viewId=this.parent.addView(this);this.appId=this.parent.appId;this.app=HSystem.apps[this.appId];this.views=[];this.viewsZOrder=[];this._5D();this.setRect(_1);this.isHidden=true;if(this.parent.type=='[HView]'){this.type='[HSubview]';}else{this.type='[HView]';}
this.drawn=false;this._3K=_1.left;this._3L=_1.top;this._11=[];if(!this.isinherited){this.draw();this.show();}},setFlexRight:function(_9,_Y){if(_9===undefined){_9=true;}
this.flexRight=_9;if(_Y===undefined){_Y=0;}
this.flexRightOffset=_Y;},setFlexLeft:function(_9,_Y){if(_9===undefined){_9=true;}
this.flexLeft=_9;if(_Y!==undefined){this.rect.setLeft(_Y);}},setFlexTop:function(_9,_Y){if(_9===undefined){_9=true;}
this.flexTop=_9;if(_Y!==undefined){this.rect.setTop(_Y);}},setFlexBottom:function(_9,_Y){if(_9===undefined){_9=true;}
this.flexBottom=_9;if(_Y===undefined){_Y=0;}
this.flexBottomOffset=_Y;},setAbsolute:function(_9){if(_9===undefined){_9=true;}
this.isAbsolute=_9;},setRelative:function(_9){if(_9===undefined){_9=true;}
this.isAbsolute=(!_9);},getThemeGfxPath:function(){if(this.preserveTheme){_h=this.theme;}else{_h=HThemeManager.currentTheme;}
return HThemeManager._1p(_h,this.componentName,this.themePath,this.packageName);},getThemeGfxFile:function(_0f){if(this.preserveTheme){_h=this.theme;}else{_h=HThemeManager.currentTheme;}
return HThemeManager._5A(_h,this.componentName,this.themePath,this.packageName,_0f);},_4t:function(_1a){this.elemId=ELEM.make(_1a,'div');},_6J:function(_5o){var _26='display:none;overflow:hidden;visibility:hidden;';if(this.isAbsolute){_26+='position:absolute;';}else{_26+='position:relative;';}
_26+=_5o;ELEM.setCSS(this.elemId,_26);},_32:function(){var _1a;if(this.parent.elemId===undefined){_1a=0;}
else if(this.parent.markupElemIds&&this.parent.markupElemIds['subview']){_1a=this.parent.markupElemIds['subview'];}
else{_1a=this.parent.elemId;}
return _1a;},_5D:function(){if(!this.elemId){this._4t(this._32());this._6J('');if(this.preserveTheme){ELEM.addClassName(this.elemId,this.theme);}
else{ELEM.addClassName(this.elemId,HThemeManager.currentTheme);}}},drawRect:function(){if(!this.parent||!this.rect.isValid){return;}
this.drawn=true;var _a=this.elemId;var _1=this.rect;ELEM.setStyle(_a,'left',this.flexLeft?(_1.left+'px'):'auto',true);ELEM.setStyle(_a,'top',this.flexTop?(_1.top+'px'):'auto',true);ELEM.setStyle(_a,'right',this.flexRight?(this.flexRightOffset+'px'):'auto',true);ELEM.setStyle(_a,'bottom',this.flexBottom?(this.flexBottomOffset+'px'):'auto',true);ELEM.setStyle(_a,'width',(this.flexLeft&&this.flexRight)?'auto':(_1.width+'px'),true);ELEM.setStyle(_a,'height',(this.flexTop&&this.flexBottom)?'auto':(_1.height+'px'),true);if(this.flexLeft&&this.flexRight){ELEM.setStyle(_a,'min-width',_1.width+'px',true);}
if(this.flexTop&&this.flexBottom){ELEM.setStyle(_a,'min-height',_1.height+'px',true);}
if(undefined===this.isHidden||this.isHidden==false){ELEM.setStyle(_a,'visibility','inherit',true);}
ELEM.setStyle(_a,'display','block',true);this._5c();if(this._3K!=_1.left||this._3L!=_1.top){this.invalidatePositionCache();this._3K=_1.left;this._3L=_1.top;}},_5c:function(){ELEM.setStyle(this.elemId,'z-index',this.parent.viewsZOrder.indexOf(this.viewId));},_2C:function(){var _5d=this.parent.viewsZOrder;for(var i=0;i<_5d.length;i++){ELEM.setStyle(HSystem.views[_5d[i]].elemId,'z-index',i);}},draw:function(){this.drawRect();},_4q:function(){var _h;if(this.preserveTheme){_h=this.theme;}
else{_h=HThemeManager.currentTheme;}
this.markup=HThemeManager.getMarkup(_h,this.componentName,this.themePath,this.packageName);},drawMarkup:function(){ELEM.setStyle(this.elemId,'display','none',true);this._4q();this.bindMarkupVariables();ELEM.setHTML(this.elemId,this.markup);this.markupElemIds={};var _4K=['bg','label','state','control','value','subview'];for(var i=0;i<_4K.length;i++){var _0h=_4K[i];var _3V=_0h+this.elemId;var _68=' id="'+_3V+'"';if(this.markup.indexOf(_68)!=-1){this.markupElemIds[_0h]=this.bindDomElement(_3V);}}
ELEM.setStyle(this.elemId,'display','block',true);},setHTML:function(_1F){ELEM.setHTML(this.elemId,_1F);},refresh:function(){if(this.drawn){this.drawRect();}
if(this.optimizeWidthOnRefresh){this.optimizeWidth();}},setRect:function(_1){if(this.rect){this.rect.unbind(this);}
this.rect=_1;this.rect.bind(this);this.refresh();},setStyle:function(_A,_4,_2N){if(!this.elemId){return;}
ELEM.setStyle(this.elemId,_A,_4,_2N);},style:function(_A){if(!this.elemId){return;}
return ELEM.getStyle(this.elemId,_A);},setStyleForPart:function(_0h,_A,_4,_2N){if(!this.markupElemIds[_0h]){return;}
ELEM.setStyle(this.markupElemIds[_0h],_A,_4,_2N);},styleForPart:function(_0h,_A){if(!this.markupElemIds[_0h]){return;}
ELEM.getStyle(this.markupElemIds[_0h],_A);},hide:function(){if(!this.isHidden){this.setStyle('visibility','hidden');this.setStyle('display','none');this.isHidden=true;}},show:function(){if(this.isHidden){this.setStyle('visibility','inherit');this.setStyle('display','block');this.isHidden=false;}},toggle:function(){if(this.isHidden){this.show();}else{this.hide();}},remove:function(){if(this.parent){var _7b=this.parent.viewsZOrder.indexOf(this.viewId),_7a=this.parent.views.indexOf(this.viewId);this.parent.views.splice(_7a,1);HSystem.delView(this.viewId);this.parent.viewsZOrder.splice(_7b,1);this._2C();this.parent=null;this.parents=[];}},die:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].die();}
this.remove();for(var i=0;i<this._11.length;i++){ELEM.del(this._11[i]);}
this._11=[];ELEM.del(this.elemId);this.elemId=null;this.drawn=false;delete this.rect;},onIdle:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].onIdle();}},buildParents:function(_j){var _l=HSystem.views[_j];_l.parent=this;_l.parents=[];for(var _0P=0;_0P<this.parents.length;_0P++){_l.parents.push(this.parents[_0P]);}
_l.parents.push(this);},addView:function(_l){var _j=HSystem.addView(_l);this.views.push(_j);this.buildParents(_j);this.viewsZOrder.push(_j);return _j;},removeView:function(_j){HSystem.views[_j].remove();},destroyView:function(_j){HSystem.views[_j].die();},bounds:function(){var _0J=new HRect(this.rect);_0J.right-=_0J.left;_0J.left=0;_0J.bottom-=_0J.top;_0J.top=0;return _0J;},resizeBy:function(_35,_1W){var _1=this.rect;_1.right+=_35;_1.bottom+=_1W;_1.updateSecondaryValues();this.drawRect();},resizeTo:function(_p,_D){var _1=this.rect;_1.right=_1.left+_p;_1.bottom=_1.top+_D;_1.updateSecondaryValues();this.drawRect();},offsetTo:function(){this.rect.offsetTo.apply(this.rect,arguments);this.drawRect();},moveTo:function(){this.offsetTo.apply(this,arguments);},offsetBy:function(_35,_1W){this.rect.offsetBy(_35,_1W);this.drawRect();},moveBy:function(){this.offsetBy.apply(this,arguments);},bringToFront:function(){if(!this.parent){return;}
var _E=this.zIndex();this.parent.viewsZOrder.splice(_E,1);this.parent.viewsZOrder.push(this.viewId);this._2C();},sendToBack:function(){if(!this.parent){return;}
var _E=this.zIndex();this.parent.viewsZOrder.splice(_E,1);this.parent.viewsZOrder.splice(0,0,this.viewId);this._2C();},zIndex:function(){if(!this.parent){return;}
return this.parent.viewsZOrder.indexOf(this.viewId);},stringWidth:function(_1e,_2h,_a){if(_2h!==undefined&&_2h!=null){_1e=_1e.substring(0,_2h);}
if(_a===undefined||_a==null){_a=this.elemId;}
var _0Q=ELEM.make(_a);ELEM.setCSS(_0Q,"visibility:hidden;position:absolute;white-space:nowrap;");ELEM.setHTML(_0Q,_1e);var _p=0,_D=0;if(ELEM._15||ELEM._7K||ELEM._7L){_p=parseInt(ELEM.get(_0Q).offsetWidth,10);if(arguments[3]){_D=parseInt(ELEM.get(_0Q).offsetHeight,10);}}else{_p=parseInt(ELEM.get(_0Q).clientWidth,10);if(arguments[3]){_D=parseInt(ELEM.get(_0Q).clientHeight,10);}}
ELEM.del(_0Q);if(arguments[3]){return[_p,_D];}else{return _p;}},pageX:function(){var _5=0;var _7=this;while(_7){if(_7.elemId&&_7.rect){_5+=ELEM.get(_7.elemId).offsetLeft;_5-=ELEM.get(_7.elemId).scrollLeft;}
_7=_7.parent;}
return _5;},pageY:function(){var _8=0;var _7=this;while(_7){if(_7.elemId&&_7.rect){_8+=ELEM.get(_7.elemId).offsetTop;_8-=ELEM.get(_7.elemId).scrollTop;}
_7=_7.parent;}
return _8;},pageLocation:function(){return new HPoint(this.pageX(),this.pageY());},optimizeWidth:function(){},invalidatePositionCache:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].invalidatePositionCache();}},bindDomElement:function(_00){var _2M=ELEM.bindId(_00);if(_2M){this._11.push(_2M);}
return _2M;},unbindDomElement:function(_0e){var _4b=this._11.indexOf(_0e);if(_4b>-1){ELEM.del(_0e);this._11.splice(_4b,1);}},animateTo:function(_m,_0x,_0p){if(_m instanceof HPoint){var _1=new HRect(_m,_m);_1.setSize(this.rect.width,this.rect.height);this._2J(_1,_0x);}
else if(_m instanceof HRect){this._2J(_m,_0x);}
else{throw"Wrong argument type.";}},stopAnimation:function(){if(this._21){window.clearInterval(this._21);this._21=null;var _09=parseInt(this.style('left'),10),_0G=parseInt(this.style('top'),10),_p=parseInt(this.style('width'),10),_D=parseInt(this.style('height'),10);this.rect.set(_09,_0G,_09+_p,_0G+_D);this.drawRect();if(this._3E){this.onAnimationEnd();}
else{this.onAnimationCancel();}}},_2J:function(_1,_0x,_0p){if(null===_0x||undefined===_0x){_0x=500;}
if(null===_0p||undefined===_0p||_0p<1){_0p=50;}
if(!this._21){this._3E=false;this.onAnimationStart();var _6N=new Date().getTime();var _i=this;this._21=window.setInterval(function(){_i._7m({startTime:_6N,duration:_0x,transition:function(t,b,c,d){return c*t/d+b;},props:[{prop:'left',from:_i.rect.left,to:_1.left,unit:'px'},{prop:'top',from:_i.rect.top,to:_1.top,unit:'px'},{prop:'width',from:_i.rect.width,to:_1.width,unit:'px'},{prop:'height',from:_i.rect.height,to:_1.height,unit:'px'}]});},Math.round(1000/_0p));}},_7m:function(_m){var _57=new Date().getTime();if(_57<_m.startTime+_m.duration){var _5u=_57-_m.startTime;for(var i=0;i<_m.props.length;i++){var _31=_m.props[i].from;var _59=_m.props[i].to;if(_31!=_59){var _6A=_m.transition(_5u,_31,(_59-_31),_m.duration);this.setStyle(_m.props[i].prop,_6A+_m.props[i].unit);}}}else{for(var i=0;i<_m.props.length;i++){this.setStyle(_m.props[i].prop,_m.props[i].to+_m.props[i].unit);}
this._3E=true;this.stopAnimation();}},onAnimationStart:function(){},onAnimationEnd:function(){},onAnimationCancel:function(){}});HView.implement(HMarkupView);HControl=HView.extend({refreshOnValueChange:true,refreshOnLabelChange:true,constructor:function(_1,_c,_2){if(!_2){_2={};}
var options=new(HComponentDefaults.extend(_2));this.options=options;if(this.isinherited){this.base(_1,_c);}
else{this.isinherited=true;this.base(_1,_c);this.isinherited=false;}
var _w=options.label;this.setLabel(_w);var _1B=options.events;this.setEvents(_1B);this.type='[HControl]';if(!this.valueObj){this.setValueObj(new HDummyValue());}
if(!this.value){this.setValue(options.value);}
var _6g=(_2.minValue||_2.maxValue);if(_6g){this.setValueRange(options.value,options.minValue,options.maxValue);}
this.setEnabled(options.enabled);this.action=options.action;if(options.visible){this.show();}
else{this.hide();}
if(!this.isinherited){this.draw();}},setAction:function(_3B){this.action=_3B;},die:function(){if(this.valueObj){this.valueObj.unbind(this);delete this.valueObj;}
EVENT.unreg(this);this.base();},setLabel:function(_w){this.label=_w;this.options.label=_w;this.refresh();},setEnabled:function(_9){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].setEnabled(_9);}
if(this.enabled===_9){return;}
this.enabled=_9;if(_9){EVENT.reg(this,this.events);}
else{EVENT.unreg(this);}
this.toggleCSSClass(this.elemId,HControl.CSS_ENABLED,this.enabled);this.toggleCSSClass(this.elemId,HControl.CSS_DISABLED,!this.enabled);},setValue:function(_4){if(_4===undefined){return;}
if(!this.valueObj){return;}
if(_4!==this.value){this.value=_4;this.valueObj.set(this.value);this.refresh();}},setValueObj:function(_2F){this.valueObj=_2F;this.setValue(_2F.value);},setValueRange:function(_4,_2n,_2k){this.minValue=_2n;this.maxValue=_2k;_4=(_4<_2n)?_2n:_4;_4=(_4>_2k)?_2k:_4;this.setValue(_4);this.refresh();},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setHTML(this.markupElemIds.value,this.value);}}},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.label){ELEM.setHTML(this.markupElemIds.label,this.label);}}},refresh:function(){this.base();if(this.drawn){if(this.refreshOnValueChange){this.refreshValue();}
if(this.refreshOnLabelChange){this.refreshLabel();}}},setEvents:function(_1B){if(!this.events){var _5R=HClass.extend({mouseMove:false,mouseDown:false,mouseUp:false,draggable:false,droppable:false,keyDown:false,keyUp:false,mouseWheel:false,textEnter:false});this.events=new _5R;}
if(_1B){this.events.extend(_1B);}
this.events.ctrl=this;EVENT.focusOptions[this.elemId]=this.events;var _4w=this.events.mouseMove;var _3h=EVENT.coordListeners.indexOf(this.elemId);if(_4w&&(_3h==-1)){EVENT.coordListeners.push(this.elemId);}else if((!_4w)&&(_3h!=-1)){EVENT.coordListeners.splice(_3h,1);}
this.isDragged=false;},setMouseMove:function(_9){this.events.mouseMove=_9;this.setEvents();},setMouseDown:function(_9){this.events.mouseDown=_9;this.setEvents();},setMouseUp:function(_9){this.events.mouseUp=_9;this.setEvents();},setMouseWheel:function(_9){this.events.mouseWheel=_9;this.setEvents();},setDraggable:function(_9){this.events.draggable=_9;this.setEvents();},setDroppable:function(_9){this.events.droppable=_9;this.setEvents();},setKeyDown:function(_9){this.events.keyDown=_9;this.setEvents();},setKeyUp:function(_9){this.events.keyUp=_9;this.setEvents();},setTextEnter:function(_9){this.events.textEnter=_9;this.setEvents();},textEnter:function(){},focus:function(){},blur:function(){},gainedActiveStatus:function(_2g){},_5Y:function(_2g){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,true);}
this.gainedActiveStatus(_2g);},lostActiveStatus:function(_B){},_6j:function(_B){if(this.enabled){this.toggleCSSClass(this.elemId,HControl.CSS_ACTIVE,false);}
this.lostActiveStatus(_B);},mouseMove:function(_5,_8){},mouseDown:function(_5,_8,_T){},mouseUp:function(_5,_8,_T){},mouseWheel:function(_Q){},startDrag:function(x,y){this.isDragged=true;},doDrag:function(x,y){},endDrag:function(x,y){this.isDragged=false;this.invalidatePositionCache();},onDrop:function(obj){},onHoverStart:function(obj){},onHoverEnd:function(obj){},keyDown:function(_F){},keyUp:function(_F){},_4y:function(e){if(!Event.element){return;}
var _i=Event.element(e);while(_i&&_i.ctrl===undefined){_i=_i.parentNode;}
if(!_i){return;}
var _0=_i.ctrl;EVENT.focus(_0);Event.stop(e);},_4x:function(e){if(!Event.element){return;}
var _i=Event.element(e);while(_i&&_i.ctrl===undefined){_i=_i.parentNode;}
if(!_i){return;}
var _0=_i.owner;EVENT.blur(_0);Event.stop(e);},invalidatePositionCache:function(){this.base();EVENT.coordCacheFlush(this.elemId);}},{stopPropagation:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}},H_CONTROL_ON:1,H_CONTROL_OFF:0,CSS_DISABLED:"disabled",CSS_ENABLED:"enabled",CSS_ACTIVE:"active"});HDummyValue=HClass.extend({constructor:function(_3,_4){this.id=_3;this.value=_4;this.type='[HDummyValue]';},set:function(_4){this.value=_4;},get:function(){return this.value;},bind:function(_1U){},unbind:function(_1U){}});HComponentDefaults=HClass.extend({label:"Untitled",visible:true,events:{},value:0,action:function(){},enabled:true,active:false,minValue:-2147483648,maxValue:2147483648});HDynControl=HControl.extend({componentName:'dyncontrol',constructor:function(_1,_c,_2){if(!_2){_2={};}
var _s=HClass.extend({minSize:[24,54],maxSize:[16000,9000],resizeW:1,resizeE:1,resizeN:1,resizeS:1,resizeNW:[1,1],resizeNE:[1,1],resizeSW:[1,1],resizeSE:[1,1],noResize:false});_2=new(_s.extend(_2))();if(_2.noResize){_2.minSize=[_1.width,_1.height];_2.maxSize=[_1.width,_1.height];_2.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.presrveTheme=true;this.setDraggable(true);this.type="[HDynControl]";this._6d();this._4d();if(!this.isinherited){this.draw();}},drawRect:function(_4o,_73){if(this.rect.width<this.options.minSize[0]){var _2W=0-(this.options.minSize[0]-this.rect.width);this.rect.setWidth(this.options.minSize[0]);if(_4o){this.rect.offsetBy(_2W,0);}}
else if(this.rect.width>this.options.maxSize[0]){var _2W=0-(this.options.maxSize[0]-this.rect.width);this.rect.setWidth(this.options.maxSize[0]);if(_4o){this.rect.offsetBy(_2W,0);}}
if(this.rect.height<this.options.minSize[1]){var _2T=0-(this.options.minSize[1]-this.rect.height);this.rect.setHeight(this.options.minSize[1]);if(_73){this.rect.offsetBy(0,_2T);}}
else if(this.rect.height>this.options.maxSize[1]){var _2T=0-(this.options.maxSize[1]-this.rect.height);this.rect.setHeight(this.options.maxSize[1]);if(_73){this.rect.offsetBy(0,_2T);}}
this.base();},draw:function(){var _1H=_0.drawn;this.base();this.drawRect();if(!_1H){this.drawMarkup();this.buildStructure();}},buildStructure:function(){},_z:function(_5,_8){return this._6x.subtract(_5,_8);},dynResizeNW:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setLeftTop(_0.rect.leftTop.subtract(_I));_0.drawRect(1,1);_0._6x.set(_5,_8);},dynResizeNE:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setRightTop(_0.rect.rightTop.subtract(_I));_0.drawRect(0,1);_0._6x.set(_5,_8);},dynResizeSW:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setLeftBottom(_0.rect.leftBottom.subtract(_I));_0.drawRect(1,0);_0._6x.set(_5,_8);},dynResizeSE:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setRightBottom(_0.rect.rightBottom.subtract(_I));_0.drawRect(0,0);_0._6x.set(_5,_8);},dynResizeW:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setLeft(_0.rect.left-_I.x);_0.drawRect(1,0);_0._6x.set(_5,_8);},dynResizeE:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setRight(_0.rect.right-_I.x);_0.drawRect(0,0);_0._6x.set(_5,_8);},dynResizeN:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setTop(_0.rect.top-_I.y);_0.drawRect(0,1);_0._6x.set(_5,_8);},dynResizeS:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.setBottom(_0.rect.bottom-_I.y);_0.drawRect(0,0);_0._6x.set(_5,_8);},dynDrag:function(_0,_5,_8){var _I=_0._z(_5,_8);_0.rect.offsetTo(_0.rect.leftTop.subtract(_I));_0.drawRect(1,1);_0._6x.set(_5,_8);},_6d:function(){this._Z=[];var i,_0=this,_7X=0,_7W=1,_80=2,_7Z=3,_81=4,_7U=5,_7V=6,_7Y=7,_7y=8,_Z=this._Z;_Z[_7X]=_0.dynResizeNW;_Z[_7W]=_0.dynResizeNE;_Z[_80]=_0.dynResizeSW;_Z[_7Z]=_0.dynResizeSE;_Z[_81]=_0.dynResizeW;_Z[_7U]=_0.dynResizeE;_Z[_7V]=_0.dynResizeN;_Z[_7Y]=_0.dynResizeS;_Z[_7y]=_0.dynDrag;},_4d:function(){this._1j=-1;this._1Y=[];var i,_1P,_t=this.options,_1=this.rect,_6B=[[0,0,_t.resizeNW[0],_t.resizeNW[1]],[_1.width-_t.resizeNE[0],0,_1.width,_t.resizeNE[1]],[0,_1.height-_t.resizeSW[1],_t.resizeSW[0],_1.height],[_1.width-_t.resizeSE[0],_1.height-_t.resizeSE[1],_1.width,_1.height],[0,_t.resizeN,_t.resizeW,_1.height-_t.resizeS],[_1.width-_t.resizeE,_t.resizeN,_1.width,_1.height-_t.resizeS],[_t.resizeW,0,_1.width-_t.resizeE,_t.resizeN],[_t.resizeW,_1.height-_t.resizeS,_1.width-_t.resizeE,_1.height],[_t.resizeW,_t.resizeN,_1.width-_t.resizeE,_1.height-_t.resizeS]];for(i=0;i!=9;i++){_1P=_6B[i];this._1Y.push(new HRect(_1P[0],_1P[1],_1P[2],_1P[3]));}},_5I:function(){var i,_5l=this._6M.subtract(this.rect.left,this.rect.top),_1Y=this._1Y;for(i=0;i!=9;i++){if(_1Y[i].contains(_5l)){this._1j=i;return;}}},startDrag:function(_5,_8,_2d){this._6M=new HPoint(_5,_8);this._6x=new HPoint(_5,_8);this._86=new HRect(this.rect);this._5I();if(this._1j==8){this.setStyle('cursor','move');}
this.bringToFront();this.doDrag(_5,_8,_2d);},doDrag:function(_5,_8,_2d){if(this._1j!=-1){this._Z[this._1j](this,_5,_8);}},endDrag:function(_5,_8,_2d){this.doDrag(_5,_8,_2d);if(this._1j==8){this.setStyle('cursor','default');}
this._4d();}});