
HClass=function(){if(arguments.length){if(this===window){HClass.prototype.extend.call(arguments[0],arguments.callee.prototype);}
else{this.extend(arguments[0]);}}};HClass.prototype={extend:function(_r0,_1){var _c0=HClass.prototype.extend;if(arguments.length===2){var _s3=this[_r0];if((_s3 instanceof Function)&&(_1 instanceof Function)&&_s3.valueOf()!==_1.valueOf()&&(/\bbase\b/).test(_1)){var _f0=_1;_1=function(){var _s6=this.base;this.base=_s3;var _t6=_f0.apply(this,arguments);this.base=_s6;return _t6;};_1.valueOf=function(){return _f0;};_1.toString=function(){return String(_f0);};}
return this[_r0]=_1;}else if(_r0){var _g0={toSource:null};var _i4=["toString","valueOf"];if(HClass._c3){_i4.push("constructor");}
for(var i=0;(_i=_i4[i]);i++){if(_r0[_i]!==_g0[_i]){_c0.call(this,_i,_r0[_i]);}}
for(var _i in _r0){if(!_g0[_i]){_c0.call(this,_i,_r0[_i]);}}}
this.nu=function(){return new(this.extend({constructor:function(args){this.base.apply(this,args);}}))(arguments);};return this;},base:function(){}};HClass.extend=function(_Q,_b3){var _c0=HClass.prototype.extend;if(!_Q){_Q={};}
HClass._c3=true;var _g0=new this;_c0.call(_g0,_Q);var _j1=_g0.constructor;_g0.constructor=this;delete HClass._c3;var _O0=function(){if(!HClass._c3){_j1.apply(this,arguments);}
this.constructor=_O0;};_O0.prototype=_g0;_O0.extend=this.extend;_O0.implement=this.implement;_O0.toString=function(){return String(_j1);};_c0.call(_O0,_b3);var _93=(_j1!==null)?_O0:_g0;if(_93.init instanceof Function){_93.init();}
return _93;};HClass.implement=function(_q1){if(_q1 instanceof Function){_q1=_q1.prototype;}
this.prototype.extend(_q1);};var Base=HClass;if([]['indexOf']===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_u6){var i=0,l=this.length;for(;i<l;i++){if(this[i]===_u6){return i;}}
return-1;}});}
COMM={_Ja:function(){alert("'ERROR: This web browser doesn't support XMLHttpRequest. Please upgrade; unable to continue.");},_r4:function(_0){if(_0.X.readyState===4){var _e2=_0.X.status,_s4='on'+_e2,_v6=((_e2>=200&&_e2<300)||(_e2===0));_0[_s4]?_0[_s4](_0):_v6?_0.onSuccess(_0):_0.onFailure(_0);}},_53:function(_u1){var i=0,_y0=_u1.length,_23='';for(;i<_y0;i++){_23+=encodeURIComponent(_u1[i]);_23+=(i===_y0-1)?'':(i%2===0)?'=':'&';}
return _23;},request:function(_y,_4){var _f2=COMM,_0=_4?_4:{},_f0=_4.method?_4.method.toUpperCase():'GET',_21=(_4.async===undefined)?true:_4.async,_u1=_4.params?_4.params:[],_13=_4.headers?_4.headers:{},_W0=_4.contentType?_4.contentType:'application/x-www-form-urlencoded',_w6=_4.charset?_4.charset:'UTF-8',_x6=_4.username?_4.username:null,_y6=_4.username?_4.password:null;if(!_4.onFailure){_0.onFailure=function(resp){console.log('No failure handler specified, response: ',resp);};}
if(!_4.onSuccess){_0.onSuccess=function(resp){console.log('No success handler specified, response: ',resp);};}
_0.url=_y;_0.options=_4;_0.X=_f2._X2();if(_f0==='GET'&&_u1.length!==0){_y+=((_y.indexOf('?')!==-1)?'&':'?')+_f2._53(_u1);}
if(!_21){console.log("WARNING: Synchronous "+_f0+" request to "+_y+", these will fail on the Symbian web browser.");}
_0.X.open(_f0,_y,_21,_x6,_y6);_0.X.onreadystatechange=function(){_f2._r4(_0);};if(_f0==='POST'){_13['Content-Type']=_W0+'; charset='+_w6;var _M3=_4.body?_4.body:'';for(var _J4 in _13){_0.X.setRequestHeader(_J4,_13[_J4]);}
_0.X.send(_M3);}
else if(_f0==='GET'){_0.X.send(null);}
if(!_21){_f2._r4(_0);}
return _0;}};if(window['XMLHttpRequest']!==undefined){COMM._X2=function(){return new XMLHttpRequest();};}
else if(BROWSER_TYPE.ie){COMM._X2=function(){return new ActiveXObject("Msxml2.XMLHTTP");};}
else{COMM._X2=function(){console.log("No XMLHttpRequest object types known. Can't Communicate.");return new COMM._Ma();};}
HSystem=HClass.extend({windowFocusBehaviour:1,constructor:null,apps:[],appPriorities:[],busyApps:[],freeAppIds:[],defaultInterval:10,defaultPriority:20,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){for(var _l=0;_l<this.apps.length;_l++){if(this.apps[_l]){if(!this.busyApps[_l]){if((this.ticks%this.appPriorities[_l])===0){if(HSystem.apps[_l]){HSystem.apps[_l]._K4();}}}}}
if(this._l1.length!==0){this._z6();}},ticker:function(){this.ticks++;this.scheduler();this._La=setTimeout(function(){HSystem.ticker();},this.defaultInterval);},addApp:function(_v0,_U){var _l;if(this.freeAppIds.length!==0){_l=this.freeAppIds.unshift();this.apps[_l]=_v0;}else{this.apps.push(_v0);_l=this.apps.length-1;}
_v0.parent=this;_v0.parents=[this];_v0.appId=_l;this.startApp(_l,_U);return _l;},startApp:function(_l,_U){if(_U===undefined){_U=this.defaultInterval;}
this.appPriorities[_l]=_U;this.busyApps[_l]=false;},stopApp:function(_l){this.busyApps[_l]=true;},reniceApp:function(_l,_U){this.appPriorities[_l]=_U;},killApp:function(_l,_O4){if(!_O4){var _A6=new Date().getTime();while(this.busyApps[_l]===true){if(new Date().getTime()>_A6+this.maxAppRunTime){break;}}}
this.busyApps[_l]=true;this.apps[_l].destroyAllViews();this.apps[_l]=null;this.freeAppIds.push(_l);},views:[],_K2:[],addView:function(_c){var _g2;if(this._K2.length===0){_g2=this.views.length;this.views.push(_c);}
else{_g2=this._K2.pop();this.views[_g2]=_c;}
return _g2;},delView:function(_e){this.views[_e]=null;this._K2.push(_e);},activeWindowId:0,windowFocus:function(_c){if(!_c){this.activeWindowId=0;return;}
var _q3=this.activeWindowId,_S=this.views,_e=_c.viewId;if(_S[_q3]){if(_S[_q3]["windowBlur"]){_S[_q3].windowBlur();}}
this.activeWindowId=_e;_c.bringToFront();_c.windowFocus();},_l1:[],updateZIndexOfChildren:function(_e){if(this._l1.indexOf(_e)===-1){this._l1.push(_e);}},_z6:function(){var j=0,_0=HSystem,_U4=this._l1,_B6=_U4.length;for(;j<_B6;j++){var _e=_U4.shift(),_S=((_e===null)?(_0.viewsZOrder):(_0.views[_e].viewsZOrder)),_C6=_S.length,_C1=ELEM.setStyle,_J3=_0.views,_V4,_c,_D6='elemId',_E6='z-index',i=0,_6;for(;i<_C6;i++){_V4=_S[i];_c=_J3[_V4];_6=_c[_D6];_C1(_6,_E6,i);}}}});LOAD(function(){HSystem.ticker();});HApplication=HClass.extend({componentBehaviour:['app'],constructor:function(_U,_f){this.viewId=null;this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_U);if(_f){this.label=_f;}
else{this.label='ProcessID='+this.appId;}},buildParents:function(_e){var _c=HSystem.views[_e],i=0;_c.parent=this;_c.parents=[];for(;i<this.parents.length;i++){_c.parents.push(this.parents[i]);}
_c.parents.push(this);},addView:function(_c){var _e=HSystem.addView(_c);this.views.push(_e);this.buildParents(_e);this.viewsZOrder.push(_e);return _e;},removeView:function(_e){HSystem.views[_e].remove();},destroyView:function(_e){HSystem.views[_e].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){for(var i=0;i<this.views.length;i++){HSystem.views[this.views[i]].die();}},_F6:function(){var i,_e,_c;for(i=0;i<this.views.length;i++){_e=this.views[i];_c=HSystem.views[_e];if((_c!==null)&&(_c['onIdle']!==undefined)){_c.onIdle();}}},_K4:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._F6();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});LOAD(function(){COMM.URLResponder.implement(HValueResponder);COMM.urlResponder=COMM.URLResponder.nu();urlResponder=COMM.urlResponder;COMM.Transporter.url=HCLIENT_HELLO;COMM.Transporter.stop=false;COMM.Transporter.sync();});HValue=HClass.extend({constructor:function(_2,_1){this.id=_2;this.type='[HValue]';this.value=_1;this.views=[];if(_2){COMM.Values.add(_2,this);}},die:function(){for(var _R=0;_R<this.views.length;_R++){var _y3=this.views[_R];_y3.setValueObj(HDummyValue.nu());this.views.splice(_R,1);}
if(this.id){COMM.Values.del(this.id);}},set:function(_1){if(this.differs(_1)){this.value=_1;if(this.id){COMM.Values.changed(this);}
this.refresh();}},differs:function(_1){return(COMM.Values.encode(_1)!==COMM.Values.encode(this.value));},s:function(_1){this.value=_1;this.refresh();},get:function(){return this.value;},bind:function(_L){if(_L===undefined){throw("HValueBindError: responder is undefined!");}
if(this.views.indexOf(_L)===-1){this.views.push(_L);_L.setValueObj(this);}},unbind:function(_L){for(var _R=0;_R<this.views.length;_R++){var _y3=this.views[_R];if(_y3===_L){this.views.splice(_R,1);return;}}},release:function(_L){return this.unbind(_L);},refresh:function(){for(var _R=0;_R<this.views.length;_R++){var _L=this.views[_R];if(_L.value!==this.value){if(!_L._h4){_L._h4=true;_L.setValue(this.value);_L._h4=false;}}}}});COMM.JSLoader=HClass.extend({constructor:function(_G6){var _0=this;_0._o4=[];_0.uri=_G6;_0._Ha=false;},_H6:function(_0,_m0){console.log("failed to load js: "+_m0.url);},load:function(_H1){var _0=this;if((_0._o4.indexOf(_H1)!==-1)){return;}
COMM.Queue.pause();_0._o4.push(_H1);if(BROWSER_TYPE.ie||BROWSER_TYPE.symbian){_0._Oa=COMM.request(_0.uri+_H1+'.js',{onSuccess:function(_m0){COMM.Queue.unshiftEval(_m0.X.responseText);COMM.Queue.resume();},onFailure:_0._H6,method:'GET',async:true});}
else{var _J1=document.createElement('script');_J1.onload=function(){COMM.Queue.resume();};_J1.src=_0.uri+_H1+'.js';_J1.type='text/javascript';document.getElementsByTagName('head')[0].appendChild(_J1);}}});JSLoader=COMM.JSLoader;LOAD(function(){COMM.jsLoader=COMM.JSLoader.nu(HCLIENT_BASE+'/js/');jsLoader=COMM.jsLoader;});