
HButton=HControl.extend({componentName:'button',setStyle:function(_i,_1){ELEM.setStyle(this.markupElemIds.label,_i,_1);}});HClickValueButton=HButton.extend({refreshValue:function(){this.setEnabled(this.value===0);},click:function(){if(this.enabled){this.setValue(1);}}});HCheckbox=HButton.extend({componentName:'checkbox',controlDefaults:(HControlDefaults.extend({constructor:function(){if(!this.events){this.events={click:true}}}})),click:function(){this.setValue(!this.value);},setStyle:function(_i,_1,_T){this.setStyleOfPart('label',_i,_1,_T);},refreshValue:function(){if(this.markupElemIds.control){if(this.value){this.toggleCSSClass(this.markupElemIds.control,'checked',true);this.toggleCSSClass(this.markupElemIds.control,'unchecked',false);}
else{this.toggleCSSClass(this.markupElemIds.control,'checked',false);this.toggleCSSClass(this.markupElemIds.control,'unchecked',true);}}}});HCheckBox=HCheckbox;HRadioButton=HCheckbox.extend(HValueMatrixComponentExtension);HRadioButton.prototype.componentName='radiobutton';HRadiobutton=HRadioButton;HStringView=HControl.extend({componentName:"stringview",componentBehaviour:['view','control','text'],setStyle:function(_i,_1,_R0){if(!this['markupElemIds']||!this.markupElemIds['value']){return;}
ELEM.setStyle(this.markupElemIds.value,_i,_1,_R0);},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'title',this.label);}}}});HTextControl=HControl.extend({componentName:"textcontrol",controlDefaults:(HControlDefaults.extend({constructor:function(_a){if(!this.events){this.events={textEnter:true};}}})),refreshLabel:function(){if(this['markupElemIds']!==undefined){if(this.markupElemIds['label']!==undefined){ELEM.setAttr(this.markupElemIds.label,'title',this.label);}}},drawSubviews:function(){if(this['markupElemIds']!==undefined){if(this.markupElemIds['label']!==undefined){var _D=this.markupElemIds.value,_f=this.markupElemIds.label;if(BROWSER_TYPE.firefox){if(this.componentName==='textarea'){ELEM.setStyle(_D,'padding-top','0px');}
else{ELEM.setStyle(_D,'margin-top','1px');}
ELEM.setStyle(_D,'padding-left','0px');ELEM.setStyle(_f,'left','2px');ELEM.setStyle(_f,'top','0px');ELEM.setStyle(_f,'right','2px');ELEM.setStyle(_f,'bottom','2px');}
else if(BROWSER_TYPE.ie){ELEM.flushLoop();var _o0=ELEM.getVisibleSize(this.elemId),_w=_o0[0],_B=_o0[1];ELEM.setStyle(_D,'left','2px');ELEM.setStyle(_D,'top','1px');ELEM.setStyle(_D,'padding-top','0px');ELEM.setStyle(_D,'padding-left','0px');ELEM.setStyle(_D,'padding-right','8px');ELEM.setStyle(_D,'padding-bottom','0px');ELEM.setStyle(_D,'width',(_w-10)+'px');ELEM.setStyle(_D,'height',(_B-2)+'px');ELEM.setStyle(_f,'left','0px');ELEM.setStyle(_f,'top','0px');ELEM.setStyle(_f,'right','0px');ELEM.setStyle(_f,'bottom','0px');}
else if(BROWSER_TYPE.safari||BROWSER_TYPE.chrome){ELEM.setStyle(_D,'width','auto');ELEM.setStyle(_D,'height','auto');ELEM.setStyle(_D,'left','-2px');ELEM.setStyle(_D,'top','-2px');if(BROWSER_TYPE.chrome){ELEM.setStyle(_D,'right','0px');ELEM.setStyle(_D,'bottom','0px');}
else{ELEM.setStyle(_D,'right','-2px');ELEM.setStyle(_D,'bottom','-2px');}
ELEM.setStyle(_f,'left','0px');ELEM.setStyle(_f,'top','0px');ELEM.setStyle(_f,'right','0px');ELEM.setStyle(_f,'bottom','0px');}}}
this.setEnabled(this.enabled);},setStyle:function(_i,_1,_R0){if(!this['markupElemIds']||!this.markupElemIds['value']){return;}
this.setStyleOfPart('value',_i,_1,_R0);},setEnabled:function(_9){this.base(_9);if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).disabled=!this.enabled;}},hasTextFocus:false,textFocus:function(){this.hasTextFocus=true;return true;},textBlur:function(){this.hasTextFocus=false;return true;},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).value=this.value;}}},validateText:function(_1){return _1;},getTextFieldValue:function(){return ELEM.get(this.markupElemIds.value).value;},textEnter:function(){if(this['markupElemIds']===undefined){return;}
var _1=this.validateText(this.getTextFieldValue());if(_1!==this.value.toString()){this.setValue(_1);}}});HNumericTextControl=HTextControl.extend({mouseWheel:function(_V){var _1=this.value;_1=_1-((_V<0)?1:-1);this.setValue(Math.round(this.validateText(_1)));},validateText:function(_1){if(isNaN(_1)){_1=this.value;}
_1=parseInt(_1,10);if(_1>this.options.maxValue){_1=this.options.maxValue;}
else if(_1<this.options.minValue){_1=this.options.minValue;}
if(this['markupElemIds']&&this.markupElemIds['value']){var _5=ELEM.get(this.markupElemIds.value);if(_5.value!=_1){_5.value=_1;}}
return _1;},setValue:function(_1){this.base(this.validateText(_1));}});HPasswordControl=HTextControl.extend({componentName:'passwordcontrol'});HTextArea=HTextControl.extend({componentName:"textarea"});HUploader=HControl.extend({componentName:'uploader',uploadState:false,uploadKey:false,uploadStateLabels:{'0':"Select file...",'1':"Uploading...",'2':"Processing data...",'3':"Upload Complete",'4':"Preparing upload",'-1':"Error: Invalid request",'-2':"Error: Invalid upload key",'-3':"Error: Invalid data format",'-4':"Error: File too big",'-6':"Error: Post-processing failed"},markupElemNames:['form','file','iframe','upload_progress','progress_label','progress_indicator','button','button_label','value','ack_button'],setUploadState:function(_J,_z1){if(_J!==this.uploadState){this.uploadState=_J;var _U2=_J.toString();if(this.uploadStateLabels[_U2]!==undefined){ELEM.get(this.markupElemIds.value).value=this.valueObj.id;var _f=this.uploadStateLabels[_U2];if(_J===0){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','hidden');ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');ELEM.setHTML(this.markupElemIds.button_label,_f);ELEM.setStyle(this.markupElemIds.button,'visibility','inherit');ELEM.setStyle(this.markupElemIds.form,'visibility','inherit');ELEM.setAttr(this.markupElemIds.form,'action','/U/'+_z1,true);ELEM.get(this.markupElemIds.file).value='';this.uploadKey=_z1;}
else if(_J===1||_J===2||_J===3||_J===4){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','inherit');if(_J===1||_J===2||_J===4){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','inherit');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');}
else{ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');}
ELEM.setHTML(this.markupElemIds.progress_label,_f);ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');if(_J===1){ELEM.get(this.markupElemIds.form).submit();}}
else if(_J<0){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');ELEM.setHTML(this.markupElemIds.progress_label,'<span style="color:red;">'+_f+'</span>');ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');}}}},refreshValue:function(){if(typeof this.value!=='string'){return;}
if(this.value.indexOf(':::')<1){return;}
var _N2=this.value.split(':::');if(_N2.length!==2){return;}
var _J=parseInt(_N2[0],10),_z1=_N2[1];this.setUploadState(_J,_z1);},upload:function(){this.setValue('1:::'+this.uploadKey);},getNewUploadKey:function(){this.setValue('4:::'+this.uploadKey);},click:function(){if((this.uploadState===3)||(this.uploadState<0)){this.getNewUploadKey();}}});HSlider=HControl.extend({componentName:"slider",controlDefaults:(HControlDefaults.extend({minValue:0,maxValue:1,repeatDelay:300,repeatInterval:50,inverseAxis:false,constructor:function(_a){if(!this.events){this.events={draggable:true,keyDown:true,keyUp:true,mouseWheel:true};}}})),refreshOnValueChange:false,_20:false,setValue:function(_1){if(_1<this.minValue){_1=this.minValue;}
if(_1>this.maxValue){_1=this.maxValue;}
this.base(_1);if(this._R4){this.drawThumbPos();}
return this;},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._26();}
this.refresh();},startDrag:function(_n,_j){var _k4=ELEM.getVisiblePosition(this.elemId,true);this._36=_k4[0];this._46=_k4[1];this.drag(_n,_j);},endDrag:function(_n,_j){this.drag(_n,_j);},drag:function(_n,_j){_n-=this._36;_j-=this._46;var _56=this._20?_j:_n;var _1=this._66(_56);this.setValue(_1);},keyDown:function(_O){if((_O===Event.KEY_LEFT&&!this._20)||(_O===Event.KEY_DOWN&&this._20)){this._o1=true;this._r1(-0.05);}
else if((_O===Event.KEY_RIGHT&&!this._20)||(_O===Event.KEY_UP&&this._20)){this._o1=true;this._r1(0.05);}
else if(_O===Event.KEY_HOME){this.setValue(this.minValue);}
else if(_O===Event.KEY_END){this.setValue(this.maxValue);}
else if(_O===Event.KEY_PAGEDOWN){this._o1=true;this._r1(-0.25);}
else if(_O===Event.KEY_PAGEUP){this._o1=true;this._r1(0.25);}},keyUp:function(_O){this._o1=false;},mouseWheel:function(_V){var _u0;if(_V>0){_u0=0.05;}
else{_u0=-0.05;}
if(this.options.inverseAxis){_u0=0-_u0;}
var _1=(this.maxValue-this.minValue)*_u0;this.setValue(this.value+_1);},_r1:function(_u0,_01){if(!_01){_01=this.options.repeatDelay;}
else if(_01===this.options.repeatDelay){_01=this.options.repeatInterval;}
if(this._o1&&this.active){var _1=(this.maxValue-this.minValue)*_u0;this.setValue(this.value+_1);var _t=this;if(this._Z2){window.clearTimeout(this._Z2);this._Z2=null;}
this._Z2=window.setTimeout(function(){_t._r1(_u0,_01);},_01);}},thumbSize:21,_26:function(){this._R4=this.markupElemIds.control;this.drawThumbPos();},_76:function(){var _60;if(this._20){_60=this.rect.height-this.thumbSize;}else{_60=this.rect.width-this.thumbSize;}
var _B3=_60*((this.value-this.minValue)/(this.maxValue-this.minValue));if(this._20){_B3=_60-_B3;}
_86=parseInt(_B3,10)+'px';return _86;},_66:function(_F0){var _60;if(this._20){_60=this.rect.height-this.thumbSize;}else{_60=this.rect.width-this.thumbSize;}
_F0-=(this.thumbSize/2);if(_F0<0){_F0=0;}
if(_F0>_60){_F0=_60;}
if(this._20){return this.maxValue-((_F0/_60)*(this.maxValue-this.minValue));}else{return this.minValue+((_F0/_60)*(this.maxValue-this.minValue));}},drawThumbPos:function(){var _96=this._20?'top':'left',_a6=this._76();ELEM.setStyle(this._R4,_96,_a6);this.setOrientation(this.options['orientation']||this.prevOrientation);},prevOrientation:'c',cssClassPrefix:'h',setOrientation:function(_i0){if(!_i0){_i0='c';}
_i0=_i0.toLowerCase();if(_i0===this.prevOrientation){return;}
if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds['control']===undefined){return;}
var _b6=this.toggleCSSClass,_V2=this.markupElemIds.control,_c6=['n','s','w','e','c'],_T2='',_M4='',_N4=this.cssClassPrefix,_d6=this._20?'v':'',_S4=false,i=0;for(;i<5;i++){_T2=_c6[i];_S4=(_i0===_T2);_M4=(_i0==='c')?_N4+_d6+'slider_thumb':_N4+'slider_thumb_'+_T2;_b6(_V2,_M4,_S4);}
this.prevOrientation=_i0;}});HVSlider=HSlider.extend({componentName:"vslider",_20:true});HProgressBar=HControl.extend({componentName:"progressbar",themeWidthInset:2,refreshValue:function(){if(this.drawn&&this.markupElemIds.value){var _e6=ELEM.getVisibleSize(this.elemId)[0]-this.themeWidthInset,_f6=_e6/this.maxValue,_g6=Math.round(_f6*this.value);this.setStyleOfPart('value','width',_g6+'px');}}});HProgressIndicator=HView.extend({_i2:null,_W2:0,drawSubviews:function(){var _0=this;_0.setStyle('border','1px solid #999');_0.setStyle('background-color','#ccc');var _B=_0.rect.height,_w=ELEM.getVisibleSize(_0.elemId)[0]-2;_0['_3'+0]=HRect.nu(0,0,_B,_B);_0['_3'+1]=HRect.nu(_w-_B,0,_w,_B);_0._i2=HView.nu(HRect.nu(_0['_3'+0]),_0);_0._i2.setStyle('background-color','#333');_0._i2.onAnimationEnd=function(){this.parent._I4();};_0._I4();},_I4:function(){this._W2=this._W2===1?0:1;var _h6=HRect.nu(this['_3'+this._W2]);this._i2.animateTo(_h6);}});HImageView=HControl.extend({controlDefaults:(HControlDefaults.extend({scaleToFit:true,value:null,constructor:function(_a){if(this.value===null){this.value=_a.getThemeGfxPath()+"/blank.gif";}}})),_t4:function(_Y0){this.elemId=ELEM.make(_Y0,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_p4:function(_Y0){this.elemId=ELEM.make(_Y0,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_z4:function(_Y0){if(this.options.scaleToFit){this._t4(_Y0);}
else{this._p4(_Y0);}},refreshValue:function(){ELEM.setAttr(this.elemId,'src',this.value);},refreshLabel:function(){ELEM.setAttr(this.elemId,'alt',this.label);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._t4(this._w3());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._p4(this._w3());this.options.scaleToFit=false;}}});HStepper=HControl.extend({componentName:"stepper",controlDefaults:(HControlDefaults.extend({minValue:0,maxValue:100,stepSize:1,repeatInterval:200,wrapAround:false,constructor:function(_a){if(!this.events){this.events={mouseDown:true,keyDown:true,mouseWheel:true};}}})),setWrapAround:function(_i6){this.options.wrapAround=_i6;},_D4:function(_1){var _0=this,_4=_0.options,_H4=_4.minValue,_P4=_4.maxValue,_W4=_1<_H4,_j6=_1>_P4,_k6=(_W4||_j6);if(!_k6){return _1;}
if(_4.wrapAround){if(_W4){return _P4;}
else{return _H4;}}
else{return _0.value;}},stepUp:function(){this.setValue(this._D4(this.value+this.options.stepSize));},stepDown:function(){this.setValue(this._D4(this.value-this.options.stepSize));},_B4:function(_J0){return['HSystem.views[',this.viewId,'].step',(_J0?'Up':'Down'),'();'].join('');},bgStateUp:'0px -23px',bgStateDown:'0px -46px',_l6:function(_J0){ELEM.setStyle(this.markupElemIds.state,'background-position',_J0?this.bgStateUp:this.bgStateDown);},_m6:function(){ELEM.setStyle(this.markupElemIds.state,'background-position','');},_Z0:function(_J0){var _0=this,_4=_0.options;_0._l6(_J0);if(_J0){_0.stepUp();_0._y4=setInterval(_0._B4(1),_4.repeatInterval);}
else{_0.stepDown();_0._y4=setInterval(_0._B4(0),_4.repeatInterval);}},_u3:function(){this._m6();clearInterval(this._y4);},mouseDown:function(x,y){this.setMouseUp(true);this._Z0((y-ELEM.getVisiblePosition(this.elemId)[1])<=11);},mouseUp:function(){this._u3();},blur:function(){this._u3();},keyDown:function(_w0){this.setKeyUp(true);var _n6=(_w0===Event.KEY_DOWN),_l4=(_w0===Event.KEY_UP),_o6=(_w0===Event.KEY_LEFT),_n4=(_w0===Event.KEY_RIGHT),_p6=(_n6||_l4||_o6||_n4);if(_p6){this._Z0((_l4||_n4));}
else if(_w0===Event.KEY_HOME){this.setValue(this.options.minValue);}
else if(_w0===Event.KEY_END){this.setValue(this.options.maxValue);}
else if(_w0===Event.KEY_PAGEUP){this._Z0(1);}
else if(_w0===Event.KEY_PAGEDOWN){this._Z0(0);}},keyUp:function(){this._u3();},mouseWheel:function(_V){(_V>0)?this.stepUp():this.stepDown();}});HValidatorView=HControl.extend({constructor:function(_3,_h,_4){if(_4!==undefined){if(_4.valueField&&_4.valueField.componentBehaviour[1]==='control'){_3.offsetTo(_4.valueField.rect.right,_4.valueField.rect.top);}}
this.base(_3,_h,_4);},setValue:function(_9){if(!_9&&_9!==false){_9=false;}
this.base(_9);},refreshValue:function(){var _0=this,_1=_0.value,_x4=_1===true,_n=_x4?-21:0,_j=_0.enabled?0:-21,_A2=_x4?'':_1,_6=_0.elemId;ELEM.setStyle(_6,'background-image',"url("+_0.getThemeGfxFile('validator.png')+")");ELEM.setStyle(_6,'background-repeat','no-repeat');ELEM.setStyle(_6,'background-position',_n+'px '+_j+'px');}});HWindow=HDynControl.extend({componentName:'window',controlDefaults:(HDynControl.prototype.controlDefaults.extend({constructor:function(_a){var _e1=ELEM.windowSize(),_R2=_e1[0],_O2=_e1[1];if(!this.minSize){this.minSize=[96,54];}
if(!this.maxSize){this.maxSize=_e1;}
if(!this.maxX){this.maxX=_R2-this.minSize[0];}
if(!this.maxY){this.maxY=_O2-this.minSize[1];}
if(!this.events){this.events={draggable:true};}
if(!this.resizeNW){this.resizeNW=[6,6];}
if(!this.resizeNE){this.resizeNE=[6,6];}
if(!this.resizeSW){this.resizeSW=[6,6];}
if(!this.resizeSE){this.resizeSE=[16,16];}},resizeW:4,resizeE:4,resizeN:4,resizeS:4,fullWindowMove:false,closeButton:false,collapseButton:false,zoomButton:false})),draw:function(){var _q6=this.drawn;this.base();if(!_q6){HSystem.windowFocus(this);}},makeRectRules:function(){var _0=this,_J2=_0.base(),_3=_0.rect,_v=_0.options,_j2=_v.resizeW;if(!_v.fullWindowMove){if(_v.zoomButton){_j2=61;}
else if(_v.collapseButton){_j2=46;}
else if(_v.closeButton){_j2=27;}
_J2[8]=[_j2,_v.resizeN,_3.width-_v.resizeE,25];}
return _J2;},gainedActiveStatus:function(){HSystem.windowFocus(this);},windowFocus:function(){this.toggleCSSClass(this.elemId,'inactive',false);},windowBlur:function(){this.toggleCSSClass(this.elemId,'inactive',true);this.setStyle('cursor','default');},windowClose:function(){this.die();},windowCollapse:function(){var _G1=HRect.nu(this.rect.leftTop,this.rect.leftTop.subtract(0-this.options.minSize[0],0-this.options.minSize[1]));_G1.setHeight(26);if(this.rect.equals(_G1)){if(this.prevRect!==undefined&&!this.prevRect.equals(_G1)){this.animateTo(HRect.nu(this.prevRect));}
else{this.windowZoom();}}
else{this.prevRect=HRect.nu(_G1);this.animateTo(_G1);}},windowZoom:function(){var _16=HRect.nu(this.options.minX,this.options.minY,this.options.maxSize[0],this.options.maxSize[1]),_K=HRect.nu(this.rect),i=0,_S=this.views,_c,_o0,_Y,_A;for(;i<_S.length;i++){_c=HSystem.views[_S[i]];_o0=ELEM.getVisibleSize(_c.elemId);_K1=ELEM.getVisiblePosition(_c.elemId);_Y=_o0[0]+_K1[0];_A=_o0[1]+_K1[1];if(_Y>_K.width){_K.setWidth(_Y);}
if(_A>_K.height){_K.setHeight(_A);}}
if(_K.width>this.options.maxSize[0]){_K.setWidth(this.options.maxSize[0]);}
else if(_K.width<this.options.minSize[0]){_K.setWidth(this.options.minSize[0]);}
if(_K.height>this.options.maxSize[1]){_K.setHeight(this.options.maxSize[1]);}
else if(_K.height<this.options.minSize[1]){_K.setHeight(this.options.minSize[1]);}
if(this.rect.equals(_K)){if(this.prevRect!==undefined&&!this.prevRect.equals(_K)){this.animateTo(HRect.nu(this.prevRect));}
else{this.prevRect=HRect.nu(this.rect);this.animateTo(_16);}}
else{this.prevRect=HRect.nu(_K);this.animateTo(_K);}}});HTabView=HView.extend({draw:function(){var _d4=this.drawn;this.base();if(!_d4){var i=0,_i3=[['overflow','auto']];for(i;i<_i3.length;i++){this.setStyle(_i3[i][0],_i3[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:true,refreshOnLabelChange:false,controlDefaults:(HControlDefaults.extend({constructor:function(_a){if(!this.events){this.events={mouseDown:true};}
this.tabInit(_a);},tabInit:function(_a){_a.tabs=[];_a.tabLabels=[];_a.tabLabelBounds=[];_a.tabLabelStrings=[];}})),rightmostPx:0,selectIdx:-1,tabLabelHeight:20,tabLabelLeftEdge:4,tabLabelRightEdge:4,fontStyle:'font-family:Arial,sans-serif;font-size:13px;',tabLabelHTMLPrefix1:'<div class="edge-left"></div><div class="tablabel" style="width:',tabLabelHTMLPrefix2:'px">',tabLabelHTMLSuffix:'</div><div class="edge-right"></div>',tabLabelParentElem:'label',tabLabelElementTagName:'div',tabLabelAlign:'left',tabLabelFillBg:false,tabTriggerLink:false,tabLabelNoHTMLPrefix:false,refreshValue:function(){var _1=this.value;if(typeof _1==='number'){var _x=parseInt(_1,10);if(_x<this.tabs.length){if(_x!==this.selectIdx){this.selectTab(_x);}}}},setLabel:function(_f){this.label=_f;},selectTab:function(_o){if(_o instanceof HTabView){_o=_o.tabIndex;}
if(this.selectIdx!==-1){var _G4=this.tabLabels[this.selectIdx],_r6=this.tabs[this.selectIdx];ELEM.removeClassName(_G4,'item-fg');ELEM.addClassName(_G4,'item-bg');HSystem.views[_r6].hide();}
if(_o!==-1){var _00=this.tabLabels[_o],_f3=this.tabs[_o];ELEM.removeClassName(_00,'item-bg');ELEM.addClassName(_00,'item-fg');HSystem.views[_f3].show();}
this.selectIdx=_o;this.setValue(_o);},addTab:function(_A1,_Q4){var _o=this.tabs.length,_p3='',_E4=this.stringWidth(_A1),_03=_E4+this.tabLabelLeftEdge+this.tabLabelRightEdge,_k1=new HTabView([0,this.tabLabelHeight,null,null,0,0],this),_00=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);_o=this.tabs.length;if(this.tabLabelNoHTMLPrefix){_p3=_A1;}
else{_p3=this.tabLabelHTMLPrefix1+_E4+this.tabLabelHTMLPrefix2+_A1+this.tabLabelHTMLSuffix;}
_k1.hide();ELEM.addClassName(_00,'item-bg');ELEM.setStyle(_00,'width',_03+'px');ELEM.setStyle(_00,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_00,_p3);this.tabLabelStrings.push(_A1);if(this.tabTriggerLink&&this.tabLabelElementTagName==='a'){ELEM.setAttr(_00,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_o+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_00,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_o+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_03]);}
this.rightmostPx+=_03;if(this.tabLabelAlign==='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
else if(this.tabLabelFillBg){ELEM.setStyle(this.markupElemIds.state,'left',this.rightmostPx+'px');}
this.tabs.push(_k1.viewId);this.tabLabels.push(_00);_k1.tabIndex=_o;if(_Q4||(this.value===_o)){this.selectTab(_o);}
return _k1;},mouseDown:function(_n,_j){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_n-=this.pageX();_j-=this.pageY();if(_j<=this.tabLabelHeight){if(this.tabLabelAlign==='right'){_n=this.rect.width-_n;}
if(_n<=this.rightmostPx){var i=0,_v3;for(i;i<this.tabLabelBounds.length;i++){_v3=this.tabLabelBounds[i];if(_n<_v3[1]&&_n>=_v3[0]){this.selectTab(i);return;}}}}},removeTab:function(_o){var _C4=this.selectIdx,_f3=this.tabs[_o],_00=this.tabViews[_o];this.tabs.splice(_o,1);this.tabLabels.splice(_o,1);this.tabLabelBounds.splice(_o,1);this.tabLabelStrings.splice(_o,1);if(_o===_C4){this.selectIdx=-1;if(_o===0&&this.tabs.length===0){this.selectTab(-1);}
else if(_o===(this.tabs.length-1)){this.selectTab(_o-1);}
else{this.selectTab(_o);}}
else if(_o<_C4){this.selectIdx--;}
ELEM.del(_00);HSystem.views[_f3].die();}});HTabItem={nu:function(_3,_h,_4){return _h.addTab(_4.label,_4.select);}};HSheet=HControl.extend({componentName:'sheet',refreshValue:function(){if(this.value===0){this.show();}
else{this.hide();}},drawRect:function(){if(this.parent&&this.rect.isValid){var _0=this,_6=_0.elemId,_z=ELEM.setStyle,_3=_0.rect,_w=_3.width,_b0=0-Math.floor(_3.width/2),_B=_3.height;_z(_6,'left','0px',true);_z(_6,'top','0px',true);_z(_6,'right','0px',true);_z(_6,'bottom','0px',true);_z(_6,'width','auto',true);_z(_6,'height','auto',true);_z(_6,'min-width',_w+'px',true);_z(_6,'min-height',_B+'px',true);if(_0['markupElemIds']){var _d2=_0.markupElemIds['state'];_z(_d2,'left',_b0+'px',true);_z(_d2,'top','0px',true);_z(_d2,'width',_w+'px',true);_z(_d2,'height',_B+'px',true);}
if(undefined===_0.isHidden||_0.isHidden===false){_z(_6,'visibility','inherit',true);}
_z(_6,'display','block',true);_0._06();_0.drawn=true;}
return this;}});HAlertSheet=HSheet.extend({refreshLabel:function(){this.base();if(this['alertText']){this.alertText.setValue(this.label);}},drawSubviews:function(){this.icon=HImageView.nu([16,16,48,48],this,{value:this.getThemeGfxFile('sheet_warning.png')});this.alertText=HStringView.nu([80,16,null,null,8,48],this,{value:this.label});this.alertButtons();},alertButtons:function(){this.okButton=HClickValueButton.nu([null,null,60,23,8,8],this,{label:'OK',valueObj:this.valueObj,events:{click:true}});}});HConfirmSheet=HAlertSheet.extend({alertButtons:function(){this.cancelButton=HClickValueButton.extend({click:function(){this.setValue(-1);}}).nu([null,null,60,23,76,8],this,{label:'Cancel',valueObj:this.valueObj,events:{click:true}});this.base();}});