
HDateTime=HClass.extend({msWeek:604800000,msDay:86400000,msHour:3600000,msMinute:60000,months_localized:['January','February','March','April','May','June','July','August','September','October','November','December'],monthName:function(_8){_8=(_8 instanceof Date)?_8:this.date();return this.months_localized[_8.getUTCMonth()];},week:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _E7=this.firstDateOfYear(_8),_L2=this.firstDateOfWeek(_E7);if(_L2.getUTCDate()<=28){_L2=new Date(_L2.getTime()+this.msWeek-this.tzMs(_L2));}
var _b5=Math.ceil((((_8.getTime()-_L2-this.tzMs(_8))/this.msDay)+_E7.getUTCDay()+1)/7);if((_b5===53)&&(this.firstDateOfWeek(this.lastDateOfYear(_8)).getUTCDate()>28)){_b5=1;}
return _b5;},mday:function(_8){_8=(_8 instanceof Date)?_8:this.date();return _8.getUTCDate();},month:function(_8){_8=(_8 instanceof Date)?_8:this.date();return _8.getUTCMonth();},year:function(_8){_8=(_8 instanceof Date)?_8:this.date();return _8.getUTCFullYear();},tzMs:function(_8){return _8.getTimezoneOffset()*this.msMinute;},date:function(epoch_seconds){epoch_seconds=(typeof epoch_seconds==='number')?epoch_seconds:this.value;var _8=new Date(epoch_seconds*1000);return _8;},firstDateOfYear:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(_8.getUTCFullYear(),0,1),_f1=new Date(_q0.getTime()-this.tzMs(_q0));return _f1;},lastDateOfYear:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(new Date(_8.getUTCFullYear()+1,0,1)-1),_f1=new Date(_q0.getTime()-this.tzMs(_q0));return _f1;},firstDateOfMonth:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(_8.getUTCFullYear(),_8.getUTCMonth(),1),_f1=new Date(_q0.getTime()-this.tzMs(_q0));return _f1;},lastDateOfMonth:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(new Date(_8.getUTCFullYear(),_8.getUTCMonth()+1,1)-1),_f1=new Date(_q0.getTime()-this.tzMs(_q0));return _f1;},firstDateOfWeek:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _K5=_8.getUTCDay();if(_K5===0){_K5=7;}
var _v9=((_K5-1)*this.msDay),_q0=new Date(_8.getTime()-_v9),_f1=new Date(_q0.getTime());return _f1;},lastDateOfWeek:function(_8){var _u9=this.firstDateOfWeek(_8),_t9=new Date(_u9.getTime()+this.msWeek-this.msDay-1);return _t9;}});HCalendar=HControl.extend({componentName:'calendar',weekdays_localized:['Wk','Mon','Tue','Wed','Thu','Fri','Sat','Sun'],mouseWheel:function(_V){if(_V<0){this.nextMonth();}
else{this.prevMonth();}},refreshLabel:function(){var _N5=this.weekdays_localized,_p8=Math.floor(this.rect.width/_N5.length),_n8=[],i=0,_Ea=['<div style="width:'+_p8+'px;left:','px">'],_Da='</div>';for(;i<_N5.length;i++){_n8.push([_Ea.join(i*_p8),_N5[i],_Da].join(''));}
ELEM.setHTML(this.markupElemIds.label,_n8.join(''));},calendarDateRange:function(_8){var _Aa=this.firstDateOfMonth(_8),_va=this.lastDateOfMonth(_8),_z1=this.firstDateOfWeek(_Aa),_x2=this.lastDateOfWeek(_va),_ua=this.week(_z1),_ta=this.week(_x2),_F5=_ta-_ua;if((_F5===5)&&(_z1.getDate()!==1)){_x2=new Date(_x2.getTime()+this.msWeek);}
else if((_F5===5)&&(_z1.getDate()===1)){_z1=new Date(_z1.getTime()-this.msWeek);}
else if(_F5===4){_z1=new Date(_z1.getTime()-this.msWeek);_x2=new Date(_x2.getTime()+this.msWeek);}
return[_z1,_x2];},refreshValue:function(){var _8=this.date();this.drawCalendar(_8);},nextMonth:function(){var _8=new Date(this.viewMonth[0],this.viewMonth[1]+1,1);this.drawCalendar(new Date(_8.getTime()-this.tzMs(_8)));},prevMonth:function(){var _8=new Date(this.viewMonth[0],this.viewMonth[1]-1,1);this.drawCalendar(new Date(_8.getTime()-this.tzMs(_8)));},viewMonth:[1970,0],drawCalendar:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _f8=this.calendarDateRange(_8),_J5=this.firstDateOfMonth(_8),_na=this.lastDateOfMonth(_8),_ma=_f8[0],_5b=_f8[1],_ja=this.weekdays_localized.length,_O5=Math.floor((this.rect.width-1)/_ja),_m2=Math.floor((this.rect.height-1-35)/6),_ca=['<div class="calendar_weeks_week_row" style="width:'+(this.rect.width-3)+'px;height:'+_m2+'px;top:','px">'],_aa='</div>',_44=['<a href="javascript:void(HSystem.views['+this.viewId+'].setValue(','));" class="calendar_weeks_week_col','" style="width:'+_O5+'px;height:'+_m2+'px;line-height:'+_m2+'px;left:','px">'],_4a='</a>',_Q9='<div class="calendar_weeks_week_col_wk" style="width:'+_O5+'px;height:'+_m2+'px;line-height:'+_m2+'px;left:0px">',_P9='</div>',_18=[],_V5,_W5,_I0=0,_q2,_08,_R3,_s2,_45;for(;_I0<6;_I0++){_V5=[];for(_q2=0;_q2<8;_q2++){_s2=new Date(_ma.getTime()+((_I0*this.msWeek)+((_q2-1)*this.msDay)));_08=_s2.getTime();if(_q2===0){_W5=[_Q9,this.week(_s2),_P9].join('');}
else{_R3=Math.round(_08/1000);if((this.value>=_R3)&&(this.value<(_R3+86400))){_45='_'+'sel';}
else{_45=(_s2<_J5||_s2>_na)?'_'+'no':'_'+'yes';}
_W5=[_44[0],_R3,_44[1],_45,_44[2],(_q2*_O5),_44[3],this.mday(_s2),_4a].join('');}
_V5.push(_W5);}
_18.push([_ca.join(_I0*_m2),_V5.join(''),_aa].join(''));}
ELEM.setHTML(this.markupElemIds.value,_18.join(''));ELEM.setHTML(this.markupElemIds.state,this.monthName(_8)+'&nbsp;'+this.year(_8));this.viewMonth=[_J5.getUTCFullYear(),_J5.getUTCMonth()];}});HCalendar.implement(HDateTime);HTimeSheet=HControl.extend({componentName:'timesheet',pxPerHour:24,itemOffsetLeft:36,itemOffsetRight:0,refresh:function(){if(this.drawn){var _Q7=this.rect.height;this.pxPerHour=(_Q7-(_Q7%48))/24;if(this.options['hideLabel']){this.setStyleOfPart('label','display','none');this.setStyleOfPart('state','left','0px');this.itemOffsetLeft=0;}
else{this.setStyleOfPart('label','height',(this.pxPerHour*24)+'px');}
this.setStyleOfPart('state','height',(this.pxPerHour*24)+'px');}
this.base();},refreshLabel:function(){var hour=1,hours=[],rowHeight=this.pxPerHour;lineHeight=Math.round(this.pxPerHour/2);for(;hour<24;hour++){hours.push('<div style="line-height:'+rowHeight+'px;height:'+rowHeight+'px;top:'+Math.round((hour*rowHeight)-lineHeight)+'px" class="timesheet_hours_row">'+hour+':00</div>');}
ELEM.setHTML(this.markupElemIds.label,hours.join(''));this.refreshState();},refreshState:function(){var line=0,lines=[],lineHeight=Math.round(this.pxPerHour/2);for(;line<48;line++){lines.push('<div style="top:'+(line*lineHeight)+'px" class="timesheet_lines_row'+(line%2)+'"></div>');}
ELEM.setHTML(this.markupElemIds.state,lines.join(''));},dragItem:false,createItem:function(origY){var _q=Math.round(this.pxPerHour/2);origY=Math.floor(origY/_q)*_q;var maxY=_q*48,lineHeight=Math.round(this.pxPerHour/2);if(origY>maxY){origY=maxY;}
var item=HTimeSheetItem.nu(this.createItemRect(origY,lineHeight),this,{label:'New Item',events:{draggable:true}});this.dragItem=item;},startDrag:function(x,y){this.createItem(y-this.pageY());EVENT.startDragging(this.dragItem);},listItemViews:false,setEditor:function(_u2){this.editor=_u2;},createItemRect:function(_d5,_q){var _b0=this.itemOffsetLeft,_F=_d5,_W=this.rect.width-this.itemOffsetRight,_C=_d5+_q;return HRect.nu(_b0,_F,_W,_C);},die:function(){this.editor.die();this.base();},refreshValue:function(){var _s=this.value,i;if(this.listItemViews===false){this.listItemViews=[];}
if(this.listItemViews.length!==0){for(i=0;i<this.listItemViews.length;i++){this.listItemViews[i].die();}
this.listItemViews=[];}
if(_s instanceof Array){var _1,_f,_r;for(i=0;i<_s.length;i++){_1=_s[i];_f=_1['label'];_r=HTimeSheetItem.nu(this.createItemRect(0,12),this,{label:_f,value:_1,events:{draggable:true}});_r.dragMode='normal';this.listItemViews.push(_r);}}}});HTimeSheetItem=HControl.extend({componentName:'timesheet_item',dragMode:'create',prevXY:[0,0],prevXYTime:0,startDrag:function(x,y){this.origY=y-this.parent.pageY();if(this.dragMode==='normal'){var _M7=new Date().getTime(),_q9=(Math.round(this.prevXY[0]/4)===Math.round(x/4)),_o9=(Math.round(this.prevXY[1]/4)===Math.round(y/4)),_g9=((_M7-this.prevXYTime)<500);if(_q9&&_o9&&_g9){if(this.parent['editor']){var _u2=this.parent.editor;_u2.setTimeSheetItem(this);_u2.bringToFront();_u2.show();}}
else{var _K7=this.rect.top-this.origY,_J7=this.rect.bottom-this.origY;if(0>=_K7&&_K7>=-3){this.dragMode='resize-top';}
else if(0<=_J7&&_J7<=4){this.dragMode='resize-bottom';}
else{this.dragMode='move';this.moveDiff=this.origY-this.rect.top;}
this.bringToFront();}}
this.prevXY=[x,y];this.prevXYTime=_M7;return true;},setTimeSheetItemLabel:function(_f){this.label=_f;this.refreshLabel();},dragCreate:function(_j){var _89=(_j<this.origY),_q=Math.floor(this.parent.pxPerHour/2),_F,_C,_z2;if(_89){var _M2=Math.floor(_j/_q)*_q,_n5=Math.ceil(this.origY/_q)*_q;if(_M2<0){_M2=0;}
_z2=_M2-_n5;if(_z2<=0-_q){_F=_M2;_C=_n5;}
else if(_z2===0){_F=_M2-_q;_C=_n5;}}
else{var _N2=Math.ceil(_j/_q)*_q,_t5=Math.floor(this.origY/_q)*_q;if(_N2>(_q*48)){_N2=_q*48;}
_z2=_N2-_t5;if(_z2>=_q){_F=_t5;_C=_N2;}
else if(_z2===0){_F=_t5;_C=_N2+_q;}}
this.rect.setTop(_F);this.rect.setBottom(_C);},dragResizeTop:function(_j){var _q=Math.floor(this.parent.pxPerHour/2),_F=Math.floor(_j/_q)*_q;if(_F<0){_F=0;}
if(_F+_q>this.rect.bottom){_F=this.rect.bottom-_q;}
this.rect.setTop(_F);},dragResizeBottom:function(_j){var _q=Math.floor(this.parent.pxPerHour/2),_C=Math.floor(_j/_q)*_q;if(_C>_q*48){_C=_q*48;}
if(_C-_q<this.rect.top){_C=this.rect.top+_q;}
this.rect.setBottom(_C);},dragMove:function(_j){var _q=Math.floor(this.parent.pxPerHour/2),_F=Math.floor((0-this.moveDiff+_j)/_q)*_q;if(_F<0){_F=0;}
if(_F+this.rect.height>_q*48){_F=_q*48-this.rect.height;}
this.rect.offsetTo(this.rect.left,_F);},drag:function(x,y){var _V8=this.parent.pageY(),_j=y-_V8;if(this.dragMode==='create'){this.dragCreate(_j);}
else if(this.dragMode==='resize-top'){this.dragResizeTop(_j);}
else if(this.dragMode==='resize-bottom'){this.dragResizeBottom(_j);}
else if(this.dragMode==='move'){this.dragMove(_j);}
this.drawRect();return true;},endDrag:function(x,y){var _M1=Math.floor(this.parent.pxPerHour),_1;if(this.dragMode==='create'){this.parent.listItemViews.push(this);_1={'timeBegin':this.rect.top/_M1,'timeEnd':this.rect.bottom/_M1,'label':this.label};if(this.parent['editor']){this.parent.editor.createItem(_1);}}
else{_1=COMM.Values.clone(this.value);_1['timeBegin']=this.rect.top/_M1;_1['timeEnd']=this.rect.bottom/_M1;if(this.parent['editor']){this.parent.editor.modifyItem(_1);}}
this.setValue(_1);this.dragMode='normal';return true;},refreshValue:function(){var _1=this.value,_M1=this.parent.pxPerHour;if((_1 instanceof Object)&&!(_1 instanceof Array)){this.setLabel(_1['label']);this.rect.setTop(_1['timeBegin']*_M1);this.rect.setBottom(_1['timeEnd']*_M1);this.drawRect();}}});HTimeSheetEditor=HControl.extend({timeSheetItem:false,createId:0,setTimeSheetItem:function(_y5){this.timeSheetItem=_y5;this.textField.setValue(_y5.label);},show:function(){if(this.timeSheetItem!==false){var _D2=HRect.nu(this.timeSheetItem.rect);if(_D2.height<40){_D2.setHeight(40);}
if(_D2.width<200){_D2.setWidth(200);}
var _u7=this.timeSheetItem.parent.rect;_D2.offsetBy(_u7.left,_u7.top);this.setRect(_D2);this.drawRect();}
this.base();},hide:function(){this.base();},origParent:null,createItem:function(_90){if(_90['id']===undefined){this.createId--;_90['id']=this.createId;}
var _1=COMM.Values.clone(this.value),_I3=_1['create'],i=0,_r=false;for(;i<_I3.length;i++){if(_I3[i]['id']===_90['id']){_r=_I3[i];break;}}
if(!_r){_I3.push(_90);}
else{for(var _7 in _90){_r[_7]=_90[_7];}}
this.setValue(_1);},modifyItem:function(_90){if(_90['id']<0){this.createItem(_90);}
else{var _1=COMM.Values.clone(this.value),_g4=_1['modify'],i=0,_r=false;for(;i<_g4.length;i++){if(_g4[i]['id']===_90['id']){_r=_g4[i];break;}}
if(!_r){_g4.push(_90);}
else{for(var _7 in _90){_r[_7]=_90[_7];}}
this.setValue(_1);}},deleteItem:function(_m5){var _1=COMM.Values.clone(this.value);if(_1['delete'].indexOf(_m5)===-1){_1['delete'].push(_m5);this.setValue(_1);}},refreshValue:function(){var _1=COMM.Values.clone(this.value),i=0,_h=this.origParent?this.origParent:this.parent,_k7=_h.listItemViews,_j7=_1['response'],_r,_e5,_O2,j,k;for(;i<_j7.length;i++){for(j=0;j<_k7.length;j++){_O2=_j7[i];_r=_k7[j];if(_r.value['id']===_O2['id']){_e5=COMM.Values.clone(_r.value);if(_O2['modify']!==undefined){for(k in _O2['modify']){_e5[k]=_O2['modify'][k];}
_r.setValue(_e5);}}}}
_1['response']=[];this.setValue(_1);},drawSubviews:function(){this.origParent=this.parent;this.remove();this.origParent.parent.addView(this);ELEM.append(this.elemId,this.parent.elemId);this.textField=HTextArea.nu([0,0,null,20,0,26],this,{value:''});this.delButton=HButton.extend({click:function(){this.parent.hide();var _U3=this.parent.timeSheetItem;if(_U3!==false){this.parent.deleteItem(_U3.value['id']);_U3.die();var _h=this.parent.origParent?this.parent.origParent:this.parent.parent;var _s9=_h.listItemViews.indexOf(_U3);_h.listItemViews.splice(_s9,1);this.parent.timeSheetItem=false;}}}).nu([2,null,60,24,null,0],this,{label:'Delete',events:{click:true}});this.okButton=HButton.extend({click:function(){this.parent.hide();if(this.parent.timeSheetItem!==false){var _f=this.parent.textField.getTextFieldValue(),_2=this.parent.timeSheetItem.value['id'],_s=this.parent.timeSheetItem.value;_s['label']=_f;this.parent.modifyItem(_s);this.parent.timeSheetItem.setTimeSheetItemLabel(_f);this.parent.timeSheetItem=false;}}}).nu([null,null,60,24,2,0],this,{label:'Save',events:{click:true}});this.cancelButton=HButton.extend({click:function(){this.parent.hide();if(this.timeSheetItem!==false){this.parent.timeSheetItem=false;}}}).nu([null,null,60,24,66,0],this,{label:'Cancel',events:{click:true}});this.textField.setStyle('text-align','center');this.textField.setStyle('line-height','12px');this.textField.setStyle('font-size','12px');this.textField.setStyle('font-family','Arial, sans-serif');this.origParent.setEditor(this);}});