
HDateTime=HClass.extend({msWeek:604800000,msDay:86400000,msHour:3600000,msMinute:60000,months_localized:['January','February','March','April','May','June','July','August','September','October','November','December'],monthName:function(_8){_8=(_8 instanceof Date)?_8:this.date();return this.months_localized[_8.getUTCMonth()];},week:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _s8=this.firstDateOfYear(_8),_73=this.firstDateOfWeek(_s8);if(_73.getUTCDate()<=28){_73=new Date(_73.getTime()+this.msWeek-this.tzMs(_73));}
var _95=Math.ceil((((_8.getTime()-_73-this.tzMs(_8))/this.msDay)+_s8.getUTCDay()+1)/7);if((_95===53)&&(this.firstDateOfWeek(this.lastDateOfYear(_8)).getUTCDate()>28)){_95=1;}
return _95;},mday:function(_8){_8=(_8 instanceof Date)?_8:this.date();return _8.getUTCDate();},month:function(_8){_8=(_8 instanceof Date)?_8:this.date();return _8.getUTCMonth();},year:function(_8){_8=(_8 instanceof Date)?_8:this.date();return _8.getUTCFullYear();},tzMs:function(_8){return _8.getTimezoneOffset()*this.msMinute;},date:function(epoch_seconds){epoch_seconds=(typeof epoch_seconds==='number')?epoch_seconds:this.value;var _8=new Date(epoch_seconds*1000);return _8;},firstDateOfYear:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(_8.getUTCFullYear(),0,1),_61=new Date(_q0.getTime()-this.tzMs(_q0));return _61;},lastDateOfYear:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(new Date(_8.getUTCFullYear()+1,0,1)-1),_61=new Date(_q0.getTime()-this.tzMs(_q0));return _61;},firstDateOfMonth:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(_8.getUTCFullYear(),_8.getUTCMonth(),1),_61=new Date(_q0.getTime()-this.tzMs(_q0));return _61;},lastDateOfMonth:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _q0=new Date(new Date(_8.getUTCFullYear(),_8.getUTCMonth()+1,1)-1),_61=new Date(_q0.getTime()-this.tzMs(_q0));return _61;},firstDateOfWeek:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _O5=_8.getUTCDay();if(_O5===0){_O5=7;}
var _ra=((_O5-1)*this.msDay),_q0=new Date(_8.getTime()-_ra),_61=new Date(_q0.getTime());return _61;},lastDateOfWeek:function(_8){var _sa=this.firstDateOfWeek(_8),_ta=new Date(_sa.getTime()+this.msWeek-this.msDay-1);return _ta;}});HCalendar=HControl.extend({componentName:'calendar',weekdays_localized:['Wk','Mon','Tue','Wed','Thu','Fri','Sat','Sun'],mouseWheel:function(_V){if(_V<0){this.nextMonth();}
else{this.prevMonth();}},refreshLabel:function(){var _N5=this.weekdays_localized,_t8=Math.floor(this.rect.width/_N5.length),_u8=[],i=0,_va=['<div style="width:'+_t8+'px;left:','px">'],_wa='</div>';for(;i<_N5.length;i++){_u8.push([_va.join(i*_t8),_N5[i],_wa].join(''));}
ELEM.setHTML(this.markupElemIds.label,_u8.join(''));},calendarDateRange:function(_8){var _xa=this.firstDateOfMonth(_8),_ya=this.lastDateOfMonth(_8),_p1=this.firstDateOfWeek(_xa),_t2=this.lastDateOfWeek(_ya),_Aa=this.week(_p1),_Ba=this.week(_t2),_K5=_Ba-_Aa;if((_K5===5)&&(_p1.getDate()!==1)){_t2=new Date(_t2.getTime()+this.msWeek);}
else if((_K5===5)&&(_p1.getDate()===1)){_p1=new Date(_p1.getTime()-this.msWeek);}
else if(_K5===4){_p1=new Date(_p1.getTime()-this.msWeek);_t2=new Date(_t2.getTime()+this.msWeek);}
return[_p1,_t2];},refreshValue:function(){var _8=this.date();this.drawCalendar(_8);},nextMonth:function(){var _8=new Date(this.viewMonth[0],this.viewMonth[1]+1,1);this.drawCalendar(new Date(_8.getTime()-this.tzMs(_8)));},prevMonth:function(){var _8=new Date(this.viewMonth[0],this.viewMonth[1]-1,1);this.drawCalendar(new Date(_8.getTime()-this.tzMs(_8)));},viewMonth:[1970,0],drawCalendar:function(_8){_8=(_8 instanceof Date)?_8:this.date();var _v8=this.calendarDateRange(_8),_Z4=this.firstDateOfMonth(_8),_Da=this.lastDateOfMonth(_8),_Ea=_v8[0],_ob=_v8[1],_Fa=this.weekdays_localized.length,_I5=Math.floor((this.rect.width-1)/_Fa),_q2=Math.floor((this.rect.height-1-35)/6),_R8=['<div class="calendar_weeks_week_row" style="width:'+(this.rect.width-3)+'px;height:'+_q2+'px;top:','px">'],_S8='</div>',_W3=['<a href="javascript:void(HSystem.views['+this.viewId+'].setValue(','));" class="calendar_weeks_week_col','" style="width:'+_I5+'px;height:'+_q2+'px;line-height:'+_q2+'px;left:','px">'],_T8='</a>',_U8='<div class="calendar_weeks_week_col_wk" style="width:'+_I5+'px;height:'+_q2+'px;line-height:'+_q2+'px;left:0px">',_V8='</div>',_w8=[],_15,_35,_G0=0,_o2,_x8,_V3,_m2,_45;for(;_G0<6;_G0++){_15=[];for(_o2=0;_o2<8;_o2++){_m2=new Date(_Ea.getTime()+((_G0*this.msWeek)+((_o2-1)*this.msDay)));_x8=_m2.getTime();if(_o2===0){_35=[_U8,this.week(_m2),_V8].join('');}
else{_V3=Math.round(_x8/1000);if((this.value>=_V3)&&(this.value<(_V3+86400))){_45='_'+'sel';}
else{_45=(_m2<_Z4||_m2>_Da)?'_'+'no':'_'+'yes';}
_35=[_W3[0],_V3,_W3[1],_45,_W3[2],(_o2*_I5),_W3[3],this.mday(_m2),_T8].join('');}
_15.push(_35);}
_w8.push([_R8.join(_G0*_q2),_15.join(''),_S8].join(''));}
ELEM.setHTML(this.markupElemIds.value,_w8.join(''));ELEM.setHTML(this.markupElemIds.state,this.monthName(_8)+'&nbsp;'+this.year(_8));this.viewMonth=[_Z4.getUTCFullYear(),_Z4.getUTCMonth()];}});HCalendar.implement(HDateTime);HTimeSheet=HControl.extend({componentName:'timesheet',pxPerHour:24,itemOffsetLeft:36,itemOffsetRight:0,refresh:function(){if(this.drawn){var _y8=this.rect.height;this.pxPerHour=(_y8-(_y8%48))/24;if(this.options['hideLabel']){this.setStyleOfPart('label','display','none');this.setStyleOfPart('state','left','0px');this.itemOffsetLeft=0;}
else{this.setStyleOfPart('label','height',(this.pxPerHour*24)+'px');}
this.setStyleOfPart('state','height',(this.pxPerHour*24)+'px');}
this.base();},refreshLabel:function(){var hour=1,hours=[],rowHeight=this.pxPerHour;lineHeight=Math.round(this.pxPerHour/2);for(;hour<24;hour++){hours.push('<div style="line-height:'+rowHeight+'px;height:'+rowHeight+'px;top:'+Math.round((hour*rowHeight)-lineHeight)+'px" class="timesheet_hours_row">'+hour+':00</div>');}
ELEM.setHTML(this.markupElemIds.label,hours.join(''));this.refreshState();},refreshState:function(){var line=0,lines=[],lineHeight=Math.round(this.pxPerHour/2);for(;line<48;line++){lines.push('<div style="top:'+(line*lineHeight)+'px" class="timesheet_lines_row'+(line%2)+'"></div>');}
ELEM.setHTML(this.markupElemIds.state,lines.join(''));},dragItem:false,createItem:function(origY){var _r=Math.round(this.pxPerHour/2);origY=Math.floor(origY/_r)*_r;var maxY=_r*48,lineHeight=Math.round(this.pxPerHour/2);if(origY>maxY){origY=maxY;}
var item=HTimeSheetItem.nu(this.createItemRect(origY,lineHeight),this,{label:'New Item',events:{draggable:true}});this.dragItem=item;},startDrag:function(x,y){this.createItem(y-this.pageY());EVENT.startDragging(this.dragItem);},listItemViews:false,setEditor:function(_G2){this.editor=_G2;},createItemRect:function(_h5,_r){var _b0=this.itemOffsetLeft,_F=_h5,_Y=this.rect.width-this.itemOffsetRight,_A=_h5+_r;return HRect.nu(_b0,_F,_Y,_A);},die:function(){this.editor.die();this.base();},refreshValue:function(){var _s=this.value,i;if(this.listItemViews===false){this.listItemViews=[];}
if(this.listItemViews.length!==0){for(i=0;i<this.listItemViews.length;i++){this.listItemViews[i].die();}
this.listItemViews=[];}
if(_s instanceof Array){var _1,_f,_q;for(i=0;i<_s.length;i++){_1=_s[i];_f=_1['label'];_q=HTimeSheetItem.nu(this.createItemRect(0,12),this,{label:_f,value:_1,events:{draggable:true}});_q.dragMode='normal';this.listItemViews.push(_q);}}}});HTimeSheetItem=HControl.extend({componentName:'timesheet_item',dragMode:'create',prevXY:[0,0],prevXYTime:0,startDrag:function(x,y){this.origY=y-this.parent.pageY();if(this.dragMode==='normal'){var _z8=new Date().getTime(),_39=(Math.round(this.prevXY[0]/4)===Math.round(x/4)),_49=(Math.round(this.prevXY[1]/4)===Math.round(y/4)),_59=((_z8-this.prevXYTime)<500);if(_39&&_49&&_59){if(this.parent['editor']){var _G2=this.parent.editor;_G2.setTimeSheetItem(this);_G2.bringToFront();_G2.show();}}
else{var _A8=this.rect.top-this.origY,_B8=this.rect.bottom-this.origY;if(0>=_A8&&_A8>=-3){this.dragMode='resize-top';}
else if(0<=_B8&&_B8<=4){this.dragMode='resize-bottom';}
else{this.dragMode='move';this.moveDiff=this.origY-this.rect.top;}
this.bringToFront();}}
this.prevXY=[x,y];this.prevXYTime=_z8;return true;},setTimeSheetItemLabel:function(_f){this.label=_f;this.refreshLabel();},dragCreate:function(_j){var _69=(_j<this.origY),_r=Math.floor(this.parent.pxPerHour/2),_F,_A,_D2;if(_69){var _h3=Math.floor(_j/_r)*_r,_r5=Math.ceil(this.origY/_r)*_r;if(_h3<0){_h3=0;}
_D2=_h3-_r5;if(_D2<=0-_r){_F=_h3;_A=_r5;}
else if(_D2===0){_F=_h3-_r;_A=_r5;}}
else{var _e3=Math.ceil(_j/_r)*_r,_w5=Math.floor(this.origY/_r)*_r;if(_e3>(_r*48)){_e3=_r*48;}
_D2=_e3-_w5;if(_D2>=_r){_F=_w5;_A=_e3;}
else if(_D2===0){_F=_w5;_A=_e3+_r;}}
this.rect.setTop(_F);this.rect.setBottom(_A);},dragResizeTop:function(_j){var _r=Math.floor(this.parent.pxPerHour/2),_F=Math.floor(_j/_r)*_r;if(_F<0){_F=0;}
if(_F+_r>this.rect.bottom){_F=this.rect.bottom-_r;}
this.rect.setTop(_F);},dragResizeBottom:function(_j){var _r=Math.floor(this.parent.pxPerHour/2),_A=Math.floor(_j/_r)*_r;if(_A>_r*48){_A=_r*48;}
if(_A-_r<this.rect.top){_A=this.rect.top+_r;}
this.rect.setBottom(_A);},dragMove:function(_j){var _r=Math.floor(this.parent.pxPerHour/2),_F=Math.floor((0-this.moveDiff+_j)/_r)*_r;if(_F<0){_F=0;}
if(_F+this.rect.height>_r*48){_F=_r*48-this.rect.height;}
this.rect.offsetTo(this.rect.left,_F);},drag:function(x,y){var _99=this.parent.pageY(),_j=y-_99;if(this.dragMode==='create'){this.dragCreate(_j);}
else if(this.dragMode==='resize-top'){this.dragResizeTop(_j);}
else if(this.dragMode==='resize-bottom'){this.dragResizeBottom(_j);}
else if(this.dragMode==='move'){this.dragMove(_j);}
this.drawRect();return true;},endDrag:function(x,y){var _32=Math.floor(this.parent.pxPerHour),_1;if(this.dragMode==='create'){this.parent.listItemViews.push(this);_1={'timeBegin':this.rect.top/_32,'timeEnd':this.rect.bottom/_32,'label':this.label};if(this.parent['editor']){this.parent.editor.createItem(_1);}}
else{_1=COMM.Values.clone(this.value);_1['timeBegin']=this.rect.top/_32;_1['timeEnd']=this.rect.bottom/_32;if(this.parent['editor']){this.parent.editor.modifyItem(_1);}}
this.setValue(_1);this.dragMode='normal';return true;},refreshValue:function(){var _1=this.value,_32=this.parent.pxPerHour;if((_1 instanceof Object)&&!(_1 instanceof Array)){this.setLabel(_1['label']);this.rect.setTop(_1['timeBegin']*_32);this.rect.setBottom(_1['timeEnd']*_32);this.drawRect();}}});HTimeSheetEditor=HControl.extend({timeSheetItem:false,createId:0,setTimeSheetItem:function(_A5){this.timeSheetItem=_A5;this.textField.setValue(_A5.label);},show:function(){if(this.timeSheetItem!==false){var _x2=HRect.nu(this.timeSheetItem.rect);if(_x2.height<40){_x2.setHeight(40);}
if(_x2.width<200){_x2.setWidth(200);}
var _C8=this.timeSheetItem.parent.rect;_x2.offsetBy(_C8.left,_C8.top);this.setRect(_x2);this.drawRect();}
this.base();},hide:function(){this.base();},origParent:null,createItem:function(_90){if(_90['id']===undefined){this.createId--;_90['id']=this.createId;}
var _1=COMM.Values.clone(this.value),_L3=_1['create'],i=0,_q=false;for(;i<_L3.length;i++){if(_L3[i]['id']===_90['id']){_q=_L3[i];break;}}
if(!_q){_L3.push(_90);}
else{for(var _7 in _90){_q[_7]=_90[_7];}}
this.setValue(_1);},modifyItem:function(_90){if(_90['id']<0){this.createItem(_90);}
else{var _1=COMM.Values.clone(this.value),_K3=_1['modify'],i=0,_q=false;for(;i<_K3.length;i++){if(_K3[i]['id']===_90['id']){_q=_K3[i];break;}}
if(!_q){_K3.push(_90);}
else{for(var _7 in _90){_q[_7]=_90[_7];}}
this.setValue(_1);}},deleteItem:function(_G5){var _1=COMM.Values.clone(this.value);if(_1['delete'].indexOf(_G5)===-1){_1['delete'].push(_G5);this.setValue(_1);}},refreshValue:function(){var _1=COMM.Values.clone(this.value),i=0,_h=this.origParent?this.origParent:this.parent,_D8=_h.listItemViews,_E8=_1['response'],_q,_65,_n3,j,k;for(;i<_E8.length;i++){for(j=0;j<_D8.length;j++){_n3=_E8[i];_q=_D8[j];if(_q.value['id']===_n3['id']){_65=COMM.Values.clone(_q.value);if(_n3['modify']!==undefined){for(k in _n3['modify']){_65[k]=_n3['modify'][k];}
_q.setValue(_65);}}}}
_1['response']=[];this.setValue(_1);},drawSubviews:function(){this.origParent=this.parent;this.remove();this.origParent.parent.addView(this);ELEM.append(this.elemId,this.parent.elemId);this.textField=HTextArea.nu([0,0,null,20,0,26],this,{value:''});this.delButton=HButton.extend({click:function(){this.parent.hide();var _H3=this.parent.timeSheetItem;if(_H3!==false){this.parent.deleteItem(_H3.value['id']);_H3.die();var _h=this.parent.origParent?this.parent.origParent:this.parent.parent;var _h9=_h.listItemViews.indexOf(_H3);_h.listItemViews.splice(_h9,1);this.parent.timeSheetItem=false;}}}).nu([2,null,60,24,null,0],this,{label:'Delete',events:{click:true}});this.okButton=HButton.extend({click:function(){this.parent.hide();if(this.parent.timeSheetItem!==false){var _f=this.parent.textField.getTextFieldValue(),_2=this.parent.timeSheetItem.value['id'],_s=this.parent.timeSheetItem.value;_s['label']=_f;this.parent.modifyItem(_s);this.parent.timeSheetItem.setTimeSheetItemLabel(_f);this.parent.timeSheetItem=false;}}}).nu([null,null,60,24,2,0],this,{label:'Save',events:{click:true}});this.cancelButton=HButton.extend({click:function(){this.parent.hide();if(this.timeSheetItem!==false){this.parent.timeSheetItem=false;}}}).nu([null,null,60,24,66,0],this,{label:'Cancel',events:{click:true}});this.textField.setStyle('text-align','center');this.textField.setStyle('line-height','12px');this.textField.setStyle('font-size','12px');this.textField.setStyle('font-family','Arial, sans-serif');this.origParent.setEditor(this);}});