
HListItems=HValueResponder.extend({constructor:function(_3,_h,_4){this.parent=_h;if(_4 instanceof Object){if(_4['valueObj']!==undefined){_4.valueObj.bind(this);}}},_o8:function(_da){console.log("Warning; HListItems: "+_da);},refresh:function(){if(this.value instanceof Array){var _50=[],_G0,_f,_1,i=0;for(;i<this.value.length;i++){_G0=this.value[i];if(_G0 instanceof Object){_f=_G0['label'];_1=_G0['value'];if(_f===undefined||_1===undefined){this._o8("The value or label of row "+_G0+" is undefined (ignored)");}
_50.push([_1,_f]);}
else{this._o8("The row "+_G0+" is not an object (ignored)");}}
this.parent.setListItems(_50);}}});HCheckboxList=HControl.extend({drawSubviews:function(){this.setStyle('border','1px solid #999');this.setStyle('overflow','auto');},listItems:[],listItemViews:[],ListCheckbox:HCheckbox.extend({refreshValue:function(){this.base();if(this.value===true){this.parent.addItem(this.options.listValue);}
else{this.parent.delItem(this.options.listValue);}}}),addItem:function(_D1){if(this.value.indexOf(_D1)===-1){var _w2=[],i=0;for(;i<this.value.length;i++){_w2.push(this.value[i]);}
_w2.push(_D1);this.setValue(_w2);}},delItem:function(_D1){var _ga=this.value.indexOf(_D1);if(_ga!==-1){var _w2=[],i=0;for(;i<this.value.length;i++){if(this.value[i]!==_D1){_w2.push(this.value[i]);}}
this.setValue(_w2);}},setListItems:function(_50){var _N1,_1,_f,_p8,_q8,i=0;for(;i<this.listItemViews.length;i++){try{this.listItemViews[i].die();}
catch(e){console.log('HCheckboxList, setListItems item destruction error: ',e);}}
this.listItems=_50;this.listItemViews=[];for(i=0;i<_50.length;i++){_N1=_50[i];_1=_N1[0];_f=_N1[1];_p8=(this.value.indexOf(_1)!==-1);_q8=this.ListCheckbox.nu([4,(i*23)+4,null,23,4,null],this,{label:_f,value:_p8,listValue:_1});this.listItemViews[i]=_q8;}
this.refreshValue();},die:function(){this.listItems=null;this.listItemViews=null;this.base();},refreshValue:function(){if(this.listItemViews.length===0){return this;}
var _1=this.value,_50=this.listItems,_y5,_ja=[],i=0,_u5;for(;i<_50.length;i++){_y5=_50[i][0];_u5=(_1.indexOf(_y5)!==-1);this.listItemViews[i].setValue(_u5);if(_u5){_ja.push(_y5);}}
return this;}});HRadiobuttonList=HControl.extend({drawSubviews:function(){this.setStyle('border','1px solid #999');this.setStyle('overflow-y','auto');},listItems:[],listItemViews:[],setListItems:function(_50){var _N1,_1,_f,_r8,i=0;for(;i<this.listItemViews.length;i++){try{this.listItemViews[i].die();}
catch(e){console.log('HRadiobuttonList, setListItems item destruction error: ',e);}}
this.listItems=_50;this.listItemViews=[];for(i=0;i<_50.length;i++){_N1=_50[i];_1=_N1[0];_f=_N1[1];_r8=HRadiobutton.nu([4,(i*23)+4,null,23,4,null],this,{label:_f});this.listItemViews[i]=_r8;}
this.refreshValue();},die:function(){this.listItems=null;this.listItemViews=null;this.radioButtonIndexValue.die();this.base();},radioButtonIndexValue:false,radioButtonResponder:false,RadioButtonIndexResponder:HValueResponder.extend({constructor:function(_h,_41){this.parent=_h;},refresh:function(){var _50=this.parent.listItems;if(_50[this.value]!==undefined){this.parent.setValue(_50[this.value][0]);}}}),refreshValue:function(){var _1=this.value;if(this.listItems.length!==0&&this['valueMatrix']!==undefined){if(this.radioButtonResponder===false){this.radioButtonIndexValue=HValue.nu(false,0);this.radioButtonIndexValue.bind(this.valueMatrix);this.radioButtonResponder=this.RadioButtonIndexResponder.nu(this);this.radioButtonIndexValue.bind(this.radioButtonResponder);}
for(var i=0;i<this.listItems.length;i++){if(this.listItems[i][0]===_1){this.radioButtonResponder.setValue(-1);this.radioButtonResponder.setValue(i);break;}}}}});