
HListItems=HValueResponder.extend({constructor:function(_3,_h,_4){this.parent=_h;if(_4 instanceof Object){if(_4['valueObj']!==undefined){_4.valueObj.bind(this);}}},_26:function(_W8){console.log("Warning; HListItems: "+_W8);},refresh:function(){if(this.value instanceof Array){var _40=[],_I0,_f,_1,i=0;for(;i<this.value.length;i++){_I0=this.value[i];if(_I0 instanceof Object){_f=_I0['label'];_1=_I0['value'];if(_f===undefined||_1===undefined){this._26("The value or label of row "+_I0+" is undefined (ignored)");}
_40.push([_1,_f]);}
else{this._26("The row "+_I0+" is not an object (ignored)");}}
this.parent.setListItems(_40);}}});HCheckboxList=HControl.extend({drawSubviews:function(){this.setStyle('border','1px solid #999');this.setStyle('overflow','auto');},listItems:[],listItemViews:[],ListCheckbox:HCheckbox.extend({refreshValue:function(){this.base();if(this.value===true){this.parent.addItem(this.options.listValue);}
else{this.parent.delItem(this.options.listValue);}}}),addItem:function(_E1){if(this.value.indexOf(_E1)===-1){var _o2=[],i=0;for(;i<this.value.length;i++){_o2.push(this.value[i]);}
_o2.push(_E1);this.setValue(_o2);}},delItem:function(_E1){var _N8=this.value.indexOf(_E1);if(_N8!==-1){var _o2=[],i=0;for(;i<this.value.length;i++){if(this.value[i]!==_E1){_o2.push(this.value[i]);}}
this.setValue(_o2);}},setListItems:function(_40){var _22,_1,_f,_F8,_E8,i=0;for(;i<this.listItemViews.length;i++){try{this.listItemViews[i].die();}
catch(e){console.log('HCheckboxList, setListItems item destruction error: ',e);}}
this.listItems=_40;this.listItemViews=[];for(i=0;i<_40.length;i++){_22=_40[i];_1=_22[0];_f=_22[1];_F8=(this.value.indexOf(_1)!==-1);_E8=this.ListCheckbox.nu([4,(i*23)+4,null,23,4,null],this,{label:_f,value:_F8,listValue:_1});this.listItemViews[i]=_E8;}
this.refreshValue();},die:function(){this.listItems=null;this.listItemViews=null;this.base();},refreshValue:function(){if(this.listItemViews.length===0){return this;}
var _1=this.value,_40=this.listItems,_15,_d9=[],i=0,_g5;for(;i<_40.length;i++){_15=_40[i][0];_g5=(_1.indexOf(_15)!==-1);this.listItemViews[i].setValue(_g5);if(_g5){_d9.push(_15);}}
return this;}});HRadiobuttonList=HControl.extend({drawSubviews:function(){this.setStyle('border','1px solid #999');this.setStyle('overflow-y','auto');},listItems:[],listItemViews:[],setListItems:function(_40){var _22,_1,_f,_A8,i=0;for(;i<this.listItemViews.length;i++){try{this.listItemViews[i].die();}
catch(e){console.log('HRadiobuttonList, setListItems item destruction error: ',e);}}
this.listItems=_40;this.listItemViews=[];for(i=0;i<_40.length;i++){_22=_40[i];_1=_22[0];_f=_22[1];_A8=HRadiobutton.nu([4,(i*23)+4,null,23,4,null],this,{label:_f});this.listItemViews[i]=_A8;}
this.refreshValue();},die:function(){this.listItems=null;this.listItemViews=null;this.radioButtonIndexValue.die();this.base();},radioButtonIndexValue:false,radioButtonResponder:false,RadioButtonIndexResponder:HValueResponder.extend({constructor:function(_h,_i1){this.parent=_h;},refresh:function(){var _40=this.parent.listItems;if(_40[this.value]!==undefined){this.parent.setValue(_40[this.value][0]);}}}),refreshValue:function(){var _1=this.value;if(this.listItems.length!==0&&this['valueMatrix']!==undefined){if(this.radioButtonResponder===false){this.radioButtonIndexValue=HValue.nu(false,0);this.radioButtonIndexValue.bind(this.valueMatrix);this.radioButtonResponder=this.RadioButtonIndexResponder.nu(this);this.radioButtonIndexValue.bind(this.radioButtonResponder);}
for(var i=0;i<this.listItems.length;i++){if(this.listItems[i][0]===_1){this.radioButtonResponder.setValue(-1);this.radioButtonResponder.setValue(i);break;}}}}});