
HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _1H=this.drawn;this.base();if(!_1H){var i=0,_3t=[['overflow','auto']];for(i;i<_3t.length;i++){this.setStyle(_3t[i][0],_3t[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_1,_u,_2){this.tabInit();if(this.isinherited){this.base(_1,_u,_2);}
else{this.isinherited=true;this.base(_1,_u,_2);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_4){this.base(_4);if(typeof _4=='number'){var _E=parseInt(_4,10);if(_E<this.tabs.length){if(_E!=this.selectIdx){this.selectTab(_E);}}}},stringWidth:function(_1e,_a){var _1F='<span style="'+this.fontStyle+'">'+_1e+'</span>',_p=this.base(_1F,null,_a);return _p;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Trebuchet MS,Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_w){this.label=_w;},selectTab:function(_r){if(_r instanceof HTabView){_r=_r.tabIndex;}
if(this.selectIdx!=-1){var _53=this.tabLabels[this.selectIdx],_6Y=this.tabs[this.selectIdx];ELEM.removeClassName(_53,'item-fg');ELEM.addClassName(_53,'item-bg');HSystem.views[_6Y].hide();}
if(_r!=-1){var _04=this.tabLabels[_r],_3u=this.tabs[_r];ELEM.removeClassName(_04,'item-bg');ELEM.addClassName(_04,'item-fg');HSystem.views[_3u].show();}
this.selectIdx=_r;this.setValue(_r);},addTab:function(_2z,_7v){var _r=this.tabs.length,_52='',_6h=this.stringWidth(_2z,0),_3a=_6h+this.tabLabelLeftEdge+this.tabLabelRightEdge,_1g=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_r=this.tabs.length,_04=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);if(this.tabLabelNoHTMLPrefix){_52=_2z;}
else{_52=this.tabLabelHTMLPrefix1+_6h+this.tabLabelHTMLPrefix2+_2z+this.tabLabelHTMLSuffix;}
_1g.hide();ELEM.addClassName(_04,'item-bg');ELEM.setStyle(_04,'width',_3a+'px');ELEM.setStyle(_04,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_04,_52);this.tabLabelStrings.push(_2z);if(this.tabTriggerLink&&this.tabLabelElementTagName=='a'){ELEM.setAttr(_04,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_r+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_04,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_r+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_3a]);}
this.rightmostPx+=_3a;if(this.tabLabelAlign=='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
this.tabs.push(_1g.viewId);this.tabLabels.push(_04);_1g.tabIndex=_r;if(_7v){this.selectTab(_r);}
return _1g;},mouseDown:function(_5,_8){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_5-=this.pageX();_8-=this.pageY();if(_5<=this.rightmostPx){if(_8<=this.tabLabelHeight){var i=0,_4k;for(i;i<this.tabLabelBounds.length;i++){_4k=this.tabLabelBounds[i];if(_5<_4k[1]&&_5>=_4k[0]){this.selectTab(i);return;}}}}},removeTab:function(_r){var _6I=this.selectIdx,_3u=this.tabs[_r],_04=this.tabViews[_r];this.tabs.splice(_r,1);this.tabLabels.splice(_r,1);this.tabLabelBounds.splice(_r,1);this.tabLabelStrings.splice(_r,1);if(_r==_6I){this.selectIdx=-1;if(_r==0&&this.tabs.length==0){this.selectTab(-1);}
else if(_r==(this.tabs.length-1)){this.selectTab(_r-1);}
else{this.selectTab(_r);}}
else if(_r<_6I){this.selectIdx--;}
ELEM.del(_04);HSystem.views[_3u].die();},draw:function(){var _1H=this.drawn;this.base();if(!_1H){this.drawMarkup();}
this.refresh();}});