
HWindowBar=HButton.extend({packageName:"window",componentName:"windowbar",constructor:function(_1,_c,_2){if(!_2){_2={};}
if(!_2.events){_2.events={};}
if(!_2.events.draggable){_2.events.draggable=true;}
if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HWindowBar]';if(!this.isinherited){this.draw();}},setLabel:function(_w){this.label=_w;if(this.parent.windowLabel){this.parent.windowLabel.setLabel(_w);}},startDrag:function(_5,_8){this.parent.startDrag(_5,_8);},doDrag:function(_5,_8){this.parent.doDrag(_5,_8);},endDrag:function(_5,_8){this.parent.endDrag(_5,_8);}});HWindowLabel=HButton.extend({packageName:"window",componentName:"windowlabel",constructor:function(_1,_c,_2){if(!_2){_2={};}
if(!_2.events){_2.events={};}
if(!_2.events.draggable){_2.events.draggable=true;}
if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HWindowLabel]';if(!this.isinherited){this.draw();}},gainedActiveStatus:function(_2g){EVENT.changeActiveControl(this.parent.parent);},startDrag:function(_5,_8){this.parent.parent.startDrag(_5,_8);},doDrag:function(_5,_8){this.parent.parent.doDrag(_5,_8);},endDrag:function(_5,_8){this.parent.parent.endDrag(_5,_8);}});HWindowView=HView.extend({packageName:"window",flexTop:true,flexLeft:true,flexRight:true,flexBottom:true,flexTopOffset:24,flexLeftOffset:4,flexRightOffset:4,flexBottomOffset:4,constructor:function(_1,_c){if(this.isinherited){this.base(_1,_c);}
else{this.isinherited=true;this.base(_1,_c);this.isinherited=false;}
this.type='[HWindowView]';this.preserveTheme=true;if(!this.isinherited){this.draw();}},draw:function(){if(!this.drawn){ELEM.setCSS(this.elemId,'position:absolute;border:1px solid #ccc;border-top: 0;background-color: #f7f7f7;overflow:auto;');}
this.drawRect();}},{_58:"windowview"});HWindowControl=HControl.extend({packageName:"window",componentName:"windowcontrol",constructor:function(_1,_c,_2){if(!_2){_2={};}
var _s=Base.extend({minSize:[64,32],maxSize:[4096,3072],barHeight:21,resizeW:4,resizeE:4,resizeN:4,resizeS:4,resizeNW:[4,4],resizeNE:[4,4],resizeSW:[4,4],resizeSE:[16,16],menuBar:null});_2=new(_s.extend(_2))();if(this.isinherited){this.base(_1,_c,_2);}
else{this.isinherited=true;this.base(_1,_c,_2);this.isinherited=false;}
this.type='[HWindowControl]';this.preserveTheme=true;this._3r();this.setDraggable(true);this.drawRect();this.drawMarkup();this.buildWinParts();this.setLabel(this.label);if(_2.menuBar){this.setMenuBar(_2.menuBar);}
if(!this.isinherited){this.draw();}},buildWinParts:function(){this.calcWindowPartRects();this.windowBar=new HWindowBar(this._g.windowBarRect,this,{label:this.label});this.windowBar.draw();this.windowLabel=new HWindowLabel(this._g.windowLabelRect,this.windowBar,{label:this.label});this.windowLabel.draw();this.windowView=new HWindowView(this._g.windowViewRect,this);this.windowView.draw();},_3r:function(){this._g={dragWindow:false,resizeW:false,resizeE:false,resizeN:false,resizeS:false,resizeNW:false,resizeNE:false,resizeSW:false,resizeSE:false,dragWindowRect:new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN),resizeNRect:new HRect(this.options.resizeW,0,this.rect.width-this.options.resizeE,this.options.resizeN),resizeSRect:new HRect(this.options.resizeW,this.rect.height-this.options.resizeS,this.rect.width-this.options.resizeE,this.rect.height),resizeWRect:new HRect(0,this.options.resizeN,this.options.resizeW,this.rect.height-this.options.resizeS),resizeERect:new HRect(this.rect.width-this.options.resizeE,this.options.resizeN,this.rect.width,this.rect.height-this.options.resizeS),resizeNWRect:new HRect(0,0,this.options.resizeNW[0],this.options.resizeNW[1]),resizeNERect:new HRect(this.rect.width-this.options.resizeNE[0],0,this.rect.width,this.options.resizeNE[1]),resizeSWRect:new HRect(0,this.rect.height-this.options.resizeSW[1],this.options.resizeSW[0],this.rect.height),resizeSERect:new HRect(this.rect.width-this.options.resizeSE[0],this.rect.height-this.options.resizeSE[1],this.rect.width,this.rect.height)};},checkWindowSizeConstrains:function(){var _4P=this._g.resizeW||this._g.resizeSW||this._g.resizeNW;var _4O=this._g.resizeN||this._g.resizeNE||this._g.resizeNW;if(this.rect.width<this.options.minSize[0]){if(_4P){this.rect.left=this.rect.right-this.options.minSize[0];}
this.rect.setWidth(this.options.minSize[0]);}else if(this.rect.width>this.options.maxSize[0]){if(_4P){this.rect.left=this.rect.right-this.options.maxSize[0];}
this.rect.setWidth(this.options.maxSize[0]);}
if(this.rect.height<this.options.minSize[1]){if(_4O){this.rect.top=this.rect.bottom-this.options.minSize[1];}
this.rect.setHeight(this.options.minSize[1]);}else if(this.rect.height>this.options.maxSize[1]){if(_4O){this.rect.top=this.rect.bottom-this.options.maxSize[1];}
this.rect.setHeight(this.options.maxSize[1]);}
var _3b=0-this.options.resizeW;if(this.rect.left<_3b){this.rect.left=_3b;this.rect.right=this.rect.width+_3b;}
var _3x=0-this.options.resizeN;if(this.rect.top<_3x){this.rect.top=_3x;this.rect.bottom=this.rect.height+_3x;}},startDrag:function(_5,_8){this._0E=new HPoint(_5,_8);this._2w=new HPoint(_5,_8);this._1Q=new HRect(this.rect);this._3r();var _0i=this._0E.subtract(this._1Q.leftTop);if(this._g.resizeNWRect.contains(_0i)){this._z=_0i;this._g.resizeNW=true;}else if(this._g.resizeNERect.contains(_0i)){this._z=this._0E.subtract(this._1Q.rightTop);this._g.resizeNE=true;}else if(this._g.resizeSWRect.contains(_0i)){this._z=this._0E.subtract(this._1Q.leftBottom);this._g.resizeSW=true;}else if(this._g.resizeSERect.contains(_0i)){this._z=this._0E.subtract(this._1Q.rightBottom);this._g.resizeSE=true;}else if(this._g.resizeNRect.contains(_0i)){this._z=_8-this.rect.top;this._g.resizeN=true;}else if(this._g.resizeSRect.contains(_0i)){this._z=_8-this.rect.bottom;this._g.resizeS=true;}else if(this._g.resizeWRect.contains(_0i)){this._z=_5-this.rect.left;this._g.resizeW=true;}else if(this._g.resizeERect.contains(_0i)){this._z=_5-this.rect.right;this._g.resizeE=true;}else if(this._g.dragWindowRect.contains(_0i)){this._z=this._0E.subtract(this._1Q.leftTop);this._g.dragWindow=true;}
this.bringToFront();this.doDrag(_5,_8);},doDrag:function(_5,_8){var _n;var _0N=new HPoint(_5,_8);if(!this._2w.equals(_0N)){if(this._g.resizeNW==true){_n=_0N.subtract(this._z);this.rect.setLeftTop(_n);}else if(this._g.resizeNE==true){_n=_0N.subtract(this._z);this.rect.setRightTop(_n);}else if(this._g.resizeSW==true){_n=_0N.subtract(this._z);this.rect.setLeftBottom(_n);}else if(this._g.resizeSE==true){_n=_0N.subtract(this._z);this.rect.setRightBottom(_n);}else if(this._g.resizeN==true){_n=_8-this._z;this.rect.top=_n;this.rect.updateSecondaryValues();}else if(this._g.resizeS==true){_n=_8-this._z;this.rect.bottom=_n;this.rect.updateSecondaryValues();}else if(this._g.resizeW==true){_n=_5-this._z;this.rect.left=_n;this.rect.updateSecondaryValues();}else if(this._g.resizeE==true){_n=_5-this._z;this.rect.right=_n;this.rect.updateSecondaryValues();}else if(this._g.dragWindow==true){_n=_0N.subtract(this._z);this.rect.offsetTo(_n);}
this.checkWindowSizeConstrains();this.setStyle('left',this.rect.left+'px',true);this.setStyle('top',this.rect.top+'px',true);this.setStyle('width',this.rect.width+'px',true);this.setStyle('height',this.rect.height+'px',true);if(this._g.dragWindow==false){this.calcWindowPartRects();}
this._2w=_0N;}},endDrag:function(_5,_8){this.doDrag(_5,_8);},calcWindowPartRects:function(){var _2E=new HRect(this.options.resizeW,this.options.resizeN,this.rect.width-this.options.resizeE,this.options.barHeight+this.options.resizeN);var _5g=new HRect(0,0,_2E.width,_2E.height);var _1X=new HRect(this.options.resizeW,this.options.resizeN+this.options.barHeight,this.rect.width-this.options.resizeE,this.rect.height-this.options.resizeS);if(this.menuBar){var _2m=this.options.menuBarHeight;if(_2m+this.options.resizeN+this.options.barHeight>this.rect.height-this.options.resizeS){_2m=this.rect.height-this.options.barHeight-
this.options.resizeS-this.options.resizeN;}
_1X.setTop(_1X.top+_2m);this.menuBar.resizeTo(_1X.width,_2m);}
if(!this._g.windowBarRect){this._g.windowBarRect=_2E;this._g.windowLabelRect=_5g;this._g.windowViewRect=_1X;}else{this.windowBar.setRect(_2E);this.windowLabel.setRect(_5g);this.windowView.setRect(_1X);}},draw:function(){this.drawRect();},setLabel:function(_w){if(this.drawn&&this.windowLabel){this.windowLabel.setLabel(_w);}
this.base(_w);},refresh:function(){if(this.windowBar){this.windowBar.refresh();}
this.drawRect();},setMenuBar:function(_2l){if(_2l==this.menuBar){return;}
if(this.menuBar){this.menuBar.die();}
this.menuBar=_2l;if(_2l){this.options.menuBarHeight=this.menuBar.rect.height;this.menuBar.remove();this.addView(this.menuBar);ELEM.append(this.menuBar.elemId,this.elemId);this.menuBar.moveTo(this.windowView.rect.left,this.windowBar.rect.bottom);}
this.calcWindowPartRects();},stopAnimation:function(){this.base();this.calcWindowPartRects();this.refresh();}});HWindow=HWindowControl;