
var HClass=function(){if(arguments.length){var _84=arguments[0];if(this===window){HClass.prototype.extend.call(_84,arguments.callee.prototype);}else{this.extend(_84);}}};HClass.prototype={extend:function(_h0,_3){var _t1=HClass.prototype.extend;if(arguments.length===2){var _b3=this[_h0];if((_b3 instanceof Function)&&(_3 instanceof Function)&&_b3.valueOf()!==_3.valueOf()&&(/\bbase\b/).test(_3)){var _60=_3;_3=function(){var _J5=this.base;this.base=_b3;var _K5=_60.apply(this,arguments);this.base=_J5;return _K5;};_3.valueOf=function(){return _60;};_3.toString=function(){return String(_60);};}
return this[_h0]=_3;}else if(_h0){var _d0={toSource:null};var _94=["toString","valueOf"];if(HClass._83){_94.push("constructor");}
for(var i=0;(_i=_94[i]);i++){if(_h0[_i]!==_d0[_i]){_t1.call(this,_i,_h0[_i]);}}
for(var _i in _h0){if(!_d0[_i]){_t1.call(this,_i,_h0[_i]);}}}
this.nu=function(){return new(this.extend({constructor:function(args){this.base.apply(this,args);}}))(arguments);};return this;},base:function(){}};HClass.extend=function(_20,_53){var _t1=HClass.prototype.extend;if(!_20){_20={};}
HClass._83=true;var _d0=new this;_t1.call(_d0,_20);var _n1=_d0.constructor;_d0.constructor=this;delete HClass._83;var _y0=function(){if(!HClass._83){_n1.apply(this,arguments);}
this.constructor=_y0;};_y0.prototype=_d0;_y0.extend=this.extend;_y0.implement=this.implement;_y0.toString=function(){return String(_n1);};_t1.call(_y0,_53);var _43=_n1?_y0:_d0;if(_43.init instanceof Function){_43.init();}
return _43;};HClass.implement=function(_u1){if(_u1 instanceof Function){_u1=_u1.prototype;}
this.prototype.extend(_u1);};var Base=HClass;if([]['indexOf']===undefined){Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.extend(Array.prototype,{indexOf:function(_L5){var i=0,l=this.length;for(;i<l;i++){if(this[i]===_L5){return i;}}
return-1;}});}
COMM={_Y8:function(){}};eval('COMM._M5 = function(){return new '+((window['XMLHttpRequest']!==undefined)?'XMLHttpRequest()':(BROWSER_TYPE.ie?'ActiveXObject("Msxml2.XMLHTTP")':'COMM._49()'))+';}');COMM._j4=function(_Y0){var i=0,_n0=_Y0.length,_W2='';for(;i<_n0;i++){_W2+=encodeURIComponent(_Y0[i]);_W2+=(i===_n0-1)?'':(i%2===0)?'=':'&';}
return _W2;};COMM._k4=function(_0){if(_0.X.readyState===4){var _d2=_0.X.status,_l4='on'+_d2,_n4=((_d2>=200&&_d2<300)||(_d2===0));_0[_l4]?_0[_l4](_0):_n4?_0.onSuccess(_0):_0.onFailure(_0);}};COMM.request=function(_w,_1){var _12=COMM,_0=_1?_1:{},_60=_1.method?_1.method.toUpperCase():'GET',_F0=(_1.async===undefined)?true:_1.async,_Y0=_1.params?_1.params:[],_52=_1.headers?_1.headers:{},_t0=_1.contentType?_1.contentType:'application/x-www-form-urlencoded',_i4=_1.charset?_1.charset:'UTF-8',_a4=_1.username?_1.username:null,_d4=_1.username?_1.password:null;if(!_1.onFailure){_0.onFailure=function(resp){console.log('No failure handler specified, response: ',resp);};}
if(!_1.onSuccess){_0.onSuccess=function(resp){console.log('No success handler specified, response: ',resp);};}
_0.url=_w;_0.X=_12._M5();if(_60==='GET'&&_Y0.length!==0){_w+=((_w.indexOf('?')!==-1)?'&':'?')+_12._j4(_Y0);}
if(!_F0){console.log("WARNING: Synchronous "+_60+" request to "+_w+", these will fail on the Symbian web browser.");}
_0.X.open(_60,_w,_F0,_a4,_d4);_0.X.onreadystatechange=function(){_12._k4(_0);};if(_60==='POST'){_52['Content-Type']=_t0+'; charset='+_i4;var _32=_1.body?_1.body:'';for(var _24 in _52){_0.X.setRequestHeader(_24,_52[_24]);}
_0.X.send(_32);}
else if(_60==='GET'){_0.X.send(null);}
if(!_F0){_12._k4(_0);}
return _0;};HDefaultApplicationInterval=20;HSystemTickerInterval=10;HWindowFocusBehaviour=1;HSystem=HClass.extend({constructor:null,type:'[HSystem]',apps:[],appPriorities:[],busyApps:[],appTimers:[],freeAppIds:[],defaultInterval:HDefaultApplicationInterval,viewsZOrder:[],ticks:0,maxAppRunTime:5000,scheduler:function(){for(var _j=0;_j<this.apps.length;_j++){if(this.apps[_j]){if(!this.busyApps[_j]){if((this.ticks%this.appPriorities[_j])===0){this.appTimers[_j]=setTimeout('if (HSystem.apps['+_j+']) {HSystem.apps['+_j+']._s4();}',10);}}}}
if(this._o1.length!==0){this._N5();}},ticker:function(){this.ticks++;this.scheduler();this._69=setTimeout('HSystem.ticker();',HSystemTickerInterval);},addApp:function(_V0,_N){if(this.freeAppIds.length!==0){var _j=this.freeAppIds.unshift();this.apps[_j]=_V0;}else{this.apps.push(_V0);var _j=this.apps.length-1;}
_V0.parent=this;_V0.parents=[this];_V0.appId=_j;this.startApp(_j,_N);return _j;},startApp:function(_j,_N){if(_N===undefined){_N=this.defaultInterval;}
this.appPriorities[_j]=_N;this.busyApps[_j]=false;},stopApp:function(_j){this.busyApps[_j]=true;},reniceApp:function(_j,_N){this.appPriorities[_j]=_N;},killApp:function(_j,_O5){if(!_O5){var _P5=new Date().getTime();while(this.busyApps[_j]===true){if(new Date().getTime()>_P5+this.maxAppRunTime){break;}}}
this.busyApps[_j]=true;this.apps[_j].destroyAllViews();this.apps[_j]=null;delete this.apps[_j];this.freeAppIds.push(_j);},views:[],_Q2:[],addView:function(_7){var _92;if(this._Q2.length===0){_92=this.views.length;this.views.push(_7);}
else{_92=this._Q2.pop();this.views[_92]=_7;}
return _92;},delView:function(_f){this.views[_f]=null;this._Q2.push(_f);},activeWindowId:0,windowFocus:function(_7){if(!_7){this.activeWindowId=0;return;}
var _V2=this.activeWindowId,_40=this.views,_f=_7.viewId;if(_40[_V2]){if(_40[_V2]["windowBlur"]){_40[_V2].windowBlur();}}
this.activeWindowId=_f;_7.bringToFront();_7.windowFocus();},_o1:[],updateZIndexOfChildren:function(_f){if(this._o1.indexOf(_f)===-1){this._o1.push(_f);}},_N5:function(){var j=0,_0=HSystem,_74=this._o1,_Q5=_74.length;for(;j<_Q5;j++){var _f=_74.shift(),_40=((_f===null)?(_0.viewsZOrder):(_0.views[_f].viewsZOrder)),_R5=_40.length,_y1=ELEM.setStyle,_T3=_0.views,_14,_7,_S5='elemId',_T5='z-index',i=0,_6;for(;i<_R5;i++){_14=_40[i];_7=_T3[_14];_6=_7[_S5];_y1(_6,_T5,i);}}}});LOAD('HSystem.ticker();');HApplication=HClass.extend({componentBehaviour:['app'],constructor:function(_N,_o){this.viewId=null;this.views=[];this.markupElemIds=[];this.viewsZOrder=HSystem.viewsZOrder;HSystem.addApp(this,_N);if(_o){this.label=_o;}
else{this.label='ProcessID='+this.appId;}},buildParents:function(_f){var _7=HSystem.views[_f];_7.parent=this;_7.parents=[];for(var _k1=0;_k1<this.parents.length;_k1++){_7.parents.push(this.parents[_k1]);}
_7.parents.push(this);},addView:function(_7){var _f=HSystem.addView(_7);this.views.push(_f);this.buildParents(_f);this.viewsZOrder.push(_f);return _f;},removeView:function(_f){HSystem.views[_f].remove();},destroyView:function(_f){HSystem.views[_f].die();},die:function(){HSystem.killApp(this.appId,false);},destroyAllViews:function(){var i,_f;for(i=0;i<this.views.length;i++){_f=this.views[i];HSystem.views[_f].die();}},_U5:function(){var i,_f,_7;for(i=0;i<this.views.length;i++){_f=this.views[i];_7=HSystem.views[_f];if((_7!==null)&&(_7['onIdle']!==undefined)){_7.onIdle();}}},_s4:function(){HSystem.busyApps[this.appId]=true;this.onIdle();this._U5();HSystem.busyApps[this.appId]=false;},onIdle:function(){}});COMM.Queue=HApplication.extend({commandQueue:[],paused:false,constructor:function(){this.base(10);},onIdle:function(){if(!this.paused&&(this.commandQueue.length!==0)){this.flush();}},pause:function(){this.paused=true;},resume:function(){this.paused=false;this.flush();},flush:function(){var i=0,_v,_x,_10,_80=this.commandQueue.length;for(;i<_80;i++){if(this.paused){break;}
_v=this.commandQueue.shift();try{if(typeof _v==='function'){_v();}
else{_x=_v[0];_10=_v[1];_x(_10);}}
catch(e){if(BROWSER_TYPE.ie){console.log('COMM.Queue; failed to execute the js block: '+_v+' reason:'+e);}
else{console.log('COMM.Queue; failed to execute the js block: '+_v.toSource()+' reason:'+e);}}}},unshift:function(_x,_10){if(_10!==undefined){this.commandQueue.unshift([_x,_10]);}
else{this.commandQueue.unshift(_x);}},push:function(_x,_10){if(_10!==undefined){this.commandQueue.push([_x,_10]);}
else{this.commandQueue.push(_x);}},unshiftEval:function(_02,_10){var _x;eval('_x = function(){'+_02+'}');this.unshift(_x);},pushEval:function(_02){var _x;eval('_x = function(){'+_02+'}');this.push(_x);}}).nu();COMM.Session=HClass.extend({ses_key:'',req_num:0,newKey:function(_T0){var _0=this,_Z3=_0.sha.hexSHA1(_T0+_0.sha_key);_0.req_num++;_0.ses_key=_0.req_num+':.o.:'+_Z3;_0.sha_key=_Z3;},constructor:function(){var _0=this;_0.sha=SHAClass.nu(8);_0.sha_key=_0.sha.hexSHA1(((new Date().getTime())*Math.random()*1000).toString());_0.ses_key='0:.o.:'+_0.sha_key;}}).nu();COMM.Transporter=HApplication.extend({constructor:function(){var _0=this;this.serverLostMessage='Server Connection Lost. Retrying.';_0.label='Transporter';_0.url=false;_0.busy=false;_0.stop=true;_0._c0=false;_0._L2=false;_0._V5=false;_0.base(1);},onIdle:function(){if(!this.busy){this.sync();}},poll:function(_W5){HSystem.reniceApp(this.appId,_W5);},getClientEvalError:function(){var _0=COMM.Transporter;if(_0._L2){return'&err_msg='+HVM._j5(_0._L2);}
return'';},success:function(resp){var _0=COMM.Transporter,_x1=eval(resp.X.responseText),i=1,_X5=_x1.length,_T0=_x1[0];if(_T0===''){console.log('Invalid session, error message should follow...');}
else{COMM.Session.newKey(_T0);}
for(;i<_X5;i++){try{COMM.Queue.pushEval(_x1[i]);}
catch(e){console.log('clientError:'+e+" - "+e.description+' - '+_x1[i]);_0._L2=e+" - "+e.description+' - '+_x1[i];}}
if(_0._c0){ELEM.del(_0._c0);_0._c0=false;}
COMM.Queue.push(function(){COMM.Transporter.flushBusy();});COMM.Queue.flush();},flushBusy:function(){var _0=COMM.Transporter;_0.busy=false;if(HVM.tosync.length!==0){_0.sync();}},failMessage:function(_J1,_S3){console.log('failMessage?');this.stop=true;COMM.Queue.push(function(){jsLoader.load('default_theme');});COMM.Queue.push(function(){jsLoader.load('controls');});COMM.Queue.push(function(){jsLoader.load('servermessage');});COMM.Queue.push(function(){ReloadApp.nu(_J1,_S3);});},failure:function(_F1){var _0=COMM.Transporter;if(_F1.X.status===0){console.log(_0.serverLostMessage);if(HSystem.appPriorities[_0.appId]<10){HSystem.reniceApp(_0.appId,10);}
if(!_0._c0){_0._c0=ELEM.make(0);ELEM.setCSS(_0._c0,'position:absolute;z-index:1000;padding-left:8px;left:0px;top:0px;height:28px;width:100%;background-color:#600;color:#fff;font-family:Arial,sans-serif;font-size:20px;');ELEM.setStyle(_0._c0,'opacity',0.85);ELEM.setHTML(_0._c0,_0.serverLostMessage);}
else{ELEM.get(_0._c0).innerHTML+='.';}
_0.busy=false;}
else{_0.failMessage('Transporter Error','Transporter was unable to complete the synchronization request.');}},sync:function(){if(this.stop){return;}
if(this.busy){return;}
this.busy=true;var _0=this,_l1=COMM.Values.sync(),_T0='ses_key='+COMM.Session.ses_key,_Y5=_0.getClientEvalError(),_32=[_T0,_Y5,_l1?'&values='+_l1:''].join('');COMM.request(_0.url,{_0:_0,onSuccess:COMM.Transporter.success,onFailure:COMM.Transporter.failure,method:'POST',async:true,body:_32});}}).nu();LOAD('COMM.Transporter.url=HCLIENT_HELLO;COMM.Transporter.stop=false;COMM.Transporter.sync();');HValue=HClass.extend({constructor:function(_4,_3){this.id=_4;this.type='[HValue]';this.value=_3;this.views=[];if(_4){HVM.add(_4,this);}},die:function(){for(var _O=0;_O<this.views.length;_O++){var _73=this.views[_O];_73.setValueObj(HDummyValue.nu());this.views.splice(_O,1);}
if(this.id){HVM.del(this.id);}},set:function(_3){if(this.differs(_3)){this.value=_3;if(this.id){HVM.changed(this);}
this.refresh();}},differs:function(_3){return(COMM.Values.encode(_3)!==COMM.Values.encode(this.value));},s:function(_3){this.value=_3;this.refresh();},get:function(){return this.value;},bind:function(_B){if(_B===undefined){throw("HValueBindError: _B is undefined!");}
if(this.views.indexOf(_B)===-1){this.views.push(_B);_B.setValueObj(this);}},unbind:function(_B){for(var _O=0;_O<this.views.length;_O++){var _73=this.views[_O];if(_73===_B){this.views.splice(_O,1);return;}}},release:function(_B){return this.unbind(_B);},refresh:function(){for(var _O=0;_O<this.views.length;_O++){var _B=this.views[_O];if(_B.value!==this.value){if(!_B._c4){_B._c4=true;_B.setValue(this.value);_B._c4=false;}}}}});JSLoader=HClass.extend({constructor:function(_Z5){var _0=this;_0._f4=[];_0.uri=_Z5;_0._19=false;},_06:function(_0,_F1){console.log("failed to load js: "+_F1.url);},load:function(_I2){var _0=this;if((_0._f4.indexOf(_I2)!==-1)){return;}
COMM.Queue.pause();_0._f4.push(_I2);_0._99=COMM.request(_0.uri+_I2+'.js',{onSuccess:function(_F1){COMM.Queue.unshiftEval(_F1.X.responseText);COMM.Queue.resume();},onFailure:_0._06,method:'GET',async:true});}});RUN("jsLoader = JSLoader.nu(HCLIENT_BASE+'/js/');");