
HButton=HControl.extend({componentName:'button',setStyle:function(_i,_3){ELEM.setStyle(this.markupElemIds.label,_i,_3);}});HClickValueButton=HButton.extend({refreshValue:function(){this.setEnabled(this.value===0);},click:function(){this.setValue(1);}});HCheckbox=HButton.extend({componentName:'checkbox',constructor:function(_2,_b,_1){this.base(_2,_b,_1);this.setClickable(true);},click:function(){this.setValue(!this.value);},setStyle:function(_i,_3,_i0){this.setStyleOfPart('label',_i,_3,_i0);},refreshValue:function(){if(this.markupElemIds.control){if(this.value){this.toggleCSSClass(this.markupElemIds.control,'checked',true);this.toggleCSSClass(this.markupElemIds.control,'unchecked',false);}
else{this.toggleCSSClass(this.markupElemIds.control,'checked',false);this.toggleCSSClass(this.markupElemIds.control,'unchecked',true);}}}});HCheckBox=HCheckbox;HRadioButton=(HCheckbox.extend(HValueMatrixComponentExtension)).extend({componentName:'radiobutton'});HRadiobutton=HRadioButton;HStringView=HControl.extend({componentName:"stringview",componentBehaviour:['view','control','text'],setStyle:function(_i,_3,_g1){if(!this['markupElemIds']||!this.markupElemIds['value']){return;}
ELEM.setStyle(this.markupElemIds.value,_i,_3,_g1);},refreshLabel:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'title',this.label);}}}});HTextControl=HControl.extend({componentName:"textcontrol",constructor:function(_2,_u,_1){this.base(_2,_u,_1);this.setTextEnter(true);},refreshLabel:function(){if(this['markupElemIds']!==undefined){if(this.markupElemIds['label']!==undefined){ELEM.setAttr(this.markupElemIds.label,'title',this.label);}}},drawSubviews:function(){if(this['markupElemIds']!==undefined){if(this.markupElemIds['label']!==undefined){var _K1=ELEM.getVisibleSize(this.elemId),_D=_K1[0],_W=_K1[1],_y=this.markupElemIds.value,_o=this.markupElemIds.label;if(BROWSER_TYPE.firefox){ELEM.setStyle(_y,'padding-top','0px');ELEM.setStyle(_y,'padding-left','0px');ELEM.setStyle(_o,'left','2px');ELEM.setStyle(_o,'top','2px');ELEM.setStyle(_o,'right','2px');ELEM.setStyle(_o,'bottom','2px');}
else if(BROWSER_TYPE.ie7){ELEM.setStyle(_y,'left','2px');ELEM.setStyle(_y,'top','2px');ELEM.setStyle(_y,'padding-top','0px');ELEM.setStyle(_y,'padding-left','0px');ELEM.setStyle(_y,'padding-right','8px');ELEM.setStyle(_y,'padding-bottom','0px');ELEM.setStyle(_y,'width',(_D-4)+'px');ELEM.setStyle(_y,'height',(_W-4)+'px');ELEM.setStyle(_o,'left','0px');ELEM.setStyle(_o,'top','0px');ELEM.setStyle(_o,'right','0px');ELEM.setStyle(_o,'bottom','0px');}
else if(BROWSER_TYPE.safari||BROWSER_TYPE.chrome){ELEM.setStyle(_y,'width','auto');ELEM.setStyle(_y,'height','auto');ELEM.setStyle(_y,'left','-2px');ELEM.setStyle(_y,'top','-2px');if(BROWSER_TYPE.chrome){ELEM.setStyle(_y,'right','0px');ELEM.setStyle(_y,'bottom','0px');}
else{ELEM.setStyle(_y,'right','-2px');ELEM.setStyle(_y,'bottom','-2px');}
ELEM.setStyle(_o,'left','0px');ELEM.setStyle(_o,'top','0px');ELEM.setStyle(_o,'right','0px');ELEM.setStyle(_o,'bottom','0px');}}}},setStyle:function(_i,_3,_g1){if(!this['markupElemIds']||!this.markupElemIds['value']){return;}
this.setStyleOfPart('value',_i,_3,_g1);},setEnabled:function(_8){this.base(_8);if(this['markupElemIds']===undefined){return;}
if(this.markupElemIds.value){ELEM.setAttr(this.markupElemIds.value,'disabled',!this.enabled);}},hasTextFocus:false,textFocus:function(){this.hasTextFocus=true;},textBlur:function(){this.hasTextFocus=false;},refreshValue:function(){if(this.markupElemIds){if(this.markupElemIds.value){ELEM.get(this.markupElemIds.value).value=this.value;}}},validateText:function(_3){return _3;},textEnter:function(){if(this['markupElemIds']===undefined){return;}
var _3=this.validateText(ELEM.get(this.markupElemIds.value).value);if(_3!==this.value.toString()){this.setValue(_3);}}});HNumericTextControl=HTextControl.extend({mouseWheel:function(_M){var _3=this.value;_3=_3-((_M<0)?1:-1);this.setValue(Math.round(this.validateText(_3)));},validateText:function(_3){if(isNaN(_3)){_3=this.value;}
_3=parseInt(_3,10);if(_3>this.options.maxValue){_3=this.options.maxValue;}
else if(_3<this.options.minValue){_3=this.options.minValue;}
if(this['markupElemIds']&&this.markupElemIds['value']){var _5=ELEM.get(this.markupElemIds.value);if(_5.value!=_3){_5.value=_3;}}
return _3;},setValue:function(_3){this.base(this.validateText(_3));}});HPasswordControl=HTextControl.extend({drawSubviews:function(){this.base();ELEM.get(this.markupElemIds.value).type='password';},refreshValue:function(){}});HTextArea=HTextControl.extend({componentName:"textarea"});HUploader=HControl.extend({componentName:'uploader',uploadState:false,uploadKey:false,uploadStateLabels:{'0':"Select file...",'1':"Uploading...",'2':"Processing data...",'3':"Upload Complete",'4':"Preparing upload",'-1':"Error: Invalid request",'-2':"Error: Invalid upload key",'-3':"Error: Invalid data format",'-4':"Error: File too big",'-6':"Error: Post-processing failed"},markupElemNames:['form','file','iframe','upload_progress','progress_label','progress_indicator','button','button_label','value','ack_button'],setUploadState:function(_F,_22){if(_F!==this.uploadState){this.uploadState=_F;var _K2=_F.toString();if(this.uploadStateLabels[_K2]!==undefined){ELEM.get(this.markupElemIds.value).value=this.valueObj.id;var _o=this.uploadStateLabels[_K2];if(_F===0){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','hidden');ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');ELEM.setHTML(this.markupElemIds.button_label,_o);ELEM.setStyle(this.markupElemIds.button,'visibility','inherit');ELEM.setStyle(this.markupElemIds.form,'visibility','inherit');ELEM.setAttr(this.markupElemIds.form,'action','/U/'+_22,true);ELEM.get(this.markupElemIds.file).value='';this.uploadKey=_22;}
else if(_F===1||_F===2||_F===3||_F===4){ELEM.setStyle(this.markupElemIds.upload_progress,'visibility','inherit');if(_F===1||_F===2||_F===4){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','inherit');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','hidden');}
else{ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');}
ELEM.setHTML(this.markupElemIds.progress_label,_o);ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');if(_F===1){ELEM.get(this.markupElemIds.form).submit();}}
else if(_F<0){ELEM.setStyle(this.markupElemIds.progress_indicator,'visibility','hidden');ELEM.setStyle(this.markupElemIds.ack_button,'visibility','inherit');ELEM.setHTML(this.markupElemIds.progress_label,'<span style="color:red;">'+_o+'</span>');ELEM.setStyle(this.markupElemIds.button,'visibility','hidden');ELEM.setStyle(this.markupElemIds.form,'visibility','hidden');}}}},refreshValue:function(){if(typeof this.value!=='string'){return;}
if(this.value.indexOf(':::')<1){return;}
var _G2=this.value.split(':::');if(_G2.length!==2){return;}
var _F=parseInt(_G2[0],10),_22=_G2[1];this.setUploadState(_F,_22);},upload:function(){this.setValue('1:::'+this.uploadKey);},getNewUploadKey:function(){this.setValue('4:::'+this.uploadKey);},click:function(){if((this.uploadState===3)||(this.uploadState<0)){this.getNewUploadKey();}}});HSlider=HControl.extend({componentName:"slider",constructor:function(_2,_b,_1){if(!_1){_1={};}
if(!_1.events){_1.events={mouseDown:false,mouseUp:false,draggable:true,keyDown:true,keyUp:true,mouseWheel:true};}
_1=HClass.extend({minValue:0,maxValue:1,repeatDelay:300,repeatInterval:50,inverseAxis:false}).extend(_1).nu();if(this.isinherited){this.base(_2,_b,_1);}
else{this.isinherited=true;this.base(_2,_b,_1);this.isinherited=false;}
this.refreshOnValueChange=false;this._U=false;if(!this.isinherited){this.draw();}},setValue:function(_3){if(_3<this.minValue){var _3=this.minValue;}
if(_3>this.maxValue){var _3=this.maxValue;}
this.base(_3);if(this._44){this.drawThumbPos();}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._n5();}
this.refresh();},startDrag:function(_d,_g){var _b4=ELEM.getVisiblePosition(this.elemId,true);this._o5=_b4[0];this._p5=_b4[1];this.doDrag(_d,_g);},endDrag:function(_d,_g){this.doDrag(_d,_g);},doDrag:function(_d,_g){_d-=this._o5;_g-=this._p5;var _q5=this._U?_g:_d;var _3=this._r5(_q5);this.setValue(_3);},keyDown:function(_J){if((_J===Event.KEY_LEFT&&!this._U)||(_J===Event.KEY_DOWN&&this._U)){this._z1=true;this._E1(-0.05);}
else if((_J===Event.KEY_RIGHT&&!this._U)||(_J===Event.KEY_UP&&this._U)){this._z1=true;this._E1(0.05);}
else if(_J===Event.KEY_HOME){this.setValue(this.minValue);}
else if(_J===Event.KEY_END){this.setValue(this.maxValue);}
else if(_J===Event.KEY_PAGEDOWN){this._z1=true;this._E1(-0.25);}
else if(_J===Event.KEY_PAGEUP){this._z1=true;this._E1(0.25);}},keyUp:function(_J){this._z1=false;},mouseWheel:function(_M){var _o0;if(_M>0){_o0=0.05;}
else{_o0=-0.05;}
if(this.options.inverseAxis){_o0=0-_o0;}
var _3=(this.maxValue-this.minValue)*_o0;this.setValue(this.value+_3);},_E1:function(_o0,_41){if(!_41){_41=this.options.repeatDelay;}
else if(_41===this.options.repeatDelay){_41=this.options.repeatInterval;}
if(this._z1&&this.active){var _3=(this.maxValue-this.minValue)*_o0;this.setValue(this.value+_3);var _r=this;if(this._P2){window.clearTimeout(this._P2);this._P2=null;}
this._P2=window.setTimeout(function(){_r._E1(_o0,_41);},_41);}},thumbSize:21,_n5:function(){this._44=this.markupElemIds.control;this.drawThumbPos();},_N2:function(){if(this._U){var _a0=this.rect.height-this.thumbSize;}else{var _a0=this.rect.width-this.thumbSize;}
var _r1=_a0*((this.value-this.minValue)/(this.maxValue-this.minValue));if(this._U){_r1=_a0-_r1;}
var _O2=parseInt(_r1,10)+'px';return _O2;},_r5:function(_D0){if(this._U){var _a0=this.rect.height-this.thumbSize;}else{var _a0=this.rect.width-this.thumbSize;}
_D0-=(this.thumbSize/2);if(_D0<0){_D0=0;}
if(_D0>_a0){_D0=_a0;}
if(this._U){return this.maxValue-((_D0/_a0)*(this.maxValue-this.minValue));}else{return this.minValue+((_D0/_a0)*(this.maxValue-this.minValue));}},drawThumbPos:function(){var _s5=this._U?'top':'left',_a3=this._N2();ELEM.setStyle(this._44,_s5,_a3);this.setOrientation(this.options['orientation']||this.prevOrientation);},prevOrientation:'c',cssClassPrefix:'h',setOrientation:function(_m0){if(!_m0){_m0='c';}
_m0=_m0.toLowerCase();if(_m0===this.prevOrientation){return false;}
if(this['markupElemIds']===undefined){return false;}
if(this.markupElemIds['control']===undefined){return false;}
var _t5=this.toggleCSSClass,_u5=this.markupElemIds.control,_v5=['n','s','w','e','c'],_F2='',_u4='',_U3=this.cssClassPrefix,_w5=this._U?'v':'',_X3=false,i=0;for(;i<5;i++){_F2=_v5[i];_X3=(_m0===_F2);_u4=(_m0==='c')?_U3+_w5+'slider_thumb':_U3+'slider_thumb_'+_F2;_t5(_u5,_u4,_X3);}
this.prevOrientation=_m0;}});HVSlider=HSlider.extend({componentName:"vslider",constructor:function(_2,_u,_1){if(this.isinherited){this.base(_2,_u,_1);}
else{this.isinherited=true;this.base(_2,_u,_1);this.isinherited=false;}
this._U=true;if(!this.isinherited){this.draw();}}});HProgressBar=HControl.extend({componentName:"progressbar",constructor:function(_2,_u,_1){if(this.isinherited){this.base(_2,_u,_1);}
else{this.isinherited=true;this.base(_2,_u,_1);this.isinherited=false;}
if(!_1){_1={};}
var _P=Base.extend({value:0,minValue:0,maxValue:100});_P=_P.extend(_1);_1=new _P();this.value=_1.value;this.minValue=_1.minValue;this.maxValue=_1.maxValue;this.visibleWidth=this.rect.width-2;this.type='[HProgressBar]';this._p3='progressmark';if(!this.isinherited){this.draw();}
this.progressFrameHeight=20;this.progressFrames=10;this.currProgressFrame=0;},setProgressFrameHeight:function(_K){this.progressFrameHeight=_K;},setProgressFrameNum:function(_h3){this.progressFrames=_h3;},setValue:function(_3){this.base(_3);this.drawProgress();},onIdle:function(){if(this.progressbarElemId){this.currProgressFrame++;if(this.currProgressFrame>=this.progressFrames){this.currProgressFrame=0;}
var _K=this.currProgressFrame*this.progressFrameHeight;ELEM.setStyle(this.progressbarElemId,'background-position','0px -'+_K+'px');}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._93();}},_93:function(){this.progressbarElemId=this.bindDomElement(this._p3+this.elemId);this.drawProgress();},_N2:function(){var _r1=this.visibleWidth*((this.value-this.minValue)/(this.maxValue-this.minValue));var _O2=parseInt(Math.round(_r1),10)+'px';return _O2;},drawProgress:function(){if(this.progressbarElemId){var _a3=this._N2();ELEM.setStyle(this.progressbarElemId,'width',_a3);}}});HProgressIndicator=HControl.extend({packageName:"progress",componentName:"progressindicator",constructor:function(_2,_u,_1){if(this.isinherited){this.base(_2,_u,_1);}
else{this.isinherited=true;this.base(_2,_u,_1);this.isinherited=false;}
if(!_1){_1={};}
var _P=Base.extend({value:0,interval:20});_P=_P.extend(_1);_1=new _P();this.type='[HProgressIndicator]';this._p3='progressmark';this.interval=_1.interval;this.value=_1.value;this._21=null;if(!this.isinherited){this.draw();}},setValue:function(_3){if(this._13){if(_3===true&&!this._21){var temp=this;this._21=setInterval(function(){temp.drawProgress();},temp.interval);}
else{clearInterval(this._21);this._21=null;}}},die:function(){this.base();if(this._21){clearInterval(this._21);}},draw:function(){if(!this.drawn){this.drawRect();this.drawMarkup();this._93();}},_93:function(){this._13=this.bindDomElement(this._p3+this.elemId);this.drawProgress();},drawProgress:function(){this.progressPosition++;if(this.progressPosition>this.positionLimit-1){this.progressPosition=0;}
if(this._13){ELEM.setStyle(this._13,'background-position','0px -'+
(this.progressPosition*this.rect.height)+'px');}}});HImageView=HControl.extend({constructor:function(_2,_u,_1){if(!_1){_1={};}
var _P=HClass.extend({scaleToFit:true});_1=new(_P.extend(_1))();if(this.isinherited){this.base(_2,_u,_1);}
else{this.isinherited=true;this.base(_2,_u,_1);this.isinherited=false;}
if(!this.value){this.value=this.getThemeGfxPath()+"/blank.gif";}
if(!this.isinherited){this.draw();}},_e4:function(_W0){this.elemId=ELEM.make(_W0,'img');ELEM.setAttr(this.elemId,'src',this.value);ELEM.setAttr(this.elemId,'alt',this.label);},_m4:function(_W0){this.elemId=ELEM.make(_W0,'div');ELEM.setStyle(this.elemId,'background-image','url('+this.value+')');ELEM.setStyle(this.elemId,'background-position','0px 0px');ELEM.setStyle(this.elemId,'background-repeat','no-repeat');},_h5:function(_W0){if(this.options.scaleToFit){this._e4(_W0);}
else{this._m4(_W0);}},refreshValue:function(){ELEM.setAttr(this.elemId,'src',this.value);},refreshLabel:function(){ELEM.setAttr(this.elemId,'alt',this.label);},scaleToFit:function(){if(!this.options.scaleToFit){ELEM.del(this.elemId);this._e4(this._s3());this.options.scaleToFit=true;}},scaleToOriginal:function(){if(this.options.scaleToFit){ELEM.del(this.elemId);this._m4(this._s3());this.options.scaleToFit=false;}}});HSplitView=HControl.extend({componentName:"splitview",constructor:function(_2,_u,_1){_1=new(Base.extend({vertical:false}).extend(_1));if(this.isinherited){this.base(_2,_u,_1);}
else{this.isinherited=true;this.base(_2,_u,_1);this.isinherited=false;}
this.preserveTheme=true;this.vertical=this.options.vertical;this.dividerWidth=6;this.splitviews=[];this.dividers=[];this.setDraggable(true);if(!this.isinherited){this.draw();}},startDrag:function(_d,_g,_A){if(!_A){return;}
_d-=this.pageX();_g-=this.pageY();var _m=this.dividers.indexOfObject(_A);this._h4=new HPoint(_d,_g);this._x5=new HPoint(_d,_g);this._90=this._h4.subtract(_A.rect.leftTop);this._Y=this.splitviews[_m];this._G=this.splitviews[_m+1];this._A=_A;if(this.vertical===false){this._42=this._Y.rect.top;this._a2=this._G.rect.bottom-this.dividerWidth;}else{this._42=this._Y.rect.left;this._a2=this._G.rect.right-this.dividerWidth;}},doDrag:function(_d,_g,_A){if(!_A){return;}
_d-=this.pageX();_g-=this.pageY();if(this.vertical===false){var _Z=_g-this._90.y;if(_Z<this._42||_Z>this._a2){return;}
this._Y.rect.setHeight(_Z);this._Y.rect.updateSecondaryValues();this._Y.setStyle('height',this._Y.rect.height+'px',true);this._A.rect.setTop(_Z);this._A.rect.updateSecondaryValues();this._A.setStyle('top',this._A.rect.top+'px',true);this._G.rect.setTop(_Z+this.dividerWidth);this._G.rect.updateSecondaryValues();this._G.setStyle('top',this._G.rect.top+'px',true);this._G.setStyle('height',this._G.rect.height+'px',true);}else{var _Z=_d-this._90.x;if(_Z<this._42||_Z>this._a2){return;}
this._Y.rect.setRight(_Z);this._Y.rect.updateSecondaryValues();this._Y.setStyle('width',this._Y.rect.width+'px',true);this._A.rect.setLeft(_Z);this._A.rect.updateSecondaryValues();this._A.setStyle('left',this._A.rect.left+'px',true);this._G.rect.setLeft(_Z+this.dividerWidth);this._G.rect.updateSecondaryValues();this._G.setStyle('left',this._G.rect.left+'px',true);this._G.setStyle('width',this._G.rect.width+'px',true);}},endDrag:function(_d,_g,_A){this.doDrag(_d,_g);delete this._h4;delete this._x5;delete this._90;delete this._Y;delete this._G;delete this._A;delete this._42;delete this._a2;},addSplitViewItem:function(_v,_m){if(_m!==undefined){this.splitviews.splice(_m,0,_v);}else{this.splitviews.push(_v);}},removeSplitViewItem:function(_v){if(typeof _v==="object"){var _m=this.splitviews.indexOfObject(_v);if(_m!==-1){this.splitviews.splice(_m,1);_v.die();this.dividers.splice(_m,1);this.dividers[_m].die();}}},setVertical:function(_8){this.vertical=_8;this.options.vertical=_8;},adjustViews:function(){var _50=this.splitviews.length;var _c2;var _Z0;var _b2;var _51;if(this.vertical===false){_c2=this.rect.height-this.dividerWidth*(_50-1);_Z0=0;for(var i=0;i<_50;i++){_Z0+=this.splitviews[i].rect.height;}
_b2=_c2/_Z0;_51=0;for(var i=0;i<_50;i++){var _7=this.splitviews[i];var _01=_7.rect.height*_b2;if(i===_50-1){_01=Math.floor(_01);}else{_01=Math.ceil(_01);}
_7.rect.offsetTo(0,_51);_7.rect.setSize(this.rect.width,_01);_7.draw();_51+=_01+this.dividerWidth;}}else{_c2=this.rect.width-this.dividerWidth*(_50-1);_Z0=0;for(var i=0;i<_50;i++){_Z0+=this.splitviews[i].rect.width;}
_b2=_c2/_Z0;_51=0;for(var i=0;i<_50;i++){var _7=this.splitviews[i];var _X0=_7.rect.width*_b2;if(i===_50-1){_X0=Math.floor(_X0);}else{_X0=Math.ceil(_X0);}
_7.rect.offsetTo(_51,0);_7.rect.setSize(_X0,this.rect.height);_7.draw();_51+=_X0+this.dividerWidth;}}
this.draw();},refresh:function(){this.base();if(this.drawn){var _50=this.splitviews.length;var _I;for(var i=0;i<(_50-1);i++){_I=new HRect(this.splitviews[i].rect);if(!this.vertical){_I.offsetTo(_I.left,_I.bottom);_I.setHeight(this.dividerWidth);}else{_I.offsetTo(_I.right,_I.top);_I.setWidth(this.dividerWidth);}
if(!this.dividers[i]){this.dividers[i]=new HDivider(_I,this);}else{var _7=this.dividers[i];_7.rect.offsetTo(_I.left,_I.top);_7.rect.setSize(_I.width,_I.height);_7.draw();}}}}});HStepper=HControl.extend({componentName:"stepper",constructor:function(_2,_b,_1){if(!_1){_1={};}
if(!_1.events){_1.events={mouseDown:true,keyDown:true,mouseWheel:true};}
_1=HClass.extend({minValue:0,maxValue:100,stepSize:1,repeatInterval:200,wrapAround:false}).extend(_1).nu();this.base(_2,_b,_1);},setWrapAround:function(_y5){this.options.wrapAround=_y5;},_04:function(_3){var _0=this,_1=_0.options,_Y3=_1.minValue,_V3=_1.maxValue,_v4=_3<_Y3,_z5=_3>_V3,_A5=(_v4||_z5);if(!_A5){return _3;}
if(_1.wrapAround){if(_v4){return _V3;}
else{return _Y3;}}
else{return _0.value;}},stepUp:function(){this.setValue(this._04(this.value+this.options.stepSize));},stepDown:function(){this.setValue(this._04(this.value-this.options.stepSize));},_r4:function(_A0){return['HSystem.views[',this.viewId,'].step',(_A0?'Up':'Down'),'();'].join('');},bgStateUp:'0px -23px',bgStateDown:'0px -46px',_B5:function(_A0){ELEM.setStyle(this.markupElemIds.state,'background-position',_A0?this.bgStateUp:this.bgStateDown);},_C5:function(){ELEM.setStyle(this.markupElemIds.state,'background-position','');},_11:function(_A0){var _0=this,_1=_0.options;_0._B5(_A0);if(_A0){_0.stepUp();_0._q4=setInterval(_0._r4(1),_1.repeatInterval);}
else{_0.stepDown();_0._q4=setInterval(_0._r4(0),_1.repeatInterval);}},_J2:function(){this._C5();clearInterval(this._q4);},mouseDown:function(x,y){this.setMouseUp(true);this._11((y-ELEM.getVisiblePosition(this.elemId)[1])<=11);},mouseUp:function(){this._J2();},blur:function(){this._J2();},keyDown:function(_l0){this.setKeyUp(true);var _D5=(_l0===Event.KEY_DOWN),_o4=(_l0===Event.KEY_UP),_E5=(_l0===Event.KEY_LEFT),_p4=(_l0===Event.KEY_RIGHT),_F5=(_D5||_o4||_E5||_p4);if(_F5){this._11((_o4||_p4));}
else if(_l0===Event.KEY_HOME){this.setValue(this.options.minValue);}
else if(_l0===Event.KEY_END){this.setValue(this.options.maxValue);}
else if(_l0===Event.KEY_PAGEUP){this._11(1);}
else if(_l0===Event.KEY_PAGEDOWN){this._11(0);}},keyUp:function(){this._J2();},mouseWheel:function(_M){(_M>0)?this.stepUp():this.stepDown();}});HValidatorView=HControl.extend({constructor:function(_2,_b,_1){if(_1!==undefined){if(_1.valueField&&_1.valueField.componentBehaviour[1]==='control'){_2.offsetTo(_1.valueField.rect.right,_1.valueField.rect.top);}}
this.base(_2,_b,_1);},drawSubviews:function(){this.setStyle('background-image',"url('"+this.getThemeGfxFile('validator.png')+"')");},setValue:function(_8){if(!_8&&_8!==false){_8=false;}
this.base(_8);},refreshValue:function(){var _0=this,_3=_0.value,_t4=_3===true,_d=_t4?-21:0,_g=_0.enabled?0:-21,_J1=_t4?'':_3,_W3=ELEM.setStyle,_6=_0.elemId;_W3(_6,'background-repeat','no-repeat');ELEM.setAttr(_6,'title',_J1);_W3(_6,'background-position',_d+'px '+_g+'px');}});HWindow=HDynControl.extend({componentName:'window',constructor:function(_2,_G5,_1){if(!_1){_1={};}
var _P=HClass.extend({minSize:[96,54],maxSize:[16000,9000],resizeW:4,resizeE:4,resizeN:4,resizeS:4,resizeNW:[6,6],resizeNE:[6,6],resizeSW:[6,6],resizeSE:[16,16],noResize:false,fullWindowMove:false,closeButton:false,collapseButton:false,zoomButton:false});_1=new(_P.extend(_1))();if(_1.noResize){_1.minSize=[_2.width,_2.height];_1.maxSize=[_2.width,_2.height];_1.resizeW=0;resizeE=0;resizeN=0;resizeS=0;resizeNW=[0,0];resizeNE=[0,0];resizeSW=[0,0];resizeSE=[0,0];}
this.base(_2,_G5,_1);HSystem.windowFocus(this);},makeRectRules:function(){var _0=this,_D2=_0.base(),_2=_0.rect,_q=_0.options,_82=_q.resizeW;if(!_q.fullWindowMove){if(_q.zoomButton){_82=61;}
else if(_q.collapseButton){_82=46;}
else if(_q.closeButton){_82=27;}
_D2[8]=[_82,_q.resizeN,_2.width-_q.resizeE,25];}
return _D2;},gainedActiveStatus:function(){HSystem.windowFocus(this);},windowFocus:function(){this.toggleCSSClass(this.elemId,'inactive',false);},windowBlur:function(){this.toggleCSSClass(this.elemId,'inactive',true);this.setStyle('cursor','default');},windowClose:function(){this.die();},windowCollapse:function(){},windowZoom:function(){}});HTabView=HView.extend({tabIndex:0,flexRight:true,flexRightOffset:0,flexBottom:true,flexBottomOffset:0,draw:function(){var _P1=this.drawn;this.base();if(!_P1){var i=0,_q3=[['overflow','auto']];for(i;i<_q3.length;i++){this.setStyle(_q3[i][0],_q3[i][1]);}
this.hide();}}});HTab=HControl.extend({componentName:"tab",componentBehaviour:['view','control','tab'],refreshOnValueChange:false,refreshOnLabelChange:false,constructor:function(_2,_b,_1){this.tabInit();if(this.isinherited){this.base(_2,_b,_1);}
else{this.isinherited=true;this.base(_2,_b,_1);this.isinherited=false;}
this.type='[HTab]';this.setMouseDown(true);if(!this.isinherited){this.draw();}},setValue:function(_3){this.base(_3);if(typeof _3==='number'){var _m=parseInt(_3,10);if(_m<this.tabs.length){if(_m!==this.selectIdx){this.selectTab(_m);}}}},stringWidth:function(_x0,_6){var _e1='<span style="'+this.fontStyle+'">'+_x0+'</span>',_D=this.base(_e1,null,_6);return _D;},tabInit:function(){this.tabs=[];this.tabLabels=[];this.tabLabelBounds=[];this.tabLabelStrings=[];this.rightmostPx=0;this.selectIdx=-1;this.tabLabelHeight=20;this.tabLabelLeftEdge=4;this.tabLabelRightEdge=4;this.fontStyle='font-family:Arial,sans-serif;font-size:13px;';this.tabLabelHTMLPrefix1='<div class="edge-left"></div><div class="tablabel" style="width:';this.tabLabelHTMLPrefix2='px">';this.tabLabelHTMLSuffix='</div><div class="edge-right"></div>';this.tabLabelParentElem='label';this.tabLabelElementTagName='div';this.tabLabelAlign='left';this.tabLabelFillBg=false;this.tabTriggerLink=false;this.tabLabelNoHTMLPrefix=false;},setLabel:function(_o){this.label=_o;},selectTab:function(_p){if(_p instanceof HTabView){_p=_p.tabIndex;}
if(this.selectIdx!==-1){var _34=this.tabLabels[this.selectIdx],_H5=this.tabs[this.selectIdx];ELEM.removeClassName(_34,'item-fg');ELEM.addClassName(_34,'item-bg');HSystem.views[_H5].hide();}
if(_p!==-1){var _T=this.tabLabels[_p],_r3=this.tabs[_p];ELEM.removeClassName(_T,'item-bg');ELEM.addClassName(_T,'item-fg');HSystem.views[_r3].show();}
this.selectIdx=_p;this.setValue(_p);},addTab:function(_72,_I5){var _p=this.tabs.length,_k3='',_54=this.stringWidth(_72,0),_g3=_54+this.tabLabelLeftEdge+this.tabLabelRightEdge,_m1=new HTabView(new HRect(0,this.tabLabelHeight,this.rect.width,this.rect.height),this),_T=ELEM.make(this.markupElemIds[this.tabLabelParentElem],this.tabLabelElementTagName);_p=this.tabs.length;if(this.tabLabelNoHTMLPrefix){_k3=_72;}
else{_k3=this.tabLabelHTMLPrefix1+_54+this.tabLabelHTMLPrefix2+_72+this.tabLabelHTMLSuffix;}
_m1.hide();ELEM.addClassName(_T,'item-bg');ELEM.setStyle(_T,'width',_g3+'px');ELEM.setStyle(_T,this.tabLabelAlign,this.rightmostPx+'px');ELEM.setHTML(_T,_k3);this.tabLabelStrings.push(_72);if(this.tabTriggerLink&&this.tabLabelElementTagName==='a'){ELEM.setAttr(_T,'href','javascript:HSystem.views['+this.viewId+'].selectTab('+_p+');');}
else if(this.tabTriggerLink){ELEM.setAttr(_T,'mouseup','HSystem.views['+this.viewId+'].selectTab('+_p+');');}
else{this.tabLabelBounds.push([this.rightmostPx,this.rightmostPx+_g3]);}
this.rightmostPx+=_g3;if(this.tabLabelAlign==='right'){ELEM.setStyle(this.markupElemIds[this.tabLabelParentElem],'width',this.rightmostPx+'px');}
else if(this.tabLabelFillBg){ELEM.setStyle(this.markupElemIds.state,'left',this.rightmostPx+'px');}
this.tabs.push(_m1.viewId);this.tabLabels.push(_T);_m1.tabIndex=_p;if(_I5){this.selectTab(_p);}
return _m1;},mouseDown:function(_d,_g){if(this.tabTriggerLink){this.setMouseDown(false);return;}
_d-=this.pageX();_g-=this.pageY();if(_g<=this.tabLabelHeight){if(this.tabLabelAlign==='right'){_d=this.rect.width-_d;}
if(_d<=this.rightmostPx){var i=0,_f3;for(i;i<this.tabLabelBounds.length;i++){_f3=this.tabLabelBounds[i];if(_d<_f3[1]&&_d>=_f3[0]){this.selectTab(i);return;}}}}},removeTab:function(_p){var _64=this.selectIdx,_r3=this.tabs[_p],_T=this.tabViews[_p];this.tabs.splice(_p,1);this.tabLabels.splice(_p,1);this.tabLabelBounds.splice(_p,1);this.tabLabelStrings.splice(_p,1);if(_p===_64){this.selectIdx=-1;if(_p===0&&this.tabs.length===0){this.selectTab(-1);}
else if(_p===(this.tabs.length-1)){this.selectTab(_p-1);}
else{this.selectTab(_p);}}
else if(_p<_64){this.selectIdx--;}
ELEM.del(_T);HSystem.views[_r3].die();},draw:function(){var _P1=this.drawn;this.base();if(!_P1){this.drawMarkup();}
this.refresh();}});HTabItem={nu:function(_2,_b,_1){return _b.addTab(_1.label,_1.select);}};