
HDateTime=HClass.extend({msWeek:604800000,msDay:86400000,msHour:3600000,msMinute:60000,months_localized:['January','February','March','April','May','June','July','August','September','October','November','December'],monthName:function(date){date=(date instanceof Date)?date:this.date();return this.months_localized[date.getUTCMonth()];},week:function(date){date=(date instanceof Date)?date:this.date();var firstDateOfYear=this.firstDateOfYear(date),firstWeekOfYear=this.firstDateOfWeek(firstDateOfYear);if(firstWeekOfYear.getUTCDate()<=28){firstWeekOfYear=new Date(firstWeekOfYear.getTime()+this.msWeek-this.tzMs(firstWeekOfYear));}
var week=Math.ceil((((date.getTime()-firstWeekOfYear-this.tzMs(date))/this.msDay)+firstDateOfYear.getUTCDay()+1)/7);if((week===53)&&(this.firstDateOfWeek(this.lastDateOfYear(date)).getUTCDate()>28)){week=1;}
return week;},mday:function(date){date=(date instanceof Date)?date:this.date();return date.getUTCDate();},month:function(date){date=(date instanceof Date)?date:this.date();return date.getUTCMonth();},year:function(date){date=(date instanceof Date)?date:this.date();return date.getUTCFullYear();},tzMs:function(date){return date.getTimezoneOffset()*this.msMinute;},date:function(epoch_seconds){epoch_seconds=(typeof epoch_seconds==='number')?epoch_seconds:this.value;var date=new Date(epoch_seconds*1000);return date;},firstDateOfYear:function(date){date=(date instanceof Date)?date:this.date();var date1=new Date(date.getUTCFullYear(),0,1),date2=new Date(date1.getTime()-this.tzMs(date1));return date2;},lastDateOfYear:function(date){date=(date instanceof Date)?date:this.date();var date1=new Date(new Date(date.getUTCFullYear()+1,0,1)-1),date2=new Date(date1.getTime()-this.tzMs(date1));return date2;},firstDateOfMonth:function(date){date=(date instanceof Date)?date:this.date();var date1=new Date(date.getUTCFullYear(),date.getUTCMonth(),1),date2=new Date(date1.getTime()-this.tzMs(date1));return date2;},lastDateOfMonth:function(date){date=(date instanceof Date)?date:this.date();var date1=new Date(new Date(date.getUTCFullYear(),date.getUTCMonth()+1,1)-1),date2=new Date(date1.getTime()-this.tzMs(date1));return date2;},firstDateOfWeek:function(date){date=(date instanceof Date)?date:this.date();var wday=date.getUTCDay();if(wday===0){wday=7;}
var dateMs=((wday-1)*this.msDay),date1=new Date(date.getTime()-dateMs),date2=new Date(date1.getTime());return date2;},lastDateOfWeek:function(date){var firstDateOfWeek=this.firstDateOfWeek(date),lastDateOfWeek=new Date(firstDateOfWeek.getTime()+this.msWeek-this.msDay-1);return lastDateOfWeek;}});HCalendar=HControl.extend({componentName:'calendar',weekdays_localized:['Wk','Mon','Tue','Wed','Thu','Fri','Sat','Sun'],mouseWheel:function(delta){if(delta<0){this.nextMonth();}
else{this.prevMonth();}},refreshLabel:function(){var weekdays_localized=this.weekdays_localized,weekdays_width=Math.floor(this.rect.width/weekdays_localized.length),weekdays_html=[],i=0,weekdays_html_pre=['<div style="width:'+weekdays_width+'px;left:','px">'],weekdays_html_suf='</div>';for(;i<weekdays_localized.length;i++){weekdays_html.push([weekdays_html_pre.join(i*weekdays_width),weekdays_localized[i],weekdays_html_suf].join(''));}
ELEM.setHTML(this.markupElemIds.label,weekdays_html.join(''));},calendarDateRange:function(date){var date_begin=this.firstDateOfMonth(date),date_end=this.lastDateOfMonth(date),firstWeeksDate=this.firstDateOfWeek(date_begin),lastWeeksDate=this.lastDateOfWeek(date_end),week_begin=this.week(firstWeeksDate),week_end=this.week(lastWeeksDate),weeks=week_end-week_begin;if((weeks===5)&&(firstWeeksDate.getDate()!==1)){lastWeeksDate=new Date(lastWeeksDate.getTime()+this.msWeek);}
else if((weeks===5)&&(firstWeeksDate.getDate()===1)){firstWeeksDate=new Date(firstWeeksDate.getTime()-this.msWeek);}
else if(weeks===4){firstWeeksDate=new Date(firstWeeksDate.getTime()-this.msWeek);lastWeeksDate=new Date(lastWeeksDate.getTime()+this.msWeek);}
return[firstWeeksDate,lastWeeksDate];},refreshValue:function(){var date=this.date();this.drawCalendar(date);},nextMonth:function(){var date=new Date(this.viewMonth[0],this.viewMonth[1]+1,1);this.drawCalendar(new Date(date.getTime()-this.tzMs(date)));},prevMonth:function(){var date=new Date(this.viewMonth[0],this.viewMonth[1]-1,1);this.drawCalendar(new Date(date.getTime()-this.tzMs(date)));},viewMonth:[1970,0],drawCalendar:function(date){date=(date instanceof Date)?date:this.date();var calendarDateRange=this.calendarDateRange(date),monthFirst=this.firstDateOfMonth(date),monthLast=this.lastDateOfMonth(date),firstDate=calendarDateRange[0],lastDate=calendarDateRange[1],column_count=this.weekdays_localized.length,column_width=Math.floor((this.rect.width-1)/column_count),row_height=Math.floor((this.rect.height-1-35)/6),week_html_pre=['<div class="calendar_weeks_week_row" style="width:'+(this.rect.width-3)+'px;height:'+row_height+'px;top:','px">'],week_html_suf='</div>',col_html_pre=['<a href="javascript:HSystem.views['+this.viewId+'].setValue(',');" class="calendar_weeks_week_col','" style="width:'+column_width+'px;height:'+row_height+'px;line-height:'+row_height+'px;left:','px">'],col_html_suf='</a>',col_week_pre='<div class="calendar_weeks_week_col_wk" style="width:'+column_width+'px;height:'+row_height+'px;line-height:'+row_height+'px;left:0px">',col_week_suf='</div>',month_html=[],week_html,col_html,row,col,colMs,colSecs,colDate,extraCssClass;for(row=0;row<6;row++){week_html=[];for(col=0;col<8;col++){colDate=new Date(firstDate.getTime()+((row*this.msWeek)+((col-1)*this.msDay)));colMs=colDate.getTime();if(col===0){col_html=[col_week_pre,this.week(colDate),col_week_suf].join('');}
else{colSecs=Math.round(colMs/1000);if((this.value>=colSecs)&&(this.value<(colSecs+86400))){extraCssClass='_'+'sel';}
else{extraCssClass=(colDate<monthFirst||colDate>monthLast)?'_'+'no':'_'+'yes';}
col_html=[col_html_pre[0],colSecs,col_html_pre[1],extraCssClass,col_html_pre[2],(col*column_width),col_html_pre[3],this.mday(colDate),col_html_suf].join('');}
week_html.push(col_html);}
month_html.push([week_html_pre.join(row*row_height),week_html.join(''),week_html_suf].join(''));}
ELEM.setHTML(this.markupElemIds.value,month_html.join(''));ELEM.setHTML(this.markupElemIds.state,this.monthName(date)+'&nbsp;'+this.year(date));this.viewMonth=[monthFirst.getUTCFullYear(),monthFirst.getUTCMonth()];}});HCalendar.implement(HDateTime);HTimeSheet=HControl.extend({componentName:'timesheet',refreshLabel:function(){var hour=1,hours=[],rowHeight=24;for(;hour<24;hour++){hours.push('<div style="top:'+((hour-1)*rowHeight)+'px" class="timesheet_hours_row">'+hour+':00</div>');}
ELEM.setHTML(this.markupElemIds.label,hours.join(''));this.refreshState();},refreshState:function(){var line=0,lines=[],lineHeight=12;for(;line<48;line++){lines.push('<div style="top:'+(line*lineHeight)+'px" class="timesheet_lines_row'+(line%2)+'"></div>');}
ELEM.setHTML(this.markupElemIds.state,lines.join(''));},refreshValue:function(){for(var i=0;i<this.value.length;i++){}}});